import { 
  LucideIcon, 
  Plane, 
  Camera, 
  ChefHat, 
  Mountain, 
  Book, 
  Music, 
  Disc3,
  Trophy, 
  Dumbbell, 
  Palette, 
  Film, 
  Gamepad2, 
  Laptop, 
  Shirt, 
  UtensilsCrossed, 
  Trees, 
  PawPrint, 
  Clock, 
  Microscope, 
  Vote,
  Pencil,
  Paintbrush,
  PenTool,
  Mic,
  Music2,
  Sprout,
  Scissors,
  Puzzle,
  Heart,
  PersonStanding,
  Bike,
  FlowerIcon as Flower,
  Code,
  Languages,
  Landmark,
  BookOpen,
  Cookie,
  Wine,
  Coffee,
  Pizza,
  Drama,
  Tent,
  Waves,
  Fish,
  Coins,
  Car,
  Baby,
  GraduationCap,
  Stethoscope,
  Wrench,
  Hammer,
  Shirt as Sewing,
  TreePine,
  Bird,
  Camera as Photography2,
  Utensils,
  Sun,
  Moon,
  Sparkles,
  Leaf,
  Home,
  Target,
  Shield,
  TrendingUp,
  Scale,
  Compass,
  Users,
  Briefcase,
  HeartPulse,
  Lightbulb,
  CircleDot,
  HandHeart,
  Star,
  Smile,
  Globe,
  Zap,
  Award
} from 'lucide-react';

type IconMap = Record<string, LucideIcon>;

export const interestIcons: IconMap = {
  'Travel': Plane,
  'Photography': Camera,
  'Cooking': ChefHat,
  'Hiking': Mountain,
  'Reading': Book,
  'Music': Music,
  'Dancing': Disc3,
  'Sports': Trophy,
  'Fitness': Dumbbell,
  'Art': Palette,
  'Movies': Film,
  'Gaming': Gamepad2,
  'Technology': Laptop,
  'Fashion': Shirt,
  'Food': UtensilsCrossed,
  'Nature': Trees,
  'Animals': PawPrint,
  'History': Clock,
  'Science': Microscope,
  'Politics': Vote,
};

export const hobbyIcons: IconMap = {
  'Drawing': Pencil,
  'Painting': Paintbrush,
  'Writing': PenTool,
  'Singing': Mic,
  'Playing musical instruments': Music2,
  'Gardening': Sprout,
  'Crafting': Scissors,
  'Board games': Puzzle,
  'Video games': Gamepad2,
  'Yoga': Heart,
  'Running': PersonStanding,
  'Cycling': Bike,
  'Swimming': Waves,
  'Collecting': Coins,
  'Photography': Camera,
  'Cooking': ChefHat,
  'Baking': Cookie,
  'Wine tasting': Wine,
  'Coffee': Coffee,
  'Hiking': Mountain,
  'Camping': Tent,
  'Fishing': Fish,
  'Surfing': Waves,
  'Traveling': Plane,
  'Reading': BookOpen,
  'Watching movies': Film,
  'Theater': Drama,
  'Dancing': Disc3,
  'Volunteering': HandHeart,
  'Learning languages': Languages,
  'Coding': Code,
  'DIY projects': Wrench,
  'Woodworking': Hammer,
  'Sewing': Sewing,
  'Knitting': Scissors,
  'Pottery': Palette,
  'Calligraphy': PenTool,
  'Bird watching': Bird,
  'Stargazing': Moon,
  'Astronomy': Moon,
  'Meditation': CircleDot,
  'Martial arts': Trophy,
  'Rock climbing': Mountain,
  'Skateboarding': PersonStanding,
  'Roller skating': PersonStanding,
  'Archery': Target,
  'Bowling': Trophy,
  'Golfing': Trophy,
  'Tennis': Trophy,
  'Basketball': Trophy,
  'Soccer': Trophy,
  'Football': Trophy,
  'Baseball': Trophy,
  'Volleyball': Trophy,
  'Fashion design': Shirt,
  'Interior design': Home,
  'Graphic design': Palette,
  'Web design': Code,
  'Blogging': PenTool,
  'Vlogging': Film,
  'Podcasting': Mic,
  'Music production': Music2,
  'DJing': Music,
  'Singing karaoke': Mic,
  'Car restoration': Car,
  'Motorcycling': Bike,
  'Model building': Puzzle,
  'Genealogy': Users,
  'Antiquing': Clock,
};

export const valueIcons: IconMap = {
  'Honesty': Shield,
  'Kindness': Heart,
  'Personal growth': TrendingUp,
  'Work-life balance': Scale,
  'Adventure': Compass,
  'Family': Users,
  'Career success': Briefcase,
  'Health': HeartPulse,
  'Creativity': Lightbulb,
  'Spirituality': Sparkles,
  'Freedom': Bird,
  'Loyalty': HandHeart,
  'Integrity': Shield,
  'Compassion': Heart,
  'Respect': Award,
  'Responsibility': Target,
  'Humility': Leaf,
  'Gratitude': Star,
  'Optimism': Sun,
  'Courage': Shield,
  'Wisdom': BookOpen,
  'Justice': Scale,
  'Peace': CircleDot,
  'Harmony': Waves,
  'Authenticity': Smile,
  'Community': Users,
  'Environmentalism': Trees,
  'Education': GraduationCap,
  'Innovation': Lightbulb,
  'Tradition': Landmark,
  'Diversity': Globe,
  'Equality': Scale,
  'Passion': Zap,
  'Excellence': Award,
};

export const getIconForOption = (
  label: string,
  option: string
): LucideIcon | null => {
  const lowerLabel = label.toLowerCase();
  
  if (lowerLabel.includes('interest')) {
    return interestIcons[option] || Sparkles;
  }
  
  if (lowerLabel.includes('hobb')) {
    return hobbyIcons[option] || Coffee;
  }
  
  if (lowerLabel.includes('value')) {
    return valueIcons[option] || Heart;
  }
  
  return null;
};
