
import React, { useState } from 'react';
import { User, Sparkles, Wand2, Bot, Brain } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { useToast } from '@/hooks/use-toast';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';

interface ProfileBioProps {
  about: string;
  isMobile: boolean;
}

const ProfileBio: React.FC<ProfileBioProps> = ({ about, isMobile }) => {
  const [isSubscriber] = useState(false); // Mock subscription status
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedBio, setGeneratedBio] = useState<string>("");
  const { toast } = useToast();
  
  // Function to generate a bio based on profile information
  const generateBio = () => {
    setIsGenerating(true);
    
    // Simulate AI processing delay
    setTimeout(() => {
      const newBio = about || "Hi there! I'm a UX Designer with a passion for creating beautiful digital experiences. I love hiking in the mountains, trying new restaurants in San Francisco, and curling up with good books like The Alchemist. As a Libra with ENFJ personality, I value deep connections and communication. Looking for someone who shares my sense of adventure and appreciation for both the outdoors and quality time together.";
      setGeneratedBio(newBio);
      setIsGenerating(false);
      
      toast({
        title: "Bio Generated",
        description: "AI has created a personalized bio based on your profile.",
        variant: "default",
      });
    }, 1500);
  };

  const applyGeneratedBio = () => {
    toast({
      title: "Bio Applied",
      description: "Your profile has been updated with the AI-generated bio.",
      variant: "default",
    });
    // In a real app, this would update the profile in the database
  };

  return (
    <div className="mb-6 relative">
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-xl font-medium text-tinder-rose flex items-center">
          <User size={18} className="mr-2" />
          Bio
        </h3>
        <div className="flex items-center gap-2">
          <div className="text-xs bg-gradient-to-r from-tinder-rose to-tinder-orange bg-clip-text text-transparent font-medium flex items-center">
            <Bot size={14} className="mr-1 text-tinder-orange" />
            AI Generated
          </div>
          
          <Dialog>
            <DialogTrigger asChild>
              <Button 
                variant="outline" 
                size="sm" 
                className="text-xs border-tinder-rose text-tinder-rose hover:bg-tinder-rose/5 flex items-center gap-1 neo-border"
              >
                <Wand2 size={14} className="shimmer" />
                Regenerate Bio
              </Button>
            </DialogTrigger>
            <DialogContent className="neo-card bg-white/90 backdrop-blur-md">
              <DialogHeader>
                <DialogTitle className="ai-text-gradient flex items-center">
                  <Brain size={18} className="mr-2" />
                  AI Bio Generation
                </DialogTitle>
                <DialogDescription>
                  {isSubscriber ? (
                    <>
                      <p className="mb-4">Your profile bio is automatically generated by our AI by analyzing your profile information. You can regenerate it at any time.</p>
                      <div className="bg-gradient-to-r from-tinder-rose/5 to-tinder-orange/5 p-4 rounded-md border neo-border mb-4 relative">
                        {isGenerating ? (
                          <div className="flex flex-col items-center py-4 space-y-2">
                            <div className="relative w-8 h-8">
                              <div className="absolute inset-0 rounded-full bg-tinder-rose/20 animate-ping"></div>
                              <Brain size={24} className="text-tinder-rose relative z-10 ai-pulse" />
                            </div>
                            <p className="text-sm text-tinder-rose">Generating personalized bio...</p>
                          </div>
                        ) : (
                          <p className="text-sm font-medium">{generatedBio}</p>
                        )}
                      </div>
                      <Button 
                        className="w-full bg-gradient-to-r from-tinder-rose to-tinder-orange hover:from-tinder-rose/90 hover:to-tinder-orange/90 neo-glow"
                        onClick={isGenerating ? undefined : generatedBio ? applyGeneratedBio : generateBio}
                        disabled={isGenerating}
                      >
                        <Sparkles size={16} className="mr-2" />
                        {generatedBio ? "Apply Generated Bio" : "Regenerate Bio"}
                      </Button>
                    </>
                  ) : (
                    <>
                      <p className="mb-4">Premium users can regenerate their AI bio as many times as they want to get the perfect description.</p>
                      <div className="relative mb-4 overflow-hidden rounded-md border neo-border">
                        <div className="absolute inset-0 bg-gradient-to-r from-tinder-rose/10 to-tinder-orange/10 backdrop-blur-sm flex items-center justify-center">
                          <div className="text-center p-4">
                            <Bot size={24} className="mx-auto mb-2 text-tinder-rose" />
                            <p className="text-sm font-medium text-gray-600">Subscriber-only feature</p>
                          </div>
                        </div>
                        <div className="bg-gray-100 p-4 opacity-50">
                          <p className="text-sm">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae ipsum sed enim finibus ultrices.</p>
                        </div>
                      </div>
                      <Button className="w-full bg-gradient-to-r from-tinder-rose to-tinder-orange hover:from-tinder-rose/90 hover:to-tinder-orange/90 neo-glow">
                        <Sparkles size={16} className="mr-2" />
                        Upgrade to Premium
                      </Button>
                    </>
                  )}
                </DialogDescription>
              </DialogHeader>
            </DialogContent>
          </Dialog>
        </div>
      </div>
      <div className="backdrop-blur-md bg-black/5 border border-tinder-rose/20 p-5 rounded-2xl relative overflow-hidden shadow-lg">
        {/* AI-like decorative elements */}
        <div className="absolute -top-6 -right-6 w-12 h-12 bg-gradient-to-br from-tinder-rose/20 to-tinder-orange/20 rounded-full blur-xl"></div>
        <div className="absolute -bottom-4 -left-4 w-10 h-10 bg-gradient-to-br from-tinder-orange/30 to-tinder-rose/10 rounded-full blur-lg"></div>
        
        {/* Animated circuit pattern */}
        <div className="absolute inset-0 opacity-10">
          <div className="absolute top-0 left-0 w-full h-0.5 bg-gradient-to-r from-transparent via-tinder-rose/50 to-transparent"></div>
          <div className="absolute bottom-0 left-0 w-full h-0.5 bg-gradient-to-r from-transparent via-tinder-orange/50 to-transparent"></div>
          <div className="absolute top-0 left-0 h-full w-0.5 bg-gradient-to-b from-transparent via-tinder-rose/50 to-transparent"></div>
          <div className="absolute top-0 right-0 h-full w-0.5 bg-gradient-to-b from-transparent via-tinder-orange/50 to-transparent"></div>
        </div>
        
        <p className="text-muted-foreground leading-relaxed italic relative z-10 font-light">
          {about}
          <span className="absolute -bottom-1 -right-1 opacity-70">
            <Sparkles size={14} className="text-tinder-orange animate-pulse" />
          </span>
        </p>
        <div className="mt-3 flex items-center">
          <TooltipProvider>
            <Tooltip>
              <TooltipTrigger>
                <div className="flex items-center gap-1 text-xs text-tinder-rose/80">
                  <Bot size={12} className="text-tinder-orange" />
                  <span className="font-mono">AI_analyzed</span>
                </div>
              </TooltipTrigger>
              <TooltipContent side="top" className="backdrop-blur-md bg-black/40 border border-tinder-rose/30 text-white">
                <p className="text-xs">
                  AI automatically analyzes your profile data to create this personalized bio
                </p>
              </TooltipContent>
            </Tooltip>
          </TooltipProvider>
        </div>
      </div>
    </div>
  );
};

export default ProfileBio;
