
// Define types for profile data
export type KurdistanRegion = 'South-Kurdistan' | 'West-Kurdistan' | 'East-Kurdistan' | 'North-Kurdistan';

export interface ProfileData {
  name: string;
  age: number;
  location: string;
  occupation: string;
  lastActive: string;
  verified: boolean;
  profileImage: string;
  distance: number;
  kurdistanRegion: KurdistanRegion;
  bio: string;
  height: string;
  bodyType: string;
  ethnicity: string;
  religion: string;
  politicalViews: string;
  values: string[];
  interests: string[];
  hobbies: string[];
  languages: string[];
  education?: string;
  company?: string;
  relationshipGoals?: string;
  wantChildren?: string;
  havePets?: string;
  exerciseHabits?: string;
  zodiacSign?: string;
  personalityType?: string;
  sleepSchedule?: string;
  travelFrequency?: string;
  communicationStyle?: string;
  loveLanguage?: string;
  petPeeves?: string[] | string;
  dreamVacation?: string;
  weekendActivities?: string[] | string;
  financialHabits?: string;
  idealDate?: string;
  childrenStatus?: string;
  familyCloseness?: string;
  friendshipStyle?: string;
  workLifeBalance?: string;
  careerAmbitions?: string;
  dietaryPreferences?: string;
  favoriteQuote?: string;
  morningRoutine?: string;
  eveningRoutine?: string;
  favoriteSeason?: string;
  idealWeather?: string;
  creativePursuits?: string[] | string;
  dreamHome?: string;
  transportationPreference?: string;
  techSkills?: string[] | string;
  musicInstruments?: string[] | string;
  favoriteGames?: string[] | string;
  favoritePodcasts?: string[] | string;
  favoriteBooks?: string[] | string;
  favoriteMovies?: string[] | string;
  favoriteMusic?: string[] | string;
  favoriteFoods?: string[] | string;
  charityInvolvement?: string;
  growthGoals?: string[] | string;
  hiddenTalents?: string[] | string;
  favoriteMemory?: string;
  stressRelievers?: string[] | string;
  workEnvironment?: string;
  decisionMakingStyle?: string;
  smoking?: string;
  drinking?: string;
}
