-- Add Messages category translations
INSERT INTO app_translations (language_code, translation_key, translation_value, category, needs_review, auto_translated) VALUES
-- Messages - English
('english', 'message.send', 'Send', 'messages', false, false),
('english', 'message.type_message', 'Type a message...', 'messages', false, false),
('english', 'message.no_messages', 'No messages yet', 'messages', false, false),
('english', 'message.conversation_started', 'Conversation started', 'messages', false, false),
('english', 'message.online', 'Online', 'messages', false, false),
('english', 'message.offline', 'Offline', 'messages', false, false),
('english', 'message.typing', 'Typing...', 'messages', false, false),
('english', 'message.delivered', 'Delivered', 'messages', false, false),
('english', 'message.read', 'Read', 'messages', false, false),
('english', 'message.delete_conversation', 'Delete conversation', 'messages', false, false),
('english', 'message.block_user', 'Block user', 'messages', false, false),
('english', 'message.report_user', 'Report user', 'messages', false, false),
('english', 'message.unmatch', 'Unmatch', 'messages', false, false),
('english', 'message.send_photo', 'Send photo', 'messages', false, false),
('english', 'message.send_voice', 'Send voice message', 'messages', false, false),
('english', 'message.emoji_picker', 'Choose emoji', 'messages', false, false),
('english', 'message.search_conversations', 'Search conversations', 'messages', false, false),
('english', 'message.new_message', 'New message', 'messages', false, false),
('english', 'message.message_deleted', 'Message deleted', 'messages', false, false),
('english', 'message.cannot_send', 'Cannot send message', 'messages', false, false),

-- Messages - Kurdish
('kurdish', 'message.send', 'ناردن', 'messages', false, false),
('kurdish', 'message.type_message', 'نامەیەک بنووسە...', 'messages', false, false),
('kurdish', 'message.no_messages', 'هێشتا هیچ نامەیەک نییە', 'messages', false, false),
('kurdish', 'message.conversation_started', 'گفتوگۆ دەستی پێکرد', 'messages', false, false),
('kurdish', 'message.online', 'سەرهێڵ', 'messages', false, false),
('kurdish', 'message.offline', 'دەرهێڵ', 'messages', false, false),
('kurdish', 'message.typing', 'دەنووسێت...', 'messages', false, false),
('kurdish', 'message.delivered', 'گەیشت', 'messages', false, false),
('kurdish', 'message.read', 'خوێندراوە', 'messages', false, false),
('kurdish', 'message.delete_conversation', 'سڕینەوەی گفتوگۆ', 'messages', false, false),
('kurdish', 'message.block_user', 'بلۆککردنی بەکارهێنەر', 'messages', false, false),
('kurdish', 'message.report_user', 'گازەکردن لە بەکارهێنەر', 'messages', false, false),
('kurdish', 'message.unmatch', 'لابردنی هاوتا', 'messages', false, false),
('kurdish', 'message.send_photo', 'ناردنی وێنە', 'messages', false, false),
('kurdish', 'message.send_voice', 'ناردنی نامەی دەنگی', 'messages', false, false),
('kurdish', 'message.emoji_picker', 'هەڵبژاردنی ئیمۆجی', 'messages', false, false),
('kurdish', 'message.search_conversations', 'گەڕان لە گفتوگۆکان', 'messages', false, false),
('kurdish', 'message.new_message', 'نامەی نوێ', 'messages', false, false),
('kurdish', 'message.message_deleted', 'نامە سڕایەوە', 'messages', false, false),
('kurdish', 'message.cannot_send', 'ناتوانرێت نامە بنێردرێت', 'messages', false, false),

-- Messages - Arabic
('arabic', 'message.send', 'إرسال', 'messages', false, false),
('arabic', 'message.type_message', 'اكتب رسالة...', 'messages', false, false),
('arabic', 'message.no_messages', 'لا توجد رسائل بعد', 'messages', false, false),
('arabic', 'message.conversation_started', 'بدأت المحادثة', 'messages', false, false),
('arabic', 'message.online', 'متصل', 'messages', false, false),
('arabic', 'message.offline', 'غير متصل', 'messages', false, false),
('arabic', 'message.typing', 'يكتب...', 'messages', false, false),
('arabic', 'message.delivered', 'تم التسليم', 'messages', false, false),
('arabic', 'message.read', 'مقروء', 'messages', false, false),
('arabic', 'message.delete_conversation', 'حذف المحادثة', 'messages', false, false),
('arabic', 'message.block_user', 'حظر المستخدم', 'messages', false, false),
('arabic', 'message.report_user', 'الإبلاغ عن المستخدم', 'messages', false, false),
('arabic', 'message.unmatch', 'إلغاء المطابقة', 'messages', false, false),
('arabic', 'message.send_photo', 'إرسال صورة', 'messages', false, false),
('arabic', 'message.send_voice', 'إرسال رسالة صوتية', 'messages', false, false),
('arabic', 'message.emoji_picker', 'اختر رمز تعبيري', 'messages', false, false),
('arabic', 'message.search_conversations', 'البحث في المحادثات', 'messages', false, false),
('arabic', 'message.new_message', 'رسالة جديدة', 'messages', false, false),
('arabic', 'message.message_deleted', 'تم حذف الرسالة', 'messages', false, false),
('arabic', 'message.cannot_send', 'لا يمكن إرسال الرسالة', 'messages', false, false),

-- Messages - Turkish
('turkish', 'message.send', 'Gönder', 'messages', false, false),
('turkish', 'message.type_message', 'Mesaj yazın...', 'messages', false, false),
('turkish', 'message.no_messages', 'Henüz mesaj yok', 'messages', false, false),
('turkish', 'message.conversation_started', 'Sohbet başladı', 'messages', false, false),
('turkish', 'message.online', 'Çevrimiçi', 'messages', false, false),
('turkish', 'message.offline', 'Çevrimdışı', 'messages', false, false),
('turkish', 'message.typing', 'Yazıyor...', 'messages', false, false),
('turkish', 'message.delivered', 'İletildi', 'messages', false, false),
('turkish', 'message.read', 'Okundu', 'messages', false, false),
('turkish', 'message.delete_conversation', 'Sohbeti sil', 'messages', false, false),
('turkish', 'message.block_user', 'Kullanıcıyı engelle', 'messages', false, false),
('turkish', 'message.report_user', 'Kullanıcıyı bildir', 'messages', false, false),
('turkish', 'message.unmatch', 'Eşleşmeyi kaldır', 'messages', false, false),
('turkish', 'message.send_photo', 'Fotoğraf gönder', 'messages', false, false),
('turkish', 'message.send_voice', 'Sesli mesaj gönder', 'messages', false, false),
('turkish', 'message.emoji_picker', 'Emoji seç', 'messages', false, false),
('turkish', 'message.search_conversations', 'Sohbetlerde ara', 'messages', false, false),
('turkish', 'message.new_message', 'Yeni mesaj', 'messages', false, false),
('turkish', 'message.message_deleted', 'Mesaj silindi', 'messages', false, false),
('turkish', 'message.cannot_send', 'Mesaj gönderilemez', 'messages', false, false),

-- Messages - Persian
('persian', 'message.send', 'ارسال', 'messages', false, false),
('persian', 'message.type_message', 'پیام بنویسید...', 'messages', false, false),
('persian', 'message.no_messages', 'هنوز پیامی وجود ندارد', 'messages', false, false),
('persian', 'message.conversation_started', 'گفتگو شروع شد', 'messages', false, false),
('persian', 'message.online', 'آنلاین', 'messages', false, false),
('persian', 'message.offline', 'آفلاین', 'messages', false, false),
('persian', 'message.typing', 'در حال نوشتن...', 'messages', false, false),
('persian', 'message.delivered', 'تحویل داده شد', 'messages', false, false),
('persian', 'message.read', 'خوانده شده', 'messages', false, false),
('persian', 'message.delete_conversation', 'حذف گفتگو', 'messages', false, false),
('persian', 'message.block_user', 'مسدود کردن کاربر', 'messages', false, false),
('persian', 'message.report_user', 'گزارش کاربر', 'messages', false, false),
('persian', 'message.unmatch', 'حذف تطابق', 'messages', false, false),
('persian', 'message.send_photo', 'ارسال عکس', 'messages', false, false),
('persian', 'message.send_voice', 'ارسال پیام صوتی', 'messages', false, false),
('persian', 'message.emoji_picker', 'انتخاب شکلک', 'messages', false, false),
('persian', 'message.search_conversations', 'جستجو در گفتگوها', 'messages', false, false),
('persian', 'message.new_message', 'پیام جدید', 'messages', false, false),
('persian', 'message.message_deleted', 'پیام حذف شد', 'messages', false, false),
('persian', 'message.cannot_send', 'نمی‌توان پیام ارسال کرد', 'messages', false, false),

-- Discovery category translations
-- Discovery - English
('english', 'discovery.explore', 'Explore', 'discovery', false, false),
('english', 'discovery.nearby', 'Nearby', 'discovery', false, false),
('english', 'discovery.new_members', 'New Members', 'discovery', false, false),
('english', 'discovery.popular', 'Popular', 'discovery', false, false),
('english', 'discovery.verified_only', 'Verified Only', 'discovery', false, false),
('english', 'discovery.online_now', 'Online Now', 'discovery', false, false),
('english', 'discovery.recent_activity', 'Recent Activity', 'discovery', false, false),
('english', 'discovery.suggested_matches', 'Suggested Matches', 'discovery', false, false),
('english', 'discovery.load_more', 'Load More', 'discovery', false, false),
('english', 'discovery.no_results', 'No results found', 'discovery', false, false),
('english', 'discovery.filter_by', 'Filter By', 'discovery', false, false),
('english', 'discovery.sort_by', 'Sort By', 'discovery', false, false),
('english', 'discovery.distance', 'Distance', 'discovery', false, false),
('english', 'discovery.age_range', 'Age Range', 'discovery', false, false),
('english', 'discovery.show_me', 'Show Me', 'discovery', false, false),
('english', 'discovery.advanced_filters', 'Advanced Filters', 'discovery', false, false),
('english', 'discovery.reset_filters', 'Reset Filters', 'discovery', false, false),
('english', 'discovery.apply_filters', 'Apply Filters', 'discovery', false, false),
('english', 'discovery.save_search', 'Save Search', 'discovery', false, false),
('english', 'discovery.search_results', 'Search Results', 'discovery', false, false),

-- Discovery - Kurdish
('kurdish', 'discovery.explore', 'گەڕان', 'discovery', false, false),
('kurdish', 'discovery.nearby', 'نزیک', 'discovery', false, false),
('kurdish', 'discovery.new_members', 'ئەندامانی نوێ', 'discovery', false, false),
('kurdish', 'discovery.popular', 'بەناوبانگ', 'discovery', false, false),
('kurdish', 'discovery.verified_only', 'تەنها پشتڕاستکراوەکان', 'discovery', false, false),
('kurdish', 'discovery.online_now', 'ئێستا سەرهێڵە', 'discovery', false, false),
('kurdish', 'discovery.recent_activity', 'چالاکی تازە', 'discovery', false, false),
('kurdish', 'discovery.suggested_matches', 'هاوتاکانی پێشنیارکراو', 'discovery', false, false),
('kurdish', 'discovery.load_more', 'زیاتر بار بکە', 'discovery', false, false),
('kurdish', 'discovery.no_results', 'هیچ ئەنجامێک نەدۆزرایەوە', 'discovery', false, false),
('kurdish', 'discovery.filter_by', 'فلتەرکردن بە', 'discovery', false, false),
('kurdish', 'discovery.sort_by', 'ڕیزکردن بە', 'discovery', false, false),
('kurdish', 'discovery.distance', 'مەودا', 'discovery', false, false),
('kurdish', 'discovery.age_range', 'مەودای تەمەن', 'discovery', false, false),
('kurdish', 'discovery.show_me', 'پیشانم بدە', 'discovery', false, false),
('kurdish', 'discovery.advanced_filters', 'فلتەرە پێشکەوتووەکان', 'discovery', false, false),
('kurdish', 'discovery.reset_filters', 'ڕێکخستنەوەی فلتەرەکان', 'discovery', false, false),
('kurdish', 'discovery.apply_filters', 'جێبەجێکردنی فلتەرەکان', 'discovery', false, false),
('kurdish', 'discovery.save_search', 'پاشەکەوتکردنی گەڕان', 'discovery', false, false),
('kurdish', 'discovery.search_results', 'ئەنجامەکانی گەڕان', 'discovery', false, false),

-- Discovery - Arabic
('arabic', 'discovery.explore', 'استكشف', 'discovery', false, false),
('arabic', 'discovery.nearby', 'قريب', 'discovery', false, false),
('arabic', 'discovery.new_members', 'أعضاء جدد', 'discovery', false, false),
('arabic', 'discovery.popular', 'شائع', 'discovery', false, false),
('arabic', 'discovery.verified_only', 'موثق فقط', 'discovery', false, false),
('arabic', 'discovery.online_now', 'متصل الآن', 'discovery', false, false),
('arabic', 'discovery.recent_activity', 'النشاط الأخير', 'discovery', false, false),
('arabic', 'discovery.suggested_matches', 'مطابقات مقترحة', 'discovery', false, false),
('arabic', 'discovery.load_more', 'تحميل المزيد', 'discovery', false, false),
('arabic', 'discovery.no_results', 'لم يتم العثور على نتائج', 'discovery', false, false),
('arabic', 'discovery.filter_by', 'تصفية حسب', 'discovery', false, false),
('arabic', 'discovery.sort_by', 'ترتيب حسب', 'discovery', false, false),
('arabic', 'discovery.distance', 'المسافة', 'discovery', false, false),
('arabic', 'discovery.age_range', 'نطاق العمر', 'discovery', false, false),
('arabic', 'discovery.show_me', 'اعرض لي', 'discovery', false, false),
('arabic', 'discovery.advanced_filters', 'فلاتر متقدمة', 'discovery', false, false),
('arabic', 'discovery.reset_filters', 'إعادة تعيين الفلاتر', 'discovery', false, false),
('arabic', 'discovery.apply_filters', 'تطبيق الفلاتر', 'discovery', false, false),
('arabic', 'discovery.save_search', 'حفظ البحث', 'discovery', false, false),
('arabic', 'discovery.search_results', 'نتائج البحث', 'discovery', false, false),

-- Discovery - Turkish
('turkish', 'discovery.explore', 'Keşfet', 'discovery', false, false),
('turkish', 'discovery.nearby', 'Yakınımda', 'discovery', false, false),
('turkish', 'discovery.new_members', 'Yeni Üyeler', 'discovery', false, false),
('turkish', 'discovery.popular', 'Popüler', 'discovery', false, false),
('turkish', 'discovery.verified_only', 'Sadece Doğrulanmış', 'discovery', false, false),
('turkish', 'discovery.online_now', 'Şimdi Çevrimiçi', 'discovery', false, false),
('turkish', 'discovery.recent_activity', 'Son Etkinlik', 'discovery', false, false),
('turkish', 'discovery.suggested_matches', 'Önerilen Eşleşmeler', 'discovery', false, false),
('turkish', 'discovery.load_more', 'Daha Fazla Yükle', 'discovery', false, false),
('turkish', 'discovery.no_results', 'Sonuç bulunamadı', 'discovery', false, false),
('turkish', 'discovery.filter_by', 'Filtrele', 'discovery', false, false),
('turkish', 'discovery.sort_by', 'Sırala', 'discovery', false, false),
('turkish', 'discovery.distance', 'Mesafe', 'discovery', false, false),
('turkish', 'discovery.age_range', 'Yaş Aralığı', 'discovery', false, false),
('turkish', 'discovery.show_me', 'Göster', 'discovery', false, false),
('turkish', 'discovery.advanced_filters', 'Gelişmiş Filtreler', 'discovery', false, false),
('turkish', 'discovery.reset_filters', 'Filtreleri Sıfırla', 'discovery', false, false),
('turkish', 'discovery.apply_filters', 'Filtreleri Uygula', 'discovery', false, false),
('turkish', 'discovery.save_search', 'Aramayı Kaydet', 'discovery', false, false),
('turkish', 'discovery.search_results', 'Arama Sonuçları', 'discovery', false, false),

-- Discovery - Persian
('persian', 'discovery.explore', 'کاوش', 'discovery', false, false),
('persian', 'discovery.nearby', 'نزدیک', 'discovery', false, false),
('persian', 'discovery.new_members', 'اعضای جدید', 'discovery', false, false),
('persian', 'discovery.popular', 'محبوب', 'discovery', false, false),
('persian', 'discovery.verified_only', 'فقط تایید شده', 'discovery', false, false),
('persian', 'discovery.online_now', 'آنلاین الان', 'discovery', false, false),
('persian', 'discovery.recent_activity', 'فعالیت اخیر', 'discovery', false, false),
('persian', 'discovery.suggested_matches', 'تطابق‌های پیشنهادی', 'discovery', false, false),
('persian', 'discovery.load_more', 'بارگیری بیشتر', 'discovery', false, false),
('persian', 'discovery.no_results', 'نتیجه‌ای یافت نشد', 'discovery', false, false),
('persian', 'discovery.filter_by', 'فیلتر بر اساس', 'discovery', false, false),
('persian', 'discovery.sort_by', 'مرتب‌سازی بر اساس', 'discovery', false, false),
('persian', 'discovery.distance', 'فاصله', 'discovery', false, false),
('persian', 'discovery.age_range', 'محدوده سنی', 'discovery', false, false),
('persian', 'discovery.show_me', 'نمایش', 'discovery', false, false),
('persian', 'discovery.advanced_filters', 'فیلترهای پیشرفته', 'discovery', false, false),
('persian', 'discovery.reset_filters', 'بازنشانی فیلترها', 'discovery', false, false),
('persian', 'discovery.apply_filters', 'اعمال فیلترها', 'discovery', false, false),
('persian', 'discovery.save_search', 'ذخیره جستجو', 'discovery', false, false),
('persian', 'discovery.search_results', 'نتایج جستجو', 'discovery', false, false),

-- Profile category translations
-- Profile - English
('english', 'profile.edit_profile', 'Edit Profile', 'profile', false, false),
('english', 'profile.view_profile', 'View Profile', 'profile', false, false),
('english', 'profile.complete_profile', 'Complete Profile', 'profile', false, false),
('english', 'profile.profile_photo', 'Profile Photo', 'profile', false, false),
('english', 'profile.add_photo', 'Add Photo', 'profile', false, false),
('english', 'profile.delete_photo', 'Delete Photo', 'profile', false, false),
('english', 'profile.set_primary', 'Set as Primary', 'profile', false, false),
('english', 'profile.about_me', 'About Me', 'profile', false, false),
('english', 'profile.basic_info', 'Basic Info', 'profile', false, false),
('english', 'profile.lifestyle', 'Lifestyle', 'profile', false, false),
('english', 'profile.interests', 'Interests', 'profile', false, false),
('english', 'profile.preferences', 'Preferences', 'profile', false, false),
('english', 'profile.settings', 'Settings', 'profile', false, false),
('english', 'profile.privacy', 'Privacy', 'profile', false, false),
('english', 'profile.notifications', 'Notifications', 'profile', false, false),
('english', 'profile.account', 'Account', 'profile', false, false),
('english', 'profile.subscription', 'Subscription', 'profile', false, false),
('english', 'profile.help', 'Help', 'profile', false, false),
('english', 'profile.logout', 'Logout', 'profile', false, false),
('english', 'profile.delete_account', 'Delete Account', 'profile', false, false),
('english', 'profile.verify_profile', 'Verify Profile', 'profile', false, false),
('english', 'profile.share_profile', 'Share Profile', 'profile', false, false),
('english', 'profile.report_profile', 'Report Profile', 'profile', false, false),
('english', 'profile.block_profile', 'Block User', 'profile', false, false),
('english', 'profile.save_changes', 'Save Changes', 'profile', false, false),

-- Profile - Kurdish
('kurdish', 'profile.edit_profile', 'دەستکاریکردنی پرۆفایل', 'profile', false, false),
('kurdish', 'profile.view_profile', 'بینینی پرۆفایل', 'profile', false, false),
('kurdish', 'profile.complete_profile', 'تەواوکردنی پرۆفایل', 'profile', false, false),
('kurdish', 'profile.profile_photo', 'وێنەی پرۆفایل', 'profile', false, false),
('kurdish', 'profile.add_photo', 'زیادکردنی وێنە', 'profile', false, false),
('kurdish', 'profile.delete_photo', 'سڕینەوەی وێنە', 'profile', false, false),
('kurdish', 'profile.set_primary', 'دانان وەک سەرەکی', 'profile', false, false),
('kurdish', 'profile.about_me', 'دەربارەی من', 'profile', false, false),
('kurdish', 'profile.basic_info', 'زانیاری بنەڕەتی', 'profile', false, false),
('kurdish', 'profile.lifestyle', 'شێوازی ژیان', 'profile', false, false),
('kurdish', 'profile.interests', 'حەزەکان', 'profile', false, false),
('kurdish', 'profile.preferences', 'هەڵبژاردنەکان', 'profile', false, false),
('kurdish', 'profile.settings', 'ڕێکخستنەکان', 'profile', false, false),
('kurdish', 'profile.privacy', 'تایبەتمەندی', 'profile', false, false),
('kurdish', 'profile.notifications', 'ئاگادارکردنەوەکان', 'profile', false, false),
('kurdish', 'profile.account', 'هەژمار', 'profile', false, false),
('kurdish', 'profile.subscription', 'بەشداری', 'profile', false, false),
('kurdish', 'profile.help', 'یارمەتی', 'profile', false, false),
('kurdish', 'profile.logout', 'چوونەدەرەوە', 'profile', false, false),
('kurdish', 'profile.delete_account', 'سڕینەوەی هەژمار', 'profile', false, false),
('kurdish', 'profile.verify_profile', 'پشتڕاستکردنەوەی پرۆفایل', 'profile', false, false),
('kurdish', 'profile.share_profile', 'هاوبەشکردنی پرۆفایل', 'profile', false, false),
('kurdish', 'profile.report_profile', 'گازەکردن لە پرۆفایل', 'profile', false, false),
('kurdish', 'profile.block_profile', 'بلۆککردنی بەکارهێنەر', 'profile', false, false),
('kurdish', 'profile.save_changes', 'پاشەکەوتکردنی گۆڕانکاریەکان', 'profile', false, false),

-- Profile - Arabic
('arabic', 'profile.edit_profile', 'تعديل الملف الشخصي', 'profile', false, false),
('arabic', 'profile.view_profile', 'عرض الملف الشخصي', 'profile', false, false),
('arabic', 'profile.complete_profile', 'إكمال الملف الشخصي', 'profile', false, false),
('arabic', 'profile.profile_photo', 'صورة الملف الشخصي', 'profile', false, false),
('arabic', 'profile.add_photo', 'إضافة صورة', 'profile', false, false),
('arabic', 'profile.delete_photo', 'حذف الصورة', 'profile', false, false),
('arabic', 'profile.set_primary', 'تعيين كأساسي', 'profile', false, false),
('arabic', 'profile.about_me', 'نبذة عني', 'profile', false, false),
('arabic', 'profile.basic_info', 'المعلومات الأساسية', 'profile', false, false),
('arabic', 'profile.lifestyle', 'نمط الحياة', 'profile', false, false),
('arabic', 'profile.interests', 'الاهتمامات', 'profile', false, false),
('arabic', 'profile.preferences', 'التفضيلات', 'profile', false, false),
('arabic', 'profile.settings', 'الإعدادات', 'profile', false, false),
('arabic', 'profile.privacy', 'الخصوصية', 'profile', false, false),
('arabic', 'profile.notifications', 'الإشعارات', 'profile', false, false),
('arabic', 'profile.account', 'الحساب', 'profile', false, false),
('arabic', 'profile.subscription', 'الاشتراك', 'profile', false, false),
('arabic', 'profile.help', 'المساعدة', 'profile', false, false),
('arabic', 'profile.logout', 'تسجيل الخروج', 'profile', false, false),
('arabic', 'profile.delete_account', 'حذف الحساب', 'profile', false, false),
('arabic', 'profile.verify_profile', 'توثيق الملف الشخصي', 'profile', false, false),
('arabic', 'profile.share_profile', 'مشاركة الملف الشخصي', 'profile', false, false),
('arabic', 'profile.report_profile', 'الإبلاغ عن الملف الشخصي', 'profile', false, false),
('arabic', 'profile.block_profile', 'حظر المستخدم', 'profile', false, false),
('arabic', 'profile.save_changes', 'حفظ التغييرات', 'profile', false, false),

-- Profile - Turkish
('turkish', 'profile.edit_profile', 'Profili Düzenle', 'profile', false, false),
('turkish', 'profile.view_profile', 'Profili Görüntüle', 'profile', false, false),
('turkish', 'profile.complete_profile', 'Profili Tamamla', 'profile', false, false),
('turkish', 'profile.profile_photo', 'Profil Fotoğrafı', 'profile', false, false),
('turkish', 'profile.add_photo', 'Fotoğraf Ekle', 'profile', false, false),
('turkish', 'profile.delete_photo', 'Fotoğrafı Sil', 'profile', false, false),
('turkish', 'profile.set_primary', 'Ana Olarak Ayarla', 'profile', false, false),
('turkish', 'profile.about_me', 'Hakkımda', 'profile', false, false),
('turkish', 'profile.basic_info', 'Temel Bilgiler', 'profile', false, false),
('turkish', 'profile.lifestyle', 'Yaşam Tarzı', 'profile', false, false),
('turkish', 'profile.interests', 'İlgi Alanları', 'profile', false, false),
('turkish', 'profile.preferences', 'Tercihler', 'profile', false, false),
('turkish', 'profile.settings', 'Ayarlar', 'profile', false, false),
('turkish', 'profile.privacy', 'Gizlilik', 'profile', false, false),
('turkish', 'profile.notifications', 'Bildirimler', 'profile', false, false),
('turkish', 'profile.account', 'Hesap', 'profile', false, false),
('turkish', 'profile.subscription', 'Abonelik', 'profile', false, false),
('turkish', 'profile.help', 'Yardım', 'profile', false, false),
('turkish', 'profile.logout', 'Çıkış Yap', 'profile', false, false),
('turkish', 'profile.delete_account', 'Hesabı Sil', 'profile', false, false),
('turkish', 'profile.verify_profile', 'Profili Doğrula', 'profile', false, false),
('turkish', 'profile.share_profile', 'Profili Paylaş', 'profile', false, false),
('turkish', 'profile.report_profile', 'Profili Bildir', 'profile', false, false),
('turkish', 'profile.block_profile', 'Kullanıcıyı Engelle', 'profile', false, false),
('turkish', 'profile.save_changes', 'Değişiklikleri Kaydet', 'profile', false, false),

-- Profile - Persian
('persian', 'profile.edit_profile', 'ویرایش پروفایل', 'profile', false, false),
('persian', 'profile.view_profile', 'مشاهده پروفایل', 'profile', false, false),
('persian', 'profile.complete_profile', 'تکمیل پروفایل', 'profile', false, false),
('persian', 'profile.profile_photo', 'عکس پروفایل', 'profile', false, false),
('persian', 'profile.add_photo', 'افزودن عکس', 'profile', false, false),
('persian', 'profile.delete_photo', 'حذف عکس', 'profile', false, false),
('persian', 'profile.set_primary', 'تنظیم به عنوان اصلی', 'profile', false, false),
('persian', 'profile.about_me', 'درباره من', 'profile', false, false),
('persian', 'profile.basic_info', 'اطلاعات پایه', 'profile', false, false),
('persian', 'profile.lifestyle', 'سبک زندگی', 'profile', false, false),
('persian', 'profile.interests', 'علایق', 'profile', false, false),
('persian', 'profile.preferences', 'ترجیحات', 'profile', false, false),
('persian', 'profile.settings', 'تنظیمات', 'profile', false, false),
('persian', 'profile.privacy', 'حریم خصوصی', 'profile', false, false),
('persian', 'profile.notifications', 'اعلان‌ها', 'profile', false, false),
('persian', 'profile.account', 'حساب کاربری', 'profile', false, false),
('persian', 'profile.subscription', 'اشتراک', 'profile', false, false),
('persian', 'profile.help', 'راهنما', 'profile', false, false),
('persian', 'profile.logout', 'خروج', 'profile', false, false),
('persian', 'profile.delete_account', 'حذف حساب', 'profile', false, false),
('persian', 'profile.verify_profile', 'تایید پروفایل', 'profile', false, false),
('persian', 'profile.share_profile', 'اشتراک‌گذاری پروفایل', 'profile', false, false),
('persian', 'profile.report_profile', 'گزارش پروفایل', 'profile', false, false),
('persian', 'profile.block_profile', 'مسدود کردن کاربر', 'profile', false, false),
('persian', 'profile.save_changes', 'ذخیره تغییرات', 'profile', false, false)

ON CONFLICT (language_code, translation_key) DO NOTHING;