-- Create comprehensive profile for lalo.peshawa@gmail.com
INSERT INTO public.profiles (
  id,
  name,
  age,
  gender,
  location,
  kurdistan_region,
  occupation,
  company,
  height,
  body_type,
  ethnicity,
  religion,
  political_views,
  education,
  relationship_goals,
  want_children,
  exercise_habits,
  dietary_preferences,
  smoking,
  drinking,
  sleep_schedule,
  have_pets,
  travel_frequency,
  communication_style,
  love_language,
  work_environment,
  family_closeness,
  ideal_date,
  career_ambitions,
  work_life_balance,
  zodiac_sign,
  personality_type,
  values,
  interests,
  hobbies,
  creative_pursuits,
  weekend_activities,
  languages,
  bio,
  profile_image,
  verified,
  last_active
) VALUES (
  'ebd61474-e0a3-44e2-b6b2-76003985ec9d',
  'Lalo Peshawa',
  28,
  'male',
  'Erbil, Kurdistan',
  'South-Kurdistan',
  'Software Engineer',
  'Tech Kurdistan',
  '5''10"',
  'Athletic',
  'Kurdish',
  'Islam',
  'Progressive',
  'Bachelor''s Degree',
  'Looking for something serious',
  'Want children someday',
  'Regular exercise',
  'Halal',
  'Non-smoker',
  'Social drinker',
  'Early bird',
  'Love pets but don''t have any',
  'Frequent traveler',
  'Direct and honest',
  'Quality Time',
  'Remote worker',
  'Very close',
  'Coffee and conversation',
  'Start own business',
  'Balanced approach',
  'Leo',
  'ENFJ',
  ARRAY['Family', 'Kurdish heritage', 'Honesty', 'Community', 'Education', 'Freedom'],
  ARRAY['Kurdish music', 'Poetry', 'Literature', 'Cultural events', 'Technology', 'Travel'],
  ARRAY['Reading', 'Programming', 'Photography', 'Hiking', 'Music', 'Learning languages'],
  ARRAY['Photography', 'Music production', 'Writing'],
  ARRAY['Family gatherings', 'Cultural events', 'Outdoor activities'],
  ARRAY['Kurdish', 'English', 'Arabic', 'Turkish'],
  'Proud Kurdish software engineer who values family, heritage, and building meaningful connections. Passionate about technology and cultural preservation. Looking for someone who shares similar values and appreciates our rich Kurdish culture.',
  'https://randomuser.me/api/portraits/men/1.jpg',
  true,
  NOW()
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  age = EXCLUDED.age,
  gender = EXCLUDED.gender,
  location = EXCLUDED.location,
  kurdistan_region = EXCLUDED.kurdistan_region,
  occupation = EXCLUDED.occupation,
  company = EXCLUDED.company,
  height = EXCLUDED.height,
  body_type = EXCLUDED.body_type,
  ethnicity = EXCLUDED.ethnicity,
  religion = EXCLUDED.religion,
  political_views = EXCLUDED.political_views,
  education = EXCLUDED.education,
  relationship_goals = EXCLUDED.relationship_goals,
  want_children = EXCLUDED.want_children,
  exercise_habits = EXCLUDED.exercise_habits,
  dietary_preferences = EXCLUDED.dietary_preferences,
  smoking = EXCLUDED.smoking,
  drinking = EXCLUDED.drinking,
  sleep_schedule = EXCLUDED.sleep_schedule,
  have_pets = EXCLUDED.have_pets,
  travel_frequency = EXCLUDED.travel_frequency,
  communication_style = EXCLUDED.communication_style,
  love_language = EXCLUDED.love_language,
  work_environment = EXCLUDED.work_environment,
  family_closeness = EXCLUDED.family_closeness,
  ideal_date = EXCLUDED.ideal_date,
  career_ambitions = EXCLUDED.career_ambitions,
  work_life_balance = EXCLUDED.work_life_balance,
  zodiac_sign = EXCLUDED.zodiac_sign,
  personality_type = EXCLUDED.personality_type,
  values = EXCLUDED.values,
  interests = EXCLUDED.interests,
  hobbies = EXCLUDED.hobbies,
  creative_pursuits = EXCLUDED.creative_pursuits,
  weekend_activities = EXCLUDED.weekend_activities,
  languages = EXCLUDED.languages,
  bio = EXCLUDED.bio,
  profile_image = EXCLUDED.profile_image,
  verified = EXCLUDED.verified,
  last_active = EXCLUDED.last_active;

-- Add profile photos for complete basic info
INSERT INTO public.photos (
  profile_id,
  url,
  is_primary
) VALUES 
  ('ebd61474-e0a3-44e2-b6b2-76003985ec9d', 'https://randomuser.me/api/portraits/men/1.jpg', true),
  ('ebd61474-e0a3-44e2-b6b2-76003985ec9d', 'https://randomuser.me/api/portraits/men/2.jpg', false),
  ('ebd61474-e0a3-44e2-b6b2-76003985ec9d', 'https://randomuser.me/api/portraits/men/3.jpg', false)
ON CONFLICT DO NOTHING;