-- Add Settings category translations
INSERT INTO app_translations (language_code, translation_key, translation_value, category, needs_review, auto_translated) VALUES
-- Settings - English
('english', 'settings.general', 'General Settings', 'settings', false, false),
('english', 'settings.account_settings', 'Account Settings', 'settings', false, false),
('english', 'settings.privacy_settings', 'Privacy Settings', 'settings', false, false),
('english', 'settings.notification_settings', 'Notification Settings', 'settings', false, false),
('english', 'settings.language', 'Language', 'settings', false, false),
('english', 'settings.change_password', 'Change Password', 'settings', false, false),
('english', 'settings.change_email', 'Change Email', 'settings', false, false),
('english', 'settings.deactivate_account', 'Deactivate Account', 'settings', false, false),
('english', 'settings.data_privacy', 'Data & Privacy', 'settings', false, false),
('english', 'settings.blocked_users', 'Blocked Users', 'settings', false, false),
('english', 'settings.who_can_see_profile', 'Who can see my profile', 'settings', false, false),
('english', 'settings.who_can_message', 'Who can message me', 'settings', false, false),
('english', 'settings.show_online_status', 'Show online status', 'settings', false, false),
('english', 'settings.show_distance', 'Show my distance', 'settings', false, false),
('english', 'settings.show_age', 'Show my age', 'settings', false, false),
('english', 'settings.discovery_settings', 'Discovery Settings', 'settings', false, false),
('english', 'settings.max_distance', 'Maximum Distance', 'settings', false, false),
('english', 'settings.age_preference', 'Age Preference', 'settings', false, false),
('english', 'settings.verify_account', 'Verify Your Account', 'settings', false, false),
('english', 'settings.connected_accounts', 'Connected Accounts', 'settings', false, false),

-- Settings - Kurdish
('kurdish', 'settings.general', 'ڕێکخستنە گشتیەکان', 'settings', false, false),
('kurdish', 'settings.account_settings', 'ڕێکخستنەکانی هەژمار', 'settings', false, false),
('kurdish', 'settings.privacy_settings', 'ڕێکخستنەکانی تایبەتمەندی', 'settings', false, false),
('kurdish', 'settings.notification_settings', 'ڕێکخستنەکانی ئاگادارکردنەوە', 'settings', false, false),
('kurdish', 'settings.language', 'زمان', 'settings', false, false),
('kurdish', 'settings.change_password', 'گۆڕینی وشەی نهێنی', 'settings', false, false),
('kurdish', 'settings.change_email', 'گۆڕینی ئیمەیڵ', 'settings', false, false),
('kurdish', 'settings.deactivate_account', 'ناچالاککردنی هەژمار', 'settings', false, false),
('kurdish', 'settings.data_privacy', 'داتا و تایبەتمەندی', 'settings', false, false),
('kurdish', 'settings.blocked_users', 'بەکارهێنەرە بلۆککراوەکان', 'settings', false, false),
('kurdish', 'settings.who_can_see_profile', 'کێ دەتوانێت پرۆفایلم ببینێت', 'settings', false, false),
('kurdish', 'settings.who_can_message', 'کێ دەتوانێت نامەم بۆ بنێرێت', 'settings', false, false),
('kurdish', 'settings.show_online_status', 'پیشاندانی دۆخی سەرهێڵ', 'settings', false, false),
('kurdish', 'settings.show_distance', 'پیشاندانی مەوداکەم', 'settings', false, false),
('kurdish', 'settings.show_age', 'پیشاندانی تەمەنم', 'settings', false, false),
('kurdish', 'settings.discovery_settings', 'ڕێکخستنەکانی دۆزینەوە', 'settings', false, false),
('kurdish', 'settings.max_distance', 'زۆرترین مەودا', 'settings', false, false),
('kurdish', 'settings.age_preference', 'هەڵبژاردنی تەمەن', 'settings', false, false),
('kurdish', 'settings.verify_account', 'پشتڕاستکردنەوەی هەژمارەکەت', 'settings', false, false),
('kurdish', 'settings.connected_accounts', 'هەژمارە بەستراوەکان', 'settings', false, false),

-- Settings - Arabic
('arabic', 'settings.general', 'الإعدادات العامة', 'settings', false, false),
('arabic', 'settings.account_settings', 'إعدادات الحساب', 'settings', false, false),
('arabic', 'settings.privacy_settings', 'إعدادات الخصوصية', 'settings', false, false),
('arabic', 'settings.notification_settings', 'إعدادات الإشعارات', 'settings', false, false),
('arabic', 'settings.language', 'اللغة', 'settings', false, false),
('arabic', 'settings.change_password', 'تغيير كلمة المرور', 'settings', false, false),
('arabic', 'settings.change_email', 'تغيير البريد الإلكتروني', 'settings', false, false),
('arabic', 'settings.deactivate_account', 'تعطيل الحساب', 'settings', false, false),
('arabic', 'settings.data_privacy', 'البيانات والخصوصية', 'settings', false, false),
('arabic', 'settings.blocked_users', 'المستخدمون المحظورون', 'settings', false, false),
('arabic', 'settings.who_can_see_profile', 'من يمكنه رؤية ملفي الشخصي', 'settings', false, false),
('arabic', 'settings.who_can_message', 'من يمكنه مراسلتي', 'settings', false, false),
('arabic', 'settings.show_online_status', 'إظهار حالة الاتصال', 'settings', false, false),
('arabic', 'settings.show_distance', 'إظهار المسافة', 'settings', false, false),
('arabic', 'settings.show_age', 'إظهار العمر', 'settings', false, false),
('arabic', 'settings.discovery_settings', 'إعدادات الاكتشاف', 'settings', false, false),
('arabic', 'settings.max_distance', 'المسافة القصوى', 'settings', false, false),
('arabic', 'settings.age_preference', 'تفضيل العمر', 'settings', false, false),
('arabic', 'settings.verify_account', 'تحقق من حسابك', 'settings', false, false),
('arabic', 'settings.connected_accounts', 'الحسابات المتصلة', 'settings', false, false),

-- Settings - Turkish
('turkish', 'settings.general', 'Genel Ayarlar', 'settings', false, false),
('turkish', 'settings.account_settings', 'Hesap Ayarları', 'settings', false, false),
('turkish', 'settings.privacy_settings', 'Gizlilik Ayarları', 'settings', false, false),
('turkish', 'settings.notification_settings', 'Bildirim Ayarları', 'settings', false, false),
('turkish', 'settings.language', 'Dil', 'settings', false, false),
('turkish', 'settings.change_password', 'Şifreyi Değiştir', 'settings', false, false),
('turkish', 'settings.change_email', 'E-postayı Değiştir', 'settings', false, false),
('turkish', 'settings.deactivate_account', 'Hesabı Devre Dışı Bırak', 'settings', false, false),
('turkish', 'settings.data_privacy', 'Veri ve Gizlilik', 'settings', false, false),
('turkish', 'settings.blocked_users', 'Engellenen Kullanıcılar', 'settings', false, false),
('turkish', 'settings.who_can_see_profile', 'Profilimi kim görebilir', 'settings', false, false),
('turkish', 'settings.who_can_message', 'Bana kim mesaj gönderebilir', 'settings', false, false),
('turkish', 'settings.show_online_status', 'Çevrimiçi durumu göster', 'settings', false, false),
('turkish', 'settings.show_distance', 'Mesafemi göster', 'settings', false, false),
('turkish', 'settings.show_age', 'Yaşımı göster', 'settings', false, false),
('turkish', 'settings.discovery_settings', 'Keşif Ayarları', 'settings', false, false),
('turkish', 'settings.max_distance', 'Maksimum Mesafe', 'settings', false, false),
('turkish', 'settings.age_preference', 'Yaş Tercihi', 'settings', false, false),
('turkish', 'settings.verify_account', 'Hesabını Doğrula', 'settings', false, false),
('turkish', 'settings.connected_accounts', 'Bağlı Hesaplar', 'settings', false, false),

-- Settings - Persian
('persian', 'settings.general', 'تنظیمات عمومی', 'settings', false, false),
('persian', 'settings.account_settings', 'تنظیمات حساب', 'settings', false, false),
('persian', 'settings.privacy_settings', 'تنظیمات حریم خصوصی', 'settings', false, false),
('persian', 'settings.notification_settings', 'تنظیمات اعلان‌ها', 'settings', false, false),
('persian', 'settings.language', 'زبان', 'settings', false, false),
('persian', 'settings.change_password', 'تغییر رمز عبور', 'settings', false, false),
('persian', 'settings.change_email', 'تغییر ایمیل', 'settings', false, false),
('persian', 'settings.deactivate_account', 'غیرفعال کردن حساب', 'settings', false, false),
('persian', 'settings.data_privacy', 'داده و حریم خصوصی', 'settings', false, false),
('persian', 'settings.blocked_users', 'کاربران مسدود شده', 'settings', false, false),
('persian', 'settings.who_can_see_profile', 'چه کسی می‌تواند پروفایلم را ببیند', 'settings', false, false),
('persian', 'settings.who_can_message', 'چه کسی می‌تواند پیام بفرستد', 'settings', false, false),
('persian', 'settings.show_online_status', 'نمایش وضعیت آنلاین', 'settings', false, false),
('persian', 'settings.show_distance', 'نمایش فاصله من', 'settings', false, false),
('persian', 'settings.show_age', 'نمایش سن من', 'settings', false, false),
('persian', 'settings.discovery_settings', 'تنظیمات کشف', 'settings', false, false),
('persian', 'settings.max_distance', 'حداکثر فاصله', 'settings', false, false),
('persian', 'settings.age_preference', 'ترجیح سنی', 'settings', false, false),
('persian', 'settings.verify_account', 'تایید حساب خود', 'settings', false, false),
('persian', 'settings.connected_accounts', 'حساب‌های متصل', 'settings', false, false),

-- Notifications category translations
-- Notifications - English
('english', 'notifications.new_match', 'New Match!', 'notifications', false, false),
('english', 'notifications.new_message', 'New Message', 'notifications', false, false),
('english', 'notifications.new_like', 'Someone liked you!', 'notifications', false, false),
('english', 'notifications.profile_view', 'viewed your profile', 'notifications', false, false),
('english', 'notifications.mark_all_read', 'Mark all as read', 'notifications', false, false),
('english', 'notifications.no_notifications', 'No notifications yet', 'notifications', false, false),
('english', 'notifications.turn_on', 'Turn on notifications', 'notifications', false, false),
('english', 'notifications.turn_off', 'Turn off notifications', 'notifications', false, false),
('english', 'notifications.push_notifications', 'Push Notifications', 'notifications', false, false),
('english', 'notifications.email_notifications', 'Email Notifications', 'notifications', false, false),
('english', 'notifications.message_notifications', 'Message Notifications', 'notifications', false, false),
('english', 'notifications.match_notifications', 'Match Notifications', 'notifications', false, false),
('english', 'notifications.like_notifications', 'Like Notifications', 'notifications', false, false),
('english', 'notifications.view_all', 'View All Notifications', 'notifications', false, false),
('english', 'notifications.clear_all', 'Clear All', 'notifications', false, false),

-- Notifications - Kurdish
('kurdish', 'notifications.new_match', 'هاوتای نوێ!', 'notifications', false, false),
('kurdish', 'notifications.new_message', 'نامەی نوێ', 'notifications', false, false),
('kurdish', 'notifications.new_like', 'کەسێک حەزی لێت کردووە!', 'notifications', false, false),
('kurdish', 'notifications.profile_view', 'پرۆفایلەکەتی بینیوە', 'notifications', false, false),
('kurdish', 'notifications.mark_all_read', 'نیشانکردنی هەموو وەک خوێندراوە', 'notifications', false, false),
('kurdish', 'notifications.no_notifications', 'هێشتا هیچ ئاگادارکردنەوەیەک نییە', 'notifications', false, false),
('kurdish', 'notifications.turn_on', 'چالاککردنی ئاگادارکردنەوەکان', 'notifications', false, false),
('kurdish', 'notifications.turn_off', 'ناچالاککردنی ئاگادارکردنەوەکان', 'notifications', false, false),
('kurdish', 'notifications.push_notifications', 'ئاگادارکردنەوە پاڵپشتیەکان', 'notifications', false, false),
('kurdish', 'notifications.email_notifications', 'ئاگادارکردنەوەی ئیمەیڵ', 'notifications', false, false),
('kurdish', 'notifications.message_notifications', 'ئاگادارکردنەوەی نامە', 'notifications', false, false),
('kurdish', 'notifications.match_notifications', 'ئاگادارکردنەوەی هاوتا', 'notifications', false, false),
('kurdish', 'notifications.like_notifications', 'ئاگادارکردنەوەی حەز', 'notifications', false, false),
('kurdish', 'notifications.view_all', 'بینینی هەموو ئاگادارکردنەوەکان', 'notifications', false, false),
('kurdish', 'notifications.clear_all', 'پاککردنەوەی هەموو', 'notifications', false, false),

-- Notifications - Arabic
('arabic', 'notifications.new_match', 'مطابقة جديدة!', 'notifications', false, false),
('arabic', 'notifications.new_message', 'رسالة جديدة', 'notifications', false, false),
('arabic', 'notifications.new_like', 'شخص ما أعجب بك!', 'notifications', false, false),
('arabic', 'notifications.profile_view', 'شاهد ملفك الشخصي', 'notifications', false, false),
('arabic', 'notifications.mark_all_read', 'وضع علامة مقروء على الكل', 'notifications', false, false),
('arabic', 'notifications.no_notifications', 'لا توجد إشعارات بعد', 'notifications', false, false),
('arabic', 'notifications.turn_on', 'تشغيل الإشعارات', 'notifications', false, false),
('arabic', 'notifications.turn_off', 'إيقاف الإشعارات', 'notifications', false, false),
('arabic', 'notifications.push_notifications', 'الإشعارات الفورية', 'notifications', false, false),
('arabic', 'notifications.email_notifications', 'إشعارات البريد الإلكتروني', 'notifications', false, false),
('arabic', 'notifications.message_notifications', 'إشعارات الرسائل', 'notifications', false, false),
('arabic', 'notifications.match_notifications', 'إشعارات المطابقة', 'notifications', false, false),
('arabic', 'notifications.like_notifications', 'إشعارات الإعجاب', 'notifications', false, false),
('arabic', 'notifications.view_all', 'عرض جميع الإشعارات', 'notifications', false, false),
('arabic', 'notifications.clear_all', 'مسح الكل', 'notifications', false, false),

-- Notifications - Turkish
('turkish', 'notifications.new_match', 'Yeni Eşleşme!', 'notifications', false, false),
('turkish', 'notifications.new_message', 'Yeni Mesaj', 'notifications', false, false),
('turkish', 'notifications.new_like', 'Birisi seni beğendi!', 'notifications', false, false),
('turkish', 'notifications.profile_view', 'profilini görüntüledi', 'notifications', false, false),
('turkish', 'notifications.mark_all_read', 'Tümünü okundu işaretle', 'notifications', false, false),
('turkish', 'notifications.no_notifications', 'Henüz bildirim yok', 'notifications', false, false),
('turkish', 'notifications.turn_on', 'Bildirimleri aç', 'notifications', false, false),
('turkish', 'notifications.turn_off', 'Bildirimleri kapat', 'notifications', false, false),
('turkish', 'notifications.push_notifications', 'Anlık Bildirimler', 'notifications', false, false),
('turkish', 'notifications.email_notifications', 'E-posta Bildirimleri', 'notifications', false, false),
('turkish', 'notifications.message_notifications', 'Mesaj Bildirimleri', 'notifications', false, false),
('turkish', 'notifications.match_notifications', 'Eşleşme Bildirimleri', 'notifications', false, false),
('turkish', 'notifications.like_notifications', 'Beğeni Bildirimleri', 'notifications', false, false),
('turkish', 'notifications.view_all', 'Tüm Bildirimleri Görüntüle', 'notifications', false, false),
('turkish', 'notifications.clear_all', 'Tümünü Temizle', 'notifications', false, false),

-- Notifications - Persian
('persian', 'notifications.new_match', 'تطابق جدید!', 'notifications', false, false),
('persian', 'notifications.new_message', 'پیام جدید', 'notifications', false, false),
('persian', 'notifications.new_like', 'کسی شما را پسندید!', 'notifications', false, false),
('persian', 'notifications.profile_view', 'پروفایل شما را دید', 'notifications', false, false),
('persian', 'notifications.mark_all_read', 'علامت‌گذاری همه به عنوان خوانده شده', 'notifications', false, false),
('persian', 'notifications.no_notifications', 'هنوز اعلانی وجود ندارد', 'notifications', false, false),
('persian', 'notifications.turn_on', 'روشن کردن اعلان‌ها', 'notifications', false, false),
('persian', 'notifications.turn_off', 'خاموش کردن اعلان‌ها', 'notifications', false, false),
('persian', 'notifications.push_notifications', 'اعلان‌های فوری', 'notifications', false, false),
('persian', 'notifications.email_notifications', 'اعلان‌های ایمیل', 'notifications', false, false),
('persian', 'notifications.message_notifications', 'اعلان‌های پیام', 'notifications', false, false),
('persian', 'notifications.match_notifications', 'اعلان‌های تطابق', 'notifications', false, false),
('persian', 'notifications.like_notifications', 'اعلان‌های لایک', 'notifications', false, false),
('persian', 'notifications.view_all', 'مشاهده همه اعلان‌ها', 'notifications', false, false),
('persian', 'notifications.clear_all', 'پاک کردن همه', 'notifications', false, false),

-- Social/Community category translations
-- Social - English
('english', 'social.share', 'Share', 'common', false, false),
('english', 'social.comment', 'Comment', 'common', false, false),
('english', 'social.like', 'Like', 'common', false, false),
('english', 'social.unlike', 'Unlike', 'common', false, false),
('english', 'social.follow', 'Follow', 'common', false, false),
('english', 'social.unfollow', 'Unfollow', 'common', false, false),
('english', 'social.followers', 'Followers', 'common', false, false),
('english', 'social.following', 'Following', 'common', false, false),
('english', 'social.posts', 'Posts', 'common', false, false),
('english', 'social.create_post', 'Create Post', 'common', false, false),
('english', 'social.delete_post', 'Delete Post', 'common', false, false),
('english', 'social.edit_post', 'Edit Post', 'common', false, false),
('english', 'social.report_post', 'Report Post', 'common', false, false),
('english', 'social.add_comment', 'Add a comment...', 'common', false, false),
('english', 'social.view_comments', 'View Comments', 'common', false, false),

-- Social - Kurdish
('kurdish', 'social.share', 'هاوبەشکردن', 'common', false, false),
('kurdish', 'social.comment', 'کۆمێنت', 'common', false, false),
('kurdish', 'social.like', 'حەز', 'common', false, false),
('kurdish', 'social.unlike', 'لابردنی حەز', 'common', false, false),
('kurdish', 'social.follow', 'شوێنکەوتن', 'common', false, false),
('kurdish', 'social.unfollow', 'لابردنی شوێنکەوتن', 'common', false, false),
('kurdish', 'social.followers', 'شوێنکەوتووان', 'common', false, false),
('kurdish', 'social.following', 'شوێنکەوتن', 'common', false, false),
('kurdish', 'social.posts', 'پۆستەکان', 'common', false, false),
('kurdish', 'social.create_post', 'دروستکردنی پۆست', 'common', false, false),
('kurdish', 'social.delete_post', 'سڕینەوەی پۆست', 'common', false, false),
('kurdish', 'social.edit_post', 'دەستکاریکردنی پۆست', 'common', false, false),
('kurdish', 'social.report_post', 'گازەکردن لە پۆست', 'common', false, false),
('kurdish', 'social.add_comment', 'کۆمێنتێک زیاد بکە...', 'common', false, false),
('kurdish', 'social.view_comments', 'بینینی کۆمێنتەکان', 'common', false, false),

-- Social - Arabic
('arabic', 'social.share', 'مشاركة', 'common', false, false),
('arabic', 'social.comment', 'تعليق', 'common', false, false),
('arabic', 'social.like', 'إعجاب', 'common', false, false),
('arabic', 'social.unlike', 'إلغاء الإعجاب', 'common', false, false),
('arabic', 'social.follow', 'متابعة', 'common', false, false),
('arabic', 'social.unfollow', 'إلغاء المتابعة', 'common', false, false),
('arabic', 'social.followers', 'المتابعون', 'common', false, false),
('arabic', 'social.following', 'يتابع', 'common', false, false),
('arabic', 'social.posts', 'المنشورات', 'common', false, false),
('arabic', 'social.create_post', 'إنشاء منشور', 'common', false, false),
('arabic', 'social.delete_post', 'حذف المنشور', 'common', false, false),
('arabic', 'social.edit_post', 'تعديل المنشور', 'common', false, false),
('arabic', 'social.report_post', 'الإبلاغ عن المنشور', 'common', false, false),
('arabic', 'social.add_comment', 'أضف تعليقاً...', 'common', false, false),
('arabic', 'social.view_comments', 'عرض التعليقات', 'common', false, false),

-- Social - Turkish
('turkish', 'social.share', 'Paylaş', 'common', false, false),
('turkish', 'social.comment', 'Yorum', 'common', false, false),
('turkish', 'social.like', 'Beğen', 'common', false, false),
('turkish', 'social.unlike', 'Beğenmeyi Kaldır', 'common', false, false),
('turkish', 'social.follow', 'Takip Et', 'common', false, false),
('turkish', 'social.unfollow', 'Takibi Bırak', 'common', false, false),
('turkish', 'social.followers', 'Takipçiler', 'common', false, false),
('turkish', 'social.following', 'Takip Edilen', 'common', false, false),
('turkish', 'social.posts', 'Gönderiler', 'common', false, false),
('turkish', 'social.create_post', 'Gönderi Oluştur', 'common', false, false),
('turkish', 'social.delete_post', 'Gönderiyi Sil', 'common', false, false),
('turkish', 'social.edit_post', 'Gönderiyi Düzenle', 'common', false, false),
('turkish', 'social.report_post', 'Gönderiyi Bildir', 'common', false, false),
('turkish', 'social.add_comment', 'Yorum ekle...', 'common', false, false),
('turkish', 'social.view_comments', 'Yorumları Görüntüle', 'common', false, false),

-- Social - Persian
('persian', 'social.share', 'اشتراک‌گذاری', 'common', false, false),
('persian', 'social.comment', 'نظر', 'common', false, false),
('persian', 'social.like', 'پسندیدن', 'common', false, false),
('persian', 'social.unlike', 'حذف پسند', 'common', false, false),
('persian', 'social.follow', 'دنبال کردن', 'common', false, false),
('persian', 'social.unfollow', 'لغو دنبال کردن', 'common', false, false),
('persian', 'social.followers', 'دنبال‌کنندگان', 'common', false, false),
('persian', 'social.following', 'دنبال‌شده', 'common', false, false),
('persian', 'social.posts', 'پست‌ها', 'common', false, false),
('persian', 'social.create_post', 'ایجاد پست', 'common', false, false),
('persian', 'social.delete_post', 'حذف پست', 'common', false, false),
('persian', 'social.edit_post', 'ویرایش پست', 'common', false, false),
('persian', 'social.report_post', 'گزارش پست', 'common', false, false),
('persian', 'social.add_comment', 'نظر اضافه کنید...', 'common', false, false),
('persian', 'social.view_comments', 'مشاهده نظرات', 'common', false, false)

ON CONFLICT (language_code, translation_key) DO NOTHING;