-- Phase 1: Core User Flows - Auth, Swipe, Navigation
-- Using ON CONFLICT DO NOTHING to skip existing keys

-- ============================================
-- AUTHENTICATION TRANSLATIONS
-- ============================================

INSERT INTO app_translations (language_code, translation_key, translation_value, category, context) VALUES
-- English - Login
('english', 'auth.login.title', 'Welcome Back', 'auth', 'Login page title'),
('english', 'auth.login.subtitle', 'Sign in to your account', 'auth', 'Login page subtitle'),
('english', 'auth.login.email', 'Email', 'auth', 'Email field label'),
('english', 'auth.login.password', 'Password', 'auth', 'Password field label'),
('english', 'auth.login.remember_me', 'Remember me', 'auth', 'Remember me checkbox'),
('english', 'auth.login.forgot_password', 'Forgot password?', 'auth', 'Forgot password link'),
('english', 'auth.login.button', 'Sign in', 'auth', 'Login button'),
('english', 'auth.login.button_loading', 'Signing in...', 'auth', 'Login button loading state'),
('english', 'auth.login.or_continue_with', 'Or continue with', 'auth', 'OAuth divider text'),
('english', 'auth.login.no_account', 'Don''t have an account?', 'auth', 'Link to registration'),
('english', 'auth.login.sign_up', 'Sign up', 'auth', 'Link to registration'),
('english', 'auth.login.success', 'You have been logged in successfully', 'auth', 'Login success toast'),
('english', 'auth.login.error', 'Failed to log in. Please try again.', 'auth', 'Login error toast'),

-- Kurdish Sorani - Login
('kurdish_sorani', 'auth.login.title', 'بەخێربێیتەوە', 'auth', 'Login page title'),
('kurdish_sorani', 'auth.login.subtitle', 'بچۆرە ژوورەوە بۆ هەژمارەکەت', 'auth', 'Login page subtitle'),
('kurdish_sorani', 'auth.login.email', 'ئیمەیڵ', 'auth', 'Email field label'),
('kurdish_sorani', 'auth.login.password', 'وشەی نهێنی', 'auth', 'Password field label'),
('kurdish_sorani', 'auth.login.remember_me', 'لەبیرم بێت', 'auth', 'Remember me checkbox'),
('kurdish_sorani', 'auth.login.forgot_password', 'وشەی نهێنیت لەبیر چووە؟', 'auth', 'Forgot password link'),
('kurdish_sorani', 'auth.login.button', 'چوونەژوورەوە', 'auth', 'Login button'),
('kurdish_sorani', 'auth.login.button_loading', 'چوونەژوورەوە...', 'auth', 'Login button loading state'),
('kurdish_sorani', 'auth.login.or_continue_with', 'یان بەردەوام بە لەگەڵ', 'auth', 'OAuth divider text'),
('kurdish_sorani', 'auth.login.no_account', 'هەژمارت نییە؟', 'auth', 'Link to registration'),
('kurdish_sorani', 'auth.login.sign_up', 'خۆتۆمارکردن', 'auth', 'Link to registration'),
('kurdish_sorani', 'auth.login.success', 'بە سەرکەوتوویی چوویتە ژوورەوە', 'auth', 'Login success toast'),
('kurdish_sorani', 'auth.login.error', 'چوونەژوورەوە سەرکەوتوو نەبوو. تکایە دووبارە هەوڵ بدەرەوە.', 'auth', 'Login error toast'),

-- Kurdish Kurmanci - Login  
('kurdish_kurmanci', 'auth.login.title', 'Bi xêr hatî', 'auth', 'Login page title'),
('kurdish_kurmanci', 'auth.login.subtitle', 'Têkevin hesabê xwe', 'auth', 'Login page subtitle'),
('kurdish_kurmanci', 'auth.login.email', 'E-mail', 'auth', 'Email field label'),
('kurdish_kurmanci', 'auth.login.password', 'Şîfre', 'auth', 'Password field label'),
('kurdish_kurmanci', 'auth.login.remember_me', 'Min bi bîr bîne', 'auth', 'Remember me checkbox'),
('kurdish_kurmanci', 'auth.login.forgot_password', 'Şîfreya xwe ji bîr kir?', 'auth', 'Forgot password link'),
('kurdish_kurmanci', 'auth.login.button', 'Têkevin', 'auth', 'Login button'),
('kurdish_kurmanci', 'auth.login.button_loading', 'Têkevin...', 'auth', 'Login button loading state'),
('kurdish_kurmanci', 'auth.login.or_continue_with', 'Yan jî bi', 'auth', 'OAuth divider text'),
('kurdish_kurmanci', 'auth.login.no_account', 'Hesabê we tune ye?', 'auth', 'Link to registration'),
('kurdish_kurmanci', 'auth.login.sign_up', 'Têketin', 'auth', 'Link to registration'),
('kurdish_kurmanci', 'auth.login.success', 'Hûn bi serkeftî têketin', 'auth', 'Login success toast'),
('kurdish_kurmanci', 'auth.login.error', 'Têketin têk çû. Ji kerema xwe dîsa biceribîne.', 'auth', 'Login error toast'),

-- Norwegian - Login
('norwegian', 'auth.login.title', 'Velkommen tilbake', 'auth', 'Login page title'),
('norwegian', 'auth.login.subtitle', 'Logg inn på kontoen din', 'auth', 'Login page subtitle'),
('norwegian', 'auth.login.email', 'E-post', 'auth', 'Email field label'),
('norwegian', 'auth.login.password', 'Passord', 'auth', 'Password field label'),
('norwegian', 'auth.login.remember_me', 'Husk meg', 'auth', 'Remember me checkbox'),
('norwegian', 'auth.login.forgot_password', 'Glemt passord?', 'auth', 'Forgot password link'),
('norwegian', 'auth.login.button', 'Logg inn', 'auth', 'Login button'),
('norwegian', 'auth.login.button_loading', 'Logger inn...', 'auth', 'Login button loading state'),
('norwegian', 'auth.login.or_continue_with', 'Eller fortsett med', 'auth', 'OAuth divider text'),
('norwegian', 'auth.login.no_account', 'Har du ikke en konto?', 'auth', 'Link to registration'),
('norwegian', 'auth.login.sign_up', 'Registrer deg', 'auth', 'Link to registration'),
('norwegian', 'auth.login.success', 'Du har logget inn', 'auth', 'Login success toast'),
('norwegian', 'auth.login.error', 'Kunne ikke logge inn. Vennligst prøv igjen.', 'auth', 'Login error toast'),

-- German - Login
('german', 'auth.login.title', 'Willkommen zurück', 'auth', 'Login page title'),
('german', 'auth.login.subtitle', 'Melden Sie sich bei Ihrem Konto an', 'auth', 'Login page subtitle'),
('german', 'auth.login.email', 'E-Mail', 'auth', 'Email field label'),
('german', 'auth.login.password', 'Passwort', 'auth', 'Password field label'),
('german', 'auth.login.remember_me', 'Angemeldet bleiben', 'auth', 'Remember me checkbox'),
('german', 'auth.login.forgot_password', 'Passwort vergessen?', 'auth', 'Forgot password link'),
('german', 'auth.login.button', 'Anmelden', 'auth', 'Login button'),
('german', 'auth.login.button_loading', 'Anmelden...', 'auth', 'Login button loading state'),
('german', 'auth.login.or_continue_with', 'Oder fortfahren mit', 'auth', 'OAuth divider text'),
('german', 'auth.login.no_account', 'Noch kein Konto?', 'auth', 'Link to registration'),
('german', 'auth.login.sign_up', 'Registrieren', 'auth', 'Link to registration'),
('german', 'auth.login.success', 'Sie haben sich erfolgreich angemeldet', 'auth', 'Login success toast'),
('german', 'auth.login.error', 'Anmeldung fehlgeschlagen. Bitte versuchen Sie es erneut.', 'auth', 'Login error toast'),

-- English - Registration
('english', 'auth.register.title', 'Create Account', 'auth', 'Registration page title'),
('english', 'auth.register.subtitle', 'Join KurdMatch Today', 'auth', 'Registration page subtitle'),
('english', 'auth.register.first_name', 'First Name', 'auth', 'First name field'),
('english', 'auth.register.last_name', 'Last Name', 'auth', 'Last name field'),
('english', 'auth.register.email', 'Email', 'auth', 'Email field'),
('english', 'auth.register.password', 'Password', 'auth', 'Password field'),
('english', 'auth.register.confirm_password', 'Confirm Password', 'auth', 'Confirm password field'),
('english', 'auth.register.button', 'Create Account', 'auth', 'Register button'),
('english', 'auth.register.button_loading', 'Creating account...', 'auth', 'Register button loading'),
('english', 'auth.register.terms', 'By signing up, you agree to our Terms of Service and Privacy Policy', 'auth', 'Terms agreement text'),
('english', 'auth.register.have_account', 'Already have an account?', 'auth', 'Link to login'),
('english', 'auth.register.sign_in', 'Sign in', 'auth', 'Link to login'),
('english', 'auth.register.success', 'Account created successfully!', 'auth', 'Registration success'),
('english', 'auth.register.error', 'Failed to create account. Please try again.', 'auth', 'Registration error'),

-- Kurdish Sorani - Registration
('kurdish_sorani', 'auth.register.title', 'دروستکردنی هەژمار', 'auth', 'Registration page title'),
('kurdish_sorani', 'auth.register.subtitle', 'ئەمڕۆ بەشداری کوردماچ بکە', 'auth', 'Registration page subtitle'),
('kurdish_sorani', 'auth.register.first_name', 'ناوی یەکەم', 'auth', 'First name field'),
('kurdish_sorani', 'auth.register.last_name', 'ناوی دووەم', 'auth', 'Last name field'),
('kurdish_sorani', 'auth.register.email', 'ئیمەیڵ', 'auth', 'Email field'),
('kurdish_sorani', 'auth.register.password', 'وشەی نهێنی', 'auth', 'Password field'),
('kurdish_sorani', 'auth.register.confirm_password', 'دووبارەکردنەوەی وشەی نهێنی', 'auth', 'Confirm password field'),
('kurdish_sorani', 'auth.register.button', 'دروستکردنی هەژمار', 'auth', 'Register button'),
('kurdish_sorani', 'auth.register.button_loading', 'دروستکردنی هەژمار...', 'auth', 'Register button loading'),
('kurdish_sorani', 'auth.register.terms', 'بە خۆتۆمارکردن، تۆ ڕەزامەندیت لەسەر مەرجەکانی خزمەتگوزاری و سیاسەتی تایبەتێتی', 'auth', 'Terms agreement text'),
('kurdish_sorani', 'auth.register.have_account', 'هەژمارت هەیە؟', 'auth', 'Link to login'),
('kurdish_sorani', 'auth.register.sign_in', 'چوونەژوورەوە', 'auth', 'Link to login'),
('kurdish_sorani', 'auth.register.success', 'هەژمار بە سەرکەوتوویی دروست کرا!', 'auth', 'Registration success'),
('kurdish_sorani', 'auth.register.error', 'دروستکردنی هەژمار سەرکەوتوو نەبوو. تکایە دووبارە هەوڵ بدەرەوە.', 'auth', 'Registration error'),

-- Kurdish Kurmanci - Registration
('kurdish_kurmanci', 'auth.register.title', 'Hesab biafirîne', 'auth', 'Registration page title'),
('kurdish_kurmanci', 'auth.register.subtitle', 'Îro beşdarî KurdMatch bibe', 'auth', 'Registration page subtitle'),
('kurdish_kurmanci', 'auth.register.first_name', 'Navê yekem', 'auth', 'First name field'),
('kurdish_kurmanci', 'auth.register.last_name', 'Paşnav', 'auth', 'Last name field'),
('kurdish_kurmanci', 'auth.register.email', 'E-mail', 'auth', 'Email field'),
('kurdish_kurmanci', 'auth.register.password', 'Şîfre', 'auth', 'Password field'),
('kurdish_kurmanci', 'auth.register.confirm_password', 'Şîfreyê bipejirîne', 'auth', 'Confirm password field'),
('kurdish_kurmanci', 'auth.register.button', 'Hesab biafirîne', 'auth', 'Register button'),
('kurdish_kurmanci', 'auth.register.button_loading', 'Hesab tê afirandin...', 'auth', 'Register button loading'),
('kurdish_kurmanci', 'auth.register.terms', 'Bi xwe tomarkirin, hûn mercên karûbarê me û siyaseta me ya taybetiyê qebûl dikin', 'auth', 'Terms agreement text'),
('kurdish_kurmanci', 'auth.register.have_account', 'Hesabê we heye?', 'auth', 'Link to login'),
('kurdish_kurmanci', 'auth.register.sign_in', 'Têkevin', 'auth', 'Link to login'),
('kurdish_kurmanci', 'auth.register.success', 'Hesab bi serkeftî hate afirandin!', 'auth', 'Registration success'),
('kurdish_kurmanci', 'auth.register.error', 'Afirîna hesabê têk çû. Ji kerema xwe dîsa biceribîne.', 'auth', 'Registration error'),

-- Norwegian - Registration
('norwegian', 'auth.register.title', 'Opprett konto', 'auth', 'Registration page title'),
('norwegian', 'auth.register.subtitle', 'Bli med i KurdMatch i dag', 'auth', 'Registration page subtitle'),
('norwegian', 'auth.register.first_name', 'Fornavn', 'auth', 'First name field'),
('norwegian', 'auth.register.last_name', 'Etternavn', 'auth', 'Last name field'),
('norwegian', 'auth.register.email', 'E-post', 'auth', 'Email field'),
('norwegian', 'auth.register.password', 'Passord', 'auth', 'Password field'),
('norwegian', 'auth.register.confirm_password', 'Bekreft passord', 'auth', 'Confirm password field'),
('norwegian', 'auth.register.button', 'Opprett konto', 'auth', 'Register button'),
('norwegian', 'auth.register.button_loading', 'Oppretter konto...', 'auth', 'Register button loading'),
('norwegian', 'auth.register.terms', 'Ved å registrere deg godtar du våre tjenestevilkår og personvernregler', 'auth', 'Terms agreement text'),
('norwegian', 'auth.register.have_account', 'Har du allerede en konto?', 'auth', 'Link to login'),
('norwegian', 'auth.register.sign_in', 'Logg inn', 'auth', 'Link to login'),
('norwegian', 'auth.register.success', 'Konto opprettet!', 'auth', 'Registration success'),
('norwegian', 'auth.register.error', 'Kunne ikke opprette konto. Vennligst prøv igjen.', 'auth', 'Registration error'),

-- German - Registration
('german', 'auth.register.title', 'Konto erstellen', 'auth', 'Registration page title'),
('german', 'auth.register.subtitle', 'Werden Sie heute Mitglied bei KurdMatch', 'auth', 'Registration page subtitle'),
('german', 'auth.register.first_name', 'Vorname', 'auth', 'First name field'),
('german', 'auth.register.last_name', 'Nachname', 'auth', 'Last name field'),
('german', 'auth.register.email', 'E-Mail', 'auth', 'Email field'),
('german', 'auth.register.password', 'Passwort', 'auth', 'Password field'),
('german', 'auth.register.confirm_password', 'Passwort bestätigen', 'auth', 'Confirm password field'),
('german', 'auth.register.button', 'Konto erstellen', 'auth', 'Register button'),
('german', 'auth.register.button_loading', 'Konto wird erstellt...', 'auth', 'Register button loading'),
('german', 'auth.register.terms', 'Mit der Registrierung stimmen Sie unseren Nutzungsbedingungen und Datenschutzrichtlinien zu', 'auth', 'Terms agreement text'),
('german', 'auth.register.have_account', 'Sie haben bereits ein Konto?', 'auth', 'Link to login'),
('german', 'auth.register.sign_in', 'Anmelden', 'auth', 'Link to login'),
('german', 'auth.register.success', 'Konto erfolgreich erstellt!', 'auth', 'Registration success'),
('german', 'auth.register.error', 'Konto konnte nicht erstellt werden. Bitte versuchen Sie es erneut.', 'auth', 'Registration error')

ON CONFLICT (language_code, translation_key) DO NOTHING;