-- Update ethnicity field options with comprehensive Kurdish list
UPDATE registration_questions
SET field_options = ARRAY[
  'Kurdish – Kurmanji',
  'Kurdish – Sorani',
  'Kurdish – Zaza / Dimili',
  'Kurdish – Other',
  'Kurdish – Arab',
  'Kurdish – Turkish',
  'Kurdish – Persian / Iranian',
  'Kurdish – Assyrian / Armenian',
  'Kurdish – Caucasian',
  'Kurdish – German',
  'Kurdish – French',
  'Kurdish – Dutch',
  'Kurdish – Belgian',
  'Kurdish – Swiss',
  'Kurdish – Austrian',
  'Kurdish – Luxembourgish',
  'Kurdish – Swedish',
  'Kurdish – Norwegian',
  'Kurdish – Danish',
  'Kurdish – Finnish',
  'Kurdish – Icelandic',
  'Kurdish – Italian',
  'Kurdish – Spanish',
  'Kurdish – Portuguese',
  'Kurdish – Greek',
  'Kurdish – Maltese',
  'Kurdish – Polish',
  'Kurdish – Czech',
  'Kurdish – Slovak',
  'Kurdish – Hungarian',
  'Kurdish – Romanian',
  'Kurdish – Bulgarian',
  'Kurdish – Serbian',
  'Kurdish – Bosnian',
  'Kurdish – Croatian',
  'Kurdish – Albanian',
  'Kurdish – Slovenian',
  'Kurdish – Ukrainian',
  'Kurdish – Russian',
  'Kurdish – British',
  'Kurdish – Scottish',
  'Kurdish – Welsh',
  'Kurdish – Irish',
  'Kurdish – Central Asian',
  'Kurdish – African',
  'Kurdish – American / Canadian / Australian',
  'Kurdish – Other Mixed',
  'Arab',
  'Turkish',
  'Persian / Iranian',
  'Assyrian / Armenian',
  'Caucasian',
  'European',
  'Central Asian',
  'African',
  'Other / Prefer not to say'
]
WHERE profile_field = 'ethnicity';

-- Update height field options to CM only (145-210 cm)
UPDATE registration_questions
SET field_options = ARRAY[
  '145 cm', '146 cm', '147 cm', '148 cm', '149 cm', '150 cm',
  '151 cm', '152 cm', '153 cm', '154 cm', '155 cm', '156 cm',
  '157 cm', '158 cm', '159 cm', '160 cm', '161 cm', '162 cm',
  '163 cm', '164 cm', '165 cm', '166 cm', '167 cm', '168 cm',
  '169 cm', '170 cm', '171 cm', '172 cm', '173 cm', '174 cm',
  '175 cm', '176 cm', '177 cm', '178 cm', '179 cm', '180 cm',
  '181 cm', '182 cm', '183 cm', '184 cm', '185 cm', '186 cm',
  '187 cm', '188 cm', '189 cm', '190 cm', '191 cm', '192 cm',
  '193 cm', '194 cm', '195 cm', '196 cm', '197 cm', '198 cm',
  '199 cm', '200 cm', '201 cm', '202 cm', '203 cm', '204 cm',
  '205 cm', '206 cm', '207 cm', '208 cm', '209 cm', '210 cm'
]
WHERE profile_field = 'height';