-- Phase 1 Continuation: Validation & Error Messages

INSERT INTO app_translations (language_code, translation_key, translation_value, category, context) VALUES
-- English - Validation Messages
('english', 'validation.email.required', 'Email is required', 'validation', 'Email validation'),
('english', 'validation.email.invalid', 'Invalid email format', 'validation', 'Email validation'),
('english', 'validation.password.required', 'Password is required', 'validation', 'Password validation'),
('english', 'validation.password.min', 'Password must be at least 8 characters', 'validation', 'Password validation'),
('english', 'validation.password.uppercase', 'Password must contain at least one uppercase letter', 'validation', 'Password validation'),
('english', 'validation.password.lowercase', 'Password must contain at least one lowercase letter', 'validation', 'Password validation'),
('english', 'validation.password.number', 'Password must contain at least one number', 'validation', 'Password validation'),
('english', 'validation.password.mismatch', 'Passwords don''t match', 'validation', 'Password validation'),
('english', 'validation.name.required', 'Name is required', 'validation', 'Name validation'),
('english', 'validation.name.min', 'Name must be at least 2 characters', 'validation', 'Name validation'),
('english', 'validation.bio.min', 'Bio must be at least 20 characters', 'validation', 'Bio validation'),
('english', 'validation.bio.max', 'Bio cannot exceed 500 characters', 'validation', 'Bio validation'),
('english', 'validation.age.min', 'You must be at least 18 years old', 'validation', 'Age validation'),
('english', 'validation.photo.required', 'At least one photo is required', 'validation', 'Photo validation'),
('english', 'validation.interests.min', 'Please select at least 3 interests', 'validation', 'Interests validation'),
('english', 'validation.values.min', 'Please select at least 3 values', 'validation', 'Values validation'),
('english', 'validation.field.required', 'This field is required', 'validation', 'Generic field validation'),

-- Kurdish Sorani - Validation Messages
('kurdish_sorani', 'validation.email.required', 'ئیمەیڵ پێویستە', 'validation', 'Email validation'),
('kurdish_sorani', 'validation.email.invalid', 'فۆرماتی ئیمەیڵ نادروستە', 'validation', 'Email validation'),
('kurdish_sorani', 'validation.password.required', 'وشەی نهێنی پێویستە', 'validation', 'Password validation'),
('kurdish_sorani', 'validation.password.min', 'وشەی نهێنی دەبێت لانیکەم ٨ پیت بێت', 'validation', 'Password validation'),
('kurdish_sorani', 'validation.password.uppercase', 'وشەی نهێنی دەبێت لانیکەم یەک پیتی گەورە هەبێت', 'validation', 'Password validation'),
('kurdish_sorani', 'validation.password.lowercase', 'وشەی نهێنی دەبێت لانیکەم یەک پیتی بچووک هەبێت', 'validation', 'Password validation'),
('kurdish_sorani', 'validation.password.number', 'وشەی نهێنی دەبێت لانیکەم یەک ژمارە هەبێت', 'validation', 'Password validation'),
('kurdish_sorani', 'validation.password.mismatch', 'وشەکانی نهێنی یەکناگرنەوە', 'validation', 'Password validation'),
('kurdish_sorani', 'validation.name.required', 'ناو پێویستە', 'validation', 'Name validation'),
('kurdish_sorani', 'validation.name.min', 'ناو دەبێت لانیکەم ٢ پیت بێت', 'validation', 'Name validation'),
('kurdish_sorani', 'validation.bio.min', 'بایۆ دەبێت لانیکەم ٢٠ پیت بێت', 'validation', 'Bio validation'),
('kurdish_sorani', 'validation.bio.max', 'بایۆ ناتوانێت لە ٥٠٠ پیت زیاتر بێت', 'validation', 'Bio validation'),
('kurdish_sorani', 'validation.age.min', 'دەبێت لانیکەم ١٨ ساڵت بێت', 'validation', 'Age validation'),
('kurdish_sorani', 'validation.photo.required', 'لانیکەم یەک وێنە پێویستە', 'validation', 'Photo validation'),
('kurdish_sorani', 'validation.interests.min', 'تکایە لانیکەم ٣ حەزت هەڵبژێرە', 'validation', 'Interests validation'),
('kurdish_sorani', 'validation.values.min', 'تکایە لانیکەم ٣ بەهات هەڵبژێرە', 'validation', 'Values validation'),
('kurdish_sorani', 'validation.field.required', 'ئەم خانەیە پێویستە', 'validation', 'Generic field validation'),

-- Kurdish Kurmanci - Validation Messages
('kurdish_kurmanci', 'validation.email.required', 'E-mail pêwîst e', 'validation', 'Email validation'),
('kurdish_kurmanci', 'validation.email.invalid', 'Formata e-mailê nederbasdar e', 'validation', 'Email validation'),
('kurdish_kurmanci', 'validation.password.required', 'Şîfre pêwîst e', 'validation', 'Password validation'),
('kurdish_kurmanci', 'validation.password.min', 'Şîfre divê herî kêm 8 tîp be', 'validation', 'Password validation'),
('kurdish_kurmanci', 'validation.password.uppercase', 'Şîfre divê herî kêm yek tîpa mezin hebe', 'validation', 'Password validation'),
('kurdish_kurmanci', 'validation.password.lowercase', 'Şîfre divê herî kêm yek tîpa piçûk hebe', 'validation', 'Password validation'),
('kurdish_kurmanci', 'validation.password.number', 'Şîfre divê herî kêm yek jimare hebe', 'validation', 'Password validation'),
('kurdish_kurmanci', 'validation.password.mismatch', 'Şîfre li hev nakin', 'validation', 'Password validation'),
('kurdish_kurmanci', 'validation.name.required', 'Nav pêwîst e', 'validation', 'Name validation'),
('kurdish_kurmanci', 'validation.name.min', 'Nav divê herî kêm 2 tîp be', 'validation', 'Name validation'),
('kurdish_kurmanci', 'validation.bio.min', 'Bio divê herî kêm 20 tîp be', 'validation', 'Bio validation'),
('kurdish_kurmanci', 'validation.bio.max', 'Bio nikare ji 500 tîpan zêdetir be', 'validation', 'Bio validation'),
('kurdish_kurmanci', 'validation.age.min', 'Divê tu herî kêm 18 salî bî', 'validation', 'Age validation'),
('kurdish_kurmanci', 'validation.photo.required', 'Herî kêm yek wêne pêwîst e', 'validation', 'Photo validation'),
('kurdish_kurmanci', 'validation.interests.min', 'Ji kerema xwe herî kêm 3 berjewendiyan hilbijêre', 'validation', 'Interests validation'),
('kurdish_kurmanci', 'validation.values.min', 'Ji kerema xwe herî kêm 3 nirxan hilbijêre', 'validation', 'Values validation'),
('kurdish_kurmanci', 'validation.field.required', 'Ev qada pêwîst e', 'validation', 'Generic field validation'),

-- Norwegian - Validation Messages
('norwegian', 'validation.email.required', 'E-post er påkrevd', 'validation', 'Email validation'),
('norwegian', 'validation.email.invalid', 'Ugyldig e-postformat', 'validation', 'Email validation'),
('norwegian', 'validation.password.required', 'Passord er påkrevd', 'validation', 'Password validation'),
('norwegian', 'validation.password.min', 'Passord må være minst 8 tegn', 'validation', 'Password validation'),
('norwegian', 'validation.password.uppercase', 'Passord må inneholde minst én stor bokstav', 'validation', 'Password validation'),
('norwegian', 'validation.password.lowercase', 'Passord må inneholde minst én liten bokstav', 'validation', 'Password validation'),
('norwegian', 'validation.password.number', 'Passord må inneholde minst ett tall', 'validation', 'Password validation'),
('norwegian', 'validation.password.mismatch', 'Passordene stemmer ikke overens', 'validation', 'Password validation'),
('norwegian', 'validation.name.required', 'Navn er påkrevd', 'validation', 'Name validation'),
('norwegian', 'validation.name.min', 'Navn må være minst 2 tegn', 'validation', 'Name validation'),
('norwegian', 'validation.bio.min', 'Bio må være minst 20 tegn', 'validation', 'Bio validation'),
('norwegian', 'validation.bio.max', 'Bio kan ikke overstige 500 tegn', 'validation', 'Bio validation'),
('norwegian', 'validation.age.min', 'Du må være minst 18 år gammel', 'validation', 'Age validation'),
('norwegian', 'validation.photo.required', 'Minst ett bilde er påkrevd', 'validation', 'Photo validation'),
('norwegian', 'validation.interests.min', 'Vennligst velg minst 3 interesser', 'validation', 'Interests validation'),
('norwegian', 'validation.values.min', 'Vennligst velg minst 3 verdier', 'validation', 'Values validation'),
('norwegian', 'validation.field.required', 'Dette feltet er påkrevd', 'validation', 'Generic field validation'),

-- German - Validation Messages
('german', 'validation.email.required', 'E-Mail ist erforderlich', 'validation', 'Email validation'),
('german', 'validation.email.invalid', 'Ungültiges E-Mail-Format', 'validation', 'Email validation'),
('german', 'validation.password.required', 'Passwort ist erforderlich', 'validation', 'Password validation'),
('german', 'validation.password.min', 'Passwort muss mindestens 8 Zeichen lang sein', 'validation', 'Password validation'),
('german', 'validation.password.uppercase', 'Passwort muss mindestens einen Großbuchstaben enthalten', 'validation', 'Password validation'),
('german', 'validation.password.lowercase', 'Passwort muss mindestens einen Kleinbuchstaben enthalten', 'validation', 'Password validation'),
('german', 'validation.password.number', 'Passwort muss mindestens eine Zahl enthalten', 'validation', 'Password validation'),
('german', 'validation.password.mismatch', 'Passwörter stimmen nicht überein', 'validation', 'Password validation'),
('german', 'validation.name.required', 'Name ist erforderlich', 'validation', 'Name validation'),
('german', 'validation.name.min', 'Name muss mindestens 2 Zeichen lang sein', 'validation', 'Name validation'),
('german', 'validation.bio.min', 'Bio muss mindestens 20 Zeichen lang sein', 'validation', 'Bio validation'),
('german', 'validation.bio.max', 'Bio darf 500 Zeichen nicht überschreiten', 'validation', 'Bio validation'),
('german', 'validation.age.min', 'Sie müssen mindestens 18 Jahre alt sein', 'validation', 'Age validation'),
('german', 'validation.photo.required', 'Mindestens ein Foto ist erforderlich', 'validation', 'Photo validation'),
('german', 'validation.interests.min', 'Bitte wählen Sie mindestens 3 Interessen', 'validation', 'Interests validation'),
('german', 'validation.values.min', 'Bitte wählen Sie mindestens 3 Werte', 'validation', 'Values validation'),
('german', 'validation.field.required', 'Dieses Feld ist erforderlich', 'validation', 'Generic field validation'),

-- English - Error Messages
('english', 'errors.network', 'Network error. Please check your connection.', 'errors', 'Network error'),
('english', 'errors.server', 'Server error. Please try again later.', 'errors', 'Server error'),
('english', 'errors.unknown', 'Something went wrong. Please try again.', 'errors', 'Unknown error'),
('english', 'errors.session_expired', 'Session expired. Please log in again.', 'errors', 'Session error'),
('english', 'errors.unauthorized', 'You are not authorized to perform this action.', 'errors', 'Authorization error'),
('english', 'errors.not_found', 'The requested resource was not found.', 'errors', 'Not found error'),
('english', 'errors.rate_limit', 'Rate limit exceeded. Please wait a moment.', 'errors', 'Rate limit error'),
('english', 'errors.upload_failed', 'Failed to upload file. Please try again.', 'errors', 'Upload error'),
('english', 'errors.load_failed', 'Failed to load data. Please refresh the page.', 'errors', 'Load error'),

('kurdish_sorani', 'errors.network', 'هەڵەی تۆڕ. تکایە پشکنینی پەیوەندیت بکە.', 'errors', 'Network error'),
('kurdish_sorani', 'errors.server', 'هەڵەی ڕاژەکار. تکایە دواتر دووبارە هەوڵ بدەرەوە.', 'errors', 'Server error'),
('kurdish_sorani', 'errors.unknown', 'هەڵەیەک ڕوویدا. تکایە دووبارە هەوڵ بدەرەوە.', 'errors', 'Unknown error'),
('kurdish_sorani', 'errors.session_expired', 'دانیشتن بەسەرچوو. تکایە دووبارە بچۆرە ژوورەوە.', 'errors', 'Session error'),
('kurdish_sorani', 'errors.unauthorized', 'مۆڵەتت نییە ئەم کردارە ئەنجام بدەیت.', 'errors', 'Authorization error'),
('kurdish_sorani', 'errors.not_found', 'سەرچاوەی داواکراو نەدۆزرایەوە.', 'errors', 'Not found error'),
('kurdish_sorani', 'errors.rate_limit', 'سنووری ڕێژە تێپەڕێنرا. تکایە چاوەڕێ بکە.', 'errors', 'Rate limit error'),
('kurdish_sorani', 'errors.upload_failed', 'بارکردنی فایل سەرکەوتوو نەبوو. تکایە دووبارە هەوڵ بدەرەوە.', 'errors', 'Upload error'),
('kurdish_sorani', 'errors.load_failed', 'بارکردنی داتا سەرکەوتوو نەبوو. تکایە لاپەڕەکە تازە بکەرەوە.', 'errors', 'Load error'),

('kurdish_kurmanci', 'errors.network', 'Xeletiya torê. Ji kerema xwe girêdana xwe kontrol bike.', 'errors', 'Network error'),
('kurdish_kurmanci', 'errors.server', 'Xeletiya rajekar. Ji kerema xwe paşê dîsa biceribîne.', 'errors', 'Server error'),
('kurdish_kurmanci', 'errors.unknown', 'Tiştek çewt çû. Ji kerema xwe dîsa biceribîne.', 'errors', 'Unknown error'),
('kurdish_kurmanci', 'errors.session_expired', 'Daneşîn qediya. Ji kerema xwe dîsa têkevin.', 'errors', 'Session error'),
('kurdish_kurmanci', 'errors.unauthorized', 'Mafê te tune ku vê çalakiyê bike.', 'errors', 'Authorization error'),
('kurdish_kurmanci', 'errors.not_found', 'Çavkaniya xwestî nehat dîtin.', 'errors', 'Not found error'),
('kurdish_kurmanci', 'errors.rate_limit', 'Sînorê rêjeyê derbas bû. Ji kerema xwe bisekine.', 'errors', 'Rate limit error'),
('kurdish_kurmanci', 'errors.upload_failed', 'Barkirina pelê têk çû. Ji kerema xwe dîsa biceribîne.', 'errors', 'Upload error'),
('kurdish_kurmanci', 'errors.load_failed', 'Barkirina daneyan têk çû. Ji kerema xwe rûpelê nû bike.', 'errors', 'Load error'),

('norwegian', 'errors.network', 'Nettverksfeil. Vennligst sjekk tilkoblingen din.', 'errors', 'Network error'),
('norwegian', 'errors.server', 'Serverfeil. Vennligst prøv igjen senere.', 'errors', 'Server error'),
('norwegian', 'errors.unknown', 'Noe gikk galt. Vennligst prøv igjen.', 'errors', 'Unknown error'),
('norwegian', 'errors.session_expired', 'Økten har utløpt. Vennligst logg inn på nytt.', 'errors', 'Session error'),
('norwegian', 'errors.unauthorized', 'Du har ikke tillatelse til å utføre denne handlingen.', 'errors', 'Authorization error'),
('norwegian', 'errors.not_found', 'Den forespurte ressursen ble ikke funnet.', 'errors', 'Not found error'),
('norwegian', 'errors.rate_limit', 'Grense overskredet. Vennligst vent et øyeblikk.', 'errors', 'Rate limit error'),
('norwegian', 'errors.upload_failed', 'Kunne ikke laste opp filen. Vennligst prøv igjen.', 'errors', 'Upload error'),
('norwegian', 'errors.load_failed', 'Kunne ikke laste inn data. Vennligst oppdater siden.', 'errors', 'Load error'),

('german', 'errors.network', 'Netzwerkfehler. Bitte überprüfen Sie Ihre Verbindung.', 'errors', 'Network error'),
('german', 'errors.server', 'Serverfehler. Bitte versuchen Sie es später erneut.', 'errors', 'Server error'),
('german', 'errors.unknown', 'Etwas ist schief gelaufen. Bitte versuchen Sie es erneut.', 'errors', 'Unknown error'),
('german', 'errors.session_expired', 'Sitzung abgelaufen. Bitte melden Sie sich erneut an.', 'errors', 'Session error'),
('german', 'errors.unauthorized', 'Sie sind nicht berechtigt, diese Aktion auszuführen.', 'errors', 'Authorization error'),
('german', 'errors.not_found', 'Die angeforderte Ressource wurde nicht gefunden.', 'errors', 'Not found error'),
('german', 'errors.rate_limit', 'Limit überschritten. Bitte warten Sie einen Moment.', 'errors', 'Rate limit error'),
('german', 'errors.upload_failed', 'Datei-Upload fehlgeschlagen. Bitte versuchen Sie es erneut.', 'errors', 'Upload error'),
('german', 'errors.load_failed', 'Daten konnten nicht geladen werden. Bitte aktualisieren Sie die Seite.', 'errors', 'Load error')

ON CONFLICT (language_code, translation_key) DO NOTHING;