-- Phase 1 Continuation: Swipe & Navigation translations

-- Navigation translations (adding more beyond basic nav)
INSERT INTO app_translations (language_code, translation_key, translation_value, category, context) VALUES
-- English - Extended Navigation
('english', 'nav.home', 'Home', 'navigation', 'Home link'),
('english', 'nav.explore', 'Explore', 'navigation', 'Explore link'),
('english', 'nav.notifications', 'Notifications', 'navigation', 'Notifications link'),
('english', 'nav.back', 'Back', 'navigation', 'Back button'),
('english', 'nav.close', 'Close', 'navigation', 'Close button'),
('english', 'nav.menu', 'Menu', 'navigation', 'Menu button'),
('english', 'nav.search', 'Search', 'navigation', 'Search'),
('english', 'nav.filter', 'Filter', 'navigation', 'Filter button'),
('english', 'nav.save', 'Save', 'navigation', 'Save button'),
('english', 'nav.cancel', 'Cancel', 'navigation', 'Cancel button'),
('english', 'nav.edit', 'Edit', 'navigation', 'Edit button'),
('english', 'nav.delete', 'Delete', 'navigation', 'Delete button'),
('english', 'nav.share', 'Share', 'navigation', 'Share button'),
('english', 'nav.report', 'Report', 'navigation', 'Report button'),
('english', 'nav.block', 'Block', 'navigation', 'Block button'),

-- Kurdish Sorani - Extended Navigation
('kurdish_sorani', 'nav.home', 'سەرەکی', 'navigation', 'Home link'),
('kurdish_sorani', 'nav.explore', 'گەڕان', 'navigation', 'Explore link'),
('kurdish_sorani', 'nav.notifications', 'ئاگاداریەکان', 'navigation', 'Notifications link'),
('kurdish_sorani', 'nav.back', 'گەڕانەوە', 'navigation', 'Back button'),
('kurdish_sorani', 'nav.close', 'داخستن', 'navigation', 'Close button'),
('kurdish_sorani', 'nav.menu', 'لیست', 'navigation', 'Menu button'),
('kurdish_sorani', 'nav.search', 'گەڕان', 'navigation', 'Search'),
('kurdish_sorani', 'nav.filter', 'پاڵاوتن', 'navigation', 'Filter button'),
('kurdish_sorani', 'nav.save', 'پاشەکەوتکردن', 'navigation', 'Save button'),
('kurdish_sorani', 'nav.cancel', 'هەڵوەشاندنەوە', 'navigation', 'Cancel button'),
('kurdish_sorani', 'nav.edit', 'دەستکاریکردن', 'navigation', 'Edit button'),
('kurdish_sorani', 'nav.delete', 'سڕینەوە', 'navigation', 'Delete button'),
('kurdish_sorani', 'nav.share', 'هاوبەشکردن', 'navigation', 'Share button'),
('kurdish_sorani', 'nav.report', 'گوزارشتکردن', 'navigation', 'Report button'),
('kurdish_sorani', 'nav.block', 'بلۆککردن', 'navigation', 'Block button'),

-- Kurdish Kurmanci - Extended Navigation
('kurdish_kurmanci', 'nav.home', 'Sereke', 'navigation', 'Home link'),
('kurdish_kurmanci', 'nav.explore', 'Vegerin', 'navigation', 'Explore link'),
('kurdish_kurmanci', 'nav.notifications', 'Agahdarî', 'navigation', 'Notifications link'),
('kurdish_kurmanci', 'nav.back', 'Vegere', 'navigation', 'Back button'),
('kurdish_kurmanci', 'nav.close', 'Bigire', 'navigation', 'Close button'),
('kurdish_kurmanci', 'nav.menu', 'Menû', 'navigation', 'Menu button'),
('kurdish_kurmanci', 'nav.search', 'Lêgerîn', 'navigation', 'Search'),
('kurdish_kurmanci', 'nav.filter', 'Parzûn', 'navigation', 'Filter button'),
('kurdish_kurmanci', 'nav.save', 'Tomar bike', 'navigation', 'Save button'),
('kurdish_kurmanci', 'nav.cancel', 'Betal bike', 'navigation', 'Cancel button'),
('kurdish_kurmanci', 'nav.edit', 'Sererast bike', 'navigation', 'Edit button'),
('kurdish_kurmanci', 'nav.delete', 'Jê bibe', 'navigation', 'Delete button'),
('kurdish_kurmanci', 'nav.share', 'Parve bike', 'navigation', 'Share button'),
('kurdish_kurmanci', 'nav.report', 'Rapor bike', 'navigation', 'Report button'),
('kurdish_kurmanci', 'nav.block', 'Asteng bike', 'navigation', 'Block button'),

-- Norwegian - Extended Navigation
('norwegian', 'nav.home', 'Hjem', 'navigation', 'Home link'),
('norwegian', 'nav.explore', 'Utforsk', 'navigation', 'Explore link'),
('norwegian', 'nav.notifications', 'Varsler', 'navigation', 'Notifications link'),
('norwegian', 'nav.back', 'Tilbake', 'navigation', 'Back button'),
('norwegian', 'nav.close', 'Lukk', 'navigation', 'Close button'),
('norwegian', 'nav.menu', 'Meny', 'navigation', 'Menu button'),
('norwegian', 'nav.search', 'Søk', 'navigation', 'Search'),
('norwegian', 'nav.filter', 'Filter', 'navigation', 'Filter button'),
('norwegian', 'nav.save', 'Lagre', 'navigation', 'Save button'),
('norwegian', 'nav.cancel', 'Avbryt', 'navigation', 'Cancel button'),
('norwegian', 'nav.edit', 'Rediger', 'navigation', 'Edit button'),
('norwegian', 'nav.delete', 'Slett', 'navigation', 'Delete button'),
('norwegian', 'nav.share', 'Del', 'navigation', 'Share button'),
('norwegian', 'nav.report', 'Rapporter', 'navigation', 'Report button'),
('norwegian', 'nav.block', 'Blokkér', 'navigation', 'Block button'),

-- German - Extended Navigation
('german', 'nav.home', 'Startseite', 'navigation', 'Home link'),
('german', 'nav.explore', 'Erkunden', 'navigation', 'Explore link'),
('german', 'nav.notifications', 'Benachrichtigungen', 'navigation', 'Notifications link'),
('german', 'nav.back', 'Zurück', 'navigation', 'Back button'),
('german', 'nav.close', 'Schließen', 'navigation', 'Close button'),
('german', 'nav.menu', 'Menü', 'navigation', 'Menu button'),
('german', 'nav.search', 'Suchen', 'navigation', 'Search'),
('german', 'nav.filter', 'Filtern', 'navigation', 'Filter button'),
('german', 'nav.save', 'Speichern', 'navigation', 'Save button'),
('german', 'nav.cancel', 'Abbrechen', 'navigation', 'Cancel button'),
('german', 'nav.edit', 'Bearbeiten', 'navigation', 'Edit button'),
('german', 'nav.delete', 'Löschen', 'navigation', 'Delete button'),
('german', 'nav.share', 'Teilen', 'navigation', 'Share button'),
('german', 'nav.report', 'Melden', 'navigation', 'Report button'),
('german', 'nav.block', 'Blockieren', 'navigation', 'Block button'),

-- Common UI elements
('english', 'common.loading', 'Loading...', 'common', 'Loading state'),
('english', 'common.error', 'Error', 'common', 'Error title'),
('english', 'common.success', 'Success', 'common', 'Success title'),
('english', 'common.warning', 'Warning', 'common', 'Warning title'),
('english', 'common.info', 'Info', 'common', 'Info title'),
('english', 'common.confirm', 'Confirm', 'common', 'Confirm button'),
('english', 'common.yes', 'Yes', 'common', 'Yes button'),
('english', 'common.no', 'No', 'common', 'No button'),
('english', 'common.ok', 'OK', 'common', 'OK button'),
('english', 'common.continue', 'Continue', 'common', 'Continue button'),
('english', 'common.skip', 'Skip', 'common', 'Skip button'),
('english', 'common.next', 'Next', 'common', 'Next button'),
('english', 'common.previous', 'Previous', 'common', 'Previous button'),
('english', 'common.finish', 'Finish', 'common', 'Finish button'),
('english', 'common.required', 'Required', 'common', 'Required field indicator'),

('kurdish_sorani', 'common.loading', 'بارکردن...', 'common', 'Loading state'),
('kurdish_sorani', 'common.error', 'هەڵە', 'common', 'Error title'),
('kurdish_sorani', 'common.success', 'سەرکەوتوو', 'common', 'Success title'),
('kurdish_sorani', 'common.warning', 'ئاگاداری', 'common', 'Warning title'),
('kurdish_sorani', 'common.info', 'زانیاری', 'common', 'Info title'),
('kurdish_sorani', 'common.confirm', 'پشتڕاستکردنەوە', 'common', 'Confirm button'),
('kurdish_sorani', 'common.yes', 'بەڵێ', 'common', 'Yes button'),
('kurdish_sorani', 'common.no', 'نەخێر', 'common', 'No button'),
('kurdish_sorani', 'common.ok', 'باشە', 'common', 'OK button'),
('kurdish_sorani', 'common.continue', 'بەردەوامبوون', 'common', 'Continue button'),
('kurdish_sorani', 'common.skip', 'تێپەڕین', 'common', 'Skip button'),
('kurdish_sorani', 'common.next', 'دواتر', 'common', 'Next button'),
('kurdish_sorani', 'common.previous', 'پێشوو', 'common', 'Previous button'),
('kurdish_sorani', 'common.finish', 'تەواوکردن', 'common', 'Finish button'),
('kurdish_sorani', 'common.required', 'پێویست', 'common', 'Required field indicator'),

('kurdish_kurmanci', 'common.loading', 'Tê barkirin...', 'common', 'Loading state'),
('kurdish_kurmanci', 'common.error', 'Xeletî', 'common', 'Error title'),
('kurdish_kurmanci', 'common.success', 'Serketî', 'common', 'Success title'),
('kurdish_kurmanci', 'common.warning', 'Hişyarî', 'common', 'Warning title'),
('kurdish_kurmanci', 'common.info', 'Agahî', 'common', 'Info title'),
('kurdish_kurmanci', 'common.confirm', 'Piştrast bike', 'common', 'Confirm button'),
('kurdish_kurmanci', 'common.yes', 'Erê', 'common', 'Yes button'),
('kurdish_kurmanci', 'common.no', 'Na', 'common', 'No button'),
('kurdish_kurmanci', 'common.ok', 'Baş e', 'common', 'OK button'),
('kurdish_kurmanci', 'common.continue', 'Berdewam be', 'common', 'Continue button'),
('kurdish_kurmanci', 'common.skip', 'Derbas bike', 'common', 'Skip button'),
('kurdish_kurmanci', 'common.next', 'Pêş', 'common', 'Next button'),
('kurdish_kurmanci', 'common.previous', 'Paş', 'common', 'Previous button'),
('kurdish_kurmanci', 'common.finish', 'Qedand', 'common', 'Finish button'),
('kurdish_kurmanci', 'common.required', 'Pêwîst', 'common', 'Required field indicator'),

('norwegian', 'common.loading', 'Laster...', 'common', 'Loading state'),
('norwegian', 'common.error', 'Feil', 'common', 'Error title'),
('norwegian', 'common.success', 'Suksess', 'common', 'Success title'),
('norwegian', 'common.warning', 'Advarsel', 'common', 'Warning title'),
('norwegian', 'common.info', 'Info', 'common', 'Info title'),
('norwegian', 'common.confirm', 'Bekreft', 'common', 'Confirm button'),
('norwegian', 'common.yes', 'Ja', 'common', 'Yes button'),
('norwegian', 'common.no', 'Nei', 'common', 'No button'),
('norwegian', 'common.ok', 'OK', 'common', 'OK button'),
('norwegian', 'common.continue', 'Fortsett', 'common', 'Continue button'),
('norwegian', 'common.skip', 'Hopp over', 'common', 'Skip button'),
('norwegian', 'common.next', 'Neste', 'common', 'Next button'),
('norwegian', 'common.previous', 'Forrige', 'common', 'Previous button'),
('norwegian', 'common.finish', 'Fullfør', 'common', 'Finish button'),
('norwegian', 'common.required', 'Påkrevd', 'common', 'Required field indicator'),

('german', 'common.loading', 'Lädt...', 'common', 'Loading state'),
('german', 'common.error', 'Fehler', 'common', 'Error title'),
('german', 'common.success', 'Erfolg', 'common', 'Success title'),
('german', 'common.warning', 'Warnung', 'common', 'Warning title'),
('german', 'common.info', 'Info', 'common', 'Info title'),
('german', 'common.confirm', 'Bestätigen', 'common', 'Confirm button'),
('german', 'common.yes', 'Ja', 'common', 'Yes button'),
('german', 'common.no', 'Nein', 'common', 'No button'),
('german', 'common.ok', 'OK', 'common', 'OK button'),
('german', 'common.continue', 'Weiter', 'common', 'Continue button'),
('german', 'common.skip', 'Überspringen', 'common', 'Skip button'),
('german', 'common.next', 'Weiter', 'common', 'Next button'),
('german', 'common.previous', 'Zurück', 'common', 'Previous button'),
('german', 'common.finish', 'Fertig', 'common', 'Finish button'),
('german', 'common.required', 'Erforderlich', 'common', 'Required field indicator')

ON CONFLICT (language_code, translation_key) DO NOTHING;