-- Disable love_language question
UPDATE registration_questions 
SET enabled = false 
WHERE id = 'love_language';

-- Update education to occupation with comprehensive list
UPDATE registration_questions 
SET 
  text = 'What''s your occupation? (Select up to 3)',
  field_type = 'multi_select',
  placeholder = 'Search for your occupation...',
  field_options = ARRAY[
    'University / College Student',
    'High School Student',
    'Apprentice / Trainee / Intern',
    'Teacher / Teaching Assistant / Professor',
    'Researcher / Academic',
    'Doctor / Surgeon',
    'Nurse / Midwife',
    'Physiotherapist / Occupational Therapist',
    'Psychologist / Therapist',
    'Social Worker',
    'Healthcare Assistant / Caregiver',
    'Veterinarian',
    'Software Developer / Programmer',
    'Web Designer / UX Designer',
    'Data Analyst / Data Scientist',
    'IT Support / Technician',
    'System Administrator / Network Administrator',
    'AI / Machine Learning Specialist',
    'Cybersecurity Specialist',
    'Designer (Graphic, Fashion, Interior)',
    'Artist / Illustrator / Painter',
    'Musician / Composer',
    'Actor / Performer',
    'Writer / Author',
    'Photographer / Videographer',
    'Journalist / Reporter',
    'Blogger / Influencer / Content Creator',
    'PR / Marketing Professional',
    'Advertising / Ad Agency',
    'Social Media Specialist',
    'Editor / Publisher',
    'CEO / Entrepreneur / Business Owner',
    'Accountant / Auditor',
    'Banking / Finance Professional',
    'Consultant / Advisor',
    'Sales / Account Manager',
    'Human Resources (HR)',
    'Electrician / Plumber / HVAC',
    'Carpenter / Joiner',
    'Painter / Decorator',
    'Mechanic / Technician',
    'Construction Worker / Contractor',
    'Heavy Machinery Operator',
    'Waiter / Bartender / Chef',
    'Hotel Staff / Receptionist / Concierge',
    'Retail / Sales',
    'Customer Service / Call Center',
    'Tourism / Travel Industry',
    'Police / Firefighter / Military',
    'Civil Servant / Government Worker',
    'Lawyer / Judge / Legal Professional',
    'Politician / Public Administration',
    'Pilot / Flight Crew',
    'Bus / Train / Truck Driver',
    'Logistics / Warehouse Worker',
    'Shipping / Freight',
    'Freelancer (Translator, Writer, Designer)',
    'Stay-at-Home Parent',
    'Own Business / Online Store',
    'Agriculture / Farming',
    'Animal Husbandry / Livestock',
    'Handicrafts / Traditional Kurdish Crafts',
    'Small Business / Local Shop / Bazaar',
    'Traditional Food Production',
    'Musician / Cultural Promoter (Kurdish)',
    'Cultural Event Organizer',
    'Journalist / Media (Kurdish communities)',
    'NGO / Social Work (Kurdish communities)',
    'Kurdish Language Teacher / Language Promoter',
    'Unemployed',
    'Retired',
    'Other / Miscellaneous'
  ]
WHERE id = 'education';

-- Expand languages with global coverage (80+ languages)
UPDATE registration_questions 
SET field_options = ARRAY[
  'Kurdish (Sorani)',
  'Kurdish (Kurmanji)',
  'Kurdish (Zazaki)',
  'Kurdish (Gorani)',
  'Kurdish (Hawrami)',
  'Arabic',
  'Hebrew',
  'Persian (Farsi)',
  'Turkish',
  'Aramaic',
  'Armenian',
  'Azerbaijani',
  'Georgian',
  'Urdu',
  'Pashto',
  'Balochi',
  'Luri',
  'Assyrian',
  'Turkmen',
  'Kazakh',
  'English',
  'French',
  'German',
  'Spanish',
  'Italian',
  'Portuguese',
  'Russian',
  'Dutch',
  'Polish',
  'Swedish',
  'Norwegian',
  'Danish',
  'Finnish',
  'Greek',
  'Czech',
  'Hungarian',
  'Romanian',
  'Bulgarian',
  'Croatian',
  'Serbian',
  'Ukrainian',
  'Belarusian',
  'Slovak',
  'Slovenian',
  'Albanian',
  'Lithuanian',
  'Latvian',
  'Estonian',
  'Icelandic',
  'Irish',
  'Welsh',
  'Scots Gaelic',
  'Catalan',
  'Basque',
  'Galician',
  'Luxembourgish',
  'Maltese',
  'Macedonian',
  'Montenegrin',
  'Bosnian',
  'Mandarin Chinese',
  'Japanese',
  'Korean',
  'Hindi',
  'Bengali',
  'Vietnamese',
  'Thai',
  'Indonesian',
  'Malay',
  'Tagalog',
  'Tamil',
  'Telugu',
  'Punjabi',
  'Nepali',
  'Sinhala',
  'Swahili',
  'Amharic',
  'Somali',
  'Hausa',
  'Yoruba',
  'Zulu',
  'Afrikaans',
  'Berber'
]
WHERE id = 'languages';