
INSERT INTO public.app_translations (language_code, translation_key, translation_value, category) VALUES
('english', 'admin.transactions', 'Transactions', 'admin'),
('english', 'admin.subscription_revenue', 'Subscription Revenue', 'admin'),
('english', 'admin.payment_settings', 'Payment Settings', 'admin'),
('english', 'admin.payment_refunded_success', 'Payment refunded successfully', 'admin'),
('english', 'admin.payment_refund_failed', 'Failed to refund payment', 'admin'),
('english', 'admin.receipt_resent_to', 'Receipt resent to {{email}}', 'admin'),
('english', 'admin.payment_processing', 'Payment Processing', 'admin'),
('english', 'admin.manage_payment_transactions', 'Manage payment transactions and billing', 'admin'),
('english', 'admin.payment_data_exported', 'Payment data exported successfully', 'admin'),
('english', 'admin.payment_actions', 'Payment Actions', 'admin'),
('english', 'admin.sync_payment_data', 'Sync Payment Data', 'admin'),
('english', 'admin.sync_payment_data_success', 'Sync payment data with external service', 'admin'),
('english', 'admin.generate_monthly_report', 'Generate Monthly Report', 'admin'),
('english', 'admin.generate_monthly_report_success', 'Generate monthly report', 'admin'),
('english', 'admin.configure_payment_gateway', 'Configure Payment Gateway', 'admin'),
('english', 'admin.configure_payment_gateway_success', 'Configure payment gateway', 'admin'),
('english', 'admin.total_revenue', 'Total Revenue', 'admin'),
('english', 'admin.revenue_change', '+12.5% from last month', 'admin'),
('english', 'admin.todays_revenue', 'Today''s Revenue', 'admin'),
('english', 'admin.successful_transactions_today', '5 successful transactions today', 'admin'),
('english', 'admin.pending_payments', 'Pending Payments', 'admin'),
('english', 'admin.awaiting_processing', '{{amount}} awaiting processing', 'admin'),
('english', 'common.date', 'Date', 'common'),
('english', 'common.customer', 'Customer', 'common'),
('english', 'common.invoice', 'Invoice', 'common'),
('english', 'common.description', 'Description', 'common'),
('english', 'common.method', 'Method', 'common'),
('english', 'common.status', 'Status', 'common'),
('english', 'common.actions', 'Actions', 'common'),
('english', 'admin.view_receipt', 'View Receipt', 'admin'),
('english', 'admin.no_payment_transactions', 'No payment transactions found', 'admin'),
('english', 'admin.search_payments_placeholder', 'Search by name, email, or invoice number...', 'admin'),
('english', 'admin.all_statuses', 'All Statuses', 'admin'),
('english', 'admin.all_methods', 'All Methods', 'admin'),
('english', 'admin.date_range', 'Date Range', 'admin'),
('english', 'admin.filter_by_date', 'Filter by date', 'admin'),
('english', 'common.today', 'Today', 'common'),
('english', 'common.yesterday', 'Yesterday', 'common'),
('english', 'admin.this_week', 'This Week', 'admin'),
('english', 'admin.this_month', 'This Month', 'admin'),
('english', 'admin.last_month', 'Last Month', 'admin'),
('english', 'admin.all_time', 'All Time', 'admin'),
('english', 'admin.payment_receipt', 'Payment Receipt', 'admin'),
('english', 'admin.receipt_details_for', 'Receipt details for transaction', 'admin'),
('english', 'admin.receipt', 'RECEIPT', 'admin'),
('english', 'admin.company_name', 'Company Name', 'admin'),
('english', 'admin.billed_to', 'Billed To', 'admin'),
('english', 'admin.payment_info', 'Payment Info', 'admin'),
('english', 'admin.card', 'Card', 'admin'),
('english', 'admin.ending_in', 'ending in', 'admin'),
('english', 'admin.subscription', 'Subscription', 'admin'),
('english', 'admin.subtotal', 'Subtotal', 'admin'),
('english', 'admin.tax', 'Tax', 'admin'),
('english', 'admin.total', 'Total', 'admin'),
('english', 'admin.thank_you', 'Thank you for your business!', 'admin'),
('english', 'admin.print', 'Print', 'admin'),
('english', 'admin.download_pdf', 'Download PDF', 'admin'),
('english', 'admin.email_receipt', 'Email Receipt', 'admin'),
('english', 'admin.receipt_printed', 'Receipt printed successfully', 'admin'),
('english', 'admin.receipt_downloaded', 'Receipt downloaded as PDF', 'admin'),
('english', 'admin.configure_payment_settings', 'Configure payment gateways and transaction settings', 'admin'),
('english', 'admin.payment_gateways', 'Payment Gateways', 'admin'),
('english', 'admin.primary_payment_processor', 'Primary payment processor', 'admin'),
('english', 'admin.secondary_payment_processor', 'Secondary payment processor', 'admin'),
('english', 'admin.not_configured', 'Not configured', 'admin'),
('english', 'common.active', 'Active', 'common'),
('english', 'common.inactive', 'Inactive', 'common'),
('english', 'admin.invoice_settings', 'Invoice Settings', 'admin'),
('english', 'admin.company_information', 'Company Information', 'admin'),
('english', 'admin.info_displayed_invoices', 'Information displayed on invoices', 'admin'),
('english', 'admin.edit_company_info', 'Edit Company Information', 'admin'),
('english', 'admin.invoice_templates', 'Invoice Templates', 'admin'),
('english', 'admin.customize_invoice', 'Customize invoice appearance', 'admin'),
('english', 'admin.manage_templates', 'Manage Templates', 'admin'),
('english', 'admin.tax_settings', 'Tax Settings', 'admin'),
('english', 'admin.auto_tax_calculation', 'Automatic Tax Calculation', 'admin'),
('english', 'admin.tax_calc_desc', 'Calculate taxes based on customer location', 'admin'),
('english', 'admin.tax_reports', 'Tax Reports', 'admin'),
('english', 'admin.tax_reports_desc', 'Download tax reports for accounting', 'admin'),
('english', 'admin.generate_report', 'Generate Report', 'admin'),
('english', 'common.configure', 'Configure', 'common'),
('english', 'admin.subscription_revenue_overview', 'Subscription Revenue Overview', 'admin'),
('english', 'admin.mrr_metrics', 'Monthly recurring revenue and subscription metrics', 'admin'),
('english', 'admin.monthly_recurring_revenue', 'Monthly Recurring Revenue', 'admin'),
('english', 'admin.mrr_change', '+8.4% from last month', 'admin'),
('english', 'admin.active_subscribers', 'Active Subscribers', 'admin'),
('english', 'admin.new_subscribers_month', '+23 new subscribers this month', 'admin'),
('english', 'admin.avg_revenue_per_user', 'Average Revenue Per User', 'admin'),
('english', 'admin.arpu_change', '+$1.25 from last month', 'admin'),
('english', 'admin.monthly_revenue_year', 'Monthly Revenue (2023)', 'admin'),
('english', 'admin.subscription_plans', 'Subscription Plans', 'admin'),
('english', 'admin.subscribers', 'subscribers', 'admin'),
('english', 'admin.churn_rate', 'Churn Rate', 'admin'),
('english', 'admin.monthly_churn', 'Monthly Churn', 'admin'),
('english', 'admin.annual_projection', 'Annual Projection', 'admin'),
('english', 'admin.requires_attention', 'Requires attention', 'admin'),
('english', 'admin.ai_powered_admin', 'AI-Powered Administration', 'admin'),
('english', 'admin.ai_admin_desc', 'Our AI systems enhance administration capabilities across the platform', 'admin'),

('norwegian', 'admin.transactions', 'Transaksjoner', 'admin'),
('norwegian', 'admin.subscription_revenue', 'Abonnementsinntekter', 'admin'),
('norwegian', 'admin.payment_settings', 'Betalingsinnstillinger', 'admin'),
('norwegian', 'admin.payment_refunded_success', 'Betaling refundert', 'admin'),
('norwegian', 'admin.payment_refund_failed', 'Kunne ikke refundere betaling', 'admin'),
('norwegian', 'admin.receipt_resent_to', 'Kvittering sendt på nytt til {{email}}', 'admin'),
('norwegian', 'admin.payment_processing', 'Betalingsbehandling', 'admin'),
('norwegian', 'admin.manage_payment_transactions', 'Administrer betalingstransaksjoner og fakturering', 'admin'),
('norwegian', 'admin.payment_data_exported', 'Betalingsdata eksportert', 'admin'),
('norwegian', 'admin.payment_actions', 'Betalingshandlinger', 'admin'),
('norwegian', 'admin.sync_payment_data', 'Synkroniser betalingsdata', 'admin'),
('norwegian', 'admin.generate_monthly_report', 'Generer månedsrapport', 'admin'),
('norwegian', 'admin.configure_payment_gateway', 'Konfigurer betalingsgateway', 'admin'),
('norwegian', 'admin.total_revenue', 'Total inntekt', 'admin'),
('norwegian', 'admin.revenue_change', '+12,5% fra forrige måned', 'admin'),
('norwegian', 'admin.todays_revenue', 'Dagens inntekt', 'admin'),
('norwegian', 'admin.successful_transactions_today', '5 vellykkede transaksjoner i dag', 'admin'),
('norwegian', 'admin.pending_payments', 'Ventende betalinger', 'admin'),
('norwegian', 'admin.awaiting_processing', '{{amount}} venter på behandling', 'admin'),
('norwegian', 'common.date', 'Dato', 'common'),
('norwegian', 'common.customer', 'Kunde', 'common'),
('norwegian', 'common.invoice', 'Faktura', 'common'),
('norwegian', 'common.description', 'Beskrivelse', 'common'),
('norwegian', 'common.method', 'Metode', 'common'),
('norwegian', 'common.status', 'Status', 'common'),
('norwegian', 'common.actions', 'Handlinger', 'common'),
('norwegian', 'admin.view_receipt', 'Vis kvittering', 'admin'),
('norwegian', 'admin.no_payment_transactions', 'Ingen betalingstransaksjoner funnet', 'admin'),
('norwegian', 'admin.search_payments_placeholder', 'Søk etter navn, e-post eller fakturanummer...', 'admin'),
('norwegian', 'admin.all_statuses', 'Alle statuser', 'admin'),
('norwegian', 'admin.all_methods', 'Alle metoder', 'admin'),
('norwegian', 'admin.date_range', 'Datoperiode', 'admin'),
('norwegian', 'admin.filter_by_date', 'Filtrer etter dato', 'admin'),
('norwegian', 'common.today', 'I dag', 'common'),
('norwegian', 'common.yesterday', 'I går', 'common'),
('norwegian', 'admin.this_week', 'Denne uken', 'admin'),
('norwegian', 'admin.this_month', 'Denne måneden', 'admin'),
('norwegian', 'admin.last_month', 'Forrige måned', 'admin'),
('norwegian', 'admin.all_time', 'All tid', 'admin'),
('norwegian', 'admin.payment_receipt', 'Betalingskvittering', 'admin'),
('norwegian', 'admin.receipt_details_for', 'Kvitteringsdetaljer for transaksjon', 'admin'),
('norwegian', 'admin.receipt', 'KVITTERING', 'admin'),
('norwegian', 'admin.company_name', 'Firmanavn', 'admin'),
('norwegian', 'admin.billed_to', 'Fakturert til', 'admin'),
('norwegian', 'admin.payment_info', 'Betalingsinformasjon', 'admin'),
('norwegian', 'admin.card', 'Kort', 'admin'),
('norwegian', 'admin.ending_in', 'slutter på', 'admin'),
('norwegian', 'admin.subscription', 'Abonnement', 'admin'),
('norwegian', 'admin.subtotal', 'Delsum', 'admin'),
('norwegian', 'admin.tax', 'Mva', 'admin'),
('norwegian', 'admin.total', 'Totalt', 'admin'),
('norwegian', 'admin.thank_you', 'Takk for handelen!', 'admin'),
('norwegian', 'admin.print', 'Skriv ut', 'admin'),
('norwegian', 'admin.download_pdf', 'Last ned PDF', 'admin'),
('norwegian', 'admin.email_receipt', 'Send kvittering', 'admin'),
('norwegian', 'admin.receipt_printed', 'Kvittering skrevet ut', 'admin'),
('norwegian', 'admin.receipt_downloaded', 'Kvittering lastet ned som PDF', 'admin'),
('norwegian', 'admin.configure_payment_settings', 'Konfigurer betalingsgatewayer og transaksjonsinnstillinger', 'admin'),
('norwegian', 'admin.payment_gateways', 'Betalingsgatewayer', 'admin'),
('norwegian', 'admin.primary_payment_processor', 'Primær betalingsbehandler', 'admin'),
('norwegian', 'admin.secondary_payment_processor', 'Sekundær betalingsbehandler', 'admin'),
('norwegian', 'admin.not_configured', 'Ikke konfigurert', 'admin'),
('norwegian', 'common.active', 'Aktiv', 'common'),
('norwegian', 'common.inactive', 'Inaktiv', 'common'),
('norwegian', 'admin.invoice_settings', 'Fakturainnstillinger', 'admin'),
('norwegian', 'admin.company_information', 'Firmainformasjon', 'admin'),
('norwegian', 'admin.info_displayed_invoices', 'Informasjon vist på fakturaer', 'admin'),
('norwegian', 'admin.edit_company_info', 'Rediger firmainformasjon', 'admin'),
('norwegian', 'admin.invoice_templates', 'Fakturamaler', 'admin'),
('norwegian', 'admin.customize_invoice', 'Tilpass fakturautseende', 'admin'),
('norwegian', 'admin.manage_templates', 'Administrer maler', 'admin'),
('norwegian', 'admin.tax_settings', 'Skatteinnstillinger', 'admin'),
('norwegian', 'admin.auto_tax_calculation', 'Automatisk skatteberegning', 'admin'),
('norwegian', 'admin.tax_calc_desc', 'Beregn skatt basert på kundens plassering', 'admin'),
('norwegian', 'admin.tax_reports', 'Skatterapporter', 'admin'),
('norwegian', 'admin.tax_reports_desc', 'Last ned skatterapporter for regnskap', 'admin'),
('norwegian', 'admin.generate_report', 'Generer rapport', 'admin'),
('norwegian', 'common.configure', 'Konfigurer', 'common'),
('norwegian', 'admin.subscription_revenue_overview', 'Oversikt over abonnementsinntekter', 'admin'),
('norwegian', 'admin.mrr_metrics', 'Månedlige gjentakende inntekter og abonnementsmetrikker', 'admin'),
('norwegian', 'admin.monthly_recurring_revenue', 'Månedlige gjentakende inntekter', 'admin'),
('norwegian', 'admin.mrr_change', '+8,4% fra forrige måned', 'admin'),
('norwegian', 'admin.active_subscribers', 'Aktive abonnenter', 'admin'),
('norwegian', 'admin.new_subscribers_month', '+23 nye abonnenter denne måneden', 'admin'),
('norwegian', 'admin.avg_revenue_per_user', 'Gjennomsnittlig inntekt per bruker', 'admin'),
('norwegian', 'admin.arpu_change', '+$1,25 fra forrige måned', 'admin'),
('norwegian', 'admin.monthly_revenue_year', 'Månedlig inntekt (2023)', 'admin'),
('norwegian', 'admin.subscription_plans', 'Abonnementsplaner', 'admin'),
('norwegian', 'admin.subscribers', 'abonnenter', 'admin'),
('norwegian', 'admin.churn_rate', 'Frafallsrate', 'admin'),
('norwegian', 'admin.monthly_churn', 'Månedlig frafall', 'admin'),
('norwegian', 'admin.annual_projection', 'Årlig prognose', 'admin'),
('norwegian', 'admin.requires_attention', 'Krever oppmerksomhet', 'admin'),
('norwegian', 'admin.ai_powered_admin', 'AI-drevet administrasjon', 'admin'),
('norwegian', 'admin.ai_admin_desc', 'Våre AI-systemer forbedrer administrasjonsevnene på plattformen', 'admin'),

('german', 'admin.transactions', 'Transaktionen', 'admin'),
('german', 'admin.subscription_revenue', 'Abonnement-Einnahmen', 'admin'),
('german', 'admin.payment_settings', 'Zahlungseinstellungen', 'admin'),
('german', 'admin.payment_refunded_success', 'Zahlung erfolgreich erstattet', 'admin'),
('german', 'admin.payment_refund_failed', 'Erstattung fehlgeschlagen', 'admin'),
('german', 'admin.receipt_resent_to', 'Quittung erneut gesendet an {{email}}', 'admin'),
('german', 'admin.payment_processing', 'Zahlungsabwicklung', 'admin'),
('german', 'admin.manage_payment_transactions', 'Zahlungstransaktionen und Abrechnung verwalten', 'admin'),
('german', 'admin.payment_data_exported', 'Zahlungsdaten erfolgreich exportiert', 'admin'),
('german', 'admin.payment_actions', 'Zahlungsaktionen', 'admin'),
('german', 'admin.sync_payment_data', 'Zahlungsdaten synchronisieren', 'admin'),
('german', 'admin.generate_monthly_report', 'Monatsbericht erstellen', 'admin'),
('german', 'admin.configure_payment_gateway', 'Zahlungs-Gateway konfigurieren', 'admin'),
('german', 'admin.total_revenue', 'Gesamteinnahmen', 'admin'),
('german', 'admin.revenue_change', '+12,5% gegenüber Vormonat', 'admin'),
('german', 'admin.todays_revenue', 'Heutige Einnahmen', 'admin'),
('german', 'admin.successful_transactions_today', '5 erfolgreiche Transaktionen heute', 'admin'),
('german', 'admin.pending_payments', 'Ausstehende Zahlungen', 'admin'),
('german', 'admin.awaiting_processing', '{{amount}} warten auf Verarbeitung', 'admin'),
('german', 'common.date', 'Datum', 'common'),
('german', 'common.customer', 'Kunde', 'common'),
('german', 'common.invoice', 'Rechnung', 'common'),
('german', 'common.description', 'Beschreibung', 'common'),
('german', 'common.method', 'Methode', 'common'),
('german', 'common.status', 'Status', 'common'),
('german', 'common.actions', 'Aktionen', 'common'),
('german', 'admin.view_receipt', 'Quittung anzeigen', 'admin'),
('german', 'admin.no_payment_transactions', 'Keine Zahlungstransaktionen gefunden', 'admin'),
('german', 'admin.search_payments_placeholder', 'Nach Name, E-Mail oder Rechnungsnummer suchen...', 'admin'),
('german', 'admin.all_statuses', 'Alle Status', 'admin'),
('german', 'admin.all_methods', 'Alle Methoden', 'admin'),
('german', 'admin.date_range', 'Datumsbereich', 'admin'),
('german', 'admin.filter_by_date', 'Nach Datum filtern', 'admin'),
('german', 'common.today', 'Heute', 'common'),
('german', 'common.yesterday', 'Gestern', 'common'),
('german', 'admin.this_week', 'Diese Woche', 'admin'),
('german', 'admin.this_month', 'Dieser Monat', 'admin'),
('german', 'admin.last_month', 'Letzter Monat', 'admin'),
('german', 'admin.all_time', 'Gesamtzeit', 'admin'),
('german', 'admin.payment_receipt', 'Zahlungsquittung', 'admin'),
('german', 'admin.receipt_details_for', 'Quittungsdetails für Transaktion', 'admin'),
('german', 'admin.receipt', 'QUITTUNG', 'admin'),
('german', 'admin.company_name', 'Firmenname', 'admin'),
('german', 'admin.billed_to', 'Rechnung an', 'admin'),
('german', 'admin.payment_info', 'Zahlungsinformationen', 'admin'),
('german', 'admin.card', 'Karte', 'admin'),
('german', 'admin.ending_in', 'endend auf', 'admin'),
('german', 'admin.subscription', 'Abonnement', 'admin'),
('german', 'admin.subtotal', 'Zwischensumme', 'admin'),
('german', 'admin.tax', 'Steuer', 'admin'),
('german', 'admin.total', 'Gesamt', 'admin'),
('german', 'admin.thank_you', 'Vielen Dank für Ihren Einkauf!', 'admin'),
('german', 'admin.print', 'Drucken', 'admin'),
('german', 'admin.download_pdf', 'PDF herunterladen', 'admin'),
('german', 'admin.email_receipt', 'Quittung per E-Mail', 'admin'),
('german', 'admin.receipt_printed', 'Quittung erfolgreich gedruckt', 'admin'),
('german', 'admin.receipt_downloaded', 'Quittung als PDF heruntergeladen', 'admin'),
('german', 'admin.configure_payment_settings', 'Zahlungs-Gateways und Transaktionseinstellungen konfigurieren', 'admin'),
('german', 'admin.payment_gateways', 'Zahlungs-Gateways', 'admin'),
('german', 'admin.primary_payment_processor', 'Primärer Zahlungsabwickler', 'admin'),
('german', 'admin.secondary_payment_processor', 'Sekundärer Zahlungsabwickler', 'admin'),
('german', 'admin.not_configured', 'Nicht konfiguriert', 'admin'),
('german', 'common.active', 'Aktiv', 'common'),
('german', 'common.inactive', 'Inaktiv', 'common'),
('german', 'admin.invoice_settings', 'Rechnungseinstellungen', 'admin'),
('german', 'admin.company_information', 'Firmeninformationen', 'admin'),
('german', 'admin.info_displayed_invoices', 'Auf Rechnungen angezeigte Informationen', 'admin'),
('german', 'admin.edit_company_info', 'Firmeninformationen bearbeiten', 'admin'),
('german', 'admin.invoice_templates', 'Rechnungsvorlagen', 'admin'),
('german', 'admin.customize_invoice', 'Rechnungsdarstellung anpassen', 'admin'),
('german', 'admin.manage_templates', 'Vorlagen verwalten', 'admin'),
('german', 'admin.tax_settings', 'Steuereinstellungen', 'admin'),
('german', 'admin.auto_tax_calculation', 'Automatische Steuerberechnung', 'admin'),
('german', 'admin.tax_calc_desc', 'Steuern basierend auf Kundenstandort berechnen', 'admin'),
('german', 'admin.tax_reports', 'Steuerberichte', 'admin'),
('german', 'admin.tax_reports_desc', 'Steuerberichte für die Buchhaltung herunterladen', 'admin'),
('german', 'admin.generate_report', 'Bericht erstellen', 'admin'),
('german', 'common.configure', 'Konfigurieren', 'common'),
('german', 'admin.subscription_revenue_overview', 'Übersicht Abonnement-Einnahmen', 'admin'),
('german', 'admin.mrr_metrics', 'Monatlich wiederkehrende Einnahmen und Abonnement-Metriken', 'admin'),
('german', 'admin.monthly_recurring_revenue', 'Monatlich wiederkehrende Einnahmen', 'admin'),
('german', 'admin.mrr_change', '+8,4% gegenüber Vormonat', 'admin'),
('german', 'admin.active_subscribers', 'Aktive Abonnenten', 'admin'),
('german', 'admin.new_subscribers_month', '+23 neue Abonnenten diesen Monat', 'admin'),
('german', 'admin.avg_revenue_per_user', 'Durchschnittlicher Umsatz pro Nutzer', 'admin'),
('german', 'admin.arpu_change', '+1,25$ gegenüber Vormonat', 'admin'),
('german', 'admin.monthly_revenue_year', 'Monatliche Einnahmen (2023)', 'admin'),
('german', 'admin.subscription_plans', 'Abonnementpläne', 'admin'),
('german', 'admin.subscribers', 'Abonnenten', 'admin'),
('german', 'admin.churn_rate', 'Abwanderungsrate', 'admin'),
('german', 'admin.monthly_churn', 'Monatliche Abwanderung', 'admin'),
('german', 'admin.annual_projection', 'Jahresprognose', 'admin'),
('german', 'admin.requires_attention', 'Erfordert Aufmerksamkeit', 'admin'),
('german', 'admin.ai_powered_admin', 'KI-gestützte Verwaltung', 'admin'),
('german', 'admin.ai_admin_desc', 'Unsere KI-Systeme verbessern die Verwaltungsfähigkeiten der Plattform', 'admin'),

('kurdish_sorani', 'admin.transactions', 'مامەڵەکان', 'admin'),
('kurdish_sorani', 'admin.subscription_revenue', 'داهاتی بەشداری', 'admin'),
('kurdish_sorani', 'admin.payment_settings', 'ڕێکخستنەکانی پارەدان', 'admin'),
('kurdish_sorani', 'admin.payment_refunded_success', 'پارە بە سەرکەوتوویی گەڕێنرایەوە', 'admin'),
('kurdish_sorani', 'admin.payment_refund_failed', 'گەڕاندنەوەی پارە سەرنەکەوت', 'admin'),
('kurdish_sorani', 'admin.receipt_resent_to', 'پسوولە دووبارە نێردرا بۆ {{email}}', 'admin'),
('kurdish_sorani', 'admin.payment_processing', 'چارەسەرکردنی پارەدان', 'admin'),
('kurdish_sorani', 'admin.manage_payment_transactions', 'بەڕێوەبردنی مامەڵە و قەرزەکانی پارەدان', 'admin'),
('kurdish_sorani', 'admin.total_revenue', 'کۆی داهات', 'admin'),
('kurdish_sorani', 'admin.todays_revenue', 'داهاتی ئەمڕۆ', 'admin'),
('kurdish_sorani', 'admin.pending_payments', 'پارەدانە چاوەڕوانەکان', 'admin'),
('kurdish_sorani', 'admin.view_receipt', 'بینینی پسوولە', 'admin'),
('kurdish_sorani', 'admin.no_payment_transactions', 'هیچ مامەڵەیەکی پارەدان نەدۆزرایەوە', 'admin'),
('kurdish_sorani', 'admin.all_statuses', 'هەموو بارەکان', 'admin'),
('kurdish_sorani', 'admin.all_methods', 'هەموو ڕێگاکان', 'admin'),
('kurdish_sorani', 'admin.date_range', 'ماوەی بەروار', 'admin'),
('kurdish_sorani', 'admin.filter_by_date', 'فلتەرکردن بە بەروار', 'admin'),
('kurdish_sorani', 'common.today', 'ئەمڕۆ', 'common'),
('kurdish_sorani', 'common.yesterday', 'دوێنێ', 'common'),
('kurdish_sorani', 'admin.this_week', 'ئەم هەفتەیە', 'admin'),
('kurdish_sorani', 'admin.this_month', 'ئەم مانگە', 'admin'),
('kurdish_sorani', 'admin.last_month', 'مانگی پێشوو', 'admin'),
('kurdish_sorani', 'admin.all_time', 'هەموو کات', 'admin'),
('kurdish_sorani', 'admin.payment_receipt', 'پسوولەی پارەدان', 'admin'),
('kurdish_sorani', 'admin.receipt', 'پسوولە', 'admin'),
('kurdish_sorani', 'admin.billed_to', 'قەرزکراوە بۆ', 'admin'),
('kurdish_sorani', 'admin.payment_info', 'زانیاری پارەدان', 'admin'),
('kurdish_sorani', 'admin.subtotal', 'کۆی لاوەکی', 'admin'),
('kurdish_sorani', 'admin.tax', 'باج', 'admin'),
('kurdish_sorani', 'admin.total', 'کۆی گشتی', 'admin'),
('kurdish_sorani', 'admin.print', 'چاپکردن', 'admin'),
('kurdish_sorani', 'admin.download_pdf', 'داگرتنی PDF', 'admin'),
('kurdish_sorani', 'admin.email_receipt', 'ناردنی پسوولە', 'admin'),
('kurdish_sorani', 'admin.payment_gateways', 'دەروازەکانی پارەدان', 'admin'),
('kurdish_sorani', 'admin.not_configured', 'ڕێکنەخراوە', 'admin'),
('kurdish_sorani', 'common.active', 'چالاک', 'common'),
('kurdish_sorani', 'common.inactive', 'ناچالاک', 'common'),
('kurdish_sorani', 'admin.invoice_settings', 'ڕێکخستنەکانی پسوولە', 'admin'),
('kurdish_sorani', 'admin.tax_settings', 'ڕێکخستنەکانی باج', 'admin'),
('kurdish_sorani', 'admin.generate_report', 'دروستکردنی ڕاپۆرت', 'admin'),
('kurdish_sorani', 'common.configure', 'ڕێکخستن', 'common'),
('kurdish_sorani', 'admin.subscription_revenue_overview', 'پوختەی داهاتی بەشداری', 'admin'),
('kurdish_sorani', 'admin.monthly_recurring_revenue', 'داهاتی مانگانەی دووبارە', 'admin'),
('kurdish_sorani', 'admin.active_subscribers', 'بەشداربووە چالاکەکان', 'admin'),
('kurdish_sorani', 'admin.subscription_plans', 'پلانەکانی بەشداری', 'admin'),
('kurdish_sorani', 'admin.subscribers', 'بەشداربوو', 'admin'),
('kurdish_sorani', 'admin.churn_rate', 'ڕێژەی وازهێنان', 'admin'),
('kurdish_sorani', 'admin.requires_attention', 'پێویستی بە سەرنج هەیە', 'admin'),
('kurdish_sorani', 'admin.ai_powered_admin', 'بەڕێوەبردنی بە هێزی AI', 'admin'),
('kurdish_sorani', 'admin.ai_admin_desc', 'سیستەمەکانی AI تواناکانی بەڕێوەبردن باشتر دەکەن', 'admin'),
('kurdish_sorani', 'common.date', 'بەروار', 'common'),
('kurdish_sorani', 'common.customer', 'کڕیار', 'common'),
('kurdish_sorani', 'common.invoice', 'پسوولە', 'common'),
('kurdish_sorani', 'common.description', 'وەسف', 'common'),
('kurdish_sorani', 'common.method', 'ڕێگا', 'common'),
('kurdish_sorani', 'common.status', 'بار', 'common'),
('kurdish_sorani', 'common.actions', 'کردارەکان', 'common'),

('kurdish_kurmanji', 'admin.transactions', 'Danûstendin', 'admin'),
('kurdish_kurmanji', 'admin.subscription_revenue', 'Dahata Abonetiyê', 'admin'),
('kurdish_kurmanji', 'admin.payment_settings', 'Mîhengên Dravdanê', 'admin'),
('kurdish_kurmanji', 'admin.payment_refunded_success', 'Drav bi serkeftî hat vegerandin', 'admin'),
('kurdish_kurmanji', 'admin.payment_refund_failed', 'Vegerandina drav bi ser neket', 'admin'),
('kurdish_kurmanji', 'admin.receipt_resent_to', 'Fîş ji nû ve hat şandin bo {{email}}', 'admin'),
('kurdish_kurmanji', 'admin.payment_processing', 'Pêvajoya Dravdanê', 'admin'),
('kurdish_kurmanji', 'admin.manage_payment_transactions', 'Birêvebirina danûstendin û fatûreyên dravdanê', 'admin'),
('kurdish_kurmanji', 'admin.total_revenue', 'Dahata Giştî', 'admin'),
('kurdish_kurmanji', 'admin.todays_revenue', 'Dahata Îro', 'admin'),
('kurdish_kurmanji', 'admin.pending_payments', 'Dravdanên Li Bendê', 'admin'),
('kurdish_kurmanji', 'admin.view_receipt', 'Fîşê Bibîne', 'admin'),
('kurdish_kurmanji', 'admin.no_payment_transactions', 'Tu danûstendinek dravdanê nehat dîtin', 'admin'),
('kurdish_kurmanji', 'admin.all_statuses', 'Hemû Rewş', 'admin'),
('kurdish_kurmanji', 'admin.all_methods', 'Hemû Rêbaz', 'admin'),
('kurdish_kurmanji', 'admin.date_range', 'Navbera Dîrokê', 'admin'),
('kurdish_kurmanji', 'admin.filter_by_date', 'Li gorî dîrokê fîltre bike', 'admin'),
('kurdish_kurmanji', 'common.today', 'Îro', 'common'),
('kurdish_kurmanji', 'common.yesterday', 'Duh', 'common'),
('kurdish_kurmanji', 'admin.this_week', 'Vê Hefteyê', 'admin'),
('kurdish_kurmanji', 'admin.this_month', 'Vê Mehê', 'admin'),
('kurdish_kurmanji', 'admin.last_month', 'Meha Borî', 'admin'),
('kurdish_kurmanji', 'admin.all_time', 'Hemû Dem', 'admin'),
('kurdish_kurmanji', 'admin.payment_receipt', 'Fîşa Dravdanê', 'admin'),
('kurdish_kurmanji', 'admin.receipt', 'FÎŞ', 'admin'),
('kurdish_kurmanji', 'admin.billed_to', 'Fatûre Ji Bo', 'admin'),
('kurdish_kurmanji', 'admin.payment_info', 'Agahiyên Dravdanê', 'admin'),
('kurdish_kurmanji', 'admin.subtotal', 'Bihayê Qismî', 'admin'),
('kurdish_kurmanji', 'admin.tax', 'Bac', 'admin'),
('kurdish_kurmanji', 'admin.total', 'Giştî', 'admin'),
('kurdish_kurmanji', 'admin.print', 'Çapkirin', 'admin'),
('kurdish_kurmanji', 'admin.download_pdf', 'PDF Daxîne', 'admin'),
('kurdish_kurmanji', 'admin.email_receipt', 'Fîşê Bişîne', 'admin'),
('kurdish_kurmanji', 'admin.payment_gateways', 'Dergehên Dravdanê', 'admin'),
('kurdish_kurmanji', 'admin.not_configured', 'Nehatiye mîhengkirin', 'admin'),
('kurdish_kurmanji', 'common.active', 'Çalak', 'common'),
('kurdish_kurmanji', 'common.inactive', 'Neçalak', 'common'),
('kurdish_kurmanji', 'admin.invoice_settings', 'Mîhengên Fatûreyê', 'admin'),
('kurdish_kurmanji', 'admin.tax_settings', 'Mîhengên Bacê', 'admin'),
('kurdish_kurmanji', 'admin.generate_report', 'Raporê Çêke', 'admin'),
('kurdish_kurmanji', 'common.configure', 'Mîheng Bike', 'common'),
('kurdish_kurmanji', 'admin.subscription_revenue_overview', 'Dîmena Dahata Abonetiyê', 'admin'),
('kurdish_kurmanji', 'admin.monthly_recurring_revenue', 'Dahata Mehane ya Dubare', 'admin'),
('kurdish_kurmanji', 'admin.active_subscribers', 'Abonetiyên Çalak', 'admin'),
('kurdish_kurmanji', 'admin.subscription_plans', 'Planên Abonetiyê', 'admin'),
('kurdish_kurmanji', 'admin.subscribers', 'aboneker', 'admin'),
('kurdish_kurmanji', 'admin.churn_rate', 'Rêjeya Derketinê', 'admin'),
('kurdish_kurmanji', 'admin.requires_attention', 'Baldarî hewce ye', 'admin'),
('kurdish_kurmanji', 'admin.ai_powered_admin', 'Rêvebiriya bi hêza AI', 'admin'),
('kurdish_kurmanji', 'admin.ai_admin_desc', 'Pergalên me yên AI kapasîteyên rêvebirinê li ser platformê baştir dikin', 'admin'),
('kurdish_kurmanji', 'common.date', 'Dîrok', 'common'),
('kurdish_kurmanji', 'common.customer', 'Xerîdar', 'common'),
('kurdish_kurmanji', 'common.invoice', 'Fatûre', 'common'),
('kurdish_kurmanji', 'common.description', 'Danasîn', 'common'),
('kurdish_kurmanji', 'common.method', 'Rêbaz', 'common'),
('kurdish_kurmanji', 'common.status', 'Rewş', 'common'),
('kurdish_kurmanji', 'common.actions', 'Kiryar', 'common')

ON CONFLICT (language_code, translation_key) DO UPDATE SET translation_value = EXCLUDED.translation_value;
