
INSERT INTO public.app_translations (language_code, translation_key, translation_value, category) VALUES
-- ResendReceiptDialog
('english','admin.resend_receipt','Resend Receipt','admin'),
('norwegian','admin.resend_receipt','Send kvittering på nytt','admin'),
('kurdish_sorani','admin.resend_receipt','ناردنەوەی پسوولە','admin'),
('kurdish_kurmanci','admin.resend_receipt','Ji nû ve şandina fatûreyê','admin'),
('german','admin.resend_receipt','Beleg erneut senden','admin'),
('english','admin.resend_receipt_desc','Resend the receipt to the customer''s email address.','admin'),
('norwegian','admin.resend_receipt_desc','Send kvitteringen til kundens e-postadresse.','admin'),
('kurdish_sorani','admin.resend_receipt_desc','پسوولەکە بنێرەوە بۆ ئیمەیڵی کڕیار.','admin'),
('kurdish_kurmanci','admin.resend_receipt_desc','Fatûreyê ji nû ve bişîne bo e-nameya xerîdar.','admin'),
('german','admin.resend_receipt_desc','Beleg erneut an die E-Mail-Adresse des Kunden senden.','admin'),
('english','admin.resend_for_transaction','Resend receipt for transaction','admin'),
('norwegian','admin.resend_for_transaction','Send kvittering på nytt for transaksjon','admin'),
('kurdish_sorani','admin.resend_for_transaction','ناردنەوەی پسوولە بۆ مامەڵە','admin'),
('kurdish_kurmanci','admin.resend_for_transaction','Ji nû ve şandina fatûreyê bo danûstendinê','admin'),
('german','admin.resend_for_transaction','Beleg erneut senden für Transaktion','admin'),
('english','admin.send_receipt','Send Receipt','admin'),
('norwegian','admin.send_receipt','Send kvittering','admin'),
('kurdish_sorani','admin.send_receipt','ناردنی پسوولە','admin'),
('kurdish_kurmanci','admin.send_receipt','Şandina fatûreyê','admin'),
('german','admin.send_receipt','Beleg senden','admin'),
-- RefundDialog
('english','admin.process_refund','Process Refund','admin'),
('norwegian','admin.process_refund','Behandle refusjon','admin'),
('kurdish_sorani','admin.process_refund','گەڕاندنەوەی پارە','admin'),
('kurdish_kurmanci','admin.process_refund','Vegerandina pere','admin'),
('german','admin.process_refund','Erstattung verarbeiten','admin'),
('english','admin.process_refund_desc','Process a refund for this transaction.','admin'),
('norwegian','admin.process_refund_desc','Behandle en refusjon for denne transaksjonen.','admin'),
('kurdish_sorani','admin.process_refund_desc','گەڕاندنەوەی پارە بۆ ئەم مامەڵەیە.','admin'),
('kurdish_kurmanci','admin.process_refund_desc','Vegerandina pere bo vê danûstendinê.','admin'),
('german','admin.process_refund_desc','Erstattung für diese Transaktion verarbeiten.','admin'),
('english','admin.process_refund_for','Process refund for:','admin'),
('norwegian','admin.process_refund_for','Behandle refusjon for:','admin'),
('kurdish_sorani','admin.process_refund_for','گەڕاندنەوەی پارە بۆ:','admin'),
('kurdish_kurmanci','admin.process_refund_for','Vegerandina pere bo:','admin'),
('german','admin.process_refund_for','Erstattung verarbeiten für:','admin'),
('english','admin.refund_warning','This action cannot be undone. The customer will be refunded the full amount.','admin'),
('norwegian','admin.refund_warning','Denne handlingen kan ikke angres. Kunden vil bli refundert hele beløpet.','admin'),
('kurdish_sorani','admin.refund_warning','ئەم کارە ناگەڕێتەوە. کڕیار تەواوی بڕەکە دەگەڕێنرێتەوە.','admin'),
('kurdish_kurmanci','admin.refund_warning','Ev çalakî nayê paşguhkirin. Xerîdar dê tevahiya meblexê vegerîne.','admin'),
('german','admin.refund_warning','Diese Aktion kann nicht rückgängig gemacht werden. Der Kunde erhält den vollen Betrag zurück.','admin'),
-- Common labels
('english','common.transaction','Transaction','common'),
('norwegian','common.transaction','Transaksjon','common'),
('kurdish_sorani','common.transaction','مامەڵە','common'),
('kurdish_kurmanci','common.transaction','Danûstendin','common'),
('german','common.transaction','Transaktion','common'),
('english','common.date','Date','common'),
('norwegian','common.date','Dato','common'),
('kurdish_sorani','common.date','بەروار','common'),
('kurdish_kurmanci','common.date','Dîrok','common'),
('german','common.date','Datum','common'),
('english','common.amount','Amount','common'),
('norwegian','common.amount','Beløp','common'),
('kurdish_sorani','common.amount','بڕ','common'),
('kurdish_kurmanci','common.amount','Meblax','common'),
('german','common.amount','Betrag','common'),
('english','common.to','to:','common'),
('norwegian','common.to','til:','common'),
('kurdish_sorani','common.to','بۆ:','common'),
('kurdish_kurmanci','common.to','bo:','common'),
('german','common.to','an:','common'),
-- Users PageHeader
('english','admin.users_management','Users Management','admin'),
('norwegian','admin.users_management','Brukeradministrasjon','admin'),
('kurdish_sorani','admin.users_management','بەڕێوەبردنی بەکارهێنەران','admin'),
('kurdish_kurmanci','admin.users_management','Rêvebirina bikarhêneran','admin'),
('german','admin.users_management','Benutzerverwaltung','admin'),
('english','admin.manage_real_users','Manage real users who registered through your app','admin'),
('norwegian','admin.manage_real_users','Administrer ekte brukere som registrerte seg gjennom appen din','admin'),
('kurdish_sorani','admin.manage_real_users','بەڕێوەبردنی بەکارهێنەرانی ڕاستەقینە کە لە ڕێگەی ئەپەکەت تۆمارکراون','admin'),
('kurdish_kurmanci','admin.manage_real_users','Rêvebirina bikarhênerên rastîn ên ku bi rêya sepana te qeyd bûne','admin'),
('german','admin.manage_real_users','Verwalten Sie echte Benutzer, die sich über Ihre App registriert haben','admin'),
('english','admin.export_users','Export Users','admin'),
('norwegian','admin.export_users','Eksporter brukere','admin'),
('kurdish_sorani','admin.export_users','هەناردەکردنی بەکارهێنەران','admin'),
('kurdish_kurmanci','admin.export_users','Derxistina bikarhêneran','admin'),
('german','admin.export_users','Benutzer exportieren','admin'),
('english','admin.user_management','User Management','admin'),
('norwegian','admin.user_management','Brukeradministrasjon','admin'),
('kurdish_sorani','admin.user_management','بەڕێوەبردنی بەکارهێنەر','admin'),
('kurdish_kurmanci','admin.user_management','Rêvebirina bikarhêner','admin'),
('german','admin.user_management','Benutzerverwaltung','admin'),
('english','admin.real_users_only','Real Users Only','admin'),
('norwegian','admin.real_users_only','Kun ekte brukere','admin'),
('kurdish_sorani','admin.real_users_only','تەنها بەکارهێنەرانی ڕاستەقینە','admin'),
('kurdish_kurmanci','admin.real_users_only','Tenê bikarhênerên rastîn','admin'),
('german','admin.real_users_only','Nur echte Benutzer','admin'),
('english','admin.real_users_info','This page now shows only real users who registered through your app''s normal registration process. To see users here, have them register at /register. All test data generation has been disabled.','admin'),
('norwegian','admin.real_users_info','Denne siden viser nå kun ekte brukere som registrerte seg gjennom appens normale registreringsprosess. For å se brukere her, la dem registrere seg på /register. All testdatagenerering er deaktivert.','admin'),
('kurdish_sorani','admin.real_users_info','ئەم پەڕەیە تەنها بەکارهێنەرانی ڕاستەقینە پیشان دەدات. بۆ بینینی بەکارهێنەران لێرە، وا لێ بکە لە /register تۆمار بکەن.','admin'),
('kurdish_kurmanci','admin.real_users_info','Ev rûpel niha tenê bikarhênerên rastîn nîşan dide. Ji bo dîtina bikarhêneran li vir, wan li /register qeyd bikin.','admin'),
('german','admin.real_users_info','Diese Seite zeigt jetzt nur echte Benutzer, die sich über den normalen Registrierungsprozess registriert haben. Damit Benutzer hier erscheinen, lassen Sie sie sich unter /register registrieren.','admin'),
-- Roles PageHeader
('english','admin.role_management','Role Management','admin'),
('norwegian','admin.role_management','Rolleadministrasjon','admin'),
('kurdish_sorani','admin.role_management','بەڕێوەبردنی ڕۆڵ','admin'),
('kurdish_kurmanci','admin.role_management','Rêvebirina rolan','admin'),
('german','admin.role_management','Rollenverwaltung','admin'),
('english','admin.new_role','New Role','admin'),
('norwegian','admin.new_role','Ny rolle','admin'),
('kurdish_sorani','admin.new_role','ڕۆڵی نوێ','admin'),
('kurdish_kurmanci','admin.new_role','Rola nû','admin'),
('german','admin.new_role','Neue Rolle','admin'),
-- TransactionsTab
('english','admin.payment_transactions','Payment Transactions','admin'),
('norwegian','admin.payment_transactions','Betalingstransaksjoner','admin'),
('kurdish_sorani','admin.payment_transactions','مامەڵەکانی پارەدان','admin'),
('kurdish_kurmanci','admin.payment_transactions','Danûstendinên dravdanê','admin'),
('german','admin.payment_transactions','Zahlungstransaktionen','admin'),
('english','admin.view_manage_transactions','View and manage all payment transactions','admin'),
('norwegian','admin.view_manage_transactions','Se og administrer alle betalingstransaksjoner','admin'),
('kurdish_sorani','admin.view_manage_transactions','بینین و بەڕێوەبردنی هەموو مامەڵەکانی پارەدان','admin'),
('kurdish_kurmanci','admin.view_manage_transactions','Dîtin û rêvebirina hemû danûstendinên dravdanê','admin'),
('german','admin.view_manage_transactions','Alle Zahlungstransaktionen anzeigen und verwalten','admin'),
-- AdminLoginForm
('english','auth.email_label','Email','auth'),
('norwegian','auth.email_label','E-post','auth'),
('kurdish_sorani','auth.email_label','ئیمەیڵ','auth'),
('kurdish_kurmanci','auth.email_label','E-name','auth'),
('german','auth.email_label','E-Mail','auth'),
('english','auth.password_label','Password','auth'),
('norwegian','auth.password_label','Passord','auth'),
('kurdish_sorani','auth.password_label','وشەی نهێنی','auth'),
('kurdish_kurmanci','auth.password_label','Şîfre','auth'),
('german','auth.password_label','Passwort','auth'),
('english','auth.verifying_credentials','Verifying Credentials...','auth'),
('norwegian','auth.verifying_credentials','Verifiserer legitimasjon...','auth'),
('kurdish_sorani','auth.verifying_credentials','پشتڕاستکردنەوەی ناسنامە...','auth'),
('kurdish_kurmanci','auth.verifying_credentials','Pejirandina pêbaweriyê...','auth'),
('german','auth.verifying_credentials','Anmeldedaten werden überprüft...','auth'),
('english','auth.access_dashboard','Access Dashboard','auth'),
('norwegian','auth.access_dashboard','Gå til dashbord','auth'),
('kurdish_sorani','auth.access_dashboard','چوونە داشبۆرد','auth'),
('kurdish_kurmanci','auth.access_dashboard','Têketina dashboard','auth'),
('german','auth.access_dashboard','Zum Dashboard','admin'),
-- UsersPage
('english','admin.admin_responsibility','Administrator Responsibility','admin'),
('norwegian','admin.admin_responsibility','Administratoransvar','admin'),
('kurdish_sorani','admin.admin_responsibility','بەرپرسیاریەتی بەڕێوەبەر','admin'),
('kurdish_kurmanci','admin.admin_responsibility','Berpirsyariya rêvebir','admin'),
('german','admin.admin_responsibility','Administratorverantwortung','admin'),
('english','admin.sensitive_data_warning','You are viewing sensitive user data. Handle this information with the utmost care and respect for user privacy. All actions are logged.','admin'),
('norwegian','admin.sensitive_data_warning','Du ser på sensitive brukerdata. Behandle denne informasjonen med største forsiktighet og respekt for brukerens personvern. Alle handlinger logges.','admin'),
('kurdish_sorani','admin.sensitive_data_warning','تۆ زانیاری هەستیاری بەکارهێنەر دەبینیت. ئەم زانیاریانە بە وریایی و ڕێزگرتن لە تایبەتمەندی بەکارهێنەر بخەرە بەکار. هەموو کارەکان تۆمار دەکرێن.','admin'),
('kurdish_kurmanci','admin.sensitive_data_warning','Tu daneyên hestiyar ên bikarhêner dibînî. Vê agahiyê bi baldarî û rêzgirtinê ji bo nepeniya bikarhêner bi kar bîne. Hemû çalakî tên tomarkirin.','admin'),
('german','admin.sensitive_data_warning','Sie sehen sensible Benutzerdaten. Behandeln Sie diese Informationen mit größter Sorgfalt und Respekt für die Privatsphäre der Benutzer. Alle Aktionen werden protokolliert.','admin')
ON CONFLICT DO NOTHING;
