
INSERT INTO public.app_translations (language_code, translation_key, translation_value, category, context)
VALUES
-- Registration form keys
('english','reg.incomplete_registration','Incomplete Registration','auth','EnhancedDynamicRegistrationForm'),
('english','reg.complete_step_before_submit','Please complete "{{step}}" step before submitting.','auth','EnhancedDynamicRegistrationForm'),
('english','reg.validation_error','Validation Error','auth','EnhancedDynamicRegistrationForm'),
('english','reg.fix_errors_in','Please fix the errors before submitting.','auth','EnhancedDynamicRegistrationForm'),
('english','reg.registration_error','Registration Error','auth','EnhancedDynamicRegistrationForm'),
('english','reg.unable_to_load','Unable to load registration form. Please refresh the page.','auth','EnhancedDynamicRegistrationForm'),
('english','reg.welcome','Welcome!','auth','EnhancedDynamicRegistrationForm'),
('english','reg.social_connected','Your social account has been connected. Please complete the registration to finish setting up your profile.','auth','EnhancedDynamicRegistrationForm'),
('english','reg.or_continue_email','or continue with email','auth','EnhancedDynamicRegistrationForm'),
('english','reg.complete_info_note','Complete all required information to create your perfect profile. Your data is secure and only visible to potential matches.','auth','EnhancedDynamicRegistrationForm'),
('english','reg.previous','Previous','auth','EnhancedFormNavigation'),
('english','reg.step_of','Step {{current}} of {{total}}','auth','EnhancedFormNavigation'),
('english','reg.creating_account','Creating Account...','auth','EnhancedFormNavigation'),
('english','reg.creating','Creating...','auth','EnhancedFormNavigation'),
('english','reg.complete_registration','Complete Registration','auth','EnhancedFormNavigation'),
('english','reg.complete','Complete','auth','EnhancedFormNavigation'),
('english','reg.continue','Continue','auth','EnhancedFormNavigation'),
('english','reg.incomplete','Incomplete','auth','EnhancedStepRenderer'),
('english','reg.all_fields_completed','All required fields completed','auth','EnhancedStepRenderer'),
('english','reg.complete_required_fields','Please complete all required fields to continue','auth','EnhancedStepRenderer'),
('english','reg.current_location','Current Location','auth','EnhancedStepRenderer'),
('english','reg.detecting_location','Detecting location...','auth','EnhancedStepRenderer'),
('english','reg.enter_city','Enter your city','auth','EnhancedStepRenderer'),
('english','reg.in_progress','In Progress','auth','EnhancedStepIndicator'),
('english','reg.step_of_name','Step {{current}} of {{total}}: {{name}}','auth','EnhancedStepIndicator'),
('english','reg.steps_completed','{{done}} of {{total}} steps completed','auth','EnhancedStepIndicator'),
-- Admin keys
('english','admin.super_admin_access','Super Admin Access','admin','SuperAdminLogin'),
('english','admin.restricted_area','Restricted area - Authorized personnel only','admin','SuperAdminLogin'),
('english','admin.verifying_setup','Verifying admin account setup...','admin','SetupStatus'),
('english','admin.configure_supabase','Configure Supabase Setup','admin','SetupStatus'),
('english','admin.retry_in','Retry available in {{seconds}}s','admin','SetupStatus'),
('english','admin.ready_to_retry','Ready to retry','admin','SetupStatus'),
('english','admin.retry_setup','Retry Setup','admin','SetupStatus'),
('english','admin.clear_cache_retry','Clear Cache & Retry','admin','SetupStatus'),
('english','admin.account_ready','Admin account is ready! You can now log in.','admin','SetupStatus'),
('english','admin.back_to_admin_login','Back to Admin Login','admin','SuperAdminSetup'),
('english','admin.setup_required','Super Admin Setup Required','admin','SuperAdminSetup'),
('english','admin.configure_supabase_desc','Configure your Supabase environment to enable super admin functionality','admin','SuperAdminSetup'),

-- Norwegian
('norwegian','reg.incomplete_registration','Ufullstendig registrering','auth','EnhancedDynamicRegistrationForm'),
('norwegian','reg.complete_step_before_submit','Vennligst fullfør "{{step}}" trinnet før du sender inn.','auth','EnhancedDynamicRegistrationForm'),
('norwegian','reg.validation_error','Valideringsfeil','auth','EnhancedDynamicRegistrationForm'),
('norwegian','reg.fix_errors_in','Vennligst rett feilene før du sender inn.','auth','EnhancedDynamicRegistrationForm'),
('norwegian','reg.registration_error','Registreringsfeil','auth','EnhancedDynamicRegistrationForm'),
('norwegian','reg.unable_to_load','Kan ikke laste registreringsskjemaet. Vennligst oppdater siden.','auth','EnhancedDynamicRegistrationForm'),
('norwegian','reg.welcome','Velkommen!','auth','EnhancedDynamicRegistrationForm'),
('norwegian','reg.social_connected','Din sosiale konto er tilkoblet. Vennligst fullfør registreringen for å sette opp profilen din.','auth','EnhancedDynamicRegistrationForm'),
('norwegian','reg.or_continue_email','eller fortsett med e-post','auth','EnhancedDynamicRegistrationForm'),
('norwegian','reg.complete_info_note','Fyll ut all nødvendig informasjon for å lage din perfekte profil. Dine data er sikre og kun synlige for potensielle matcher.','auth','EnhancedDynamicRegistrationForm'),
('norwegian','reg.previous','Forrige','auth','EnhancedFormNavigation'),
('norwegian','reg.step_of','Trinn {{current}} av {{total}}','auth','EnhancedFormNavigation'),
('norwegian','reg.creating_account','Oppretter konto...','auth','EnhancedFormNavigation'),
('norwegian','reg.creating','Oppretter...','auth','EnhancedFormNavigation'),
('norwegian','reg.complete_registration','Fullfør registrering','auth','EnhancedFormNavigation'),
('norwegian','reg.complete','Fullført','auth','EnhancedFormNavigation'),
('norwegian','reg.continue','Fortsett','auth','EnhancedFormNavigation'),
('norwegian','reg.incomplete','Ufullstendig','auth','EnhancedStepRenderer'),
('norwegian','reg.all_fields_completed','Alle nødvendige felt er fylt ut','auth','EnhancedStepRenderer'),
('norwegian','reg.complete_required_fields','Vennligst fyll ut alle obligatoriske felt for å fortsette','auth','EnhancedStepRenderer'),
('norwegian','reg.current_location','Nåværende plassering','auth','EnhancedStepRenderer'),
('norwegian','reg.detecting_location','Oppdager plassering...','auth','EnhancedStepRenderer'),
('norwegian','reg.enter_city','Skriv inn byen din','auth','EnhancedStepRenderer'),
('norwegian','reg.in_progress','Pågår','auth','EnhancedStepIndicator'),
('norwegian','reg.step_of_name','Trinn {{current}} av {{total}}: {{name}}','auth','EnhancedStepIndicator'),
('norwegian','reg.steps_completed','{{done}} av {{total}} trinn fullført','auth','EnhancedStepIndicator'),
('norwegian','admin.super_admin_access','Superadmin-tilgang','admin','SuperAdminLogin'),
('norwegian','admin.restricted_area','Begrenset område - Kun autorisert personell','admin','SuperAdminLogin'),
('norwegian','admin.verifying_setup','Verifiserer admin-kontooppsett...','admin','SetupStatus'),
('norwegian','admin.configure_supabase','Konfigurer Supabase-oppsett','admin','SetupStatus'),
('norwegian','admin.retry_in','Nytt forsøk tilgjengelig om {{seconds}}s','admin','SetupStatus'),
('norwegian','admin.ready_to_retry','Klar til å prøve igjen','admin','SetupStatus'),
('norwegian','admin.retry_setup','Prøv oppsett igjen','admin','SetupStatus'),
('norwegian','admin.clear_cache_retry','Tøm hurtigbuffer og prøv igjen','admin','SetupStatus'),
('norwegian','admin.account_ready','Admin-kontoen er klar! Du kan nå logge inn.','admin','SetupStatus'),
('norwegian','admin.back_to_admin_login','Tilbake til admin-innlogging','admin','SuperAdminSetup'),
('norwegian','admin.setup_required','Superadmin-oppsett påkrevd','admin','SuperAdminSetup'),
('norwegian','admin.configure_supabase_desc','Konfigurer Supabase-miljøet ditt for å aktivere superadmin-funksjonalitet','admin','SuperAdminSetup'),

-- German
('german','reg.incomplete_registration','Unvollständige Registrierung','auth','EnhancedDynamicRegistrationForm'),
('german','reg.complete_step_before_submit','Bitte schließen Sie den Schritt "{{step}}" ab, bevor Sie absenden.','auth','EnhancedDynamicRegistrationForm'),
('german','reg.validation_error','Validierungsfehler','auth','EnhancedDynamicRegistrationForm'),
('german','reg.fix_errors_in','Bitte beheben Sie die Fehler vor dem Absenden.','auth','EnhancedDynamicRegistrationForm'),
('german','reg.registration_error','Registrierungsfehler','auth','EnhancedDynamicRegistrationForm'),
('german','reg.unable_to_load','Registrierungsformular konnte nicht geladen werden. Bitte aktualisieren Sie die Seite.','auth','EnhancedDynamicRegistrationForm'),
('german','reg.welcome','Willkommen!','auth','EnhancedDynamicRegistrationForm'),
('german','reg.social_connected','Ihr Social-Media-Konto wurde verbunden. Bitte schließen Sie die Registrierung ab, um Ihr Profil einzurichten.','auth','EnhancedDynamicRegistrationForm'),
('german','reg.or_continue_email','oder mit E-Mail fortfahren','auth','EnhancedDynamicRegistrationForm'),
('german','reg.complete_info_note','Füllen Sie alle erforderlichen Informationen aus, um Ihr perfektes Profil zu erstellen. Ihre Daten sind sicher und nur für potenzielle Matches sichtbar.','auth','EnhancedDynamicRegistrationForm'),
('german','reg.previous','Zurück','auth','EnhancedFormNavigation'),
('german','reg.step_of','Schritt {{current}} von {{total}}','auth','EnhancedFormNavigation'),
('german','reg.creating_account','Konto wird erstellt...','auth','EnhancedFormNavigation'),
('german','reg.creating','Erstellen...','auth','EnhancedFormNavigation'),
('german','reg.complete_registration','Registrierung abschließen','auth','EnhancedFormNavigation'),
('german','reg.complete','Abgeschlossen','auth','EnhancedFormNavigation'),
('german','reg.continue','Weiter','auth','EnhancedFormNavigation'),
('german','reg.incomplete','Unvollständig','auth','EnhancedStepRenderer'),
('german','reg.all_fields_completed','Alle Pflichtfelder ausgefüllt','auth','EnhancedStepRenderer'),
('german','reg.complete_required_fields','Bitte füllen Sie alle Pflichtfelder aus, um fortzufahren','auth','EnhancedStepRenderer'),
('german','reg.current_location','Aktueller Standort','auth','EnhancedStepRenderer'),
('german','reg.detecting_location','Standort wird ermittelt...','auth','EnhancedStepRenderer'),
('german','reg.enter_city','Geben Sie Ihre Stadt ein','auth','EnhancedStepRenderer'),
('german','reg.in_progress','In Bearbeitung','auth','EnhancedStepIndicator'),
('german','reg.step_of_name','Schritt {{current}} von {{total}}: {{name}}','auth','EnhancedStepIndicator'),
('german','reg.steps_completed','{{done}} von {{total}} Schritten abgeschlossen','auth','EnhancedStepIndicator'),
('german','admin.super_admin_access','Superadmin-Zugang','admin','SuperAdminLogin'),
('german','admin.restricted_area','Eingeschränkter Bereich - Nur autorisiertes Personal','admin','SuperAdminLogin'),
('german','admin.verifying_setup','Admin-Kontoeinrichtung wird überprüft...','admin','SetupStatus'),
('german','admin.configure_supabase','Supabase-Einrichtung konfigurieren','admin','SetupStatus'),
('german','admin.retry_in','Erneuter Versuch in {{seconds}}s verfügbar','admin','SetupStatus'),
('german','admin.ready_to_retry','Bereit für erneuten Versuch','admin','SetupStatus'),
('german','admin.retry_setup','Einrichtung erneut versuchen','admin','SetupStatus'),
('german','admin.clear_cache_retry','Cache leeren und erneut versuchen','admin','SetupStatus'),
('german','admin.account_ready','Admin-Konto ist bereit! Sie können sich jetzt anmelden.','admin','SetupStatus'),
('german','admin.back_to_admin_login','Zurück zur Admin-Anmeldung','admin','SuperAdminSetup'),
('german','admin.setup_required','Superadmin-Einrichtung erforderlich','admin','SuperAdminSetup'),
('german','admin.configure_supabase_desc','Konfigurieren Sie Ihre Supabase-Umgebung, um die Superadmin-Funktionalität zu aktivieren','admin','SuperAdminSetup'),

-- Kurdish Sorani
('kurdish_sorani','reg.incomplete_registration','تۆمارکردنی نەتەواو','auth','EnhancedDynamicRegistrationForm'),
('kurdish_sorani','reg.complete_step_before_submit','تکایە هەنگاوی "{{step}}" تەواو بکە پێش ناردن.','auth','EnhancedDynamicRegistrationForm'),
('kurdish_sorani','reg.validation_error','هەڵەی پشتڕاستکردنەوە','auth','EnhancedDynamicRegistrationForm'),
('kurdish_sorani','reg.fix_errors_in','تکایە هەڵەکان چاکبکەرەوە پێش ناردن.','auth','EnhancedDynamicRegistrationForm'),
('kurdish_sorani','reg.registration_error','هەڵەی تۆمارکردن','auth','EnhancedDynamicRegistrationForm'),
('kurdish_sorani','reg.unable_to_load','فۆرمی تۆمارکردن بارنەکرا. تکایە پەڕەکە نوێ بکەرەوە.','auth','EnhancedDynamicRegistrationForm'),
('kurdish_sorani','reg.welcome','بەخێربێیت!','auth','EnhancedDynamicRegistrationForm'),
('kurdish_sorani','reg.social_connected','هەژماری کۆمەڵایەتیت پەیوەندی کرا. تکایە تۆمارکردنەکە تەواو بکە بۆ دامەزراندنی پرۆفایلەکەت.','auth','EnhancedDynamicRegistrationForm'),
('kurdish_sorani','reg.or_continue_email','یان بەردەوامبە بە ئیمەیل','auth','EnhancedDynamicRegistrationForm'),
('kurdish_sorani','reg.complete_info_note','هەموو زانیارییە پێویستەکان تەواو بکە بۆ دروستکردنی پرۆفایلی تەواوت. زانیارییەکانت پارێزراون و تەنها بۆ هاوتاکانی گونجاو دەبینرێت.','auth','EnhancedDynamicRegistrationForm'),
('kurdish_sorani','reg.previous','پێشوو','auth','EnhancedFormNavigation'),
('kurdish_sorani','reg.step_of','هەنگاوی {{current}} لە {{total}}','auth','EnhancedFormNavigation'),
('kurdish_sorani','reg.creating_account','هەژمار دروست دەکرێت...','auth','EnhancedFormNavigation'),
('kurdish_sorani','reg.creating','دروستکردن...','auth','EnhancedFormNavigation'),
('kurdish_sorani','reg.complete_registration','تەواوکردنی تۆمارکردن','auth','EnhancedFormNavigation'),
('kurdish_sorani','reg.complete','تەواو','auth','EnhancedFormNavigation'),
('kurdish_sorani','reg.continue','بەردەوامبوون','auth','EnhancedFormNavigation'),
('kurdish_sorani','reg.incomplete','نەتەواو','auth','EnhancedStepRenderer'),
('kurdish_sorani','reg.all_fields_completed','هەموو خانە پێویستەکان پڕکرانەوە','auth','EnhancedStepRenderer'),
('kurdish_sorani','reg.complete_required_fields','تکایە هەموو خانە پێویستەکان پڕبکەرەوە بۆ بەردەوامبوون','auth','EnhancedStepRenderer'),
('kurdish_sorani','reg.current_location','شوێنی ئێستا','auth','EnhancedStepRenderer'),
('kurdish_sorani','reg.detecting_location','شوێن دەدۆزرێتەوە...','auth','EnhancedStepRenderer'),
('kurdish_sorani','reg.enter_city','شارەکەت بنووسە','auth','EnhancedStepRenderer'),
('kurdish_sorani','reg.in_progress','لە بەردەست','auth','EnhancedStepIndicator'),
('kurdish_sorani','reg.step_of_name','هەنگاوی {{current}} لە {{total}}: {{name}}','auth','EnhancedStepIndicator'),
('kurdish_sorani','reg.steps_completed','{{done}} لە {{total}} هەنگاو تەواوکرا','auth','EnhancedStepIndicator'),
('kurdish_sorani','admin.super_admin_access','دەستگەیشتنی سوپەر ئەدمین','admin','SuperAdminLogin'),
('kurdish_sorani','admin.restricted_area','ناوچەی سنووردار - تەنها بۆ کەسانی مۆڵەتدار','admin','SuperAdminLogin'),
('kurdish_sorani','admin.verifying_setup','پشتڕاستکردنەوەی دامەزراندنی هەژماری ئەدمین...','admin','SetupStatus'),
('kurdish_sorani','admin.configure_supabase','ڕێکخستنی Supabase','admin','SetupStatus'),
('kurdish_sorani','admin.retry_in','هەوڵدانەوە بەردەستە لە {{seconds}} چرکەدا','admin','SetupStatus'),
('kurdish_sorani','admin.ready_to_retry','ئامادەیە بۆ هەوڵدانەوە','admin','SetupStatus'),
('kurdish_sorani','admin.retry_setup','هەوڵدانەوەی دامەزراندن','admin','SetupStatus'),
('kurdish_sorani','admin.clear_cache_retry','پاککردنەوەی کاش و هەوڵدانەوە','admin','SetupStatus'),
('kurdish_sorani','admin.account_ready','هەژماری ئەدمین ئامادەیە! ئێستا دەتوانیت بچیتە ژوورەوە.','admin','SetupStatus'),
('kurdish_sorani','admin.back_to_admin_login','گەڕانەوە بۆ چوونەژوورەوەی ئەدمین','admin','SuperAdminSetup'),
('kurdish_sorani','admin.setup_required','دامەزراندنی سوپەر ئەدمین پێویستە','admin','SuperAdminSetup'),
('kurdish_sorani','admin.configure_supabase_desc','ژینگەی Supabase ڕێکبخە بۆ چالاککردنی کارکردنی سوپەر ئەدمین','admin','SuperAdminSetup'),

-- Kurdish Kurmanci
('kurdish_kurmanci','reg.incomplete_registration','Tomarkirina netemam','auth','EnhancedDynamicRegistrationForm'),
('kurdish_kurmanci','reg.complete_step_before_submit','Ji kerema xwe gavê "{{step}}" temam bike berî şandanê.','auth','EnhancedDynamicRegistrationForm'),
('kurdish_kurmanci','reg.validation_error','Çewtiya erêkirinê','auth','EnhancedDynamicRegistrationForm'),
('kurdish_kurmanci','reg.fix_errors_in','Ji kerema xwe çewtiyan berî şandanê rast bike.','auth','EnhancedDynamicRegistrationForm'),
('kurdish_kurmanci','reg.registration_error','Çewtiya tomarkirinê','auth','EnhancedDynamicRegistrationForm'),
('kurdish_kurmanci','reg.unable_to_load','Forma tomarkirinê nehat barkirin. Ji kerema xwe rûpelê nû bike.','auth','EnhancedDynamicRegistrationForm'),
('kurdish_kurmanci','reg.welcome','Bi xêr hatî!','auth','EnhancedDynamicRegistrationForm'),
('kurdish_kurmanci','reg.social_connected','Hesabê te yê civakî hat girêdan. Ji kerema xwe tomarkirinê temam bike da ku profîla xwe saz bikî.','auth','EnhancedDynamicRegistrationForm'),
('kurdish_kurmanci','reg.or_continue_email','an jî bi e-nameyê bidomîne','auth','EnhancedDynamicRegistrationForm'),
('kurdish_kurmanci','reg.complete_info_note','Hemû agahiyên pêwîst temam bike da ku profîla xwe ya bêkêmasî çêbikî. Daneyên te ewle ne û tenê ji hevkarên guncaw re têne dîtin.','auth','EnhancedDynamicRegistrationForm'),
('kurdish_kurmanci','reg.previous','Berê','auth','EnhancedFormNavigation'),
('kurdish_kurmanci','reg.step_of','Gavê {{current}} ji {{total}}','auth','EnhancedFormNavigation'),
('kurdish_kurmanci','reg.creating_account','Hesab tê çêkirin...','auth','EnhancedFormNavigation'),
('kurdish_kurmanci','reg.creating','Çêkirin...','auth','EnhancedFormNavigation'),
('kurdish_kurmanci','reg.complete_registration','Tomarkirinê temam bike','auth','EnhancedFormNavigation'),
('kurdish_kurmanci','reg.complete','Temam','auth','EnhancedFormNavigation'),
('kurdish_kurmanci','reg.continue','Bidomîne','auth','EnhancedFormNavigation'),
('kurdish_kurmanci','reg.incomplete','Netemam','auth','EnhancedStepRenderer'),
('kurdish_kurmanci','reg.all_fields_completed','Hemû qadên pêwîst hatin dagirtin','auth','EnhancedStepRenderer'),
('kurdish_kurmanci','reg.complete_required_fields','Ji kerema xwe hemû qadên pêwîst dagire da ku bidomînî','auth','EnhancedStepRenderer'),
('kurdish_kurmanci','reg.current_location','Cihê niha','auth','EnhancedStepRenderer'),
('kurdish_kurmanci','reg.detecting_location','Cih tê dîtin...','auth','EnhancedStepRenderer'),
('kurdish_kurmanci','reg.enter_city','Bajarê xwe binivîse','auth','EnhancedStepRenderer'),
('kurdish_kurmanci','reg.in_progress','Di pêvajoyê de','auth','EnhancedStepIndicator'),
('kurdish_kurmanci','reg.step_of_name','Gavê {{current}} ji {{total}}: {{name}}','auth','EnhancedStepIndicator'),
('kurdish_kurmanci','reg.steps_completed','{{done}} ji {{total}} gavan temam bûn','auth','EnhancedStepIndicator'),
('kurdish_kurmanci','admin.super_admin_access','Gihîştina Super Admin','admin','SuperAdminLogin'),
('kurdish_kurmanci','admin.restricted_area','Devera sînordar - Tenê kesên destûrdar','admin','SuperAdminLogin'),
('kurdish_kurmanci','admin.verifying_setup','Sazkirina hesabê admin tê piştrastkirin...','admin','SetupStatus'),
('kurdish_kurmanci','admin.configure_supabase','Sazkirina Supabase mîheng bike','admin','SetupStatus'),
('kurdish_kurmanci','admin.retry_in','Hewldana nû di {{seconds}} çirkeyan de amade ye','admin','SetupStatus'),
('kurdish_kurmanci','admin.ready_to_retry','Ji bo hewldana nû amade ye','admin','SetupStatus'),
('kurdish_kurmanci','admin.retry_setup','Sazkirinê ji nû ve biceribîne','admin','SetupStatus'),
('kurdish_kurmanci','admin.clear_cache_retry','Cache paqij bike û ji nû ve biceribîne','admin','SetupStatus'),
('kurdish_kurmanci','admin.account_ready','Hesabê admin amade ye! Tu niha dikarî têkevî.','admin','SetupStatus'),
('kurdish_kurmanci','admin.back_to_admin_login','Vegere têketina admin','admin','SuperAdminSetup'),
('kurdish_kurmanci','admin.setup_required','Sazkirina Super Admin pêwîst e','admin','SuperAdminSetup'),
('kurdish_kurmanci','admin.configure_supabase_desc','Hawîrdora Supabase mîheng bike da ku fonksiyona super admin çalak bikî','admin','SuperAdminSetup')

ON CONFLICT (language_code, translation_key) DO NOTHING;
