
INSERT INTO public.app_translations (language_code, translation_key, translation_value, category, context)
VALUES
-- Profile editor placeholders (English)
('english','profile.select_education','Select education','profile','EducationCareerEditor placeholder'),
('english','profile.select_balance','Select balance','profile','EducationCareerEditor placeholder'),
('english','profile.your_job_title','Your job title','profile','EducationCareerEditor placeholder'),
('english','profile.where_you_work','Where you work','profile','EducationCareerEditor placeholder'),
('english','profile.describe_career_goals','Describe your career goals','profile','EducationCareerEditor placeholder'),
('english','profile.how_approach_work','How do you approach work?','profile','CareerEducationEditor placeholder'),
('english','profile.select_religion','Select religion','profile','ValuesPersonalityEditor placeholder'),
('english','profile.select_political_views','Select political views','profile','ValuesPersonalityEditor placeholder'),
('english','profile.select_zodiac','Select zodiac sign','profile','ValuesPersonalityEditor placeholder'),
('english','profile.select_type','Select type','profile','ValuesPersonalityEditor placeholder'),
('english','profile.looking_for','What are you looking for?','profile','RelationshipPreferencesEditor placeholder'),
('english','profile.thoughts_children','Your thoughts on children?','profile','RelationshipPreferencesEditor placeholder'),
('english','profile.how_close_family','How close to family?','profile','RelationshipPreferencesEditor placeholder'),
('english','profile.how_feel_loved','How do you feel loved?','profile','RelationshipPreferencesEditor placeholder'),
('english','profile.how_communicate','How do you communicate?','profile','RelationshipPreferencesEditor placeholder'),
('english','profile.describe_perfect_date','Describe your perfect date...','profile','RelationshipPreferencesEditor placeholder'),
('english','profile.how_often','How often?','profile','LifestyleEditor placeholder'),
('english','profile.diet_type','Diet type?','profile','LifestyleEditor placeholder'),
('english','profile.do_you_smoke','Do you smoke?','profile','LifestyleEditor placeholder'),
('english','profile.do_you_drink','Do you drink?','profile','LifestyleEditor placeholder'),
('english','profile.night_owl_early_bird','Night owl or early bird?','profile','LifestyleEditor placeholder'),
('english','profile.do_you_have_pets','Do you have pets?','profile','LifestyleEditor placeholder'),
('english','profile.quote_placeholder','A quote that inspires you...','profile','FavoritesEditor placeholder'),
('english','profile.dream_vacation_placeholder','Where would you love to travel?','profile','FavoritesEditor placeholder'),
('english','profile.about','About','profile','EditableAboutMeSection title'),
('english','profile.tell_about_yourself','Tell us about yourself... What makes you unique?','profile','EditableAboutMeSection placeholder'),
('english','profile.generate_ai_bio','Generate AI Bio','profile','EditableAboutMeSection button'),
('english','profile.tell_others','Tell others about yourself...','profile','EditableAboutMeSection empty state'),
('english','profile.add_your_bio','Add your bio','profile','EditableAboutMeSection button'),
-- Groups MembersDialog
('english','groups.group_members','Group Members','groups','MembersDialog title'),
('english','groups.view_manage_members','View and manage group members','groups','MembersDialog description'),
('english','groups.search_members','Search members...','groups','MembersDialog placeholder'),
('english','groups.no_members_found','No members found','groups','MembersDialog empty'),
('english','groups.no_members_yet','No members yet','groups','MembersDialog empty'),
('english','groups.joined','Joined','groups','MembersDialog label'),
-- Admin
('english','admin.loading_users','Loading users...','admin','AdminUsers loading'),
('english','admin.search_users','Search users...','admin','AdminUsers placeholder'),
('english','admin.no_users_found','No users found','admin','AdminUsers empty'),
('english','admin.joined','Joined','admin','AdminUsers label'),
('english','admin.moderate','Moderate','admin','AdminUsers button'),
-- Wizard Step7
('english','wizard.lets_talk_favorites','Let''s talk favorites!','wizard','Step7Favorites title'),
('english','wizard.share_what_you_love','Share what you love most','wizard','Step7Favorites subtitle'),
('english','wizard.what_love_read','What do you love to read?','wizard','Step7Favorites placeholder'),
('english','wizard.what_genres_enjoy','What genres do you enjoy?','wizard','Step7Favorites placeholder'),
('english','wizard.what_music_listen','What music do you listen to?','wizard','Step7Favorites placeholder'),
('english','wizard.what_cuisines_love','What cuisines do you love?','wizard','Step7Favorites placeholder'),
('english','wizard.what_games_enjoy','What games do you enjoy?','wizard','Step7Favorites placeholder'),
('english','wizard.what_podcasts_listen','What podcasts do you listen to?','wizard','Step7Favorites placeholder'),

-- Norwegian
('norwegian','profile.select_education','Velg utdanning','profile','placeholder'),
('norwegian','profile.select_balance','Velg balanse','profile','placeholder'),
('norwegian','profile.your_job_title','Din stillingstittel','profile','placeholder'),
('norwegian','profile.where_you_work','Hvor du jobber','profile','placeholder'),
('norwegian','profile.describe_career_goals','Beskriv dine karrieremål','profile','placeholder'),
('norwegian','profile.how_approach_work','Hvordan tilnærmer du deg arbeid?','profile','placeholder'),
('norwegian','profile.select_religion','Velg religion','profile','placeholder'),
('norwegian','profile.select_political_views','Velg politiske synspunkter','profile','placeholder'),
('norwegian','profile.select_zodiac','Velg stjernetegn','profile','placeholder'),
('norwegian','profile.select_type','Velg type','profile','placeholder'),
('norwegian','profile.looking_for','Hva ser du etter?','profile','placeholder'),
('norwegian','profile.thoughts_children','Dine tanker om barn?','profile','placeholder'),
('norwegian','profile.how_close_family','Hvor nær familien?','profile','placeholder'),
('norwegian','profile.how_feel_loved','Hvordan føler du deg elsket?','profile','placeholder'),
('norwegian','profile.how_communicate','Hvordan kommuniserer du?','profile','placeholder'),
('norwegian','profile.describe_perfect_date','Beskriv din perfekte date...','profile','placeholder'),
('norwegian','profile.how_often','Hvor ofte?','profile','placeholder'),
('norwegian','profile.diet_type','Kostholdstype?','profile','placeholder'),
('norwegian','profile.do_you_smoke','Røyker du?','profile','placeholder'),
('norwegian','profile.do_you_drink','Drikker du?','profile','placeholder'),
('norwegian','profile.night_owl_early_bird','Nattugle eller morgenfugl?','profile','placeholder'),
('norwegian','profile.do_you_have_pets','Har du kjæledyr?','profile','placeholder'),
('norwegian','profile.quote_placeholder','Et sitat som inspirerer deg...','profile','placeholder'),
('norwegian','profile.dream_vacation_placeholder','Hvor vil du gjerne reise?','profile','placeholder'),
('norwegian','profile.about','Om','profile','title'),
('norwegian','profile.tell_about_yourself','Fortell oss om deg selv... Hva gjør deg unik?','profile','placeholder'),
('norwegian','profile.generate_ai_bio','Generer AI-bio','profile','button'),
('norwegian','profile.tell_others','Fortell andre om deg selv...','profile','empty'),
('norwegian','profile.add_your_bio','Legg til din bio','profile','button'),
('norwegian','groups.group_members','Gruppemedlemmer','groups','title'),
('norwegian','groups.view_manage_members','Se og administrer gruppemedlemmer','groups','description'),
('norwegian','groups.search_members','Søk medlemmer...','groups','placeholder'),
('norwegian','groups.no_members_found','Ingen medlemmer funnet','groups','empty'),
('norwegian','groups.no_members_yet','Ingen medlemmer ennå','groups','empty'),
('norwegian','groups.joined','Ble med','groups','label'),
('norwegian','admin.loading_users','Laster brukere...','admin','loading'),
('norwegian','admin.search_users','Søk brukere...','admin','placeholder'),
('norwegian','admin.no_users_found','Ingen brukere funnet','admin','empty'),
('norwegian','admin.joined','Ble med','admin','label'),
('norwegian','admin.moderate','Moderer','admin','button'),
('norwegian','wizard.lets_talk_favorites','La oss snakke om favoritter!','wizard','title'),
('norwegian','wizard.share_what_you_love','Del det du elsker mest','wizard','subtitle'),
('norwegian','wizard.what_love_read','Hva liker du å lese?','wizard','placeholder'),
('norwegian','wizard.what_genres_enjoy','Hvilke sjangre liker du?','wizard','placeholder'),
('norwegian','wizard.what_music_listen','Hvilken musikk hører du på?','wizard','placeholder'),
('norwegian','wizard.what_cuisines_love','Hvilke kjøkken elsker du?','wizard','placeholder'),
('norwegian','wizard.what_games_enjoy','Hvilke spill liker du?','wizard','placeholder'),
('norwegian','wizard.what_podcasts_listen','Hvilke podkaster hører du på?','wizard','placeholder'),

-- German
('german','profile.select_education','Bildung auswählen','profile','placeholder'),
('german','profile.select_balance','Balance auswählen','profile','placeholder'),
('german','profile.your_job_title','Ihre Berufsbezeichnung','profile','placeholder'),
('german','profile.where_you_work','Wo Sie arbeiten','profile','placeholder'),
('german','profile.describe_career_goals','Beschreiben Sie Ihre Karriereziele','profile','placeholder'),
('german','profile.how_approach_work','Wie gehen Sie an die Arbeit heran?','profile','placeholder'),
('german','profile.select_religion','Religion auswählen','profile','placeholder'),
('german','profile.select_political_views','Politische Ansichten auswählen','profile','placeholder'),
('german','profile.select_zodiac','Sternzeichen auswählen','profile','placeholder'),
('german','profile.select_type','Typ auswählen','profile','placeholder'),
('german','profile.looking_for','Wonach suchen Sie?','profile','placeholder'),
('german','profile.thoughts_children','Ihre Gedanken zu Kindern?','profile','placeholder'),
('german','profile.how_close_family','Wie familiennah?','profile','placeholder'),
('german','profile.how_feel_loved','Wie fühlen Sie sich geliebt?','profile','placeholder'),
('german','profile.how_communicate','Wie kommunizieren Sie?','profile','placeholder'),
('german','profile.describe_perfect_date','Beschreiben Sie Ihr perfektes Date...','profile','placeholder'),
('german','profile.how_often','Wie oft?','profile','placeholder'),
('german','profile.diet_type','Ernährungstyp?','profile','placeholder'),
('german','profile.do_you_smoke','Rauchen Sie?','profile','placeholder'),
('german','profile.do_you_drink','Trinken Sie?','profile','placeholder'),
('german','profile.night_owl_early_bird','Nachteule oder Frühaufsteher?','profile','placeholder'),
('german','profile.do_you_have_pets','Haben Sie Haustiere?','profile','placeholder'),
('german','profile.quote_placeholder','Ein Zitat, das Sie inspiriert...','profile','placeholder'),
('german','profile.dream_vacation_placeholder','Wohin würden Sie gerne reisen?','profile','placeholder'),
('german','profile.about','Über','profile','title'),
('german','profile.tell_about_yourself','Erzählen Sie uns von sich... Was macht Sie einzigartig?','profile','placeholder'),
('german','profile.generate_ai_bio','KI-Bio generieren','profile','button'),
('german','profile.tell_others','Erzählen Sie anderen von sich...','profile','empty'),
('german','profile.add_your_bio','Bio hinzufügen','profile','button'),
('german','groups.group_members','Gruppenmitglieder','groups','title'),
('german','groups.view_manage_members','Gruppenmitglieder anzeigen und verwalten','groups','description'),
('german','groups.search_members','Mitglieder suchen...','groups','placeholder'),
('german','groups.no_members_found','Keine Mitglieder gefunden','groups','empty'),
('german','groups.no_members_yet','Noch keine Mitglieder','groups','empty'),
('german','groups.joined','Beigetreten','groups','label'),
('german','admin.loading_users','Benutzer werden geladen...','admin','loading'),
('german','admin.search_users','Benutzer suchen...','admin','placeholder'),
('german','admin.no_users_found','Keine Benutzer gefunden','admin','empty'),
('german','admin.joined','Beigetreten','admin','label'),
('german','admin.moderate','Moderieren','admin','button'),
('german','wizard.lets_talk_favorites','Lass uns über Favoriten reden!','wizard','title'),
('german','wizard.share_what_you_love','Teile was du am meisten liebst','wizard','subtitle'),
('german','wizard.what_love_read','Was liest du gerne?','wizard','placeholder'),
('german','wizard.what_genres_enjoy','Welche Genres magst du?','wizard','placeholder'),
('german','wizard.what_music_listen','Welche Musik hörst du?','wizard','placeholder'),
('german','wizard.what_cuisines_love','Welche Küchen liebst du?','wizard','placeholder'),
('german','wizard.what_games_enjoy','Welche Spiele magst du?','wizard','placeholder'),
('german','wizard.what_podcasts_listen','Welche Podcasts hörst du?','wizard','placeholder'),

-- Kurdish Sorani
('kurdish_sorani','profile.select_education','خوێندن هەڵبژێرە','profile','placeholder'),
('kurdish_sorani','profile.select_balance','هاوسەنگی هەڵبژێرە','profile','placeholder'),
('kurdish_sorani','profile.your_job_title','ناونیشانی کارەکەت','profile','placeholder'),
('kurdish_sorani','profile.where_you_work','لەکوێ کار دەکەیت','profile','placeholder'),
('kurdish_sorani','profile.describe_career_goals','ئامانجەکانی کارت باس بکە','profile','placeholder'),
('kurdish_sorani','profile.how_approach_work','چۆن بەکار دەچیت؟','profile','placeholder'),
('kurdish_sorani','profile.select_religion','ئاین هەڵبژێرە','profile','placeholder'),
('kurdish_sorani','profile.select_political_views','بۆچوونی سیاسی هەڵبژێرە','profile','placeholder'),
('kurdish_sorani','profile.select_zodiac','بورج هەڵبژێرە','profile','placeholder'),
('kurdish_sorani','profile.select_type','جۆر هەڵبژێرە','profile','placeholder'),
('kurdish_sorani','profile.looking_for','بەدوای چیدا دەگەڕێیت؟','profile','placeholder'),
('kurdish_sorani','profile.thoughts_children','بیرت لەسەر منداڵ؟','profile','placeholder'),
('kurdish_sorani','profile.how_close_family','چەند نزیکی خێزانیت؟','profile','placeholder'),
('kurdish_sorani','profile.how_feel_loved','چۆن هەست بە خۆشەویستی دەکەیت؟','profile','placeholder'),
('kurdish_sorani','profile.how_communicate','چۆن پەیوەندی دەکەیت؟','profile','placeholder'),
('kurdish_sorani','profile.describe_perfect_date','میعادی تەواوەکەت باس بکە...','profile','placeholder'),
('kurdish_sorani','profile.how_often','چەند جار؟','profile','placeholder'),
('kurdish_sorani','profile.diet_type','جۆری خواردن؟','profile','placeholder'),
('kurdish_sorani','profile.do_you_smoke','جگەرە دەکێشیت؟','profile','placeholder'),
('kurdish_sorani','profile.do_you_drink','خواردنەوە دەخۆیتەوە؟','profile','placeholder'),
('kurdish_sorani','profile.night_owl_early_bird','شەوپەرست یان بەیانیخوش؟','profile','placeholder'),
('kurdish_sorani','profile.do_you_have_pets','ئاژەڵی ماڵیت هەیە؟','profile','placeholder'),
('kurdish_sorani','profile.quote_placeholder','وتەیەک کە هاندەرت بێت...','profile','placeholder'),
('kurdish_sorani','profile.dream_vacation_placeholder','حەزت بەکوێ بگەشتیت؟','profile','placeholder'),
('kurdish_sorani','profile.about','دەربارە','profile','title'),
('kurdish_sorani','profile.tell_about_yourself','دەربارەی خۆت پێمان بڵێ... چیت تایبەت دەکات؟','profile','placeholder'),
('kurdish_sorani','profile.generate_ai_bio','دروستکردنی بایۆی AI','profile','button'),
('kurdish_sorani','profile.tell_others','بە کەسانی تر دەربارەی خۆت بڵێ...','profile','empty'),
('kurdish_sorani','profile.add_your_bio','بایۆکەت زیاد بکە','profile','button'),
('kurdish_sorani','groups.group_members','ئەندامانی گروپ','groups','title'),
('kurdish_sorani','groups.view_manage_members','بینین و بەڕێوەبردنی ئەندامان','groups','description'),
('kurdish_sorani','groups.search_members','گەڕان بۆ ئەندامان...','groups','placeholder'),
('kurdish_sorani','groups.no_members_found','هیچ ئەندامێک نەدۆزرایەوە','groups','empty'),
('kurdish_sorani','groups.no_members_yet','هێشتا ئەندام نییە','groups','empty'),
('kurdish_sorani','groups.joined','بەشداری کرد','groups','label'),
('kurdish_sorani','admin.loading_users','بارکردنی بەکارهێنەران...','admin','loading'),
('kurdish_sorani','admin.search_users','گەڕان بۆ بەکارهێنەران...','admin','placeholder'),
('kurdish_sorani','admin.no_users_found','هیچ بەکارهێنەرێک نەدۆزرایەوە','admin','empty'),
('kurdish_sorani','admin.joined','بەشداری کرد','admin','label'),
('kurdish_sorani','admin.moderate','چاودێری','admin','button'),
('kurdish_sorani','wizard.lets_talk_favorites','با لەسەر دڵخوازەکان بدوێین!','wizard','title'),
('kurdish_sorani','wizard.share_what_you_love','بەشداری ئەوەی کە زۆر حەزت لێیە بکە','wizard','subtitle'),
('kurdish_sorani','wizard.what_love_read','حەزت بە خوێندنەوەی چی هەیە؟','wizard','placeholder'),
('kurdish_sorani','wizard.what_genres_enjoy','حەزت بە چ جۆرێکە؟','wizard','placeholder'),
('kurdish_sorani','wizard.what_music_listen','گوێت لە چ میوزیکێک دەگریت؟','wizard','placeholder'),
('kurdish_sorani','wizard.what_cuisines_love','حەزت بە چ خواردنێکە؟','wizard','placeholder'),
('kurdish_sorani','wizard.what_games_enjoy','حەزت بە چ یارییەکە؟','wizard','placeholder'),
('kurdish_sorani','wizard.what_podcasts_listen','گوێت لە چ پۆدکاستێک دەگریت؟','wizard','placeholder'),

-- Kurdish Kurmanji
('kurdish_kurmanji','profile.select_education','Xwendinê hilbijêre','profile','placeholder'),
('kurdish_kurmanji','profile.select_balance','Hevsengiyê hilbijêre','profile','placeholder'),
('kurdish_kurmanji','profile.your_job_title','Navê karê te','profile','placeholder'),
('kurdish_kurmanji','profile.where_you_work','Li ku derê dixebitî','profile','placeholder'),
('kurdish_kurmanji','profile.describe_career_goals','Armancên kariyera xwe binivîse','profile','placeholder'),
('kurdish_kurmanji','profile.how_approach_work','Tu çawa bi karê xwe re dijî?','profile','placeholder'),
('kurdish_kurmanji','profile.select_religion','Olê hilbijêre','profile','placeholder'),
('kurdish_kurmanji','profile.select_political_views','Nêrînên siyasî hilbijêre','profile','placeholder'),
('kurdish_kurmanji','profile.select_zodiac','Burcê hilbijêre','profile','placeholder'),
('kurdish_kurmanji','profile.select_type','Cûreyê hilbijêre','profile','placeholder'),
('kurdish_kurmanji','profile.looking_for','Tu li çi digêrî?','profile','placeholder'),
('kurdish_kurmanji','profile.thoughts_children','Ramanên te li ser zarokan?','profile','placeholder'),
('kurdish_kurmanji','profile.how_close_family','Çiqas nêzî malbatê?','profile','placeholder'),
('kurdish_kurmanji','profile.how_feel_loved','Tu çawa hest bi evînê dikî?','profile','placeholder'),
('kurdish_kurmanji','profile.how_communicate','Tu çawa pêwendiyê datînî?','profile','placeholder'),
('kurdish_kurmanji','profile.describe_perfect_date','Hevdîtina xweya kamil binivîse...','profile','placeholder'),
('kurdish_kurmanji','profile.how_often','Çend caran?','profile','placeholder'),
('kurdish_kurmanji','profile.diet_type','Cûreya xwarinê?','profile','placeholder'),
('kurdish_kurmanji','profile.do_you_smoke','Tu cixarê dikişînî?','profile','placeholder'),
('kurdish_kurmanji','profile.do_you_drink','Tu vexwarinê vedixwî?','profile','placeholder'),
('kurdish_kurmanji','profile.night_owl_early_bird','Şevperist an sibehxoş?','profile','placeholder'),
('kurdish_kurmanji','profile.do_you_have_pets','Heywanên te hene?','profile','placeholder'),
('kurdish_kurmanji','profile.quote_placeholder','Gotinek ku te îlham dide...','profile','placeholder'),
('kurdish_kurmanji','profile.dream_vacation_placeholder','Tu dixwazî biçî ku derê?','profile','placeholder'),
('kurdish_kurmanji','profile.about','Derbarê','profile','title'),
('kurdish_kurmanji','profile.tell_about_yourself','Derbarê xwe de ji me re bêje... Çi te yekta dike?','profile','placeholder'),
('kurdish_kurmanji','profile.generate_ai_bio','Biyoya AI çêke','profile','button'),
('kurdish_kurmanji','profile.tell_others','Ji kesên din re derbarê xwe de bêje...','profile','empty'),
('kurdish_kurmanji','profile.add_your_bio','Biyoya xwe zêde bike','profile','button'),
('kurdish_kurmanji','groups.group_members','Endamên komê','groups','title'),
('kurdish_kurmanji','groups.view_manage_members','Endaman bibîne û birêve bibe','groups','description'),
('kurdish_kurmanji','groups.search_members','Li endaman bigere...','groups','placeholder'),
('kurdish_kurmanji','groups.no_members_found','Ti endam nehate dîtin','groups','empty'),
('kurdish_kurmanji','groups.no_members_yet','Hê jî endam tune','groups','empty'),
('kurdish_kurmanji','groups.joined','Beşdar bû','groups','label'),
('kurdish_kurmanji','admin.loading_users','Bikarhêner tên barkirin...','admin','loading'),
('kurdish_kurmanji','admin.search_users','Li bikarhêneran bigere...','admin','placeholder'),
('kurdish_kurmanji','admin.no_users_found','Ti bikarhêner nehate dîtin','admin','empty'),
('kurdish_kurmanji','admin.joined','Beşdar bû','admin','label'),
('kurdish_kurmanji','admin.moderate','Moderasyonê bike','admin','button'),
('kurdish_kurmanji','wizard.lets_talk_favorites','Ka em li ser bijareyan biaxivin!','wizard','title'),
('kurdish_kurmanji','wizard.share_what_you_love','Tiştên ku herî zêde jê hez dikî parve bike','wizard','subtitle'),
('kurdish_kurmanji','wizard.what_love_read','Tu ji xwendinê çi hez dikî?','wizard','placeholder'),
('kurdish_kurmanji','wizard.what_genres_enjoy','Tu ji kîjan cûreyan hez dikî?','wizard','placeholder'),
('kurdish_kurmanji','wizard.what_music_listen','Tu guhdariya kîjan muzîkê dikî?','wizard','placeholder'),
('kurdish_kurmanji','wizard.what_cuisines_love','Tu ji kîjan xwarinan hez dikî?','wizard','placeholder'),
('kurdish_kurmanji','wizard.what_games_enjoy','Tu ji kîjan lîstikvanan hez dikî?','wizard','placeholder'),
('kurdish_kurmanji','wizard.what_podcasts_listen','Tu guhdariya kîjan podkastan dikî?','wizard','placeholder')
ON CONFLICT (language_code, translation_key) DO UPDATE SET translation_value = EXCLUDED.translation_value;
