
-- Batch 10: Remaining SuperAdmin pages i18n
-- SocialLoginPage, SettingsPage, LikesPage, GroupsManagementPage, RegistrationQuestionsPage,
-- DashboardNew, DashboardHeader, UserManagementTabs, UserJourneyTab, UserTableHeader,
-- EditorHeader, FooterEditor, AnalyticsTab, BulkActionsTab, ContentModerationTab, ExportTab

INSERT INTO public.app_translations (language_code, translation_key, translation_value, category, auto_translated, needs_review) VALUES
-- SocialLoginPage
('english','admin.social_login_management','Social Login Management','admin',false,false),
('english','admin.social_login_desc','Enable, disable, and configure OAuth providers for user authentication.','admin',false,false),
('english','admin.enabled','Enabled','admin',false,false),
('english','admin.disabled','Disabled','admin',false,false),
('english','admin.client_id','Client ID','admin',false,false),
('english','admin.client_secret','Client Secret','admin',false,false),
('english','admin.save_credentials','Save Credentials','admin',false,false),
('english','admin.leave_blank_secret','Leave blank to keep existing secret.','admin',false,false),
('english','admin.error_loading_providers','Error loading providers','admin',false,false),
('english','admin.no_providers_found','No Providers Found','admin',false,false),
('english','admin.no_providers_desc','There are no social login providers configured in your Supabase project.','admin',false,false),
-- SettingsPage
('english','admin.system_settings','System Settings','admin',false,false),
('english','admin.reset_to_defaults','Reset to Defaults','admin',false,false),
('english','admin.reset_settings','Reset Settings','admin',false,false),
('english','admin.reset_settings_desc','This will reset all settings to their default values. This action cannot be undone.','admin',false,false),
('english','admin.cancel','Cancel','admin',false,false),
('english','admin.resetting','Resetting...','admin',false,false),
('english','admin.reset_all_settings','Reset All Settings','admin',false,false),
('english','admin.saving','Saving...','admin',false,false),
('english','admin.save_settings','Save Settings','admin',false,false),
('english','admin.general','General','admin',false,false),
('english','admin.email','Email','admin',false,false),
('english','admin.security','Security','admin',false,false),
('english','admin.api','API','admin',false,false),
('english','admin.system_status','System Status','admin',false,false),
('english','admin.system_status_desc','Control the overall behavior of the application','admin',false,false),
('english','admin.maintenance_mode','Maintenance Mode','admin',false,false),
('english','admin.maintenance_mode_desc','When enabled, only admins can access the site','admin',false,false),
('english','admin.user_registration','User Registration','admin',false,false),
('english','admin.allow_registration','Allow new users to register','admin',false,false),
('english','admin.photo_uploads','Photo Uploads','admin',false,false),
('english','admin.allow_photo_uploads','Allow users to upload new photos','admin',false,false),
('english','admin.messaging_system','Messaging System','admin',false,false),
('english','admin.enable_messaging','Enable messaging between users','admin',false,false),
('english','admin.app_configuration','App Configuration','admin',false,false),
('english','admin.app_config_desc','Basic application settings','admin',false,false),
('english','admin.application_name','Application Name','admin',false,false),
('english','admin.support_email','Support Email','admin',false,false),
('english','admin.date_format','Date Format','admin',false,false),
('english','admin.default_timezone','Default Timezone','admin',false,false),
('english','admin.email_configuration','Email Configuration','admin',false,false),
('english','admin.email_config_desc','Configure your email server settings','admin',false,false),
('english','admin.smtp_host','SMTP Host','admin',false,false),
('english','admin.smtp_port','SMTP Port','admin',false,false),
('english','admin.smtp_username','SMTP Username','admin',false,false),
('english','admin.smtp_password','SMTP Password','admin',false,false),
('english','admin.from_email','From Email Address','admin',false,false),
('english','admin.use_ssl_tls','Use SSL/TLS Encryption','admin',false,false),
('english','admin.test_email_config','Test Email Configuration','admin',false,false),
('english','admin.notification_preferences','Notification Preferences','admin',false,false),
('english','admin.notification_pref_desc','Configure what system notifications to send','admin',false,false),
('english','admin.daily_digest','Daily Digest','admin',false,false),
('english','admin.daily_digest_desc','Send daily summary of site activity','admin',false,false),
('english','admin.new_user_notifications','New User Notifications','admin',false,false),
('english','admin.new_user_notif_desc','Receive notifications for new registrations','admin',false,false),
('english','admin.report_alerts','Report Alerts','admin',false,false),
('english','admin.report_alerts_desc','Get notified when content is reported','admin',false,false),
('english','admin.security_controls','Security Controls','admin',false,false),
('english','admin.security_controls_desc','Configure security settings for the application','admin',false,false),
('english','admin.two_factor_auth','Two-Factor Authentication','admin',false,false),
('english','admin.two_factor_desc','Require 2FA for admin accounts','admin',false,false),
('english','admin.ip_restriction','IP Restriction','admin',false,false),
('english','admin.ip_restriction_desc','Limit admin access to specific IP addresses','admin',false,false),
('english','admin.password_expiry','Password Expiry (days)','admin',false,false),
('english','admin.session_timeout','Session Timeout (minutes)','admin',false,false),
('english','admin.account_security','Account Security','admin',false,false),
('english','admin.account_security_desc','Additional security settings for user accounts','admin',false,false),
('english','admin.min_password_length','Minimum Password Length','admin',false,false),
('english','admin.min_password_desc','Require at least this many characters','admin',false,false),
('english','admin.failed_login_attempts','Failed Login Attempts','admin',false,false),
('english','admin.failed_login_desc','Number of attempts before account lockout','admin',false,false),
('english','admin.account_lockout','Account Lockout Duration','admin',false,false),
('english','admin.account_lockout_desc','Time before allowing login attempts again','admin',false,false),
('english','admin.enforce_complexity','Enforce Password Complexity','admin',false,false),
('english','admin.api_configuration','API Configuration','admin',false,false),
('english','admin.api_config_desc','Manage API access and settings','admin',false,false),
('english','admin.rate_limiting','Rate Limiting','admin',false,false),
('english','admin.rate_limiting_desc','Limit number of API requests per minute','admin',false,false),
('english','admin.requests_per_minute','Requests Per Minute','admin',false,false),
-- LikesPage
('english','admin.likes_management','Likes Management','admin',false,false),
('english','admin.likes_desc','View and manage all user likes ({{count}} total)','admin',false,false),
('english','admin.all_likes','All Likes','admin',false,false),
('english','admin.search_by_user','Search by user name...','admin',false,false),
('english','admin.loading_likes','Loading likes...','admin',false,false),
('english','admin.no_likes_found','No likes found','admin',false,false),
('english','admin.liker','Liker','admin',false,false),
('english','admin.liked','Liked','admin',false,false),
('english','admin.unknown','Unknown','admin',false,false),
-- GroupsManagementPage
('english','admin.groups_management','Groups Management','admin',false,false),
('english','admin.groups_desc','Manage all groups, members, and posts','admin',false,false),
('english','admin.all_groups','All Groups','admin',false,false),
('english','admin.search_groups','Search groups...','admin',false,false),
('english','admin.loading_groups','Loading groups...','admin',false,false),
('english','admin.no_groups_found','No groups found','admin',false,false),
('english','admin.all_group_members','All Group Members','admin',false,false),
('english','admin.search_members','Search members...','admin',false,false),
('english','admin.loading_members','Loading members...','admin',false,false),
('english','admin.no_members_found','No members found','admin',false,false),
('english','admin.members','members','admin',false,false),
('english','admin.posts','posts','admin',false,false),
('english','admin.creator','Creator','admin',false,false),
-- RegistrationQuestionsPage
('english','admin.registration_questions','Registration Questions','admin',false,false),
('english','admin.reg_questions_desc','Manage the questions users are asked during the registration process','admin',false,false),
('english','admin.export','Export','admin',false,false),
('english','admin.add_question','Add Question','admin',false,false),
-- DashboardNew
('english','admin.dashboard','Dashboard','admin',false,false),
('english','admin.dashboard_welcome','Welcome back! Here''s what''s happening with your app today.','admin',false,false),
('english','admin.online_users','Online Users','admin',false,false),
('english','admin.active_users','Active Users','admin',false,false),
('english','admin.inactive_users','Inactive Users','admin',false,false),
('english','admin.blocked_users','Blocked Users','admin',false,false),
('english','admin.earning_overview','Earning Overview','admin',false,false),
('english','admin.last_12_months','last 12 months','admin',false,false),
('english','admin.registrations_chart','Last 12 Month Registrations','admin',false,false),
('english','admin.male','Male','admin',false,false),
('english','admin.female','Female','admin',false,false),
('english','admin.other','Other','admin',false,false),
-- DashboardHeader
('english','admin.last_24_hours','Last 24 hours','admin',false,false),
('english','admin.last_7_days','Last 7 days','admin',false,false),
('english','admin.last_30_days','Last 30 days','admin',false,false),
('english','admin.last_year','Last year','admin',false,false),
('english','admin.refreshing','Refreshing...','admin',false,false),
('english','admin.refresh','Refresh','admin',false,false),
-- UserManagementTabs
('english','admin.advanced_user_management','Advanced User Management','admin',false,false),
('english','admin.advanced_user_desc','Comprehensive user profile management and analytics','admin',false,false),
('english','admin.user_profiles','User Profiles','admin',false,false),
('english','admin.analytics','Analytics','admin',false,false),
('english','admin.bulk','Bulk','admin',false,false),
('english','admin.actions','Actions','admin',false,false),
('english','admin.moderation','Moderation','admin',false,false),
('english','admin.journey','Journey','admin',false,false),
-- UserJourneyTab
('english','admin.conversion_rate','Conversion Rate','admin',false,false),
('english','admin.avg_journey_time','Avg. Journey Time','admin',false,false),
('english','admin.drop_off_point','Drop-off Point','admin',false,false),
('english','admin.user_journey_funnel','User Journey Funnel','admin',false,false),
('english','admin.users_count','{{count}} users ({{pct}}%)','admin',false,false),
-- UserTableHeader
('english','admin.id','ID','admin',false,false),
('english','admin.name','Name','admin',false,false),
('english','admin.role','Role','admin',false,false),
('english','admin.status','Status','admin',false,false),
('english','admin.location','Location','admin',false,false),
('english','admin.join_date','Join Date','admin',false,false),
-- EditorHeader
('english','admin.landing_page_editor','Landing Page Editor','admin',false,false),
('english','admin.landing_page_editor_desc','Edit the content displayed on the public landing page','admin',false,false),
('english','admin.save_changes','Save Changes','admin',false,false),
-- FooterEditor
('english','admin.footer_content','Footer Content','admin',false,false),
('english','admin.footer_content_desc','Edit the content displayed in the website footer','admin',false,false),
('english','admin.copyright_text','Copyright Text','admin',false,false),
-- AnalyticsTab
('english','admin.avg_registration_time','Avg. Registration Time','admin',false,false),
('english','admin.completion_rate','Completion Rate','admin',false,false),
('english','admin.drop_off_rate','Drop-off Rate','admin',false,false),
('english','admin.daily_signups','Daily Signups','admin',false,false),
('english','admin.reg_step_completion','Registration Step Completion','admin',false,false),
('english','admin.user_status_distribution','User Status Distribution','admin',false,false),
('english','admin.profile_section_completion','Profile Section Completion Rates','admin',false,false),
-- BulkActionsTab
('english','admin.bulk_actions','Bulk Actions','admin',false,false),
('english','admin.select_action','Select Action','admin',false,false),
('english','admin.choose_bulk_action','Choose bulk action','admin',false,false),
('english','admin.target_users','Target Users','admin',false,false),
('english','admin.select_user_group','Select user group','admin',false,false),
('english','admin.all_users','All Users','admin',false,false),
('english','admin.pending_verification','Pending Verification','admin',false,false),
('english','admin.premium_users','Premium Users','admin',false,false),
('english','admin.free_users','Free Users','admin',false,false),
('english','admin.filters','Filters','admin',false,false),
('english','admin.filter_by_location','Filter by location','admin',false,false),
('english','admin.filter_by_join_date','Filter by join date','admin',false,false),
('english','admin.filter_by_activity','Filter by activity level','admin',false,false),
('english','admin.execute_bulk_action','Execute Bulk Action','admin',false,false),
('english','admin.quick_actions','Quick Actions','admin',false,false),
('english','admin.execute','Execute','admin',false,false),
('english','admin.field_specific_tools','Field-Specific Tools','admin',false,false),
('english','admin.location_verification','Location Verification','admin',false,false),
('english','admin.verify_locations_desc','Verify and standardize user locations','admin',false,false),
('english','admin.verify_locations','Verify Locations','admin',false,false),
('english','admin.photo_moderation','Photo Moderation','admin',false,false),
('english','admin.review_photos_desc','Review and approve pending photos','admin',false,false),
('english','admin.review_photos','Review Photos','admin',false,false),
('english','admin.content_check','Content Check','admin',false,false),
('english','admin.scan_content_desc','Scan profiles for inappropriate content','admin',false,false),
('english','admin.scan_content','Scan Content','admin',false,false),
-- ContentModerationTab
('english','admin.pending_review','Pending Review','admin',false,false),
('english','admin.flagged_content','Flagged Content','admin',false,false),
('english','admin.high_risk','High Risk','admin',false,false),
('english','admin.auto_approved','Auto-Approved','admin',false,false),
('english','admin.moderation_queue','Moderation Queue','admin',false,false),
('english','admin.review','Review','admin',false,false),
('english','admin.reject','Reject','admin',false,false),
('english','admin.approve','Approve','admin',false,false),
-- ExportTab
('english','admin.export_configuration','Export Configuration','admin',false,false),
('english','admin.export_format','Export Format','admin',false,false),
('english','admin.user_filter','User Filter','admin',false,false),
('english','admin.active_users_only','Active Users Only','admin',false,false),
('english','admin.verified_users_only','Verified Users Only','admin',false,false),
('english','admin.premium_users_only','Premium Users Only','admin',false,false),
('english','admin.recently_joined','Recently Joined','admin',false,false),
('english','admin.export_options','Export Options','admin',false,false),
('english','admin.anonymize_data','Anonymize personal data','admin',false,false),
('english','admin.compress_export','Compress export file','admin',false,false),
('english','admin.email_export_link','Email export link','admin',false,false),
('english','admin.quick_exports','Quick Exports','admin',false,false),
('english','admin.user_list_basic','User List (Basic Info)','admin',false,false),
('english','admin.full_user_database','Full User Database','admin',false,false),
('english','admin.analytics_report','Analytics Report','admin',false,false),
('english','admin.registration_statistics','Registration Statistics','admin',false,false),
('english','admin.select_fields_export','Select Fields to Export','admin',false,false),
('english','admin.fields_selected','{{count}} fields selected','admin',false,false),
('english','admin.clear_all','Clear All','admin',false,false),
('english','admin.export_selected_fields','Export Selected Fields','admin',false,false),

-- Norwegian translations
('norwegian','admin.social_login_management','Administrasjon av sosial pålogging','admin',true,true),
('norwegian','admin.social_login_desc','Aktiver, deaktiver og konfigurer OAuth-leverandører for brukerautentisering.','admin',true,true),
('norwegian','admin.enabled','Aktivert','admin',true,true),
('norwegian','admin.disabled','Deaktivert','admin',true,true),
('norwegian','admin.client_id','Klient-ID','admin',true,true),
('norwegian','admin.client_secret','Klienthemmelighet','admin',true,true),
('norwegian','admin.save_credentials','Lagre legitimasjon','admin',true,true),
('norwegian','admin.leave_blank_secret','La stå tom for å beholde eksisterende hemmelighet.','admin',true,true),
('norwegian','admin.error_loading_providers','Feil ved lasting av leverandører','admin',true,true),
('norwegian','admin.no_providers_found','Ingen leverandører funnet','admin',true,true),
('norwegian','admin.no_providers_desc','Det er ingen sosiale påloggingsleverandører konfigurert i Supabase-prosjektet ditt.','admin',true,true),
('norwegian','admin.system_settings','Systeminnstillinger','admin',true,true),
('norwegian','admin.reset_to_defaults','Tilbakestill til standard','admin',true,true),
('norwegian','admin.reset_settings','Tilbakestill innstillinger','admin',true,true),
('norwegian','admin.reset_settings_desc','Dette vil tilbakestille alle innstillinger til standardverdier. Denne handlingen kan ikke angres.','admin',true,true),
('norwegian','admin.cancel','Avbryt','admin',true,true),
('norwegian','admin.resetting','Tilbakestiller...','admin',true,true),
('norwegian','admin.reset_all_settings','Tilbakestill alle innstillinger','admin',true,true),
('norwegian','admin.saving','Lagrer...','admin',true,true),
('norwegian','admin.save_settings','Lagre innstillinger','admin',true,true),
('norwegian','admin.general','Generelt','admin',true,true),
('norwegian','admin.email','E-post','admin',true,true),
('norwegian','admin.security','Sikkerhet','admin',true,true),
('norwegian','admin.api','API','admin',true,true),
('norwegian','admin.system_status','Systemstatus','admin',true,true),
('norwegian','admin.system_status_desc','Kontroller den generelle oppførselen til applikasjonen','admin',true,true),
('norwegian','admin.maintenance_mode','Vedlikeholdsmodus','admin',true,true),
('norwegian','admin.maintenance_mode_desc','Når aktivert, kan bare administratorer få tilgang til nettstedet','admin',true,true),
('norwegian','admin.user_registration','Brukerregistrering','admin',true,true),
('norwegian','admin.allow_registration','Tillat nye brukere å registrere seg','admin',true,true),
('norwegian','admin.photo_uploads','Bildeopplastinger','admin',true,true),
('norwegian','admin.allow_photo_uploads','Tillat brukere å laste opp nye bilder','admin',true,true),
('norwegian','admin.messaging_system','Meldingssystem','admin',true,true),
('norwegian','admin.enable_messaging','Aktiver meldinger mellom brukere','admin',true,true),
('norwegian','admin.app_configuration','Appkonfigurasjon','admin',true,true),
('norwegian','admin.app_config_desc','Grunnleggende applikasjonsinnstillinger','admin',true,true),
('norwegian','admin.application_name','Applikasjonsnavn','admin',true,true),
('norwegian','admin.support_email','Support-e-post','admin',true,true),
('norwegian','admin.date_format','Datoformat','admin',true,true),
('norwegian','admin.default_timezone','Standard tidssone','admin',true,true),
('norwegian','admin.email_configuration','E-postkonfigurasjon','admin',true,true),
('norwegian','admin.email_config_desc','Konfigurer e-postserverinnstillingene dine','admin',true,true),
('norwegian','admin.smtp_host','SMTP-vert','admin',true,true),
('norwegian','admin.smtp_port','SMTP-port','admin',true,true),
('norwegian','admin.smtp_username','SMTP-brukernavn','admin',true,true),
('norwegian','admin.smtp_password','SMTP-passord','admin',true,true),
('norwegian','admin.from_email','Fra e-postadresse','admin',true,true),
('norwegian','admin.use_ssl_tls','Bruk SSL/TLS-kryptering','admin',true,true),
('norwegian','admin.test_email_config','Test e-postkonfigurasjon','admin',true,true),
('norwegian','admin.notification_preferences','Varslingsinnstillinger','admin',true,true),
('norwegian','admin.notification_pref_desc','Konfigurer hvilke systemvarsler som skal sendes','admin',true,true),
('norwegian','admin.daily_digest','Daglig sammendrag','admin',true,true),
('norwegian','admin.daily_digest_desc','Send daglig sammendrag av nettstedets aktivitet','admin',true,true),
('norwegian','admin.new_user_notifications','Varsler om nye brukere','admin',true,true),
('norwegian','admin.new_user_notif_desc','Motta varsler for nye registreringer','admin',true,true),
('norwegian','admin.report_alerts','Rapportvarsler','admin',true,true),
('norwegian','admin.report_alerts_desc','Bli varslet når innhold rapporteres','admin',true,true),
('norwegian','admin.security_controls','Sikkerhetskontroller','admin',true,true),
('norwegian','admin.security_controls_desc','Konfigurer sikkerhetsinnstillinger for applikasjonen','admin',true,true),
('norwegian','admin.two_factor_auth','Tofaktorautentisering','admin',true,true),
('norwegian','admin.two_factor_desc','Krev 2FA for administratorkontoer','admin',true,true),
('norwegian','admin.ip_restriction','IP-begrensning','admin',true,true),
('norwegian','admin.ip_restriction_desc','Begrens administratortilgang til bestemte IP-adresser','admin',true,true),
('norwegian','admin.password_expiry','Passordutløp (dager)','admin',true,true),
('norwegian','admin.session_timeout','Sesjonsutløp (minutter)','admin',true,true),
('norwegian','admin.account_security','Kontosikkerhet','admin',true,true),
('norwegian','admin.account_security_desc','Ytterligere sikkerhetsinnstillinger for brukerkontoer','admin',true,true),
('norwegian','admin.min_password_length','Minimum passordlengde','admin',true,true),
('norwegian','admin.min_password_desc','Krev minst så mange tegn','admin',true,true),
('norwegian','admin.failed_login_attempts','Mislykkede påloggingsforsøk','admin',true,true),
('norwegian','admin.failed_login_desc','Antall forsøk før kontolåsing','admin',true,true),
('norwegian','admin.account_lockout','Varighet av kontolåsing','admin',true,true),
('norwegian','admin.account_lockout_desc','Tid før påloggingsforsøk tillates igjen','admin',true,true),
('norwegian','admin.enforce_complexity','Krev passordkompleksitet','admin',true,true),
('norwegian','admin.api_configuration','API-konfigurasjon','admin',true,true),
('norwegian','admin.api_config_desc','Administrer API-tilgang og innstillinger','admin',true,true),
('norwegian','admin.rate_limiting','Hastighetsbegrensning','admin',true,true),
('norwegian','admin.rate_limiting_desc','Begrens antall API-forespørsler per minutt','admin',true,true),
('norwegian','admin.requests_per_minute','Forespørsler per minutt','admin',true,true),
('norwegian','admin.likes_management','Likesadministrasjon','admin',true,true),
('norwegian','admin.likes_desc','Vis og administrer alle brukerlikes ({{count}} totalt)','admin',true,true),
('norwegian','admin.all_likes','Alle likes','admin',true,true),
('norwegian','admin.search_by_user','Søk etter brukernavn...','admin',true,true),
('norwegian','admin.loading_likes','Laster likes...','admin',true,true),
('norwegian','admin.no_likes_found','Ingen likes funnet','admin',true,true),
('norwegian','admin.liker','Liker','admin',true,true),
('norwegian','admin.liked','Likt','admin',true,true),
('norwegian','admin.unknown','Ukjent','admin',true,true),
('norwegian','admin.groups_management','Gruppeadministrasjon','admin',true,true),
('norwegian','admin.groups_desc','Administrer alle grupper, medlemmer og innlegg','admin',true,true),
('norwegian','admin.all_groups','Alle grupper','admin',true,true),
('norwegian','admin.search_groups','Søk i grupper...','admin',true,true),
('norwegian','admin.loading_groups','Laster grupper...','admin',true,true),
('norwegian','admin.no_groups_found','Ingen grupper funnet','admin',true,true),
('norwegian','admin.all_group_members','Alle gruppemedlemmer','admin',true,true),
('norwegian','admin.search_members','Søk etter medlemmer...','admin',true,true),
('norwegian','admin.loading_members','Laster medlemmer...','admin',true,true),
('norwegian','admin.no_members_found','Ingen medlemmer funnet','admin',true,true),
('norwegian','admin.members','medlemmer','admin',true,true),
('norwegian','admin.posts','innlegg','admin',true,true),
('norwegian','admin.creator','Opprettet av','admin',true,true),
('norwegian','admin.registration_questions','Registreringsspørsmål','admin',true,true),
('norwegian','admin.reg_questions_desc','Administrer spørsmålene som stilles under registreringsprosessen','admin',true,true),
('norwegian','admin.export','Eksporter','admin',true,true),
('norwegian','admin.add_question','Legg til spørsmål','admin',true,true),
('norwegian','admin.dashboard','Dashbord','admin',true,true),
('norwegian','admin.dashboard_welcome','Velkommen tilbake! Her er hva som skjer med appen din i dag.','admin',true,true),
('norwegian','admin.online_users','Brukere på nett','admin',true,true),
('norwegian','admin.active_users','Aktive brukere','admin',true,true),
('norwegian','admin.inactive_users','Inaktive brukere','admin',true,true),
('norwegian','admin.blocked_users','Blokkerte brukere','admin',true,true),
('norwegian','admin.earning_overview','Inntektsoversikt','admin',true,true),
('norwegian','admin.last_12_months','siste 12 måneder','admin',true,true),
('norwegian','admin.registrations_chart','Registreringer siste 12 måneder','admin',true,true),
('norwegian','admin.male','Mann','admin',true,true),
('norwegian','admin.female','Kvinne','admin',true,true),
('norwegian','admin.other','Annet','admin',true,true),
('norwegian','admin.last_24_hours','Siste 24 timer','admin',true,true),
('norwegian','admin.last_7_days','Siste 7 dager','admin',true,true),
('norwegian','admin.last_30_days','Siste 30 dager','admin',true,true),
('norwegian','admin.last_year','Siste år','admin',true,true),
('norwegian','admin.refreshing','Oppdaterer...','admin',true,true),
('norwegian','admin.refresh','Oppdater','admin',true,true),
('norwegian','admin.advanced_user_management','Avansert brukeradministrasjon','admin',true,true),
('norwegian','admin.advanced_user_desc','Omfattende administrasjon av brukerprofiler og analyse','admin',true,true),
('norwegian','admin.user_profiles','Brukerprofiler','admin',true,true),
('norwegian','admin.analytics','Analyse','admin',true,true),
('norwegian','admin.bulk','Masse','admin',true,true),
('norwegian','admin.actions','Handlinger','admin',true,true),
('norwegian','admin.moderation','Moderering','admin',true,true),
('norwegian','admin.journey','Reise','admin',true,true),
('norwegian','admin.conversion_rate','Konverteringsrate','admin',true,true),
('norwegian','admin.avg_journey_time','Gj.sn. reisetid','admin',true,true),
('norwegian','admin.drop_off_point','Frafallspunkt','admin',true,true),
('norwegian','admin.user_journey_funnel','Brukerreisetrakt','admin',true,true),
('norwegian','admin.users_count','{{count}} brukere ({{pct}}%)','admin',true,true),
('norwegian','admin.id','ID','admin',true,true),
('norwegian','admin.name','Navn','admin',true,true),
('norwegian','admin.role','Rolle','admin',true,true),
('norwegian','admin.status','Status','admin',true,true),
('norwegian','admin.location','Sted','admin',true,true),
('norwegian','admin.join_date','Registreringsdato','admin',true,true),
('norwegian','admin.landing_page_editor','Landingssideeditor','admin',true,true),
('norwegian','admin.landing_page_editor_desc','Rediger innholdet som vises på den offentlige landingssiden','admin',true,true),
('norwegian','admin.save_changes','Lagre endringer','admin',true,true),
('norwegian','admin.footer_content','Bunntekstinnhold','admin',true,true),
('norwegian','admin.footer_content_desc','Rediger innholdet som vises i bunnteksten','admin',true,true),
('norwegian','admin.copyright_text','Opphavsrettstekst','admin',true,true),
('norwegian','admin.avg_registration_time','Gj.sn. registreringstid','admin',true,true),
('norwegian','admin.completion_rate','Fullføringsrate','admin',true,true),
('norwegian','admin.drop_off_rate','Frafallsrate','admin',true,true),
('norwegian','admin.daily_signups','Daglige registreringer','admin',true,true),
('norwegian','admin.reg_step_completion','Fullføring av registreringstrinn','admin',true,true),
('norwegian','admin.user_status_distribution','Brukerstatusfordeling','admin',true,true),
('norwegian','admin.profile_section_completion','Fullføringsrater for profilseksjoner','admin',true,true),
('norwegian','admin.bulk_actions','Massehandlinger','admin',true,true),
('norwegian','admin.select_action','Velg handling','admin',true,true),
('norwegian','admin.choose_bulk_action','Velg massehandling','admin',true,true),
('norwegian','admin.target_users','Målbrukere','admin',true,true),
('norwegian','admin.select_user_group','Velg brukergruppe','admin',true,true),
('norwegian','admin.all_users','Alle brukere','admin',true,true),
('norwegian','admin.pending_verification','Venter på verifisering','admin',true,true),
('norwegian','admin.premium_users','Premiumbrukere','admin',true,true),
('norwegian','admin.free_users','Gratisbrukere','admin',true,true),
('norwegian','admin.filters','Filtre','admin',true,true),
('norwegian','admin.filter_by_location','Filtrer etter sted','admin',true,true),
('norwegian','admin.filter_by_join_date','Filtrer etter registreringsdato','admin',true,true),
('norwegian','admin.filter_by_activity','Filtrer etter aktivitetsnivå','admin',true,true),
('norwegian','admin.execute_bulk_action','Utfør massehandling','admin',true,true),
('norwegian','admin.quick_actions','Hurtighandlinger','admin',true,true),
('norwegian','admin.execute','Utfør','admin',true,true),
('norwegian','admin.field_specific_tools','Feltspesifikke verktøy','admin',true,true),
('norwegian','admin.location_verification','Stedsverifisering','admin',true,true),
('norwegian','admin.verify_locations_desc','Verifiser og standardiser brukersteder','admin',true,true),
('norwegian','admin.verify_locations','Verifiser steder','admin',true,true),
('norwegian','admin.photo_moderation','Bildemoderasjon','admin',true,true),
('norwegian','admin.review_photos_desc','Gjennomgå og godkjenn ventende bilder','admin',true,true),
('norwegian','admin.review_photos','Gjennomgå bilder','admin',true,true),
('norwegian','admin.content_check','Innholdssjekk','admin',true,true),
('norwegian','admin.scan_content_desc','Skann profiler for upassende innhold','admin',true,true),
('norwegian','admin.scan_content','Skann innhold','admin',true,true),
('norwegian','admin.pending_review','Venter på gjennomgang','admin',true,true),
('norwegian','admin.flagged_content','Flagget innhold','admin',true,true),
('norwegian','admin.high_risk','Høy risiko','admin',true,true),
('norwegian','admin.auto_approved','Automatisk godkjent','admin',true,true),
('norwegian','admin.moderation_queue','Modereringskø','admin',true,true),
('norwegian','admin.review','Gjennomgå','admin',true,true),
('norwegian','admin.reject','Avvis','admin',true,true),
('norwegian','admin.approve','Godkjenn','admin',true,true),
('norwegian','admin.export_configuration','Eksportkonfigurasjon','admin',true,true),
('norwegian','admin.export_format','Eksportformat','admin',true,true),
('norwegian','admin.user_filter','Brukerfilter','admin',true,true),
('norwegian','admin.active_users_only','Kun aktive brukere','admin',true,true),
('norwegian','admin.verified_users_only','Kun verifiserte brukere','admin',true,true),
('norwegian','admin.premium_users_only','Kun premiumbrukere','admin',true,true),
('norwegian','admin.recently_joined','Nylig registrert','admin',true,true),
('norwegian','admin.export_options','Eksportalternativer','admin',true,true),
('norwegian','admin.anonymize_data','Anonymiser personlige data','admin',true,true),
('norwegian','admin.compress_export','Komprimer eksportfil','admin',true,true),
('norwegian','admin.email_export_link','Send eksportlenke på e-post','admin',true,true),
('norwegian','admin.quick_exports','Hurtigeksport','admin',true,true),
('norwegian','admin.user_list_basic','Brukerliste (grunnleggende info)','admin',true,true),
('norwegian','admin.full_user_database','Full brukerdatabase','admin',true,true),
('norwegian','admin.analytics_report','Analyserapport','admin',true,true),
('norwegian','admin.registration_statistics','Registreringsstatistikk','admin',true,true),
('norwegian','admin.select_fields_export','Velg felt å eksportere','admin',true,true),
('norwegian','admin.fields_selected','{{count}} felt valgt','admin',true,true),
('norwegian','admin.clear_all','Tøm alle','admin',true,true),
('norwegian','admin.export_selected_fields','Eksporter valgte felt','admin',true,true),

-- German translations
('german','admin.social_login_management','Social-Login-Verwaltung','admin',true,true),
('german','admin.social_login_desc','OAuth-Anbieter für die Benutzerauthentifizierung aktivieren, deaktivieren und konfigurieren.','admin',true,true),
('german','admin.enabled','Aktiviert','admin',true,true),
('german','admin.disabled','Deaktiviert','admin',true,true),
('german','admin.client_id','Client-ID','admin',true,true),
('german','admin.client_secret','Client-Geheimnis','admin',true,true),
('german','admin.save_credentials','Anmeldedaten speichern','admin',true,true),
('german','admin.leave_blank_secret','Leer lassen, um vorhandenes Geheimnis beizubehalten.','admin',true,true),
('german','admin.error_loading_providers','Fehler beim Laden der Anbieter','admin',true,true),
('german','admin.no_providers_found','Keine Anbieter gefunden','admin',true,true),
('german','admin.no_providers_desc','Es sind keine Social-Login-Anbieter in Ihrem Supabase-Projekt konfiguriert.','admin',true,true),
('german','admin.system_settings','Systemeinstellungen','admin',true,true),
('german','admin.reset_to_defaults','Auf Standard zurücksetzen','admin',true,true),
('german','admin.reset_settings','Einstellungen zurücksetzen','admin',true,true),
('german','admin.reset_settings_desc','Alle Einstellungen werden auf ihre Standardwerte zurückgesetzt. Diese Aktion kann nicht rückgängig gemacht werden.','admin',true,true),
('german','admin.cancel','Abbrechen','admin',true,true),
('german','admin.resetting','Wird zurückgesetzt...','admin',true,true),
('german','admin.reset_all_settings','Alle Einstellungen zurücksetzen','admin',true,true),
('german','admin.saving','Wird gespeichert...','admin',true,true),
('german','admin.save_settings','Einstellungen speichern','admin',true,true),
('german','admin.general','Allgemein','admin',true,true),
('german','admin.email','E-Mail','admin',true,true),
('german','admin.security','Sicherheit','admin',true,true),
('german','admin.api','API','admin',true,true),
('german','admin.system_status','Systemstatus','admin',true,true),
('german','admin.system_status_desc','Gesamtverhalten der Anwendung steuern','admin',true,true),
('german','admin.maintenance_mode','Wartungsmodus','admin',true,true),
('german','admin.maintenance_mode_desc','Wenn aktiviert, können nur Administratoren auf die Seite zugreifen','admin',true,true),
('german','admin.user_registration','Benutzerregistrierung','admin',true,true),
('german','admin.allow_registration','Neue Benutzer dürfen sich registrieren','admin',true,true),
('german','admin.photo_uploads','Foto-Uploads','admin',true,true),
('german','admin.allow_photo_uploads','Benutzern das Hochladen neuer Fotos erlauben','admin',true,true),
('german','admin.messaging_system','Nachrichtensystem','admin',true,true),
('german','admin.enable_messaging','Nachrichten zwischen Benutzern aktivieren','admin',true,true),
('german','admin.app_configuration','App-Konfiguration','admin',true,true),
('german','admin.app_config_desc','Grundlegende Anwendungseinstellungen','admin',true,true),
('german','admin.application_name','Anwendungsname','admin',true,true),
('german','admin.support_email','Support-E-Mail','admin',true,true),
('german','admin.date_format','Datumsformat','admin',true,true),
('german','admin.default_timezone','Standardzeitzone','admin',true,true),
('german','admin.email_configuration','E-Mail-Konfiguration','admin',true,true),
('german','admin.email_config_desc','E-Mail-Servereinstellungen konfigurieren','admin',true,true),
('german','admin.smtp_host','SMTP-Host','admin',true,true),
('german','admin.smtp_port','SMTP-Port','admin',true,true),
('german','admin.smtp_username','SMTP-Benutzername','admin',true,true),
('german','admin.smtp_password','SMTP-Passwort','admin',true,true),
('german','admin.from_email','Absender-E-Mail-Adresse','admin',true,true),
('german','admin.use_ssl_tls','SSL/TLS-Verschlüsselung verwenden','admin',true,true),
('german','admin.test_email_config','E-Mail-Konfiguration testen','admin',true,true),
('german','admin.notification_preferences','Benachrichtigungseinstellungen','admin',true,true),
('german','admin.notification_pref_desc','Systembenachrichtigungen konfigurieren','admin',true,true),
('german','admin.daily_digest','Tägliche Zusammenfassung','admin',true,true),
('german','admin.daily_digest_desc','Tägliche Zusammenfassung der Websiteaktivitäten senden','admin',true,true),
('german','admin.new_user_notifications','Neue Benutzerbenachrichtigungen','admin',true,true),
('german','admin.new_user_notif_desc','Benachrichtigungen für neue Registrierungen erhalten','admin',true,true),
('german','admin.report_alerts','Meldungsbenachrichtigungen','admin',true,true),
('german','admin.report_alerts_desc','Benachrichtigt werden, wenn Inhalte gemeldet werden','admin',true,true),
('german','admin.security_controls','Sicherheitskontrollen','admin',true,true),
('german','admin.security_controls_desc','Sicherheitseinstellungen für die Anwendung konfigurieren','admin',true,true),
('german','admin.two_factor_auth','Zwei-Faktor-Authentifizierung','admin',true,true),
('german','admin.two_factor_desc','2FA für Administratorkonten erfordern','admin',true,true),
('german','admin.ip_restriction','IP-Beschränkung','admin',true,true),
('german','admin.ip_restriction_desc','Administratorzugriff auf bestimmte IP-Adressen beschränken','admin',true,true),
('german','admin.password_expiry','Passwortablauf (Tage)','admin',true,true),
('german','admin.session_timeout','Sitzungstimeout (Minuten)','admin',true,true),
('german','admin.account_security','Kontosicherheit','admin',true,true),
('german','admin.account_security_desc','Zusätzliche Sicherheitseinstellungen für Benutzerkonten','admin',true,true),
('german','admin.min_password_length','Minimale Passwortlänge','admin',true,true),
('german','admin.min_password_desc','Mindestens so viele Zeichen erfordern','admin',true,true),
('german','admin.failed_login_attempts','Fehlgeschlagene Anmeldeversuche','admin',true,true),
('german','admin.failed_login_desc','Anzahl der Versuche vor Kontosperrung','admin',true,true),
('german','admin.account_lockout','Kontosperrdauer','admin',true,true),
('german','admin.account_lockout_desc','Zeit vor erneuten Anmeldeversuchen','admin',true,true),
('german','admin.enforce_complexity','Passwortkomplexität erzwingen','admin',true,true),
('german','admin.api_configuration','API-Konfiguration','admin',true,true),
('german','admin.api_config_desc','API-Zugang und Einstellungen verwalten','admin',true,true),
('german','admin.rate_limiting','Ratenbegrenzung','admin',true,true),
('german','admin.rate_limiting_desc','Anzahl der API-Anfragen pro Minute begrenzen','admin',true,true),
('german','admin.requests_per_minute','Anfragen pro Minute','admin',true,true),
('german','admin.likes_management','Likes-Verwaltung','admin',true,true),
('german','admin.likes_desc','Alle Benutzer-Likes anzeigen und verwalten ({{count}} gesamt)','admin',true,true),
('german','admin.all_likes','Alle Likes','admin',true,true),
('german','admin.search_by_user','Nach Benutzername suchen...','admin',true,true),
('german','admin.loading_likes','Likes werden geladen...','admin',true,true),
('german','admin.no_likes_found','Keine Likes gefunden','admin',true,true),
('german','admin.liker','Liker','admin',true,true),
('german','admin.liked','Geliked','admin',true,true),
('german','admin.unknown','Unbekannt','admin',true,true),
('german','admin.groups_management','Gruppenverwaltung','admin',true,true),
('german','admin.groups_desc','Alle Gruppen, Mitglieder und Beiträge verwalten','admin',true,true),
('german','admin.all_groups','Alle Gruppen','admin',true,true),
('german','admin.search_groups','Gruppen durchsuchen...','admin',true,true),
('german','admin.loading_groups','Gruppen werden geladen...','admin',true,true),
('german','admin.no_groups_found','Keine Gruppen gefunden','admin',true,true),
('german','admin.all_group_members','Alle Gruppenmitglieder','admin',true,true),
('german','admin.search_members','Mitglieder suchen...','admin',true,true),
('german','admin.loading_members','Mitglieder werden geladen...','admin',true,true),
('german','admin.no_members_found','Keine Mitglieder gefunden','admin',true,true),
('german','admin.members','Mitglieder','admin',true,true),
('german','admin.posts','Beiträge','admin',true,true),
('german','admin.creator','Ersteller','admin',true,true),
('german','admin.registration_questions','Registrierungsfragen','admin',true,true),
('german','admin.reg_questions_desc','Verwalten Sie die Fragen, die Benutzern während der Registrierung gestellt werden','admin',true,true),
('german','admin.export','Exportieren','admin',true,true),
('german','admin.add_question','Frage hinzufügen','admin',true,true),
('german','admin.dashboard','Dashboard','admin',true,true),
('german','admin.dashboard_welcome','Willkommen zurück! Hier ist, was heute in Ihrer App passiert.','admin',true,true),
('german','admin.online_users','Online-Benutzer','admin',true,true),
('german','admin.active_users','Aktive Benutzer','admin',true,true),
('german','admin.inactive_users','Inaktive Benutzer','admin',true,true),
('german','admin.blocked_users','Gesperrte Benutzer','admin',true,true),
('german','admin.earning_overview','Einnahmenübersicht','admin',true,true),
('german','admin.last_12_months','letzte 12 Monate','admin',true,true),
('german','admin.registrations_chart','Registrierungen der letzten 12 Monate','admin',true,true),
('german','admin.male','Männlich','admin',true,true),
('german','admin.female','Weiblich','admin',true,true),
('german','admin.other','Sonstiges','admin',true,true),
('german','admin.last_24_hours','Letzte 24 Stunden','admin',true,true),
('german','admin.last_7_days','Letzte 7 Tage','admin',true,true),
('german','admin.last_30_days','Letzte 30 Tage','admin',true,true),
('german','admin.last_year','Letztes Jahr','admin',true,true),
('german','admin.refreshing','Aktualisierung...','admin',true,true),
('german','admin.refresh','Aktualisieren','admin',true,true),
('german','admin.advanced_user_management','Erweiterte Benutzerverwaltung','admin',true,true),
('german','admin.advanced_user_desc','Umfassende Benutzerprofilverwaltung und Analyse','admin',true,true),
('german','admin.user_profiles','Benutzerprofile','admin',true,true),
('german','admin.analytics','Analyse','admin',true,true),
('german','admin.bulk','Massen','admin',true,true),
('german','admin.actions','Aktionen','admin',true,true),
('german','admin.moderation','Moderation','admin',true,true),
('german','admin.journey','Reise','admin',true,true),
('german','admin.conversion_rate','Konversionsrate','admin',true,true),
('german','admin.avg_journey_time','Durchschn. Reisezeit','admin',true,true),
('german','admin.drop_off_point','Abbruchpunkt','admin',true,true),
('german','admin.user_journey_funnel','Benutzer-Journey-Trichter','admin',true,true),
('german','admin.users_count','{{count}} Benutzer ({{pct}}%)','admin',true,true),
('german','admin.id','ID','admin',true,true),
('german','admin.name','Name','admin',true,true),
('german','admin.role','Rolle','admin',true,true),
('german','admin.status','Status','admin',true,true),
('german','admin.location','Standort','admin',true,true),
('german','admin.join_date','Beitrittsdatum','admin',true,true),
('german','admin.landing_page_editor','Landingpage-Editor','admin',true,true),
('german','admin.landing_page_editor_desc','Inhalte der öffentlichen Landingpage bearbeiten','admin',true,true),
('german','admin.save_changes','Änderungen speichern','admin',true,true),
('german','admin.footer_content','Fußzeileninhalt','admin',true,true),
('german','admin.footer_content_desc','Den in der Fußzeile angezeigten Inhalt bearbeiten','admin',true,true),
('german','admin.copyright_text','Urheberrechtstext','admin',true,true),
('german','admin.avg_registration_time','Durchschn. Registrierungszeit','admin',true,true),
('german','admin.completion_rate','Abschlussrate','admin',true,true),
('german','admin.drop_off_rate','Abbruchrate','admin',true,true),
('german','admin.daily_signups','Tägliche Anmeldungen','admin',true,true),
('german','admin.reg_step_completion','Abschluss der Registrierungsschritte','admin',true,true),
('german','admin.user_status_distribution','Benutzerstatusverteilung','admin',true,true),
('german','admin.profile_section_completion','Abschlussraten der Profilabschnitte','admin',true,true),
('german','admin.bulk_actions','Massenaktionen','admin',true,true),
('german','admin.select_action','Aktion auswählen','admin',true,true),
('german','admin.choose_bulk_action','Massenaktion wählen','admin',true,true),
('german','admin.target_users','Zielbenutzer','admin',true,true),
('german','admin.select_user_group','Benutzergruppe auswählen','admin',true,true),
('german','admin.all_users','Alle Benutzer','admin',true,true),
('german','admin.pending_verification','Ausstehende Verifizierung','admin',true,true),
('german','admin.premium_users','Premium-Benutzer','admin',true,true),
('german','admin.free_users','Kostenlose Benutzer','admin',true,true),
('german','admin.filters','Filter','admin',true,true),
('german','admin.filter_by_location','Nach Standort filtern','admin',true,true),
('german','admin.filter_by_join_date','Nach Beitrittsdatum filtern','admin',true,true),
('german','admin.filter_by_activity','Nach Aktivitätslevel filtern','admin',true,true),
('german','admin.execute_bulk_action','Massenaktion ausführen','admin',true,true),
('german','admin.quick_actions','Schnellaktionen','admin',true,true),
('german','admin.execute','Ausführen','admin',true,true),
('german','admin.field_specific_tools','Feldspezifische Werkzeuge','admin',true,true),
('german','admin.location_verification','Standortverifizierung','admin',true,true),
('german','admin.verify_locations_desc','Benutzerstandorte verifizieren und standardisieren','admin',true,true),
('german','admin.verify_locations','Standorte verifizieren','admin',true,true),
('german','admin.photo_moderation','Fotomoderation','admin',true,true),
('german','admin.review_photos_desc','Ausstehende Fotos prüfen und genehmigen','admin',true,true),
('german','admin.review_photos','Fotos prüfen','admin',true,true),
('german','admin.content_check','Inhaltsüberprüfung','admin',true,true),
('german','admin.scan_content_desc','Profile auf unangemessene Inhalte prüfen','admin',true,true),
('german','admin.scan_content','Inhalte scannen','admin',true,true),
('german','admin.pending_review','Ausstehende Überprüfung','admin',true,true),
('german','admin.flagged_content','Markierter Inhalt','admin',true,true),
('german','admin.high_risk','Hohes Risiko','admin',true,true),
('german','admin.auto_approved','Automatisch genehmigt','admin',true,true),
('german','admin.moderation_queue','Moderationswarteschlange','admin',true,true),
('german','admin.review','Überprüfen','admin',true,true),
('german','admin.reject','Ablehnen','admin',true,true),
('german','admin.approve','Genehmigen','admin',true,true),
('german','admin.export_configuration','Exportkonfiguration','admin',true,true),
('german','admin.export_format','Exportformat','admin',true,true),
('german','admin.user_filter','Benutzerfilter','admin',true,true),
('german','admin.active_users_only','Nur aktive Benutzer','admin',true,true),
('german','admin.verified_users_only','Nur verifizierte Benutzer','admin',true,true),
('german','admin.premium_users_only','Nur Premium-Benutzer','admin',true,true),
('german','admin.recently_joined','Kürzlich beigetreten','admin',true,true),
('german','admin.export_options','Exportoptionen','admin',true,true),
('german','admin.anonymize_data','Persönliche Daten anonymisieren','admin',true,true),
('german','admin.compress_export','Exportdatei komprimieren','admin',true,true),
('german','admin.email_export_link','Exportlink per E-Mail senden','admin',true,true),
('german','admin.quick_exports','Schnellexport','admin',true,true),
('german','admin.user_list_basic','Benutzerliste (Grundinfos)','admin',true,true),
('german','admin.full_user_database','Vollständige Benutzerdatenbank','admin',true,true),
('german','admin.analytics_report','Analysebericht','admin',true,true),
('german','admin.registration_statistics','Registrierungsstatistiken','admin',true,true),
('german','admin.select_fields_export','Felder zum Exportieren auswählen','admin',true,true),
('german','admin.fields_selected','{{count}} Felder ausgewählt','admin',true,true),
('german','admin.clear_all','Alle löschen','admin',true,true),
('german','admin.export_selected_fields','Ausgewählte Felder exportieren','admin',true,true),

-- Kurdish Sorani
('kurdish_sorani','admin.social_login_management','بەڕێوەبردنی چوونەژوورەوەی کۆمەڵایەتی','admin',true,true),
('kurdish_sorani','admin.system_settings','ڕێکخستنەکانی سیستەم','admin',true,true),
('kurdish_sorani','admin.dashboard','داشبۆرد','admin',true,true),
('kurdish_sorani','admin.likes_management','بەڕێوەبردنی لایکەکان','admin',true,true),
('kurdish_sorani','admin.groups_management','بەڕێوەبردنی گرووپەکان','admin',true,true),
('kurdish_sorani','admin.registration_questions','پرسیارەکانی تۆمارکردن','admin',true,true),
('kurdish_sorani','admin.refresh','نوێکردنەوە','admin',true,true),
('kurdish_sorani','admin.advanced_user_management','بەڕێوەبردنی پێشکەوتووی بەکارهێنەر','admin',true,true),
('kurdish_sorani','admin.landing_page_editor','ئێدیتەری پەڕەی دەستپێک','admin',true,true),
('kurdish_sorani','admin.save_changes','پاشەکەوتکردنی گۆڕانکاریەکان','admin',true,true),

-- Kurdish Kurmanci
('kurdish_kurmanci','admin.social_login_management','Rêveberiya têketina civakî','admin',true,true),
('kurdish_kurmanci','admin.system_settings','Mîhengên pergalê','admin',true,true),
('kurdish_kurmanci','admin.dashboard','Dashboard','admin',true,true),
('kurdish_kurmanci','admin.likes_management','Rêveberiya likes','admin',true,true),
('kurdish_kurmanci','admin.groups_management','Rêveberiya koman','admin',true,true),
('kurdish_kurmanci','admin.registration_questions','Pirsên tomarkirinê','admin',true,true),
('kurdish_kurmanci','admin.refresh','Nûkirin','admin',true,true),
('kurdish_kurmanci','admin.advanced_user_management','Rêveberiya bikarhêneran a pêşketî','admin',true,true),
('kurdish_kurmanci','admin.landing_page_editor','Edîtora rûpelê destpêkê','admin',true,true),
('kurdish_kurmanci','admin.save_changes','Guhertinan tomar bike','admin',true,true)

ON CONFLICT (language_code, translation_key) DO UPDATE SET translation_value = EXCLUDED.translation_value;
