INSERT INTO public.app_translations (language_code, translation_key, translation_value, category, context) VALUES
-- Career/Step5Career
('english','career.high_school','High School','auth','Step5Career'),
('english','career.some_college','Some College','auth','Step5Career'),
('english','career.bachelors','Bachelor''s Degree','auth','Step5Career'),
('english','career.masters','Master''s Degree','auth','Step5Career'),
('english','career.doctorate','Doctorate','auth','Step5Career'),
('english','career.trade_school','Trade School','auth','Step5Career'),
('english','career.title','Your professional life','auth','Step5Career'),
('english','career.subtitle','Tell us about your education and career','auth','Step5Career'),
('english','career.education_level','Education Level','auth','Step5Career'),
('english','career.occupation','Occupation','auth','Step5Career'),
('english','career.occupation_placeholder','e.g., Software Engineer, Teacher, Doctor','auth','Step5Career'),
('english','career.company','Company/Organization','auth','Step5Career'),
('english','career.company_placeholder','Where do you work?','auth','Step5Career'),
-- Search/Filters
('english','search.advanced_filters','Advanced Filters','search','AdvancedSearchFilters'),
('english','search.age_range','Age Range','search','AdvancedSearchFilters'),
('english','search.gender','Gender','search','AdvancedSearchFilters'),
('english','search.select_gender','Select gender','search','AdvancedSearchFilters'),
('english','search.location','Location','search','AdvancedSearchFilters'),
('english','search.enter_city','Enter city or country','search','AdvancedSearchFilters'),
('english','search.kurdistan_region','Kurdistan Region','search','AdvancedSearchFilters'),
('english','search.select_region','Select region','search','AdvancedSearchFilters'),
('english','search.all_regions','All Regions','search','AdvancedSearchFilters'),
('english','common.clear','Clear','common','AdvancedSearchFilters'),
('english','common.all','All','common','common'),
('english','common.male','Male','common','common'),
('english','common.female','Female','common','common'),
('english','common.other','Other','common','common'),
('english','common.error','Error','common','common'),
('english','common.success','Success','common','common'),
('english','common.delete','Delete','common','common'),
('english','region.south','South-Kurdistan','profile','region'),
('english','region.north','North-Kurdistan','profile','region'),
('english','region.east','East-Kurdistan','profile','region'),
('english','region.west','West-Kurdistan','profile','region'),
-- Unmatch
('english','toast.unmatch.success','You have unmatched with {{name}}','chat','UnmatchDialog'),
('english','unmatch.title','Unmatch with {{name}}?','chat','UnmatchDialog'),
('english','unmatch.description','This action cannot be undone. You will no longer be able to message each other, and your conversation history will be lost. {{name}} will not be notified.','chat','UnmatchDialog'),
('english','unmatch.unmatching','Unmatching...','chat','UnmatchDialog'),
('english','unmatch.unmatch','Unmatch','chat','UnmatchDialog'),
-- Hashtag
('english','hashtag.search_placeholder','Search hashtags...','social','HashtagSearch'),
('english','hashtag.trending','Trending Hashtags','social','HashtagSearch'),
-- Verification guidelines
('english','verification.guideline_face','Make sure your face is clearly visible','verification','VerificationForm'),
('english','verification.guideline_lighting','Use good lighting','verification','VerificationForm'),
('english','verification.guideline_no_glasses','Remove sunglasses or masks','verification','VerificationForm'),
('english','verification.guideline_camera','Look directly at the camera','verification','VerificationForm'),
('english','verification.guideline_valid_id','ID must be valid and not expired','verification','VerificationForm'),
('english','verification.guideline_readable','All text should be clearly readable','verification','VerificationForm'),
('english','verification.guideline_no_glare','No glare or shadows on the document','verification','VerificationForm'),
('english','verification.guideline_original','Photo should be original (not a photocopy)','verification','VerificationForm'),
-- Location
('english','location.search_placeholder','Search for your city...','auth','LocationSearchSelector'),
('english','location.search_city','Search city...','auth','LocationSearchSelector'),
('english','location.not_found','No location found.','auth','LocationSearchSelector'),
-- Occupation
('english','occupation.select','Select occupation...','auth','SimpleOccupationSelector'),
('english','occupation.search','Search occupations...','auth','SimpleOccupationSelector'),
('english','occupation.not_found','No occupations found','auth','SimpleOccupationSelector'),
-- Delete/Share post
('english','delete_post.title','Delete Post','social','DeletePostDialog'),
('english','delete_post.description','Are you sure you want to delete this post? This action cannot be undone.','social','DeletePostDialog'),
('english','share.title','Share Post','social','SharePostDialog'),
('english','share.copy_link','Copy Link','social','SharePostDialog'),
('english','share.whatsapp','Share via WhatsApp','social','SharePostDialog'),
('english','share.facebook','Share on Facebook','social','SharePostDialog'),
('english','share.twitter','Share on Twitter','social','SharePostDialog'),
('english','share.email','Share via Email','social','SharePostDialog'),
('english','share.post_url','Post URL:','social','SharePostDialog'),
-- Admin tabs
('english','admin.basics','Basics','admin','RegistrationQuestionsPage'),
('english','admin.lifestyle','Lifestyle','admin','RegistrationQuestionsPage'),
('english','admin.beliefs','Beliefs','admin','RegistrationQuestionsPage'),
('english','admin.relationships','Relationships','admin','RegistrationQuestionsPage'),
('english','admin.personality','Personality','admin','RegistrationQuestionsPage'),
('english','admin.interests','Interests','admin','RegistrationQuestionsPage'),
-- Admin email campaigns
('english','admin.duplicate','Duplicate','admin','EmailCampaignsPage'),
('english','admin.edit','Edit','admin','EmailCampaignsPage'),
('english','admin.not_scheduled','Not scheduled','admin','EmailCampaignsPage'),
('english','admin.campaign_performance','Campaign Performance','admin','EmailCampaignsPage'),
('english','admin.daily_engagement','Daily Engagement','admin','EmailCampaignsPage'),
('english','admin.ai_recommendations','AI Recommendations','admin','EmailCampaignsPage'),
('english','admin.ai_recommendations_text','Based on engagement patterns, we recommend sending this campaign on Tuesdays or Wednesdays for optimal open rates.','admin','EmailCampaignsPage'),
('english','admin.draft_campaign','Draft Campaign','admin','EmailCampaignsPage'),
('english','admin.draft_no_metrics','This campaign hasn''t been sent yet. No performance metrics available.','admin','EmailCampaignsPage'),
('english','admin.edit_campaign','Edit Campaign','admin','EmailCampaignsPage'),
('english','admin.schedule_campaign','Schedule Campaign','admin','EmailCampaignsPage'),
('english','admin.pause_campaign','Pause Campaign','admin','EmailCampaignsPage'),
('english','admin.active_campaigns','Active Campaigns','admin','EmailCampaignsPage'),
('english','admin.active_campaigns_desc','Campaigns that are currently active','admin','EmailCampaignsPage'),
('english','admin.scheduled_campaigns','Scheduled Campaigns','admin','EmailCampaignsPage'),
('english','admin.scheduled_campaigns_desc','Campaigns that are scheduled to be sent','admin','EmailCampaignsPage'),
('english','admin.paused_campaigns_title','Paused Campaigns','admin','EmailCampaignsPage'),
('english','admin.paused_campaigns_desc','Campaigns that have been paused','admin','EmailCampaignsPage'),
('english','admin.draft_campaigns','Draft Campaigns','admin','EmailCampaignsPage'),
('english','admin.draft_campaigns_desc','Campaigns in preparation','admin','EmailCampaignsPage'),
('english','admin.create_campaign','Create New Email Campaign','admin','EmailCampaignsPage'),
('english','admin.create_campaign_desc','Set up a new email campaign to engage with your users.','admin','EmailCampaignsPage'),
('english','admin.campaign_name_placeholder','e.g., Summer Promotion','admin','EmailCampaignsPage'),
('english','admin.target_audience','Target Audience','admin','EmailCampaignsPage'),
('english','admin.select_audience','Select audience','admin','EmailCampaignsPage'),
('english','admin.new_users','New Users','admin','EmailCampaignsPage'),
('english','admin.inactive_users','Inactive Users','admin','EmailCampaignsPage'),
('english','admin.premium_users','Premium Users','admin','EmailCampaignsPage'),
('english','admin.free_users','Free Users','admin','EmailCampaignsPage'),
('english','admin.subject_line','Subject Line','admin','EmailCampaignsPage'),
('english','admin.subject_placeholder','Enter email subject line','admin','EmailCampaignsPage'),
('english','admin.email_content','Email Content','admin','EmailCampaignsPage'),
('english','admin.email_content_placeholder','Enter email content...','admin','EmailCampaignsPage'),
('english','admin.send_date','Send Date','admin','EmailCampaignsPage'),
('english','admin.send_time','Send Time','admin','EmailCampaignsPage'),
('english','admin.campaign_type','Campaign Type','admin','EmailCampaignsPage'),
('english','admin.select_type','Select campaign type','admin','EmailCampaignsPage'),
('english','admin.one_time','One-time Campaign','admin','EmailCampaignsPage'),
('english','admin.recurring','Recurring Campaign','admin','EmailCampaignsPage'),
('english','admin.automated','Automated Trigger Campaign','admin','EmailCampaignsPage'),
('english','admin.save_draft','Save as Draft','admin','EmailCampaignsPage'),
-- Norwegian translations
('norwegian','career.title','Ditt profesjonelle liv','auth','Step5Career'),
('norwegian','career.subtitle','Fortell oss om utdanning og karriere','auth','Step5Career'),
('norwegian','career.education_level','Utdanningsnivå','auth','Step5Career'),
('norwegian','career.occupation','Yrke','auth','Step5Career'),
('norwegian','career.occupation_placeholder','f.eks. Programvareutvikler, Lærer, Lege','auth','Step5Career'),
('norwegian','career.company','Bedrift/Organisasjon','auth','Step5Career'),
('norwegian','career.company_placeholder','Hvor jobber du?','auth','Step5Career'),
('norwegian','career.high_school','Videregående','auth','Step5Career'),
('norwegian','career.some_college','Noe høyere utdanning','auth','Step5Career'),
('norwegian','career.bachelors','Bachelorgrad','auth','Step5Career'),
('norwegian','career.masters','Mastergrad','auth','Step5Career'),
('norwegian','career.doctorate','Doktorgrad','auth','Step5Career'),
('norwegian','career.trade_school','Fagskole','auth','Step5Career'),
('norwegian','search.advanced_filters','Avanserte filtre','search','AdvancedSearchFilters'),
('norwegian','search.age_range','Aldersgruppe','search','AdvancedSearchFilters'),
('norwegian','search.gender','Kjønn','search','AdvancedSearchFilters'),
('norwegian','search.select_gender','Velg kjønn','search','AdvancedSearchFilters'),
('norwegian','search.location','Sted','search','AdvancedSearchFilters'),
('norwegian','search.enter_city','Skriv inn by eller land','search','AdvancedSearchFilters'),
('norwegian','search.kurdistan_region','Kurdistan-region','search','AdvancedSearchFilters'),
('norwegian','search.select_region','Velg region','search','AdvancedSearchFilters'),
('norwegian','search.all_regions','Alle regioner','search','AdvancedSearchFilters'),
('norwegian','common.clear','Tøm','common','common'),
('norwegian','common.all','Alle','common','common'),
('norwegian','common.male','Mann','common','common'),
('norwegian','common.female','Kvinne','common','common'),
('norwegian','common.other','Annet','common','common'),
('norwegian','common.error','Feil','common','common'),
('norwegian','common.success','Suksess','common','common'),
('norwegian','common.delete','Slett','common','common'),
('norwegian','unmatch.title','Fjern match med {{name}}?','chat','UnmatchDialog'),
('norwegian','unmatch.description','Denne handlingen kan ikke angres. Dere vil ikke lenger kunne sende meldinger, og samtalehistorikken slettes. {{name}} vil ikke bli varslet.','chat','UnmatchDialog'),
('norwegian','unmatch.unmatching','Fjerner match...','chat','UnmatchDialog'),
('norwegian','unmatch.unmatch','Fjern match','chat','UnmatchDialog'),
('norwegian','toast.unmatch.success','Du har fjernet matchen med {{name}}','chat','UnmatchDialog'),
('norwegian','hashtag.search_placeholder','Søk i emneknagger...','social','HashtagSearch'),
('norwegian','hashtag.trending','Populære emneknagger','social','HashtagSearch'),
('norwegian','delete_post.title','Slett innlegg','social','DeletePostDialog'),
('norwegian','delete_post.description','Er du sikker på at du vil slette dette innlegget? Denne handlingen kan ikke angres.','social','DeletePostDialog'),
('norwegian','share.title','Del innlegg','social','SharePostDialog'),
('norwegian','share.copy_link','Kopier lenke','social','SharePostDialog'),
('norwegian','share.whatsapp','Del via WhatsApp','social','SharePostDialog'),
('norwegian','share.facebook','Del på Facebook','social','SharePostDialog'),
('norwegian','share.twitter','Del på Twitter','social','SharePostDialog'),
('norwegian','share.email','Del via e-post','social','SharePostDialog'),
('norwegian','share.post_url','Innleggslenke:','social','SharePostDialog'),
('norwegian','location.search_placeholder','Søk etter din by...','auth','LocationSearchSelector'),
('norwegian','location.search_city','Søk by...','auth','LocationSearchSelector'),
('norwegian','location.not_found','Ingen sted funnet.','auth','LocationSearchSelector'),
('norwegian','occupation.select','Velg yrke...','auth','SimpleOccupationSelector'),
('norwegian','occupation.search','Søk i yrker...','auth','SimpleOccupationSelector'),
('norwegian','occupation.not_found','Ingen yrker funnet','auth','SimpleOccupationSelector'),
('norwegian','verification.guideline_face','Sørg for at ansiktet ditt er tydelig synlig','verification','VerificationForm'),
('norwegian','verification.guideline_lighting','Bruk god belysning','verification','VerificationForm'),
('norwegian','verification.guideline_no_glasses','Fjern solbriller eller masker','verification','VerificationForm'),
('norwegian','verification.guideline_camera','Se direkte inn i kameraet','verification','VerificationForm'),
('norwegian','verification.guideline_valid_id','ID må være gyldig og ikke utløpt','verification','VerificationForm'),
('norwegian','verification.guideline_readable','All tekst bør være tydelig lesbar','verification','VerificationForm'),
('norwegian','verification.guideline_no_glare','Ingen gjenskinn eller skygger på dokumentet','verification','VerificationForm'),
('norwegian','verification.guideline_original','Bildet bør være originalt (ikke kopi)','verification','VerificationForm'),
-- German translations
('german','career.title','Dein Berufsleben','auth','Step5Career'),
('german','career.subtitle','Erzähle uns von deiner Ausbildung und Karriere','auth','Step5Career'),
('german','career.education_level','Bildungsniveau','auth','Step5Career'),
('german','career.occupation','Beruf','auth','Step5Career'),
('german','career.occupation_placeholder','z.B. Softwareentwickler, Lehrer, Arzt','auth','Step5Career'),
('german','career.company','Unternehmen/Organisation','auth','Step5Career'),
('german','career.company_placeholder','Wo arbeitest du?','auth','Step5Career'),
('german','career.high_school','Abitur','auth','Step5Career'),
('german','career.some_college','Teilstudium','auth','Step5Career'),
('german','career.bachelors','Bachelor-Abschluss','auth','Step5Career'),
('german','career.masters','Master-Abschluss','auth','Step5Career'),
('german','career.doctorate','Doktortitel','auth','Step5Career'),
('german','career.trade_school','Berufsschule','auth','Step5Career'),
('german','search.advanced_filters','Erweiterte Filter','search','AdvancedSearchFilters'),
('german','search.age_range','Altersgruppe','search','AdvancedSearchFilters'),
('german','search.gender','Geschlecht','search','AdvancedSearchFilters'),
('german','search.select_gender','Geschlecht wählen','search','AdvancedSearchFilters'),
('german','search.location','Standort','search','AdvancedSearchFilters'),
('german','search.enter_city','Stadt oder Land eingeben','search','AdvancedSearchFilters'),
('german','search.kurdistan_region','Kurdistan-Region','search','AdvancedSearchFilters'),
('german','search.select_region','Region wählen','search','AdvancedSearchFilters'),
('german','search.all_regions','Alle Regionen','search','AdvancedSearchFilters'),
('german','common.clear','Löschen','common','common'),
('german','common.all','Alle','common','common'),
('german','common.male','Männlich','common','common'),
('german','common.female','Weiblich','common','common'),
('german','common.other','Andere','common','common'),
('german','common.error','Fehler','common','common'),
('german','common.success','Erfolg','common','common'),
('german','common.delete','Löschen','common','common'),
('german','unmatch.title','Match mit {{name}} aufheben?','chat','UnmatchDialog'),
('german','unmatch.description','Diese Aktion kann nicht rückgängig gemacht werden. Ihr könnt euch nicht mehr schreiben und der Chatverlauf geht verloren. {{name}} wird nicht benachrichtigt.','chat','UnmatchDialog'),
('german','unmatch.unmatching','Wird aufgehoben...','chat','UnmatchDialog'),
('german','unmatch.unmatch','Match aufheben','chat','UnmatchDialog'),
('german','toast.unmatch.success','Du hast das Match mit {{name}} aufgehoben','chat','UnmatchDialog'),
('german','hashtag.search_placeholder','Hashtags suchen...','social','HashtagSearch'),
('german','hashtag.trending','Beliebte Hashtags','social','HashtagSearch'),
('german','delete_post.title','Beitrag löschen','social','DeletePostDialog'),
('german','delete_post.description','Bist du sicher, dass du diesen Beitrag löschen möchtest? Diese Aktion kann nicht rückgängig gemacht werden.','social','DeletePostDialog'),
('german','share.title','Beitrag teilen','social','SharePostDialog'),
('german','share.copy_link','Link kopieren','social','SharePostDialog'),
('german','share.whatsapp','Über WhatsApp teilen','social','SharePostDialog'),
('german','share.facebook','Auf Facebook teilen','social','SharePostDialog'),
('german','share.twitter','Auf Twitter teilen','social','SharePostDialog'),
('german','share.email','Per E-Mail teilen','social','SharePostDialog'),
('german','share.post_url','Beitrags-URL:','social','SharePostDialog'),
('german','location.search_placeholder','Nach deiner Stadt suchen...','auth','LocationSearchSelector'),
('german','location.search_city','Stadt suchen...','auth','LocationSearchSelector'),
('german','location.not_found','Kein Ort gefunden.','auth','LocationSearchSelector'),
('german','occupation.select','Beruf auswählen...','auth','SimpleOccupationSelector'),
('german','occupation.search','Berufe suchen...','auth','SimpleOccupationSelector'),
('german','occupation.not_found','Keine Berufe gefunden','auth','SimpleOccupationSelector'),
('german','verification.guideline_face','Stelle sicher, dass dein Gesicht klar sichtbar ist','verification','VerificationForm'),
('german','verification.guideline_lighting','Verwende gute Beleuchtung','verification','VerificationForm'),
('german','verification.guideline_no_glasses','Entferne Sonnenbrillen oder Masken','verification','VerificationForm'),
('german','verification.guideline_camera','Schaue direkt in die Kamera','verification','VerificationForm'),
('german','verification.guideline_valid_id','Ausweis muss gültig und nicht abgelaufen sein','verification','VerificationForm'),
('german','verification.guideline_readable','Alle Texte sollten deutlich lesbar sein','verification','VerificationForm'),
('german','verification.guideline_no_glare','Keine Reflexionen oder Schatten auf dem Dokument','verification','VerificationForm'),
('german','verification.guideline_original','Foto sollte original sein (keine Kopie)','verification','VerificationForm'),
-- Kurdish Sorani
('kurdish_sorani','career.title','ژیانی پیشەییت','auth','Step5Career'),
('kurdish_sorani','career.subtitle','دەربارەی خوێندن و کارەکەت بمانڵێ','auth','Step5Career'),
('kurdish_sorani','career.education_level','ئاستی خوێندن','auth','Step5Career'),
('kurdish_sorani','career.occupation','پیشە','auth','Step5Career'),
('kurdish_sorani','career.company','کۆمپانیا/ڕێکخراو','auth','Step5Career'),
('kurdish_sorani','search.advanced_filters','فلتەری پێشکەوتوو','search','AdvancedSearchFilters'),
('kurdish_sorani','search.age_range','مەودای تەمەن','search','AdvancedSearchFilters'),
('kurdish_sorani','search.gender','ڕەگەز','search','AdvancedSearchFilters'),
('kurdish_sorani','search.location','شوێن','search','AdvancedSearchFilters'),
('kurdish_sorani','search.kurdistan_region','هەرێمی کوردستان','search','AdvancedSearchFilters'),
('kurdish_sorani','search.all_regions','هەموو هەرێمەکان','search','AdvancedSearchFilters'),
('kurdish_sorani','common.clear','پاککردنەوە','common','common'),
('kurdish_sorani','common.all','هەموو','common','common'),
('kurdish_sorani','common.male','نێر','common','common'),
('kurdish_sorani','common.female','مێ','common','common'),
('kurdish_sorani','common.other','تر','common','common'),
('kurdish_sorani','common.error','هەڵە','common','common'),
('kurdish_sorani','common.success','سەرکەوتوو','common','common'),
('kurdish_sorani','common.delete','سڕینەوە','common','common'),
('kurdish_sorani','unmatch.title','ماتچ لەگەڵ {{name}} هەڵبوەشێنیتەوە؟','chat','UnmatchDialog'),
('kurdish_sorani','unmatch.unmatch','هەڵوەشاندنەوەی ماتچ','chat','UnmatchDialog'),
('kurdish_sorani','hashtag.search_placeholder','گەڕان لە هاشتاگ...','social','HashtagSearch'),
('kurdish_sorani','hashtag.trending','هاشتاگە بەنرخەکان','social','HashtagSearch'),
('kurdish_sorani','delete_post.title','سڕینەوەی بابەت','social','DeletePostDialog'),
('kurdish_sorani','share.title','هاوبەشکردنی بابەت','social','SharePostDialog'),
('kurdish_sorani','share.copy_link','کۆپیکردنی لینک','social','SharePostDialog'),
('kurdish_sorani','location.search_placeholder','بگەڕێ بۆ شارەکەت...','auth','LocationSearchSelector'),
('kurdish_sorani','location.not_found','هیچ شوێنێک نەدۆزرایەوە.','auth','LocationSearchSelector'),
('kurdish_sorani','occupation.select','پیشە هەڵبژێرە...','auth','SimpleOccupationSelector'),
('kurdish_sorani','occupation.not_found','هیچ پیشەیەک نەدۆزرایەوە','auth','SimpleOccupationSelector'),
-- Kurdish Kurmanci
('kurdish_kurmanci','career.title','Jiyana te ya pîşeyî','auth','Step5Career'),
('kurdish_kurmanci','career.subtitle','Ji me re behsa xwendin û kariyera xwe bike','auth','Step5Career'),
('kurdish_kurmanci','career.education_level','Asta perwerdehiyê','auth','Step5Career'),
('kurdish_kurmanci','career.occupation','Pîşe','auth','Step5Career'),
('kurdish_kurmanci','career.company','Şirket/Rêxistin','auth','Step5Career'),
('kurdish_kurmanci','search.advanced_filters','Fîlterên pêşketî','search','AdvancedSearchFilters'),
('kurdish_kurmanci','search.age_range','Rêza temenê','search','AdvancedSearchFilters'),
('kurdish_kurmanci','search.gender','Zayend','search','AdvancedSearchFilters'),
('kurdish_kurmanci','search.location','Cih','search','AdvancedSearchFilters'),
('kurdish_kurmanci','search.kurdistan_region','Herêma Kurdistanê','search','AdvancedSearchFilters'),
('kurdish_kurmanci','search.all_regions','Hemû herêm','search','AdvancedSearchFilters'),
('kurdish_kurmanci','common.clear','Paqij bike','common','common'),
('kurdish_kurmanci','common.all','Hemû','common','common'),
('kurdish_kurmanci','common.male','Nêr','common','common'),
('kurdish_kurmanci','common.female','Mê','common','common'),
('kurdish_kurmanci','common.other','Yên din','common','common'),
('kurdish_kurmanci','common.error','Çewtî','common','common'),
('kurdish_kurmanci','common.success','Serketî','common','common'),
('kurdish_kurmanci','common.delete','Jêbirin','common','common'),
('kurdish_kurmanci','unmatch.title','Lihevhatina bi {{name}} re betal bike?','chat','UnmatchDialog'),
('kurdish_kurmanci','unmatch.unmatch','Lihevhatinê betal bike','chat','UnmatchDialog'),
('kurdish_kurmanci','hashtag.search_placeholder','Li hashtagan bigere...','social','HashtagSearch'),
('kurdish_kurmanci','hashtag.trending','Hashtagên populer','social','HashtagSearch'),
('kurdish_kurmanci','delete_post.title','Postê jêbibe','social','DeletePostDialog'),
('kurdish_kurmanci','share.title','Postê parve bike','social','SharePostDialog'),
('kurdish_kurmanci','share.copy_link','Lînkê kopî bike','social','SharePostDialog'),
('kurdish_kurmanci','location.search_placeholder','Li bajarê xwe bigere...','auth','LocationSearchSelector'),
('kurdish_kurmanci','location.not_found','Tu cih nehat dîtin.','auth','LocationSearchSelector'),
('kurdish_kurmanci','occupation.select','Pîşe hilbijêre...','auth','SimpleOccupationSelector'),
('kurdish_kurmanci','occupation.not_found','Tu pîşe nehat dîtin','auth','SimpleOccupationSelector')
ON CONFLICT (language_code, translation_key) DO NOTHING;