
-- Batch 5: Remaining user-facing i18n translations
INSERT INTO public.app_translations (language_code, translation_key, translation_value, category) VALUES
-- DeleteAccountDialog
('english', 'toast.account.enter_password', 'Please enter your password to confirm', 'auth'),
('english', 'toast.account.deactivated', 'Account deactivated. You can reactivate by logging in again.', 'auth'),
('english', 'toast.account.deletion_scheduled', 'Account deletion scheduled. You have 30 days to cancel this request.', 'auth'),
('english', 'toast.account.deletion_failed', 'Failed to process account deletion request', 'auth'),
('english', 'account.important_decision', 'Important Decision', 'auth'),
('english', 'account.important_decision_desc', 'This action will affect your account and data. Please choose carefully.', 'auth'),
('english', 'account.choose_action', 'Choose an action:', 'auth'),
('english', 'account.deactivate', 'Deactivate Account', 'auth'),
('english', 'account.deactivate_desc', 'Hide your profile temporarily. You can reactivate anytime by logging in again.', 'auth'),
('english', 'account.reversible', 'Reversible • Data preserved', 'auth'),
('english', 'account.delete', 'Delete Account', 'auth'),
('english', 'account.delete_desc', 'Permanently remove your account. You have 30 days to cancel this request.', 'auth'),
('english', 'account.grace_period', '30-day grace period • Data archived', 'auth'),
('english', 'account.final_confirmation', 'Final Confirmation', 'auth'),
('english', 'account.summary', 'Summary', 'auth'),
('english', 'account.action', 'Action:', 'auth'),
('english', 'account.effect', 'Effect:', 'auth'),
('english', 'account.reason_label', 'Reason (Optional)', 'auth'),
('english', 'account.reason_placeholder', 'Help us improve by sharing why you are leaving...', 'auth'),
('english', 'account.confirm_password', 'Confirm Password', 'auth'),
('english', 'account.password_placeholder', 'Enter your password to confirm', 'auth'),
('english', 'account.management_step', 'Account Management - Step {{step}} of 3', 'auth'),
('english', 'common.cancel', 'Cancel', 'common'),
('english', 'common.continue', 'Continue', 'common'),
('english', 'common.back', 'Back', 'common'),
('english', 'common.processing', 'Processing...', 'common'),
('english', 'account.confirm_deactivation', 'Confirm Deactivation', 'auth'),
('english', 'account.confirm_deletion', 'Confirm Deletion', 'auth'),
('english', 'account.immediate', 'Immediate', 'auth'),
('english', 'account.thirty_day_delay', '30-day delay', 'auth'),
-- SendGiftModal
('english', 'toast.gift.sent', '{{emoji}} {{name}} sent to {{recipient}}!', 'common'),
('english', 'toast.gift.send_failed', 'Failed to send gift', 'common'),
('english', 'gift.send_title', 'Send a Gift to {{name}}', 'common'),
('english', 'gift.add_message', 'Add a message (optional)...', 'common'),
('english', 'gift.send_button', 'Send {{name}}', 'common'),
-- SmartFilters
('english', 'toast.filter.premium_required', 'Premium feature', 'discovery'),
('english', 'toast.filter.upgrade_desc', 'Upgrade to use Smart Filters', 'discovery'),
('english', 'filter.smart_filters', 'Smart Filters', 'discovery'),
('english', 'filter.premium_feature', 'Premium Feature', 'discovery'),
('english', 'filter.upgrade_unlock', 'Upgrade to unlock advanced Smart Filters', 'discovery'),
('english', 'filter.basic_preferences', 'Basic Preferences', 'discovery'),
('english', 'filter.age_range', 'Age Range: {{min}} - {{max}}', 'discovery'),
('english', 'filter.distance', 'Distance: {{value}}', 'discovery'),
('english', 'filter.unlimited', 'Unlimited', 'discovery'),
('english', 'filter.region', 'Region', 'discovery'),
('english', 'filter.any_region', 'Any region', 'discovery'),
('english', 'filter.verification', 'Verification', 'discovery'),
('english', 'filter.verified_only', 'Verified profiles only', 'discovery'),
('english', 'filter.video_verified', 'Video verified only', 'discovery'),
('english', 'filter.recently_active', 'Recently active (24h)', 'discovery'),
('english', 'filter.relationship_goals', 'Relationship Goals', 'discovery'),
('english', 'filter.education', 'Education', 'discovery'),
('english', 'filter.ai_compatibility', 'AI Compatibility', 'discovery'),
('english', 'filter.min_compatibility', 'Minimum compatibility: {{value}}%', 'discovery'),
('english', 'filter.compatibility_desc', 'Only show profiles with at least {{value}}% AI-calculated compatibility', 'discovery'),
('english', 'filter.reset', 'Reset', 'discovery'),
('english', 'filter.apply', 'Apply Filters', 'discovery'),
('english', 'filter.upgrade_to_apply', '⭐ Upgrade to Apply', 'discovery'),
('english', 'common.filters', 'Filters', 'common'),
-- ProfileSwipeActions
('english', 'toast.swipe.passed', 'Passed', 'discovery'),
('english', 'toast.swipe.liked', 'Liked!', 'discovery'),
('english', 'toast.swipe.like_failed', 'Failed to process like. Please try again.', 'discovery'),
('english', 'toast.swipe.something_wrong', 'Something went wrong', 'common'),
('english', 'toast.swipe.super_like_sent', 'Super Like sent! ⭐', 'discovery'),
('english', 'toast.swipe.super_like_failed', 'Failed to send Super Like', 'discovery'),
-- ImageUploader
('english', 'toast.image.too_large', 'Image too large', 'common'),
('english', 'toast.image.max_size', 'Max size is {{max}}MB. Your file is {{size}}MB.', 'common'),
-- ConnectedAccountsDialog
('english', 'toast.accounts.connected', '{{platform}} account connected successfully!', 'profile'),
('english', 'toast.accounts.connect_failed', 'Failed to connect {{platform}} account', 'profile'),
('english', 'toast.accounts.disconnected', '{{platform}} account disconnected', 'profile'),
('english', 'toast.accounts.disconnect_failed', 'Failed to disconnect {{platform}} account', 'profile'),
('english', 'accounts.title', 'Connected Accounts', 'profile'),
('english', 'accounts.no_accounts', 'No connected accounts', 'profile'),
('english', 'accounts.connected', 'Connected', 'profile'),
('english', 'accounts.share', 'Share', 'profile'),
('english', 'accounts.connect', 'Connect {{platform}}', 'profile'),
('english', 'accounts.username', 'Username', 'profile'),
('english', 'accounts.username_placeholder', 'Your {{platform}} username', 'profile'),
('english', 'accounts.add_new', 'Add New Account', 'profile'),
('english', 'common.done', 'Done', 'common'),
-- CreateGroupDialog
('english', 'toast.group.name_required', 'Please enter a group name', 'common'),
('english', 'toast.group.created', 'Group created successfully!', 'common'),
('english', 'toast.group.create_failed', 'Failed to create group', 'common'),
('english', 'group.create_title', 'Create New Group', 'common'),
('english', 'group.create_desc', 'Build your community and connect with people who share your interests', 'common'),
('english', 'group.name_label', 'Group Name *', 'common'),
('english', 'group.name_placeholder', 'e.g., Kurdish Tech Professionals', 'common'),
('english', 'group.description_label', 'Description', 'common'),
('english', 'group.description_placeholder', 'Tell people what your group is about...', 'common'),
('english', 'group.category_label', 'Category *', 'common'),
('english', 'group.icon_label', 'Group Icon', 'common'),
('english', 'group.privacy_label', 'Privacy', 'common'),
('english', 'group.public', 'Public', 'common'),
('english', 'group.public_desc', 'Anyone can see and join', 'common'),
('english', 'group.private', 'Private', 'common'),
('english', 'group.private_desc', 'Only members can see content', 'common'),
('english', 'group.creating', 'Creating...', 'common'),
('english', 'group.create_button', 'Create Group', 'common'),
-- LanguageEditor
('english', 'toast.language.max_reached', 'You can select up to {{max}} languages', 'profile'),
('english', 'toast.language.added', 'Added {{language}} to your languages', 'profile'),
('english', 'language.title', 'Languages You Speak', 'profile'),
('english', 'language.no_selected', 'No languages selected', 'profile'),
('english', 'language.add_placeholder', 'Add new languages', 'profile'),
('english', 'common.add', 'Add', 'common'),
('english', 'language.search', 'Search languages...', 'profile'),
('english', 'language.max_warning', 'Maximum of {{max}} languages allowed', 'profile'),
('english', 'language.save', 'Save Languages', 'profile'),
-- SuperLikeButton
('english', 'toast.super_like.limit_reached', 'Daily limit reached', 'discovery'),
('english', 'toast.super_like.limit_desc', 'You have used all your super likes for today', 'discovery'),
('english', 'toast.super_like.sent', 'Super Like sent!', 'discovery'),
('english', 'toast.super_like.sent_desc', 'They will know you really like them ❤️', 'discovery'),
('english', 'toast.super_like.error', 'Failed to send super like', 'discovery'),
('english', 'toast.checkout.error', 'Failed to start checkout', 'discovery'),
('english', 'super_like.premium_title', 'Super Like - Premium Feature', 'discovery'),
('english', 'super_like.premium_desc', 'Super Likes are available to Premium and Gold members!', 'discovery'),
('english', 'super_like.premium_benefits', 'Premium Benefits:', 'discovery'),
('english', 'super_like.upgrade', 'Upgrade to Premium', 'discovery'),
-- SocialLogin
('english', 'toast.social_login.failed', 'Login with {{provider}} failed', 'auth'),
-- LoginForm
('english', 'toast.login.success', 'Success!', 'auth'),
('english', 'toast.login.success_desc', 'You have been logged in successfully.', 'auth'),
('english', 'toast.login.error', 'Failed to log in. Please try again.', 'auth'),
('english', 'toast.login.enter_email', 'Enter your email', 'auth'),
('english', 'toast.login.enter_email_desc', 'Please enter your email address first', 'auth'),
('english', 'toast.login.check_email', 'Check your email', 'auth'),
('english', 'toast.login.reset_link_sent', 'We sent you a password reset link.', 'auth'),
('english', 'auth.email', 'Email', 'auth'),
('english', 'auth.password', 'Password', 'auth'),
('english', 'auth.remember_me', 'Remember me', 'auth'),
('english', 'auth.forgot_password', 'Forgot password?', 'auth'),
('english', 'auth.signing_in', 'Signing in...', 'auth'),
('english', 'auth.sign_in', 'Sign in', 'auth'),
-- useMessageModeration
('english', 'toast.moderation.flagged', 'Message flagged', 'messages'),
('english', 'toast.moderation.flagged_desc', 'This message may violate community guidelines', 'messages'),
('english', 'toast.moderation.failed', 'Moderation check failed', 'messages'),
('english', 'toast.moderation.failed_desc', 'Unable to verify message safety. Proceeding with caution.', 'messages'),
-- HeroSection
('english', 'hero.welcome_admin', 'Welcome Super Admin', 'auth'),
('english', 'hero.admin_redirect', 'You have been redirected to the admin dashboard', 'auth'),
('english', 'hero.welcome_back', 'Welcome back!', 'auth'),
('english', 'hero.login_success', 'You have successfully logged in.', 'auth'),
('english', 'hero.get_started', 'Get Started - It is Free', 'common'),
('english', 'hero.sign_in', 'Sign In', 'auth'),
('english', 'hero.welcome_title', 'Welcome Back', 'auth'),
('english', 'hero.welcome_desc', 'Sign in to continue your journey', 'auth'),
('english', 'hero.no_account', 'Do not have an account? Create one now →', 'auth'),
('english', 'hero.terms', 'By continuing, you agree to our Terms of Service and Privacy Policy', 'auth'),
('english', 'hero.joined_count', '{{count}} Kurdish singles have already joined', 'common'),
-- Norwegian
('norwegian', 'toast.account.enter_password', 'Vennligst skriv inn passordet ditt for å bekrefte', 'auth'),
('norwegian', 'toast.account.deactivated', 'Konto deaktivert. Du kan reaktivere ved å logge inn igjen.', 'auth'),
('norwegian', 'toast.account.deletion_scheduled', 'Kontosletting planlagt. Du har 30 dager til å kansellere.', 'auth'),
('norwegian', 'toast.account.deletion_failed', 'Kunne ikke behandle forespørsel om kontosletting', 'auth'),
('norwegian', 'toast.gift.sent', '{{emoji}} {{name}} sendt til {{recipient}}!', 'common'),
('norwegian', 'toast.gift.send_failed', 'Kunne ikke sende gave', 'common'),
('norwegian', 'toast.filter.premium_required', 'Premium-funksjon', 'discovery'),
('norwegian', 'toast.filter.upgrade_desc', 'Oppgrader for å bruke Smart Filtre', 'discovery'),
('norwegian', 'toast.swipe.passed', 'Hoppet over', 'discovery'),
('norwegian', 'toast.swipe.liked', 'Likt!', 'discovery'),
('norwegian', 'toast.swipe.like_failed', 'Kunne ikke behandle liker. Prøv igjen.', 'discovery'),
('norwegian', 'toast.swipe.something_wrong', 'Noe gikk galt', 'common'),
('norwegian', 'toast.swipe.super_like_sent', 'Super Like sendt! ⭐', 'discovery'),
('norwegian', 'toast.image.too_large', 'Bildet er for stort', 'common'),
('norwegian', 'toast.image.max_size', 'Maks størrelse er {{max}}MB. Din fil er {{size}}MB.', 'common'),
('norwegian', 'toast.accounts.connected', '{{platform}}-konto tilkoblet!', 'profile'),
('norwegian', 'toast.accounts.connect_failed', 'Kunne ikke koble til {{platform}}-konto', 'profile'),
('norwegian', 'toast.accounts.disconnected', '{{platform}}-konto frakoblet', 'profile'),
('norwegian', 'toast.group.name_required', 'Vennligst skriv inn et gruppenavn', 'common'),
('norwegian', 'toast.group.created', 'Gruppe opprettet!', 'common'),
('norwegian', 'toast.group.create_failed', 'Kunne ikke opprette gruppe', 'common'),
('norwegian', 'toast.language.max_reached', 'Du kan velge opptil {{max}} språk', 'profile'),
('norwegian', 'toast.super_like.limit_reached', 'Daglig grense nådd', 'discovery'),
('norwegian', 'toast.super_like.sent', 'Super Like sendt!', 'discovery'),
('norwegian', 'toast.social_login.failed', 'Innlogging med {{provider}} mislyktes', 'auth'),
('norwegian', 'toast.login.success', 'Suksess!', 'auth'),
('norwegian', 'toast.login.success_desc', 'Du har blitt logget inn.', 'auth'),
('norwegian', 'toast.moderation.flagged', 'Melding flagget', 'messages'),
('norwegian', 'toast.moderation.failed', 'Moderasjonssjekk feilet', 'messages'),
('norwegian', 'common.cancel', 'Avbryt', 'common'),
('norwegian', 'common.continue', 'Fortsett', 'common'),
('norwegian', 'common.back', 'Tilbake', 'common'),
('norwegian', 'common.done', 'Ferdig', 'common'),
('norwegian', 'common.add', 'Legg til', 'common'),
('norwegian', 'common.filters', 'Filtre', 'common'),
-- Kurdish Sorani
('kurdish_sorani', 'toast.account.enter_password', 'تکایە وشەی نهێنیت بنووسە بۆ دڵنیابوونەوە', 'auth'),
('kurdish_sorani', 'toast.account.deactivated', 'هەژمار ناچالاک کرا. دەتوانیت بیچالاک کەیتەوە بە چوونەوە ژوورەوە.', 'auth'),
('kurdish_sorani', 'toast.account.deletion_scheduled', 'سڕینەوەی هەژمار پلان دانرا. ٣٠ ڕۆژت هەیە بۆ هەڵوەشاندنەوە.', 'auth'),
('kurdish_sorani', 'toast.swipe.passed', 'تێپەڕیت', 'discovery'),
('kurdish_sorani', 'toast.swipe.liked', 'حەزت لێکرد!', 'discovery'),
('kurdish_sorani', 'toast.swipe.something_wrong', 'هەڵەیەک ڕوویدا', 'common'),
('kurdish_sorani', 'toast.group.created', 'گرووپ دروست کرا!', 'common'),
('kurdish_sorani', 'toast.super_like.sent', 'سوپەر لایک نێردرا!', 'discovery'),
('kurdish_sorani', 'toast.login.success', 'سەرکەوتوو!', 'auth'),
('kurdish_sorani', 'toast.moderation.flagged', 'نامە ئاگاداری لێکرا', 'messages'),
('kurdish_sorani', 'common.cancel', 'پاشگەزبوونەوە', 'common'),
('kurdish_sorani', 'common.continue', 'بەردەوام بە', 'common'),
('kurdish_sorani', 'common.back', 'گەڕانەوە', 'common'),
('kurdish_sorani', 'common.done', 'تەواو', 'common'),
('kurdish_sorani', 'common.add', 'زیادکردن', 'common'),
('kurdish_sorani', 'common.filters', 'فلتەرەکان', 'common'),
-- German
('german', 'toast.account.enter_password', 'Bitte geben Sie Ihr Passwort zur Bestätigung ein', 'auth'),
('german', 'toast.account.deactivated', 'Konto deaktiviert. Sie können es durch erneutes Anmelden reaktivieren.', 'auth'),
('german', 'toast.account.deletion_scheduled', 'Kontolöschung geplant. Sie haben 30 Tage zum Abbrechen.', 'auth'),
('german', 'toast.gift.sent', '{{emoji}} {{name}} an {{recipient}} gesendet!', 'common'),
('german', 'toast.swipe.passed', 'Übersprungen', 'discovery'),
('german', 'toast.swipe.liked', 'Gefällt mir!', 'discovery'),
('german', 'toast.swipe.something_wrong', 'Etwas ist schiefgelaufen', 'common'),
('german', 'toast.group.created', 'Gruppe erstellt!', 'common'),
('german', 'toast.super_like.sent', 'Super Like gesendet!', 'discovery'),
('german', 'toast.login.success', 'Erfolg!', 'auth'),
('german', 'toast.moderation.flagged', 'Nachricht markiert', 'messages'),
('german', 'common.cancel', 'Abbrechen', 'common'),
('german', 'common.continue', 'Weiter', 'common'),
('german', 'common.back', 'Zurück', 'common'),
('german', 'common.done', 'Fertig', 'common'),
('german', 'common.add', 'Hinzufügen', 'common'),
('german', 'common.filters', 'Filter', 'common'),
-- Kurdish Kurmanci
('kurdish_kurmanci', 'toast.account.enter_password', 'Ji kerema xwe şîfreya xwe binivîsin ji bo piştrastkirin', 'auth'),
('kurdish_kurmanci', 'toast.account.deactivated', 'Hesab neçalak kirin. Tu dikarî bi têketinê dîsa çalak bikî.', 'auth'),
('kurdish_kurmanci', 'toast.swipe.passed', 'Derbas kir', 'discovery'),
('kurdish_kurmanci', 'toast.swipe.liked', 'Jê hez kir!', 'discovery'),
('kurdish_kurmanci', 'toast.swipe.something_wrong', 'Tiştek xelet bû', 'common'),
('kurdish_kurmanci', 'toast.group.created', 'Kom hat afirandin!', 'common'),
('kurdish_kurmanci', 'toast.super_like.sent', 'Super Like hat şandin!', 'discovery'),
('kurdish_kurmanci', 'toast.login.success', 'Serkeftin!', 'auth'),
('kurdish_kurmanci', 'common.cancel', 'Betal', 'common'),
('kurdish_kurmanci', 'common.continue', 'Berdewam', 'common'),
('kurdish_kurmanci', 'common.back', 'Paşve', 'common'),
('kurdish_kurmanci', 'common.done', 'Temam', 'common'),
('kurdish_kurmanci', 'common.add', 'Zêde bike', 'common'),
('kurdish_kurmanci', 'common.filters', 'Fîltre', 'common')
ON CONFLICT DO NOTHING;
