
INSERT INTO public.app_translations (language_code, translation_key, translation_value, category, context)
VALUES
-- CategoriesPage keys
('english','admin.items_in_category','Items in {{name}}','admin','categories page'),
('english','admin.all_category_items','All Category Items','admin','categories page'),
('english','admin.manage_items_in_category','Manage items in the "{{name}}" category','admin','categories page'),
('english','admin.select_category_to_manage','Select a category to manage its items','admin','categories page'),
('english','admin.view_all_categories','View All Categories','admin','categories page'),
('english','admin.search_items','Search items...','admin','placeholder'),
('english','admin.no_items_in_category','No items found in this category','admin','categories page'),
('english','admin.create_new_profile_category','Create a new profile category','admin','dialog'),
('english','admin.category_name','Category Name','admin','form label'),
('english','admin.enter_category_name','Enter category name','admin','placeholder'),
('english','admin.enter_description','Enter description','admin','placeholder'),
('english','admin.slug','Slug','admin','form label'),
('english','admin.enter_slug','Enter slug (e.g., basic-info)','admin','placeholder'),
('english','admin.slug_description','Used in URLs and as a unique identifier','admin','form description'),
('english','admin.enable_disable_category','Enable or disable this category','admin','form description'),
('english','admin.update_category','Update Category','admin','button'),
('english','admin.edit_category','Edit Category','admin','dialog title'),
('english','admin.edit_category_desc','Make changes to the selected category','admin','dialog'),
('english','admin.delete_category','Delete Category','admin','dialog title'),
('english','admin.delete_category_confirm','Are you sure you want to delete this category? This action cannot be undone.','admin','dialog'),
('english','admin.all_items_deleted_warning','All items in this category will also be deleted.','admin','warning'),
('english','admin.add_item_to_category','Add a new item to the "{{name}}" category','admin','dialog'),
('english','admin.add_new_item','Add a new item','admin','dialog'),
('english','admin.item_name','Item Name','admin','form label'),
('english','admin.enter_item_name','Enter item name','admin','placeholder'),
('english','admin.type','Type','admin','table header'),
('english','admin.select_type','Select type','admin','placeholder'),
('english','admin.options','Options','admin','form label'),
('english','admin.enter_options_comma','Enter options, separated by commas','admin','placeholder'),
('english','admin.options_comma_desc','Enter options separated by commas (e.g., Option 1, Option 2, Option 3)','admin','form description'),
('english','admin.enable_disable_item','Enable or disable this item','admin','form description'),
('english','admin.update_item','Update Item','admin','button'),
('english','admin.edit_item','Edit Item','admin','dialog title'),
('english','admin.edit_item_desc','Make changes to the selected item','admin','dialog'),
('english','admin.delete_item','Delete Item','admin','dialog title'),
('english','admin.delete_item_confirm','Are you sure you want to delete this item? This action cannot be undone.','admin','dialog'),
('english','admin.last_updated','Last Updated','admin','table header'),
-- AddQuestionDialog keys
('english','admin.question_text_placeholder','e.g., What are your favorite hobbies?','admin','placeholder'),
('english','admin.select_category','Select category','admin','placeholder'),
('english','admin.select_field_type','Select field type','admin','placeholder'),
('english','admin.select_registration_step','Select registration step','admin','placeholder'),
('english','admin.placeholder_example','e.g., Enter your hobbies','admin','placeholder'),
('english','admin.profile_field_example','e.g., hobbies','admin','placeholder'),

-- Norwegian
('norwegian','admin.items_in_category','Elementer i {{name}}','admin','categories page'),
('norwegian','admin.all_category_items','Alle kategorielementer','admin','categories page'),
('norwegian','admin.manage_items_in_category','Administrer elementer i "{{name}}"-kategorien','admin','categories page'),
('norwegian','admin.select_category_to_manage','Velg en kategori for å administrere elementene','admin','categories page'),
('norwegian','admin.view_all_categories','Vis alle kategorier','admin','categories page'),
('norwegian','admin.search_items','Søk i elementer...','admin','placeholder'),
('norwegian','admin.no_items_in_category','Ingen elementer funnet i denne kategorien','admin','categories page'),
('norwegian','admin.create_new_profile_category','Opprett en ny profilkategori','admin','dialog'),
('norwegian','admin.category_name','Kategorinavn','admin','form label'),
('norwegian','admin.enter_category_name','Skriv inn kategorinavn','admin','placeholder'),
('norwegian','admin.enter_description','Skriv inn beskrivelse','admin','placeholder'),
('norwegian','admin.slug','Slug','admin','form label'),
('norwegian','admin.enter_slug','Skriv inn slug (f.eks. grunnleggende-info)','admin','placeholder'),
('norwegian','admin.slug_description','Brukes i URL-er og som en unik identifikator','admin','form description'),
('norwegian','admin.enable_disable_category','Aktiver eller deaktiver denne kategorien','admin','form description'),
('norwegian','admin.update_category','Oppdater kategori','admin','button'),
('norwegian','admin.edit_category','Rediger kategori','admin','dialog title'),
('norwegian','admin.edit_category_desc','Gjør endringer i den valgte kategorien','admin','dialog'),
('norwegian','admin.delete_category','Slett kategori','admin','dialog title'),
('norwegian','admin.delete_category_confirm','Er du sikker på at du vil slette denne kategorien? Denne handlingen kan ikke angres.','admin','dialog'),
('norwegian','admin.all_items_deleted_warning','Alle elementer i denne kategorien vil også bli slettet.','admin','warning'),
('norwegian','admin.add_item_to_category','Legg til et nytt element i "{{name}}"-kategorien','admin','dialog'),
('norwegian','admin.add_new_item','Legg til et nytt element','admin','dialog'),
('norwegian','admin.item_name','Elementnavn','admin','form label'),
('norwegian','admin.enter_item_name','Skriv inn elementnavn','admin','placeholder'),
('norwegian','admin.type','Type','admin','table header'),
('norwegian','admin.select_type','Velg type','admin','placeholder'),
('norwegian','admin.options','Alternativer','admin','form label'),
('norwegian','admin.enter_options_comma','Skriv inn alternativer, separert med komma','admin','placeholder'),
('norwegian','admin.options_comma_desc','Skriv inn alternativer separert med komma (f.eks. Alternativ 1, Alternativ 2, Alternativ 3)','admin','form description'),
('norwegian','admin.enable_disable_item','Aktiver eller deaktiver dette elementet','admin','form description'),
('norwegian','admin.update_item','Oppdater element','admin','button'),
('norwegian','admin.edit_item','Rediger element','admin','dialog title'),
('norwegian','admin.edit_item_desc','Gjør endringer i det valgte elementet','admin','dialog'),
('norwegian','admin.delete_item','Slett element','admin','dialog title'),
('norwegian','admin.delete_item_confirm','Er du sikker på at du vil slette dette elementet? Denne handlingen kan ikke angres.','admin','dialog'),
('norwegian','admin.last_updated','Sist oppdatert','admin','table header'),
('norwegian','admin.question_text_placeholder','f.eks. Hva er hobbyene dine?','admin','placeholder'),
('norwegian','admin.select_category','Velg kategori','admin','placeholder'),
('norwegian','admin.select_field_type','Velg felttype','admin','placeholder'),
('norwegian','admin.select_registration_step','Velg registreringssteg','admin','placeholder'),
('norwegian','admin.placeholder_example','f.eks. Skriv inn hobbyene dine','admin','placeholder'),
('norwegian','admin.profile_field_example','f.eks. hobbyer','admin','placeholder'),

-- Kurdish Sorani
('kurdish_sorani','admin.items_in_category','بابەتەکانی {{name}}','admin','categories page'),
('kurdish_sorani','admin.all_category_items','هەموو بابەتەکانی پۆلەکان','admin','categories page'),
('kurdish_sorani','admin.manage_items_in_category','بەڕێوەبردنی بابەتەکان لە پۆلی "{{name}}"','admin','categories page'),
('kurdish_sorani','admin.select_category_to_manage','پۆلێک هەڵبژێرە بۆ بەڕێوەبردنی بابەتەکانی','admin','categories page'),
('kurdish_sorani','admin.view_all_categories','بینینی هەموو پۆلەکان','admin','categories page'),
('kurdish_sorani','admin.search_items','گەڕان لە بابەتەکان...','admin','placeholder'),
('kurdish_sorani','admin.no_items_in_category','هیچ بابەتێک نەدۆزرایەوە لەم پۆلەدا','admin','categories page'),
('kurdish_sorani','admin.create_new_profile_category','دروستکردنی پۆلی نوێی پرۆفایل','admin','dialog'),
('kurdish_sorani','admin.category_name','ناوی پۆل','admin','form label'),
('kurdish_sorani','admin.enter_category_name','ناوی پۆل بنووسە','admin','placeholder'),
('kurdish_sorani','admin.enter_description','وەسف بنووسە','admin','placeholder'),
('kurdish_sorani','admin.slug','سلەگ','admin','form label'),
('kurdish_sorani','admin.enter_slug','سلەگ بنووسە (بۆ نموونە: زانیاری-سەرەتایی)','admin','placeholder'),
('kurdish_sorani','admin.slug_description','لە URL و وەک ناسنامەی تایبەت بەکاردێت','admin','form description'),
('kurdish_sorani','admin.enable_disable_category','چالاککردن یان ناچالاککردنی ئەم پۆلە','admin','form description'),
('kurdish_sorani','admin.update_category','نوێکردنەوەی پۆل','admin','button'),
('kurdish_sorani','admin.edit_category','دەستکاریکردنی پۆل','admin','dialog title'),
('kurdish_sorani','admin.edit_category_desc','گۆڕانکاری لە پۆلی هەڵبژێردراو بکە','admin','dialog'),
('kurdish_sorani','admin.delete_category','سڕینەوەی پۆل','admin','dialog title'),
('kurdish_sorani','admin.delete_category_confirm','دڵنیایت لە سڕینەوەی ئەم پۆلە؟ ئەم کارە ناگەڕێتەوە.','admin','dialog'),
('kurdish_sorani','admin.all_items_deleted_warning','هەموو بابەتەکانی ئەم پۆلە دەسڕدرێنەوە.','admin','warning'),
('kurdish_sorani','admin.add_item_to_category','زیادکردنی بابەتی نوێ بۆ پۆلی "{{name}}"','admin','dialog'),
('kurdish_sorani','admin.add_new_item','زیادکردنی بابەتی نوێ','admin','dialog'),
('kurdish_sorani','admin.item_name','ناوی بابەت','admin','form label'),
('kurdish_sorani','admin.enter_item_name','ناوی بابەت بنووسە','admin','placeholder'),
('kurdish_sorani','admin.type','جۆر','admin','table header'),
('kurdish_sorani','admin.select_type','جۆر هەڵبژێرە','admin','placeholder'),
('kurdish_sorani','admin.options','هەڵبژاردنەکان','admin','form label'),
('kurdish_sorani','admin.enter_options_comma','هەڵبژاردنەکان بنووسە، بە کۆما جیاکراوە','admin','placeholder'),
('kurdish_sorani','admin.options_comma_desc','هەڵبژاردنەکان بە کۆما جیابکەوە (بۆ نموونە: هەڵبژاردن ١، هەڵبژاردن ٢)','admin','form description'),
('kurdish_sorani','admin.enable_disable_item','چالاککردن یان ناچالاککردنی ئەم بابەتە','admin','form description'),
('kurdish_sorani','admin.update_item','نوێکردنەوەی بابەت','admin','button'),
('kurdish_sorani','admin.edit_item','دەستکاریکردنی بابەت','admin','dialog title'),
('kurdish_sorani','admin.edit_item_desc','گۆڕانکاری لە بابەتی هەڵبژێردراو بکە','admin','dialog'),
('kurdish_sorani','admin.delete_item','سڕینەوەی بابەت','admin','dialog title'),
('kurdish_sorani','admin.delete_item_confirm','دڵنیایت لە سڕینەوەی ئەم بابەتە؟ ئەم کارە ناگەڕێتەوە.','admin','dialog'),
('kurdish_sorani','admin.last_updated','دوایین نوێکردنەوە','admin','table header'),
('kurdish_sorani','admin.question_text_placeholder','بۆ نموونە: ئارەزووەکانت چین؟','admin','placeholder'),
('kurdish_sorani','admin.select_category','پۆل هەڵبژێرە','admin','placeholder'),
('kurdish_sorani','admin.select_field_type','جۆری خانە هەڵبژێرە','admin','placeholder'),
('kurdish_sorani','admin.select_registration_step','هەنگاوی تۆمارکردن هەڵبژێرە','admin','placeholder'),
('kurdish_sorani','admin.placeholder_example','بۆ نموونە: ئارەزووەکانت بنووسە','admin','placeholder'),
('kurdish_sorani','admin.profile_field_example','بۆ نموونە: ئارەزووەکان','admin','placeholder'),

-- Kurdish Kurmanci
('kurdish_kurmanci','admin.items_in_category','Tiştên di {{name}} de','admin','categories page'),
('kurdish_kurmanci','admin.all_category_items','Hemû tiştên kategoriyan','admin','categories page'),
('kurdish_kurmanci','admin.manage_items_in_category','Tiştên di kategoriya "{{name}}" de birêve bibe','admin','categories page'),
('kurdish_kurmanci','admin.select_category_to_manage','Kategoriyek hilbijêre ku tiştên wê birêve bibî','admin','categories page'),
('kurdish_kurmanci','admin.view_all_categories','Hemû kategoriyan bibîne','admin','categories page'),
('kurdish_kurmanci','admin.search_items','Li tiştan bigere...','admin','placeholder'),
('kurdish_kurmanci','admin.no_items_in_category','Di vê kategoriyê de tiştek nehat dîtin','admin','categories page'),
('kurdish_kurmanci','admin.create_new_profile_category','Kategoriya profîlê ya nû biafirîne','admin','dialog'),
('kurdish_kurmanci','admin.category_name','Navê kategoriyê','admin','form label'),
('kurdish_kurmanci','admin.enter_category_name','Navê kategoriyê binivîse','admin','placeholder'),
('kurdish_kurmanci','admin.enter_description','Danasînê binivîse','admin','placeholder'),
('kurdish_kurmanci','admin.slug','Slug','admin','form label'),
('kurdish_kurmanci','admin.enter_slug','Slug binivîse (mînak: agahiyên-bingehîn)','admin','placeholder'),
('kurdish_kurmanci','admin.slug_description','Di URL-yan de û wek nasnameyekê yekta tê bikaranîn','admin','form description'),
('kurdish_kurmanci','admin.enable_disable_category','Vê kategoriyê çalak an neçalak bike','admin','form description'),
('kurdish_kurmanci','admin.update_category','Kategoriyê nûve bike','admin','button'),
('kurdish_kurmanci','admin.edit_category','Kategoriyê biguherîne','admin','dialog title'),
('kurdish_kurmanci','admin.edit_category_desc','Di kategoriya hilbijartî de guhertinan bike','admin','dialog'),
('kurdish_kurmanci','admin.delete_category','Kategoriyê jê bibe','admin','dialog title'),
('kurdish_kurmanci','admin.delete_category_confirm','Tu bawer î ku dixwazî vê kategoriyê jê bibî? Ev çalakî nayê vegerandin.','admin','dialog'),
('kurdish_kurmanci','admin.all_items_deleted_warning','Hemû tiştên di vê kategoriyê de jî dê bên jêbirin.','admin','warning'),
('kurdish_kurmanci','admin.add_item_to_category','Tiştekî nû li kategoriya "{{name}}" zêde bike','admin','dialog'),
('kurdish_kurmanci','admin.add_new_item','Tiştekî nû zêde bike','admin','dialog'),
('kurdish_kurmanci','admin.item_name','Navê tiştî','admin','form label'),
('kurdish_kurmanci','admin.enter_item_name','Navê tiştî binivîse','admin','placeholder'),
('kurdish_kurmanci','admin.type','Cure','admin','table header'),
('kurdish_kurmanci','admin.select_type','Cure hilbijêre','admin','placeholder'),
('kurdish_kurmanci','admin.options','Vebijêrk','admin','form label'),
('kurdish_kurmanci','admin.enter_options_comma','Vebijêrkan binivîse, bi komayan veqetandî','admin','placeholder'),
('kurdish_kurmanci','admin.options_comma_desc','Vebijêrkan bi komayan veqetîne (mînak: Vebijêrk 1, Vebijêrk 2, Vebijêrk 3)','admin','form description'),
('kurdish_kurmanci','admin.enable_disable_item','Vê tiştî çalak an neçalak bike','admin','form description'),
('kurdish_kurmanci','admin.update_item','Tiştî nûve bike','admin','button'),
('kurdish_kurmanci','admin.edit_item','Tiştî biguherîne','admin','dialog title'),
('kurdish_kurmanci','admin.edit_item_desc','Di tiştê hilbijartî de guhertinan bike','admin','dialog'),
('kurdish_kurmanci','admin.delete_item','Tiştî jê bibe','admin','dialog title'),
('kurdish_kurmanci','admin.delete_item_confirm','Tu bawer î ku dixwazî vê tiştî jê bibî? Ev çalakî nayê vegerandin.','admin','dialog'),
('kurdish_kurmanci','admin.last_updated','Nûvekirina dawî','admin','table header'),
('kurdish_kurmanci','admin.question_text_placeholder','mînak: Hobiyên te çi ne?','admin','placeholder'),
('kurdish_kurmanci','admin.select_category','Kategoriyê hilbijêre','admin','placeholder'),
('kurdish_kurmanci','admin.select_field_type','Cureya qadê hilbijêre','admin','placeholder'),
('kurdish_kurmanci','admin.select_registration_step','Gava tomarkirinê hilbijêre','admin','placeholder'),
('kurdish_kurmanci','admin.placeholder_example','mînak: Hobiyên xwe binivîse','admin','placeholder'),
('kurdish_kurmanci','admin.profile_field_example','mînak: hobiyek','admin','placeholder'),

-- German
('german','admin.items_in_category','Elemente in {{name}}','admin','categories page'),
('german','admin.all_category_items','Alle Kategorieelemente','admin','categories page'),
('german','admin.manage_items_in_category','Elemente in der Kategorie "{{name}}" verwalten','admin','categories page'),
('german','admin.select_category_to_manage','Wähle eine Kategorie zum Verwalten','admin','categories page'),
('german','admin.view_all_categories','Alle Kategorien anzeigen','admin','categories page'),
('german','admin.search_items','Elemente suchen...','admin','placeholder'),
('german','admin.no_items_in_category','Keine Elemente in dieser Kategorie gefunden','admin','categories page'),
('german','admin.create_new_profile_category','Neue Profilkategorie erstellen','admin','dialog'),
('german','admin.category_name','Kategoriename','admin','form label'),
('german','admin.enter_category_name','Kategorienamen eingeben','admin','placeholder'),
('german','admin.enter_description','Beschreibung eingeben','admin','placeholder'),
('german','admin.slug','Slug','admin','form label'),
('german','admin.enter_slug','Slug eingeben (z.B. basis-info)','admin','placeholder'),
('german','admin.slug_description','Wird in URLs und als eindeutige Kennung verwendet','admin','form description'),
('german','admin.enable_disable_category','Diese Kategorie aktivieren oder deaktivieren','admin','form description'),
('german','admin.update_category','Kategorie aktualisieren','admin','button'),
('german','admin.edit_category','Kategorie bearbeiten','admin','dialog title'),
('german','admin.edit_category_desc','Änderungen an der ausgewählten Kategorie vornehmen','admin','dialog'),
('german','admin.delete_category','Kategorie löschen','admin','dialog title'),
('german','admin.delete_category_confirm','Bist du sicher, dass du diese Kategorie löschen möchtest? Diese Aktion kann nicht rückgängig gemacht werden.','admin','dialog'),
('german','admin.all_items_deleted_warning','Alle Elemente in dieser Kategorie werden ebenfalls gelöscht.','admin','warning'),
('german','admin.add_item_to_category','Neues Element zur Kategorie "{{name}}" hinzufügen','admin','dialog'),
('german','admin.add_new_item','Neues Element hinzufügen','admin','dialog'),
('german','admin.item_name','Elementname','admin','form label'),
('german','admin.enter_item_name','Elementnamen eingeben','admin','placeholder'),
('german','admin.type','Typ','admin','table header'),
('german','admin.select_type','Typ auswählen','admin','placeholder'),
('german','admin.options','Optionen','admin','form label'),
('german','admin.enter_options_comma','Optionen eingeben, durch Kommas getrennt','admin','placeholder'),
('german','admin.options_comma_desc','Optionen durch Kommas getrennt eingeben (z.B. Option 1, Option 2, Option 3)','admin','form description'),
('german','admin.enable_disable_item','Dieses Element aktivieren oder deaktivieren','admin','form description'),
('german','admin.update_item','Element aktualisieren','admin','button'),
('german','admin.edit_item','Element bearbeiten','admin','dialog title'),
('german','admin.edit_item_desc','Änderungen am ausgewählten Element vornehmen','admin','dialog'),
('german','admin.delete_item','Element löschen','admin','dialog title'),
('german','admin.delete_item_confirm','Bist du sicher, dass du dieses Element löschen möchtest? Diese Aktion kann nicht rückgängig gemacht werden.','admin','dialog'),
('german','admin.last_updated','Zuletzt aktualisiert','admin','table header'),
('german','admin.question_text_placeholder','z.B. Was sind deine Lieblingshobbys?','admin','placeholder'),
('german','admin.select_category','Kategorie auswählen','admin','placeholder'),
('german','admin.select_field_type','Feldtyp auswählen','admin','placeholder'),
('german','admin.select_registration_step','Registrierungsschritt auswählen','admin','placeholder'),
('german','admin.placeholder_example','z.B. Gib deine Hobbys ein','admin','placeholder'),
('german','admin.profile_field_example','z.B. Hobbys','admin','placeholder')

ON CONFLICT (language_code, translation_key) DO UPDATE SET translation_value = EXCLUDED.translation_value;
