
-- Batch: SuperAdmin pages (ExportsPage, RolesPage, EditorTabs, KurdistanEditor, FeaturesEditor)
INSERT INTO public.app_translations (language_code, translation_key, translation_value, category, auto_translated) VALUES
-- admin.export_name_placeholder
('english','admin.export_name_placeholder','e.g., Monthly User Activity Report','common',false),
('norwegian','admin.export_name_placeholder','f.eks. Månedlig brukeraktivitetsrapport','common',true),
('german','admin.export_name_placeholder','z.B. Monatlicher Benutzeraktivitätsbericht','common',true),
('kurdish_sorani','admin.export_name_placeholder','بۆ نموونە، ڕاپۆرتی چالاکی بەکارهێنەری مانگانە','common',true),
('kurdish_kurmanji','admin.export_name_placeholder','mînak, Rapora çalakiya bikarhêneran a mehane','common',true),
-- admin.select_data_type
('english','admin.select_data_type','Select data type','common',false),
('norwegian','admin.select_data_type','Velg datatype','common',true),
('german','admin.select_data_type','Datentyp auswählen','common',true),
('kurdish_sorani','admin.select_data_type','جۆری داتا هەڵبژێرە','common',true),
('kurdish_kurmanji','admin.select_data_type','Curê daneyê hilbijêre','common',true),
-- admin.user_activity
('english','admin.user_activity','User Activity','common',false),
('norwegian','admin.user_activity','Brukeraktivitet','common',true),
('german','admin.user_activity','Benutzeraktivität','common',true),
('kurdish_sorani','admin.user_activity','چالاکی بەکارهێنەر','common',true),
('kurdish_kurmanji','admin.user_activity','Çalakiya bikarhêner','common',true),
-- admin.user_profiles
('english','admin.user_profiles','User Profiles','common',false),
('norwegian','admin.user_profiles','Brukerprofiler','common',true),
('german','admin.user_profiles','Benutzerprofile','common',true),
('kurdish_sorani','admin.user_profiles','پرۆفایلەکانی بەکارهێنەر','common',true),
('kurdish_kurmanji','admin.user_profiles','Profîlên bikarhêneran','common',true),
-- admin.messages
('english','admin.messages','Messages','common',false),
('norwegian','admin.messages','Meldinger','common',true),
('german','admin.messages','Nachrichten','common',true),
('kurdish_sorani','admin.messages','نامەکان','common',true),
('kurdish_kurmanji','admin.messages','Peyam','common',true),
-- admin.financial_data
('english','admin.financial_data','Financial Data','common',false),
('norwegian','admin.financial_data','Finansielle data','common',true),
('german','admin.financial_data','Finanzdaten','common',true),
('kurdish_sorani','admin.financial_data','داتای داراییی','common',true),
('kurdish_kurmanji','admin.financial_data','Daneyên darayî','common',true),
-- admin.user_registrations
('english','admin.user_registrations','User Registrations','common',false),
('norwegian','admin.user_registrations','Brukerregistreringer','common',true),
('german','admin.user_registrations','Benutzerregistrierungen','common',true),
('kurdish_sorani','admin.user_registrations','تۆمارکردنی بەکارهێنەران','common',true),
('kurdish_kurmanji','admin.user_registrations','Tomarkirinên bikarhêneran','common',true),
-- admin.all_roles
('english','admin.all_roles','All Roles','common',false),
('norwegian','admin.all_roles','Alle roller','common',true),
('german','admin.all_roles','Alle Rollen','common',true),
('kurdish_sorani','admin.all_roles','هەموو ڕۆڵەکان','common',true),
('kurdish_kurmanji','admin.all_roles','Hemû rol','common',true),
-- admin.system_roles
('english','admin.system_roles','System Roles','common',false),
('norwegian','admin.system_roles','Systemroller','common',true),
('german','admin.system_roles','Systemrollen','common',true),
('kurdish_sorani','admin.system_roles','ڕۆڵەکانی سیستەم','common',true),
('kurdish_kurmanji','admin.system_roles','Rolên sîstemê','common',true),
-- admin.custom_roles
('english','admin.custom_roles','Custom Roles','common',false),
('norwegian','admin.custom_roles','Egendefinerte roller','common',true),
('german','admin.custom_roles','Benutzerdefinierte Rollen','common',true),
('kurdish_sorani','admin.custom_roles','ڕۆڵە تایبەتەکان','common',true),
('kurdish_kurmanji','admin.custom_roles','Rolên taybet','common',true),
-- admin.loading_roles
('english','admin.loading_roles','Loading roles...','common',false),
('norwegian','admin.loading_roles','Laster roller...','common',true),
('german','admin.loading_roles','Rollen werden geladen...','common',true),
('kurdish_sorani','admin.loading_roles','ڕۆڵەکان بار دەکرێن...','common',true),
('kurdish_kurmanji','admin.loading_roles','Rol tên barkirin...','common',true),
-- admin.system_roles_desc
('english','admin.system_roles_desc','Built-in roles with predefined permissions','common',false),
('norwegian','admin.system_roles_desc','Innebygde roller med forhåndsdefinerte tillatelser','common',true),
('german','admin.system_roles_desc','Eingebaute Rollen mit vordefinierten Berechtigungen','common',true),
('kurdish_sorani','admin.system_roles_desc','ڕۆڵە دروستکراوەکان بە مۆڵەتی پێشوەختدیاریکراو','common',true),
('kurdish_kurmanji','admin.system_roles_desc','Rolên çêkirî bi destûrên pêşwext diyarkirî','common',true),
-- admin.custom_roles_desc
('english','admin.custom_roles_desc','User-defined roles with custom permissions','common',false),
('norwegian','admin.custom_roles_desc','Brukerdefinerte roller med egendefinerte tillatelser','common',true),
('german','admin.custom_roles_desc','Benutzerdefinierte Rollen mit benutzerdefinierten Berechtigungen','common',true),
('kurdish_sorani','admin.custom_roles_desc','ڕۆڵە دیاریکراوەکانی بەکارهێنەر بە مۆڵەتی تایبەت','common',true),
('kurdish_kurmanji','admin.custom_roles_desc','Rolên ji hêla bikarhêner ve diyarkirî bi destûrên taybet','common',true),
-- admin.no_custom_roles
('english','admin.no_custom_roles','No custom roles created yet.','common',false),
('norwegian','admin.no_custom_roles','Ingen egendefinerte roller opprettet ennå.','common',true),
('german','admin.no_custom_roles','Noch keine benutzerdefinierten Rollen erstellt.','common',true),
('kurdish_sorani','admin.no_custom_roles','هێشتا هیچ ڕۆڵێکی تایبەت دروست نەکراوە.','common',true),
('kurdish_kurmanji','admin.no_custom_roles','Hîn tu rolên taybet nehatine afirandin.','common',true),
-- admin.hero_section
('english','admin.hero_section','Hero Section','common',false),
('norwegian','admin.hero_section','Hovedseksjon','common',true),
('german','admin.hero_section','Hero-Bereich','common',true),
('kurdish_sorani','admin.hero_section','بەشی سەرەکی','common',true),
('kurdish_kurmanji','admin.hero_section','Beşa sereke','common',true),
-- admin.features
('english','admin.features','Features','common',false),
('norwegian','admin.features','Funksjoner','common',true),
('german','admin.features','Funktionen','common',true),
('kurdish_sorani','admin.features','تایبەتمەندییەکان','common',true),
('kurdish_kurmanji','admin.features','Taybetmendî','common',true),
-- admin.kurdish_heritage
('english','admin.kurdish_heritage','Kurdish Heritage','common',false),
('norwegian','admin.kurdish_heritage','Kurdisk kulturarv','common',true),
('german','admin.kurdish_heritage','Kurdisches Erbe','common',true),
('kurdish_sorani','admin.kurdish_heritage','کەلتووری کوردی','common',true),
('kurdish_kurmanji','admin.kurdish_heritage','Mîrata Kurdî','common',true),
-- admin.footer
('english','admin.footer','Footer','common',false),
('norwegian','admin.footer','Bunntekst','common',true),
('german','admin.footer','Fußzeile','common',true),
('kurdish_sorani','admin.footer','خوارەوە','common',true),
('kurdish_kurmanji','admin.footer','Binê rûpelê','common',true),
-- admin.kurdish_heritage_section
('english','admin.kurdish_heritage_section','Kurdish Heritage Section','common',false),
('norwegian','admin.kurdish_heritage_section','Kurdisk kulturarv-seksjon','common',true),
('german','admin.kurdish_heritage_section','Kurdisches Erbe-Bereich','common',true),
('kurdish_sorani','admin.kurdish_heritage_section','بەشی کەلتووری کوردی','common',true),
('kurdish_kurmanji','admin.kurdish_heritage_section','Beşa Mîrata Kurdî','common',true),
-- admin.kurdish_heritage_desc
('english','admin.kurdish_heritage_desc','Edit the content in the Kurdish heritage section','common',false),
('norwegian','admin.kurdish_heritage_desc','Rediger innholdet i den kurdiske kulturarv-seksjonen','common',true),
('german','admin.kurdish_heritage_desc','Bearbeiten Sie den Inhalt im Bereich des kurdischen Erbes','common',true),
('kurdish_sorani','admin.kurdish_heritage_desc','ناوەڕۆکی بەشی کەلتووری کوردی دەستکاری بکە','common',true),
('kurdish_kurmanji','admin.kurdish_heritage_desc','Naveroka beşa mîrata Kurdî biguherîne','common',true),
-- admin.section_title
('english','admin.section_title','Section Title','common',false),
('norwegian','admin.section_title','Seksjontittel','common',true),
('german','admin.section_title','Abschnittstitel','common',true),
('kurdish_sorani','admin.section_title','ناونیشانی بەش','common',true),
('kurdish_kurmanji','admin.section_title','Sernavê beşê','common',true),
-- admin.section_subtitle
('english','admin.section_subtitle','Section Subtitle','common',false),
('norwegian','admin.section_subtitle','Seksjonsundertittel','common',true),
('german','admin.section_subtitle','Abschnittsuntertitel','common',true),
('kurdish_sorani','admin.section_subtitle','ژێرناونیشانی بەش','common',true),
('kurdish_kurmanji','admin.section_subtitle','Binnivîsa beşê','common',true),
-- admin.left_box
('english','admin.left_box','Left Box','common',false),
('norwegian','admin.left_box','Venstre boks','common',true),
('german','admin.left_box','Linke Box','common',true),
('kurdish_sorani','admin.left_box','سنووقی چەپ','common',true),
('kurdish_kurmanji','admin.left_box','Qutiya çepê','common',true),
-- admin.right_box
('english','admin.right_box','Right Box','common',false),
('norwegian','admin.right_box','Høyre boks','common',true),
('german','admin.right_box','Rechte Box','common',true),
('kurdish_sorani','admin.right_box','سنووقی ڕاست','common',true),
('kurdish_kurmanji','admin.right_box','Qutiya rastê','common',true),
-- admin.bullet_points
('english','admin.bullet_points','Bullet Points','common',false),
('norwegian','admin.bullet_points','Kulepunkter','common',true),
('german','admin.bullet_points','Aufzählungspunkte','common',true),
('kurdish_sorani','admin.bullet_points','خاڵەکان','common',true),
('kurdish_kurmanji','admin.bullet_points','Xalên lîsteyê','common',true),
-- admin.title
('english','admin.title','Title','common',false),
('norwegian','admin.title','Tittel','common',true),
('german','admin.title','Titel','common',true),
('kurdish_sorani','admin.title','ناونیشان','common',true),
('kurdish_kurmanji','admin.title','Sernav','common',true),
-- admin.features_section
('english','admin.features_section','Features Section','common',false),
('norwegian','admin.features_section','Funksjonsseksjon','common',true),
('german','admin.features_section','Funktionsbereich','common',true),
('kurdish_sorani','admin.features_section','بەشی تایبەتمەندییەکان','common',true),
('kurdish_kurmanji','admin.features_section','Beşa taybetmendiyan','common',true),
-- admin.features_section_desc
('english','admin.features_section_desc','Edit the features section title and feature cards','common',false),
('norwegian','admin.features_section_desc','Rediger tittelen og funksjonskortene','common',true),
('german','admin.features_section_desc','Bearbeiten Sie den Titel und die Funktionskarten','common',true),
('kurdish_sorani','admin.features_section_desc','ناونیشان و کارتەکانی تایبەتمەندییەکان دەستکاری بکە','common',true),
('kurdish_kurmanji','admin.features_section_desc','Sernav û kartên taybetmendiyan biguherîne','common',true),
-- admin.feature_cards
('english','admin.feature_cards','Feature Cards','common',false),
('norwegian','admin.feature_cards','Funksjonskort','common',true),
('german','admin.feature_cards','Funktionskarten','common',true),
('kurdish_sorani','admin.feature_cards','کارتەکانی تایبەتمەندی','common',true),
('kurdish_kurmanji','admin.feature_cards','Kartên taybetmendiyê','common',true),
-- admin.feature_card
('english','admin.feature_card','Feature Card','common',false),
('norwegian','admin.feature_card','Funksjonskort','common',true),
('german','admin.feature_card','Funktionskarte','common',true),
('kurdish_sorani','admin.feature_card','کارتی تایبەتمەندی','common',true),
('kurdish_kurmanji','admin.feature_card','Karta taybetmendiyê','common',true),
-- admin.icon
('english','admin.icon','Icon','common',false),
('norwegian','admin.icon','Ikon','common',true),
('german','admin.icon','Symbol','common',true),
('kurdish_sorani','admin.icon','ئایکۆن','common',true),
('kurdish_kurmanji','admin.icon','Îkon','common',true),
-- admin.icon_name_hint
('english','admin.icon_name_hint','Icon name (Globe, Users, Heart, etc.)','common',false),
('norwegian','admin.icon_name_hint','Ikonnavn (Globe, Users, Heart, osv.)','common',true),
('german','admin.icon_name_hint','Symbolname (Globe, Users, Heart, usw.)','common',true),
('kurdish_sorani','admin.icon_name_hint','ناوی ئایکۆن (Globe, Users, Heart, هتد.)','common',true),
('kurdish_kurmanji','admin.icon_name_hint','Navê îkonê (Globe, Users, Heart, hwd.)','common',true),
-- common.loading
('english','common.loading','Loading...','common',false),
('norwegian','common.loading','Laster...','common',true),
('german','common.loading','Laden...','common',true),
('kurdish_sorani','common.loading','بار دەکرێت...','common',true),
('kurdish_kurmanji','common.loading','Tê barkirin...','common',true)
ON CONFLICT (language_code, translation_key) DO NOTHING;
