
INSERT INTO public.app_translations (language_code, translation_key, translation_value, category, context) VALUES
-- UserMenu
('english','toast.logged_out','Logged out','common','UserMenu'),
('english','toast.logged_out_desc','You have been successfully logged out','common','UserMenu'),
('english','toast.logout_failed','Failed to log out. Please try again.','common','UserMenu'),
('english','toast.report.provide_desc','Please provide a description for your report','common','UserMenu'),
('english','toast.report.submitted','Report Submitted','common','UserMenu'),
('english','toast.report.submitted_desc','Thank you for your feedback. We will review your report.','common','UserMenu'),
('english','nav.report_issue','Report an Issue','navigation','UserMenu'),
('english','nav.help_support','Help & Support','navigation','UserMenu'),
('english','nav.log_out','Log out','navigation','UserMenu'),
('english','toast.report.dialog_desc','Please describe the issue you''re experiencing or the content you want to report.','common','UserMenu'),
('english','toast.report.placeholder','Describe the issue in detail...','common','UserMenu'),
('english','toast.report.submit','Submit Report','common','UserMenu'),

('norwegian','toast.logged_out','Logget ut','common','UserMenu'),
('norwegian','toast.logged_out_desc','Du har blitt logget ut','common','UserMenu'),
('norwegian','toast.logout_failed','Kunne ikke logge ut. Prøv igjen.','common','UserMenu'),
('norwegian','toast.report.provide_desc','Vennligst beskriv problemet du vil rapportere','common','UserMenu'),
('norwegian','toast.report.submitted','Rapport sendt','common','UserMenu'),
('norwegian','toast.report.submitted_desc','Takk for tilbakemeldingen. Vi vil gjennomgå rapporten din.','common','UserMenu'),
('norwegian','nav.report_issue','Rapporter et problem','navigation','UserMenu'),
('norwegian','nav.help_support','Hjelp og støtte','navigation','UserMenu'),
('norwegian','nav.log_out','Logg ut','navigation','UserMenu'),
('norwegian','toast.report.dialog_desc','Beskriv problemet du opplever eller innholdet du vil rapportere.','common','UserMenu'),
('norwegian','toast.report.placeholder','Beskriv problemet i detalj...','common','UserMenu'),
('norwegian','toast.report.submit','Send rapport','common','UserMenu'),

('kurdish_sorani','toast.logged_out','دەرچوون','common','UserMenu'),
('kurdish_sorani','toast.logged_out_desc','بە سەرکەوتوویی دەرچویت','common','UserMenu'),
('kurdish_sorani','toast.logout_failed','دەرچوون سەرکەوتوو نەبوو. دووبارە هەوڵ بدەرەوە.','common','UserMenu'),
('kurdish_sorani','toast.report.provide_desc','تکایە وەسفی ئەو کێشەیە بنووسە کە دەتەوێت ڕاپۆرتی بکەیت','common','UserMenu'),
('kurdish_sorani','toast.report.submitted','ڕاپۆرت نێردرا','common','UserMenu'),
('kurdish_sorani','toast.report.submitted_desc','سوپاس بۆ بەرداشتت. ئێمە ڕاپۆرتەکەت پێداچوونەوەی دەکەین.','common','UserMenu'),
('kurdish_sorani','nav.report_issue','ڕاپۆرتکردنی کێشە','navigation','UserMenu'),
('kurdish_sorani','nav.help_support','یارمەتی و پشتیوانی','navigation','UserMenu'),
('kurdish_sorani','nav.log_out','دەرچوون','navigation','UserMenu'),
('kurdish_sorani','toast.report.dialog_desc','تکایە ئەو کێشەیەی کە بەرەوڕووی دەبیتەوە یان ئەو ناوەڕۆکەی کە دەتەوێت ڕاپۆرتی بکەیت وەسف بکە.','common','UserMenu'),
('kurdish_sorani','toast.report.placeholder','کێشەکە بە وردی وەسف بکە...','common','UserMenu'),
('kurdish_sorani','toast.report.submit','ناردنی ڕاپۆرت','common','UserMenu'),

('kurdish_kurmanji','toast.logged_out','Derket','common','UserMenu'),
('kurdish_kurmanji','toast.logged_out_desc','Tu bi serkeftî derketî','common','UserMenu'),
('kurdish_kurmanji','toast.logout_failed','Derketin bi ser neket. Ji kerema xwe dîsa biceribîne.','common','UserMenu'),
('kurdish_kurmanji','toast.report.provide_desc','Ji kerema xwe pirsgirêka ku tu dixwazî rapor bikî diyar bike','common','UserMenu'),
('kurdish_kurmanji','toast.report.submitted','Rapor hat şandin','common','UserMenu'),
('kurdish_kurmanji','toast.report.submitted_desc','Spas ji bo nerîna te. Em ê rapora te binirxînin.','common','UserMenu'),
('kurdish_kurmanji','nav.report_issue','Pirsgirêkek rapor bike','navigation','UserMenu'),
('kurdish_kurmanji','nav.help_support','Alîkarî û piştgirî','navigation','UserMenu'),
('kurdish_kurmanji','nav.log_out','Derkeve','navigation','UserMenu'),
('kurdish_kurmanji','toast.report.dialog_desc','Ji kerema xwe pirsgirêka ku tu pê re rû bi rû dimînî an naveroka ku tu dixwazî rapor bikî diyar bike.','common','UserMenu'),
('kurdish_kurmanji','toast.report.placeholder','Pirsgirêkê bi hûrgulî diyar bike...','common','UserMenu'),
('kurdish_kurmanji','toast.report.submit','Raporê bişîne','common','UserMenu'),

('german','toast.logged_out','Abgemeldet','common','UserMenu'),
('german','toast.logged_out_desc','Sie wurden erfolgreich abgemeldet','common','UserMenu'),
('german','toast.logout_failed','Abmeldung fehlgeschlagen. Bitte versuchen Sie es erneut.','common','UserMenu'),
('german','toast.report.provide_desc','Bitte beschreiben Sie das Problem, das Sie melden möchten','common','UserMenu'),
('german','toast.report.submitted','Bericht eingereicht','common','UserMenu'),
('german','toast.report.submitted_desc','Vielen Dank für Ihr Feedback. Wir werden Ihren Bericht überprüfen.','common','UserMenu'),
('german','nav.report_issue','Problem melden','navigation','UserMenu'),
('german','nav.help_support','Hilfe & Support','navigation','UserMenu'),
('german','nav.log_out','Abmelden','navigation','UserMenu'),
('german','toast.report.dialog_desc','Bitte beschreiben Sie das Problem oder den Inhalt, den Sie melden möchten.','common','UserMenu'),
('german','toast.report.placeholder','Beschreiben Sie das Problem im Detail...','common','UserMenu'),
('german','toast.report.submit','Bericht senden','common','UserMenu'),

-- Passport Location
('english','toast.passport.removed','Passport location removed','settings','PassportLocation'),
('english','toast.passport.removed_desc','Your passport location has been reset.','settings','PassportLocation'),
('english','location.no_passport','No passport location set','settings','PassportLocation'),
('english','location.passport_desc','Virtual location for exploring matches in other cities worldwide.','settings','PassportLocation'),
('english','toast.location.updated','Location updated','settings','PassportLocation'),
('english','toast.location.passport_set','Your passport location is now set to {{location}}','settings','PassportLocation'),
('english','location.travel_mode','Travel Mode','settings','PassportLocation'),
('english','location.travel_mode_desc','Set your location anywhere in the world to match with people from different cities or countries.','settings','PassportLocation'),
('english','location.explore','Explore Location','settings','PassportLocation'),
('english','location.search_placeholder','Search any city in the world...','settings','PassportLocation'),
('english','location.no_results','No locations found','settings','PassportLocation'),

('norwegian','toast.passport.removed','Passplassering fjernet','settings','PassportLocation'),
('norwegian','toast.passport.removed_desc','Passplasseringen din er tilbakestilt.','settings','PassportLocation'),
('norwegian','location.no_passport','Ingen passplassering angitt','settings','PassportLocation'),
('norwegian','location.passport_desc','Virtuell plassering for å utforske matcher i andre byer over hele verden.','settings','PassportLocation'),
('norwegian','toast.location.updated','Plassering oppdatert','settings','PassportLocation'),
('norwegian','toast.location.passport_set','Passplasseringen din er nå satt til {{location}}','settings','PassportLocation'),
('norwegian','location.travel_mode','Reisemodus','settings','PassportLocation'),
('norwegian','location.travel_mode_desc','Sett plasseringen din hvor som helst i verden for å matche med folk fra forskjellige byer eller land.','settings','PassportLocation'),
('norwegian','location.explore','Utforsk plassering','settings','PassportLocation'),
('norwegian','location.search_placeholder','Søk i hvilken som helst by i verden...','settings','PassportLocation'),
('norwegian','location.no_results','Ingen plasseringer funnet','settings','PassportLocation'),

('kurdish_sorani','toast.passport.removed','شوێنی پاسپۆرت لابرا','settings','PassportLocation'),
('kurdish_sorani','toast.passport.removed_desc','شوێنی پاسپۆرتت ڕیسێت کرایەوە.','settings','PassportLocation'),
('kurdish_sorani','location.no_passport','هیچ شوێنی پاسپۆرت دانەنراوە','settings','PassportLocation'),
('kurdish_sorani','location.passport_desc','شوێنی مەجازی بۆ گەڕان بە هاوتاکانت لە شارەکانی تری جیهان.','settings','PassportLocation'),
('kurdish_sorani','toast.location.updated','شوێن نوێ کرایەوە','settings','PassportLocation'),
('kurdish_sorani','toast.location.passport_set','شوێنی پاسپۆرتت ئێستا دانراوە بۆ {{location}}','settings','PassportLocation'),
('kurdish_sorani','location.travel_mode','دۆخی گەشت','settings','PassportLocation'),
('kurdish_sorani','location.travel_mode_desc','شوێنەکەت لە هەر شوێنێکی جیهان دابنێ بۆ هاوتاکردن لەگەڵ خەڵکی شار و وڵاتانی جیاواز.','settings','PassportLocation'),
('kurdish_sorani','location.explore','گەڕانی شوێن','settings','PassportLocation'),
('kurdish_sorani','location.search_placeholder','گەڕان بۆ هەر شارێکی جیهان...','settings','PassportLocation'),
('kurdish_sorani','location.no_results','هیچ شوێنێک نەدۆزرایەوە','settings','PassportLocation'),

('kurdish_kurmanji','toast.passport.removed','Cihê pasaportê hat rakirin','settings','PassportLocation'),
('kurdish_kurmanji','toast.passport.removed_desc','Cihê pasaporta te hat vegerandin.','settings','PassportLocation'),
('kurdish_kurmanji','location.no_passport','Cihê pasaportê nehatiye danîn','settings','PassportLocation'),
('kurdish_kurmanji','location.passport_desc','Cihê virtual ji bo keşfkirina lihevhatinan li bajarên din ên cîhanê.','settings','PassportLocation'),
('kurdish_kurmanji','toast.location.updated','Cih hat nûkirin','settings','PassportLocation'),
('kurdish_kurmanji','toast.location.passport_set','Cihê pasaporta te niha li {{location}} ye','settings','PassportLocation'),
('kurdish_kurmanji','location.travel_mode','Moda rêwîtiyê','settings','PassportLocation'),
('kurdish_kurmanji','location.travel_mode_desc','Cihê xwe li her derê cîhanê danê da ku bi mirovên ji bajar û welatên cûda re lihev bên.','settings','PassportLocation'),
('kurdish_kurmanji','location.explore','Cihan keşf bike','settings','PassportLocation'),
('kurdish_kurmanji','location.search_placeholder','Li her bajarê cîhanê bigere...','settings','PassportLocation'),
('kurdish_kurmanji','location.no_results','Cih nehat dîtin','settings','PassportLocation'),

('german','toast.passport.removed','Passstandort entfernt','settings','PassportLocation'),
('german','toast.passport.removed_desc','Ihr Passstandort wurde zurückgesetzt.','settings','PassportLocation'),
('german','location.no_passport','Kein Passstandort festgelegt','settings','PassportLocation'),
('german','location.passport_desc','Virtueller Standort zum Erkunden von Matches in anderen Städten weltweit.','settings','PassportLocation'),
('german','toast.location.updated','Standort aktualisiert','settings','PassportLocation'),
('german','toast.location.passport_set','Ihr Passstandort ist jetzt auf {{location}} gesetzt','settings','PassportLocation'),
('german','location.travel_mode','Reisemodus','settings','PassportLocation'),
('german','location.travel_mode_desc','Setzen Sie Ihren Standort überall auf der Welt, um mit Menschen aus verschiedenen Städten oder Ländern zu matchen.','settings','PassportLocation'),
('german','location.explore','Standort erkunden','settings','PassportLocation'),
('german','location.search_placeholder','Suche eine Stadt weltweit...','settings','PassportLocation'),
('german','location.no_results','Keine Standorte gefunden','settings','PassportLocation'),

-- OAuth Callback
('english','auth.welcome_back','Welcome back!','auth','useOAuthCallback'),
('english','auth.redirect_admin','Redirecting to super admin dashboard...','auth','useOAuthCallback'),
('english','auth.redirect_discovery','Redirecting to discovery...','auth','useOAuthCallback'),
('english','auth.welcome','Welcome!','auth','useOAuthCallback'),
('english','auth.complete_profile','Let''s complete your profile to get started...','auth','useOAuthCallback'),
('english','auth.auth_failed','Authentication failed','auth','useOAuthCallback'),
('english','auth.try_again','Please try logging in again.','auth','useOAuthCallback'),

('norwegian','auth.welcome_back','Velkommen tilbake!','auth','useOAuthCallback'),
('norwegian','auth.redirect_admin','Omdirigerer til superadmin-dashbordet...','auth','useOAuthCallback'),
('norwegian','auth.redirect_discovery','Omdirigerer til oppdagelse...','auth','useOAuthCallback'),
('norwegian','auth.welcome','Velkommen!','auth','useOAuthCallback'),
('norwegian','auth.complete_profile','La oss fullføre profilen din for å komme i gang...','auth','useOAuthCallback'),
('norwegian','auth.auth_failed','Autentisering mislyktes','auth','useOAuthCallback'),
('norwegian','auth.try_again','Vennligst prøv å logge inn igjen.','auth','useOAuthCallback'),

('kurdish_sorani','auth.welcome_back','بەخێربێیتەوە!','auth','useOAuthCallback'),
('kurdish_sorani','auth.redirect_admin','ڕەوانەکردن بۆ داشبۆردی سوپەرئەدمین...','auth','useOAuthCallback'),
('kurdish_sorani','auth.redirect_discovery','ڕەوانەکردن بۆ دۆزینەوە...','auth','useOAuthCallback'),
('kurdish_sorani','auth.welcome','بەخێربێیت!','auth','useOAuthCallback'),
('kurdish_sorani','auth.complete_profile','با پرۆفایلەکەت تەواو بکەین بۆ دەستپێکردن...','auth','useOAuthCallback'),
('kurdish_sorani','auth.auth_failed','ناسینەوە سەرکەوتوو نەبوو','auth','useOAuthCallback'),
('kurdish_sorani','auth.try_again','تکایە دووبارە هەوڵی چوونەژوورەوە بدەرەوە.','auth','useOAuthCallback'),

('kurdish_kurmanji','auth.welcome_back','Bi xêr hatî!','auth','useOAuthCallback'),
('kurdish_kurmanji','auth.redirect_admin','Beralîkirin bo panela rêveberiyê...','auth','useOAuthCallback'),
('kurdish_kurmanji','auth.redirect_discovery','Beralîkirin bo keşfkirinê...','auth','useOAuthCallback'),
('kurdish_kurmanji','auth.welcome','Bi xêr hatî!','auth','useOAuthCallback'),
('kurdish_kurmanji','auth.complete_profile','Ka em profîla te temam bikin...','auth','useOAuthCallback'),
('kurdish_kurmanji','auth.auth_failed','Nasîn bi ser neket','auth','useOAuthCallback'),
('kurdish_kurmanji','auth.try_again','Ji kerema xwe dîsa biceribîne.','auth','useOAuthCallback'),

('german','auth.welcome_back','Willkommen zurück!','auth','useOAuthCallback'),
('german','auth.redirect_admin','Weiterleitung zum Super-Admin-Dashboard...','auth','useOAuthCallback'),
('german','auth.redirect_discovery','Weiterleitung zur Entdeckung...','auth','useOAuthCallback'),
('german','auth.welcome','Willkommen!','auth','useOAuthCallback'),
('german','auth.complete_profile','Vervollständigen wir Ihr Profil, um loszulegen...','auth','useOAuthCallback'),
('german','auth.auth_failed','Authentifizierung fehlgeschlagen','auth','useOAuthCallback'),
('german','auth.try_again','Bitte versuchen Sie sich erneut anzumelden.','auth','useOAuthCallback')
ON CONFLICT DO NOTHING;
