
INSERT INTO public.app_translations (language_code, translation_key, translation_value, category) VALUES
-- ProposeDateModal
('english','date.invite_on_date','Invite {{name}} on a Date','dates'),
('norwegian','date.invite_on_date','Inviter {{name}} på en date','dates'),
('kurdish_sorani','date.invite_on_date','بانگهێشتکردنی {{name}} بۆ میعادێک','dates'),
('kurdish_kurmanci','date.invite_on_date','{{name}} vexwîne bo hevdîtinekê','dates'),
('german','date.invite_on_date','{{name}} zu einem Date einladen','dates'),
('english','date.what_to_do','What would you like to do?','dates'),
('norwegian','date.what_to_do','Hva vil du gjøre?','dates'),
('kurdish_sorani','date.what_to_do','چی دەتەوێت بکەیت؟','dates'),
('kurdish_kurmanci','date.what_to_do','Tu dixwazî çi bikî?','dates'),
('german','date.what_to_do','Was möchten Sie unternehmen?','dates'),
('english','date.custom_activity','Or type a custom activity...','dates'),
('norwegian','date.custom_activity','Eller skriv en egendefinert aktivitet...','dates'),
('kurdish_sorani','date.custom_activity','یان چالاکییەکی تایبەت بنووسە...','dates'),
('kurdish_kurmanci','date.custom_activity','An çalakiyek taybet binivîse...','dates'),
('german','date.custom_activity','Oder geben Sie eine eigene Aktivität ein...','dates'),
('english','date.location_optional','Location (optional)','dates'),
('norwegian','date.location_optional','Sted (valgfritt)','dates'),
('kurdish_sorani','date.location_optional','شوێن (ئارەزوومەندانە)','dates'),
('kurdish_kurmanci','date.location_optional','Cih (bijartî)','dates'),
('german','date.location_optional','Ort (optional)','dates'),
('english','date.where_meet','Where should you meet?','dates'),
('norwegian','date.where_meet','Hvor skal dere møtes?','dates'),
('kurdish_sorani','date.where_meet','لەکوێ یەکتری ببینن؟','dates'),
('kurdish_kurmanci','date.where_meet','Li ku derê hûn hevûdu bibînin?','dates'),
('german','date.where_meet','Wo sollen Sie sich treffen?','dates'),
('english','date.message_optional','Message (optional)','dates'),
('norwegian','date.message_optional','Melding (valgfritt)','dates'),
('kurdish_sorani','date.message_optional','نامە (ئارەزوومەندانە)','dates'),
('kurdish_kurmanci','date.message_optional','Peyam (bijartî)','dates'),
('german','date.message_optional','Nachricht (optional)','dates'),
('english','date.add_personal_note','Add a personal note...','dates'),
('norwegian','date.add_personal_note','Legg til en personlig melding...','dates'),
('kurdish_sorani','date.add_personal_note','تێبینییەکی کەسی زیاد بکە...','dates'),
('kurdish_kurmanci','date.add_personal_note','Nîşeyek kesane zêde bike...','dates'),
('german','date.add_personal_note','Fügen Sie eine persönliche Notiz hinzu...','dates'),
('english','date.send_invitation','Send Date Invitation','dates'),
('norwegian','date.send_invitation','Send datoinvitasjon','dates'),
('kurdish_sorani','date.send_invitation','ناردنی بانگهێشتی میعاد','dates'),
('kurdish_kurmanci','date.send_invitation','Şandina vexwendina hevdîtinê','dates'),
('german','date.send_invitation','Einladung senden','dates'),
('english','toast.date.select_required','Please select an activity, date, and time','dates'),
('norwegian','toast.date.select_required','Velg en aktivitet, dato og klokkeslett','dates'),
('kurdish_sorani','toast.date.select_required','تکایە چالاکییەک، بەروار و کات هەڵبژێرە','dates'),
('kurdish_kurmanci','toast.date.select_required','Ji kerema xwe çalakiyek, dîrok û dem hilbijêre','dates'),
('german','toast.date.select_required','Bitte wählen Sie eine Aktivität, ein Datum und eine Uhrzeit','dates'),
('english','toast.date.sent','Date invitation sent to {{name}}!','dates'),
('norwegian','toast.date.sent','Datoinvitasjon sendt til {{name}}!','dates'),
('kurdish_sorani','toast.date.sent','بانگهێشتی میعاد نێردرا بۆ {{name}}!','dates'),
('kurdish_kurmanci','toast.date.sent','Vexwendina hevdîtinê hat şandin bo {{name}}!','dates'),
('german','toast.date.sent','Einladung an {{name}} gesendet!','dates'),
('english','toast.date.failed','Failed to send date proposal','dates'),
('norwegian','toast.date.failed','Kunne ikke sende datoinvitasjon','dates'),
('kurdish_sorani','toast.date.failed','ناردنی پێشنیاری میعاد سەرکەوتوو نەبوو','dates'),
('kurdish_kurmanci','toast.date.failed','Şandina pêşniyara hevdîtinê bi ser neket','dates'),
('german','toast.date.failed','Einladung konnte nicht gesendet werden','dates'),
-- DiscoveryNearby
('english','nearby.title','Nearby','discovery'),
('norwegian','nearby.title','I nærheten','discovery'),
('kurdish_sorani','nearby.title','نزیک','discovery'),
('kurdish_kurmanci','nearby.title','Nêzîk','discovery'),
('german','nearby.title','In der Nähe','discovery'),
('english','nearby.matches_within','{{count}} matches within {{radius}} km','discovery'),
('norwegian','nearby.matches_within','{{count}} treff innen {{radius}} km','discovery'),
('kurdish_sorani','nearby.matches_within','{{count}} هاوتا لە نێو {{radius}} کم','discovery'),
('kurdish_kurmanci','nearby.matches_within','{{count}} hevta di nav {{radius}} km de','discovery'),
('german','nearby.matches_within','{{count}} Treffer innerhalb von {{radius}} km','discovery'),
('english','nearby.distance_filter','Distance Filter','discovery'),
('norwegian','nearby.distance_filter','Avstandsfilter','discovery'),
('kurdish_sorani','nearby.distance_filter','فلتەری دووری','discovery'),
('kurdish_kurmanci','nearby.distance_filter','Fîltera dûrahiyê','discovery'),
('german','nearby.distance_filter','Entfernungsfilter','discovery'),
('english','nearby.adjust_radius','Adjust the search radius to find matches','discovery'),
('norwegian','nearby.adjust_radius','Juster søkeradiusen for å finne treff','discovery'),
('kurdish_sorani','nearby.adjust_radius','بازنەی گەڕان ڕێکبخە بۆ دۆزینەوەی هاوتاکان','discovery'),
('kurdish_kurmanci','nearby.adjust_radius','Bazneya lêgerînê rast bike bo dîtina hevtayan','discovery'),
('german','nearby.adjust_radius','Suchradius anpassen, um Treffer zu finden','discovery'),
('english','nearby.search_radius','Search Radius','discovery'),
('norwegian','nearby.search_radius','Søkeradius','discovery'),
('kurdish_sorani','nearby.search_radius','بازنەی گەڕان','discovery'),
('kurdish_kurmanci','nearby.search_radius','Bazneya lêgerînê','discovery'),
('german','nearby.search_radius','Suchradius','discovery'),
('english','nearby.detecting_location','Detecting your location...','discovery'),
('norwegian','nearby.detecting_location','Oppdager posisjonen din...','discovery'),
('kurdish_sorani','nearby.detecting_location','دۆزینەوەی شوێنت...','discovery'),
('kurdish_kurmanci','nearby.detecting_location','Dîtina cihê te...','discovery'),
('german','nearby.detecting_location','Standort wird ermittelt...','discovery'),
('english','nearby.finding_matches','Finding nearby matches...','discovery'),
('norwegian','nearby.finding_matches','Finner treff i nærheten...','discovery'),
('kurdish_sorani','nearby.finding_matches','دۆزینەوەی هاوتاکانی نزیک...','discovery'),
('kurdish_kurmanci','nearby.finding_matches','Dîtina hevtayên nêzîk...','discovery'),
('german','nearby.finding_matches','Nahegelegene Treffer werden gesucht...','discovery'),
('english','nearby.location_required','Location Required','discovery'),
('norwegian','nearby.location_required','Posisjon påkrevd','discovery'),
('kurdish_sorani','nearby.location_required','شوێن پێویستە','discovery'),
('kurdish_kurmanci','nearby.location_required','Cih pêwîst e','discovery'),
('german','nearby.location_required','Standort erforderlich','discovery'),
('english','nearby.need_location','We need your location to show nearby matches','discovery'),
('norwegian','nearby.need_location','Vi trenger posisjonen din for å vise treff i nærheten','discovery'),
('kurdish_sorani','nearby.need_location','پێویستمان بە شوێنت هەیە بۆ پیشاندانی هاوتاکانی نزیک','discovery'),
('kurdish_kurmanci','nearby.need_location','Pêwîstiya me bi cihê te heye bo nîşandana hevtayên nêzîk','discovery'),
('german','nearby.need_location','Wir benötigen Ihren Standort, um nahegelegene Treffer anzuzeigen','discovery'),
('english','nearby.enable_location','Enable Location','discovery'),
('norwegian','nearby.enable_location','Aktiver posisjon','discovery'),
('kurdish_sorani','nearby.enable_location','شوێن چالاک بکە','discovery'),
('kurdish_kurmanci','nearby.enable_location','Cih çalak bike','discovery'),
('german','nearby.enable_location','Standort aktivieren','discovery'),
('english','nearby.no_matches','No matches nearby','discovery'),
('norwegian','nearby.no_matches','Ingen treff i nærheten','discovery'),
('kurdish_sorani','nearby.no_matches','هیچ هاوتایەک لە نزیک نییە','discovery'),
('kurdish_kurmanci','nearby.no_matches','Tu hevta li nêzîk tune','discovery'),
('german','nearby.no_matches','Keine Treffer in der Nähe','discovery'),
('english','nearby.try_increase_radius','Try increasing your search radius','discovery'),
('norwegian','nearby.try_increase_radius','Prøv å øke søkeradiusen din','discovery'),
('kurdish_sorani','nearby.try_increase_radius','هەوڵبدە بازنەی گەڕان زیاد بکەیت','discovery'),
('kurdish_kurmanci','nearby.try_increase_radius','Hewl bide bazneya lêgerînê zêde bikî','discovery'),
('german','nearby.try_increase_radius','Versuchen Sie, Ihren Suchradius zu vergrößern','discovery'),
('english','toast.nearby.searching','Searching for matches within {{radius}} km','discovery'),
('norwegian','toast.nearby.searching','Søker etter treff innen {{radius}} km','discovery'),
('kurdish_sorani','toast.nearby.searching','گەڕان بۆ هاوتاکان لە نێو {{radius}} کم','discovery'),
('kurdish_kurmanci','toast.nearby.searching','Lêgerîn bo hevtayan di nav {{radius}} km de','discovery'),
('german','toast.nearby.searching','Suche nach Treffern innerhalb von {{radius}} km','discovery'),
('english','toast.nearby.enable_location','Please enable location access to see nearby matches','discovery'),
('norwegian','toast.nearby.enable_location','Aktiver posisjonstilgang for å se treff i nærheten','discovery'),
('kurdish_sorani','toast.nearby.enable_location','تکایە دەستگەیشتن بە شوێن چالاک بکە بۆ بینینی هاوتاکانی نزیک','discovery'),
('kurdish_kurmanci','toast.nearby.enable_location','Ji kerema xwe gihîştina cih çalak bike bo dîtina hevtayên nêzîk','discovery'),
('german','toast.nearby.enable_location','Bitte aktivieren Sie den Standortzugriff, um nahegelegene Treffer zu sehen','discovery'),
-- PostDetail
('english','toast.post.like_failed','Failed to like post','posts'),
('norwegian','toast.post.like_failed','Kunne ikke like innlegget','posts'),
('kurdish_sorani','toast.post.like_failed','لایککردنی بابەت سەرکەوتوو نەبوو','posts'),
('kurdish_kurmanci','toast.post.like_failed','Like kirina postê bi ser neket','posts'),
('german','toast.post.like_failed','Beitrag konnte nicht geliked werden','posts'),
('english','toast.post.comments_soon','Comments coming soon!','posts'),
('norwegian','toast.post.comments_soon','Kommentarer kommer snart!','posts'),
('kurdish_sorani','toast.post.comments_soon','بۆچوونەکان بەم زووانە دێن!','posts'),
('kurdish_kurmanci','toast.post.comments_soon','Şîrove di demek nêzîk de tên!','posts'),
('german','toast.post.comments_soon','Kommentare kommen bald!','posts'),
-- ModerationPage
('english','admin.content_moderation','Content Moderation','admin'),
('norwegian','admin.content_moderation','Innholdsmoderering','admin'),
('kurdish_sorani','admin.content_moderation','مۆدێرەیتکردنی ناوەرۆک','admin'),
('kurdish_kurmanci','admin.content_moderation','Moderasyona naverokê','admin'),
('german','admin.content_moderation','Inhaltsmoderation','admin'),
('english','admin.review_moderate','Review and moderate reported content','admin'),
('norwegian','admin.review_moderate','Gjennomgå og moderere rapportert innhold','admin'),
('kurdish_sorani','admin.review_moderate','پێداچوونەوە و مۆدێرەیتکردنی ناوەرۆکی ڕاپۆرتکراو','admin'),
('kurdish_kurmanci','admin.review_moderate','Vekolîn û moderasyona naveroka raportkirî','admin'),
('german','admin.review_moderate','Gemeldete Inhalte überprüfen und moderieren','admin'),
('english','admin.ai_moderation','AI-Powered Content Moderation','admin'),
('norwegian','admin.ai_moderation','KI-drevet innholdsmoderering','admin'),
('kurdish_sorani','admin.ai_moderation','مۆدێرەیتکردنی ناوەرۆک بە یارمەتی AI','admin'),
('kurdish_kurmanci','admin.ai_moderation','Moderasyona naverokê bi AI','admin'),
('german','admin.ai_moderation','KI-gestützte Inhaltsmoderation','admin'),
('english','admin.ai_moderation_desc','Our AI system pre-screens content and assigns risk levels to help prioritize your review','admin'),
('norwegian','admin.ai_moderation_desc','Vårt KI-system forfiltrerer innhold og tildeler risikonivåer for å hjelpe med prioritering','admin'),
('kurdish_sorani','admin.ai_moderation_desc','سیستەمی AIمان ناوەرۆک پێش پاڵاوتن دەکات و ئاستی مەترسی دادەنێت','admin'),
('kurdish_kurmanci','admin.ai_moderation_desc','Sîstema meya AI naverokê pêş-parzûn dike û astên xeterê destnîşan dike','admin'),
('german','admin.ai_moderation_desc','Unser KI-System prüft Inhalte vor und weist Risikostufen zu','admin'),
('english','admin.reported_content','Reported Content','admin'),
('norwegian','admin.reported_content','Rapportert innhold','admin'),
('kurdish_sorani','admin.reported_content','ناوەرۆکی ڕاپۆرتکراو','admin'),
('kurdish_kurmanci','admin.reported_content','Naveroka raportkirî','admin'),
('german','admin.reported_content','Gemeldete Inhalte','admin'),
('english','admin.review_take_action','Review and take action on user reports','admin'),
('norwegian','admin.review_take_action','Gjennomgå og ta handling på brukerrapporter','admin'),
('kurdish_sorani','admin.review_take_action','پێداچوونەوە و کار لەسەر ڕاپۆرتەکانی بەکارهێنەر','admin'),
('kurdish_kurmanci','admin.review_take_action','Vekolîn û tevgerîn li ser raportên bikarhêneran','admin'),
('german','admin.review_take_action','Benutzerberichte überprüfen und Maßnahmen ergreifen','admin'),
('english','admin.review_report','Review Report','admin'),
('norwegian','admin.review_report','Gjennomgå rapport','admin'),
('kurdish_sorani','admin.review_report','پێداچوونەوەی ڕاپۆرت','admin'),
('kurdish_kurmanci','admin.review_report','Vekolîna raportê','admin'),
('german','admin.review_report','Bericht überprüfen','admin'),
('english','admin.reported_user','Reported User','admin'),
('norwegian','admin.reported_user','Rapportert bruker','admin'),
('kurdish_sorani','admin.reported_user','بەکارهێنەری ڕاپۆرتکراو','admin'),
('kurdish_kurmanci','admin.reported_user','Bikarhênerê raportkirî','admin'),
('german','admin.reported_user','Gemeldeter Benutzer','admin'),
('english','admin.reporter','Reporter','admin'),
('norwegian','admin.reporter','Rapportør','admin'),
('kurdish_sorani','admin.reporter','ڕاپۆرتکەر','admin'),
('kurdish_kurmanci','admin.reporter','Raportker','admin'),
('german','admin.reporter','Melder','admin'),
('english','admin.content_type','Content Type','admin'),
('norwegian','admin.content_type','Innholdstype','admin'),
('kurdish_sorani','admin.content_type','جۆری ناوەرۆک','admin'),
('kurdish_kurmanci','admin.content_type','Cureyê naverokê','admin'),
('german','admin.content_type','Inhaltstyp','admin'),
('english','admin.reason','Reason','admin'),
('norwegian','admin.reason','Grunn','admin'),
('kurdish_sorani','admin.reason','هۆکار','admin'),
('kurdish_kurmanci','admin.reason','Sedem','admin'),
('german','admin.reason','Grund','admin'),
('english','admin.additional_details','Additional Details','admin'),
('norwegian','admin.additional_details','Tilleggsdetaljer','admin'),
('kurdish_sorani','admin.additional_details','وردەکاری زیاتر','admin'),
('kurdish_kurmanci','admin.additional_details','Hûrguliyên din','admin'),
('german','admin.additional_details','Zusätzliche Details','admin'),
('english','admin.action','Action','admin'),
('norwegian','admin.action','Handling','admin'),
('kurdish_sorani','admin.action','کردار','admin'),
('kurdish_kurmanci','admin.action','Çalakî','admin'),
('german','admin.action','Aktion','admin'),
('english','admin.dismiss_report','Dismiss Report','admin'),
('norwegian','admin.dismiss_report','Avvis rapport','admin'),
('kurdish_sorani','admin.dismiss_report','ڕەتکردنەوەی ڕاپۆرت','admin'),
('kurdish_kurmanci','admin.dismiss_report','Redkirina raportê','admin'),
('german','admin.dismiss_report','Bericht ablehnen','admin'),
('english','admin.action_taken','Action Taken','admin'),
('norwegian','admin.action_taken','Handling tatt','admin'),
('kurdish_sorani','admin.action_taken','کرداری ئەنجامدراو','admin'),
('kurdish_kurmanci','admin.action_taken','Çalakî hat kirin','admin'),
('german','admin.action_taken','Maßnahme ergriffen','admin'),
('english','admin.admin_notes','Admin Notes','admin'),
('norwegian','admin.admin_notes','Administratornotater','admin'),
('kurdish_sorani','admin.admin_notes','تێبینییەکانی بەڕێوەبەر','admin'),
('kurdish_kurmanci','admin.admin_notes','Nîşeyên rêvebir','admin'),
('german','admin.admin_notes','Admin-Notizen','admin'),
('english','admin.add_notes','Add your notes about this report...','admin'),
('norwegian','admin.add_notes','Legg til dine notater om denne rapporten...','admin'),
('kurdish_sorani','admin.add_notes','تێبینییەکانت زیاد بکە دەربارەی ئەم ڕاپۆرتە...','admin'),
('kurdish_kurmanci','admin.add_notes','Nîşeyên xwe li ser vê raportê zêde bike...','admin'),
('german','admin.add_notes','Fügen Sie Ihre Notizen zu diesem Bericht hinzu...','admin'),
('english','admin.mark_resolved','Mark as Resolved','admin'),
('norwegian','admin.mark_resolved','Merk som løst','admin'),
('kurdish_sorani','admin.mark_resolved','وەک چارەسەرکراو نیشانە بکە','admin'),
('kurdish_kurmanci','admin.mark_resolved','Wek çareserkirî nîşan bike','admin'),
('german','admin.mark_resolved','Als gelöst markieren','admin'),
('english','toast.report.resolved','Report resolved successfully','admin'),
('norwegian','toast.report.resolved','Rapport løst vellykket','admin'),
('kurdish_sorani','toast.report.resolved','ڕاپۆرت بە سەرکەوتوویی چارەسەر کرا','admin'),
('kurdish_kurmanci','toast.report.resolved','Raport bi serkeftî hat çareserkirin','admin'),
('german','toast.report.resolved','Bericht erfolgreich gelöst','admin'),
('english','toast.report.failed','Failed to resolve report','admin'),
('norwegian','toast.report.failed','Kunne ikke løse rapporten','admin'),
('kurdish_sorani','toast.report.failed','چارەسەرکردنی ڕاپۆرت سەرکەوتوو نەبوو','admin'),
('kurdish_kurmanci','toast.report.failed','Çareserkirina raportê bi ser neket','admin'),
('german','toast.report.failed','Bericht konnte nicht gelöst werden','admin'),
-- MessagesPage
('english','admin.messages_management','Messages Management','admin'),
('norwegian','admin.messages_management','Meldingsadministrasjon','admin'),
('kurdish_sorani','admin.messages_management','بەڕێوەبردنی نامەکان','admin'),
('kurdish_kurmanci','admin.messages_management','Rêvebirina peyaman','admin'),
('german','admin.messages_management','Nachrichtenverwaltung','admin'),
('english','admin.message_details','Message Details','admin'),
('norwegian','admin.message_details','Meldingsdetaljer','admin'),
('kurdish_sorani','admin.message_details','وردەکاری نامە','admin'),
('kurdish_kurmanci','admin.message_details','Hûrguliyên peyamê','admin'),
('german','admin.message_details','Nachrichtendetails','admin'),
('english','toast.message.deleted','Message deleted successfully','admin'),
('norwegian','toast.message.deleted','Melding slettet','admin'),
('kurdish_sorani','toast.message.deleted','نامە بە سەرکەوتوویی سڕایەوە','admin'),
('kurdish_kurmanci','toast.message.deleted','Peyam bi serkeftî hat jêbirin','admin'),
('german','toast.message.deleted','Nachricht erfolgreich gelöscht','admin'),
('english','toast.message.delete_failed','Failed to delete message','admin'),
('norwegian','toast.message.delete_failed','Kunne ikke slette meldingen','admin'),
('kurdish_sorani','toast.message.delete_failed','سڕینەوەی نامە سەرکەوتوو نەبوو','admin'),
('kurdish_kurmanci','toast.message.delete_failed','Jêbirina peyamê bi ser neket','admin'),
('german','toast.message.delete_failed','Nachricht konnte nicht gelöscht werden','admin'),
-- ConversationsPage
('english','admin.conversations_management','Conversations Management','admin'),
('norwegian','admin.conversations_management','Samtaleadministrasjon','admin'),
('kurdish_sorani','admin.conversations_management','بەڕێوەبردنی گفتوگۆکان','admin'),
('kurdish_kurmanci','admin.conversations_management','Rêvebirina axaftinan','admin'),
('german','admin.conversations_management','Konversationsverwaltung','admin'),
('english','admin.view_conversations','View all conversations and muted chats','admin'),
('norwegian','admin.view_conversations','Se alle samtaler og dempede chatter','admin'),
('kurdish_sorani','admin.view_conversations','بینینی هەموو گفتوگۆکان و چاتە بێدەنگکراوەکان','admin'),
('kurdish_kurmanci','admin.view_conversations','Dîtina hemû axaftinan û sohbetên bêdeng','admin'),
('german','admin.view_conversations','Alle Konversationen und stummgeschaltete Chats anzeigen','admin'),
('english','admin.all_conversations','All Conversations','admin'),
('norwegian','admin.all_conversations','Alle samtaler','admin'),
('kurdish_sorani','admin.all_conversations','هەموو گفتوگۆکان','admin'),
('kurdish_kurmanci','admin.all_conversations','Hemû axaftin','admin'),
('german','admin.all_conversations','Alle Konversationen','admin'),
('english','admin.muted_conversations','Muted Conversations','admin'),
('norwegian','admin.muted_conversations','Dempede samtaler','admin'),
('kurdish_sorani','admin.muted_conversations','گفتوگۆی بێدەنگکراو','admin'),
('kurdish_kurmanci','admin.muted_conversations','Axaftinên bêdeng','admin'),
('german','admin.muted_conversations','Stummgeschaltete Konversationen','admin'),
('english','admin.conversations','Conversations','admin'),
('norwegian','admin.conversations','Samtaler','admin'),
('kurdish_sorani','admin.conversations','گفتوگۆکان','admin'),
('kurdish_kurmanci','admin.conversations','Axaftin','admin'),
('german','admin.conversations','Konversationen','admin'),
('english','admin.muted','Muted','admin'),
('norwegian','admin.muted','Dempet','admin'),
('kurdish_sorani','admin.muted','بێدەنگکراو','admin'),
('kurdish_kurmanci','admin.muted','Bêdeng','admin'),
('german','admin.muted','Stummgeschaltet','admin'),
-- Common shared keys
('english','common.search','Search','common'),
('norwegian','common.search','Søk','common'),
('kurdish_sorani','common.search','گەڕان','common'),
('kurdish_kurmanci','common.search','Lêgerîn','common'),
('german','common.search','Suche','common'),
('english','common.refresh','Refresh','common'),
('norwegian','common.refresh','Oppdater','common'),
('kurdish_sorani','common.refresh','نوێکردنەوە','common'),
('kurdish_kurmanci','common.refresh','Nûkirin','common'),
('german','common.refresh','Aktualisieren','common'),
('english','common.review','Review','common'),
('norwegian','common.review','Gjennomgå','common'),
('kurdish_sorani','common.review','پێداچوونەوە','common'),
('kurdish_kurmanci','common.review','Vekolîn','common'),
('german','common.review','Überprüfen','common'),
('english','common.previous','Previous','common'),
('norwegian','common.previous','Forrige','common'),
('kurdish_sorani','common.previous','پێشوو','common'),
('kurdish_kurmanci','common.previous','Berê','common'),
('german','common.previous','Zurück','common'),
('english','common.next','Next','common'),
('norwegian','common.next','Neste','common'),
('kurdish_sorani','common.next','دواتر','common'),
('kurdish_kurmanci','common.next','Pêş','common'),
('german','common.next','Weiter','common'),
('english','common.loading','Loading...','common'),
('norwegian','common.loading','Laster...','common'),
('kurdish_sorani','common.loading','بارکردن...','common'),
('kurdish_kurmanci','common.loading','Barkirin...','common'),
('german','common.loading','Laden...','common'),
('english','common.all','All','common'),
('norwegian','common.all','Alle','common'),
('kurdish_sorani','common.all','هەموو','common'),
('kurdish_kurmanci','common.all','Hemû','common'),
('german','common.all','Alle','common'),
('english','common.read','Read','common'),
('norwegian','common.read','Lest','common'),
('kurdish_sorani','common.read','خوێندراوە','common'),
('kurdish_kurmanci','common.read','Xwendiye','common'),
('german','common.read','Gelesen','common'),
('english','common.unread','Unread','common'),
('norwegian','common.unread','Ulest','common'),
('kurdish_sorani','common.unread','نەخوێندراوە','common'),
('kurdish_kurmanci','common.unread','Nexwendiye','common'),
('german','common.unread','Ungelesen','common'),
('english','common.from','From','common'),
('norwegian','common.from','Fra','common'),
('kurdish_sorani','common.from','لە','common'),
('kurdish_kurmanci','common.from','Ji','common'),
('german','common.from','Von','common'),
('english','common.message','Message','common'),
('norwegian','common.message','Melding','common'),
('kurdish_sorani','common.message','نامە','common'),
('kurdish_kurmanci','common.message','Peyam','common'),
('german','common.message','Nachricht','common'),
('english','common.status','Status','common'),
('norwegian','common.status','Status','common'),
('kurdish_sorani','common.status','دۆخ','common'),
('kurdish_kurmanci','common.status','Rewş','common'),
('german','common.status','Status','common'),
('english','common.actions','Actions','common'),
('norwegian','common.actions','Handlinger','common'),
('kurdish_sorani','common.actions','کردارەکان','common'),
('kurdish_kurmanci','common.actions','Çalakî','common'),
('german','common.actions','Aktionen','common'),
('english','common.sender','Sender','common'),
('norwegian','common.sender','Avsender','common'),
('kurdish_sorani','common.sender','نێرەر','common'),
('kurdish_kurmanci','common.sender','Şander','common'),
('german','common.sender','Absender','common'),
('english','common.recipient','Recipient','common'),
('norwegian','common.recipient','Mottaker','common'),
('kurdish_sorani','common.recipient','وەرگر','common'),
('kurdish_kurmanci','common.recipient','Wergir','common'),
('german','common.recipient','Empfänger','common'),
('english','common.type','Type','common'),
('norwegian','common.type','Type','common'),
('kurdish_sorani','common.type','جۆر','common'),
('kurdish_kurmanci','common.type','Cure','common'),
('german','common.type','Typ','common'),
('english','toast.conversations.load_failed','Failed to load conversations','admin'),
('norwegian','toast.conversations.load_failed','Kunne ikke laste samtaler','admin'),
('kurdish_sorani','toast.conversations.load_failed','بارکردنی گفتوگۆکان سەرکەوتوو نەبوو','admin'),
('kurdish_kurmanci','toast.conversations.load_failed','Barkirina axaftinan bi ser neket','admin'),
('german','toast.conversations.load_failed','Konversationen konnten nicht geladen werden','admin'),
('english','toast.conversations.muted_failed','Failed to load muted conversations','admin'),
('norwegian','toast.conversations.muted_failed','Kunne ikke laste dempede samtaler','admin'),
('kurdish_sorani','toast.conversations.muted_failed','بارکردنی گفتوگۆی بێدەنگکراو سەرکەوتوو نەبوو','admin'),
('kurdish_kurmanci','toast.conversations.muted_failed','Barkirina axaftinên bêdeng bi ser neket','admin'),
('german','toast.conversations.muted_failed','Stummgeschaltete Konversationen konnten nicht geladen werden','admin')
ON CONFLICT DO NOTHING;
