
-- Batch 9: i18n for remaining SuperAdmin pages
-- EmailCampaigns, BulkActions, Categories, ABTesting, Interests, Comments, Matches, SupportTickets

INSERT INTO public.app_translations (language_code, translation_key, translation_value, category) VALUES
-- Email Campaigns Page
('english', 'admin.email_campaigns_title', 'Email Campaigns', 'admin'),
('english', 'admin.new_campaign', 'New Campaign', 'admin'),
('english', 'admin.ai_email_optimization', 'AI-Powered Email Optimization', 'admin'),
('english', 'admin.ai_email_optimization_desc', 'Our AI system analyzes campaign performance and suggests optimizations for subject lines, content, and send times', 'admin'),
('english', 'admin.all_campaigns', 'All Campaigns', 'admin'),
('english', 'admin.search_campaigns', 'Search campaigns...', 'admin'),
('english', 'admin.filter_by_status', 'Filter by status', 'admin'),
('english', 'admin.all_statuses', 'All Statuses', 'admin'),
('english', 'admin.campaign_name', 'Campaign Name', 'admin'),
('english', 'admin.audience', 'Audience', 'admin'),
('english', 'admin.last_sent', 'Last Sent', 'admin'),
('english', 'admin.next_send', 'Next Send', 'admin'),
('english', 'admin.opens', 'Opens', 'admin'),
('english', 'admin.clicks', 'Clicks', 'admin'),
('english', 'admin.actions', 'Actions', 'admin'),
('english', 'admin.all_users', 'All users', 'admin'),
('english', 'admin.no_campaigns_found', 'No campaigns found', 'admin'),
('english', 'admin.duplicate', 'Duplicate', 'admin'),
('english', 'admin.edit', 'Edit', 'admin'),
('english', 'admin.campaign_performance', 'Campaign Performance', 'admin'),
('english', 'admin.daily_engagement', 'Daily Engagement', 'admin'),
('english', 'admin.ai_recommendations', 'AI Recommendations', 'admin'),
('english', 'admin.draft_campaign', 'Draft Campaign', 'admin'),
('english', 'admin.draft_campaign_desc', 'This campaign hasn''t been sent yet. No performance metrics available.', 'admin'),
('english', 'admin.edit_campaign', 'Edit Campaign', 'admin'),
('english', 'admin.schedule_campaign', 'Schedule Campaign', 'admin'),
('english', 'admin.pause_campaign', 'Pause Campaign', 'admin'),
('english', 'admin.active_campaigns', 'Active Campaigns', 'admin'),
('english', 'admin.active_campaigns_desc', 'Campaigns that are currently active', 'admin'),
('english', 'admin.scheduled_campaigns', 'Scheduled Campaigns', 'admin'),
('english', 'admin.scheduled_campaigns_desc', 'Campaigns that are scheduled to be sent', 'admin'),
('english', 'admin.paused_campaigns', 'Paused Campaigns', 'admin'),
('english', 'admin.paused_campaigns_desc', 'Campaigns that have been paused', 'admin'),
('english', 'admin.draft_campaigns', 'Draft Campaigns', 'admin'),
('english', 'admin.draft_campaigns_desc', 'Campaigns in preparation', 'admin'),
('english', 'admin.create_email_campaign', 'Create New Email Campaign', 'admin'),
('english', 'admin.create_email_campaign_desc', 'Set up a new email campaign to engage with your users.', 'admin'),
('english', 'admin.target_audience', 'Target Audience', 'admin'),
('english', 'admin.subject_line', 'Subject Line', 'admin'),
('english', 'admin.email_content', 'Email Content', 'admin'),
('english', 'admin.send_date', 'Send Date', 'admin'),
('english', 'admin.send_time', 'Send Time', 'admin'),
('english', 'admin.campaign_type', 'Campaign Type', 'admin'),
('english', 'admin.one_time_campaign', 'One-time Campaign', 'admin'),
('english', 'admin.recurring_campaign', 'Recurring Campaign', 'admin'),
('english', 'admin.automated_campaign', 'Automated Trigger Campaign', 'admin'),
('english', 'admin.save_as_draft', 'Save as Draft', 'admin'),
('english', 'admin.cancel', 'Cancel', 'admin'),
('english', 'admin.campaign_started', 'Campaign started', 'admin'),
('english', 'admin.campaign_paused', 'Campaign paused', 'admin'),
('english', 'admin.campaign_deleted', 'Campaign deleted', 'admin'),
('english', 'admin.new_users', 'New Users', 'admin'),
('english', 'admin.inactive_users', 'Inactive Users', 'admin'),
('english', 'admin.premium_users', 'Premium Users', 'admin'),
('english', 'admin.free_users', 'Free Users', 'admin'),
('english', 'admin.not_scheduled', 'Not scheduled', 'admin'),
('english', 'admin.status', 'Status', 'admin'),

-- Bulk Actions Page
('english', 'admin.bulk_user_actions', 'Bulk User Actions', 'admin'),
('english', 'admin.import_users', 'Import Users', 'admin'),
('english', 'admin.refresh', 'Refresh', 'admin'),
('english', 'admin.refreshing', 'Refreshing...', 'admin'),
('english', 'admin.ai_user_segmentation', 'AI-Powered User Segmentation', 'admin'),
('english', 'admin.ai_user_segmentation_desc', 'Our AI system analyzes user behavior patterns to suggest optimal user segments for targeted actions', 'admin'),
('english', 'admin.action_history', 'Action History', 'admin'),
('english', 'admin.new_bulk_action', 'New Bulk Action', 'admin'),
('english', 'admin.scheduled_actions', 'Scheduled Actions', 'admin'),
('english', 'admin.search_bulk_actions', 'Search bulk actions...', 'admin'),
('english', 'admin.completed', 'Completed', 'admin'),
('english', 'admin.processing', 'Processing', 'admin'),
('english', 'admin.scheduled', 'Scheduled', 'admin'),
('english', 'admin.failed', 'Failed', 'admin'),
('english', 'admin.job_name', 'Job Name', 'admin'),
('english', 'admin.type', 'Type', 'admin'),
('english', 'admin.affected_users', 'Affected Users', 'admin'),
('english', 'admin.created_by', 'Created By', 'admin'),
('english', 'admin.timestamp', 'Timestamp', 'admin'),
('english', 'admin.view_details', 'View Details', 'admin'),
('english', 'admin.no_bulk_actions_found', 'No bulk action jobs found', 'admin'),
('english', 'admin.select_bulk_action_type', 'Select Bulk Action Type', 'admin'),
('english', 'admin.select_bulk_action_desc', 'Choose the type of bulk action you want to perform', 'admin'),
('english', 'admin.status_update', 'Status Update', 'admin'),
('english', 'admin.status_update_desc', 'Update the status of multiple user accounts', 'admin'),
('english', 'admin.email_notification', 'Email Notification', 'admin'),
('english', 'admin.email_notification_desc', 'Send an email to multiple users', 'admin'),
('english', 'admin.account_suspension', 'Account Suspension', 'admin'),
('english', 'admin.account_suspension_desc', 'Suspend multiple user accounts', 'admin'),
('english', 'admin.role_update', 'Role Update', 'admin'),
('english', 'admin.role_update_desc', 'Change the role of multiple users', 'admin'),
('english', 'admin.data_update', 'Data Update', 'admin'),
('english', 'admin.data_update_desc', 'Update specific data fields for multiple users', 'admin'),
('english', 'admin.custom_action', 'Custom Action', 'admin'),
('english', 'admin.custom_action_desc', 'Define a custom action for multiple users', 'admin'),
('english', 'admin.configure_settings', 'Configure your bulk action settings', 'admin'),
('english', 'admin.change_action_type', 'Change Action Type', 'admin'),
('english', 'admin.action_name', 'Action Name', 'admin'),
('english', 'admin.new_status', 'New Status', 'admin'),
('english', 'admin.active', 'Active', 'admin'),
('english', 'admin.inactive', 'Inactive', 'admin'),
('english', 'admin.suspended', 'Suspended', 'admin'),
('english', 'admin.email_subject', 'Email Subject', 'admin'),
('english', 'admin.new_role', 'New Role', 'admin'),
('english', 'admin.select_new_role', 'Select new role', 'admin'),
('english', 'admin.standard_user', 'Standard User', 'admin'),
('english', 'admin.premium_user', 'Premium User', 'admin'),
('english', 'admin.moderator', 'Moderator', 'admin'),
('english', 'admin.admin', 'Admin', 'admin'),
('english', 'admin.schedule', 'Schedule', 'admin'),
('english', 'admin.execute_immediately', 'Execute immediately', 'admin'),
('english', 'admin.schedule_for_later', 'Schedule for later', 'admin'),
('english', 'admin.select_users', 'Select Users', 'admin'),
('english', 'admin.select_users_desc', 'Choose which users to apply this action to', 'admin'),
('english', 'admin.name', 'Name', 'admin'),
('english', 'admin.email', 'Email', 'admin'),
('english', 'admin.role', 'Role', 'admin'),
('english', 'admin.users_selected', '{{count}} users selected', 'admin'),
('english', 'admin.start_bulk_action', 'Start Bulk Action', 'admin'),
('english', 'admin.scheduled_actions_desc', 'Actions scheduled to run in the future', 'admin'),
('english', 'admin.confirm_bulk_action', 'Confirm Bulk Action', 'admin'),
('english', 'admin.confirm_bulk_action_desc', 'Are you sure you want to perform this action on {{count}} users?', 'admin'),
('english', 'admin.warning', 'Warning', 'admin'),
('english', 'admin.bulk_action_warning', 'This action cannot be undone. It will affect {{count}} user accounts.', 'admin'),
('english', 'admin.type_confirm', 'Type "CONFIRM" to proceed', 'admin'),
('english', 'admin.confirm_action', 'Confirm Action', 'admin'),
('english', 'admin.bulk_import_users', 'Bulk Import Users', 'admin'),
('english', 'admin.bulk_import_desc', 'Upload a file to import multiple users at once', 'admin'),
('english', 'admin.import_type', 'Import Type', 'admin'),
('english', 'admin.create_new_users', 'Create New Users', 'admin'),
('english', 'admin.update_existing_users', 'Update Existing Users', 'admin'),
('english', 'admin.create_and_update', 'Create and Update Users', 'admin'),
('english', 'admin.file_format', 'File Format', 'admin'),
('english', 'admin.click_to_upload', 'Click to upload or drag and drop', 'admin'),
('english', 'admin.supported_formats', 'Support for CSV, XLSX, JSON', 'admin'),
('english', 'admin.select_file', 'Select File', 'admin'),
('english', 'admin.send_welcome_email', 'Send welcome email to new users', 'admin'),
('english', 'admin.override_existing', 'Override existing data for duplicate users', 'admin'),
('english', 'admin.download_template', 'Download Template', 'admin'),
('english', 'admin.upload_and_import', 'Upload and Start Import', 'admin'),

-- Categories Page
('english', 'admin.categories_management', 'Categories Management', 'admin'),
('english', 'admin.manage_categories_desc', 'Manage profile categories and items', 'admin'),
('english', 'admin.add_category', 'Add Category', 'admin'),
('english', 'admin.add_item', 'Add Item', 'admin'),
('english', 'admin.ai_categories', 'AI-Enhanced Categories', 'admin'),
('english', 'admin.ai_categories_desc', 'Our AI system analyzes user engagement and suggests optimal category organization', 'admin'),
('english', 'admin.categories', 'Categories', 'admin'),
('english', 'admin.items', 'Items', 'admin'),
('english', 'admin.profile_categories', 'Profile Categories', 'admin'),
('english', 'admin.manage_categories', 'Manage and organize profile categories', 'admin'),
('english', 'admin.search_categories', 'Search categories...', 'admin'),
('english', 'admin.all', 'All', 'admin'),
('english', 'admin.description', 'Description', 'admin'),
('english', 'admin.order', 'Order', 'admin'),
('english', 'admin.updated', 'Updated', 'admin'),
('english', 'admin.view_items', 'View Items', 'admin'),
('english', 'admin.no_categories_found', 'No categories found', 'admin'),
('english', 'admin.total_categories', 'Total categories: {{count}}', 'admin'),
('english', 'admin.view_all_categories', 'View All Categories', 'admin'),
('english', 'admin.items_in', 'Items in {{name}}', 'admin'),
('english', 'admin.manage_items_in', 'Manage items in the "{{name}}" category', 'admin'),
('english', 'admin.select_category', 'Select a category to manage its items', 'admin'),
('english', 'admin.all_category_items', 'All Category Items', 'admin'),

-- AB Testing Page
('english', 'admin.ab_testing_title', 'A/B Testing', 'admin'),
('english', 'admin.new_test', 'New Test', 'admin'),
('english', 'admin.ai_test_analysis', 'AI-Powered Test Analysis', 'admin'),
('english', 'admin.ai_test_analysis_desc', 'Our AI continuously analyzes test results and provides insights to help optimize your decisions', 'admin'),
('english', 'admin.all_tests', 'All Tests', 'admin'),
('english', 'admin.test_name', 'Test Name', 'admin'),
('english', 'admin.target', 'Target', 'admin'),
('english', 'admin.improvement', 'Improvement', 'admin'),
('english', 'admin.duration', 'Duration', 'admin'),
('english', 'admin.view_details_link', 'View details', 'admin'),
('english', 'admin.not_started', 'Not started', 'admin'),
('english', 'admin.ongoing', 'Ongoing', 'admin'),
('english', 'admin.stop', 'Stop', 'admin'),
('english', 'admin.start', 'Start', 'admin'),
('english', 'admin.target_audience_label', 'Target Audience', 'admin'),
('english', 'admin.performance_metrics', 'Performance Metrics', 'admin'),
('english', 'admin.ai_analysis', 'AI Analysis', 'admin'),
('english', 'admin.stop_test', 'Stop Test', 'admin'),
('english', 'admin.active_tests_tab', 'Active Tests', 'admin'),
('english', 'admin.active_tests_desc', 'Currently running tests', 'admin'),
('english', 'admin.completed_tests', 'Completed Tests', 'admin'),
('english', 'admin.completed_tests_desc', 'Finished tests with results', 'admin'),
('english', 'admin.draft_tests', 'Draft Tests', 'admin'),
('english', 'admin.draft_tests_desc', 'Tests in preparation', 'admin'),
('english', 'admin.create_ab_test', 'Create New A/B Test', 'admin'),
('english', 'admin.create_ab_test_desc', 'Set up a new test to compare variations and measure their performance.', 'admin'),
('english', 'admin.test_type', 'Test Type', 'admin'),
('english', 'admin.ui_component_test', 'UI Component Test', 'admin'),
('english', 'admin.user_flow_test', 'User Flow Test', 'admin'),
('english', 'admin.algorithm_test', 'Algorithm Test', 'admin'),
('english', 'admin.content_test', 'Content Test', 'admin'),
('english', 'admin.variant_a', 'Variant A (Control)', 'admin'),
('english', 'admin.variant_b', 'Variant B (Test)', 'admin'),
('english', 'admin.returning_users', 'Returning Users', 'admin'),
('english', 'admin.traffic_distribution', 'Traffic Distribution', 'admin'),
('english', 'admin.success_metrics', 'Success Metrics', 'admin'),
('english', 'admin.select_primary_metric', 'Select primary metric', 'admin'),

-- Interests Page
('english', 'admin.interests_management', 'Interests Management', 'admin'),
('english', 'admin.manage_interests', 'Manage user interest categories ({{count}} interests)', 'admin'),
('english', 'admin.add_interest', 'Add Interest', 'admin'),
('english', 'admin.all_interests', 'All Interests', 'admin'),
('english', 'admin.search_interests', 'Search interests...', 'admin'),
('english', 'admin.loading_interests', 'Loading interests...', 'admin'),
('english', 'admin.no_interests_found', 'No interests found', 'admin'),
('english', 'admin.add_new_interest', 'Add New Interest', 'admin'),
('english', 'admin.interest_name', 'Interest Name', 'admin'),
('english', 'admin.category', 'Category', 'admin'),
('english', 'admin.select_category_label', 'Select a category', 'admin'),

-- Comments Page
('english', 'admin.comments_management', 'Comments Management', 'admin'),
('english', 'admin.comments_desc', 'View and moderate all comment interactions', 'admin'),
('english', 'admin.comment_likes', 'Comment Likes', 'admin'),
('english', 'admin.all_comment_likes', 'All Comment Likes', 'admin'),
('english', 'admin.search_by_user', 'Search by user name...', 'admin'),
('english', 'admin.loading_comment_likes', 'Loading comment likes...', 'admin'),
('english', 'admin.no_comment_likes', 'No comment likes found', 'admin'),
('english', 'admin.liked_comment', 'Liked a comment', 'admin'),

-- Matches Management Page
('english', 'admin.matches_management', 'Matches Management', 'admin'),
('english', 'admin.matches_desc', 'View and monitor all user matches ({{count}} total)', 'admin'),
('english', 'admin.all_matches', 'All Matches', 'admin'),
('english', 'admin.loading_matches', 'Loading matches...', 'admin'),
('english', 'admin.no_matches_found', 'No matches found', 'admin'),
('english', 'admin.user_1', 'User 1', 'admin'),
('english', 'admin.user_2', 'User 2', 'admin'),

-- Support Tickets Page
('english', 'admin.support_tickets', 'Support Tickets', 'admin'),
('english', 'admin.support_tickets_desc', 'Manage and respond to user support requests', 'admin'),
('english', 'admin.total_tickets', 'Total Tickets', 'admin'),
('english', 'admin.open', 'Open', 'admin'),
('english', 'admin.pending', 'Pending', 'admin'),
('english', 'admin.resolved', 'Resolved', 'admin'),
('english', 'admin.search_tickets', 'Search by subject, email, or message...', 'admin'),
('english', 'admin.all_status', 'All Status', 'admin'),
('english', 'admin.all_categories', 'All Categories', 'admin'),
('english', 'admin.closed', 'Closed', 'admin'),
('english', 'admin.technical', 'Technical', 'admin'),
('english', 'admin.billing', 'Billing', 'admin'),
('english', 'admin.account', 'Account', 'admin'),
('english', 'admin.safety', 'Safety', 'admin'),
('english', 'admin.feedback', 'Feedback', 'admin'),
('english', 'admin.other', 'Other', 'admin'),
('english', 'admin.search', 'Search', 'admin'),
('english', 'admin.subject', 'Subject', 'admin'),
('english', 'admin.created', 'Created', 'admin'),
('english', 'admin.no_tickets_found', 'No support tickets found', 'admin'),
('english', 'admin.ticket_details', 'Ticket Details', 'admin'),
('english', 'admin.message', 'Message', 'admin'),
('english', 'admin.admin_notes', 'Admin Notes / Responses', 'admin'),
('english', 'admin.add_response', 'Add Response', 'admin'),
('english', 'admin.write_response', 'Write your response to the user...', 'admin'),
('english', 'admin.change_status', 'Change Status', 'admin'),
('english', 'admin.close', 'Close', 'admin'),
('english', 'admin.send_response', 'Send Response', 'admin'),
('english', 'admin.unknown', 'Unknown', 'admin'),
('english', 'admin.draft', 'Draft', 'admin'),

-- Norwegian translations
('norwegian', 'admin.email_campaigns_title', 'E-postkampanjer', 'admin'),
('norwegian', 'admin.new_campaign', 'Ny kampanje', 'admin'),
('norwegian', 'admin.ai_email_optimization', 'AI-drevet e-postoptimalisering', 'admin'),
('norwegian', 'admin.ai_email_optimization_desc', 'Vårt AI-system analyserer kampanjeytelse og foreslår optimaliseringer for emnefelt, innhold og sendetider', 'admin'),
('norwegian', 'admin.all_campaigns', 'Alle kampanjer', 'admin'),
('norwegian', 'admin.search_campaigns', 'Søk kampanjer...', 'admin'),
('norwegian', 'admin.filter_by_status', 'Filtrer etter status', 'admin'),
('norwegian', 'admin.all_statuses', 'Alle statuser', 'admin'),
('norwegian', 'admin.campaign_name', 'Kampanjenavn', 'admin'),
('norwegian', 'admin.audience', 'Målgruppe', 'admin'),
('norwegian', 'admin.last_sent', 'Sist sendt', 'admin'),
('norwegian', 'admin.next_send', 'Neste sending', 'admin'),
('norwegian', 'admin.opens', 'Åpninger', 'admin'),
('norwegian', 'admin.clicks', 'Klikk', 'admin'),
('norwegian', 'admin.actions', 'Handlinger', 'admin'),
('norwegian', 'admin.all_users', 'Alle brukere', 'admin'),
('norwegian', 'admin.no_campaigns_found', 'Ingen kampanjer funnet', 'admin'),
('norwegian', 'admin.duplicate', 'Dupliser', 'admin'),
('norwegian', 'admin.edit', 'Rediger', 'admin'),
('norwegian', 'admin.campaign_performance', 'Kampanjeytelse', 'admin'),
('norwegian', 'admin.daily_engagement', 'Daglig engasjement', 'admin'),
('norwegian', 'admin.ai_recommendations', 'AI-anbefalinger', 'admin'),
('norwegian', 'admin.draft_campaign', 'Utkastkampanje', 'admin'),
('norwegian', 'admin.draft_campaign_desc', 'Denne kampanjen er ikke sendt ennå. Ingen ytelsesmålinger tilgjengelig.', 'admin'),
('norwegian', 'admin.edit_campaign', 'Rediger kampanje', 'admin'),
('norwegian', 'admin.schedule_campaign', 'Planlegg kampanje', 'admin'),
('norwegian', 'admin.pause_campaign', 'Pause kampanje', 'admin'),
('norwegian', 'admin.cancel', 'Avbryt', 'admin'),
('norwegian', 'admin.save_as_draft', 'Lagre som utkast', 'admin'),
('norwegian', 'admin.campaign_started', 'Kampanje startet', 'admin'),
('norwegian', 'admin.campaign_paused', 'Kampanje pauset', 'admin'),
('norwegian', 'admin.campaign_deleted', 'Kampanje slettet', 'admin'),
('norwegian', 'admin.status', 'Status', 'admin'),
('norwegian', 'admin.not_scheduled', 'Ikke planlagt', 'admin'),

('norwegian', 'admin.bulk_user_actions', 'Massehandlinger for brukere', 'admin'),
('norwegian', 'admin.import_users', 'Importer brukere', 'admin'),
('norwegian', 'admin.refresh', 'Oppdater', 'admin'),
('norwegian', 'admin.refreshing', 'Oppdaterer...', 'admin'),
('norwegian', 'admin.ai_user_segmentation', 'AI-drevet brukersegmentering', 'admin'),
('norwegian', 'admin.ai_user_segmentation_desc', 'Vårt AI-system analyserer brukeratferdsmønstre for å foreslå optimale brukersegmenter', 'admin'),
('norwegian', 'admin.action_history', 'Handlingshistorikk', 'admin'),
('norwegian', 'admin.new_bulk_action', 'Ny massehandling', 'admin'),
('norwegian', 'admin.scheduled_actions', 'Planlagte handlinger', 'admin'),
('norwegian', 'admin.completed', 'Fullført', 'admin'),
('norwegian', 'admin.processing', 'Behandler', 'admin'),
('norwegian', 'admin.scheduled', 'Planlagt', 'admin'),
('norwegian', 'admin.failed', 'Mislykket', 'admin'),
('norwegian', 'admin.job_name', 'Jobbnavn', 'admin'),
('norwegian', 'admin.type', 'Type', 'admin'),
('norwegian', 'admin.affected_users', 'Berørte brukere', 'admin'),
('norwegian', 'admin.created_by', 'Opprettet av', 'admin'),
('norwegian', 'admin.timestamp', 'Tidsstempel', 'admin'),
('norwegian', 'admin.view_details', 'Vis detaljer', 'admin'),
('norwegian', 'admin.no_bulk_actions_found', 'Ingen massehandlinger funnet', 'admin'),
('norwegian', 'admin.select_bulk_action_type', 'Velg type massehandling', 'admin'),
('norwegian', 'admin.select_bulk_action_desc', 'Velg typen massehandling du vil utføre', 'admin'),
('norwegian', 'admin.status_update', 'Statusoppdatering', 'admin'),
('norwegian', 'admin.status_update_desc', 'Oppdater status for flere brukerkontoer', 'admin'),
('norwegian', 'admin.email_notification', 'E-postvarsling', 'admin'),
('norwegian', 'admin.email_notification_desc', 'Send e-post til flere brukere', 'admin'),
('norwegian', 'admin.account_suspension', 'Kontosuspensjon', 'admin'),
('norwegian', 'admin.account_suspension_desc', 'Suspender flere brukerkontoer', 'admin'),
('norwegian', 'admin.role_update', 'Rolleoppdatering', 'admin'),
('norwegian', 'admin.role_update_desc', 'Endre rollen til flere brukere', 'admin'),
('norwegian', 'admin.data_update', 'Dataoppdatering', 'admin'),
('norwegian', 'admin.data_update_desc', 'Oppdater spesifikke datafelt for flere brukere', 'admin'),
('norwegian', 'admin.custom_action', 'Egendefinert handling', 'admin'),
('norwegian', 'admin.custom_action_desc', 'Definer en egendefinert handling for flere brukere', 'admin'),
('norwegian', 'admin.warning', 'Advarsel', 'admin'),
('norwegian', 'admin.confirm_bulk_action', 'Bekreft massehandling', 'admin'),
('norwegian', 'admin.confirm_action', 'Bekreft handling', 'admin'),
('norwegian', 'admin.select_users', 'Velg brukere', 'admin'),
('norwegian', 'admin.name', 'Navn', 'admin'),
('norwegian', 'admin.email', 'E-post', 'admin'),
('norwegian', 'admin.role', 'Rolle', 'admin'),
('norwegian', 'admin.start_bulk_action', 'Start massehandling', 'admin'),
('norwegian', 'admin.active', 'Aktiv', 'admin'),
('norwegian', 'admin.inactive', 'Inaktiv', 'admin'),
('norwegian', 'admin.suspended', 'Suspendert', 'admin'),
('norwegian', 'admin.draft', 'Utkast', 'admin'),

('norwegian', 'admin.categories_management', 'Kategoriforvaltning', 'admin'),
('norwegian', 'admin.add_category', 'Legg til kategori', 'admin'),
('norwegian', 'admin.add_item', 'Legg til element', 'admin'),
('norwegian', 'admin.categories', 'Kategorier', 'admin'),
('norwegian', 'admin.items', 'Elementer', 'admin'),
('norwegian', 'admin.profile_categories', 'Profilkategorier', 'admin'),
('norwegian', 'admin.all', 'Alle', 'admin'),
('norwegian', 'admin.description', 'Beskrivelse', 'admin'),
('norwegian', 'admin.order', 'Rekkefølge', 'admin'),
('norwegian', 'admin.updated', 'Oppdatert', 'admin'),
('norwegian', 'admin.view_items', 'Vis elementer', 'admin'),
('norwegian', 'admin.no_categories_found', 'Ingen kategorier funnet', 'admin'),

('norwegian', 'admin.ab_testing_title', 'A/B-testing', 'admin'),
('norwegian', 'admin.new_test', 'Ny test', 'admin'),
('norwegian', 'admin.all_tests', 'Alle tester', 'admin'),
('norwegian', 'admin.test_name', 'Testnavn', 'admin'),
('norwegian', 'admin.target', 'Mål', 'admin'),
('norwegian', 'admin.improvement', 'Forbedring', 'admin'),
('norwegian', 'admin.duration', 'Varighet', 'admin'),
('norwegian', 'admin.stop', 'Stopp', 'admin'),
('norwegian', 'admin.start', 'Start', 'admin'),
('norwegian', 'admin.stop_test', 'Stopp test', 'admin'),
('norwegian', 'admin.active_tests_tab', 'Aktive tester', 'admin'),
('norwegian', 'admin.completed_tests', 'Fullførte tester', 'admin'),
('norwegian', 'admin.draft_tests', 'Utkasttester', 'admin'),
('norwegian', 'admin.create_ab_test', 'Opprett ny A/B-test', 'admin'),

('norwegian', 'admin.interests_management', 'Interesseforvaltning', 'admin'),
('norwegian', 'admin.add_interest', 'Legg til interesse', 'admin'),
('norwegian', 'admin.all_interests', 'Alle interesser', 'admin'),
('norwegian', 'admin.search_interests', 'Søk interesser...', 'admin'),
('norwegian', 'admin.loading_interests', 'Laster interesser...', 'admin'),
('norwegian', 'admin.no_interests_found', 'Ingen interesser funnet', 'admin'),
('norwegian', 'admin.add_new_interest', 'Legg til ny interesse', 'admin'),
('norwegian', 'admin.interest_name', 'Interessenavn', 'admin'),
('norwegian', 'admin.category', 'Kategori', 'admin'),

('norwegian', 'admin.comments_management', 'Kommentarforvaltning', 'admin'),
('norwegian', 'admin.comments_desc', 'Se og moderer alle kommentarinteraksjoner', 'admin'),
('norwegian', 'admin.comment_likes', 'Kommentarliker', 'admin'),
('norwegian', 'admin.all_comment_likes', 'Alle kommentarliker', 'admin'),
('norwegian', 'admin.search_by_user', 'Søk etter brukernavn...', 'admin'),
('norwegian', 'admin.loading_comment_likes', 'Laster kommentarliker...', 'admin'),
('norwegian', 'admin.no_comment_likes', 'Ingen kommentarliker funnet', 'admin'),
('norwegian', 'admin.liked_comment', 'Likte en kommentar', 'admin'),

('norwegian', 'admin.matches_management', 'Matchforvaltning', 'admin'),
('norwegian', 'admin.all_matches', 'Alle matcher', 'admin'),
('norwegian', 'admin.loading_matches', 'Laster matcher...', 'admin'),
('norwegian', 'admin.no_matches_found', 'Ingen matcher funnet', 'admin'),
('norwegian', 'admin.user_1', 'Bruker 1', 'admin'),
('norwegian', 'admin.user_2', 'Bruker 2', 'admin'),

('norwegian', 'admin.support_tickets', 'Støttehenvendelser', 'admin'),
('norwegian', 'admin.support_tickets_desc', 'Håndter og svar på brukerstøtteforespørsler', 'admin'),
('norwegian', 'admin.total_tickets', 'Totalt henvendelser', 'admin'),
('norwegian', 'admin.open', 'Åpen', 'admin'),
('norwegian', 'admin.pending', 'Venter', 'admin'),
('norwegian', 'admin.resolved', 'Løst', 'admin'),
('norwegian', 'admin.closed', 'Lukket', 'admin'),
('norwegian', 'admin.search_tickets', 'Søk etter emne, e-post eller melding...', 'admin'),
('norwegian', 'admin.no_tickets_found', 'Ingen støttehenvendelser funnet', 'admin'),
('norwegian', 'admin.ticket_details', 'Henvendelsesdetaljer', 'admin'),
('norwegian', 'admin.send_response', 'Send svar', 'admin'),
('norwegian', 'admin.close', 'Lukk', 'admin'),
('norwegian', 'admin.unknown', 'Ukjent', 'admin'),
('norwegian', 'admin.search', 'Søk', 'admin'),
('norwegian', 'admin.subject', 'Emne', 'admin'),
('norwegian', 'admin.message', 'Melding', 'admin'),
('norwegian', 'admin.created', 'Opprettet', 'admin'),

-- German translations
('german', 'admin.email_campaigns_title', 'E-Mail-Kampagnen', 'admin'),
('german', 'admin.new_campaign', 'Neue Kampagne', 'admin'),
('german', 'admin.all_campaigns', 'Alle Kampagnen', 'admin'),
('german', 'admin.search_campaigns', 'Kampagnen suchen...', 'admin'),
('german', 'admin.no_campaigns_found', 'Keine Kampagnen gefunden', 'admin'),
('german', 'admin.campaign_name', 'Kampagnenname', 'admin'),
('german', 'admin.audience', 'Zielgruppe', 'admin'),
('german', 'admin.last_sent', 'Zuletzt gesendet', 'admin'),
('german', 'admin.next_send', 'Nächster Versand', 'admin'),
('german', 'admin.opens', 'Öffnungen', 'admin'),
('german', 'admin.clicks', 'Klicks', 'admin'),
('german', 'admin.actions', 'Aktionen', 'admin'),
('german', 'admin.duplicate', 'Duplizieren', 'admin'),
('german', 'admin.edit', 'Bearbeiten', 'admin'),
('german', 'admin.cancel', 'Abbrechen', 'admin'),
('german', 'admin.draft', 'Entwurf', 'admin'),
('german', 'admin.status', 'Status', 'admin'),

('german', 'admin.bulk_user_actions', 'Massenbenutzeraktionen', 'admin'),
('german', 'admin.import_users', 'Benutzer importieren', 'admin'),
('german', 'admin.refresh', 'Aktualisieren', 'admin'),
('german', 'admin.refreshing', 'Aktualisiere...', 'admin'),
('german', 'admin.action_history', 'Aktionsverlauf', 'admin'),
('german', 'admin.completed', 'Abgeschlossen', 'admin'),
('german', 'admin.processing', 'Verarbeitung', 'admin'),
('german', 'admin.scheduled', 'Geplant', 'admin'),
('german', 'admin.failed', 'Fehlgeschlagen', 'admin'),
('german', 'admin.job_name', 'Auftragsname', 'admin'),
('german', 'admin.type', 'Typ', 'admin'),
('german', 'admin.affected_users', 'Betroffene Benutzer', 'admin'),
('german', 'admin.created_by', 'Erstellt von', 'admin'),
('german', 'admin.view_details', 'Details anzeigen', 'admin'),
('german', 'admin.warning', 'Warnung', 'admin'),
('german', 'admin.confirm_action', 'Aktion bestätigen', 'admin'),
('german', 'admin.name', 'Name', 'admin'),
('german', 'admin.email', 'E-Mail', 'admin'),
('german', 'admin.role', 'Rolle', 'admin'),
('german', 'admin.active', 'Aktiv', 'admin'),
('german', 'admin.inactive', 'Inaktiv', 'admin'),
('german', 'admin.suspended', 'Gesperrt', 'admin'),

('german', 'admin.categories_management', 'Kategorienverwaltung', 'admin'),
('german', 'admin.add_category', 'Kategorie hinzufügen', 'admin'),
('german', 'admin.categories', 'Kategorien', 'admin'),
('german', 'admin.items', 'Elemente', 'admin'),
('german', 'admin.description', 'Beschreibung', 'admin'),
('german', 'admin.order', 'Reihenfolge', 'admin'),
('german', 'admin.updated', 'Aktualisiert', 'admin'),
('german', 'admin.all', 'Alle', 'admin'),
('german', 'admin.no_categories_found', 'Keine Kategorien gefunden', 'admin'),

('german', 'admin.ab_testing_title', 'A/B-Tests', 'admin'),
('german', 'admin.new_test', 'Neuer Test', 'admin'),
('german', 'admin.all_tests', 'Alle Tests', 'admin'),
('german', 'admin.test_name', 'Testname', 'admin'),
('german', 'admin.stop', 'Stoppen', 'admin'),
('german', 'admin.start', 'Starten', 'admin'),
('german', 'admin.stop_test', 'Test stoppen', 'admin'),

('german', 'admin.interests_management', 'Interessenverwaltung', 'admin'),
('german', 'admin.add_interest', 'Interesse hinzufügen', 'admin'),
('german', 'admin.all_interests', 'Alle Interessen', 'admin'),
('german', 'admin.search_interests', 'Interessen suchen...', 'admin'),
('german', 'admin.no_interests_found', 'Keine Interessen gefunden', 'admin'),
('german', 'admin.category', 'Kategorie', 'admin'),

('german', 'admin.comments_management', 'Kommentarverwaltung', 'admin'),
('german', 'admin.all_comment_likes', 'Alle Kommentar-Likes', 'admin'),
('german', 'admin.no_comment_likes', 'Keine Kommentar-Likes gefunden', 'admin'),

('german', 'admin.matches_management', 'Match-Verwaltung', 'admin'),
('german', 'admin.all_matches', 'Alle Matches', 'admin'),
('german', 'admin.no_matches_found', 'Keine Matches gefunden', 'admin'),

('german', 'admin.support_tickets', 'Support-Tickets', 'admin'),
('german', 'admin.total_tickets', 'Tickets gesamt', 'admin'),
('german', 'admin.open', 'Offen', 'admin'),
('german', 'admin.pending', 'Ausstehend', 'admin'),
('german', 'admin.resolved', 'Gelöst', 'admin'),
('german', 'admin.closed', 'Geschlossen', 'admin'),
('german', 'admin.no_tickets_found', 'Keine Support-Tickets gefunden', 'admin'),
('german', 'admin.send_response', 'Antwort senden', 'admin'),
('german', 'admin.close', 'Schließen', 'admin'),
('german', 'admin.unknown', 'Unbekannt', 'admin'),
('german', 'admin.search', 'Suchen', 'admin'),
('german', 'admin.subject', 'Betreff', 'admin'),
('german', 'admin.message', 'Nachricht', 'admin'),
('german', 'admin.created', 'Erstellt', 'admin'),
('german', 'admin.all_users', 'Alle Benutzer', 'admin'),

-- Kurdish Sorani
('kurdish_sorani', 'admin.email_campaigns_title', 'کامپەینەکانی ئیمەیل', 'admin'),
('kurdish_sorani', 'admin.new_campaign', 'کامپەینی نوێ', 'admin'),
('kurdish_sorani', 'admin.all_campaigns', 'هەموو کامپەینەکان', 'admin'),
('kurdish_sorani', 'admin.no_campaigns_found', 'هیچ کامپەینێک نەدۆزرایەوە', 'admin'),
('kurdish_sorani', 'admin.cancel', 'هەڵوەشاندنەوە', 'admin'),
('kurdish_sorani', 'admin.draft', 'ڕەشنووس', 'admin'),
('kurdish_sorani', 'admin.status', 'بارودۆخ', 'admin'),
('kurdish_sorani', 'admin.duplicate', 'لەبەرگرتنەوە', 'admin'),
('kurdish_sorani', 'admin.edit', 'دەستکاریکردن', 'admin'),
('kurdish_sorani', 'admin.actions', 'کردارەکان', 'admin'),

('kurdish_sorani', 'admin.bulk_user_actions', 'کردارەکانی کۆمەڵی بەکارهێنەر', 'admin'),
('kurdish_sorani', 'admin.refresh', 'نوێکردنەوە', 'admin'),
('kurdish_sorani', 'admin.completed', 'تەواوبوو', 'admin'),
('kurdish_sorani', 'admin.processing', 'لە پرۆسەدایە', 'admin'),
('kurdish_sorani', 'admin.scheduled', 'خشتەبەندکراو', 'admin'),
('kurdish_sorani', 'admin.failed', 'شکستیهێنا', 'admin'),
('kurdish_sorani', 'admin.warning', 'ئاگاداری', 'admin'),
('kurdish_sorani', 'admin.confirm_action', 'پشتڕاستکردنەوەی کردار', 'admin'),
('kurdish_sorani', 'admin.name', 'ناو', 'admin'),
('kurdish_sorani', 'admin.email', 'ئیمەیل', 'admin'),
('kurdish_sorani', 'admin.role', 'ڕۆڵ', 'admin'),
('kurdish_sorani', 'admin.active', 'چالاک', 'admin'),
('kurdish_sorani', 'admin.inactive', 'ناچالاک', 'admin'),

('kurdish_sorani', 'admin.categories_management', 'بەڕێوەبردنی پۆلەکان', 'admin'),
('kurdish_sorani', 'admin.categories', 'پۆلەکان', 'admin'),
('kurdish_sorani', 'admin.items', 'بڕگەکان', 'admin'),
('kurdish_sorani', 'admin.description', 'وەسف', 'admin'),
('kurdish_sorani', 'admin.all', 'هەموو', 'admin'),
('kurdish_sorani', 'admin.category', 'پۆل', 'admin'),

('kurdish_sorani', 'admin.ab_testing_title', 'تاقیکردنەوەی A/B', 'admin'),
('kurdish_sorani', 'admin.new_test', 'تاقیکردنەوەی نوێ', 'admin'),
('kurdish_sorani', 'admin.all_tests', 'هەموو تاقیکردنەوەکان', 'admin'),
('kurdish_sorani', 'admin.stop', 'وەستان', 'admin'),
('kurdish_sorani', 'admin.start', 'دەستپێکردن', 'admin'),

('kurdish_sorani', 'admin.interests_management', 'بەڕێوەبردنی ئارەزووەکان', 'admin'),
('kurdish_sorani', 'admin.all_interests', 'هەموو ئارەزووەکان', 'admin'),
('kurdish_sorani', 'admin.no_interests_found', 'هیچ ئارەزووێک نەدۆزرایەوە', 'admin'),

('kurdish_sorani', 'admin.comments_management', 'بەڕێوەبردنی لێدوانەکان', 'admin'),
('kurdish_sorani', 'admin.all_comment_likes', 'هەموو حەزکردنەکانی لێدوان', 'admin'),
('kurdish_sorani', 'admin.no_comment_likes', 'هیچ حەزکردنێکی لێدوان نەدۆزرایەوە', 'admin'),

('kurdish_sorani', 'admin.matches_management', 'بەڕێوەبردنی گونجانەکان', 'admin'),
('kurdish_sorani', 'admin.all_matches', 'هەموو گونجانەکان', 'admin'),
('kurdish_sorani', 'admin.no_matches_found', 'هیچ گونجانێک نەدۆزرایەوە', 'admin'),

('kurdish_sorani', 'admin.support_tickets', 'تیکەتەکانی پشتگیری', 'admin'),
('kurdish_sorani', 'admin.open', 'کراوە', 'admin'),
('kurdish_sorani', 'admin.pending', 'چاوەڕوان', 'admin'),
('kurdish_sorani', 'admin.resolved', 'چارەسەرکرا', 'admin'),
('kurdish_sorani', 'admin.closed', 'داخراو', 'admin'),
('kurdish_sorani', 'admin.no_tickets_found', 'هیچ تیکەتێک نەدۆزرایەوە', 'admin'),
('kurdish_sorani', 'admin.send_response', 'ناردنی وەڵام', 'admin'),
('kurdish_sorani', 'admin.close', 'داخستن', 'admin'),
('kurdish_sorani', 'admin.unknown', 'نەناسراو', 'admin'),
('kurdish_sorani', 'admin.search', 'گەڕان', 'admin'),
('kurdish_sorani', 'admin.subject', 'بابەت', 'admin'),
('kurdish_sorani', 'admin.message', 'پەیام', 'admin'),
('kurdish_sorani', 'admin.created', 'دروستکرا', 'admin'),

-- Kurdish Kurmanci
('kurdish_kurmanci', 'admin.email_campaigns_title', 'Kampanyayên E-nameyê', 'admin'),
('kurdish_kurmanci', 'admin.new_campaign', 'Kampanyaya Nû', 'admin'),
('kurdish_kurmanci', 'admin.all_campaigns', 'Hemû Kampanya', 'admin'),
('kurdish_kurmanci', 'admin.cancel', 'Betal kirin', 'admin'),
('kurdish_kurmanci', 'admin.draft', 'Reşnivîs', 'admin'),
('kurdish_kurmanci', 'admin.status', 'Rewş', 'admin'),
('kurdish_kurmanci', 'admin.duplicate', 'Dubare kirin', 'admin'),
('kurdish_kurmanci', 'admin.edit', 'Guhertin', 'admin'),
('kurdish_kurmanci', 'admin.actions', 'Çalakî', 'admin'),

('kurdish_kurmanci', 'admin.bulk_user_actions', 'Çalakiyên Girseyî yên Bikarhêner', 'admin'),
('kurdish_kurmanci', 'admin.refresh', 'Nûve kirin', 'admin'),
('kurdish_kurmanci', 'admin.completed', 'Qediya', 'admin'),
('kurdish_kurmanci', 'admin.processing', 'Tê pêvajo kirin', 'admin'),
('kurdish_kurmanci', 'admin.scheduled', 'Plansazkirî', 'admin'),
('kurdish_kurmanci', 'admin.failed', 'Têk çû', 'admin'),
('kurdish_kurmanci', 'admin.warning', 'Hişyarî', 'admin'),
('kurdish_kurmanci', 'admin.name', 'Nav', 'admin'),
('kurdish_kurmanci', 'admin.email', 'E-name', 'admin'),
('kurdish_kurmanci', 'admin.role', 'Rol', 'admin'),
('kurdish_kurmanci', 'admin.active', 'Çalak', 'admin'),
('kurdish_kurmanci', 'admin.inactive', 'Neçalak', 'admin'),

('kurdish_kurmanci', 'admin.categories_management', 'Birêvebirina Kategoriyan', 'admin'),
('kurdish_kurmanci', 'admin.categories', 'Kategorî', 'admin'),
('kurdish_kurmanci', 'admin.items', 'Hêman', 'admin'),
('kurdish_kurmanci', 'admin.description', 'Danasîn', 'admin'),
('kurdish_kurmanci', 'admin.all', 'Hemû', 'admin'),
('kurdish_kurmanci', 'admin.category', 'Kategorî', 'admin'),

('kurdish_kurmanci', 'admin.ab_testing_title', 'Ceribandina A/B', 'admin'),
('kurdish_kurmanci', 'admin.new_test', 'Ceribandina Nû', 'admin'),
('kurdish_kurmanci', 'admin.all_tests', 'Hemû Ceribandî', 'admin'),
('kurdish_kurmanci', 'admin.stop', 'Rawestan', 'admin'),
('kurdish_kurmanci', 'admin.start', 'Dest pê kirin', 'admin'),

('kurdish_kurmanci', 'admin.interests_management', 'Birêvebirina Eleqeyan', 'admin'),
('kurdish_kurmanci', 'admin.all_interests', 'Hemû Eleqe', 'admin'),

('kurdish_kurmanci', 'admin.comments_management', 'Birêvebirina Şîroveyan', 'admin'),
('kurdish_kurmanci', 'admin.all_comment_likes', 'Hemû Hez-kirdinên Şîrove', 'admin'),

('kurdish_kurmanci', 'admin.matches_management', 'Birêvebirina Lihevhatinan', 'admin'),
('kurdish_kurmanci', 'admin.all_matches', 'Hemû Lihevhatin', 'admin'),
('kurdish_kurmanci', 'admin.no_matches_found', 'Tu lihevhatin nehat dîtin', 'admin'),

('kurdish_kurmanci', 'admin.support_tickets', 'Bilêtên Piştgiriyê', 'admin'),
('kurdish_kurmanci', 'admin.open', 'Vekirî', 'admin'),
('kurdish_kurmanci', 'admin.pending', 'Li benda', 'admin'),
('kurdish_kurmanci', 'admin.resolved', 'Çareserkirî', 'admin'),
('kurdish_kurmanci', 'admin.closed', 'Girtî', 'admin'),
('kurdish_kurmanci', 'admin.send_response', 'Bersiv bişîne', 'admin'),
('kurdish_kurmanci', 'admin.close', 'Girtin', 'admin'),
('kurdish_kurmanci', 'admin.unknown', 'Nenas', 'admin'),
('kurdish_kurmanci', 'admin.search', 'Lêgerîn', 'admin'),
('kurdish_kurmanci', 'admin.subject', 'Mijar', 'admin'),
('kurdish_kurmanci', 'admin.message', 'Peyam', 'admin'),
('kurdish_kurmanci', 'admin.created', 'Hatiye afirandin', 'admin')
ON CONFLICT DO NOTHING;
