
-- Batch 2: FAQ content, UI strings, toasts
INSERT INTO public.app_translations (language_code, translation_key, translation_value, category, auto_translated, needs_review) VALUES
-- ===== FAQ: Getting Started =====
('english', 'help.faq.getting_started.title', 'Getting Started', 'common', false, false),
('english', 'help.faq.getting_started.description', 'New to KurdMatch? Start here', 'common', false, false),
('english', 'help.faq.getting_started.q1', 'How do I create an account?', 'common', false, false),
('english', 'help.faq.getting_started.a1', 'Download the app or visit our website, tap "Sign Up", and follow the registration process. You''ll need to provide basic information, upload photos, and verify your email.', 'common', false, false),
('english', 'help.faq.getting_started.q2', 'How does matching work?', 'common', false, false),
('english', 'help.faq.getting_started.a2', 'When you like someone and they like you back, it''s a match! You can then start chatting with each other. Swipe right to like, left to pass.', 'common', false, false),
('english', 'help.faq.getting_started.q3', 'Can I change my profile information?', 'common', false, false),
('english', 'help.faq.getting_started.a3', 'Yes! Go to your profile, tap "Edit Profile" and you can update your photos, bio, and other details at any time.', 'common', false, false),
('english', 'help.faq.getting_started.q4', 'How do I verify my profile?', 'common', false, false),
('english', 'help.faq.getting_started.a4', 'Go to Settings > Verification and follow the selfie verification process. A verified badge increases trust and match rates.', 'common', false, false),

-- ===== FAQ: Safety =====
('english', 'help.faq.safety.title', 'Safety & Privacy', 'common', false, false),
('english', 'help.faq.safety.description', 'Stay safe while dating', 'common', false, false),
('english', 'help.faq.safety.q1', 'How do I report someone?', 'common', false, false),
('english', 'help.faq.safety.a1', 'Open the user''s profile, tap the three dots menu, and select "Report". Choose a reason and provide details. We review all reports within 24 hours.', 'common', false, false),
('english', 'help.faq.safety.q2', 'How do I block someone?', 'common', false, false),
('english', 'help.faq.safety.a2', 'Open their profile, tap the three dots menu, and select "Block". They won''t be able to see your profile or contact you.', 'common', false, false),
('english', 'help.faq.safety.q3', 'Is my personal information safe?', 'common', false, false),
('english', 'help.faq.safety.a3', 'Yes, we use industry-standard encryption and never share your personal data with third parties. Your location is approximate and you control what''s visible on your profile.', 'common', false, false),
('english', 'help.faq.safety.q4', 'What safety tips should I follow?', 'common', false, false),
('english', 'help.faq.safety.a4', 'Never share financial information, meet in public places for first dates, tell a friend where you''re going, and trust your instincts. Report any suspicious behavior.', 'common', false, false),

-- ===== FAQ: Matches =====
('english', 'help.faq.matches.title', 'Matches & Messages', 'common', false, false),
('english', 'help.faq.matches.description', 'Connecting with others', 'common', false, false),
('english', 'help.faq.matches.q1', 'Why am I not getting matches?', 'common', false, false),
('english', 'help.faq.matches.a1', 'Try adding more photos, completing your profile, and being active daily. Verified profiles get more matches. Consider upgrading to Premium for more visibility.', 'common', false, false),
('english', 'help.faq.matches.q2', 'Can I unmatch someone?', 'common', false, false),
('english', 'help.faq.matches.a2', 'Yes, open the conversation, tap the profile icon, then select "Unmatch". This removes the match and deletes the conversation for both users.', 'common', false, false),
('english', 'help.faq.matches.q3', 'How do I start a conversation?', 'common', false, false),
('english', 'help.faq.matches.a3', 'After matching, open the chat and send a message. Personalized openers based on their profile work best!', 'common', false, false),
('english', 'help.faq.matches.q4', 'Can I see who liked me?', 'common', false, false),
('english', 'help.faq.matches.a4', 'Premium members can see everyone who liked them. Free users see blurred previews and can match by swiping.', 'common', false, false),

-- ===== FAQ: Subscription =====
('english', 'help.faq.subscription.title', 'Premium & Payments', 'common', false, false),
('english', 'help.faq.subscription.description', 'Subscription questions', 'common', false, false),
('english', 'help.faq.subscription.q1', 'What are the Premium benefits?', 'common', false, false),
('english', 'help.faq.subscription.a1', 'Premium includes unlimited likes, see who liked you, advanced filters, profile boost, super likes, rewind last swipe, and ad-free experience.', 'common', false, false),
('english', 'help.faq.subscription.q2', 'How do I cancel my subscription?', 'common', false, false),
('english', 'help.faq.subscription.a2', 'Go to Settings > Subscription > Manage Subscription. You can cancel anytime and keep Premium benefits until the end of your billing period.', 'common', false, false),
('english', 'help.faq.subscription.q3', 'Can I get a refund?', 'common', false, false),
('english', 'help.faq.subscription.a3', 'Refunds are handled through your app store (Apple/Google) for in-app purchases. Contact us for web purchases within 14 days of subscription.', 'common', false, false),
('english', 'help.faq.subscription.q4', 'How do I upgrade to Premium?', 'common', false, false),
('english', 'help.faq.subscription.a4', 'Tap the Premium icon or go to Settings > Subscription. Choose your plan (monthly, quarterly, or yearly) and complete the payment.', 'common', false, false),

-- ===== FAQ: Account =====
('english', 'help.faq.account.title', 'Account Settings', 'common', false, false),
('english', 'help.faq.account.description', 'Manage your account', 'common', false, false),
('english', 'help.faq.account.q1', 'How do I delete my account?', 'common', false, false),
('english', 'help.faq.account.a1', 'Go to Settings > Account > Delete Account. Note: This is permanent and all your data, matches, and messages will be deleted.', 'common', false, false),
('english', 'help.faq.account.q2', 'Can I pause my account?', 'common', false, false),
('english', 'help.faq.account.a2', 'Yes, go to Settings > Discovery and toggle "Pause Account". Your profile will be hidden but you keep your matches and messages.', 'common', false, false),
('english', 'help.faq.account.q3', 'How do I change my email/phone?', 'common', false, false),
('english', 'help.faq.account.a3', 'Go to Settings > Account to update your email or phone number. You''ll need to verify the new contact information.', 'common', false, false),
('english', 'help.faq.account.q4', 'I forgot my password', 'common', false, false),
('english', 'help.faq.account.a4', 'On the login screen, tap "Forgot Password" and enter your email. We''ll send you a reset link valid for 24 hours.', 'common', false, false),

-- ===== UI Strings =====
('english', 'stories.your_story', 'Your Story', 'common', false, false),
('english', 'discovery.likes_count', '{{count}} likes', 'common', false, false),
('english', 'discovery.like_count_one', '{{count}} like', 'common', false, false),
('english', 'discovery.more', 'more', 'common', false, false),
('english', 'discovery.view_all_comments', 'View all {{count}} comments', 'common', false, false),
('english', 'messages.new_badge', 'new', 'messages', false, false),
('english', 'messages.new_match', 'New', 'messages', false, false),
('english', 'messages.priority', 'Priority', 'messages', false, false),
('english', 'messages.unread', 'unread', 'messages', false, false),
('english', 'messages.typing', 'typing...', 'messages', false, false),
('english', 'stories.new_story', 'New Story', 'common', false, false),
('english', 'stories.photo_story', 'Photo Story', 'common', false, false),
('english', 'stories.text_story', 'Text Story', 'common', false, false),
('english', 'stories.share', 'Share', 'common', false, false),
('english', 'stories.type_your_story', 'Type your story...', 'common', false, false),
('english', 'stories.whats_on_mind', 'What''s on your mind?', 'common', false, false),
('english', 'stories.add_text_overlay', 'Add text overlay...', 'common', false, false),
('english', 'stories.camera', 'Camera', 'common', false, false),
('english', 'stories.gallery', 'Gallery', 'common', false, false),
('english', 'stories.change', 'Change', 'common', false, false),
('english', 'stories.what_kind', 'What kind of story do you want to create?', 'common', false, false),
('english', 'stories.created', 'Story created!', 'common', false, false),
('english', 'stories.failed_create', 'Failed to create story', 'common', false, false),
('english', 'stories.select_image_video', 'Please select an image or video file', 'common', false, false),
('english', 'stories.video_too_large', 'Video must be under 20MB', 'common', false, false),
('english', 'stories.enter_text', 'Please enter some text', 'common', false, false),
('english', 'stories.select_photo', 'Please select a photo or video', 'common', false, false),
('english', 'stories.file_too_large', 'Please select a file smaller than 10MB', 'common', false, false),
('english', 'stories.upload_failed', 'Failed to create story. Please try again.', 'common', false, false),
('english', 'stories.story_live', 'Your story is now live for 24 hours', 'common', false, false),
('english', 'stories.create_story', 'Create Story', 'common', false, false),
('english', 'stories.click_upload', 'Click to upload', 'common', false, false),
('english', 'stories.drag_drop', 'or drag and drop', 'common', false, false),
('english', 'stories.max_size', 'Image or Video (Max 10MB)', 'common', false, false),
('english', 'stories.uploading', 'Uploading...', 'common', false, false),
('english', 'stories.post_story', 'Post Story', 'common', false, false),

-- Groups
('english', 'groups.back_to_groups', 'Back to Groups', 'common', false, false),
('english', 'groups.create_new', 'Create New Group', 'common', false, false),
('english', 'groups.name_label', 'Group Name *', 'common', false, false),
('english', 'groups.name_placeholder', 'Enter group name', 'common', false, false),
('english', 'groups.description_label', 'Description *', 'common', false, false),
('english', 'groups.description_placeholder', 'What is this group about?', 'common', false, false),
('english', 'groups.category', 'Category', 'common', false, false),
('english', 'groups.privacy', 'Privacy', 'common', false, false),
('english', 'groups.icon_label', 'Icon (emoji)', 'common', false, false),
('english', 'groups.cover_image', 'Cover Image URL', 'common', false, false),
('english', 'groups.creating', 'Creating...', 'common', false, false),
('english', 'groups.create_group', 'Create Group', 'common', false, false),
('english', 'groups.created_success', 'Group created successfully', 'common', false, false),
('english', 'groups.create_failed', 'Failed to create group', 'common', false, false),
('english', 'groups.general', 'General', 'common', false, false),
('english', 'groups.culture', 'Culture', 'common', false, false),
('english', 'groups.language', 'Language', 'common', false, false),
('english', 'groups.events', 'Events', 'common', false, false),
('english', 'groups.hobbies', 'Hobbies', 'common', false, false),
('english', 'groups.professional', 'Professional', 'common', false, false),
('english', 'groups.public', 'Public', 'common', false, false),
('english', 'groups.private', 'Private', 'common', false, false),

-- Blocked users toasts
('english', 'blocked.load_failed', 'Failed to load blocked users', 'common', false, false),
('english', 'blocked.unblocked_success', 'User unblocked', 'common', false, false),
('english', 'blocked.unblock_failed', 'Failed to unblock user', 'common', false, false),

-- ===== NORWEGIAN =====
('norwegian', 'help.faq.getting_started.title', 'Kom i gang', 'common', true, false),
('norwegian', 'help.faq.getting_started.description', 'Ny på KurdMatch? Start her', 'common', true, false),
('norwegian', 'help.faq.getting_started.q1', 'Hvordan oppretter jeg en konto?', 'common', true, false),
('norwegian', 'help.faq.getting_started.a1', 'Last ned appen eller besøk nettsiden vår, trykk "Registrer deg" og følg registreringsprosessen. Du må oppgi grunnleggende informasjon, laste opp bilder og verifisere e-posten din.', 'common', true, false),
('norwegian', 'help.faq.getting_started.q2', 'Hvordan fungerer matching?', 'common', true, false),
('norwegian', 'help.faq.getting_started.a2', 'Når du liker noen og de liker deg tilbake, er det en match! Dere kan da begynne å chatte med hverandre. Sveip til høyre for å like, til venstre for å gå videre.', 'common', true, false),
('norwegian', 'help.faq.getting_started.q3', 'Kan jeg endre profilinformasjonen min?', 'common', true, false),
('norwegian', 'help.faq.getting_started.a3', 'Ja! Gå til profilen din, trykk "Rediger profil" og du kan oppdatere bildene, biografien og andre detaljer når som helst.', 'common', true, false),
('norwegian', 'help.faq.getting_started.q4', 'Hvordan verifiserer jeg profilen min?', 'common', true, false),
('norwegian', 'help.faq.getting_started.a4', 'Gå til Innstillinger > Verifisering og følg selfie-verifiseringsprosessen. Et verifisert merke øker tillit og matchrater.', 'common', true, false),
('norwegian', 'help.faq.safety.title', 'Sikkerhet og personvern', 'common', true, false),
('norwegian', 'help.faq.safety.description', 'Vær trygg mens du dater', 'common', true, false),
('norwegian', 'help.faq.safety.q1', 'Hvordan rapporterer jeg noen?', 'common', true, false),
('norwegian', 'help.faq.safety.a1', 'Åpne brukerens profil, trykk på trepunktsmenyen og velg "Rapporter". Velg en grunn og gi detaljer. Vi gjennomgår alle rapporter innen 24 timer.', 'common', true, false),
('norwegian', 'help.faq.safety.q2', 'Hvordan blokkerer jeg noen?', 'common', true, false),
('norwegian', 'help.faq.safety.a2', 'Åpne profilen deres, trykk på trepunktsmenyen og velg "Blokker". De vil ikke kunne se profilen din eller kontakte deg.', 'common', true, false),
('norwegian', 'help.faq.safety.q3', 'Er min personlige informasjon trygg?', 'common', true, false),
('norwegian', 'help.faq.safety.a3', 'Ja, vi bruker bransjestandardkryptering og deler aldri dine personlige data med tredjeparter. Posisjonen din er omtrentlig og du kontrollerer hva som er synlig på profilen din.', 'common', true, false),
('norwegian', 'help.faq.safety.q4', 'Hvilke sikkerhetstips bør jeg følge?', 'common', true, false),
('norwegian', 'help.faq.safety.a4', 'Del aldri finansiell informasjon, møt på offentlige steder for første date, fortell en venn hvor du skal, og stol på instinktene dine. Rapporter mistenkelig oppførsel.', 'common', true, false),
('norwegian', 'help.faq.matches.title', 'Matcher og meldinger', 'common', true, false),
('norwegian', 'help.faq.matches.description', 'Koble deg med andre', 'common', true, false),
('norwegian', 'help.faq.matches.q1', 'Hvorfor får jeg ingen matcher?', 'common', true, false),
('norwegian', 'help.faq.matches.a1', 'Prøv å legge til flere bilder, fullføre profilen din og være aktiv daglig. Verifiserte profiler får flere matcher. Vurder å oppgradere til Premium for mer synlighet.', 'common', true, false),
('norwegian', 'help.faq.matches.q2', 'Kan jeg fjerne en match?', 'common', true, false),
('norwegian', 'help.faq.matches.a2', 'Ja, åpne samtalen, trykk på profilikonet og velg "Fjern match". Dette fjerner matchen og sletter samtalen for begge brukere.', 'common', true, false),
('norwegian', 'help.faq.matches.q3', 'Hvordan starter jeg en samtale?', 'common', true, false),
('norwegian', 'help.faq.matches.a3', 'Etter matching, åpne chatten og send en melding. Personlige åpninger basert på profilen deres fungerer best!', 'common', true, false),
('norwegian', 'help.faq.matches.q4', 'Kan jeg se hvem som likte meg?', 'common', true, false),
('norwegian', 'help.faq.matches.a4', 'Premium-medlemmer kan se alle som likte dem. Gratisbrukere ser uskarpe forhåndsvisninger og kan matche ved å sveipe.', 'common', true, false),
('norwegian', 'help.faq.subscription.title', 'Premium og betalinger', 'common', true, false),
('norwegian', 'help.faq.subscription.description', 'Abonnementsspørsmål', 'common', true, false),
('norwegian', 'help.faq.subscription.q1', 'Hva er Premium-fordelene?', 'common', true, false),
('norwegian', 'help.faq.subscription.a1', 'Premium inkluderer ubegrensede likes, se hvem som likte deg, avanserte filtre, profilboost, superlikes, angre siste sveip og reklamefri opplevelse.', 'common', true, false),
('norwegian', 'help.faq.subscription.q2', 'Hvordan kansellerer jeg abonnementet mitt?', 'common', true, false),
('norwegian', 'help.faq.subscription.a2', 'Gå til Innstillinger > Abonnement > Administrer abonnement. Du kan kansellere når som helst og beholde Premium-fordelene til slutten av faktureringsperioden.', 'common', true, false),
('norwegian', 'help.faq.subscription.q3', 'Kan jeg få refusjon?', 'common', true, false),
('norwegian', 'help.faq.subscription.a3', 'Refusjoner håndteres gjennom appbutikken din (Apple/Google) for kjøp i appen. Kontakt oss for nettkjøp innen 14 dager etter abonnement.', 'common', true, false),
('norwegian', 'help.faq.subscription.q4', 'Hvordan oppgraderer jeg til Premium?', 'common', true, false),
('norwegian', 'help.faq.subscription.a4', 'Trykk på Premium-ikonet eller gå til Innstillinger > Abonnement. Velg din plan (månedlig, kvartalsvis eller årlig) og fullfør betalingen.', 'common', true, false),
('norwegian', 'help.faq.account.title', 'Kontoinnstillinger', 'common', true, false),
('norwegian', 'help.faq.account.description', 'Administrer kontoen din', 'common', true, false),
('norwegian', 'help.faq.account.q1', 'Hvordan sletter jeg kontoen min?', 'common', true, false),
('norwegian', 'help.faq.account.a1', 'Gå til Innstillinger > Konto > Slett konto. Merk: Dette er permanent og alle dine data, matcher og meldinger vil bli slettet.', 'common', true, false),
('norwegian', 'help.faq.account.q2', 'Kan jeg pause kontoen min?', 'common', true, false),
('norwegian', 'help.faq.account.a2', 'Ja, gå til Innstillinger > Oppdagelse og slå på "Pause konto". Profilen din vil bli skjult, men du beholder matchene og meldingene dine.', 'common', true, false),
('norwegian', 'help.faq.account.q3', 'Hvordan endrer jeg e-post/telefon?', 'common', true, false),
('norwegian', 'help.faq.account.a3', 'Gå til Innstillinger > Konto for å oppdatere e-post eller telefonnummer. Du må verifisere den nye kontaktinformasjonen.', 'common', true, false),
('norwegian', 'help.faq.account.q4', 'Jeg har glemt passordet mitt', 'common', true, false),
('norwegian', 'help.faq.account.a4', 'På innloggingsskjermen, trykk "Glemt passord" og skriv inn e-posten din. Vi sender deg en tilbakestillingslenke som er gyldig i 24 timer.', 'common', true, false),
('norwegian', 'stories.your_story', 'Din historie', 'common', true, false),
('norwegian', 'discovery.likes_count', '{{count}} liker', 'common', true, false),
('norwegian', 'discovery.like_count_one', '{{count}} liker', 'common', true, false),
('norwegian', 'discovery.more', 'mer', 'common', true, false),
('norwegian', 'discovery.view_all_comments', 'Se alle {{count}} kommentarer', 'common', true, false),
('norwegian', 'messages.new_badge', 'ny', 'messages', true, false),
('norwegian', 'messages.new_match', 'Ny', 'messages', true, false),
('norwegian', 'messages.priority', 'Prioritet', 'messages', true, false),
('norwegian', 'messages.unread', 'ulest', 'messages', true, false),
('norwegian', 'messages.typing', 'skriver...', 'messages', true, false),
('norwegian', 'stories.new_story', 'Ny historie', 'common', true, false),
('norwegian', 'stories.photo_story', 'Bildehistorie', 'common', true, false),
('norwegian', 'stories.text_story', 'Teksthistorie', 'common', true, false),
('norwegian', 'stories.share', 'Del', 'common', true, false),
('norwegian', 'stories.type_your_story', 'Skriv historien din...', 'common', true, false),
('norwegian', 'stories.whats_on_mind', 'Hva tenker du på?', 'common', true, false),
('norwegian', 'stories.add_text_overlay', 'Legg til tekstoverlegg...', 'common', true, false),
('norwegian', 'stories.camera', 'Kamera', 'common', true, false),
('norwegian', 'stories.gallery', 'Galleri', 'common', true, false),
('norwegian', 'stories.change', 'Endre', 'common', true, false),
('norwegian', 'stories.what_kind', 'Hva slags historie vil du lage?', 'common', true, false),
('norwegian', 'stories.created', 'Historie opprettet!', 'common', true, false),
('norwegian', 'stories.failed_create', 'Kunne ikke opprette historie', 'common', true, false),
('norwegian', 'stories.select_image_video', 'Vennligst velg et bilde eller en videofil', 'common', true, false),
('norwegian', 'stories.video_too_large', 'Videoen må være under 20MB', 'common', true, false),
('norwegian', 'stories.enter_text', 'Vennligst skriv inn tekst', 'common', true, false),
('norwegian', 'stories.select_photo', 'Vennligst velg et bilde eller en video', 'common', true, false),
('norwegian', 'stories.file_too_large', 'Vennligst velg en fil mindre enn 10MB', 'common', true, false),
('norwegian', 'stories.upload_failed', 'Kunne ikke opprette historie. Prøv igjen.', 'common', true, false),
('norwegian', 'stories.story_live', 'Historien din er nå live i 24 timer', 'common', true, false),
('norwegian', 'stories.create_story', 'Opprett historie', 'common', true, false),
('norwegian', 'stories.click_upload', 'Klikk for å laste opp', 'common', true, false),
('norwegian', 'stories.drag_drop', 'eller dra og slipp', 'common', true, false),
('norwegian', 'stories.max_size', 'Bilde eller video (Maks 10MB)', 'common', true, false),
('norwegian', 'stories.uploading', 'Laster opp...', 'common', true, false),
('norwegian', 'stories.post_story', 'Publiser historie', 'common', true, false),
('norwegian', 'groups.back_to_groups', 'Tilbake til grupper', 'common', true, false),
('norwegian', 'groups.create_new', 'Opprett ny gruppe', 'common', true, false),
('norwegian', 'groups.name_label', 'Gruppenavn *', 'common', true, false),
('norwegian', 'groups.name_placeholder', 'Skriv inn gruppenavn', 'common', true, false),
('norwegian', 'groups.description_label', 'Beskrivelse *', 'common', true, false),
('norwegian', 'groups.description_placeholder', 'Hva handler denne gruppen om?', 'common', true, false),
('norwegian', 'groups.category', 'Kategori', 'common', true, false),
('norwegian', 'groups.privacy', 'Personvern', 'common', true, false),
('norwegian', 'groups.icon_label', 'Ikon (emoji)', 'common', true, false),
('norwegian', 'groups.cover_image', 'Forsidebilde URL', 'common', true, false),
('norwegian', 'groups.creating', 'Oppretter...', 'common', true, false),
('norwegian', 'groups.create_group', 'Opprett gruppe', 'common', true, false),
('norwegian', 'groups.created_success', 'Gruppe opprettet', 'common', true, false),
('norwegian', 'groups.create_failed', 'Kunne ikke opprette gruppe', 'common', true, false),
('norwegian', 'groups.general', 'Generelt', 'common', true, false),
('norwegian', 'groups.culture', 'Kultur', 'common', true, false),
('norwegian', 'groups.language', 'Språk', 'common', true, false),
('norwegian', 'groups.events', 'Arrangementer', 'common', true, false),
('norwegian', 'groups.hobbies', 'Hobbyer', 'common', true, false),
('norwegian', 'groups.professional', 'Profesjonell', 'common', true, false),
('norwegian', 'groups.public', 'Offentlig', 'common', true, false),
('norwegian', 'groups.private', 'Privat', 'common', true, false),
('norwegian', 'blocked.load_failed', 'Kunne ikke laste blokkerte brukere', 'common', true, false),
('norwegian', 'blocked.unblocked_success', 'Bruker avblokkert', 'common', true, false),
('norwegian', 'blocked.unblock_failed', 'Kunne ikke avblokkere bruker', 'common', true, false),

-- ===== KURDISH SORANI =====
('kurdish_sorani', 'help.faq.getting_started.title', 'دەستپێکردن', 'common', true, false),
('kurdish_sorani', 'help.faq.getting_started.description', 'تازەی لە KurdMatch؟ لێرەوە دەستپێبکە', 'common', true, false),
('kurdish_sorani', 'help.faq.getting_started.q1', 'چۆن هەژمارێک دروست بکەم؟', 'common', true, false),
('kurdish_sorani', 'help.faq.getting_started.a1', 'ئەپەکە دابەزێنە یان سەردانی ماڵپەڕەکەمان بکە، لەسەر "تۆمارکردن" بگرە و ڕێکارەکانی تۆمارکردن بەتەواوی بکە.', 'common', true, false),
('kurdish_sorani', 'help.faq.getting_started.q2', 'ماتچکردن چۆن کاردەکات؟', 'common', true, false),
('kurdish_sorani', 'help.faq.getting_started.a2', 'کاتێک کەسێک حەزت لێیەتی و ئەوانیش حەزیان لێتە، ئەوا ماتچە! دەتوانیت گفتوگۆ لەگەڵیان دەستپێبکەیت.', 'common', true, false),
('kurdish_sorani', 'help.faq.getting_started.q3', 'ئایا دەتوانم زانیاری پرۆفایلەکەم بگۆڕم؟', 'common', true, false),
('kurdish_sorani', 'help.faq.getting_started.a3', 'بەڵێ! بڕۆ بۆ پرۆفایلەکەت، لەسەر "دەستکاری پرۆفایل" بگرە و دەتوانیت وێنەکانت و بایۆکەت نوێبکەیتەوە.', 'common', true, false),
('kurdish_sorani', 'help.faq.getting_started.q4', 'چۆن پرۆفایلەکەم پشتڕاستبکەمەوە؟', 'common', true, false),
('kurdish_sorani', 'help.faq.getting_started.a4', 'بڕۆ بۆ ڕێکخستنەکان > پشتڕاستکردنەوە و ڕێکارەکانی پشتڕاستکردنەوەی سێلفی بەتەواوی بکە.', 'common', true, false),
('kurdish_sorani', 'help.faq.safety.title', 'ئاسایش و تایبەتمەندی', 'common', true, false),
('kurdish_sorani', 'help.faq.safety.description', 'لە کاتی خۆشەویستیدا بە ئاسایشی بمێنەرەوە', 'common', true, false),
('kurdish_sorani', 'help.faq.safety.q1', 'چۆن کەسێک ڕاپۆرت بکەم؟', 'common', true, false),
('kurdish_sorani', 'help.faq.safety.a1', 'پرۆفایلی بەکارهێنەرەکە بکەرەوە، لەسەر مینیوی سێ خاڵ بگرە و "ڕاپۆرت" هەڵبژێرە.', 'common', true, false),
('kurdish_sorani', 'help.faq.safety.q2', 'چۆن کەسێک بلۆک بکەم؟', 'common', true, false),
('kurdish_sorani', 'help.faq.safety.a2', 'پرۆفایلەکەیان بکەرەوە، لەسەر مینیوی سێ خاڵ بگرە و "بلۆک" هەڵبژێرە.', 'common', true, false),
('kurdish_sorani', 'help.faq.safety.q3', 'ئایا زانیاری کەسیەکەم پارێزراوە؟', 'common', true, false),
('kurdish_sorani', 'help.faq.safety.a3', 'بەڵێ، ئێمە شفرەکردنی ستانداردی پیشەسازی بەکاردەهێنین و هەرگیز زانیاری کەسیەکەت لەگەڵ لایەنی سێیەم هاوبەش ناکەین.', 'common', true, false),
('kurdish_sorani', 'help.faq.safety.q4', 'چ ئامۆژگاریانی ئاسایشێک دەبێت بەتەواوی بکەم؟', 'common', true, false),
('kurdish_sorani', 'help.faq.safety.a4', 'هەرگیز زانیاری دارایی هاوبەش مەکە، لە شوێنی گشتی بۆ یەکەم بڕوانامە بچە، و ڕەفتاری گومانلێکراو ڕاپۆرت بکە.', 'common', true, false),
('kurdish_sorani', 'help.faq.matches.title', 'ماتچەکان و نامەکان', 'common', true, false),
('kurdish_sorani', 'help.faq.matches.description', 'پەیوەندیکردن لەگەڵ کەسانی تر', 'common', true, false),
('kurdish_sorani', 'help.faq.matches.q1', 'بۆچی ماتچم نییە؟', 'common', true, false),
('kurdish_sorani', 'help.faq.matches.a1', 'هەوڵبدە وێنەی زیاتر زیاد بکەیت، پرۆفایلەکەت تەواو بکەیت و ڕۆژانە چالاک بیت.', 'common', true, false),
('kurdish_sorani', 'help.faq.matches.q2', 'ئایا دەتوانم ماتچێک لابەرم؟', 'common', true, false),
('kurdish_sorani', 'help.faq.matches.a2', 'بەڵێ، گفتوگۆکە بکەرەوە، لەسەر ئایکۆنی پرۆفایل بگرە و "لابردنی ماتچ" هەڵبژێرە.', 'common', true, false),
('kurdish_sorani', 'help.faq.matches.q3', 'چۆن گفتوگۆیەک دەستپێبکەم؟', 'common', true, false),
('kurdish_sorani', 'help.faq.matches.a3', 'دوای ماتچکردن، چاتەکە بکەرەوە و نامەیەک بنێرە. دەستپێکەری تایبەت باشتر کاردەکات!', 'common', true, false),
('kurdish_sorani', 'help.faq.matches.q4', 'ئایا دەتوانم ببینم کێ حەزی لێمە؟', 'common', true, false),
('kurdish_sorani', 'help.faq.matches.a4', 'ئەندامانی پریمیۆم دەتوانن هەموو ئەو کەسانە ببینن کە حەزیان لێتە. بەکارهێنەرە خۆڕاییەکان پێشبینی تاری دەبینن.', 'common', true, false),
('kurdish_sorani', 'help.faq.subscription.title', 'پریمیۆم و پارەدانەکان', 'common', true, false),
('kurdish_sorani', 'help.faq.subscription.description', 'پرسیارەکانی بەشداریکردن', 'common', true, false),
('kurdish_sorani', 'help.faq.subscription.q1', 'سوودەکانی پریمیۆم چین؟', 'common', true, false),
('kurdish_sorani', 'help.faq.subscription.a1', 'پریمیۆم لایکی بێسنوور، بینینی کێ حەزی لێتە، فلتەری پێشکەوتوو، بووستی پرۆفایل و تجربەی بێ ڕیکلام لەخۆدەگرێت.', 'common', true, false),
('kurdish_sorani', 'help.faq.subscription.q2', 'چۆن بەشداریکردنەکەم هەڵبوەشێنمەوە؟', 'common', true, false),
('kurdish_sorani', 'help.faq.subscription.a2', 'بڕۆ بۆ ڕێکخستنەکان > بەشداریکردن > بەڕێوەبردنی بەشداریکردن.', 'common', true, false),
('kurdish_sorani', 'help.faq.subscription.q3', 'ئایا دەتوانم پارەکەم وەربگرمەوە؟', 'common', true, false),
('kurdish_sorani', 'help.faq.subscription.a3', 'گەڕاندنەوەی پارە لەڕێگەی فرۆشگای ئەپەکەت (Apple/Google) بۆ کڕینی ناو ئەپ ئەنجامدەدرێت.', 'common', true, false),
('kurdish_sorani', 'help.faq.subscription.q4', 'چۆن بۆ پریمیۆم نوێبکەمەوە؟', 'common', true, false),
('kurdish_sorani', 'help.faq.subscription.a4', 'لەسەر ئایکۆنی پریمیۆم بگرە یان بڕۆ بۆ ڕێکخستنەکان > بەشداریکردن. پلانەکەت هەڵبژێرە و پارەدانەکە تەواو بکە.', 'common', true, false),
('kurdish_sorani', 'help.faq.account.title', 'ڕێکخستنی هەژمار', 'common', true, false),
('kurdish_sorani', 'help.faq.account.description', 'بەڕێوەبردنی هەژمارەکەت', 'common', true, false),
('kurdish_sorani', 'help.faq.account.q1', 'چۆن هەژمارەکەم بسڕمەوە؟', 'common', true, false),
('kurdish_sorani', 'help.faq.account.a1', 'بڕۆ بۆ ڕێکخستنەکان > هەژمار > سڕینەوەی هەژمار. تێبینی: ئەمە هەمیشەییە و هەموو داتاکانت دەسڕدرێنەوە.', 'common', true, false),
('kurdish_sorani', 'help.faq.account.q2', 'ئایا دەتوانم هەژمارەکەم بوەستێنم؟', 'common', true, false),
('kurdish_sorani', 'help.faq.account.a2', 'بەڵێ، بڕۆ بۆ ڕێکخستنەکان > دۆزینەوە و "وەستاندنی هەژمار" چالاک بکە.', 'common', true, false),
('kurdish_sorani', 'help.faq.account.q3', 'چۆن ئیمەیل/ژمارەی تەلەفۆنەکەم بگۆڕم؟', 'common', true, false),
('kurdish_sorani', 'help.faq.account.a3', 'بڕۆ بۆ ڕێکخستنەکان > هەژمار بۆ نوێکردنەوەی ئیمەیل یان ژمارەی تەلەفۆن.', 'common', true, false),
('kurdish_sorani', 'help.faq.account.q4', 'وشەی نهێنیم بیرچووەتەوە', 'common', true, false),
('kurdish_sorani', 'help.faq.account.a4', 'لە شاشەی چوونەژوورەوە، لەسەر "وشەی نهێنی بیرچووەتەوە" بگرە و ئیمەیلەکەت بنووسە.', 'common', true, false),
('kurdish_sorani', 'stories.your_story', 'چیرۆکەکەت', 'common', true, false),
('kurdish_sorani', 'discovery.likes_count', '{{count}} حەز', 'common', true, false),
('kurdish_sorani', 'discovery.like_count_one', '{{count}} حەز', 'common', true, false),
('kurdish_sorani', 'discovery.more', 'زیاتر', 'common', true, false),
('kurdish_sorani', 'discovery.view_all_comments', 'بینینی هەموو {{count}} لێدوان', 'common', true, false),
('kurdish_sorani', 'messages.new_badge', 'نوێ', 'messages', true, false),
('kurdish_sorani', 'messages.new_match', 'نوێ', 'messages', true, false),
('kurdish_sorani', 'messages.priority', 'گرنگ', 'messages', true, false),
('kurdish_sorani', 'messages.unread', 'نەخوێندراو', 'messages', true, false),
('kurdish_sorani', 'messages.typing', 'دەنووسێت...', 'messages', true, false),
('kurdish_sorani', 'stories.new_story', 'چیرۆکی نوێ', 'common', true, false),
('kurdish_sorani', 'stories.photo_story', 'چیرۆکی وێنە', 'common', true, false),
('kurdish_sorani', 'stories.text_story', 'چیرۆکی تێکست', 'common', true, false),
('kurdish_sorani', 'stories.share', 'هاوبەشکردن', 'common', true, false),
('kurdish_sorani', 'stories.type_your_story', 'چیرۆکەکەت بنووسە...', 'common', true, false),
('kurdish_sorani', 'stories.whats_on_mind', 'چی لە مێشکتدایە؟', 'common', true, false),
('kurdish_sorani', 'stories.add_text_overlay', 'تێکست زیاد بکە...', 'common', true, false),
('kurdish_sorani', 'stories.camera', 'کامێرا', 'common', true, false),
('kurdish_sorani', 'stories.gallery', 'گالەری', 'common', true, false),
('kurdish_sorani', 'stories.change', 'گۆڕین', 'common', true, false),
('kurdish_sorani', 'stories.what_kind', 'چ جۆرە چیرۆکێک دەتەوێت دروست بکەیت؟', 'common', true, false),
('kurdish_sorani', 'stories.created', 'چیرۆک دروستکرا!', 'common', true, false),
('kurdish_sorani', 'stories.failed_create', 'دروستکردنی چیرۆک سەرکەوتوو نەبوو', 'common', true, false),
('kurdish_sorani', 'stories.select_image_video', 'تکایە وێنە یان ڤیدیۆ هەڵبژێرە', 'common', true, false),
('kurdish_sorani', 'stories.video_too_large', 'ڤیدیۆ دەبێت لە 20MB کەمتر بێت', 'common', true, false),
('kurdish_sorani', 'stories.enter_text', 'تکایە تێکست بنووسە', 'common', true, false),
('kurdish_sorani', 'stories.select_photo', 'تکایە وێنە یان ڤیدیۆ هەڵبژێرە', 'common', true, false),
('kurdish_sorani', 'stories.file_too_large', 'تکایە فایلێک کەمتر لە 10MB هەڵبژێرە', 'common', true, false),
('kurdish_sorani', 'stories.upload_failed', 'دروستکردنی چیرۆک سەرکەوتوو نەبوو. دووبارە هەوڵبدەرەوە.', 'common', true, false),
('kurdish_sorani', 'stories.story_live', 'چیرۆکەکەت ئێستا بۆ 24 کاتژمێر زیندووە', 'common', true, false),
('kurdish_sorani', 'stories.create_story', 'دروستکردنی چیرۆک', 'common', true, false),
('kurdish_sorani', 'stories.click_upload', 'کلیک بکە بۆ بارکردن', 'common', true, false),
('kurdish_sorani', 'stories.drag_drop', 'یان ڕاکێشە و بەردە', 'common', true, false),
('kurdish_sorani', 'stories.max_size', 'وێنە یان ڤیدیۆ (زۆرینە 10MB)', 'common', true, false),
('kurdish_sorani', 'stories.uploading', 'باردەکرێت...', 'common', true, false),
('kurdish_sorani', 'stories.post_story', 'بڵاوکردنەوەی چیرۆک', 'common', true, false),
('kurdish_sorani', 'groups.back_to_groups', 'گەڕانەوە بۆ گروپەکان', 'common', true, false),
('kurdish_sorani', 'groups.create_new', 'دروستکردنی گروپی نوێ', 'common', true, false),
('kurdish_sorani', 'groups.name_label', 'ناوی گروپ *', 'common', true, false),
('kurdish_sorani', 'groups.name_placeholder', 'ناوی گروپ بنووسە', 'common', true, false),
('kurdish_sorani', 'groups.description_label', 'وەسف *', 'common', true, false),
('kurdish_sorani', 'groups.description_placeholder', 'ئەم گروپە سەبارەت بە چییە؟', 'common', true, false),
('kurdish_sorani', 'groups.category', 'پۆل', 'common', true, false),
('kurdish_sorani', 'groups.privacy', 'تایبەتمەندی', 'common', true, false),
('kurdish_sorani', 'groups.icon_label', 'ئایکۆن (ئیمۆجی)', 'common', true, false),
('kurdish_sorani', 'groups.cover_image', 'لینکی وێنەی بەرگ', 'common', true, false),
('kurdish_sorani', 'groups.creating', 'دروستدەکرێت...', 'common', true, false),
('kurdish_sorani', 'groups.create_group', 'دروستکردنی گروپ', 'common', true, false),
('kurdish_sorani', 'groups.created_success', 'گروپ بە سەرکەوتوویی دروستکرا', 'common', true, false),
('kurdish_sorani', 'groups.create_failed', 'دروستکردنی گروپ سەرکەوتوو نەبوو', 'common', true, false),
('kurdish_sorani', 'groups.general', 'گشتی', 'common', true, false),
('kurdish_sorani', 'groups.culture', 'کەلتوور', 'common', true, false),
('kurdish_sorani', 'groups.language', 'زمان', 'common', true, false),
('kurdish_sorani', 'groups.events', 'بۆنەکان', 'common', true, false),
('kurdish_sorani', 'groups.hobbies', 'ئارەزووەکان', 'common', true, false),
('kurdish_sorani', 'groups.professional', 'پیشەیی', 'common', true, false),
('kurdish_sorani', 'groups.public', 'گشتی', 'common', true, false),
('kurdish_sorani', 'groups.private', 'تایبەت', 'common', true, false),
('kurdish_sorani', 'blocked.load_failed', 'نەتوانرا بەکارهێنەرە بلۆککراوەکان بار بکرێت', 'common', true, false),
('kurdish_sorani', 'blocked.unblocked_success', 'بەکارهێنەر بلۆک لێکرایەوە', 'common', true, false),
('kurdish_sorani', 'blocked.unblock_failed', 'نەتوانرا بلۆک لە بەکارهێنەر لابەرێت', 'common', true, false),

-- ===== KURDISH KURMANCI =====
('kurdish_kurmanci', 'help.faq.getting_started.title', 'Destpêkirin', 'common', true, false),
('kurdish_kurmanci', 'help.faq.getting_started.description', 'Nû li KurdMatch? Li vir dest pê bike', 'common', true, false),
('kurdish_kurmanci', 'help.faq.getting_started.q1', 'Ez çawa hesabek çêbikim?', 'common', true, false),
('kurdish_kurmanci', 'help.faq.getting_started.a1', 'Serlêdanê daxîne an serdana malpera me bike, li ser "Tomar bibe" bitikîne û pêvajoya tomarkirinê bişopîne.', 'common', true, false),
('kurdish_kurmanci', 'help.faq.getting_started.q2', 'Lihevhatin çawa dixebite?', 'common', true, false),
('kurdish_kurmanci', 'help.faq.getting_started.a2', 'Dema tu yekî hez dikî û ew jî te hez dikin, ew lihevhatin e! Tu dikarî dest bi sohbetê bikî.', 'common', true, false),
('kurdish_kurmanci', 'help.faq.getting_started.q3', 'Ma ez dikarim agahiyên profîla xwe biguherînim?', 'common', true, false),
('kurdish_kurmanci', 'help.faq.getting_started.a3', 'Erê! Biçe profîla xwe, li ser "Profîlê biguherîne" bitikîne û tu dikarî wêne û biyografiya xwe nû bikî.', 'common', true, false),
('kurdish_kurmanci', 'help.faq.getting_started.q4', 'Ez çawa profîla xwe piştrastbikim?', 'common', true, false),
('kurdish_kurmanci', 'help.faq.getting_started.a4', 'Biçe Mîheng > Piştrastkirin û pêvajoya piştrastkirina selfiyê bişopîne.', 'common', true, false),
('kurdish_kurmanci', 'help.faq.safety.title', 'Ewlehî û Nepenî', 'common', true, false),
('kurdish_kurmanci', 'help.faq.safety.description', 'Di dema hezkirinê de ewle bimîne', 'common', true, false),
('kurdish_kurmanci', 'help.faq.safety.q1', 'Ez çawa kesekî rapor bikim?', 'common', true, false),
('kurdish_kurmanci', 'help.faq.safety.a1', 'Profîla bikarhêner veke, li ser menuya sê xalan bitikîne û "Rapor bike" hilbijêre.', 'common', true, false),
('kurdish_kurmanci', 'help.faq.safety.q2', 'Ez çawa kesekî blok bikim?', 'common', true, false),
('kurdish_kurmanci', 'help.faq.safety.a2', 'Profîla wan veke, li ser menuya sê xalan bitikîne û "Blok bike" hilbijêre.', 'common', true, false),
('kurdish_kurmanci', 'help.faq.safety.q3', 'Ma agahiyên min ên kesane ewle ne?', 'common', true, false),
('kurdish_kurmanci', 'help.faq.safety.a3', 'Erê, em şîfrekirina standard a pîşesaziyê bikar tînin û tu carî daneyên te yên kesane bi aliyên sêyemîn re parve nakin.', 'common', true, false),
('kurdish_kurmanci', 'help.faq.safety.q4', 'Divê ez çi şîretên ewlehiyê bişopînim?', 'common', true, false),
('kurdish_kurmanci', 'help.faq.safety.a4', 'Tu carî agahiyên darayî parve neke, li cihên giştî hevdu bibîne, û tevgerên gumanbar rapor bike.', 'common', true, false),
('kurdish_kurmanci', 'help.faq.matches.title', 'Lihevhatin û Peyam', 'common', true, false),
('kurdish_kurmanci', 'help.faq.matches.description', 'Bi kesên din re têkilî daynin', 'common', true, false),
('kurdish_kurmanci', 'help.faq.matches.q1', 'Çima ez lihevhatinan nabînim?', 'common', true, false),
('kurdish_kurmanci', 'help.faq.matches.a1', 'Biceribîne bêtir wêne zêde bike, profîla xwe temam bike û rojane çalak be.', 'common', true, false),
('kurdish_kurmanci', 'help.faq.matches.q2', 'Ma ez dikarim lihevhatinekê rakîm?', 'common', true, false),
('kurdish_kurmanci', 'help.faq.matches.a2', 'Erê, sohbetê veke, li ser îkona profîlê bitikîne û "Lihevhatinê rake" hilbijêre.', 'common', true, false),
('kurdish_kurmanci', 'help.faq.matches.q3', 'Ez çawa sohbetê dest pê bikim?', 'common', true, false),
('kurdish_kurmanci', 'help.faq.matches.a3', 'Piştî lihevhatinê, sohbetê veke û peyamek bişîne. Destpêkên taybet baştir dixebitin!', 'common', true, false),
('kurdish_kurmanci', 'help.faq.matches.q4', 'Ma ez dikarim bibînim kê min hez kiriye?', 'common', true, false),
('kurdish_kurmanci', 'help.faq.matches.a4', 'Endamên Premium dikarin hemû kesên ku wan hez kirine bibînin.', 'common', true, false),
('kurdish_kurmanci', 'help.faq.subscription.title', 'Premium û Dayîn', 'common', true, false),
('kurdish_kurmanci', 'help.faq.subscription.description', 'Pirsên abonetiyê', 'common', true, false),
('kurdish_kurmanci', 'help.faq.subscription.q1', 'Feydeyên Premium çi ne?', 'common', true, false),
('kurdish_kurmanci', 'help.faq.subscription.a1', 'Premium heskirinên bêsînor, bibîne kê te hez kiriye, fîlterên pêşketî, û ezmûna bê reklam pêk tîne.', 'common', true, false),
('kurdish_kurmanci', 'help.faq.subscription.q2', 'Ez çawa abonetiya xwe betal bikim?', 'common', true, false),
('kurdish_kurmanci', 'help.faq.subscription.a2', 'Biçe Mîheng > Abonekirinê > Birêvebirina Abonekirinê. Tu dikarî her dem betal bikî.', 'common', true, false),
('kurdish_kurmanci', 'help.faq.subscription.q3', 'Ma ez dikarim vegerandinek bistînim?', 'common', true, false),
('kurdish_kurmanci', 'help.faq.subscription.a3', 'Vegerandin bi navgîniya firotgeha serlêdanê (Apple/Google) tê çêkirin.', 'common', true, false),
('kurdish_kurmanci', 'help.faq.subscription.q4', 'Ez çawa bo Premium nûbikim?', 'common', true, false),
('kurdish_kurmanci', 'help.faq.subscription.a4', 'Li ser îkona Premium bitikîne an biçe Mîheng > Abonekirinê. Plana xwe hilbijêre û dayînê temam bike.', 'common', true, false),
('kurdish_kurmanci', 'help.faq.account.title', 'Mîhengên Hesab', 'common', true, false),
('kurdish_kurmanci', 'help.faq.account.description', 'Hesabê xwe birêve bibe', 'common', true, false),
('kurdish_kurmanci', 'help.faq.account.q1', 'Ez çawa hesabê xwe jê bikim?', 'common', true, false),
('kurdish_kurmanci', 'help.faq.account.a1', 'Biçe Mîheng > Hesab > Hesab Jêbike. Baldar: Ev domdar e û hemû daneyên te têne jêbirin.', 'common', true, false),
('kurdish_kurmanci', 'help.faq.account.q2', 'Ma ez dikarim hesabê xwe bisekinînim?', 'common', true, false),
('kurdish_kurmanci', 'help.faq.account.a2', 'Erê, biçe Mîheng > Vedîtin û "Hesab Bisekinîne" çalak bike.', 'common', true, false),
('kurdish_kurmanci', 'help.faq.account.q3', 'Ez çawa e-peyam/telefona xwe biguherînim?', 'common', true, false),
('kurdish_kurmanci', 'help.faq.account.a3', 'Biçe Mîheng > Hesab ji bo nûkirina e-peyam an jimara telefonê.', 'common', true, false),
('kurdish_kurmanci', 'help.faq.account.q4', 'Min şîfreya xwe ji bîr kiriye', 'common', true, false),
('kurdish_kurmanci', 'help.faq.account.a4', 'Li ser dîmena têketinê, li ser "Şîfre ji bîr kir" bitikîne û e-peyama xwe binivîse.', 'common', true, false),
('kurdish_kurmanci', 'stories.your_story', 'Çîroka te', 'common', true, false),
('kurdish_kurmanci', 'discovery.likes_count', '{{count}} hez', 'common', true, false),
('kurdish_kurmanci', 'discovery.like_count_one', '{{count}} hez', 'common', true, false),
('kurdish_kurmanci', 'discovery.more', 'bêtir', 'common', true, false),
('kurdish_kurmanci', 'discovery.view_all_comments', 'Hemû {{count}} şîroveyan bibîne', 'common', true, false),
('kurdish_kurmanci', 'messages.new_badge', 'nû', 'messages', true, false),
('kurdish_kurmanci', 'messages.new_match', 'Nû', 'messages', true, false),
('kurdish_kurmanci', 'messages.priority', 'Girîng', 'messages', true, false),
('kurdish_kurmanci', 'messages.unread', 'nexwendî', 'messages', true, false),
('kurdish_kurmanci', 'messages.typing', 'dinivîse...', 'messages', true, false),
('kurdish_kurmanci', 'stories.new_story', 'Çîroka nû', 'common', true, false),
('kurdish_kurmanci', 'stories.photo_story', 'Çîroka wêneyî', 'common', true, false),
('kurdish_kurmanci', 'stories.text_story', 'Çîroka nivîsê', 'common', true, false),
('kurdish_kurmanci', 'stories.share', 'Parve bike', 'common', true, false),
('kurdish_kurmanci', 'stories.type_your_story', 'Çîroka xwe binivîse...', 'common', true, false),
('kurdish_kurmanci', 'stories.whats_on_mind', 'Çi di serê te de ye?', 'common', true, false),
('kurdish_kurmanci', 'stories.add_text_overlay', 'Nivîs lê zêde bike...', 'common', true, false),
('kurdish_kurmanci', 'stories.camera', 'Kamera', 'common', true, false),
('kurdish_kurmanci', 'stories.gallery', 'Galerî', 'common', true, false),
('kurdish_kurmanci', 'stories.change', 'Biguherîne', 'common', true, false),
('kurdish_kurmanci', 'stories.what_kind', 'Tu dixwazî çi cûre çîrokek çêbikî?', 'common', true, false),
('kurdish_kurmanci', 'stories.created', 'Çîrok hat çêkirin!', 'common', true, false),
('kurdish_kurmanci', 'stories.failed_create', 'Çêkirina çîrokê bi ser neket', 'common', true, false),
('kurdish_kurmanci', 'stories.select_image_video', 'Ji kerema xwe wêne an vîdyoyek hilbijêre', 'common', true, false),
('kurdish_kurmanci', 'stories.video_too_large', 'Divê vîdyo ji 20MB kêmtir be', 'common', true, false),
('kurdish_kurmanci', 'stories.enter_text', 'Ji kerema xwe nivîsek binivîse', 'common', true, false),
('kurdish_kurmanci', 'stories.select_photo', 'Ji kerema xwe wêne an vîdyoyek hilbijêre', 'common', true, false),
('kurdish_kurmanci', 'stories.file_too_large', 'Ji kerema xwe pelê kêmtir ji 10MB hilbijêre', 'common', true, false),
('kurdish_kurmanci', 'stories.upload_failed', 'Çêkirina çîrokê bi ser neket. Ji kerema xwe dîsa biceribîne.', 'common', true, false),
('kurdish_kurmanci', 'stories.story_live', 'Çîroka te niha ji bo 24 saetan zindî ye', 'common', true, false),
('kurdish_kurmanci', 'stories.create_story', 'Çîrok çêbike', 'common', true, false),
('kurdish_kurmanci', 'stories.click_upload', 'Ji bo barkirin bitikîne', 'common', true, false),
('kurdish_kurmanci', 'stories.drag_drop', 'an bikişîne û berde', 'common', true, false),
('kurdish_kurmanci', 'stories.max_size', 'Wêne an Vîdyo (Zêdetirîn 10MB)', 'common', true, false),
('kurdish_kurmanci', 'stories.uploading', 'Tê barkirin...', 'common', true, false),
('kurdish_kurmanci', 'stories.post_story', 'Çîrokê weşîne', 'common', true, false),
('kurdish_kurmanci', 'groups.back_to_groups', 'Vegere grûpan', 'common', true, false),
('kurdish_kurmanci', 'groups.create_new', 'Grûpa nû çêbike', 'common', true, false),
('kurdish_kurmanci', 'groups.name_label', 'Navê grûpê *', 'common', true, false),
('kurdish_kurmanci', 'groups.name_placeholder', 'Navê grûpê binivîse', 'common', true, false),
('kurdish_kurmanci', 'groups.description_label', 'Danasîn *', 'common', true, false),
('kurdish_kurmanci', 'groups.description_placeholder', 'Ev grûp li ser çi ye?', 'common', true, false),
('kurdish_kurmanci', 'groups.category', 'Beş', 'common', true, false),
('kurdish_kurmanci', 'groups.privacy', 'Nepenî', 'common', true, false),
('kurdish_kurmanci', 'groups.icon_label', 'Îkon (emojî)', 'common', true, false),
('kurdish_kurmanci', 'groups.cover_image', 'URL-ya wêneya bergê', 'common', true, false),
('kurdish_kurmanci', 'groups.creating', 'Tê çêkirin...', 'common', true, false),
('kurdish_kurmanci', 'groups.create_group', 'Grûp çêbike', 'common', true, false),
('kurdish_kurmanci', 'groups.created_success', 'Grûp bi serkeftî hat çêkirin', 'common', true, false),
('kurdish_kurmanci', 'groups.create_failed', 'Çêkirina grûpê bi ser neket', 'common', true, false),
('kurdish_kurmanci', 'groups.general', 'Giştî', 'common', true, false),
('kurdish_kurmanci', 'groups.culture', 'Çand', 'common', true, false),
('kurdish_kurmanci', 'groups.language', 'Ziman', 'common', true, false),
('kurdish_kurmanci', 'groups.events', 'Bûyer', 'common', true, false),
('kurdish_kurmanci', 'groups.hobbies', 'Hobî', 'common', true, false),
('kurdish_kurmanci', 'groups.professional', 'Profesyonel', 'common', true, false),
('kurdish_kurmanci', 'groups.public', 'Giştî', 'common', true, false),
('kurdish_kurmanci', 'groups.private', 'Taybet', 'common', true, false),
('kurdish_kurmanci', 'blocked.load_failed', 'Bar kirina bikarhênerên blokkirî bi ser neket', 'common', true, false),
('kurdish_kurmanci', 'blocked.unblocked_success', 'Bikarhêner hat blokdan', 'common', true, false),
('kurdish_kurmanci', 'blocked.unblock_failed', 'Rakirina blokê bi ser neket', 'common', true, false),

-- ===== GERMAN =====
('german', 'help.faq.getting_started.title', 'Erste Schritte', 'common', true, false),
('german', 'help.faq.getting_started.description', 'Neu bei KurdMatch? Starte hier', 'common', true, false),
('german', 'help.faq.getting_started.q1', 'Wie erstelle ich ein Konto?', 'common', true, false),
('german', 'help.faq.getting_started.a1', 'Lade die App herunter oder besuche unsere Website, tippe auf "Registrieren" und folge dem Registrierungsprozess.', 'common', true, false),
('german', 'help.faq.getting_started.q2', 'Wie funktioniert das Matching?', 'common', true, false),
('german', 'help.faq.getting_started.a2', 'Wenn du jemanden magst und er/sie dich zurück mag, ist es ein Match! Ihr könnt dann miteinander chatten.', 'common', true, false),
('german', 'help.faq.getting_started.q3', 'Kann ich meine Profilinformationen ändern?', 'common', true, false),
('german', 'help.faq.getting_started.a3', 'Ja! Gehe zu deinem Profil, tippe auf "Profil bearbeiten" und du kannst deine Fotos, Bio und andere Details jederzeit aktualisieren.', 'common', true, false),
('german', 'help.faq.getting_started.q4', 'Wie verifiziere ich mein Profil?', 'common', true, false),
('german', 'help.faq.getting_started.a4', 'Gehe zu Einstellungen > Verifizierung und folge dem Selfie-Verifizierungsprozess.', 'common', true, false),
('german', 'help.faq.safety.title', 'Sicherheit & Datenschutz', 'common', true, false),
('german', 'help.faq.safety.description', 'Bleib sicher beim Daten', 'common', true, false),
('german', 'help.faq.safety.q1', 'Wie melde ich jemanden?', 'common', true, false),
('german', 'help.faq.safety.a1', 'Öffne das Profil des Benutzers, tippe auf das Drei-Punkte-Menü und wähle "Melden".', 'common', true, false),
('german', 'help.faq.safety.q2', 'Wie blockiere ich jemanden?', 'common', true, false),
('german', 'help.faq.safety.a2', 'Öffne ihr Profil, tippe auf das Drei-Punkte-Menü und wähle "Blockieren".', 'common', true, false),
('german', 'help.faq.safety.q3', 'Sind meine persönlichen Informationen sicher?', 'common', true, false),
('german', 'help.faq.safety.a3', 'Ja, wir verwenden branchenübliche Verschlüsselung und teilen niemals deine persönlichen Daten mit Dritten.', 'common', true, false),
('german', 'help.faq.safety.q4', 'Welche Sicherheitstipps sollte ich befolgen?', 'common', true, false),
('german', 'help.faq.safety.a4', 'Teile niemals Finanzinformationen, triff dich an öffentlichen Orten, und melde verdächtiges Verhalten.', 'common', true, false),
('german', 'help.faq.matches.title', 'Matches & Nachrichten', 'common', true, false),
('german', 'help.faq.matches.description', 'Mit anderen verbinden', 'common', true, false),
('german', 'help.faq.matches.q1', 'Warum bekomme ich keine Matches?', 'common', true, false),
('german', 'help.faq.matches.a1', 'Versuche mehr Fotos hinzuzufügen, dein Profil zu vervollständigen und täglich aktiv zu sein.', 'common', true, false),
('german', 'help.faq.matches.q2', 'Kann ich ein Match aufheben?', 'common', true, false),
('german', 'help.faq.matches.a2', 'Ja, öffne die Unterhaltung, tippe auf das Profilsymbol und wähle "Match aufheben".', 'common', true, false),
('german', 'help.faq.matches.q3', 'Wie starte ich eine Unterhaltung?', 'common', true, false),
('german', 'help.faq.matches.a3', 'Nach dem Match öffne den Chat und sende eine Nachricht. Personalisierte Eröffnungen funktionieren am besten!', 'common', true, false),
('german', 'help.faq.matches.q4', 'Kann ich sehen, wer mich geliked hat?', 'common', true, false),
('german', 'help.faq.matches.a4', 'Premium-Mitglieder können alle sehen, die sie geliked haben. Kostenlose Benutzer sehen verschwommene Vorschauen.', 'common', true, false),
('german', 'help.faq.subscription.title', 'Premium & Zahlungen', 'common', true, false),
('german', 'help.faq.subscription.description', 'Abo-Fragen', 'common', true, false),
('german', 'help.faq.subscription.q1', 'Was sind die Premium-Vorteile?', 'common', true, false),
('german', 'help.faq.subscription.a1', 'Premium beinhaltet unbegrenzte Likes, sehen wer dich geliked hat, erweiterte Filter, Profil-Boost und werbefreies Erlebnis.', 'common', true, false),
('german', 'help.faq.subscription.q2', 'Wie kündige ich mein Abo?', 'common', true, false),
('german', 'help.faq.subscription.a2', 'Gehe zu Einstellungen > Abo > Abo verwalten. Du kannst jederzeit kündigen.', 'common', true, false),
('german', 'help.faq.subscription.q3', 'Kann ich eine Rückerstattung erhalten?', 'common', true, false),
('german', 'help.faq.subscription.a3', 'Rückerstattungen werden über deinen App Store (Apple/Google) für In-App-Käufe abgewickelt.', 'common', true, false),
('german', 'help.faq.subscription.q4', 'Wie upgrade ich auf Premium?', 'common', true, false),
('german', 'help.faq.subscription.a4', 'Tippe auf das Premium-Symbol oder gehe zu Einstellungen > Abo. Wähle deinen Plan und schließe die Zahlung ab.', 'common', true, false),
('german', 'help.faq.account.title', 'Kontoeinstellungen', 'common', true, false),
('german', 'help.faq.account.description', 'Verwalte dein Konto', 'common', true, false),
('german', 'help.faq.account.q1', 'Wie lösche ich mein Konto?', 'common', true, false),
('german', 'help.faq.account.a1', 'Gehe zu Einstellungen > Konto > Konto löschen. Hinweis: Dies ist dauerhaft.', 'common', true, false),
('german', 'help.faq.account.q2', 'Kann ich mein Konto pausieren?', 'common', true, false),
('german', 'help.faq.account.a2', 'Ja, gehe zu Einstellungen > Entdecken und schalte "Konto pausieren" ein.', 'common', true, false),
('german', 'help.faq.account.q3', 'Wie ändere ich meine E-Mail/Telefonnummer?', 'common', true, false),
('german', 'help.faq.account.a3', 'Gehe zu Einstellungen > Konto, um deine E-Mail oder Telefonnummer zu aktualisieren.', 'common', true, false),
('german', 'help.faq.account.q4', 'Ich habe mein Passwort vergessen', 'common', true, false),
('german', 'help.faq.account.a4', 'Tippe auf dem Anmeldebildschirm auf "Passwort vergessen" und gib deine E-Mail ein.', 'common', true, false),
('german', 'stories.your_story', 'Deine Story', 'common', true, false),
('german', 'discovery.likes_count', '{{count}} Gefällt mir', 'common', true, false),
('german', 'discovery.like_count_one', '{{count}} Gefällt mir', 'common', true, false),
('german', 'discovery.more', 'mehr', 'common', true, false),
('german', 'discovery.view_all_comments', 'Alle {{count}} Kommentare ansehen', 'common', true, false),
('german', 'messages.new_badge', 'neu', 'messages', true, false),
('german', 'messages.new_match', 'Neu', 'messages', true, false),
('german', 'messages.priority', 'Priorität', 'messages', true, false),
('german', 'messages.unread', 'ungelesen', 'messages', true, false),
('german', 'messages.typing', 'tippt...', 'messages', true, false),
('german', 'stories.new_story', 'Neue Story', 'common', true, false),
('german', 'stories.photo_story', 'Foto-Story', 'common', true, false),
('german', 'stories.text_story', 'Text-Story', 'common', true, false),
('german', 'stories.share', 'Teilen', 'common', true, false),
('german', 'stories.type_your_story', 'Schreibe deine Story...', 'common', true, false),
('german', 'stories.whats_on_mind', 'Was denkst du?', 'common', true, false),
('german', 'stories.add_text_overlay', 'Text hinzufügen...', 'common', true, false),
('german', 'stories.camera', 'Kamera', 'common', true, false),
('german', 'stories.gallery', 'Galerie', 'common', true, false),
('german', 'stories.change', 'Ändern', 'common', true, false),
('german', 'stories.what_kind', 'Welche Art von Story möchtest du erstellen?', 'common', true, false),
('german', 'stories.created', 'Story erstellt!', 'common', true, false),
('german', 'stories.failed_create', 'Story konnte nicht erstellt werden', 'common', true, false),
('german', 'stories.select_image_video', 'Bitte wähle ein Bild oder Video', 'common', true, false),
('german', 'stories.video_too_large', 'Video muss unter 20MB sein', 'common', true, false),
('german', 'stories.enter_text', 'Bitte gib Text ein', 'common', true, false),
('german', 'stories.select_photo', 'Bitte wähle ein Foto oder Video', 'common', true, false),
('german', 'stories.file_too_large', 'Bitte wähle eine Datei unter 10MB', 'common', true, false),
('german', 'stories.upload_failed', 'Story konnte nicht erstellt werden. Bitte versuche es erneut.', 'common', true, false),
('german', 'stories.story_live', 'Deine Story ist jetzt 24 Stunden live', 'common', true, false),
('german', 'stories.create_story', 'Story erstellen', 'common', true, false),
('german', 'stories.click_upload', 'Klicke zum Hochladen', 'common', true, false),
('german', 'stories.drag_drop', 'oder per Drag & Drop', 'common', true, false),
('german', 'stories.max_size', 'Bild oder Video (Max 10MB)', 'common', true, false),
('german', 'stories.uploading', 'Wird hochgeladen...', 'common', true, false),
('german', 'stories.post_story', 'Story posten', 'common', true, false),
('german', 'groups.back_to_groups', 'Zurück zu Gruppen', 'common', true, false),
('german', 'groups.create_new', 'Neue Gruppe erstellen', 'common', true, false),
('german', 'groups.name_label', 'Gruppenname *', 'common', true, false),
('german', 'groups.name_placeholder', 'Gruppenname eingeben', 'common', true, false),
('german', 'groups.description_label', 'Beschreibung *', 'common', true, false),
('german', 'groups.description_placeholder', 'Worum geht es in dieser Gruppe?', 'common', true, false),
('german', 'groups.category', 'Kategorie', 'common', true, false),
('german', 'groups.privacy', 'Datenschutz', 'common', true, false),
('german', 'groups.icon_label', 'Symbol (Emoji)', 'common', true, false),
('german', 'groups.cover_image', 'Titelbild-URL', 'common', true, false),
('german', 'groups.creating', 'Wird erstellt...', 'common', true, false),
('german', 'groups.create_group', 'Gruppe erstellen', 'common', true, false),
('german', 'groups.created_success', 'Gruppe erfolgreich erstellt', 'common', true, false),
('german', 'groups.create_failed', 'Gruppe konnte nicht erstellt werden', 'common', true, false),
('german', 'groups.general', 'Allgemein', 'common', true, false),
('german', 'groups.culture', 'Kultur', 'common', true, false),
('german', 'groups.language', 'Sprache', 'common', true, false),
('german', 'groups.events', 'Veranstaltungen', 'common', true, false),
('german', 'groups.hobbies', 'Hobbys', 'common', true, false),
('german', 'groups.professional', 'Beruflich', 'common', true, false),
('german', 'groups.public', 'Öffentlich', 'common', true, false),
('german', 'groups.private', 'Privat', 'common', true, false),
('german', 'blocked.load_failed', 'Blockierte Benutzer konnten nicht geladen werden', 'common', true, false),
('german', 'blocked.unblocked_success', 'Benutzer entblockt', 'common', true, false),
('german', 'blocked.unblock_failed', 'Benutzer konnte nicht entblockt werden', 'common', true, false)

ON CONFLICT DO NOTHING;
