
INSERT INTO public.app_translations (language_code, translation_key, translation_value, category, context) VALUES
-- Video Verification
('english','toast.video.submit_failed','Failed to submit verification','validation','useVideoVerification'),
('english','toast.video.not_verified','Not verified','validation','useVideoVerification'),
('english','toast.video.in_review','Verification in review','validation','useVideoVerification'),
('english','toast.video.verified','Video verified ✓','validation','useVideoVerification'),
('english','toast.video.rejected','Verification rejected','validation','useVideoVerification'),
('english','toast.video.expired','Verification expired - please reverify','validation','useVideoVerification'),
('norwegian','toast.video.submit_failed','Kunne ikke sende verifisering','validation','useVideoVerification'),
('norwegian','toast.video.not_verified','Ikke verifisert','validation','useVideoVerification'),
('norwegian','toast.video.in_review','Verifisering under gjennomgang','validation','useVideoVerification'),
('norwegian','toast.video.verified','Video verifisert ✓','validation','useVideoVerification'),
('norwegian','toast.video.rejected','Verifisering avvist','validation','useVideoVerification'),
('norwegian','toast.video.expired','Verifisering utløpt - vennligst verifiser på nytt','validation','useVideoVerification'),
('kurdish_sorani','toast.video.submit_failed','ناردنی پشتڕاستکردنەوە سەرکەوتوو نەبوو','validation','useVideoVerification'),
('kurdish_sorani','toast.video.not_verified','پشتڕاست نەکراوە','validation','useVideoVerification'),
('kurdish_sorani','toast.video.in_review','پشتڕاستکردنەوە لە پێداچوونەوەدایە','validation','useVideoVerification'),
('kurdish_sorani','toast.video.verified','ڤیدیۆ پشتڕاست کرا ✓','validation','useVideoVerification'),
('kurdish_sorani','toast.video.rejected','پشتڕاستکردنەوە ڕەتکرایەوە','validation','useVideoVerification'),
('kurdish_sorani','toast.video.expired','پشتڕاستکردنەوە بەسەرچووە - تکایە دووبارە پشتڕاست بکەرەوە','validation','useVideoVerification'),
('kurdish_kurmanji','toast.video.submit_failed','Şandina verastkirinê bi ser neket','validation','useVideoVerification'),
('kurdish_kurmanji','toast.video.not_verified','Nehatiye verastkirin','validation','useVideoVerification'),
('kurdish_kurmanji','toast.video.in_review','Verastkirin di lêkolînê de ye','validation','useVideoVerification'),
('kurdish_kurmanji','toast.video.verified','Vîdyo hat verastkirin ✓','validation','useVideoVerification'),
('kurdish_kurmanji','toast.video.rejected','Verastkirin hat redkirin','validation','useVideoVerification'),
('kurdish_kurmanji','toast.video.expired','Verastkirin qediya - ji kerema xwe dîsa verastkin bikin','validation','useVideoVerification'),
('german','toast.video.submit_failed','Verifizierung konnte nicht eingereicht werden','validation','useVideoVerification'),
('german','toast.video.not_verified','Nicht verifiziert','validation','useVideoVerification'),
('german','toast.video.in_review','Verifizierung wird überprüft','validation','useVideoVerification'),
('german','toast.video.verified','Video verifiziert ✓','validation','useVideoVerification'),
('german','toast.video.rejected','Verifizierung abgelehnt','validation','useVideoVerification'),
('german','toast.video.expired','Verifizierung abgelaufen - bitte erneut verifizieren','validation','useVideoVerification'),

-- Phone Verification
('english','phone.send_code_failed','Failed to send code','validation','usePhoneVerification'),
('english','phone.verify_code_failed','Failed to verify code','validation','usePhoneVerification'),
('english','common.not_authenticated','Not authenticated','common','usePhoneVerification'),
('norwegian','phone.send_code_failed','Kunne ikke sende kode','validation','usePhoneVerification'),
('norwegian','phone.verify_code_failed','Kunne ikke verifisere kode','validation','usePhoneVerification'),
('norwegian','common.not_authenticated','Ikke autentisert','common','usePhoneVerification'),
('kurdish_sorani','phone.send_code_failed','ناردنی کۆد سەرکەوتوو نەبوو','validation','usePhoneVerification'),
('kurdish_sorani','phone.verify_code_failed','پشتڕاستکردنی کۆد سەرکەوتوو نەبوو','validation','usePhoneVerification'),
('kurdish_sorani','common.not_authenticated','چوونەژوورەوە نەکراوە','common','usePhoneVerification'),
('kurdish_kurmanji','phone.send_code_failed','Şandina kodê bi ser neket','validation','usePhoneVerification'),
('kurdish_kurmanji','phone.verify_code_failed','Verastkirina kodê bi ser neket','validation','usePhoneVerification'),
('kurdish_kurmanji','common.not_authenticated','Nehatiye nasîn','common','usePhoneVerification'),
('german','phone.send_code_failed','Code konnte nicht gesendet werden','validation','usePhoneVerification'),
('german','phone.verify_code_failed','Code konnte nicht verifiziert werden','validation','usePhoneVerification'),
('german','common.not_authenticated','Nicht authentifiziert','common','usePhoneVerification'),

-- Match Score Card
('english','match.calc_failed','Failed to calculate match score','validation','MatchScoreCard'),
('english','match.perfect','Perfect Match','discovery','MatchScoreCard'),
('english','match.great','Great Match','discovery','MatchScoreCard'),
('english','match.good','Good Match','discovery','MatchScoreCard'),
('english','match.potential','Potential','discovery','MatchScoreCard'),
('english','match.worth_exploring','Worth Exploring','discovery','MatchScoreCard'),
('english','match.getting_to_know','Getting to Know','discovery','MatchScoreCard'),
('english','match.calculating','Calculating compatibility...','discovery','MatchScoreCard'),
('english','common.try_again','Try Again','common','MatchScoreCard'),
('english','match.match_score','Match Score','discovery','MatchScoreCard'),
('english','match.based_on_ai','Based on AI analysis','discovery','MatchScoreCard'),
('english','match.in_common','What you have in common','discovery','MatchScoreCard'),
('english','match.shared_interests','Shared Interests','discovery','MatchScoreCard'),
('english','match.core_values','Core Values','discovery','MatchScoreCard'),
('english','match.lifestyle_match','Lifestyle Match','discovery','MatchScoreCard'),
('english','match.relationship_goals','Relationship Goals','discovery','MatchScoreCard'),

('norwegian','match.calc_failed','Kunne ikke beregne matchpoeng','validation','MatchScoreCard'),
('norwegian','match.perfect','Perfekt match','discovery','MatchScoreCard'),
('norwegian','match.great','Flott match','discovery','MatchScoreCard'),
('norwegian','match.good','God match','discovery','MatchScoreCard'),
('norwegian','match.potential','Potensial','discovery','MatchScoreCard'),
('norwegian','match.worth_exploring','Verdt å utforske','discovery','MatchScoreCard'),
('norwegian','match.getting_to_know','Bli kjent','discovery','MatchScoreCard'),
('norwegian','match.calculating','Beregner kompatibilitet...','discovery','MatchScoreCard'),
('norwegian','common.try_again','Prøv igjen','common','MatchScoreCard'),
('norwegian','match.match_score','Matchpoeng','discovery','MatchScoreCard'),
('norwegian','match.based_on_ai','Basert på AI-analyse','discovery','MatchScoreCard'),
('norwegian','match.in_common','Hva dere har til felles','discovery','MatchScoreCard'),
('norwegian','match.shared_interests','Felles interesser','discovery','MatchScoreCard'),
('norwegian','match.core_values','Kjerneverdier','discovery','MatchScoreCard'),
('norwegian','match.lifestyle_match','Livsstilsmatch','discovery','MatchScoreCard'),
('norwegian','match.relationship_goals','Forholdsmål','discovery','MatchScoreCard'),

('kurdish_sorani','match.calc_failed','نمرەی هاوتاکردن حیساب نەکرا','validation','MatchScoreCard'),
('kurdish_sorani','match.perfect','هاوتای تەواو','discovery','MatchScoreCard'),
('kurdish_sorani','match.great','هاوتای نایاب','discovery','MatchScoreCard'),
('kurdish_sorani','match.good','هاوتای باش','discovery','MatchScoreCard'),
('kurdish_sorani','match.potential','پتانسیال','discovery','MatchScoreCard'),
('kurdish_sorani','match.worth_exploring','شایەنی لێکۆڵینەوەیە','discovery','MatchScoreCard'),
('kurdish_sorani','match.getting_to_know','ناسینەوە','discovery','MatchScoreCard'),
('kurdish_sorani','match.calculating','حیسابکردنی گونجاوی...','discovery','MatchScoreCard'),
('kurdish_sorani','common.try_again','دووبارە هەوڵ بدەرەوە','common','MatchScoreCard'),
('kurdish_sorani','match.match_score','نمرەی هاوتاکردن','discovery','MatchScoreCard'),
('kurdish_sorani','match.based_on_ai','لەسەر بنەمای شیکاری AI','discovery','MatchScoreCard'),
('kurdish_sorani','match.in_common','چی هاوبەشتانە','discovery','MatchScoreCard'),
('kurdish_sorani','match.shared_interests','ئارەزووی هاوبەش','discovery','MatchScoreCard'),
('kurdish_sorani','match.core_values','بەهای سەرەکی','discovery','MatchScoreCard'),
('kurdish_sorani','match.lifestyle_match','هاوتای شێوازی ژیان','discovery','MatchScoreCard'),
('kurdish_sorani','match.relationship_goals','ئامانجی پەیوەندی','discovery','MatchScoreCard'),

('kurdish_kurmanji','match.calc_failed','Pûana lihevhatinê nehat hesabkirin','validation','MatchScoreCard'),
('kurdish_kurmanji','match.perfect','Lihevhatina bêkêmasî','discovery','MatchScoreCard'),
('kurdish_kurmanji','match.great','Lihevhatina mezin','discovery','MatchScoreCard'),
('kurdish_kurmanji','match.good','Lihevhatina baş','discovery','MatchScoreCard'),
('kurdish_kurmanji','match.potential','Potansiyel','discovery','MatchScoreCard'),
('kurdish_kurmanji','match.worth_exploring','Hêjayî lêgerînê ye','discovery','MatchScoreCard'),
('kurdish_kurmanji','match.getting_to_know','Nasîn','discovery','MatchScoreCard'),
('kurdish_kurmanji','match.calculating','Lihevhatin tê hesabkirin...','discovery','MatchScoreCard'),
('kurdish_kurmanji','common.try_again','Dîsa biceribîne','common','MatchScoreCard'),
('kurdish_kurmanji','match.match_score','Pûana Lihevhatinê','discovery','MatchScoreCard'),
('kurdish_kurmanji','match.based_on_ai','Li ser bingeha analîza AI','discovery','MatchScoreCard'),
('kurdish_kurmanji','match.in_common','Çi hevpar e','discovery','MatchScoreCard'),
('kurdish_kurmanji','match.shared_interests','Eleqeyên hevpar','discovery','MatchScoreCard'),
('kurdish_kurmanji','match.core_values','Nirxên bingehîn','discovery','MatchScoreCard'),
('kurdish_kurmanji','match.lifestyle_match','Lihevhatina şêwaza jiyanê','discovery','MatchScoreCard'),
('kurdish_kurmanji','match.relationship_goals','Armancên têkiliyê','discovery','MatchScoreCard'),

('german','match.calc_failed','Match-Score konnte nicht berechnet werden','validation','MatchScoreCard'),
('german','match.perfect','Perfektes Match','discovery','MatchScoreCard'),
('german','match.great','Tolles Match','discovery','MatchScoreCard'),
('german','match.good','Gutes Match','discovery','MatchScoreCard'),
('german','match.potential','Potenzial','discovery','MatchScoreCard'),
('german','match.worth_exploring','Erkundungswert','discovery','MatchScoreCard'),
('german','match.getting_to_know','Kennenlernen','discovery','MatchScoreCard'),
('german','match.calculating','Kompatibilität wird berechnet...','discovery','MatchScoreCard'),
('german','common.try_again','Erneut versuchen','common','MatchScoreCard'),
('german','match.match_score','Match-Score','discovery','MatchScoreCard'),
('german','match.based_on_ai','Basierend auf KI-Analyse','discovery','MatchScoreCard'),
('german','match.in_common','Was ihr gemeinsam habt','discovery','MatchScoreCard'),
('german','match.shared_interests','Gemeinsame Interessen','discovery','MatchScoreCard'),
('german','match.core_values','Kernwerte','discovery','MatchScoreCard'),
('german','match.lifestyle_match','Lebensstil-Match','discovery','MatchScoreCard'),
('german','match.relationship_goals','Beziehungsziele','discovery','MatchScoreCard')
ON CONFLICT DO NOTHING;
