
-- Batch 15: i18n for BlockedUsersPage, LandingPageEditor, EventsManagementPage, HashtagsPage, FollowersPage + remaining strings
INSERT INTO public.app_translations (language_code, translation_key, translation_value, category, auto_translated, needs_review) VALUES
-- BlockedUsersPage
('english', 'admin.blocked_users_management', 'Blocked Users Management', 'admin', false, false),
('english', 'admin.view_all_blocks', 'View all user blocks ({{count}} total)', 'admin', false, false),
('english', 'admin.all_blocked_users', 'All Blocked Users', 'admin', false, false),
('english', 'admin.search_blocks', 'Search blocks...', 'admin', false, false),
('english', 'admin.loading_blocked', 'Loading blocked users...', 'admin', false, false),
('english', 'admin.no_blocked_found', 'No blocked users found', 'admin', false, false),
('english', 'admin.blocker', 'Blocker', 'admin', false, false),
('english', 'admin.blocked', 'Blocked', 'admin', false, false),
('english', 'admin.reason_label', 'Reason: {{reason}}', 'admin', false, false),
('english', 'admin.confirm_unblock', 'Are you sure you want to remove this block?', 'admin', false, false),
('english', 'toast.block_removed', 'Block removed successfully', 'admin', false, false),
('english', 'toast.block_remove_failed', 'Failed to remove block', 'admin', false, false),
('english', 'toast.blocked_load_failed', 'Failed to load blocked users', 'admin', false, false),

-- LandingPageEditor
('english', 'admin.loading_landing_content', 'Loading landing page content...', 'admin', false, false),
('english', 'admin.error_loading_landing', 'Error loading landing page content', 'admin', false, false),
('english', 'admin.content_missing', 'Content data is missing', 'admin', false, false),
('english', 'admin.content_not_loaded', 'The landing page content could not be loaded properly.', 'admin', false, false),
('english', 'common.retry', 'Retry', 'common', false, false),

-- EventsManagementPage
('english', 'admin.events_management', 'Events Management', 'admin', false, false),
('english', 'admin.manage_events_attendees', 'Manage all events and attendees', 'admin', false, false),
('english', 'admin.all_events', 'All Events', 'admin', false, false),
('english', 'admin.search_events', 'Search events...', 'admin', false, false),
('english', 'admin.loading_events', 'Loading events...', 'admin', false, false),
('english', 'admin.no_events_found', 'No events found', 'admin', false, false),
('english', 'admin.attendees', 'Attendees', 'admin', false, false),
('english', 'admin.all_attendees', 'All Attendees', 'admin', false, false),
('english', 'admin.search_attendees', 'Search attendees...', 'admin', false, false),
('english', 'admin.loading_attendees', 'Loading attendees...', 'admin', false, false),
('english', 'admin.no_attendees_found', 'No attendees found', 'admin', false, false),
('english', 'admin.attendees_count', '{{count}} attendees', 'admin', false, false),
('english', 'admin.confirm_delete_event', 'Are you sure you want to delete this event?', 'admin', false, false),
('english', 'admin.confirm_remove_attendee', 'Are you sure you want to remove this attendee?', 'admin', false, false),
('english', 'toast.event_deleted', 'Event deleted successfully', 'admin', false, false),
('english', 'toast.event_delete_failed', 'Failed to delete event', 'admin', false, false),
('english', 'toast.events_load_failed', 'Failed to load events', 'admin', false, false),
('english', 'toast.attendee_removed', 'Attendee removed successfully', 'admin', false, false),
('english', 'toast.attendee_remove_failed', 'Failed to remove attendee', 'admin', false, false),
('english', 'toast.attendees_load_failed', 'Failed to load attendees', 'admin', false, false),
('english', 'admin.user_label_short', 'User', 'admin', false, false),
('english', 'admin.event_label', 'Event', 'admin', false, false),

-- HashtagsPage
('english', 'admin.hashtags_management', 'Hashtags Management', 'admin', false, false),
('english', 'admin.manage_hashtags', 'Manage trending hashtags ({{count}} total)', 'admin', false, false),
('english', 'admin.all_hashtags', 'All Hashtags', 'admin', false, false),
('english', 'admin.search_hashtags', 'Search hashtags...', 'admin', false, false),
('english', 'admin.loading_hashtags', 'Loading hashtags...', 'admin', false, false),
('english', 'admin.no_hashtags_found', 'No hashtags found', 'admin', false, false),
('english', 'admin.uses_count', '{{count}} uses', 'admin', false, false),
('english', 'admin.last_used', 'Last used: {{date}}', 'admin', false, false),
('english', 'admin.created_label', 'Created: {{date}}', 'admin', false, false),
('english', 'admin.confirm_delete_hashtag', 'Are you sure you want to delete this hashtag?', 'admin', false, false),
('english', 'toast.hashtag_deleted', 'Hashtag deleted successfully', 'admin', false, false),
('english', 'toast.hashtag_delete_failed', 'Failed to delete hashtag', 'admin', false, false),
('english', 'toast.hashtags_load_failed', 'Failed to load hashtags', 'admin', false, false),

-- FollowersPage
('english', 'admin.followers_management', 'Followers Management', 'admin', false, false),
('english', 'admin.view_followers', 'View all follower relationships ({{count}} total)', 'admin', false, false),
('english', 'admin.all_followers', 'All Followers', 'admin', false, false),
('english', 'admin.search_by_user_id', 'Search by user ID...', 'admin', false, false),
('english', 'admin.loading_followers', 'Loading followers...', 'admin', false, false),
('english', 'admin.no_followers_found', 'No followers found', 'admin', false, false),
('english', 'admin.follower', 'Follower', 'admin', false, false),
('english', 'admin.following', 'Following', 'admin', false, false),
('english', 'admin.confirm_delete_follower', 'Are you sure you want to delete this follower relationship?', 'admin', false, false),
('english', 'toast.follower_deleted', 'Follower relationship deleted successfully', 'admin', false, false),
('english', 'toast.follower_delete_failed', 'Failed to delete follower', 'admin', false, false),
('english', 'toast.followers_load_failed', 'Failed to load followers', 'admin', false, false),

-- Remaining hardcoded strings in other files
('english', 'admin.no_conversations_found', 'No conversations found', 'admin', false, false),
('english', 'admin.no_muted_found', 'No muted conversations found', 'admin', false, false),
('english', 'admin.archived', 'Archived', 'admin', false, false),
('english', 'admin.last_label', 'Last: {{date}}', 'admin', false, false),
('english', 'admin.until_label', 'Until: {{date}}', 'admin', false, false),
('english', 'admin.indefinite', 'Indefinite', 'admin', false, false),
('english', 'admin.no_reports_found', 'No reports found', 'admin', false, false),
('english', 'admin.no_messages_found', 'No messages found', 'admin', false, false),
('english', 'admin.events', 'Events', 'admin', false, false),

-- Norwegian translations
('norwegian', 'admin.blocked_users_management', 'Blokkerte brukere', 'admin', true, true),
('norwegian', 'admin.view_all_blocks', 'Se alle brukerblokkeringer ({{count}} totalt)', 'admin', true, true),
('norwegian', 'admin.all_blocked_users', 'Alle blokkerte brukere', 'admin', true, true),
('norwegian', 'admin.search_blocks', 'Søk blokkeringer...', 'admin', true, true),
('norwegian', 'admin.loading_blocked', 'Laster blokkerte brukere...', 'admin', true, true),
('norwegian', 'admin.no_blocked_found', 'Ingen blokkerte brukere funnet', 'admin', true, true),
('norwegian', 'admin.blocker', 'Blokkerer', 'admin', true, true),
('norwegian', 'admin.blocked', 'Blokkert', 'admin', true, true),
('norwegian', 'admin.reason_label', 'Grunn: {{reason}}', 'admin', true, true),
('norwegian', 'admin.confirm_unblock', 'Er du sikker på at du vil fjerne denne blokkeringen?', 'admin', true, true),
('norwegian', 'toast.block_removed', 'Blokkering fjernet', 'admin', true, true),
('norwegian', 'toast.block_remove_failed', 'Kunne ikke fjerne blokkering', 'admin', true, true),
('norwegian', 'toast.blocked_load_failed', 'Kunne ikke laste blokkerte brukere', 'admin', true, true),
('norwegian', 'admin.loading_landing_content', 'Laster landingssideinnhold...', 'admin', true, true),
('norwegian', 'admin.error_loading_landing', 'Feil ved lasting av landingssideinnhold', 'admin', true, true),
('norwegian', 'admin.content_missing', 'Innholdsdata mangler', 'admin', true, true),
('norwegian', 'admin.content_not_loaded', 'Landingssideinnholdet kunne ikke lastes riktig.', 'admin', true, true),
('norwegian', 'common.retry', 'Prøv igjen', 'common', true, true),
('norwegian', 'admin.events_management', 'Arrangementer', 'admin', true, true),
('norwegian', 'admin.manage_events_attendees', 'Administrer alle arrangementer og deltakere', 'admin', true, true),
('norwegian', 'admin.all_events', 'Alle arrangementer', 'admin', true, true),
('norwegian', 'admin.search_events', 'Søk arrangementer...', 'admin', true, true),
('norwegian', 'admin.loading_events', 'Laster arrangementer...', 'admin', true, true),
('norwegian', 'admin.no_events_found', 'Ingen arrangementer funnet', 'admin', true, true),
('norwegian', 'admin.attendees', 'Deltakere', 'admin', true, true),
('norwegian', 'admin.all_attendees', 'Alle deltakere', 'admin', true, true),
('norwegian', 'admin.search_attendees', 'Søk deltakere...', 'admin', true, true),
('norwegian', 'admin.loading_attendees', 'Laster deltakere...', 'admin', true, true),
('norwegian', 'admin.no_attendees_found', 'Ingen deltakere funnet', 'admin', true, true),
('norwegian', 'admin.attendees_count', '{{count}} deltakere', 'admin', true, true),
('norwegian', 'admin.confirm_delete_event', 'Er du sikker på at du vil slette dette arrangementet?', 'admin', true, true),
('norwegian', 'admin.confirm_remove_attendee', 'Er du sikker på at du vil fjerne denne deltakeren?', 'admin', true, true),
('norwegian', 'toast.event_deleted', 'Arrangement slettet', 'admin', true, true),
('norwegian', 'toast.event_delete_failed', 'Kunne ikke slette arrangement', 'admin', true, true),
('norwegian', 'toast.events_load_failed', 'Kunne ikke laste arrangementer', 'admin', true, true),
('norwegian', 'toast.attendee_removed', 'Deltaker fjernet', 'admin', true, true),
('norwegian', 'toast.attendee_remove_failed', 'Kunne ikke fjerne deltaker', 'admin', true, true),
('norwegian', 'toast.attendees_load_failed', 'Kunne ikke laste deltakere', 'admin', true, true),
('norwegian', 'admin.user_label_short', 'Bruker', 'admin', true, true),
('norwegian', 'admin.event_label', 'Arrangement', 'admin', true, true),
('norwegian', 'admin.hashtags_management', 'Hashtag-administrasjon', 'admin', true, true),
('norwegian', 'admin.manage_hashtags', 'Administrer trendende hashtags ({{count}} totalt)', 'admin', true, true),
('norwegian', 'admin.all_hashtags', 'Alle hashtags', 'admin', true, true),
('norwegian', 'admin.search_hashtags', 'Søk hashtags...', 'admin', true, true),
('norwegian', 'admin.loading_hashtags', 'Laster hashtags...', 'admin', true, true),
('norwegian', 'admin.no_hashtags_found', 'Ingen hashtags funnet', 'admin', true, true),
('norwegian', 'admin.uses_count', '{{count}} bruk', 'admin', true, true),
('norwegian', 'admin.last_used', 'Sist brukt: {{date}}', 'admin', true, true),
('norwegian', 'admin.created_label', 'Opprettet: {{date}}', 'admin', true, true),
('norwegian', 'admin.confirm_delete_hashtag', 'Er du sikker på at du vil slette denne hashtaggen?', 'admin', true, true),
('norwegian', 'toast.hashtag_deleted', 'Hashtag slettet', 'admin', true, true),
('norwegian', 'toast.hashtag_delete_failed', 'Kunne ikke slette hashtag', 'admin', true, true),
('norwegian', 'toast.hashtags_load_failed', 'Kunne ikke laste hashtags', 'admin', true, true),
('norwegian', 'admin.followers_management', 'Følgere-administrasjon', 'admin', true, true),
('norwegian', 'admin.view_followers', 'Se alle følgerforhold ({{count}} totalt)', 'admin', true, true),
('norwegian', 'admin.all_followers', 'Alle følgere', 'admin', true, true),
('norwegian', 'admin.search_by_user_id', 'Søk etter bruker-ID...', 'admin', true, true),
('norwegian', 'admin.loading_followers', 'Laster følgere...', 'admin', true, true),
('norwegian', 'admin.no_followers_found', 'Ingen følgere funnet', 'admin', true, true),
('norwegian', 'admin.follower', 'Følger', 'admin', true, true),
('norwegian', 'admin.following', 'Følger', 'admin', true, true),
('norwegian', 'admin.confirm_delete_follower', 'Er du sikker på at du vil slette dette følgerforholdet?', 'admin', true, true),
('norwegian', 'toast.follower_deleted', 'Følgerforhold slettet', 'admin', true, true),
('norwegian', 'toast.follower_delete_failed', 'Kunne ikke slette følger', 'admin', true, true),
('norwegian', 'toast.followers_load_failed', 'Kunne ikke laste følgere', 'admin', true, true),
('norwegian', 'admin.no_conversations_found', 'Ingen samtaler funnet', 'admin', true, true),
('norwegian', 'admin.no_muted_found', 'Ingen dempede samtaler funnet', 'admin', true, true),
('norwegian', 'admin.archived', 'Arkivert', 'admin', true, true),
('norwegian', 'admin.last_label', 'Sist: {{date}}', 'admin', true, true),
('norwegian', 'admin.until_label', 'Til: {{date}}', 'admin', true, true),
('norwegian', 'admin.indefinite', 'Ubestemt', 'admin', true, true),
('norwegian', 'admin.no_reports_found', 'Ingen rapporter funnet', 'admin', true, true),
('norwegian', 'admin.no_messages_found', 'Ingen meldinger funnet', 'admin', true, true),
('norwegian', 'admin.events', 'Arrangementer', 'admin', true, true),

-- Kurdish Sorani translations
('kurdish_sorani', 'admin.blocked_users_management', 'بەڕێوەبردنی بەکارهێنەرە بلۆککراوەکان', 'admin', true, true),
('kurdish_sorani', 'admin.view_all_blocks', 'بینینی هەموو بلۆکەکان ({{count}} کۆی گشتی)', 'admin', true, true),
('kurdish_sorani', 'admin.all_blocked_users', 'هەموو بەکارهێنەرە بلۆککراوەکان', 'admin', true, true),
('kurdish_sorani', 'admin.search_blocks', 'گەڕان لە بلۆکەکان...', 'admin', true, true),
('kurdish_sorani', 'admin.loading_blocked', 'بارکردنی بەکارهێنەرە بلۆککراوەکان...', 'admin', true, true),
('kurdish_sorani', 'admin.no_blocked_found', 'هیچ بەکارهێنەرێکی بلۆککراو نەدۆزرایەوە', 'admin', true, true),
('kurdish_sorani', 'admin.blocker', 'بلۆککەر', 'admin', true, true),
('kurdish_sorani', 'admin.blocked', 'بلۆککراو', 'admin', true, true),
('kurdish_sorani', 'admin.reason_label', 'هۆکار: {{reason}}', 'admin', true, true),
('kurdish_sorani', 'admin.confirm_unblock', 'دڵنیایت لە لابردنی ئەم بلۆکە؟', 'admin', true, true),
('kurdish_sorani', 'toast.block_removed', 'بلۆک لابرا', 'admin', true, true),
('kurdish_sorani', 'toast.block_remove_failed', 'لابردنی بلۆک سەرنەکەوت', 'admin', true, true),
('kurdish_sorani', 'toast.blocked_load_failed', 'بارکردنی بەکارهێنەرە بلۆککراوەکان سەرنەکەوت', 'admin', true, true),
('kurdish_sorani', 'admin.loading_landing_content', 'بارکردنی ناوەڕۆکی پەڕەی دەستپێک...', 'admin', true, true),
('kurdish_sorani', 'admin.error_loading_landing', 'هەڵە لە بارکردنی ناوەڕۆکی پەڕەی دەستپێک', 'admin', true, true),
('kurdish_sorani', 'admin.content_missing', 'داتای ناوەڕۆک بوونی نییە', 'admin', true, true),
('kurdish_sorani', 'admin.content_not_loaded', 'ناوەڕۆکی پەڕەی دەستپێک بە دروستی بارنەکرا.', 'admin', true, true),
('kurdish_sorani', 'common.retry', 'دووبارە هەوڵبدەرەوە', 'common', true, true),
('kurdish_sorani', 'admin.events_management', 'بەڕێوەبردنی ڕووداوەکان', 'admin', true, true),
('kurdish_sorani', 'admin.manage_events_attendees', 'بەڕێوەبردنی هەموو ڕووداوەکان و بەشداربووان', 'admin', true, true),
('kurdish_sorani', 'admin.all_events', 'هەموو ڕووداوەکان', 'admin', true, true),
('kurdish_sorani', 'admin.search_events', 'گەڕان لە ڕووداوەکان...', 'admin', true, true),
('kurdish_sorani', 'admin.loading_events', 'بارکردنی ڕووداوەکان...', 'admin', true, true),
('kurdish_sorani', 'admin.no_events_found', 'هیچ ڕووداوێک نەدۆزرایەوە', 'admin', true, true),
('kurdish_sorani', 'admin.attendees', 'بەشداربووان', 'admin', true, true),
('kurdish_sorani', 'admin.all_attendees', 'هەموو بەشداربووان', 'admin', true, true),
('kurdish_sorani', 'admin.search_attendees', 'گەڕان لە بەشداربووان...', 'admin', true, true),
('kurdish_sorani', 'admin.loading_attendees', 'بارکردنی بەشداربووان...', 'admin', true, true),
('kurdish_sorani', 'admin.no_attendees_found', 'هیچ بەشداربووێک نەدۆزرایەوە', 'admin', true, true),
('kurdish_sorani', 'admin.attendees_count', '{{count}} بەشداربوو', 'admin', true, true),
('kurdish_sorani', 'admin.confirm_delete_event', 'دڵنیایت لە سڕینەوەی ئەم ڕووداوە؟', 'admin', true, true),
('kurdish_sorani', 'admin.confirm_remove_attendee', 'دڵنیایت لە لابردنی ئەم بەشداربووە؟', 'admin', true, true),
('kurdish_sorani', 'toast.event_deleted', 'ڕووداو سڕایەوە', 'admin', true, true),
('kurdish_sorani', 'toast.event_delete_failed', 'سڕینەوەی ڕووداو سەرنەکەوت', 'admin', true, true),
('kurdish_sorani', 'toast.events_load_failed', 'بارکردنی ڕووداوەکان سەرنەکەوت', 'admin', true, true),
('kurdish_sorani', 'toast.attendee_removed', 'بەشداربوو لابرا', 'admin', true, true),
('kurdish_sorani', 'toast.attendee_remove_failed', 'لابردنی بەشداربوو سەرنەکەوت', 'admin', true, true),
('kurdish_sorani', 'toast.attendees_load_failed', 'بارکردنی بەشداربووان سەرنەکەوت', 'admin', true, true),
('kurdish_sorani', 'admin.user_label_short', 'بەکارهێنەر', 'admin', true, true),
('kurdish_sorani', 'admin.event_label', 'ڕووداو', 'admin', true, true),
('kurdish_sorani', 'admin.hashtags_management', 'بەڕێوەبردنی هاشتاگەکان', 'admin', true, true),
('kurdish_sorani', 'admin.manage_hashtags', 'بەڕێوەبردنی هاشتاگە ترێندەکان ({{count}} کۆی گشتی)', 'admin', true, true),
('kurdish_sorani', 'admin.all_hashtags', 'هەموو هاشتاگەکان', 'admin', true, true),
('kurdish_sorani', 'admin.search_hashtags', 'گەڕان لە هاشتاگەکان...', 'admin', true, true),
('kurdish_sorani', 'admin.loading_hashtags', 'بارکردنی هاشتاگەکان...', 'admin', true, true),
('kurdish_sorani', 'admin.no_hashtags_found', 'هیچ هاشتاگێک نەدۆزرایەوە', 'admin', true, true),
('kurdish_sorani', 'admin.uses_count', '{{count}} بەکارهێنان', 'admin', true, true),
('kurdish_sorani', 'admin.last_used', 'دوایین بەکارهێنان: {{date}}', 'admin', true, true),
('kurdish_sorani', 'admin.created_label', 'دروستکراو: {{date}}', 'admin', true, true),
('kurdish_sorani', 'admin.confirm_delete_hashtag', 'دڵنیایت لە سڕینەوەی ئەم هاشتاگە؟', 'admin', true, true),
('kurdish_sorani', 'toast.hashtag_deleted', 'هاشتاگ سڕایەوە', 'admin', true, true),
('kurdish_sorani', 'toast.hashtag_delete_failed', 'سڕینەوەی هاشتاگ سەرنەکەوت', 'admin', true, true),
('kurdish_sorani', 'toast.hashtags_load_failed', 'بارکردنی هاشتاگەکان سەرنەکەوت', 'admin', true, true),
('kurdish_sorani', 'admin.followers_management', 'بەڕێوەبردنی شوێنکەوتووان', 'admin', true, true),
('kurdish_sorani', 'admin.view_followers', 'بینینی هەموو پەیوەندییەکانی شوێنکەوتن ({{count}} کۆی گشتی)', 'admin', true, true),
('kurdish_sorani', 'admin.all_followers', 'هەموو شوێنکەوتووان', 'admin', true, true),
('kurdish_sorani', 'admin.search_by_user_id', 'گەڕان بە ناسنامەی بەکارهێنەر...', 'admin', true, true),
('kurdish_sorani', 'admin.loading_followers', 'بارکردنی شوێنکەوتووان...', 'admin', true, true),
('kurdish_sorani', 'admin.no_followers_found', 'هیچ شوێنکەوتووێک نەدۆزرایەوە', 'admin', true, true),
('kurdish_sorani', 'admin.follower', 'شوێنکەوتوو', 'admin', true, true),
('kurdish_sorani', 'admin.following', 'شوێنکەوتن', 'admin', true, true),
('kurdish_sorani', 'admin.confirm_delete_follower', 'دڵنیایت لە سڕینەوەی ئەم پەیوەندییە؟', 'admin', true, true),
('kurdish_sorani', 'toast.follower_deleted', 'پەیوەندیی شوێنکەوتن سڕایەوە', 'admin', true, true),
('kurdish_sorani', 'toast.follower_delete_failed', 'سڕینەوەی شوێنکەوتوو سەرنەکەوت', 'admin', true, true),
('kurdish_sorani', 'toast.followers_load_failed', 'بارکردنی شوێنکەوتووان سەرنەکەوت', 'admin', true, true),
('kurdish_sorani', 'admin.no_conversations_found', 'هیچ گفتوگۆیەک نەدۆزرایەوە', 'admin', true, true),
('kurdish_sorani', 'admin.no_muted_found', 'هیچ گفتوگۆی بێدەنگکراو نەدۆزرایەوە', 'admin', true, true),
('kurdish_sorani', 'admin.archived', 'ئەرشیفکراو', 'admin', true, true),
('kurdish_sorani', 'admin.last_label', 'دوایین: {{date}}', 'admin', true, true),
('kurdish_sorani', 'admin.until_label', 'هەتا: {{date}}', 'admin', true, true),
('kurdish_sorani', 'admin.indefinite', 'بێ کۆتایی', 'admin', true, true),
('kurdish_sorani', 'admin.no_reports_found', 'هیچ ڕاپۆرتێک نەدۆزرایەوە', 'admin', true, true),
('kurdish_sorani', 'admin.no_messages_found', 'هیچ نامەیەک نەدۆزرایەوە', 'admin', true, true),
('kurdish_sorani', 'admin.events', 'ڕووداوەکان', 'admin', true, true),

-- Kurdish Kurmanci translations
('kurdish_kurmanci', 'admin.blocked_users_management', 'Rêveberiya bikarhênerên astengkirî', 'admin', true, true),
('kurdish_kurmanci', 'admin.view_all_blocks', 'Hemû astengkirinan bibîne ({{count}} bi giştî)', 'admin', true, true),
('kurdish_kurmanci', 'admin.all_blocked_users', 'Hemû bikarhênerên astengkirî', 'admin', true, true),
('kurdish_kurmanci', 'admin.search_blocks', 'Li astengkirinan bigere...', 'admin', true, true),
('kurdish_kurmanci', 'admin.loading_blocked', 'Bikarhênerên astengkirî tên barkirin...', 'admin', true, true),
('kurdish_kurmanci', 'admin.no_blocked_found', 'Tu bikarhênerê astengkirî nehate dîtin', 'admin', true, true),
('kurdish_kurmanci', 'admin.blocker', 'Astengker', 'admin', true, true),
('kurdish_kurmanci', 'admin.blocked', 'Astengkirî', 'admin', true, true),
('kurdish_kurmanci', 'admin.reason_label', 'Sedem: {{reason}}', 'admin', true, true),
('kurdish_kurmanci', 'admin.confirm_unblock', 'Ma tu bawer î ku dixwazî vê astengkirinê rakin?', 'admin', true, true),
('kurdish_kurmanci', 'toast.block_removed', 'Astengkirin hat rakirin', 'admin', true, true),
('kurdish_kurmanci', 'toast.block_remove_failed', 'Rakirina astengkirinê bi ser neket', 'admin', true, true),
('kurdish_kurmanci', 'toast.blocked_load_failed', 'Barkirina bikarhênerên astengkirî bi ser neket', 'admin', true, true),
('kurdish_kurmanci', 'admin.loading_landing_content', 'Naveroka rûpela destpêkê tê barkirin...', 'admin', true, true),
('kurdish_kurmanci', 'admin.error_loading_landing', 'Çewtî di barkirina naveroka rûpela destpêkê de', 'admin', true, true),
('kurdish_kurmanci', 'admin.content_missing', 'Daneyên naveroka tune ne', 'admin', true, true),
('kurdish_kurmanci', 'admin.content_not_loaded', 'Naveroka rûpela destpêkê bi rêkûpêk bar nebû.', 'admin', true, true),
('kurdish_kurmanci', 'common.retry', 'Careke din biceribîne', 'common', true, true),
('kurdish_kurmanci', 'admin.events_management', 'Rêveberiya bûyeran', 'admin', true, true),
('kurdish_kurmanci', 'admin.manage_events_attendees', 'Hemû bûyer û beşdaran birêve bibe', 'admin', true, true),
('kurdish_kurmanci', 'admin.all_events', 'Hemû bûyer', 'admin', true, true),
('kurdish_kurmanci', 'admin.search_events', 'Li bûyeran bigere...', 'admin', true, true),
('kurdish_kurmanci', 'admin.loading_events', 'Bûyer tên barkirin...', 'admin', true, true),
('kurdish_kurmanci', 'admin.no_events_found', 'Tu bûyer nehate dîtin', 'admin', true, true),
('kurdish_kurmanci', 'admin.attendees', 'Beşdar', 'admin', true, true),
('kurdish_kurmanci', 'admin.all_attendees', 'Hemû beşdar', 'admin', true, true),
('kurdish_kurmanci', 'admin.search_attendees', 'Li beşdaran bigere...', 'admin', true, true),
('kurdish_kurmanci', 'admin.loading_attendees', 'Beşdar tên barkirin...', 'admin', true, true),
('kurdish_kurmanci', 'admin.no_attendees_found', 'Tu beşdar nehate dîtin', 'admin', true, true),
('kurdish_kurmanci', 'admin.attendees_count', '{{count}} beşdar', 'admin', true, true),
('kurdish_kurmanci', 'admin.confirm_delete_event', 'Ma tu bawer î ku dixwazî vê bûyerê jê bibî?', 'admin', true, true),
('kurdish_kurmanci', 'admin.confirm_remove_attendee', 'Ma tu bawer î ku dixwazî vî beşdarî rakin?', 'admin', true, true),
('kurdish_kurmanci', 'toast.event_deleted', 'Bûyer hat jêbirin', 'admin', true, true),
('kurdish_kurmanci', 'toast.event_delete_failed', 'Jêbirina bûyerê bi ser neket', 'admin', true, true),
('kurdish_kurmanci', 'toast.events_load_failed', 'Barkirina bûyeran bi ser neket', 'admin', true, true),
('kurdish_kurmanci', 'toast.attendee_removed', 'Beşdar hat rakirin', 'admin', true, true),
('kurdish_kurmanci', 'toast.attendee_remove_failed', 'Rakirina beşdar bi ser neket', 'admin', true, true),
('kurdish_kurmanci', 'toast.attendees_load_failed', 'Barkirina beşdaran bi ser neket', 'admin', true, true),
('kurdish_kurmanci', 'admin.user_label_short', 'Bikarhêner', 'admin', true, true),
('kurdish_kurmanci', 'admin.event_label', 'Bûyer', 'admin', true, true),
('kurdish_kurmanci', 'admin.hashtags_management', 'Rêveberiya hashtagan', 'admin', true, true),
('kurdish_kurmanci', 'admin.manage_hashtags', 'Hashtag trendên birêve bibe ({{count}} bi giştî)', 'admin', true, true),
('kurdish_kurmanci', 'admin.all_hashtags', 'Hemû hashtag', 'admin', true, true),
('kurdish_kurmanci', 'admin.search_hashtags', 'Li hashtagan bigere...', 'admin', true, true),
('kurdish_kurmanci', 'admin.loading_hashtags', 'Hashtag tên barkirin...', 'admin', true, true),
('kurdish_kurmanci', 'admin.no_hashtags_found', 'Tu hashtag nehate dîtin', 'admin', true, true),
('kurdish_kurmanci', 'admin.uses_count', '{{count}} bikaranîn', 'admin', true, true),
('kurdish_kurmanci', 'admin.last_used', 'Dawîn bikaranîn: {{date}}', 'admin', true, true),
('kurdish_kurmanci', 'admin.created_label', 'Hatiye afirandin: {{date}}', 'admin', true, true),
('kurdish_kurmanci', 'admin.confirm_delete_hashtag', 'Ma tu bawer î ku dixwazî vê hashtagê jê bibî?', 'admin', true, true),
('kurdish_kurmanci', 'toast.hashtag_deleted', 'Hashtag hat jêbirin', 'admin', true, true),
('kurdish_kurmanci', 'toast.hashtag_delete_failed', 'Jêbirina hashtagê bi ser neket', 'admin', true, true),
('kurdish_kurmanci', 'toast.hashtags_load_failed', 'Barkirina hashtagan bi ser neket', 'admin', true, true),
('kurdish_kurmanci', 'admin.followers_management', 'Rêveberiya şopîneran', 'admin', true, true),
('kurdish_kurmanci', 'admin.view_followers', 'Hemû têkiliyên şopîneriyê bibîne ({{count}} bi giştî)', 'admin', true, true),
('kurdish_kurmanci', 'admin.all_followers', 'Hemû şopîner', 'admin', true, true),
('kurdish_kurmanci', 'admin.search_by_user_id', 'Bi nasnameya bikarhêner bigere...', 'admin', true, true),
('kurdish_kurmanci', 'admin.loading_followers', 'Şopîner tên barkirin...', 'admin', true, true),
('kurdish_kurmanci', 'admin.no_followers_found', 'Tu şopîner nehate dîtin', 'admin', true, true),
('kurdish_kurmanci', 'admin.follower', 'Şopîner', 'admin', true, true),
('kurdish_kurmanci', 'admin.following', 'Dişopîne', 'admin', true, true),
('kurdish_kurmanci', 'admin.confirm_delete_follower', 'Ma tu bawer î ku dixwazî vê têkiliyê jê bibî?', 'admin', true, true),
('kurdish_kurmanci', 'toast.follower_deleted', 'Têkiliya şopîneriyê hat jêbirin', 'admin', true, true),
('kurdish_kurmanci', 'toast.follower_delete_failed', 'Jêbirina şopîner bi ser neket', 'admin', true, true),
('kurdish_kurmanci', 'toast.followers_load_failed', 'Barkirina şopîneran bi ser neket', 'admin', true, true),
('kurdish_kurmanci', 'admin.no_conversations_found', 'Tu axaftin nehate dîtin', 'admin', true, true),
('kurdish_kurmanci', 'admin.no_muted_found', 'Tu axaftina bêdengkirî nehate dîtin', 'admin', true, true),
('kurdish_kurmanci', 'admin.archived', 'Arşîvkirî', 'admin', true, true),
('kurdish_kurmanci', 'admin.last_label', 'Dawîn: {{date}}', 'admin', true, true),
('kurdish_kurmanci', 'admin.until_label', 'Heta: {{date}}', 'admin', true, true),
('kurdish_kurmanci', 'admin.indefinite', 'Bê dawî', 'admin', true, true),
('kurdish_kurmanci', 'admin.no_reports_found', 'Tu rapor nehate dîtin', 'admin', true, true),
('kurdish_kurmanci', 'admin.no_messages_found', 'Tu peyam nehate dîtin', 'admin', true, true),
('kurdish_kurmanci', 'admin.events', 'Bûyer', 'admin', true, true),

-- German translations
('german', 'admin.blocked_users_management', 'Blockierte Benutzer', 'admin', true, true),
('german', 'admin.view_all_blocks', 'Alle Benutzerblockierungen anzeigen ({{count}} gesamt)', 'admin', true, true),
('german', 'admin.all_blocked_users', 'Alle blockierten Benutzer', 'admin', true, true),
('german', 'admin.search_blocks', 'Blockierungen durchsuchen...', 'admin', true, true),
('german', 'admin.loading_blocked', 'Blockierte Benutzer werden geladen...', 'admin', true, true),
('german', 'admin.no_blocked_found', 'Keine blockierten Benutzer gefunden', 'admin', true, true),
('german', 'admin.blocker', 'Blockierer', 'admin', true, true),
('german', 'admin.blocked', 'Blockiert', 'admin', true, true),
('german', 'admin.reason_label', 'Grund: {{reason}}', 'admin', true, true),
('german', 'admin.confirm_unblock', 'Möchten Sie diese Blockierung wirklich aufheben?', 'admin', true, true),
('german', 'toast.block_removed', 'Blockierung aufgehoben', 'admin', true, true),
('german', 'toast.block_remove_failed', 'Blockierung konnte nicht aufgehoben werden', 'admin', true, true),
('german', 'toast.blocked_load_failed', 'Blockierte Benutzer konnten nicht geladen werden', 'admin', true, true),
('german', 'admin.loading_landing_content', 'Landingpage-Inhalt wird geladen...', 'admin', true, true),
('german', 'admin.error_loading_landing', 'Fehler beim Laden des Landingpage-Inhalts', 'admin', true, true),
('german', 'admin.content_missing', 'Inhaltsdaten fehlen', 'admin', true, true),
('german', 'admin.content_not_loaded', 'Der Landingpage-Inhalt konnte nicht richtig geladen werden.', 'admin', true, true),
('german', 'common.retry', 'Erneut versuchen', 'common', true, true),
('german', 'admin.events_management', 'Veranstaltungsverwaltung', 'admin', true, true),
('german', 'admin.manage_events_attendees', 'Alle Veranstaltungen und Teilnehmer verwalten', 'admin', true, true),
('german', 'admin.all_events', 'Alle Veranstaltungen', 'admin', true, true),
('german', 'admin.search_events', 'Veranstaltungen durchsuchen...', 'admin', true, true),
('german', 'admin.loading_events', 'Veranstaltungen werden geladen...', 'admin', true, true),
('german', 'admin.no_events_found', 'Keine Veranstaltungen gefunden', 'admin', true, true),
('german', 'admin.attendees', 'Teilnehmer', 'admin', true, true),
('german', 'admin.all_attendees', 'Alle Teilnehmer', 'admin', true, true),
('german', 'admin.search_attendees', 'Teilnehmer durchsuchen...', 'admin', true, true),
('german', 'admin.loading_attendees', 'Teilnehmer werden geladen...', 'admin', true, true),
('german', 'admin.no_attendees_found', 'Keine Teilnehmer gefunden', 'admin', true, true),
('german', 'admin.attendees_count', '{{count}} Teilnehmer', 'admin', true, true),
('german', 'admin.confirm_delete_event', 'Möchten Sie diese Veranstaltung wirklich löschen?', 'admin', true, true),
('german', 'admin.confirm_remove_attendee', 'Möchten Sie diesen Teilnehmer wirklich entfernen?', 'admin', true, true),
('german', 'toast.event_deleted', 'Veranstaltung gelöscht', 'admin', true, true),
('german', 'toast.event_delete_failed', 'Veranstaltung konnte nicht gelöscht werden', 'admin', true, true),
('german', 'toast.events_load_failed', 'Veranstaltungen konnten nicht geladen werden', 'admin', true, true),
('german', 'toast.attendee_removed', 'Teilnehmer entfernt', 'admin', true, true),
('german', 'toast.attendee_remove_failed', 'Teilnehmer konnte nicht entfernt werden', 'admin', true, true),
('german', 'toast.attendees_load_failed', 'Teilnehmer konnten nicht geladen werden', 'admin', true, true),
('german', 'admin.user_label_short', 'Benutzer', 'admin', true, true),
('german', 'admin.event_label', 'Veranstaltung', 'admin', true, true),
('german', 'admin.hashtags_management', 'Hashtag-Verwaltung', 'admin', true, true),
('german', 'admin.manage_hashtags', 'Trending Hashtags verwalten ({{count}} gesamt)', 'admin', true, true),
('german', 'admin.all_hashtags', 'Alle Hashtags', 'admin', true, true),
('german', 'admin.search_hashtags', 'Hashtags durchsuchen...', 'admin', true, true),
('german', 'admin.loading_hashtags', 'Hashtags werden geladen...', 'admin', true, true),
('german', 'admin.no_hashtags_found', 'Keine Hashtags gefunden', 'admin', true, true),
('german', 'admin.uses_count', '{{count}} Verwendungen', 'admin', true, true),
('german', 'admin.last_used', 'Zuletzt verwendet: {{date}}', 'admin', true, true),
('german', 'admin.created_label', 'Erstellt: {{date}}', 'admin', true, true),
('german', 'admin.confirm_delete_hashtag', 'Möchten Sie diesen Hashtag wirklich löschen?', 'admin', true, true),
('german', 'toast.hashtag_deleted', 'Hashtag gelöscht', 'admin', true, true),
('german', 'toast.hashtag_delete_failed', 'Hashtag konnte nicht gelöscht werden', 'admin', true, true),
('german', 'toast.hashtags_load_failed', 'Hashtags konnten nicht geladen werden', 'admin', true, true),
('german', 'admin.followers_management', 'Follower-Verwaltung', 'admin', true, true),
('german', 'admin.view_followers', 'Alle Follower-Beziehungen anzeigen ({{count}} gesamt)', 'admin', true, true),
('german', 'admin.all_followers', 'Alle Follower', 'admin', true, true),
('german', 'admin.search_by_user_id', 'Nach Benutzer-ID suchen...', 'admin', true, true),
('german', 'admin.loading_followers', 'Follower werden geladen...', 'admin', true, true),
('german', 'admin.no_followers_found', 'Keine Follower gefunden', 'admin', true, true),
('german', 'admin.follower', 'Follower', 'admin', true, true),
('german', 'admin.following', 'Folgt', 'admin', true, true),
('german', 'admin.confirm_delete_follower', 'Möchten Sie diese Follower-Beziehung wirklich löschen?', 'admin', true, true),
('german', 'toast.follower_deleted', 'Follower-Beziehung gelöscht', 'admin', true, true),
('german', 'toast.follower_delete_failed', 'Follower konnte nicht gelöscht werden', 'admin', true, true),
('german', 'toast.followers_load_failed', 'Follower konnten nicht geladen werden', 'admin', true, true),
('german', 'admin.no_conversations_found', 'Keine Gespräche gefunden', 'admin', true, true),
('german', 'admin.no_muted_found', 'Keine stummgeschalteten Gespräche gefunden', 'admin', true, true),
('german', 'admin.archived', 'Archiviert', 'admin', true, true),
('german', 'admin.last_label', 'Zuletzt: {{date}}', 'admin', true, true),
('german', 'admin.until_label', 'Bis: {{date}}', 'admin', true, true),
('german', 'admin.indefinite', 'Unbefristet', 'admin', true, true),
('german', 'admin.no_reports_found', 'Keine Berichte gefunden', 'admin', true, true),
('german', 'admin.no_messages_found', 'Keine Nachrichten gefunden', 'admin', true, true),
('german', 'admin.events', 'Veranstaltungen', 'admin', true, true)
ON CONFLICT (language_code, translation_key) DO UPDATE SET
  translation_value = EXCLUDED.translation_value,
  updated_at = now();
