
INSERT INTO public.app_translations (language_code, translation_key, translation_value, category, context) VALUES
-- Location components
('english','location.device_location','Device Location','settings','CurrentLocationTab'),
('english','location.updating','Updating...','settings','CurrentLocationTab'),
('english','location.update','Update','settings','CurrentLocationTab'),
('english','location.detecting','Detecting location...','settings','CurrentLocationTab'),
('english','location.gps_desc','This uses your device''s GPS to determine your exact location.','settings','CurrentLocationTab'),
('english','location.manual','Manual Location','settings','ManualLocationTab'),
('english','location.manual_desc','Choose your location by clicking on the map or searching for a city.','settings','ManualLocationTab'),
('english','location.search','Search Location','settings','ManualLocationTab'),
('english','location.search_city','Search City','settings','ManualLocationTab'),
('english','location.search_city_placeholder','Search for a city or country...','settings','ManualLocationTab'),
('english','location.no_results_try','No locations found. Try a different search.','settings','ManualLocationTab'),
('english','location.no_location','No location set','settings','ManualLocationTab'),
('english','location.click_map','Click on the map or search to set your location.','settings','ManualLocationTab'),
('english','location.info','Location Information','settings','LocationSectionContent'),
('english','location.your_location','Your Location','settings','LocationSectionContent'),

('norwegian','location.device_location','Enhetens plassering','settings','CurrentLocationTab'),
('norwegian','location.updating','Oppdaterer...','settings','CurrentLocationTab'),
('norwegian','location.update','Oppdater','settings','CurrentLocationTab'),
('norwegian','location.detecting','Oppdager plassering...','settings','CurrentLocationTab'),
('norwegian','location.gps_desc','Dette bruker enhetens GPS for å bestemme din nøyaktige plassering.','settings','CurrentLocationTab'),
('norwegian','location.manual','Manuell plassering','settings','ManualLocationTab'),
('norwegian','location.manual_desc','Velg plasseringen din ved å klikke på kartet eller søke etter en by.','settings','ManualLocationTab'),
('norwegian','location.search','Søk plassering','settings','ManualLocationTab'),
('norwegian','location.search_city','Søk by','settings','ManualLocationTab'),
('norwegian','location.search_city_placeholder','Søk etter en by eller et land...','settings','ManualLocationTab'),
('norwegian','location.no_results_try','Ingen plasseringer funnet. Prøv et annet søk.','settings','ManualLocationTab'),
('norwegian','location.no_location','Ingen plassering angitt','settings','ManualLocationTab'),
('norwegian','location.click_map','Klikk på kartet eller søk for å angi plasseringen din.','settings','ManualLocationTab'),
('norwegian','location.info','Plasseringsinformasjon','settings','LocationSectionContent'),
('norwegian','location.your_location','Din plassering','settings','LocationSectionContent'),

('kurdish_sorani','location.device_location','شوێنی ئامێر','settings','CurrentLocationTab'),
('kurdish_sorani','location.updating','نوێکردنەوە...','settings','CurrentLocationTab'),
('kurdish_sorani','location.update','نوێکردنەوە','settings','CurrentLocationTab'),
('kurdish_sorani','location.detecting','دۆزینەوەی شوێن...','settings','CurrentLocationTab'),
('kurdish_sorani','location.gps_desc','ئەمە GPSی ئامێرەکەت بەکاردەهێنێت بۆ دیاریکردنی شوێنی ڕاستەقینەت.','settings','CurrentLocationTab'),
('kurdish_sorani','location.manual','شوێنی دەستی','settings','ManualLocationTab'),
('kurdish_sorani','location.manual_desc','شوێنەکەت هەڵبژێرە بە کلیککردن لەسەر نەخشەکە یان گەڕان بۆ شارێک.','settings','ManualLocationTab'),
('kurdish_sorani','location.search','گەڕانی شوێن','settings','ManualLocationTab'),
('kurdish_sorani','location.search_city','گەڕان بۆ شار','settings','ManualLocationTab'),
('kurdish_sorani','location.search_city_placeholder','گەڕان بۆ شارێک یان وڵاتێک...','settings','ManualLocationTab'),
('kurdish_sorani','location.no_results_try','هیچ شوێنێک نەدۆزرایەوە. گەڕانێکی جیاواز تاقی بکەرەوە.','settings','ManualLocationTab'),
('kurdish_sorani','location.no_location','هیچ شوێنێک دانەنراوە','settings','ManualLocationTab'),
('kurdish_sorani','location.click_map','کلیک لەسەر نەخشەکە بکە یان بگەڕێ بۆ دانانی شوێنەکەت.','settings','ManualLocationTab'),
('kurdish_sorani','location.info','زانیاری شوێن','settings','LocationSectionContent'),
('kurdish_sorani','location.your_location','شوێنەکەت','settings','LocationSectionContent'),

('kurdish_kurmanji','location.device_location','Cihê amûrê','settings','CurrentLocationTab'),
('kurdish_kurmanji','location.updating','Tê nûkirin...','settings','CurrentLocationTab'),
('kurdish_kurmanji','location.update','Nûke','settings','CurrentLocationTab'),
('kurdish_kurmanji','location.detecting','Cih tê dîtin...','settings','CurrentLocationTab'),
('kurdish_kurmanji','location.gps_desc','Ev GPSa amûra te bikar tîne da ku cihê te yê rast diyar bike.','settings','CurrentLocationTab'),
('kurdish_kurmanji','location.manual','Cihê bi destan','settings','ManualLocationTab'),
('kurdish_kurmanji','location.manual_desc','Cihê xwe hilbijêre bi klîkkirina li nexşeyê an lêgerîna bajarekî.','settings','ManualLocationTab'),
('kurdish_kurmanji','location.search','Lêgerîna cihê','settings','ManualLocationTab'),
('kurdish_kurmanji','location.search_city','Li bajar bigere','settings','ManualLocationTab'),
('kurdish_kurmanji','location.search_city_placeholder','Li bajarek an welatek bigere...','settings','ManualLocationTab'),
('kurdish_kurmanji','location.no_results_try','Cih nehat dîtin. Lêgerînek din biceribîne.','settings','ManualLocationTab'),
('kurdish_kurmanji','location.no_location','Cih nehatiye danîn','settings','ManualLocationTab'),
('kurdish_kurmanji','location.click_map','Li nexşeyê klîk bike an bigere ji bo danîna cihê xwe.','settings','ManualLocationTab'),
('kurdish_kurmanji','location.info','Agahiyên cihê','settings','LocationSectionContent'),
('kurdish_kurmanji','location.your_location','Cihê te','settings','LocationSectionContent'),

('german','location.device_location','Gerätestandort','settings','CurrentLocationTab'),
('german','location.updating','Wird aktualisiert...','settings','CurrentLocationTab'),
('german','location.update','Aktualisieren','settings','CurrentLocationTab'),
('german','location.detecting','Standort wird erkannt...','settings','CurrentLocationTab'),
('german','location.gps_desc','Dies nutzt das GPS Ihres Geräts, um Ihren genauen Standort zu bestimmen.','settings','CurrentLocationTab'),
('german','location.manual','Manueller Standort','settings','ManualLocationTab'),
('german','location.manual_desc','Wählen Sie Ihren Standort durch Klicken auf die Karte oder Suche nach einer Stadt.','settings','ManualLocationTab'),
('german','location.search','Standort suchen','settings','ManualLocationTab'),
('german','location.search_city','Stadt suchen','settings','ManualLocationTab'),
('german','location.search_city_placeholder','Nach einer Stadt oder einem Land suchen...','settings','ManualLocationTab'),
('german','location.no_results_try','Keine Standorte gefunden. Versuchen Sie eine andere Suche.','settings','ManualLocationTab'),
('german','location.no_location','Kein Standort festgelegt','settings','ManualLocationTab'),
('german','location.click_map','Klicken Sie auf die Karte oder suchen Sie, um Ihren Standort festzulegen.','settings','ManualLocationTab'),
('german','location.info','Standortinformationen','settings','LocationSectionContent'),
('german','location.your_location','Ihr Standort','settings','LocationSectionContent'),

-- PhotoManagement
('english','photos.gallery','Photo Gallery','profile','PhotoManagement'),
('english','photos.add_up_to','Add up to {{max}} photos to showcase yourself','profile','PhotoManagement'),
('english','photos.photos','photos','profile','PhotoManagement'),
('english','photos.completion','Photo Gallery Completion','profile','PhotoManagement'),
('english','photos.add','Add Photo','profile','PhotoManagement'),
('english','photos.photo','Photo','profile','PhotoManagement'),
('english','photos.profile','Profile','profile','PhotoManagement'),
('english','photos.verified','Verified','profile','PhotoManagement'),
('english','photos.tips','Photo Tips','profile','PhotoManagement'),
('english','photos.tip1','Use natural lighting for better photos','profile','PhotoManagement'),
('english','photos.tip2','Include photos that show your personality','profile','PhotoManagement'),
('english','photos.tip3','Add at least one full-body photo','profile','PhotoManagement'),
('english','photos.tip4','Smile! Photos with smiles get more likes','profile','PhotoManagement'),
('english','photos.tip5','Show your hobbies and interests','profile','PhotoManagement'),
('english','photos.tip6','Avoid group photos as your main picture','profile','PhotoManagement'),
('english','photos.ai_enhance','AI Photo Enhancement','profile','PhotoManagement'),
('english','photos.ai_enhance_desc','Enhance your photos with AI to get more matches','profile','PhotoManagement'),
('english','photos.enhance_btn','Enhance Photos','profile','PhotoManagement'),

('norwegian','photos.gallery','Bildegalleri','profile','PhotoManagement'),
('norwegian','photos.add_up_to','Legg til opptil {{max}} bilder for å vise deg frem','profile','PhotoManagement'),
('norwegian','photos.photos','bilder','profile','PhotoManagement'),
('norwegian','photos.completion','Bildegalleriet fullført','profile','PhotoManagement'),
('norwegian','photos.add','Legg til bilde','profile','PhotoManagement'),
('norwegian','photos.photo','Bilde','profile','PhotoManagement'),
('norwegian','photos.profile','Profil','profile','PhotoManagement'),
('norwegian','photos.verified','Verifisert','profile','PhotoManagement'),
('norwegian','photos.tips','Bildetips','profile','PhotoManagement'),
('norwegian','photos.tip1','Bruk naturlig lys for bedre bilder','profile','PhotoManagement'),
('norwegian','photos.tip2','Inkluder bilder som viser personligheten din','profile','PhotoManagement'),
('norwegian','photos.tip3','Legg til minst ett helfigurbilde','profile','PhotoManagement'),
('norwegian','photos.tip4','Smil! Bilder med smil får flere likes','profile','PhotoManagement'),
('norwegian','photos.tip5','Vis hobbyene og interessene dine','profile','PhotoManagement'),
('norwegian','photos.tip6','Unngå gruppebilder som hovedbilde','profile','PhotoManagement'),
('norwegian','photos.ai_enhance','AI-bildeforbedring','profile','PhotoManagement'),
('norwegian','photos.ai_enhance_desc','Forbedre bildene dine med AI for å få flere matcher','profile','PhotoManagement'),
('norwegian','photos.enhance_btn','Forbedre bilder','profile','PhotoManagement'),

('kurdish_sorani','photos.gallery','گالێری وێنە','profile','PhotoManagement'),
('kurdish_sorani','photos.add_up_to','تا {{max}} وێنە زیاد بکە بۆ نیشاندانی خۆت','profile','PhotoManagement'),
('kurdish_sorani','photos.photos','وێنە','profile','PhotoManagement'),
('kurdish_sorani','photos.completion','تەواوکردنی گالێری وێنە','profile','PhotoManagement'),
('kurdish_sorani','photos.add','زیادکردنی وێنە','profile','PhotoManagement'),
('kurdish_sorani','photos.photo','وێنە','profile','PhotoManagement'),
('kurdish_sorani','photos.profile','پرۆفایل','profile','PhotoManagement'),
('kurdish_sorani','photos.verified','پشتڕاستکراوە','profile','PhotoManagement'),
('kurdish_sorani','photos.tips','ڕێنمایی وێنە','profile','PhotoManagement'),
('kurdish_sorani','photos.tip1','ڕووناکی سروشتی بەکاربهێنە بۆ وێنەی باشتر','profile','PhotoManagement'),
('kurdish_sorani','photos.tip2','وێنەیەک بخەرەوە کە کەسایەتیت نیشان بدات','profile','PhotoManagement'),
('kurdish_sorani','photos.tip3','لانیکەم یەک وێنەی تەواوی جەستە زیاد بکە','profile','PhotoManagement'),
('kurdish_sorani','photos.tip4','بزەنە! وێنەی بزەنەدار لایکی زیاتر وەردەگرن','profile','PhotoManagement'),
('kurdish_sorani','photos.tip5','ئارەزوو و حەزەکانت نیشان بدە','profile','PhotoManagement'),
('kurdish_sorani','photos.tip6','لە وێنەی کۆمەڵە وەک وێنەی سەرەکی دوور بکەوەرەوە','profile','PhotoManagement'),
('kurdish_sorani','photos.ai_enhance','باشترکردنی وێنە بە AI','profile','PhotoManagement'),
('kurdish_sorani','photos.ai_enhance_desc','وێنەکانت باشتر بکە بە AI بۆ بەدەستهێنانی هاوتای زیاتر','profile','PhotoManagement'),
('kurdish_sorani','photos.enhance_btn','باشترکردنی وێنەکان','profile','PhotoManagement'),

('kurdish_kurmanji','photos.gallery','Galeriya wêneyan','profile','PhotoManagement'),
('kurdish_kurmanji','photos.add_up_to','Heta {{max}} wêneyan lê zêde bike ji bo nîşandana xwe','profile','PhotoManagement'),
('kurdish_kurmanji','photos.photos','wêne','profile','PhotoManagement'),
('kurdish_kurmanji','photos.completion','Temamkirina galeriya wêneyan','profile','PhotoManagement'),
('kurdish_kurmanji','photos.add','Wêne lê zêde bike','profile','PhotoManagement'),
('kurdish_kurmanji','photos.photo','Wêne','profile','PhotoManagement'),
('kurdish_kurmanji','photos.profile','Profîl','profile','PhotoManagement'),
('kurdish_kurmanji','photos.verified','Hatiye verastkirin','profile','PhotoManagement'),
('kurdish_kurmanji','photos.tips','Şîretên wêneyan','profile','PhotoManagement'),
('kurdish_kurmanji','photos.tip1','Ronahiya xwezayî bikar bîne ji bo wêneyên çêtir','profile','PhotoManagement'),
('kurdish_kurmanji','photos.tip2','Wêneyên ku kesayetiya te nîşan didin têxe nav','profile','PhotoManagement'),
('kurdish_kurmanji','photos.tip3','Bi kêmanî wêneyek tam-laş lê zêde bike','profile','PhotoManagement'),
('kurdish_kurmanji','photos.tip4','Biken! Wêneyên bi ken bêtir like distînin','profile','PhotoManagement'),
('kurdish_kurmanji','photos.tip5','Hobî û eleqeyên xwe nîşan bide','profile','PhotoManagement'),
('kurdish_kurmanji','photos.tip6','Ji wêneyên komê wekî wêneya sereke dûr bikeve','profile','PhotoManagement'),
('kurdish_kurmanji','photos.ai_enhance','Baştirkirina wêneyan bi AI','profile','PhotoManagement'),
('kurdish_kurmanji','photos.ai_enhance_desc','Wêneyên xwe bi AI baştir bike ji bo bêtir lihevhatinan','profile','PhotoManagement'),
('kurdish_kurmanji','photos.enhance_btn','Wêneyan baştir bike','profile','PhotoManagement'),

('german','photos.gallery','Fotogalerie','profile','PhotoManagement'),
('german','photos.add_up_to','Fügen Sie bis zu {{max}} Fotos hinzu, um sich zu präsentieren','profile','PhotoManagement'),
('german','photos.photos','Fotos','profile','PhotoManagement'),
('german','photos.completion','Fotogalerie-Fortschritt','profile','PhotoManagement'),
('german','photos.add','Foto hinzufügen','profile','PhotoManagement'),
('german','photos.photo','Foto','profile','PhotoManagement'),
('german','photos.profile','Profil','profile','PhotoManagement'),
('german','photos.verified','Verifiziert','profile','PhotoManagement'),
('german','photos.tips','Foto-Tipps','profile','PhotoManagement'),
('german','photos.tip1','Verwenden Sie natürliches Licht für bessere Fotos','profile','PhotoManagement'),
('german','photos.tip2','Fügen Sie Fotos hinzu, die Ihre Persönlichkeit zeigen','profile','PhotoManagement'),
('german','photos.tip3','Fügen Sie mindestens ein Ganzkörperfoto hinzu','profile','PhotoManagement'),
('german','photos.tip4','Lächeln! Fotos mit Lächeln bekommen mehr Likes','profile','PhotoManagement'),
('german','photos.tip5','Zeigen Sie Ihre Hobbys und Interessen','profile','PhotoManagement'),
('german','photos.tip6','Vermeiden Sie Gruppenfotos als Hauptbild','profile','PhotoManagement'),
('german','photos.ai_enhance','KI-Fotoverbesserung','profile','PhotoManagement'),
('german','photos.ai_enhance_desc','Verbessern Sie Ihre Fotos mit KI für mehr Matches','profile','PhotoManagement'),
('german','photos.enhance_btn','Fotos verbessern','profile','PhotoManagement'),

-- ProfileSections
('english','profile.sections','Profile Sections','profile','ProfileSections'),
('english','profile.edit_sections','Edit Sections','profile','ProfileSections'),
('english','profile.choose_sections','Choose which sections to display on your profile','profile','ProfileSections'),
('english','profile.update_info','Update your profile information to help others get to know you better.','profile','ProfileSections'),
('norwegian','profile.sections','Profilseksjoner','profile','ProfileSections'),
('norwegian','profile.edit_sections','Rediger seksjoner','profile','ProfileSections'),
('norwegian','profile.choose_sections','Velg hvilke seksjoner som skal vises på profilen din','profile','ProfileSections'),
('norwegian','profile.update_info','Oppdater profilinformasjonen din for å hjelpe andre å bli kjent med deg.','profile','ProfileSections'),
('kurdish_sorani','profile.sections','بەشەکانی پرۆفایل','profile','ProfileSections'),
('kurdish_sorani','profile.edit_sections','دەستکاریکردنی بەشەکان','profile','ProfileSections'),
('kurdish_sorani','profile.choose_sections','هەڵبژێرە کام بەش لەسەر پرۆفایلەکەت نیشان بدرێت','profile','ProfileSections'),
('kurdish_sorani','profile.update_info','زانیاری پرۆفایلەکەت نوێ بکەرەوە بۆ یارمەتیدان بە کەسانی تر بۆ ناسینت.','profile','ProfileSections'),
('kurdish_kurmanji','profile.sections','Beşên profîlê','profile','ProfileSections'),
('kurdish_kurmanji','profile.edit_sections','Beşan biguherîne','profile','ProfileSections'),
('kurdish_kurmanji','profile.choose_sections','Hilbijêre kîjan beş li ser profîla te bêne nîşandan','profile','ProfileSections'),
('kurdish_kurmanji','profile.update_info','Agahiyên profîla xwe nû bike da ku alîkariya kesên din bike ku te baştir nas bikin.','profile','ProfileSections'),
('german','profile.sections','Profilabschnitte','profile','ProfileSections'),
('german','profile.edit_sections','Abschnitte bearbeiten','profile','ProfileSections'),
('german','profile.choose_sections','Wählen Sie, welche Abschnitte in Ihrem Profil angezeigt werden','profile','ProfileSections'),
('german','profile.update_info','Aktualisieren Sie Ihre Profilinformationen, damit andere Sie besser kennenlernen.','profile','ProfileSections'),

-- PrivacySettings
('english','privacy.blur_photos','Blur Photos','settings','PrivacySettings'),
('english','privacy.blur_desc','Hide your face on dating profiles','settings','PrivacySettings'),
('english','privacy.blur_info','Your photos will appear blurred to other users. You can share clear photos with specific matches below.','settings','PrivacySettings'),
('english','privacy.field_visibility','Field Visibility','settings','PrivacySettings'),
('english','privacy.control_visible','Control what others see','settings','PrivacySettings'),
('english','privacy.hidden','hidden','settings','PrivacySettings'),
('english','privacy.upgrade_premium','Upgrade to Premium to control which fields are visible on your profile.','settings','PrivacySettings'),
('english','privacy.share_matches','Share With Matches','settings','PrivacySettings'),
('english','privacy.share_desc','Share hidden info & clear photos with specific people','settings','PrivacySettings'),
('english','privacy.no_matches','No matches yet','settings','PrivacySettings'),
('english','privacy.match_to_share','Match with people to share your full profile with them','settings','PrivacySettings'),
('english','privacy.shared','Shared ✓','settings','PrivacySettings'),
('english','privacy.share','Share','settings','PrivacySettings'),

('norwegian','privacy.blur_photos','Slør bilder','settings','PrivacySettings'),
('norwegian','privacy.blur_desc','Skjul ansiktet ditt på datingprofiler','settings','PrivacySettings'),
('norwegian','privacy.blur_info','Bildene dine vil vises uskarpe for andre brukere. Du kan dele klare bilder med spesifikke matcher nedenfor.','settings','PrivacySettings'),
('norwegian','privacy.field_visibility','Feltsynlighet','settings','PrivacySettings'),
('norwegian','privacy.control_visible','Kontroller hva andre ser','settings','PrivacySettings'),
('norwegian','privacy.hidden','skjult','settings','PrivacySettings'),
('norwegian','privacy.upgrade_premium','Oppgrader til Premium for å kontrollere hvilke felt som er synlige på profilen din.','settings','PrivacySettings'),
('norwegian','privacy.share_matches','Del med matcher','settings','PrivacySettings'),
('norwegian','privacy.share_desc','Del skjult info og klare bilder med bestemte personer','settings','PrivacySettings'),
('norwegian','privacy.no_matches','Ingen matcher ennå','settings','PrivacySettings'),
('norwegian','privacy.match_to_share','Match med folk for å dele hele profilen din med dem','settings','PrivacySettings'),
('norwegian','privacy.shared','Delt ✓','settings','PrivacySettings'),
('norwegian','privacy.share','Del','settings','PrivacySettings'),

('kurdish_sorani','privacy.blur_photos','تاڵکردنی وێنەکان','settings','PrivacySettings'),
('kurdish_sorani','privacy.blur_desc','ڕووت بشارەوە لە پرۆفایلەکانی دۆستبینین','settings','PrivacySettings'),
('kurdish_sorani','privacy.blur_info','وێنەکانت تاڵ دەردەکەون بۆ بەکارهێنەرانی تر. دەتوانیت وێنەی ڕوون لەگەڵ هاوتاکانی دیاریکراو بپارێزیت لەخوارەوە.','settings','PrivacySettings'),
('kurdish_sorani','privacy.field_visibility','بینینی خانەکان','settings','PrivacySettings'),
('kurdish_sorani','privacy.control_visible','کۆنترۆلی ئەوەی کە کەسانی تر دەیبینن','settings','PrivacySettings'),
('kurdish_sorani','privacy.hidden','شاراوە','settings','PrivacySettings'),
('kurdish_sorani','privacy.upgrade_premium','نوێکردنەوە بۆ پریمیۆم بۆ کۆنترۆلکردنی خانەکان لەسەر پرۆفایلەکەت.','settings','PrivacySettings'),
('kurdish_sorani','privacy.share_matches','هاوبەشکردن لەگەڵ هاوتاکان','settings','PrivacySettings'),
('kurdish_sorani','privacy.share_desc','زانیاری شاراوە و وێنەی ڕوون لەگەڵ کەسانی دیاریکراو هاوبەش بکە','settings','PrivacySettings'),
('kurdish_sorani','privacy.no_matches','هێشتا هیچ هاوتایەک نییە','settings','PrivacySettings'),
('kurdish_sorani','privacy.match_to_share','هاوتا بکە لەگەڵ خەڵکی بۆ هاوبەشکردنی پرۆفایلی تەواوت لەگەڵیان','settings','PrivacySettings'),
('kurdish_sorani','privacy.shared','هاوبەشکرا ✓','settings','PrivacySettings'),
('kurdish_sorani','privacy.share','هاوبەشکردن','settings','PrivacySettings'),

('kurdish_kurmanji','privacy.blur_photos','Wêneyan tarî bike','settings','PrivacySettings'),
('kurdish_kurmanji','privacy.blur_desc','Rûyê xwe li profîlên hevdîtinê veşêre','settings','PrivacySettings'),
('kurdish_kurmanji','privacy.blur_info','Wêneyên te dê tarî xuya bibin ji bikarhênerên din re. Tu dikarî wêneyên zelal bi lihevhatinên taybet re li jêr parve bikî.','settings','PrivacySettings'),
('kurdish_kurmanji','privacy.field_visibility','Dîtina qadan','settings','PrivacySettings'),
('kurdish_kurmanji','privacy.control_visible','Kontrol bike ku yên din çi dibînin','settings','PrivacySettings'),
('kurdish_kurmanji','privacy.hidden','veşartî','settings','PrivacySettings'),
('kurdish_kurmanji','privacy.upgrade_premium','Ji bo kontrolkirina kîjan qad li ser profîla te xuya dibin, bi Premium re nû bike.','settings','PrivacySettings'),
('kurdish_kurmanji','privacy.share_matches','Bi lihevhatinan re parve bike','settings','PrivacySettings'),
('kurdish_kurmanji','privacy.share_desc','Agahiyên veşartî û wêneyên zelal bi kesên taybet re parve bike','settings','PrivacySettings'),
('kurdish_kurmanji','privacy.no_matches','Hîn lihevhatin tune','settings','PrivacySettings'),
('kurdish_kurmanji','privacy.match_to_share','Bi kesan re lihevhatin bike da ku profîla xwe ya temam bi wan re parve bikî','settings','PrivacySettings'),
('kurdish_kurmanji','privacy.shared','Hat parve kirin ✓','settings','PrivacySettings'),
('kurdish_kurmanji','privacy.share','Parve bike','settings','PrivacySettings'),

('german','privacy.blur_photos','Fotos verwischen','settings','PrivacySettings'),
('german','privacy.blur_desc','Verstecken Sie Ihr Gesicht auf Dating-Profilen','settings','PrivacySettings'),
('german','privacy.blur_info','Ihre Fotos erscheinen für andere Benutzer unscharf. Sie können klare Fotos mit bestimmten Matches unten teilen.','settings','PrivacySettings'),
('german','privacy.field_visibility','Feldsichtbarkeit','settings','PrivacySettings'),
('german','privacy.control_visible','Kontrollieren Sie, was andere sehen','settings','PrivacySettings'),
('german','privacy.hidden','versteckt','settings','PrivacySettings'),
('german','privacy.upgrade_premium','Upgraden Sie auf Premium, um zu kontrollieren, welche Felder in Ihrem Profil sichtbar sind.','settings','PrivacySettings'),
('german','privacy.share_matches','Mit Matches teilen','settings','PrivacySettings'),
('german','privacy.share_desc','Versteckte Infos und klare Fotos mit bestimmten Personen teilen','settings','PrivacySettings'),
('german','privacy.no_matches','Noch keine Matches','settings','PrivacySettings'),
('german','privacy.match_to_share','Matchen Sie mit Leuten, um Ihr vollständiges Profil mit ihnen zu teilen','settings','PrivacySettings'),
('german','privacy.shared','Geteilt ✓','settings','PrivacySettings'),
('german','privacy.share','Teilen','settings','PrivacySettings')
ON CONFLICT DO NOTHING;
