
-- Batch 13: i18n for NotificationsPage, VerificationPage, GhostUsersPage, VirtualGiftsPage, SubscribersPage, RateLimitsPage, DailyUsagePage
INSERT INTO public.app_translations (language_code, translation_key, translation_value, category) VALUES
-- NotificationsPage
('english', 'admin.notifications_management', 'Notifications Management', 'admin'),
('english', 'admin.view_manage_notifications', 'View and manage all system notifications ({{count}} total)', 'admin'),
('english', 'admin.all_notifications', 'All Notifications', 'admin'),
('english', 'admin.search_notifications', 'Search notifications...', 'admin'),
('english', 'admin.loading_notifications', 'Loading notifications...', 'admin'),
('english', 'admin.no_notifications_found', 'No notifications found', 'admin'),
('english', 'admin.delete_notification_confirm', 'Are you sure you want to delete this notification?', 'admin'),
('english', 'admin.notification_deleted', 'Notification deleted successfully', 'admin'),
('english', 'admin.notification_delete_failed', 'Failed to delete notification', 'admin'),
('english', 'admin.failed_load_notifications', 'Failed to load notifications', 'admin'),
('english', 'common.all', 'All', 'common'),
('english', 'common.unread', 'Unread', 'common'),
('english', 'common.read', 'Read', 'common'),
('english', 'common.refresh', 'Refresh', 'common'),
('english', 'common.user', 'User', 'common'),

-- VerificationPage
('english', 'admin.user_verification', 'User Verification', 'admin'),
('english', 'admin.verification_history', 'History', 'admin'),
('english', 'admin.verification_settings', 'Verification Settings', 'admin'),
('english', 'admin.ai_enhanced_verification', 'AI-Enhanced Verification', 'admin'),
('english', 'admin.ai_verification_desc', 'Our AI system pre-validates documents and flags potential issues for your review', 'admin'),
('english', 'admin.pending_review', 'Pending Review', 'admin'),
('english', 'admin.verified', 'Verified', 'admin'),
('english', 'admin.rejected', 'Rejected', 'admin'),
('english', 'admin.ai_flagged', 'AI Flagged', 'admin'),
('english', 'admin.search_name_email', 'Search by name or email...', 'admin'),
('english', 'admin.filter_by_status', 'Filter by status', 'admin'),
('english', 'admin.all_statuses', 'All Statuses', 'admin'),
('english', 'admin.document_type', 'Document Type', 'admin'),
('english', 'admin.submitted', 'Submitted', 'admin'),
('english', 'admin.priority', 'Priority', 'admin'),
('english', 'admin.high', 'High', 'admin'),
('english', 'admin.medium', 'Medium', 'admin'),
('english', 'admin.normal', 'Normal', 'admin'),
('english', 'admin.no_flagged_requests', 'No AI flagged requests found', 'admin'),
('english', 'admin.no_verification_requests', 'No {{status}} verification requests found', 'admin'),
('english', 'admin.loading_verification', 'Loading verification requests...', 'admin'),

-- GhostUsersPage
('english', 'admin.ghost_users', 'Ghost Users', 'admin'),
('english', 'admin.ghost_users_desc', 'Generate and manage auto-generated profiles', 'admin'),
('english', 'admin.publish_due_content', 'Publish Due Content', 'admin'),
('english', 'admin.regenerate_activity', 'Regenerate Activity', 'admin'),
('english', 'admin.generate_users', 'Generate Users', 'admin'),
('english', 'admin.generate_ghost_users', 'Generate Ghost Users', 'admin'),
('english', 'admin.create_realistic_profiles', 'Create realistic auto-generated profiles', 'admin'),
('english', 'admin.number_of_users', 'Number of users', 'admin'),
('english', 'admin.gender', 'Gender', 'admin'),
('english', 'admin.mixed', 'Mixed', 'admin'),
('english', 'admin.male_only', 'Male only', 'admin'),
('english', 'admin.female_only', 'Female only', 'admin'),
('english', 'admin.region_optional', 'Region (optional)', 'admin'),
('english', 'admin.all_regions', 'All regions', 'admin'),
('english', 'admin.content_options', 'Content options', 'admin'),
('english', 'admin.generate_posts', 'Generate posts (2-5 per user)', 'admin'),
('english', 'admin.generate_stories', 'Generate stories (1-3 per user)', 'admin'),
('english', 'admin.generate_profile_photos', 'Generate profile photos (2-4 per user)', 'admin'),
('english', 'admin.set_verified_profiles', 'Set as verified profiles', 'admin'),
('english', 'admin.generating_progress', 'Generating {{current}} / {{total}}', 'admin'),
('english', 'admin.generation_complete', 'Generation Complete', 'admin'),
('english', 'admin.generation_result', 'Successfully created {{count}} ghost users.', 'admin'),
('english', 'admin.delete_all_ghost_users', 'Delete All Ghost Users', 'admin'),
('english', 'admin.delete_all_ghost_confirm', 'This will permanently remove all {{count}} ghost users and their posts, stories, photos, and scheduled content.', 'admin'),
('english', 'admin.all_ghost_deleted', 'All Ghost Users Deleted', 'admin'),
('english', 'admin.ghost_deleted_result', 'Removed {{count}} ghost users and their content.', 'admin'),
('english', 'admin.ghost_user_deleted', 'Ghost user deleted', 'admin'),
('english', 'admin.published_content', 'Published Content', 'admin'),
('english', 'admin.activity_regenerated', 'Activity Regenerated', 'admin'),
('english', 'admin.total_posts', 'Total Posts', 'admin'),
('english', 'admin.scheduled_content', 'Scheduled Content', 'admin'),
('english', 'admin.no_ghost_users', 'No ghost users yet. Generate some to get started.', 'admin'),
('english', 'common.name', 'Name', 'common'),
('english', 'common.gender', 'Gender', 'common'),
('english', 'common.location', 'Location', 'common'),
('english', 'common.created', 'Created', 'common'),
('english', 'common.last_active', 'Last Active', 'common'),
('english', 'common.cancel', 'Cancel', 'common'),
('english', 'common.generate', 'Generate', 'common'),
('english', 'common.generating', 'Generating...', 'common'),
('english', 'common.delete_all', 'Delete All', 'common'),
('english', 'common.loading', 'Loading...', 'common'),

-- VirtualGiftsPage
('english', 'admin.virtual_gifts', 'Virtual Gifts', 'admin'),
('english', 'admin.active_total_gifts', '{{active}} active · {{total}} total gifts', 'admin'),
('english', 'admin.add_gift', 'Add Gift', 'admin'),
('english', 'admin.edit_gift', 'Edit Gift', 'admin'),
('english', 'admin.create_gift', 'Create Gift', 'admin'),
('english', 'admin.update_gift', 'Update Gift', 'admin'),
('english', 'admin.emoji', 'Emoji', 'admin'),
('english', 'admin.price_coins', 'Price (coins)', 'admin'),
('english', 'admin.sort_order', 'Sort Order', 'admin'),
('english', 'admin.premium_only', 'Premium only', 'admin'),
('english', 'admin.gift_updated', 'Gift updated', 'admin'),
('english', 'admin.gift_created', 'Gift created', 'admin'),
('english', 'admin.name_emoji_required', 'Name and emoji are required', 'admin'),

-- SubscribersPage
('english', 'admin.subscriber_management', 'Subscriber Management', 'admin'),
('english', 'admin.manage_subscriptions', 'Manage premium subscriptions', 'admin'),
('english', 'admin.total_subscribers', 'Total Subscribers', 'admin'),
('english', 'admin.basic_plan', 'Basic Plan', 'admin'),
('english', 'admin.premium_plan', 'Premium Plan', 'admin'),
('english', 'admin.monthly_revenue', 'Monthly Revenue', 'admin'),
('english', 'admin.subscribers', 'Subscribers', 'admin'),
('english', 'admin.view_manage_subscriptions', 'View and manage all active subscriptions', 'admin'),
('english', 'admin.search_by_user', 'Search by user name...', 'admin'),
('english', 'admin.filter_by_plan', 'Filter by plan', 'admin'),
('english', 'admin.all_plans', 'All Plans', 'admin'),
('english', 'admin.plan', 'Plan', 'admin'),
('english', 'admin.start_date', 'Start Date', 'admin'),
('english', 'admin.expires', 'Expires', 'admin'),
('english', 'admin.never', 'Never', 'admin'),
('english', 'admin.loading_subscribers', 'Loading subscribers...', 'admin'),
('english', 'admin.no_subscribers_found', 'No subscribers found', 'admin'),
('english', 'admin.subscription_cancelled', 'Subscription cancelled successfully', 'admin'),
('english', 'admin.subscription_cancel_failed', 'Failed to cancel subscription', 'admin'),
('english', 'common.previous', 'Previous', 'common'),
('english', 'common.next', 'Next', 'common'),
('english', 'common.page_of', 'Page {{current}} of {{total}}', 'common'),

-- RateLimitsPage
('english', 'admin.rate_limits_management', 'Rate Limits Management', 'admin'),
('english', 'admin.monitor_rate_limits', 'Monitor and manage message rate limits ({{count}} users tracked)', 'admin'),
('english', 'admin.message_rate_limits', 'Message Rate Limits', 'admin'),
('english', 'admin.search_by_user_id', 'Search by user ID...', 'admin'),
('english', 'admin.loading_rate_limits', 'Loading rate limits...', 'admin'),
('english', 'admin.no_rate_limits', 'No rate limits found', 'admin'),
('english', 'admin.messages_count', '{{count}} messages', 'admin'),
('english', 'admin.reset_rate_limit', 'Reset', 'admin'),
('english', 'admin.reset_confirm', 'Are you sure you want to reset this rate limit?', 'admin'),
('english', 'admin.rate_limit_reset', 'Rate limit reset successfully', 'admin'),
('english', 'admin.rate_limit_reset_failed', 'Failed to reset rate limit', 'admin'),
('english', 'admin.tracked_since', 'Tracked since: {{date}}', 'admin'),

-- DailyUsagePage
('english', 'admin.daily_usage_analytics', 'Daily Usage Analytics', 'admin'),
('english', 'admin.track_usage_per_day', 'Track user feature usage per day ({{count}} records)', 'admin'),
('english', 'admin.daily_usage_statistics', 'Daily Usage Statistics', 'admin'),
('english', 'admin.loading_usage_data', 'Loading usage data...', 'admin'),
('english', 'admin.no_usage_data', 'No usage data found', 'admin'),
('english', 'admin.failed_load_usage', 'Failed to load usage data', 'admin'),
('english', 'admin.total_actions', '{{count}} total actions', 'admin'),
('english', 'admin.likes', 'Likes', 'admin'),
('english', 'admin.super_likes', 'Super Likes', 'admin'),
('english', 'admin.rewinds', 'Rewinds', 'admin'),
('english', 'admin.boosts', 'Boosts', 'admin'),
('english', 'admin.last_updated', 'Last updated: {{date}}', 'admin'),

-- Norwegian translations
('norwegian', 'admin.notifications_management', 'Varselstyring', 'admin'),
('norwegian', 'admin.view_manage_notifications', 'Se og administrer alle systemvarsler ({{count}} totalt)', 'admin'),
('norwegian', 'admin.all_notifications', 'Alle varsler', 'admin'),
('norwegian', 'admin.search_notifications', 'Søk i varsler...', 'admin'),
('norwegian', 'admin.loading_notifications', 'Laster varsler...', 'admin'),
('norwegian', 'admin.no_notifications_found', 'Ingen varsler funnet', 'admin'),
('norwegian', 'admin.delete_notification_confirm', 'Er du sikker på at du vil slette dette varselet?', 'admin'),
('norwegian', 'admin.notification_deleted', 'Varsel slettet', 'admin'),
('norwegian', 'admin.notification_delete_failed', 'Kunne ikke slette varsel', 'admin'),
('norwegian', 'admin.failed_load_notifications', 'Kunne ikke laste varsler', 'admin'),
('norwegian', 'common.all', 'Alle', 'common'),
('norwegian', 'common.unread', 'Ulest', 'common'),
('norwegian', 'common.read', 'Lest', 'common'),
('norwegian', 'common.refresh', 'Oppdater', 'common'),
('norwegian', 'common.user', 'Bruker', 'common'),
('norwegian', 'admin.user_verification', 'Brukerverifisering', 'admin'),
('norwegian', 'admin.verification_history', 'Historikk', 'admin'),
('norwegian', 'admin.verification_settings', 'Verifiseringsinnstillinger', 'admin'),
('norwegian', 'admin.ai_enhanced_verification', 'AI-forbedret verifisering', 'admin'),
('norwegian', 'admin.ai_verification_desc', 'Vårt AI-system forhåndsvaliderer dokumenter og markerer potensielle problemer for gjennomgang', 'admin'),
('norwegian', 'admin.pending_review', 'Venter på gjennomgang', 'admin'),
('norwegian', 'admin.verified', 'Verifisert', 'admin'),
('norwegian', 'admin.rejected', 'Avvist', 'admin'),
('norwegian', 'admin.ai_flagged', 'AI-markert', 'admin'),
('norwegian', 'admin.search_name_email', 'Søk etter navn eller e-post...', 'admin'),
('norwegian', 'admin.filter_by_status', 'Filtrer etter status', 'admin'),
('norwegian', 'admin.all_statuses', 'Alle statuser', 'admin'),
('norwegian', 'admin.document_type', 'Dokumenttype', 'admin'),
('norwegian', 'admin.submitted', 'Innsendt', 'admin'),
('norwegian', 'admin.priority', 'Prioritet', 'admin'),
('norwegian', 'admin.high', 'Høy', 'admin'),
('norwegian', 'admin.medium', 'Middels', 'admin'),
('norwegian', 'admin.normal', 'Normal', 'admin'),
('norwegian', 'admin.no_flagged_requests', 'Ingen AI-markerte forespørsler funnet', 'admin'),
('norwegian', 'admin.no_verification_requests', 'Ingen {{status}} verifiseringsforespørsler funnet', 'admin'),
('norwegian', 'admin.loading_verification', 'Laster verifiseringsforespørsler...', 'admin'),
('norwegian', 'admin.ghost_users', 'Spøkelsesbrukere', 'admin'),
('norwegian', 'admin.ghost_users_desc', 'Generer og administrer automatisk genererte profiler', 'admin'),
('norwegian', 'admin.publish_due_content', 'Publiser forfalt innhold', 'admin'),
('norwegian', 'admin.regenerate_activity', 'Regenerer aktivitet', 'admin'),
('norwegian', 'admin.generate_users', 'Generer brukere', 'admin'),
('norwegian', 'admin.generate_ghost_users', 'Generer spøkelsesbrukere', 'admin'),
('norwegian', 'admin.create_realistic_profiles', 'Opprett realistiske automatisk genererte profiler', 'admin'),
('norwegian', 'admin.number_of_users', 'Antall brukere', 'admin'),
('norwegian', 'admin.gender', 'Kjønn', 'admin'),
('norwegian', 'admin.mixed', 'Blandet', 'admin'),
('norwegian', 'admin.male_only', 'Kun menn', 'admin'),
('norwegian', 'admin.female_only', 'Kun kvinner', 'admin'),
('norwegian', 'admin.region_optional', 'Region (valgfritt)', 'admin'),
('norwegian', 'admin.all_regions', 'Alle regioner', 'admin'),
('norwegian', 'admin.content_options', 'Innholdsvalg', 'admin'),
('norwegian', 'admin.generate_posts', 'Generer innlegg (2-5 per bruker)', 'admin'),
('norwegian', 'admin.generate_stories', 'Generer historier (1-3 per bruker)', 'admin'),
('norwegian', 'admin.generate_profile_photos', 'Generer profilbilder (2-4 per bruker)', 'admin'),
('norwegian', 'admin.set_verified_profiles', 'Sett som verifiserte profiler', 'admin'),
('norwegian', 'admin.generating_progress', 'Genererer {{current}} / {{total}}', 'admin'),
('norwegian', 'admin.generation_complete', 'Generering fullført', 'admin'),
('norwegian', 'admin.generation_result', 'Opprettet {{count}} spøkelsesbrukere.', 'admin'),
('norwegian', 'admin.delete_all_ghost_users', 'Slett alle spøkelsesbrukere', 'admin'),
('norwegian', 'admin.delete_all_ghost_confirm', 'Dette vil permanent fjerne alle {{count}} spøkelsesbrukere og deres innlegg, historier, bilder og planlagt innhold.', 'admin'),
('norwegian', 'admin.all_ghost_deleted', 'Alle spøkelsesbrukere slettet', 'admin'),
('norwegian', 'admin.ghost_deleted_result', 'Fjernet {{count}} spøkelsesbrukere og deres innhold.', 'admin'),
('norwegian', 'admin.ghost_user_deleted', 'Spøkelsesbruker slettet', 'admin'),
('norwegian', 'admin.published_content', 'Publisert innhold', 'admin'),
('norwegian', 'admin.activity_regenerated', 'Aktivitet regenerert', 'admin'),
('norwegian', 'admin.total_posts', 'Totalt innlegg', 'admin'),
('norwegian', 'admin.scheduled_content', 'Planlagt innhold', 'admin'),
('norwegian', 'admin.no_ghost_users', 'Ingen spøkelsesbrukere ennå. Generer noen for å komme i gang.', 'admin'),
('norwegian', 'common.name', 'Navn', 'common'),
('norwegian', 'common.gender', 'Kjønn', 'common'),
('norwegian', 'common.location', 'Sted', 'common'),
('norwegian', 'common.created', 'Opprettet', 'common'),
('norwegian', 'common.last_active', 'Sist aktiv', 'common'),
('norwegian', 'common.cancel', 'Avbryt', 'common'),
('norwegian', 'common.generate', 'Generer', 'common'),
('norwegian', 'common.generating', 'Genererer...', 'common'),
('norwegian', 'common.delete_all', 'Slett alle', 'common'),
('norwegian', 'common.loading', 'Laster...', 'common'),
('norwegian', 'admin.virtual_gifts', 'Virtuelle gaver', 'admin'),
('norwegian', 'admin.active_total_gifts', '{{active}} aktive · {{total}} totalt gaver', 'admin'),
('norwegian', 'admin.add_gift', 'Legg til gave', 'admin'),
('norwegian', 'admin.edit_gift', 'Rediger gave', 'admin'),
('norwegian', 'admin.create_gift', 'Opprett gave', 'admin'),
('norwegian', 'admin.update_gift', 'Oppdater gave', 'admin'),
('norwegian', 'admin.emoji', 'Emoji', 'admin'),
('norwegian', 'admin.price_coins', 'Pris (mynter)', 'admin'),
('norwegian', 'admin.sort_order', 'Sorteringsrekkefølge', 'admin'),
('norwegian', 'admin.premium_only', 'Kun premium', 'admin'),
('norwegian', 'admin.gift_updated', 'Gave oppdatert', 'admin'),
('norwegian', 'admin.gift_created', 'Gave opprettet', 'admin'),
('norwegian', 'admin.name_emoji_required', 'Navn og emoji er påkrevd', 'admin'),
('norwegian', 'admin.subscriber_management', 'Abonnentstyring', 'admin'),
('norwegian', 'admin.manage_subscriptions', 'Administrer premiumabonnementer', 'admin'),
('norwegian', 'admin.total_subscribers', 'Totalt abonnenter', 'admin'),
('norwegian', 'admin.basic_plan', 'Basisplan', 'admin'),
('norwegian', 'admin.premium_plan', 'Premiumplan', 'admin'),
('norwegian', 'admin.monthly_revenue', 'Månedlig inntekt', 'admin'),
('norwegian', 'admin.subscribers', 'Abonnenter', 'admin'),
('norwegian', 'admin.view_manage_subscriptions', 'Se og administrer alle aktive abonnementer', 'admin'),
('norwegian', 'admin.filter_by_plan', 'Filtrer etter plan', 'admin'),
('norwegian', 'admin.all_plans', 'Alle planer', 'admin'),
('norwegian', 'admin.plan', 'Plan', 'admin'),
('norwegian', 'admin.start_date', 'Startdato', 'admin'),
('norwegian', 'admin.expires', 'Utløper', 'admin'),
('norwegian', 'admin.never', 'Aldri', 'admin'),
('norwegian', 'admin.loading_subscribers', 'Laster abonnenter...', 'admin'),
('norwegian', 'admin.no_subscribers_found', 'Ingen abonnenter funnet', 'admin'),
('norwegian', 'admin.subscription_cancelled', 'Abonnement kansellert', 'admin'),
('norwegian', 'admin.subscription_cancel_failed', 'Kunne ikke kansellere abonnement', 'admin'),
('norwegian', 'common.previous', 'Forrige', 'common'),
('norwegian', 'common.next', 'Neste', 'common'),
('norwegian', 'common.page_of', 'Side {{current}} av {{total}}', 'common'),
('norwegian', 'admin.rate_limits_management', 'Hastighetsbegrensninger', 'admin'),
('norwegian', 'admin.monitor_rate_limits', 'Overvåk og administrer meldingsbegrensninger ({{count}} brukere sporet)', 'admin'),
('norwegian', 'admin.message_rate_limits', 'Meldingsbegrensninger', 'admin'),
('norwegian', 'admin.search_by_user_id', 'Søk etter bruker-ID...', 'admin'),
('norwegian', 'admin.loading_rate_limits', 'Laster begrensninger...', 'admin'),
('norwegian', 'admin.no_rate_limits', 'Ingen begrensninger funnet', 'admin'),
('norwegian', 'admin.messages_count', '{{count}} meldinger', 'admin'),
('norwegian', 'admin.reset_rate_limit', 'Tilbakestill', 'admin'),
('norwegian', 'admin.reset_confirm', 'Er du sikker på at du vil tilbakestille denne begrensningen?', 'admin'),
('norwegian', 'admin.rate_limit_reset', 'Begrensning tilbakestilt', 'admin'),
('norwegian', 'admin.rate_limit_reset_failed', 'Kunne ikke tilbakestille begrensning', 'admin'),
('norwegian', 'admin.tracked_since', 'Sporet siden: {{date}}', 'admin'),
('norwegian', 'admin.daily_usage_analytics', 'Daglig bruksanalyse', 'admin'),
('norwegian', 'admin.track_usage_per_day', 'Spor brukerens funksjonsbruk per dag ({{count}} oppføringer)', 'admin'),
('norwegian', 'admin.daily_usage_statistics', 'Daglig bruksstatistikk', 'admin'),
('norwegian', 'admin.loading_usage_data', 'Laster bruksdata...', 'admin'),
('norwegian', 'admin.no_usage_data', 'Ingen bruksdata funnet', 'admin'),
('norwegian', 'admin.failed_load_usage', 'Kunne ikke laste bruksdata', 'admin'),
('norwegian', 'admin.total_actions', '{{count}} totale handlinger', 'admin'),
('norwegian', 'admin.likes', 'Likerklikk', 'admin'),
('norwegian', 'admin.super_likes', 'Superlikerklikk', 'admin'),
('norwegian', 'admin.rewinds', 'Spoling tilbake', 'admin'),
('norwegian', 'admin.boosts', 'Boost', 'admin'),
('norwegian', 'admin.last_updated', 'Sist oppdatert: {{date}}', 'admin'),

-- Kurdish Sorani translations
('kurdish_sorani', 'admin.notifications_management', 'بەڕێوەبردنی ئاگاداریەکان', 'admin'),
('kurdish_sorani', 'admin.view_manage_notifications', 'بینین و بەڕێوەبردنی هەموو ئاگاداریەکانی سیستەم ({{count}} کۆی گشتی)', 'admin'),
('kurdish_sorani', 'admin.all_notifications', 'هەموو ئاگاداریەکان', 'admin'),
('kurdish_sorani', 'admin.search_notifications', 'گەڕان لە ئاگاداریەکان...', 'admin'),
('kurdish_sorani', 'admin.loading_notifications', 'بارکردنی ئاگاداریەکان...', 'admin'),
('kurdish_sorani', 'admin.no_notifications_found', 'هیچ ئاگاداریەک نەدۆزرایەوە', 'admin'),
('kurdish_sorani', 'common.all', 'هەموو', 'common'),
('kurdish_sorani', 'common.unread', 'نەخوێنراوە', 'common'),
('kurdish_sorani', 'common.read', 'خوێنراوە', 'common'),
('kurdish_sorani', 'common.refresh', 'نوێکردنەوە', 'common'),
('kurdish_sorani', 'common.user', 'بەکارهێنەر', 'common'),
('kurdish_sorani', 'admin.user_verification', 'پشتڕاستکردنەوەی بەکارهێنەر', 'admin'),
('kurdish_sorani', 'admin.ghost_users', 'بەکارهێنەرە خەیاڵییەکان', 'admin'),
('kurdish_sorani', 'admin.virtual_gifts', 'دیاریە ڤێرچواڵەکان', 'admin'),
('kurdish_sorani', 'admin.subscriber_management', 'بەڕێوەبردنی بەشداربووان', 'admin'),
('kurdish_sorani', 'admin.rate_limits_management', 'بەڕێوەبردنی سنووری خێرایی', 'admin'),
('kurdish_sorani', 'admin.daily_usage_analytics', 'شیکاری بەکارهێنانی ڕۆژانە', 'admin'),
('kurdish_sorani', 'common.previous', 'پێشوو', 'common'),
('kurdish_sorani', 'common.next', 'دواتر', 'common'),
('kurdish_sorani', 'common.cancel', 'پاشگەزبوونەوە', 'common'),
('kurdish_sorani', 'common.loading', 'بارکردن...', 'common'),
('kurdish_sorani', 'common.name', 'ناو', 'common'),
('kurdish_sorani', 'common.location', 'شوێن', 'common'),

-- Kurdish Kurmanji translations
('kurdish_kurmanji', 'admin.notifications_management', 'Birêvebirina agahdariyan', 'admin'),
('kurdish_kurmanji', 'admin.all_notifications', 'Hemû agahdarî', 'admin'),
('kurdish_kurmanji', 'common.all', 'Hemû', 'common'),
('kurdish_kurmanji', 'common.unread', 'Nexwendî', 'common'),
('kurdish_kurmanji', 'common.read', 'Xwendî', 'common'),
('kurdish_kurmanji', 'common.refresh', 'Nûkirin', 'common'),
('kurdish_kurmanji', 'common.user', 'Bikarhêner', 'common'),
('kurdish_kurmanji', 'admin.user_verification', 'Verastkirina bikarhêner', 'admin'),
('kurdish_kurmanji', 'admin.ghost_users', 'Bikarhênerên xeyalî', 'admin'),
('kurdish_kurmanji', 'admin.virtual_gifts', 'Diyariyên virtual', 'admin'),
('kurdish_kurmanji', 'admin.subscriber_management', 'Birêvebirina abonan', 'admin'),
('kurdish_kurmanji', 'admin.rate_limits_management', 'Birêvebirina sînorên lezê', 'admin'),
('kurdish_kurmanji', 'admin.daily_usage_analytics', 'Analîza bikaranîna rojane', 'admin'),
('kurdish_kurmanji', 'common.previous', 'Berê', 'common'),
('kurdish_kurmanji', 'common.next', 'Paşê', 'common'),
('kurdish_kurmanji', 'common.cancel', 'Betal', 'common'),
('kurdish_kurmanji', 'common.loading', 'Tê barkirin...', 'common'),
('kurdish_kurmanji', 'common.name', 'Nav', 'common'),
('kurdish_kurmanji', 'common.location', 'Cih', 'common'),

-- German translations
('german', 'admin.notifications_management', 'Benachrichtigungsverwaltung', 'admin'),
('german', 'admin.view_manage_notifications', 'Alle Systembenachrichtigungen anzeigen und verwalten ({{count}} insgesamt)', 'admin'),
('german', 'admin.all_notifications', 'Alle Benachrichtigungen', 'admin'),
('german', 'admin.search_notifications', 'Benachrichtigungen suchen...', 'admin'),
('german', 'admin.loading_notifications', 'Benachrichtigungen laden...', 'admin'),
('german', 'admin.no_notifications_found', 'Keine Benachrichtigungen gefunden', 'admin'),
('german', 'common.all', 'Alle', 'common'),
('german', 'common.unread', 'Ungelesen', 'common'),
('german', 'common.read', 'Gelesen', 'common'),
('german', 'common.refresh', 'Aktualisieren', 'common'),
('german', 'common.user', 'Benutzer', 'common'),
('german', 'admin.user_verification', 'Benutzerverifizierung', 'admin'),
('german', 'admin.ghost_users', 'Geisterbenutzer', 'admin'),
('german', 'admin.ghost_users_desc', 'Automatisch generierte Profile erstellen und verwalten', 'admin'),
('german', 'admin.virtual_gifts', 'Virtuelle Geschenke', 'admin'),
('german', 'admin.subscriber_management', 'Abonnentenverwaltung', 'admin'),
('german', 'admin.manage_subscriptions', 'Premium-Abonnements verwalten', 'admin'),
('german', 'admin.total_subscribers', 'Gesamtabonnenten', 'admin'),
('german', 'admin.basic_plan', 'Basisplan', 'admin'),
('german', 'admin.premium_plan', 'Premium-Plan', 'admin'),
('german', 'admin.monthly_revenue', 'Monatlicher Umsatz', 'admin'),
('german', 'admin.rate_limits_management', 'Ratenlimit-Verwaltung', 'admin'),
('german', 'admin.daily_usage_analytics', 'Tägliche Nutzungsanalyse', 'admin'),
('german', 'common.previous', 'Zurück', 'common'),
('german', 'common.next', 'Weiter', 'common'),
('german', 'common.cancel', 'Abbrechen', 'common'),
('german', 'common.loading', 'Laden...', 'common'),
('german', 'common.name', 'Name', 'common'),
('german', 'common.location', 'Standort', 'common'),
('german', 'admin.likes', 'Likes', 'admin'),
('german', 'admin.super_likes', 'Super Likes', 'admin'),
('german', 'admin.rewinds', 'Zurückspulen', 'admin'),
('german', 'admin.boosts', 'Boosts', 'admin')
ON CONFLICT DO NOTHING;
