
INSERT INTO public.app_translations (language_code, translation_key, translation_value, category, context) VALUES
-- CreateSuperAdmin
('english','admin.email_password_required','Email and password are required','admin','CreateSuperAdmin'),
('english','admin.admin_created','Super admin account created for {{email}}','admin','CreateSuperAdmin'),
('english','admin.login_info','Use email: {{email}} and your password to login','admin','CreateSuperAdmin'),
('english','admin.create_admin_failed','Failed to create super admin account','admin','CreateSuperAdmin'),
('english','admin.create_super_admin','Create Super Admin','admin','CreateSuperAdmin'),
('english','admin.create_admin_desc','Set up your super admin account to access the admin dashboard','admin','CreateSuperAdmin'),
('english','admin.enter_secure_password','Enter secure password','admin','CreateSuperAdmin'),
('english','admin.name_optional','Name (Optional)','admin','CreateSuperAdmin'),
('english','admin.your_name','Your name','admin','CreateSuperAdmin'),
('english','admin.creating_admin','Creating Admin Account...','admin','CreateSuperAdmin'),
('english','admin.full_access_note','This will create a super admin account with full access to the system.','admin','CreateSuperAdmin'),
('norwegian','admin.email_password_required','E-post og passord er påkrevd','admin','CreateSuperAdmin'),
('norwegian','admin.admin_created','Superadmin-konto opprettet for {{email}}','admin','CreateSuperAdmin'),
('norwegian','admin.login_info','Bruk e-post: {{email}} og passordet ditt for å logge inn','admin','CreateSuperAdmin'),
('norwegian','admin.create_admin_failed','Kunne ikke opprette superadmin-konto','admin','CreateSuperAdmin'),
('norwegian','admin.create_super_admin','Opprett superadmin','admin','CreateSuperAdmin'),
('norwegian','admin.create_admin_desc','Sett opp superadmin-kontoen din for å få tilgang til administrasjonspanelet','admin','CreateSuperAdmin'),
('norwegian','admin.enter_secure_password','Skriv inn sikkert passord','admin','CreateSuperAdmin'),
('norwegian','admin.name_optional','Navn (valgfritt)','admin','CreateSuperAdmin'),
('norwegian','admin.your_name','Ditt navn','admin','CreateSuperAdmin'),
('norwegian','admin.creating_admin','Oppretter admin-konto...','admin','CreateSuperAdmin'),
('norwegian','admin.full_access_note','Dette vil opprette en superadmin-konto med full tilgang til systemet.','admin','CreateSuperAdmin'),
('german','admin.email_password_required','E-Mail und Passwort sind erforderlich','admin','CreateSuperAdmin'),
('german','admin.admin_created','Super-Admin-Konto erstellt für {{email}}','admin','CreateSuperAdmin'),
('german','admin.login_info','Verwenden Sie E-Mail: {{email}} und Ihr Passwort zum Anmelden','admin','CreateSuperAdmin'),
('german','admin.create_admin_failed','Super-Admin-Konto konnte nicht erstellt werden','admin','CreateSuperAdmin'),
('german','admin.create_super_admin','Super-Admin erstellen','admin','CreateSuperAdmin'),
('german','admin.create_admin_desc','Richten Sie Ihr Super-Admin-Konto ein, um auf das Admin-Dashboard zuzugreifen','admin','CreateSuperAdmin'),
('german','admin.enter_secure_password','Sicheres Passwort eingeben','admin','CreateSuperAdmin'),
('german','admin.name_optional','Name (optional)','admin','CreateSuperAdmin'),
('german','admin.your_name','Ihr Name','admin','CreateSuperAdmin'),
('german','admin.creating_admin','Admin-Konto wird erstellt...','admin','CreateSuperAdmin'),
('german','admin.full_access_note','Dies erstellt ein Super-Admin-Konto mit vollem Zugriff auf das System.','admin','CreateSuperAdmin'),
('kurdish_sorani','admin.email_password_required','ئیمەیل و وشەی نهێنی پێویستە','admin','CreateSuperAdmin'),
('kurdish_sorani','admin.admin_created','هەژماری سوپەر ئەدمین دروستکرا بۆ {{email}}','admin','CreateSuperAdmin'),
('kurdish_sorani','admin.login_info','ئیمەیل: {{email}} و وشەی نهێنیت بەکاربهێنە بۆ چوونەژوورەوە','admin','CreateSuperAdmin'),
('kurdish_sorani','admin.create_admin_failed','دروستکردنی هەژماری سوپەر ئەدمین سەرکەوتوو نەبوو','admin','CreateSuperAdmin'),
('kurdish_sorani','admin.create_super_admin','دروستکردنی سوپەر ئەدمین','admin','CreateSuperAdmin'),
('kurdish_sorani','admin.create_admin_desc','هەژماری سوپەر ئەدمینت دابنێ بۆ دەستگەیشتن بە داشبۆردی بەڕێوەبەری','admin','CreateSuperAdmin'),
('kurdish_sorani','admin.enter_secure_password','وشەی نهێنی پارێزراو بنووسە','admin','CreateSuperAdmin'),
('kurdish_sorani','admin.name_optional','ناو (ئارەزوومەندانە)','admin','CreateSuperAdmin'),
('kurdish_sorani','admin.your_name','ناوی تۆ','admin','CreateSuperAdmin'),
('kurdish_sorani','admin.creating_admin','دروستکردنی هەژماری ئەدمین...','admin','CreateSuperAdmin'),
('kurdish_sorani','admin.full_access_note','ئەمە هەژمارێکی سوپەر ئەدمین دروست دەکات کە دەستگەیشتنی تەواوی بە سیستەمەکە هەیە.','admin','CreateSuperAdmin'),
('kurdish_kurmanci','admin.email_password_required','E-name û şîfre hewce ne','admin','CreateSuperAdmin'),
('kurdish_kurmanci','admin.admin_created','Hesabê super admin ji bo {{email}} hat afirandin','admin','CreateSuperAdmin'),
('kurdish_kurmanci','admin.login_info','E-name: {{email}} û şîfreya xwe bikar bînin bo têketinê','admin','CreateSuperAdmin'),
('kurdish_kurmanci','admin.create_admin_failed','Afirandina hesabê super admin bi ser neket','admin','CreateSuperAdmin'),
('kurdish_kurmanci','admin.create_super_admin','Super Admin biafirîne','admin','CreateSuperAdmin'),
('kurdish_kurmanci','admin.create_admin_desc','Hesabê super admin saz bikin bo gihîştina panela rêveberiyê','admin','CreateSuperAdmin'),
('kurdish_kurmanci','admin.enter_secure_password','Şîfreya ewle binivisînin','admin','CreateSuperAdmin'),
('kurdish_kurmanci','admin.name_optional','Nav (bijartî)','admin','CreateSuperAdmin'),
('kurdish_kurmanci','admin.your_name','Navê te','admin','CreateSuperAdmin'),
('kurdish_kurmanci','admin.creating_admin','Hesabê admin tê afirandin...','admin','CreateSuperAdmin'),
('kurdish_kurmanci','admin.full_access_note','Ev ê hesabek super admin bi gihîştina tevahî ya sîstemê biafirîne.','admin','CreateSuperAdmin'),

-- GroupDetail
('english','groups.left_group','Left group','discovery','GroupDetail'),
('english','groups.joined_group','Joined group','discovery','GroupDetail'),
('english','groups.loading','Loading group...','discovery','GroupDetail'),
('english','groups.category','Category','discovery','GroupDetail'),
('english','groups.privacy','Privacy','discovery','GroupDetail'),
('english','groups.created','Created','discovery','GroupDetail'),
('norwegian','groups.left_group','Forlot gruppen','discovery','GroupDetail'),
('norwegian','groups.joined_group','Ble med i gruppen','discovery','GroupDetail'),
('norwegian','groups.loading','Laster gruppe...','discovery','GroupDetail'),
('norwegian','groups.category','Kategori','discovery','GroupDetail'),
('norwegian','groups.privacy','Personvern','discovery','GroupDetail'),
('norwegian','groups.created','Opprettet','discovery','GroupDetail'),
('german','groups.left_group','Gruppe verlassen','discovery','GroupDetail'),
('german','groups.joined_group','Gruppe beigetreten','discovery','GroupDetail'),
('german','groups.loading','Gruppe wird geladen...','discovery','GroupDetail'),
('german','groups.category','Kategorie','discovery','GroupDetail'),
('german','groups.privacy','Datenschutz','discovery','GroupDetail'),
('german','groups.created','Erstellt','discovery','GroupDetail'),
('kurdish_sorani','groups.left_group','گروپەکەت جێهێشت','discovery','GroupDetail'),
('kurdish_sorani','groups.joined_group','چووە ناو گروپەکە','discovery','GroupDetail'),
('kurdish_sorani','groups.loading','گروپ بارکردن...','discovery','GroupDetail'),
('kurdish_sorani','groups.category','پۆل','discovery','GroupDetail'),
('kurdish_sorani','groups.privacy','تایبەتمەندی','discovery','GroupDetail'),
('kurdish_sorani','groups.created','دروستکرا','discovery','GroupDetail'),
('kurdish_kurmanci','groups.left_group','Ji grupê derket','discovery','GroupDetail'),
('kurdish_kurmanci','groups.joined_group','Ket nav grupê','discovery','GroupDetail'),
('kurdish_kurmanci','groups.loading','Grup tê barkirin...','discovery','GroupDetail'),
('kurdish_kurmanci','groups.category','Beş','discovery','GroupDetail'),
('kurdish_kurmanci','groups.privacy','Nepenîtî','discovery','GroupDetail'),
('kurdish_kurmanci','groups.created','Hatiye afirandin','discovery','GroupDetail'),

-- EventDetail
('english','events.going_label','going','discovery','EventDetail'),
('english','events.max_capacity','max capacity','discovery','EventDetail'),
('norwegian','events.going_label','kommer','discovery','EventDetail'),
('norwegian','events.max_capacity','maks kapasitet','discovery','EventDetail'),
('german','events.going_label','kommen','discovery','EventDetail'),
('german','events.max_capacity','maximale Kapazität','discovery','EventDetail'),
('kurdish_sorani','events.going_label','دەچن','discovery','EventDetail'),
('kurdish_sorani','events.max_capacity','زۆرترین گنجایش','discovery','EventDetail'),
('kurdish_kurmanci','events.going_label','diçin','discovery','EventDetail'),
('kurdish_kurmanci','events.max_capacity','kapasîteya herî zêde','discovery','EventDetail'),

-- LikedMe
('english','liked_me.pass','Pass','discovery','LikedMe'),
('english','liked_me.mutual_like','Mutual Like','discovery','LikedMe'),
('english','liked_me.send_message','Send message','discovery','LikedMe'),
('english','common.more','more','common','general'),
('norwegian','liked_me.pass','Hopp over','discovery','LikedMe'),
('norwegian','liked_me.mutual_like','Gjensidig like','discovery','LikedMe'),
('norwegian','liked_me.send_message','Send melding','discovery','LikedMe'),
('norwegian','common.more','flere','common','general'),
('german','liked_me.pass','Überspringen','discovery','LikedMe'),
('german','liked_me.mutual_like','Gegenseitiges Like','discovery','LikedMe'),
('german','liked_me.send_message','Nachricht senden','discovery','LikedMe'),
('german','common.more','mehr','common','general'),
('kurdish_sorani','liked_me.pass','تێپەڕاندن','discovery','LikedMe'),
('kurdish_sorani','liked_me.mutual_like','لایکی هاوبەش','discovery','LikedMe'),
('kurdish_sorani','liked_me.send_message','نامە بنێرە','discovery','LikedMe'),
('kurdish_sorani','common.more','زیاتر','common','general'),
('kurdish_kurmanci','liked_me.pass','Derbas bike','discovery','LikedMe'),
('kurdish_kurmanci','liked_me.mutual_like','Like hevpar','discovery','LikedMe'),
('kurdish_kurmanci','liked_me.send_message','Peyam bişîne','discovery','LikedMe'),
('kurdish_kurmanci','common.more','zêdetir','common','general')

ON CONFLICT (language_code, translation_key) DO NOTHING;
