
-- Batch 19-21: i18n remaining admin strings
INSERT INTO public.app_translations (language_code, translation_key, translation_value, category, context) VALUES
-- InterestsPage toast messages
('english','admin.failed_load_interests','Failed to load interests','admin','toast'),
('norwegian','admin.failed_load_interests','Kunne ikke laste interesser','admin','toast'),
('german','admin.failed_load_interests','Interessen konnten nicht geladen werden','admin','toast'),
('kurdish_sorani','admin.failed_load_interests','ناتوانرێت ئارەزووەکان بار بکرێت','admin','toast'),
('kurdish_kurmanji','admin.failed_load_interests','Eleqe nehatin barkirin','admin','toast'),
('english','admin.please_fill_all_fields','Please fill in all fields','admin','toast'),
('norwegian','admin.please_fill_all_fields','Vennligst fyll ut alle feltene','admin','toast'),
('german','admin.please_fill_all_fields','Bitte füllen Sie alle Felder aus','admin','toast'),
('kurdish_sorani','admin.please_fill_all_fields','تکایە هەموو خانەکان پڕبکەوە','admin','toast'),
('kurdish_kurmanji','admin.please_fill_all_fields','Ji kerema xwe hemû qadan dagirin','admin','toast'),
('english','admin.interest_added','Interest added successfully','admin','toast'),
('norwegian','admin.interest_added','Interesse lagt til','admin','toast'),
('german','admin.interest_added','Interesse erfolgreich hinzugefügt','admin','toast'),
('kurdish_sorani','admin.interest_added','ئارەزوو بە سەرکەوتوویی زیادکرا','admin','toast'),
('kurdish_kurmanji','admin.interest_added','Eleqe bi serkeftî hat zêdekirin','admin','toast'),
('english','admin.failed_add_interest','Failed to add interest','admin','toast'),
('norwegian','admin.failed_add_interest','Kunne ikke legge til interesse','admin','toast'),
('german','admin.failed_add_interest','Interesse konnte nicht hinzugefügt werden','admin','toast'),
('kurdish_sorani','admin.failed_add_interest','ناتوانرێت ئارەزوو زیاد بکرێت','admin','toast'),
('kurdish_kurmanji','admin.failed_add_interest','Eleqe nehate zêdekirin','admin','toast'),

-- CommentsPage toast messages
('english','admin.failed_load_comment_likes','Failed to load comment likes','admin','toast'),
('norwegian','admin.failed_load_comment_likes','Kunne ikke laste kommentarlikes','admin','toast'),
('german','admin.failed_load_comment_likes','Kommentar-Likes konnten nicht geladen werden','admin','toast'),
('kurdish_sorani','admin.failed_load_comment_likes','ناتوانرێت لایکەکانی لێدوان بار بکرێت','admin','toast'),
('kurdish_kurmanji','admin.failed_load_comment_likes','Hezkirinên şîroveyan nehatin barkirin','admin','toast'),
('english','admin.confirm_delete_comment_like','Are you sure you want to delete this comment like?','admin','confirm'),
('norwegian','admin.confirm_delete_comment_like','Er du sikker på at du vil slette denne kommentarliken?','admin','confirm'),
('german','admin.confirm_delete_comment_like','Möchten Sie dieses Kommentar-Like wirklich löschen?','admin','confirm'),
('kurdish_sorani','admin.confirm_delete_comment_like','دڵنیایت دەتەوێ ئەم لایکەی لێدوان بسڕیتەوە؟','admin','confirm'),
('kurdish_kurmanji','admin.confirm_delete_comment_like','Tu bawer î ku dixwazî vê hezkirina şîroveyê jêbirî?','admin','confirm'),
('english','admin.comment_like_deleted','Comment like deleted successfully','admin','toast'),
('norwegian','admin.comment_like_deleted','Kommentarlike slettet','admin','toast'),
('german','admin.comment_like_deleted','Kommentar-Like erfolgreich gelöscht','admin','toast'),
('kurdish_sorani','admin.comment_like_deleted','لایکی لێدوان بە سەرکەوتوویی سڕایەوە','admin','toast'),
('kurdish_kurmanji','admin.comment_like_deleted','Hezkirina şîroveyê bi serkeftî hat jêbirin','admin','toast'),
('english','admin.failed_delete_comment_like','Failed to delete comment like','admin','toast'),
('norwegian','admin.failed_delete_comment_like','Kunne ikke slette kommentarlike','admin','toast'),
('german','admin.failed_delete_comment_like','Kommentar-Like konnte nicht gelöscht werden','admin','toast'),
('kurdish_sorani','admin.failed_delete_comment_like','ناتوانرێت لایکی لێدوان بسڕدرێتەوە','admin','toast'),
('kurdish_kurmanji','admin.failed_delete_comment_like','Hezkirina şîroveyê nehate jêbirin','admin','toast'),

-- GroupsManagementPage toast messages
('english','admin.failed_load_groups','Failed to load groups','admin','toast'),
('norwegian','admin.failed_load_groups','Kunne ikke laste grupper','admin','toast'),
('german','admin.failed_load_groups','Gruppen konnten nicht geladen werden','admin','toast'),
('kurdish_sorani','admin.failed_load_groups','ناتوانرێت گرووپەکان بار بکرێن','admin','toast'),
('kurdish_kurmanji','admin.failed_load_groups','Kom nehatin barkirin','admin','toast'),
('english','admin.failed_load_members','Failed to load members','admin','toast'),
('norwegian','admin.failed_load_members','Kunne ikke laste medlemmer','admin','toast'),
('german','admin.failed_load_members','Mitglieder konnten nicht geladen werden','admin','toast'),
('kurdish_sorani','admin.failed_load_members','ناتوانرێت ئەندامەکان بار بکرێن','admin','toast'),
('kurdish_kurmanji','admin.failed_load_members','Endam nehatin barkirin','admin','toast'),
('english','admin.confirm_delete_group','Are you sure you want to delete this group?','admin','confirm'),
('norwegian','admin.confirm_delete_group','Er du sikker på at du vil slette denne gruppen?','admin','confirm'),
('german','admin.confirm_delete_group','Möchten Sie diese Gruppe wirklich löschen?','admin','confirm'),
('kurdish_sorani','admin.confirm_delete_group','دڵنیایت دەتەوێ ئەم گرووپە بسڕیتەوە؟','admin','confirm'),
('kurdish_kurmanji','admin.confirm_delete_group','Tu bawer î ku dixwazî vê komê jêbirî?','admin','confirm'),
('english','admin.group_deleted','Group deleted successfully','admin','toast'),
('norwegian','admin.group_deleted','Gruppe slettet','admin','toast'),
('german','admin.group_deleted','Gruppe erfolgreich gelöscht','admin','toast'),
('kurdish_sorani','admin.group_deleted','گرووپ بە سەرکەوتوویی سڕایەوە','admin','toast'),
('kurdish_kurmanji','admin.group_deleted','Kom bi serkeftî hat jêbirin','admin','toast'),
('english','admin.failed_delete_group','Failed to delete group','admin','toast'),
('norwegian','admin.failed_delete_group','Kunne ikke slette gruppen','admin','toast'),
('german','admin.failed_delete_group','Gruppe konnte nicht gelöscht werden','admin','toast'),
('kurdish_sorani','admin.failed_delete_group','ناتوانرێت گرووپ بسڕدرێتەوە','admin','toast'),
('kurdish_kurmanji','admin.failed_delete_group','Kom nehate jêbirin','admin','toast'),
('english','admin.confirm_remove_member','Are you sure you want to remove this member?','admin','confirm'),
('norwegian','admin.confirm_remove_member','Er du sikker på at du vil fjerne dette medlemmet?','admin','confirm'),
('german','admin.confirm_remove_member','Möchten Sie dieses Mitglied wirklich entfernen?','admin','confirm'),
('kurdish_sorani','admin.confirm_remove_member','دڵنیایت دەتەوێ ئەم ئەندامە لاببەیت؟','admin','confirm'),
('kurdish_kurmanji','admin.confirm_remove_member','Tu bawer î ku dixwazî vê endamî jêbirî?','admin','confirm'),
('english','admin.member_removed','Member removed successfully','admin','toast'),
('norwegian','admin.member_removed','Medlem fjernet','admin','toast'),
('german','admin.member_removed','Mitglied erfolgreich entfernt','admin','toast'),
('kurdish_sorani','admin.member_removed','ئەندام بە سەرکەوتوویی لابرا','admin','toast'),
('kurdish_kurmanji','admin.member_removed','Endam bi serkeftî hat jêbirin','admin','toast'),
('english','admin.failed_remove_member','Failed to remove member','admin','toast'),
('norwegian','admin.failed_remove_member','Kunne ikke fjerne medlemmet','admin','toast'),
('german','admin.failed_remove_member','Mitglied konnte nicht entfernt werden','admin','toast'),
('kurdish_sorani','admin.failed_remove_member','ناتوانرێت ئەندام لابدرێت','admin','toast'),
('kurdish_kurmanji','admin.failed_remove_member','Endam nehate jêbirin','admin','toast'),

-- AIInsightsPage toast
('english','admin.failed_load_ai_insights','Failed to load AI insights','admin','toast'),
('norwegian','admin.failed_load_ai_insights','Kunne ikke laste AI-innsikt','admin','toast'),
('german','admin.failed_load_ai_insights','KI-Erkenntnisse konnten nicht geladen werden','admin','toast'),
('kurdish_sorani','admin.failed_load_ai_insights','ناتوانرێت بینینەکانی AI بار بکرێن','admin','toast'),
('kurdish_kurmanji','admin.failed_load_ai_insights','Têgihiştinên AI-ê nehatin barkirin','admin','toast'),

-- ExportsPage toast
('english','admin.file_not_available','File not available','admin','toast'),
('norwegian','admin.file_not_available','Fil ikke tilgjengelig','admin','toast'),
('german','admin.file_not_available','Datei nicht verfügbar','admin','toast'),
('kurdish_sorani','admin.file_not_available','فایل بەردەست نییە','admin','toast'),
('kurdish_kurmanji','admin.file_not_available','Dosye ne amade ye','admin','toast'),

-- RegistrationQuestionsPage toast
('english','admin.questions_exported','Questions exported to CSV successfully','admin','toast'),
('norwegian','admin.questions_exported','Spørsmål eksportert til CSV','admin','toast'),
('german','admin.questions_exported','Fragen erfolgreich als CSV exportiert','admin','toast'),
('kurdish_sorani','admin.questions_exported','پرسیارەکان بە سەرکەوتوویی بۆ CSV هەناردە کران','admin','toast'),
('kurdish_kurmanji','admin.questions_exported','Pirs bi serkeftî bo CSV hatin hinardekirin','admin','toast'),

-- useLandingPageContent toast messages
('english','admin.could_not_load_landing','Could not load landing page content from the database.','admin','toast'),
('norwegian','admin.could_not_load_landing','Kunne ikke laste landingssideinnhold fra databasen.','admin','toast'),
('german','admin.could_not_load_landing','Landingpage-Inhalte konnten nicht aus der Datenbank geladen werden.','admin','toast'),
('kurdish_sorani','admin.could_not_load_landing','ناتوانرێت ناوەڕۆکی پەڕەی دەستپێکردن لە داتابەیس بار بکرێت.','admin','toast'),
('kurdish_kurmanji','admin.could_not_load_landing','Naveroka rûpela destpêkê ji databasê nehate barkirin.','admin','toast'),
('english','admin.invalid_content_format','The content stored in the database has an invalid format.','admin','toast'),
('norwegian','admin.invalid_content_format','Innholdet lagret i databasen har et ugyldig format.','admin','toast'),
('german','admin.invalid_content_format','Der in der Datenbank gespeicherte Inhalt hat ein ungültiges Format.','admin','toast'),
('kurdish_sorani','admin.invalid_content_format','ناوەڕۆکی لە داتابەیسدا هەڵگیراوە فۆرماتێکی نادروستی هەیە.','admin','toast'),
('kurdish_kurmanji','admin.invalid_content_format','Naveroka ku di databasê de tê hilanîn formatek nerast heye.','admin','toast'),
('english','admin.unexpected_error_loading','An unexpected error occurred while loading the content.','admin','toast'),
('norwegian','admin.unexpected_error_loading','En uventet feil oppstod under lasting av innholdet.','admin','toast'),
('german','admin.unexpected_error_loading','Beim Laden des Inhalts ist ein unerwarteter Fehler aufgetreten.','admin','toast'),
('kurdish_sorani','admin.unexpected_error_loading','هەڵەیەکی چاوەڕواننەکراو ڕوویدا لەکاتی بارکردنی ناوەڕۆک.','admin','toast'),
('kurdish_kurmanji','admin.unexpected_error_loading','Çewtiyek nediyar di dema barkirina naverokê de çêbû.','admin','toast'),
('english','admin.could_not_save_default','Could not save default content to the database.','admin','toast'),
('norwegian','admin.could_not_save_default','Kunne ikke lagre standardinnhold til databasen.','admin','toast'),
('german','admin.could_not_save_default','Standardinhalte konnten nicht in der Datenbank gespeichert werden.','admin','toast'),
('kurdish_sorani','admin.could_not_save_default','ناتوانرێت ناوەڕۆکی بنەڕەت لە داتابەیس هەڵبگیرێت.','admin','toast'),
('kurdish_kurmanji','admin.could_not_save_default','Naveroka standard di databasê de nehate hilanîn.','admin','toast'),
('english','admin.no_content_to_save','No content to save. Please try reloading the page.','admin','toast'),
('norwegian','admin.no_content_to_save','Ingen innhold å lagre. Prøv å laste siden på nytt.','admin','toast'),
('german','admin.no_content_to_save','Kein Inhalt zum Speichern. Bitte laden Sie die Seite neu.','admin','toast'),
('kurdish_sorani','admin.no_content_to_save','هیچ ناوەڕۆکێک نییە بۆ هەڵگرتن. تکایە پەڕەکە دووبارە بار بکە.','admin','toast'),
('kurdish_kurmanji','admin.no_content_to_save','Tu naverok tune ye ku were hilanîn. Ji kerema xwe rûpelê ji nû ve bar bike.','admin','toast'),
('english','admin.could_not_save_landing','Could not save landing page content to the database.','admin','toast'),
('norwegian','admin.could_not_save_landing','Kunne ikke lagre landingssideinnhold til databasen.','admin','toast'),
('german','admin.could_not_save_landing','Landingpage-Inhalte konnten nicht in der Datenbank gespeichert werden.','admin','toast'),
('kurdish_sorani','admin.could_not_save_landing','ناتوانرێت ناوەڕۆکی پەڕەی دەستپێکردن لە داتابەیس هەڵبگیرێت.','admin','toast'),
('kurdish_kurmanji','admin.could_not_save_landing','Naveroka rûpela destpêkê di databasê de nehate hilanîn.','admin','toast'),
('english','admin.landing_saved','Landing page content has been updated successfully.','admin','toast'),
('norwegian','admin.landing_saved','Landingssideinnhold er oppdatert.','admin','toast'),
('german','admin.landing_saved','Landingpage-Inhalte wurden erfolgreich aktualisiert.','admin','toast'),
('kurdish_sorani','admin.landing_saved','ناوەڕۆکی پەڕەی دەستپێکردن بە سەرکەوتوویی نوێکرایەوە.','admin','toast'),
('kurdish_kurmanji','admin.landing_saved','Naveroka rûpela destpêkê bi serkeftî hat nûkirin.','admin','toast'),
('english','admin.unexpected_error_saving','An unexpected error occurred while saving the content.','admin','toast'),
('norwegian','admin.unexpected_error_saving','En uventet feil oppstod under lagring av innholdet.','admin','toast'),
('german','admin.unexpected_error_saving','Beim Speichern des Inhalts ist ein unerwarteter Fehler aufgetreten.','admin','toast'),
('kurdish_sorani','admin.unexpected_error_saving','هەڵەیەکی چاوەڕواننەکراو ڕوویدا لەکاتی هەڵگرتنی ناوەڕۆک.','admin','toast'),
('kurdish_kurmanji','admin.unexpected_error_saving','Çewtiyek nediyar di dema hilanîna naverokê de çêbû.','admin','toast'),

-- useAdminBulkActions toast messages
('english','admin.notifications_sent','Notifications Sent','admin','toast'),
('norwegian','admin.notifications_sent','Varsler sendt','admin','toast'),
('german','admin.notifications_sent','Benachrichtigungen gesendet','admin','toast'),
('kurdish_sorani','admin.notifications_sent','ئاگادارییەکان نێردران','admin','toast'),
('kurdish_kurmanji','admin.notifications_sent','Agahdarî hatin şandin','admin','toast'),
('english','admin.sent_to_users','Sent to {{count}} users','admin','toast'),
('norwegian','admin.sent_to_users','Sendt til {{count}} brukere','admin','toast'),
('german','admin.sent_to_users','An {{count}} Benutzer gesendet','admin','toast'),
('kurdish_sorani','admin.sent_to_users','نێردرا بۆ {{count}} بەکارهێنەر','admin','toast'),
('kurdish_kurmanji','admin.sent_to_users','Ji bo {{count}} bikarhêner hat şandin','admin','toast'),
('english','admin.export_started','Export Started','admin','toast'),
('norwegian','admin.export_started','Eksport startet','admin','toast'),
('german','admin.export_started','Export gestartet','admin','toast'),
('kurdish_sorani','admin.export_started','هەناردەکردن دەستی پێکرد','admin','toast'),
('kurdish_kurmanji','admin.export_started','Hinardekirinê dest pê kir','admin','toast'),
('english','admin.exporting_data_for','Exporting data for {{count}} users','admin','toast'),
('norwegian','admin.exporting_data_for','Eksporterer data for {{count}} brukere','admin','toast'),
('german','admin.exporting_data_for','Daten für {{count}} Benutzer werden exportiert','admin','toast'),
('kurdish_sorani','admin.exporting_data_for','هەناردەکردنی داتا بۆ {{count}} بەکارهێنەر','admin','toast'),
('kurdish_kurmanji','admin.exporting_data_for','Daneyên {{count}} bikarhêneran tên hinardekirinê','admin','toast'),
('english','admin.bulk_action_completed','Bulk action completed for {{count}} users','admin','toast'),
('norwegian','admin.bulk_action_completed','Massehandling fullført for {{count}} brukere','admin','toast'),
('german','admin.bulk_action_completed','Massenaktion für {{count}} Benutzer abgeschlossen','admin','toast'),
('kurdish_sorani','admin.bulk_action_completed','کردارەکەی کۆمەڵ بۆ {{count}} بەکارهێنەر تەواوبوو','admin','toast'),
('kurdish_kurmanji','admin.bulk_action_completed','Kiryara giştî ji bo {{count}} bikarhêneran qediya','admin','toast'),
('english','admin.failed_bulk_action','Failed to execute bulk action','admin','toast'),
('norwegian','admin.failed_bulk_action','Kunne ikke utføre massehandling','admin','toast'),
('german','admin.failed_bulk_action','Massenaktion konnte nicht ausgeführt werden','admin','toast'),
('kurdish_sorani','admin.failed_bulk_action','ناتوانرێت کردارەکەی کۆمەڵ جێبەجێ بکرێت','admin','toast'),
('kurdish_kurmanji','admin.failed_bulk_action','Kiryara giştî nehate bicîhkirin','admin','toast'),

-- useUserDelete toast messages
('english','admin.cannot_delete_own_account','You cannot delete your own account','admin','toast'),
('norwegian','admin.cannot_delete_own_account','Du kan ikke slette din egen konto','admin','toast'),
('german','admin.cannot_delete_own_account','Sie können Ihr eigenes Konto nicht löschen','admin','toast'),
('kurdish_sorani','admin.cannot_delete_own_account','ناتوانیت هەژمارەکەی خۆت بسڕیتەوە','admin','toast'),
('kurdish_kurmanji','admin.cannot_delete_own_account','Tu nikarî hesabê xwe jêbirî','admin','toast'),
('english','admin.user_permanently_deleted','{{name}} has been permanently deleted.','admin','toast'),
('norwegian','admin.user_permanently_deleted','{{name}} er permanent slettet.','admin','toast'),
('german','admin.user_permanently_deleted','{{name}} wurde dauerhaft gelöscht.','admin','toast'),
('kurdish_sorani','admin.user_permanently_deleted','{{name}} بە هەمیشەیی سڕایەوە.','admin','toast'),
('kurdish_kurmanji','admin.user_permanently_deleted','{{name}} bi domdarî hat jêbirin.','admin','toast'),
('english','admin.user_deactivated','{{name}} has been deactivated.','admin','toast'),
('norwegian','admin.user_deactivated','{{name}} er deaktivert.','admin','toast'),
('german','admin.user_deactivated','{{name}} wurde deaktiviert.','admin','toast'),
('kurdish_sorani','admin.user_deactivated','{{name}} ناچالاک کرا.','admin','toast'),
('kurdish_kurmanji','admin.user_deactivated','{{name}} hat neçalakkirin.','admin','toast'),
('english','admin.error_processing_request','There was an error processing this request.','admin','toast'),
('norwegian','admin.error_processing_request','Det oppstod en feil ved behandling av forespørselen.','admin','toast'),
('german','admin.error_processing_request','Bei der Verarbeitung dieser Anfrage ist ein Fehler aufgetreten.','admin','toast'),
('kurdish_sorani','admin.error_processing_request','هەڵەیەک ڕوویدا لەکاتی پرۆسەکردنی داواکارییەکە.','admin','toast'),
('kurdish_kurmanji','admin.error_processing_request','Di dema pêvajoya vê daxwazê de çewtiyek çêbû.','admin','toast'),

-- ABTestingPage toast messages
('english','admin.test_started','Test started successfully','admin','toast'),
('norwegian','admin.test_started','Test startet','admin','toast'),
('german','admin.test_started','Test erfolgreich gestartet','admin','toast'),
('kurdish_sorani','admin.test_started','تاقیکردنەوە بە سەرکەوتوویی دەستی پێکرد','admin','toast'),
('kurdish_kurmanji','admin.test_started','Ceribandin bi serkeftî dest pê kir','admin','toast'),
('english','admin.test_stopped','Test stopped','admin','toast'),
('norwegian','admin.test_stopped','Test stoppet','admin','toast'),
('german','admin.test_stopped','Test gestoppt','admin','toast'),
('kurdish_sorani','admin.test_stopped','تاقیکردنەوە وەستا','admin','toast'),
('kurdish_kurmanji','admin.test_stopped','Ceribandin hat rawestandin','admin','toast'),
('english','admin.test_deleted','Test deleted','admin','toast'),
('norwegian','admin.test_deleted','Test slettet','admin','toast'),
('german','admin.test_deleted','Test gelöscht','admin','toast'),
('kurdish_sorani','admin.test_deleted','تاقیکردنەوە سڕایەوە','admin','toast'),
('kurdish_kurmanji','admin.test_deleted','Ceribandin hat jêbirin','admin','toast'),

-- ABTestingPage dialog labels
('english','admin.test_name_label','Test Name','admin','label'),
('norwegian','admin.test_name_label','Testnavn','admin','label'),
('german','admin.test_name_label','Testname','admin','label'),
('kurdish_sorani','admin.test_name_label','ناوی تاقیکردنەوە','admin','label'),
('kurdish_kurmanji','admin.test_name_label','Navê ceribandinê','admin','label'),
('english','admin.test_type','Test Type','admin','label'),
('norwegian','admin.test_type','Testtype','admin','label'),
('german','admin.test_type','Testtyp','admin','label'),
('kurdish_sorani','admin.test_type','جۆری تاقیکردنەوە','admin','label'),
('kurdish_kurmanji','admin.test_type','Tîpa ceribandinê','admin','label'),
('english','admin.variant_a_control','Variant A (Control)','admin','label'),
('norwegian','admin.variant_a_control','Variant A (Kontroll)','admin','label'),
('german','admin.variant_a_control','Variante A (Kontrolle)','admin','label'),
('kurdish_sorani','admin.variant_a_control','جۆرەکەی A (کۆنترۆڵ)','admin','label'),
('kurdish_kurmanji','admin.variant_a_control','Guhertoya A (Kontrol)','admin','label'),
('english','admin.variant_b_test','Variant B (Test)','admin','label'),
('norwegian','admin.variant_b_test','Variant B (Test)','admin','label'),
('german','admin.variant_b_test','Variante B (Test)','admin','label'),
('kurdish_sorani','admin.variant_b_test','جۆرەکەی B (تاقیکردنەوە)','admin','label'),
('kurdish_kurmanji','admin.variant_b_test','Guhertoya B (Ceribandin)','admin','label'),
('english','admin.target_audience_label','Target Audience','admin','label'),
('norwegian','admin.target_audience_label','Målgruppe','admin','label'),
('german','admin.target_audience_label','Zielgruppe','admin','label'),
('kurdish_sorani','admin.target_audience_label','ئامانجی گوێگرەکان','admin','label'),
('kurdish_kurmanji','admin.target_audience_label','Temaşevanên armanc','admin','label'),
('english','admin.traffic_distribution','Traffic Distribution','admin','label'),
('norwegian','admin.traffic_distribution','Trafikkfordeling','admin','label'),
('german','admin.traffic_distribution','Verkehrsverteilung','admin','label'),
('kurdish_sorani','admin.traffic_distribution','دابەشکردنی ترافیک','admin','label'),
('kurdish_kurmanji','admin.traffic_distribution','Dabeşkirina trafîkê','admin','label'),
('english','admin.success_metrics','Success Metrics','admin','label'),
('norwegian','admin.success_metrics','Suksessmålinger','admin','label'),
('german','admin.success_metrics','Erfolgsmetriken','admin','label'),
('kurdish_sorani','admin.success_metrics','پێوەرەکانی سەرکەوتن','admin','label'),
('kurdish_kurmanji','admin.success_metrics','Pîvanên serkeftinê','admin','label'),
('english','admin.start_date','Start Date','admin','label'),
('norwegian','admin.start_date','Startdato','admin','label'),
('german','admin.start_date','Startdatum','admin','label'),
('kurdish_sorani','admin.start_date','بەرواری دەستپێکردن','admin','label'),
('kurdish_kurmanji','admin.start_date','Dîroka destpêkê','admin','label'),
('english','admin.end_date','End Date','admin','label'),
('norwegian','admin.end_date','Sluttdato','admin','label'),
('german','admin.end_date','Enddatum','admin','label'),
('kurdish_sorani','admin.end_date','بەرواری کۆتایی','admin','label'),
('kurdish_kurmanji','admin.end_date','Dîroka dawiyê','admin','label'),
('english','admin.create_test','Create Test','admin','button'),
('norwegian','admin.create_test','Opprett test','admin','button'),
('german','admin.create_test','Test erstellen','admin','button'),
('kurdish_sorani','admin.create_test','دروستکردنی تاقیکردنەوە','admin','button'),
('kurdish_kurmanji','admin.create_test','Ceribandinê biafirîne','admin','button'),

-- ExportsPage additional
('english','admin.failed_status','Failed','admin','label'),
('norwegian','admin.failed_status','Mislykket','admin','label'),
('german','admin.failed_status','Fehlgeschlagen','admin','label'),
('kurdish_sorani','admin.failed_status','شکستی هێنا','admin','label'),
('kurdish_kurmanji','admin.failed_status','Têkçû','admin','label'),
('english','admin.scheduled_exports_content','Scheduled exports content will appear here.','admin','placeholder'),
('norwegian','admin.scheduled_exports_content','Planlagte eksporter vises her.','admin','placeholder'),
('german','admin.scheduled_exports_content','Geplante Exporte werden hier angezeigt.','admin','placeholder'),
('kurdish_sorani','admin.scheduled_exports_content','ناوەڕۆکی هەناردەکراوە پلاندراوەکان لێرە دەردەکەوێت.','admin','placeholder'),
('kurdish_kurmanji','admin.scheduled_exports_content','Naveroka hinardekirinên plankirî dê li vir xuya bibe.','admin','placeholder'),
('english','admin.templates_content','Export templates content will appear here.','admin','placeholder'),
('norwegian','admin.templates_content','Eksportmaler vises her.','admin','placeholder'),
('german','admin.templates_content','Exportvorlagen werden hier angezeigt.','admin','placeholder'),
('kurdish_sorani','admin.templates_content','ناوەڕۆکی قاڵبەکانی هەناردەکردن لێرە دەردەکەوێت.','admin','placeholder'),
('kurdish_kurmanji','admin.templates_content','Naveroka şablonên hinardekirinê dê li vir xuya bibe.','admin','placeholder')
ON CONFLICT (language_code, translation_key) DO NOTHING;
