
-- Insert all missing translation keys for full i18n coverage
-- Languages: english, kurdish_sorani, kurdish_kurmanci, norwegian, german

-- ===== COOKIE CONSENT BANNER =====
INSERT INTO app_translations (language_code, translation_key, translation_value, category) VALUES
('english', 'cookie_banner.title', 'We use cookies 🍪', 'common'),
('norwegian', 'cookie_banner.title', 'Vi bruker informasjonskapsler 🍪', 'common'),
('kurdish_sorani', 'cookie_banner.title', 'ئێمە کوکیز بەکاردەهێنین 🍪', 'common'),
('kurdish_kurmanci', 'cookie_banner.title', 'Em cookie bi kar tînin 🍪', 'common'),
('german', 'cookie_banner.title', 'Wir verwenden Cookies 🍪', 'common'),
('english', 'cookie_banner.description', 'We use cookies to enhance your experience, keep you logged in, and analyze platform usage.', 'common'),
('norwegian', 'cookie_banner.description', 'Vi bruker informasjonskapsler for å forbedre opplevelsen din, holde deg innlogget og analysere plattformbruk.', 'common'),
('kurdish_sorani', 'cookie_banner.description', 'ئێمە کوکیز بەکاردەهێنین بۆ باشتر کردنی ئەزموونەکەت، لۆگین هەڵگرتنت، و شیکاری بەکارهێنانی پلاتفۆرمەکە.', 'common'),
('kurdish_kurmanci', 'cookie_banner.description', 'Em cookie bi kar tînin ji bo baştirkirina ezmûna te, ku tu têkevin û analîzkirina bikaranîna platformê.', 'common'),
('german', 'cookie_banner.description', 'Wir verwenden Cookies, um Ihr Erlebnis zu verbessern, Sie eingeloggt zu halten und die Plattformnutzung zu analysieren.', 'common'),
('english', 'cookie_banner.learn_more', 'Learn more', 'common'),
('norwegian', 'cookie_banner.learn_more', 'Les mer', 'common'),
('kurdish_sorani', 'cookie_banner.learn_more', 'زیاتر بزانە', 'common'),
('kurdish_kurmanci', 'cookie_banner.learn_more', 'Bêtir fêr bibe', 'common'),
('german', 'cookie_banner.learn_more', 'Mehr erfahren', 'common'),
('english', 'cookie_banner.accept_all', 'Accept All', 'common'),
('norwegian', 'cookie_banner.accept_all', 'Godta alle', 'common'),
('kurdish_sorani', 'cookie_banner.accept_all', 'هەموو قبوڵ بکە', 'common'),
('kurdish_kurmanci', 'cookie_banner.accept_all', 'Hemûyan qebûl bike', 'common'),
('german', 'cookie_banner.accept_all', 'Alle akzeptieren', 'common'),
('english', 'cookie_banner.essential_only', 'Essential Only', 'common'),
('norwegian', 'cookie_banner.essential_only', 'Kun nødvendige', 'common'),
('kurdish_sorani', 'cookie_banner.essential_only', 'تەنها پێویستەکان', 'common'),
('kurdish_kurmanci', 'cookie_banner.essential_only', 'Tenê yên pêwîst', 'common'),
('german', 'cookie_banner.essential_only', 'Nur notwendige', 'common')
ON CONFLICT DO NOTHING;

-- ===== COOKIE POLICY PAGE =====
INSERT INTO app_translations (language_code, translation_key, translation_value, category) VALUES
('english', 'cookie.title', 'Cookie Policy', 'common'),
('norwegian', 'cookie.title', 'Retningslinjer for informasjonskapsler', 'common'),
('kurdish_sorani', 'cookie.title', 'سیاسەتی کوکیز', 'common'),
('kurdish_kurmanci', 'cookie.title', 'Polîtîkaya Cookie', 'common'),
('german', 'cookie.title', 'Cookie-Richtlinie', 'common'),
('english', 'cookie.last_updated', 'Last updated: February 2026', 'common'),
('norwegian', 'cookie.last_updated', 'Sist oppdatert: Februar 2026', 'common'),
('kurdish_sorani', 'cookie.last_updated', 'دوایین نوێکردنەوە: شوبات ٢٠٢٦', 'common'),
('kurdish_kurmanci', 'cookie.last_updated', 'Nûvekirina dawî: Sibat 2026', 'common'),
('german', 'cookie.last_updated', 'Zuletzt aktualisiert: Februar 2026', 'common'),
('english', 'cookie.questions_contact', 'Questions? Contact Us', 'common'),
('norwegian', 'cookie.questions_contact', 'Spørsmål? Kontakt oss', 'common'),
('kurdish_sorani', 'cookie.questions_contact', 'پرسیارت هەیە؟ پەیوەندیمان پێوە بکە', 'common'),
('kurdish_kurmanci', 'cookie.questions_contact', 'Pirs hene? Bi me re têkilî daynin', 'common'),
('german', 'cookie.questions_contact', 'Fragen? Kontaktieren Sie uns', 'common'),
-- Cookie sections
('english', 'cookie.s1_title', '1. What Are Cookies', 'common'),
('norwegian', 'cookie.s1_title', '1. Hva er informasjonskapsler', 'common'),
('kurdish_sorani', 'cookie.s1_title', '١. کوکیز چییە', 'common'),
('kurdish_kurmanci', 'cookie.s1_title', '1. Cookie çi ne', 'common'),
('german', 'cookie.s1_title', '1. Was sind Cookies', 'common'),
('english', 'cookie.s1_content', 'Cookies are small text files stored on your device when you visit our platform. They help us provide you with a better experience by remembering your preferences, keeping you signed in, and understanding how you use KurdMatch.', 'common'),
('norwegian', 'cookie.s1_content', 'Informasjonskapsler er små tekstfiler som lagres på enheten din når du besøker plattformen vår. De hjelper oss med å gi deg en bedre opplevelse ved å huske preferansene dine, holde deg innlogget og forstå hvordan du bruker KurdMatch.', 'common'),
('kurdish_sorani', 'cookie.s1_content', 'کوکیز فایلی تێکستی بچووکن کە لەسەر ئامێرەکەت خەزن دەکرێن کاتێک سەردانی پلاتفۆرمەکەمان دەکەیت. یارمەتیمان دەدەن ئەزموونێکی باشتر پێشکەشت بکەین.', 'common'),
('kurdish_kurmanci', 'cookie.s1_content', 'Cookie pelên nivîsê yên piçûk in ku li ser amûra te têne hilanîn dema ku tu serdana platforma me dikî. Ew ji me re dibin alîkar ku ezmûnek çêtir ji te re pêşkêş bikin.', 'common'),
('german', 'cookie.s1_content', 'Cookies sind kleine Textdateien, die auf Ihrem Gerät gespeichert werden, wenn Sie unsere Plattform besuchen. Sie helfen uns, Ihnen ein besseres Erlebnis zu bieten.', 'common'),
('english', 'cookie.s2_title', '2. Types of Cookies We Use', 'common'),
('norwegian', 'cookie.s2_title', '2. Typer informasjonskapsler vi bruker', 'common'),
('kurdish_sorani', 'cookie.s2_title', '٢. جۆرەکانی کوکیز کە بەکاریان دەهێنین', 'common'),
('kurdish_kurmanci', 'cookie.s2_title', '2. Cûreyên cookie ku em bi kar tînin', 'common'),
('german', 'cookie.s2_title', '2. Arten von Cookies, die wir verwenden', 'common'),
('english', 'cookie.s2_content', '**Essential Cookies**: Required for the platform to function. These handle authentication, security, and basic functionality. You cannot opt out of these.

**Functional Cookies**: Remember your preferences like language selection, dark/light mode, and notification settings.

**Analytics Cookies**: Help us understand how users interact with KurdMatch so we can improve the experience. These collect anonymized usage data.

**Performance Cookies**: Monitor platform performance and help us identify and fix issues quickly.', 'common'),
('norwegian', 'cookie.s2_content', '**Nødvendige informasjonskapsler**: Påkrevd for at plattformen skal fungere. Disse håndterer autentisering, sikkerhet og grunnleggende funksjonalitet.

**Funksjonelle informasjonskapsler**: Husker preferansene dine som språkvalg, mørk/lys modus og varslingsinnstillinger.

**Analyseinformasjonskapsler**: Hjelper oss å forstå hvordan brukere samhandler med KurdMatch slik at vi kan forbedre opplevelsen.

**Ytelseinformasjonskapsler**: Overvåker plattformens ytelse og hjelper oss med å identifisere og fikse problemer raskt.', 'common'),
('kurdish_sorani', 'cookie.s2_content', '**کوکیزە پێویستەکان**: پێویستن بۆ کارکردنی پلاتفۆرمەکە.

**کوکیزە فەنکشناڵەکان**: هەڵبژاردەکانت بیر دەکەنەوە.

**کوکیزە شیکارییەکان**: یارمەتیمان دەدەن بزانین چۆن بەکارهێنەران لەگەڵ کوردماچ کاردەکەن.

**کوکیزە ئەداییەکان**: چاودێری ئەدای پلاتفۆرمەکە دەکەن.', 'common'),
('kurdish_kurmanci', 'cookie.s2_content', '**Cookieyên Pêwîst**: Ji bo xebata platformê pêwîst in.

**Cookieyên Fonksiyonel**: Bijarteyên te bi bîr tînin.

**Cookieyên Analîtîk**: Ji me re dibin alîkar ku em fêm bikin ka bikarhêner çawa bi KurdMatch re têkildar dibin.

**Cookieyên Performansê**: Performansa platformê dişopînin.', 'common'),
('german', 'cookie.s2_content', '**Wesentliche Cookies**: Für die Funktion der Plattform erforderlich.

**Funktionale Cookies**: Merken sich Ihre Einstellungen wie Sprachauswahl und Benachrichtigungseinstellungen.

**Analyse-Cookies**: Helfen uns zu verstehen, wie Nutzer mit KurdMatch interagieren.

**Leistungs-Cookies**: Überwachen die Plattformleistung.', 'common'),
('english', 'cookie.s3_title', '3. Third-Party Cookies', 'common'),
('norwegian', 'cookie.s3_title', '3. Tredjeparts informasjonskapsler', 'common'),
('kurdish_sorani', 'cookie.s3_title', '٣. کوکیزی لایەنی سێیەم', 'common'),
('kurdish_kurmanci', 'cookie.s3_title', '3. Cookieyên Aliyê Sêyemîn', 'common'),
('german', 'cookie.s3_title', '3. Cookies von Drittanbietern', 'common'),
('english', 'cookie.s3_content', 'We use services like Supabase for authentication and data storage, Stripe for payment processing, and Giphy for GIF content. These services may set their own cookies according to their respective privacy policies.', 'common'),
('norwegian', 'cookie.s3_content', 'Vi bruker tjenester som Supabase for autentisering og datalagring, Stripe for betalingsbehandling og Giphy for GIF-innhold. Disse tjenestene kan sette sine egne informasjonskapsler.', 'common'),
('kurdish_sorani', 'cookie.s3_content', 'ئێمە خزمەتگوزارییەکانی وەک Supabase بۆ ناسینەوە و خەزنکردنی داتا، Stripe بۆ پرۆسێسی پارەدان، و Giphy بۆ ناوەرۆکی GIF بەکاردەهێنین.', 'common'),
('kurdish_kurmanci', 'cookie.s3_content', 'Em karûbarên wekî Supabase ji bo erêkirinê û hilanîna daneyan, Stripe ji bo pêvajoya dravdanê, û Giphy ji bo naveroka GIF bi kar tînin.', 'common'),
('german', 'cookie.s3_content', 'Wir nutzen Dienste wie Supabase für Authentifizierung und Datenspeicherung, Stripe für Zahlungsabwicklung und Giphy für GIF-Inhalte.', 'common'),
('english', 'cookie.s4_title', '4. How Long Cookies Last', 'common'),
('norwegian', 'cookie.s4_title', '4. Hvor lenge informasjonskapsler varer', 'common'),
('kurdish_sorani', 'cookie.s4_title', '٤. کوکیز چەند دەخایەنێ', 'common'),
('kurdish_kurmanci', 'cookie.s4_title', '4. Cookie çiqas dirêj dimînin', 'common'),
('german', 'cookie.s4_title', '4. Wie lange Cookies gespeichert werden', 'common'),
('english', 'cookie.s4_content', '**Session Cookies**: Deleted when you close your browser. Used for temporary tasks like keeping you logged in during a session.

**Persistent Cookies**: Remain on your device for a set period (typically 30 days to 1 year). Used for remembering your preferences and login status.', 'common'),
('norwegian', 'cookie.s4_content', '**Øktinformasjonskapsler**: Slettes når du lukker nettleseren. Brukes til midlertidige oppgaver som å holde deg innlogget under en økt.

**Vedvarende informasjonskapsler**: Forblir på enheten din i en bestemt periode (vanligvis 30 dager til 1 år). Brukes til å huske preferansene dine og innloggingsstatus.', 'common'),
('kurdish_sorani', 'cookie.s4_content', '**کوکیزی دانیشتن**: دەسڕدرێنەوە کاتێک وێبگەڕەکەت دادەخەیت.

**کوکیزی مانەوە**: لەسەر ئامێرەکەت دەمێنن بۆ ماوەیەکی دیاریکراو.', 'common'),
('kurdish_kurmanci', 'cookie.s4_content', '**Cookieyên Danişînê**: Dema ku tu geroka xwe digirî têne jêbirin.

**Cookieyên Domdar**: Li ser amûra te ji bo demek diyar dimînin.', 'common'),
('german', 'cookie.s4_content', '**Sitzungs-Cookies**: Werden gelöscht, wenn Sie Ihren Browser schließen.

**Dauerhafte Cookies**: Verbleiben für einen bestimmten Zeitraum auf Ihrem Gerät (in der Regel 30 Tage bis 1 Jahr).', 'common'),
('english', 'cookie.s5_title', '5. Managing Cookies', 'common'),
('norwegian', 'cookie.s5_title', '5. Administrere informasjonskapsler', 'common'),
('kurdish_sorani', 'cookie.s5_title', '٥. بەڕێوەبردنی کوکیز', 'common'),
('kurdish_kurmanci', 'cookie.s5_title', '5. Rêveberiya Cookie', 'common'),
('german', 'cookie.s5_title', '5. Cookies verwalten', 'common'),
('english', 'cookie.s5_content', 'You can manage cookie preferences through your browser settings. Most browsers allow you to block or delete cookies. However, blocking essential cookies may prevent KurdMatch from functioning properly. You can also clear cookies at any time through your browser settings.', 'common'),
('norwegian', 'cookie.s5_content', 'Du kan administrere informasjonskapsler gjennom nettleserinnstillingene dine. De fleste nettlesere lar deg blokkere eller slette informasjonskapsler. Men å blokkere nødvendige informasjonskapsler kan hindre KurdMatch i å fungere riktig.', 'common'),
('kurdish_sorani', 'cookie.s5_content', 'دەتوانیت کوکیزەکان لە ڕێگەی ڕێکخستنەکانی وێبگەڕەکەتەوە بەڕێوەببەیت.', 'common'),
('kurdish_kurmanci', 'cookie.s5_content', 'Tu dikarî bi rêya mîhengên geroka xwe cookieyan birêve bibî.', 'common'),
('german', 'cookie.s5_content', 'Sie können Cookies über Ihre Browsereinstellungen verwalten. Die meisten Browser erlauben es Ihnen, Cookies zu blockieren oder zu löschen.', 'common'),
('english', 'cookie.s6_title', '6. Updates to This Policy', 'common'),
('norwegian', 'cookie.s6_title', '6. Oppdateringer av denne policyen', 'common'),
('kurdish_sorani', 'cookie.s6_title', '٦. نوێکردنەوەی ئەم سیاسەتە', 'common'),
('kurdish_kurmanci', 'cookie.s6_title', '6. Nûvekirina vê polîtîkayê', 'common'),
('german', 'cookie.s6_title', '6. Aktualisierungen dieser Richtlinie', 'common'),
('english', 'cookie.s6_content', 'We may update this Cookie Policy from time to time to reflect changes in our practices or applicable laws. We will notify you of significant changes through the platform.', 'common'),
('norwegian', 'cookie.s6_content', 'Vi kan oppdatere denne retningslinjen fra tid til annen for å gjenspeile endringer i vår praksis eller gjeldende lover.', 'common'),
('kurdish_sorani', 'cookie.s6_content', 'ئێمە لەوانەیە ئەم سیاسەتە نوێ بکەینەوە بۆ گۆڕانکاری لە ڕێوشوێنەکانمان.', 'common'),
('kurdish_kurmanci', 'cookie.s6_content', 'Dibe ku em vê polîtîkayê dem bi dem nûve bikin.', 'common'),
('german', 'cookie.s6_content', 'Wir können diese Richtlinie von Zeit zu Zeit aktualisieren.', 'common'),
('english', 'cookie.s7_title', '7. Contact Us', 'common'),
('norwegian', 'cookie.s7_title', '7. Kontakt oss', 'common'),
('kurdish_sorani', 'cookie.s7_title', '٧. پەیوەندیمان پێوە بکە', 'common'),
('kurdish_kurmanci', 'cookie.s7_title', '7. Bi me re têkilî daynin', 'common'),
('german', 'cookie.s7_title', '7. Kontaktieren Sie uns', 'common'),
('english', 'cookie.s7_content', 'If you have questions about our use of cookies, please contact us at support@kurdmatch.com or visit our Contact Us page.', 'common'),
('norwegian', 'cookie.s7_content', 'Hvis du har spørsmål om vår bruk av informasjonskapsler, ta kontakt med oss på support@kurdmatch.com eller besøk vår Kontakt oss-side.', 'common'),
('kurdish_sorani', 'cookie.s7_content', 'ئەگەر پرسیارت هەیە دەربارەی بەکارهێنانی کوکیز، تکایە پەیوەندیمان پێوە بکە لە support@kurdmatch.com.', 'common'),
('kurdish_kurmanci', 'cookie.s7_content', 'Eger pirsên te hene derbarê bikaranîna cookie, ji kerema xwe bi me re têkilî daynin li support@kurdmatch.com.', 'common'),
('german', 'cookie.s7_content', 'Wenn Sie Fragen zur Verwendung von Cookies haben, kontaktieren Sie uns bitte unter support@kurdmatch.com.', 'common')
ON CONFLICT DO NOTHING;

-- ===== PRIVACY POLICY =====
INSERT INTO app_translations (language_code, translation_key, translation_value, category) VALUES
('english', 'privacy.title', 'Privacy Policy', 'common'),
('norwegian', 'privacy.title', 'Personvernpolicy', 'common'),
('kurdish_sorani', 'privacy.title', 'سیاسەتی تایبەتمەندی', 'common'),
('kurdish_kurmanci', 'privacy.title', 'Polîtîkaya Nepenîtiyê', 'common'),
('german', 'privacy.title', 'Datenschutzrichtlinie', 'common'),
('english', 'privacy.last_updated', 'Last updated: December 2024', 'common'),
('norwegian', 'privacy.last_updated', 'Sist oppdatert: Desember 2024', 'common'),
('kurdish_sorani', 'privacy.last_updated', 'دوایین نوێکردنەوە: کانونی یەکەم ٢٠٢٤', 'common'),
('kurdish_kurmanci', 'privacy.last_updated', 'Nûvekirina dawî: Berfanbar 2024', 'common'),
('german', 'privacy.last_updated', 'Zuletzt aktualisiert: Dezember 2024', 'common'),
('english', 'privacy.back', 'Back', 'common'),
('norwegian', 'privacy.back', 'Tilbake', 'common'),
('kurdish_sorani', 'privacy.back', 'گەڕانەوە', 'common'),
('kurdish_kurmanci', 'privacy.back', 'Vegere', 'common'),
('german', 'privacy.back', 'Zurück', 'common'),
('english', 'privacy.s1_title', '1. Introduction', 'common'),
('norwegian', 'privacy.s1_title', '1. Introduksjon', 'common'),
('kurdish_sorani', 'privacy.s1_title', '١. پێشەکی', 'common'),
('kurdish_kurmanci', 'privacy.s1_title', '1. Destpêk', 'common'),
('german', 'privacy.s1_title', '1. Einleitung', 'common'),
('english', 'privacy.s1_content', 'Welcome to KurdMatch. We respect your privacy and are committed to protecting your personal data. This privacy policy explains how we collect, use, and safeguard your information when you use our dating platform.', 'common'),
('norwegian', 'privacy.s1_content', 'Velkommen til KurdMatch. Vi respekterer personvernet ditt og er forpliktet til å beskytte dine personlige data. Denne personvernpolicyen forklarer hvordan vi samler inn, bruker og beskytter informasjonen din når du bruker datingplattformen vår.', 'common'),
('kurdish_sorani', 'privacy.s1_content', 'بەخێربێیت بۆ KurdMatch. ئێمە ڕێزی تایبەتمەندی تۆ دەگرین و پابەندین بە پاراستنی داتای کەسیت.', 'common'),
('kurdish_kurmanci', 'privacy.s1_content', 'Bi xêr hatî KurdMatch. Em rêzê li nepenîtiya te digirin û soz didin ku daneyên te yên kesane biparêzin.', 'common'),
('german', 'privacy.s1_content', 'Willkommen bei KurdMatch. Wir respektieren Ihre Privatsphäre und verpflichten uns, Ihre persönlichen Daten zu schützen.', 'common'),
('english', 'privacy.s2_title', '2. Information We Collect', 'common'),
('norwegian', 'privacy.s2_title', '2. Informasjon vi samler inn', 'common'),
('kurdish_sorani', 'privacy.s2_title', '٢. زانیاری کە کۆیدەکەینەوە', 'common'),
('kurdish_kurmanci', 'privacy.s2_title', '2. Agahiyên ku em berhev dikin', 'common'),
('german', 'privacy.s2_title', '2. Informationen, die wir erfassen', 'common'),
('english', 'privacy.s3_title', '3. How We Use Your Information', 'common'),
('norwegian', 'privacy.s3_title', '3. Hvordan vi bruker informasjonen din', 'common'),
('kurdish_sorani', 'privacy.s3_title', '٣. چۆن زانیاریەکەت بەکاردەهێنین', 'common'),
('kurdish_kurmanci', 'privacy.s3_title', '3. Em agahiyên te çawa bi kar tînin', 'common'),
('german', 'privacy.s3_title', '3. Wie wir Ihre Informationen verwenden', 'common'),
('english', 'privacy.s4_title', '4. Information Sharing', 'common'),
('norwegian', 'privacy.s4_title', '4. Deling av informasjon', 'common'),
('kurdish_sorani', 'privacy.s4_title', '٤. هاوبەشکردنی زانیاری', 'common'),
('kurdish_kurmanci', 'privacy.s4_title', '4. Parvekirina Agahiyan', 'common'),
('german', 'privacy.s4_title', '4. Weitergabe von Informationen', 'common'),
('english', 'privacy.s5_title', '5. Data Security', 'common'),
('norwegian', 'privacy.s5_title', '5. Datasikkerhet', 'common'),
('kurdish_sorani', 'privacy.s5_title', '٥. ئاسایشی داتا', 'common'),
('kurdish_kurmanci', 'privacy.s5_title', '5. Ewlehiya Daneyan', 'common'),
('german', 'privacy.s5_title', '5. Datensicherheit', 'common'),
('english', 'privacy.s6_title', '6. Your Rights', 'common'),
('norwegian', 'privacy.s6_title', '6. Dine rettigheter', 'common'),
('kurdish_sorani', 'privacy.s6_title', '٦. مافەکانت', 'common'),
('kurdish_kurmanci', 'privacy.s6_title', '6. Mafên Te', 'common'),
('german', 'privacy.s6_title', '6. Ihre Rechte', 'common'),
('english', 'privacy.s7_title', '7. Cookies', 'common'),
('norwegian', 'privacy.s7_title', '7. Informasjonskapsler', 'common'),
('kurdish_sorani', 'privacy.s7_title', '٧. کوکیز', 'common'),
('kurdish_kurmanci', 'privacy.s7_title', '7. Cookie', 'common'),
('german', 'privacy.s7_title', '7. Cookies', 'common'),
('english', 'privacy.s8_title', '8. Contact Us', 'common'),
('norwegian', 'privacy.s8_title', '8. Kontakt oss', 'common'),
('kurdish_sorani', 'privacy.s8_title', '٨. پەیوەندیمان پێوە بکە', 'common'),
('kurdish_kurmanci', 'privacy.s8_title', '8. Bi me re têkilî daynin', 'common'),
('german', 'privacy.s8_title', '8. Kontaktieren Sie uns', 'common')
ON CONFLICT DO NOTHING;

-- ===== TERMS OF SERVICE =====
INSERT INTO app_translations (language_code, translation_key, translation_value, category) VALUES
('english', 'terms.title', 'Terms of Service', 'common'),
('norwegian', 'terms.title', 'Vilkår for bruk', 'common'),
('kurdish_sorani', 'terms.title', 'مەرجەکانی خزمەتگوزاری', 'common'),
('kurdish_kurmanci', 'terms.title', 'Mercên Xizmetê', 'common'),
('german', 'terms.title', 'Nutzungsbedingungen', 'common'),
('english', 'terms.last_updated', 'Last updated: December 2024', 'common'),
('norwegian', 'terms.last_updated', 'Sist oppdatert: Desember 2024', 'common'),
('kurdish_sorani', 'terms.last_updated', 'دوایین نوێکردنەوە: کانونی یەکەم ٢٠٢٤', 'common'),
('kurdish_kurmanci', 'terms.last_updated', 'Nûvekirina dawî: Berfanbar 2024', 'common'),
('german', 'terms.last_updated', 'Zuletzt aktualisiert: Dezember 2024', 'common'),
('english', 'terms.s1_title', '1. Acceptance of Terms', 'common'),
('norwegian', 'terms.s1_title', '1. Aksept av vilkår', 'common'),
('kurdish_sorani', 'terms.s1_title', '١. قبوڵکردنی مەرجەکان', 'common'),
('kurdish_kurmanci', 'terms.s1_title', '1. Pejirandina Mercan', 'common'),
('german', 'terms.s1_title', '1. Annahme der Bedingungen', 'common'),
('english', 'terms.s2_title', '2. Eligibility', 'common'),
('norwegian', 'terms.s2_title', '2. Kvalifisering', 'common'),
('kurdish_sorani', 'terms.s2_title', '٢. شایستەیی', 'common'),
('kurdish_kurmanci', 'terms.s2_title', '2. Destûr', 'common'),
('german', 'terms.s2_title', '2. Berechtigung', 'common'),
('english', 'terms.s3_title', '3. Account Registration', 'common'),
('norwegian', 'terms.s3_title', '3. Kontoregistrering', 'common'),
('kurdish_sorani', 'terms.s3_title', '٣. تۆمارکردنی هەژمار', 'common'),
('kurdish_kurmanci', 'terms.s3_title', '3. Tomarkirina Hesabê', 'common'),
('german', 'terms.s3_title', '3. Kontoregistrierung', 'common'),
('english', 'terms.s4_title', '4. User Conduct', 'common'),
('norwegian', 'terms.s4_title', '4. Brukeratferd', 'common'),
('kurdish_sorani', 'terms.s4_title', '٤. ڕەفتاری بەکارهێنەر', 'common'),
('kurdish_kurmanci', 'terms.s4_title', '4. Tevgera Bikarhêner', 'common'),
('german', 'terms.s4_title', '4. Nutzerverhalten', 'common'),
('english', 'terms.s5_title', '5. Content Guidelines', 'common'),
('norwegian', 'terms.s5_title', '5. Retningslinjer for innhold', 'common'),
('kurdish_sorani', 'terms.s5_title', '٥. ڕێنماییەکانی ناوەرۆک', 'common'),
('kurdish_kurmanci', 'terms.s5_title', '5. Rêwerzên Naverokê', 'common'),
('german', 'terms.s5_title', '5. Inhaltsrichtlinien', 'common'),
('english', 'terms.s6_title', '6. Premium Services', 'common'),
('norwegian', 'terms.s6_title', '6. Premium-tjenester', 'common'),
('kurdish_sorani', 'terms.s6_title', '٦. خزمەتگوزاری پریمیۆم', 'common'),
('kurdish_kurmanci', 'terms.s6_title', '6. Karûbarên Premium', 'common'),
('german', 'terms.s6_title', '6. Premium-Dienste', 'common'),
('english', 'terms.s7_title', '7. Safety', 'common'),
('norwegian', 'terms.s7_title', '7. Sikkerhet', 'common'),
('kurdish_sorani', 'terms.s7_title', '٧. ئاسایش', 'common'),
('kurdish_kurmanci', 'terms.s7_title', '7. Ewlehî', 'common'),
('german', 'terms.s7_title', '7. Sicherheit', 'common'),
('english', 'terms.s8_title', '8. Termination', 'common'),
('norwegian', 'terms.s8_title', '8. Oppsigelse', 'common'),
('kurdish_sorani', 'terms.s8_title', '٨. کۆتاییهێنان', 'common'),
('kurdish_kurmanci', 'terms.s8_title', '8. Dawîanîn', 'common'),
('german', 'terms.s8_title', '8. Kündigung', 'common'),
('english', 'terms.s9_title', '9. Contact', 'common'),
('norwegian', 'terms.s9_title', '9. Kontakt', 'common'),
('kurdish_sorani', 'terms.s9_title', '٩. پەیوەندی', 'common'),
('kurdish_kurmanci', 'terms.s9_title', '9. Têkilî', 'common'),
('german', 'terms.s9_title', '9. Kontakt', 'common')
ON CONFLICT DO NOTHING;

-- ===== MATCH POPUP =====
INSERT INTO app_translations (language_code, translation_key, translation_value, category) VALUES
('english', 'match_popup.title', 'It''s a Match!', 'common'),
('norwegian', 'match_popup.title', 'Det er en match!', 'common'),
('kurdish_sorani', 'match_popup.title', 'ماچ بوو!', 'common'),
('kurdish_kurmanci', 'match_popup.title', 'Maç bû!', 'common'),
('german', 'match_popup.title', 'Es ist ein Match!', 'common'),
('english', 'match_popup.liked_each_other', 'You and {{name}} liked each other', 'common'),
('norwegian', 'match_popup.liked_each_other', 'Du og {{name}} likte hverandre', 'common'),
('kurdish_sorani', 'match_popup.liked_each_other', 'تۆ و {{name}} حەزتان لە یەکتری کرد', 'common'),
('kurdish_kurmanci', 'match_popup.liked_each_other', 'Tu û {{name}} ji hev hez kirin', 'common'),
('german', 'match_popup.liked_each_other', 'Du und {{name}} mögen sich', 'common'),
('english', 'match_popup.send_message', 'Send a Message', 'common'),
('norwegian', 'match_popup.send_message', 'Send en melding', 'common'),
('kurdish_sorani', 'match_popup.send_message', 'نامەیەک بنێرە', 'common'),
('kurdish_kurmanci', 'match_popup.send_message', 'Peyamek bişîne', 'common'),
('german', 'match_popup.send_message', 'Nachricht senden', 'common'),
('english', 'match_popup.keep_swiping', 'Keep Swiping', 'common'),
('norwegian', 'match_popup.keep_swiping', 'Fortsett å sveipe', 'common'),
('kurdish_sorani', 'match_popup.keep_swiping', 'بەردەوام بە سوایپکردن', 'common'),
('kurdish_kurmanci', 'match_popup.keep_swiping', 'Bi swêpkirinê bidomîne', 'common'),
('german', 'match_popup.keep_swiping', 'Weiter swipen', 'common')
ON CONFLICT DO NOTHING;

-- ===== ERROR BOUNDARY =====
INSERT INTO app_translations (language_code, translation_key, translation_value, category) VALUES
('english', 'error.something_wrong', 'Something went wrong', 'common'),
('norwegian', 'error.something_wrong', 'Noe gikk galt', 'common'),
('kurdish_sorani', 'error.something_wrong', 'هەڵەیەک ڕووی دا', 'common'),
('kurdish_kurmanci', 'error.something_wrong', 'Tiştek xelet derket', 'common'),
('german', 'error.something_wrong', 'Etwas ist schief gelaufen', 'common'),
('english', 'error.unexpected', 'An unexpected error occurred. Please try refreshing the page.', 'common'),
('norwegian', 'error.unexpected', 'En uventet feil oppstod. Vennligst prøv å oppdatere siden.', 'common'),
('kurdish_sorani', 'error.unexpected', 'هەڵەیەکی چاوەڕوان نەکراو ڕووی دا. تکایە لاپەڕەکە نوێ بکەوە.', 'common'),
('kurdish_kurmanci', 'error.unexpected', 'Çewtiyek nediyar derket. Ji kerema xwe rûpelê nû bike.', 'common'),
('german', 'error.unexpected', 'Ein unerwarteter Fehler ist aufgetreten. Bitte aktualisieren Sie die Seite.', 'common'),
('english', 'error.refresh', 'Refresh Page', 'common'),
('norwegian', 'error.refresh', 'Oppdater side', 'common'),
('kurdish_sorani', 'error.refresh', 'نوێکردنەوەی لاپەڕە', 'common'),
('kurdish_kurmanci', 'error.refresh', 'Rûpelê nû bike', 'common'),
('german', 'error.refresh', 'Seite aktualisieren', 'common')
ON CONFLICT DO NOTHING;

-- ===== PHOTO TIPS =====
INSERT INTO app_translations (language_code, translation_key, translation_value, category) VALUES
('english', 'photo_tips.safety_title', 'Your safety is our priority', 'auth'),
('norwegian', 'photo_tips.safety_title', 'Din sikkerhet er vår prioritet', 'auth'),
('kurdish_sorani', 'photo_tips.safety_title', 'ئاسایشت ئەولەویەتی ئێمەیە', 'auth'),
('kurdish_kurmanci', 'photo_tips.safety_title', 'Ewlehiya te pêşîniya me ye', 'auth'),
('german', 'photo_tips.safety_title', 'Ihre Sicherheit hat Priorität', 'auth'),
('english', 'photo_tips.safety_desc', 'Never share photos that reveal personal information like your home address or workplace. Be mindful of what''s in the background of your photos.', 'auth'),
('norwegian', 'photo_tips.safety_desc', 'Del aldri bilder som avslører personlig informasjon som hjemmeadressen din eller arbeidsplassen din. Vær oppmerksom på hva som er i bakgrunnen av bildene dine.', 'auth'),
('kurdish_sorani', 'photo_tips.safety_desc', 'هەرگیز وێنەی کە زانیاری کەسی ئاشکرا دەکات هاوبەش مەکە.', 'auth'),
('kurdish_kurmanci', 'photo_tips.safety_desc', 'Tu carî wêneyên ku agahiyên kesane eşkere dikin parve nekin.', 'auth'),
('german', 'photo_tips.safety_desc', 'Teilen Sie niemals Fotos, die persönliche Informationen preisgeben.', 'auth'),
('english', 'photo_tips.title', 'Photo tips:', 'auth'),
('norwegian', 'photo_tips.title', 'Bildetips:', 'auth'),
('kurdish_sorani', 'photo_tips.title', 'ئامۆژگاری وێنە:', 'auth'),
('kurdish_kurmanci', 'photo_tips.title', 'Şîretên wêneyan:', 'auth'),
('german', 'photo_tips.title', 'Foto-Tipps:', 'auth'),
('english', 'photo_tips.tip1', 'Your first photo should clearly show your face', 'auth'),
('norwegian', 'photo_tips.tip1', 'Det første bildet ditt bør tydelig vise ansiktet ditt', 'auth'),
('kurdish_sorani', 'photo_tips.tip1', 'یەکەم وێنەکەت دەبێت ڕووخسارت بە ئاشکرا پیشان بدات', 'auth'),
('kurdish_kurmanci', 'photo_tips.tip1', 'Wêneya te ya yekem divê rûyê te bi zelalî nîşan bide', 'auth'),
('german', 'photo_tips.tip1', 'Ihr erstes Foto sollte Ihr Gesicht deutlich zeigen', 'auth'),
('english', 'photo_tips.tip2', 'Add up to 5 photos to showcase your personality', 'auth'),
('norwegian', 'photo_tips.tip2', 'Legg til opptil 5 bilder for å vise personligheten din', 'auth'),
('kurdish_sorani', 'photo_tips.tip2', 'تا ٥ وێنە زیاد بکە بۆ پیشاندانی کەسایەتیت', 'auth'),
('kurdish_kurmanci', 'photo_tips.tip2', 'Heta 5 wêneyan lê zêde bike da ku kesayetiya xwe nîşan bidî', 'auth'),
('german', 'photo_tips.tip2', 'Fügen Sie bis zu 5 Fotos hinzu, um Ihre Persönlichkeit zu zeigen', 'auth'),
('english', 'photo_tips.tip3', 'Use our free AI editor to enhance your photos', 'auth'),
('norwegian', 'photo_tips.tip3', 'Bruk vår gratis AI-editor for å forbedre bildene dine', 'auth'),
('kurdish_sorani', 'photo_tips.tip3', 'دەستکاریکەری AI ی بێبەرامبەرمان بەکاربهێنە بۆ باشترکردنی وێنەکانت', 'auth'),
('kurdish_kurmanci', 'photo_tips.tip3', 'Edîtora meya AIyê ya belaş bi kar bîne da ku wêneyên xwe baştir bikî', 'auth'),
('german', 'photo_tips.tip3', 'Nutzen Sie unseren kostenlosen KI-Editor, um Ihre Fotos zu verbessern', 'auth'),
('english', 'photo_tips.tip4', 'Background removal and filters are completely free', 'auth'),
('norwegian', 'photo_tips.tip4', 'Fjerning av bakgrunn og filtre er helt gratis', 'auth'),
('kurdish_sorani', 'photo_tips.tip4', 'لابردنی باکگراوند و فلتەرەکان بەتەواوی بێبەرامبەرن', 'auth'),
('kurdish_kurmanci', 'photo_tips.tip4', 'Rakirina paşperdê û fîlter bi tevahî belaş in', 'auth'),
('german', 'photo_tips.tip4', 'Hintergrundentfernung und Filter sind völlig kostenlos', 'auth'),
('english', 'photo_tips.tip5', 'Good lighting makes a big difference', 'auth'),
('norwegian', 'photo_tips.tip5', 'Godt lys gjør en stor forskjell', 'auth'),
('kurdish_sorani', 'photo_tips.tip5', 'ڕووناکی باش جیاوازی گەورە دروست دەکات', 'auth'),
('kurdish_kurmanci', 'photo_tips.tip5', 'Roniya baş cûdahiyek mezin çêdike', 'auth'),
('german', 'photo_tips.tip5', 'Gute Beleuchtung macht einen großen Unterschied', 'auth')
ON CONFLICT DO NOTHING;

-- ===== LANDING PAGE NAV + FOOTER =====
INSERT INTO app_translations (language_code, translation_key, translation_value, category) VALUES
('english', 'landing.nav.home', 'Home', 'navigation'),
('norwegian', 'landing.nav.home', 'Hjem', 'navigation'),
('kurdish_sorani', 'landing.nav.home', 'ماڵەوە', 'navigation'),
('kurdish_kurmanci', 'landing.nav.home', 'Mal', 'navigation'),
('german', 'landing.nav.home', 'Startseite', 'navigation'),
('english', 'landing.nav.about', 'About', 'navigation'),
('norwegian', 'landing.nav.about', 'Om oss', 'navigation'),
('kurdish_sorani', 'landing.nav.about', 'دەربارە', 'navigation'),
('kurdish_kurmanci', 'landing.nav.about', 'Der barê me', 'navigation'),
('german', 'landing.nav.about', 'Über uns', 'navigation'),
('english', 'landing.nav.features', 'Features', 'navigation'),
('norwegian', 'landing.nav.features', 'Funksjoner', 'navigation'),
('kurdish_sorani', 'landing.nav.features', 'تایبەتمەندییەکان', 'navigation'),
('kurdish_kurmanci', 'landing.nav.features', 'Taybetmendî', 'navigation'),
('german', 'landing.nav.features', 'Funktionen', 'navigation'),
('english', 'landing.nav.contact', 'Contact', 'navigation'),
('norwegian', 'landing.nav.contact', 'Kontakt', 'navigation'),
('kurdish_sorani', 'landing.nav.contact', 'پەیوەندی', 'navigation'),
('kurdish_kurmanci', 'landing.nav.contact', 'Têkilî', 'navigation'),
('german', 'landing.nav.contact', 'Kontakt', 'navigation'),
('english', 'landing.nav.login', 'Login', 'navigation'),
('norwegian', 'landing.nav.login', 'Logg inn', 'navigation'),
('kurdish_sorani', 'landing.nav.login', 'چوونەژوورەوە', 'navigation'),
('kurdish_kurmanci', 'landing.nav.login', 'Têkeve', 'navigation'),
('german', 'landing.nav.login', 'Anmelden', 'navigation'),
('english', 'landing.nav.register', 'REGISTER', 'navigation'),
('norwegian', 'landing.nav.register', 'REGISTRER', 'navigation'),
('kurdish_sorani', 'landing.nav.register', 'تۆمارکردن', 'navigation'),
('kurdish_kurmanci', 'landing.nav.register', 'TOMAR BIBE', 'navigation'),
('german', 'landing.nav.register', 'REGISTRIEREN', 'navigation'),
('english', 'landing.what_you_find', 'What You Can', 'navigation'),
('norwegian', 'landing.what_you_find', 'Hva du kan', 'navigation'),
('kurdish_sorani', 'landing.what_you_find', 'چی دەتوانیت', 'navigation'),
('kurdish_kurmanci', 'landing.what_you_find', 'Tu dikarî çi', 'navigation'),
('german', 'landing.what_you_find', 'Was Sie', 'navigation'),
('english', 'landing.find', 'Find', 'navigation'),
('norwegian', 'landing.find', 'finne', 'navigation'),
('kurdish_sorani', 'landing.find', 'بدۆزیتەوە', 'navigation'),
('kurdish_kurmanci', 'landing.find', 'bibînî', 'navigation'),
('german', 'landing.find', 'finden können', 'navigation'),
('english', 'landing.connect_worldwide', 'Connect with Kurdish community worldwide', 'navigation'),
('norwegian', 'landing.connect_worldwide', 'Få kontakt med det kurdiske miljøet over hele verden', 'navigation'),
('kurdish_sorani', 'landing.connect_worldwide', 'پەیوەندی بە کۆمەڵگەی کوردی جیهانی بکە', 'navigation'),
('kurdish_kurmanci', 'landing.connect_worldwide', 'Bi civaka Kurd a cîhanê re têkilî daynin', 'navigation'),
('german', 'landing.connect_worldwide', 'Verbinden Sie sich mit der kurdischen Gemeinschaft weltweit', 'navigation'),
('english', 'landing.all_dialects', 'All Kurdish Dialects Welcome', 'navigation'),
('norwegian', 'landing.all_dialects', 'Alle kurdiske dialekter velkommen', 'navigation'),
('kurdish_sorani', 'landing.all_dialects', 'هەموو زاراوەکانی کوردی بەخێرهاتوون', 'navigation'),
('kurdish_kurmanci', 'landing.all_dialects', 'Hemû zaravayên Kurdî bi xêr hatin', 'navigation'),
('german', 'landing.all_dialects', 'Alle kurdischen Dialekte willkommen', 'navigation'),
('english', 'landing.three_steps', 'Three simple steps to start your journey', 'navigation'),
('norwegian', 'landing.three_steps', 'Tre enkle steg for å starte reisen din', 'navigation'),
('kurdish_sorani', 'landing.three_steps', 'سێ هەنگاوی ئاسان بۆ دەستپێکردنی گەشتەکەت', 'navigation'),
('kurdish_kurmanci', 'landing.three_steps', 'Sê gavên hêsan ji bo destpêkirina rêwîtiya te', 'navigation'),
('german', 'landing.three_steps', 'Drei einfache Schritte, um Ihre Reise zu beginnen', 'navigation'),
('english', 'landing.connecting_hearts', 'Connecting Kurdish hearts worldwide', 'navigation'),
('norwegian', 'landing.connecting_hearts', 'Forbinder kurdiske hjerter over hele verden', 'navigation'),
('kurdish_sorani', 'landing.connecting_hearts', 'بەستنەوەی دڵەکانی کوردی جیهان', 'navigation'),
('kurdish_kurmanci', 'landing.connecting_hearts', 'Girêdana dilên Kurd li seranserê cîhanê', 'navigation'),
('german', 'landing.connecting_hearts', 'Kurdische Herzen weltweit verbinden', 'navigation'),
('english', 'landing.footer.company', 'Company', 'navigation'),
('norwegian', 'landing.footer.company', 'Selskap', 'navigation'),
('kurdish_sorani', 'landing.footer.company', 'کۆمپانیا', 'navigation'),
('kurdish_kurmanci', 'landing.footer.company', 'Pargîdanî', 'navigation'),
('german', 'landing.footer.company', 'Unternehmen', 'navigation'),
('english', 'landing.footer.about_us', 'About Us', 'navigation'),
('norwegian', 'landing.footer.about_us', 'Om oss', 'navigation'),
('kurdish_sorani', 'landing.footer.about_us', 'دەربارەی ئێمە', 'navigation'),
('kurdish_kurmanci', 'landing.footer.about_us', 'Der barê me', 'navigation'),
('german', 'landing.footer.about_us', 'Über uns', 'navigation'),
('english', 'landing.footer.help', 'Help & Support', 'navigation'),
('norwegian', 'landing.footer.help', 'Hjelp og støtte', 'navigation'),
('kurdish_sorani', 'landing.footer.help', 'یارمەتی و پشتیوانی', 'navigation'),
('kurdish_kurmanci', 'landing.footer.help', 'Alîkarî û Piştgirî', 'navigation'),
('german', 'landing.footer.help', 'Hilfe & Support', 'navigation'),
('english', 'landing.footer.guidelines', 'Community Guidelines', 'navigation'),
('norwegian', 'landing.footer.guidelines', 'Retningslinjer for fellesskap', 'navigation'),
('kurdish_sorani', 'landing.footer.guidelines', 'ڕێنماییەکانی کۆمەڵگە', 'navigation'),
('kurdish_kurmanci', 'landing.footer.guidelines', 'Rêwerzên Civakê', 'navigation'),
('german', 'landing.footer.guidelines', 'Community-Richtlinien', 'navigation'),
('english', 'landing.footer.legal', 'Legal', 'navigation'),
('norwegian', 'landing.footer.legal', 'Juridisk', 'navigation'),
('kurdish_sorani', 'landing.footer.legal', 'یاسایی', 'navigation'),
('kurdish_kurmanci', 'landing.footer.legal', 'Qanûnî', 'navigation'),
('german', 'landing.footer.legal', 'Rechtliches', 'navigation'),
('english', 'landing.footer.privacy', 'Privacy Policy', 'navigation'),
('norwegian', 'landing.footer.privacy', 'Personvernpolicy', 'navigation'),
('kurdish_sorani', 'landing.footer.privacy', 'سیاسەتی تایبەتمەندی', 'navigation'),
('kurdish_kurmanci', 'landing.footer.privacy', 'Polîtîkaya Nepenîtiyê', 'navigation'),
('german', 'landing.footer.privacy', 'Datenschutzrichtlinie', 'navigation'),
('english', 'landing.footer.terms', 'Terms of Service', 'navigation'),
('norwegian', 'landing.footer.terms', 'Vilkår for bruk', 'navigation'),
('kurdish_sorani', 'landing.footer.terms', 'مەرجەکانی خزمەتگوزاری', 'navigation'),
('kurdish_kurmanci', 'landing.footer.terms', 'Mercên Xizmetê', 'navigation'),
('german', 'landing.footer.terms', 'Nutzungsbedingungen', 'navigation'),
('english', 'landing.footer.cookie', 'Cookie Policy', 'navigation'),
('norwegian', 'landing.footer.cookie', 'Retningslinjer for informasjonskapsler', 'navigation'),
('kurdish_sorani', 'landing.footer.cookie', 'سیاسەتی کوکیز', 'navigation'),
('kurdish_kurmanci', 'landing.footer.cookie', 'Polîtîkaya Cookie', 'navigation'),
('german', 'landing.footer.cookie', 'Cookie-Richtlinie', 'navigation'),
('english', 'landing.footer.contact', 'Contact Us', 'navigation'),
('norwegian', 'landing.footer.contact', 'Kontakt oss', 'navigation'),
('kurdish_sorani', 'landing.footer.contact', 'پەیوەندیمان پێوە بکە', 'navigation'),
('kurdish_kurmanci', 'landing.footer.contact', 'Bi me re têkilî daynin', 'navigation'),
('german', 'landing.footer.contact', 'Kontaktieren Sie uns', 'navigation'),
('english', 'landing.footer.get_started', 'Get Started', 'navigation'),
('norwegian', 'landing.footer.get_started', 'Kom i gang', 'navigation'),
('kurdish_sorani', 'landing.footer.get_started', 'دەست بکە', 'navigation'),
('kurdish_kurmanci', 'landing.footer.get_started', 'Dest pê bike', 'navigation'),
('german', 'landing.footer.get_started', 'Loslegen', 'navigation'),
('english', 'landing.footer.register', 'Register', 'navigation'),
('norwegian', 'landing.footer.register', 'Registrer', 'navigation'),
('kurdish_sorani', 'landing.footer.register', 'تۆمارکردن', 'navigation'),
('kurdish_kurmanci', 'landing.footer.register', 'Tomar bibe', 'navigation'),
('german', 'landing.footer.register', 'Registrieren', 'navigation'),
('english', 'landing.footer.all_rights', 'All rights reserved.', 'navigation'),
('norwegian', 'landing.footer.all_rights', 'Alle rettigheter forbeholdt.', 'navigation'),
('kurdish_sorani', 'landing.footer.all_rights', 'هەموو مافەکان پارێزراون.', 'navigation'),
('kurdish_kurmanci', 'landing.footer.all_rights', 'Hemû maf parastî ne.', 'navigation'),
('german', 'landing.footer.all_rights', 'Alle Rechte vorbehalten.', 'navigation')
ON CONFLICT DO NOTHING;

-- ===== MOBILE SIDEBAR =====
INSERT INTO app_translations (language_code, translation_key, translation_value, category) VALUES
('english', 'sidebar.login', 'Login', 'navigation'),
('norwegian', 'sidebar.login', 'Logg inn', 'navigation'),
('kurdish_sorani', 'sidebar.login', 'چوونەژوورەوە', 'navigation'),
('kurdish_kurmanci', 'sidebar.login', 'Têkeve', 'navigation'),
('german', 'sidebar.login', 'Anmelden', 'navigation'),
('english', 'sidebar.registration', 'Registration', 'navigation'),
('norwegian', 'sidebar.registration', 'Registrering', 'navigation'),
('kurdish_sorani', 'sidebar.registration', 'تۆمارکردن', 'navigation'),
('kurdish_kurmanci', 'sidebar.registration', 'Tomarbûn', 'navigation'),
('german', 'sidebar.registration', 'Registrierung', 'navigation'),
('english', 'sidebar.about', 'About Us', 'navigation'),
('norwegian', 'sidebar.about', 'Om oss', 'navigation'),
('kurdish_sorani', 'sidebar.about', 'دەربارەی ئێمە', 'navigation'),
('kurdish_kurmanci', 'sidebar.about', 'Der barê me', 'navigation'),
('german', 'sidebar.about', 'Über uns', 'navigation'),
('english', 'sidebar.contact', 'Contact Us', 'navigation'),
('norwegian', 'sidebar.contact', 'Kontakt oss', 'navigation'),
('kurdish_sorani', 'sidebar.contact', 'پەیوەندیمان پێوە بکە', 'navigation'),
('kurdish_kurmanci', 'sidebar.contact', 'Bi me re têkilî daynin', 'navigation'),
('german', 'sidebar.contact', 'Kontaktieren Sie uns', 'navigation'),
('english', 'sidebar.language', 'Language', 'navigation'),
('norwegian', 'sidebar.language', 'Språk', 'navigation'),
('kurdish_sorani', 'sidebar.language', 'زمان', 'navigation'),
('kurdish_kurmanci', 'sidebar.language', 'Ziman', 'navigation'),
('german', 'sidebar.language', 'Sprache', 'navigation'),
('english', 'sidebar.kurdish_hearts', 'Kurdish Hearts', 'navigation'),
('norwegian', 'sidebar.kurdish_hearts', 'Kurdiske hjerter', 'navigation'),
('kurdish_sorani', 'sidebar.kurdish_hearts', 'دڵەکانی کورد', 'navigation'),
('kurdish_kurmanci', 'sidebar.kurdish_hearts', 'Dilên Kurd', 'navigation'),
('german', 'sidebar.kurdish_hearts', 'Kurdische Herzen', 'navigation')
ON CONFLICT DO NOTHING;

-- ===== SUBSCRIPTION (missing keys) =====
INSERT INTO app_translations (language_code, translation_key, translation_value, category) VALUES
('english', 'subscription.current_plan', 'Current Plan', 'settings'),
('norwegian', 'subscription.current_plan', 'Nåværende plan', 'settings'),
('kurdish_sorani', 'subscription.current_plan', 'پلانی ئێستا', 'settings'),
('kurdish_kurmanci', 'subscription.current_plan', 'Plana niha', 'settings'),
('german', 'subscription.current_plan', 'Aktueller Plan', 'settings'),
('english', 'subscription.refresh', 'Refresh', 'settings'),
('norwegian', 'subscription.refresh', 'Oppdater', 'settings'),
('kurdish_sorani', 'subscription.refresh', 'نوێکردنەوە', 'settings'),
('kurdish_kurmanci', 'subscription.refresh', 'Nû bike', 'settings'),
('german', 'subscription.refresh', 'Aktualisieren', 'settings'),
('english', 'subscription.manage', 'Manage', 'settings'),
('norwegian', 'subscription.manage', 'Administrer', 'settings'),
('kurdish_sorani', 'subscription.manage', 'بەڕێوەبردن', 'settings'),
('kurdish_kurmanci', 'subscription.manage', 'Birêve bibe', 'settings'),
('german', 'subscription.manage', 'Verwalten', 'settings'),
('english', 'subscription.billed_monthly', 'All subscriptions are billed monthly', 'settings'),
('norwegian', 'subscription.billed_monthly', 'Alle abonnementer faktureres månedlig', 'settings'),
('kurdish_sorani', 'subscription.billed_monthly', 'هەموو ئابوونەکان مانگانە پارە دەدرێت', 'settings'),
('kurdish_kurmanci', 'subscription.billed_monthly', 'Hemû abonetî mehane têne faturekirin', 'settings'),
('german', 'subscription.billed_monthly', 'Alle Abonnements werden monatlich abgerechnet', 'settings'),
('english', 'subscription.cancel_anytime', 'Cancel anytime through the management portal', 'settings'),
('norwegian', 'subscription.cancel_anytime', 'Avbryt når som helst gjennom administrasjonsportalen', 'settings'),
('kurdish_sorani', 'subscription.cancel_anytime', 'هەر کاتێک دەتوانیت هەڵیبوەشێنیتەوە', 'settings'),
('kurdish_kurmanci', 'subscription.cancel_anytime', 'Her dem dikare betal bikî', 'settings'),
('german', 'subscription.cancel_anytime', 'Jederzeit über das Verwaltungsportal kündbar', 'settings'),
('english', 'subscription.upgrades_immediate', 'Upgrades take effect immediately', 'settings'),
('norwegian', 'subscription.upgrades_immediate', 'Oppgraderinger trer i kraft umiddelbart', 'settings'),
('kurdish_sorani', 'subscription.upgrades_immediate', 'نوێکردنەوەکان دەستبەجێ کاردەکەن', 'settings'),
('kurdish_kurmanci', 'subscription.upgrades_immediate', 'Bilindkirin tavilê bandor dibin', 'settings'),
('german', 'subscription.upgrades_immediate', 'Upgrades werden sofort wirksam', 'settings'),
('english', 'subscription.secure_payments', 'Secure payments powered by Stripe', 'settings'),
('norwegian', 'subscription.secure_payments', 'Sikre betalinger drevet av Stripe', 'settings'),
('kurdish_sorani', 'subscription.secure_payments', 'پارەدانی ئاراستە لەلایەن Stripe', 'settings'),
('kurdish_kurmanci', 'subscription.secure_payments', 'Dravdanên ewle ji hêla Stripe ve', 'settings'),
('german', 'subscription.secure_payments', 'Sichere Zahlungen powered by Stripe', 'settings')
ON CONFLICT DO NOTHING;

-- ===== BLOCKED USERS (missing keys) =====
INSERT INTO app_translations (language_code, translation_key, translation_value, category) VALUES
('english', 'blocked.unblock', 'Unblock', 'settings'),
('norwegian', 'blocked.unblock', 'Opphev blokkering', 'settings'),
('kurdish_sorani', 'blocked.unblock', 'بلۆک لابردن', 'settings'),
('kurdish_kurmanci', 'blocked.unblock', 'Blokê rake', 'settings'),
('german', 'blocked.unblock', 'Entsperren', 'settings'),
('english', 'blocked.unblock_title', 'Unblock User?', 'settings'),
('norwegian', 'blocked.unblock_title', 'Oppheve blokkering?', 'settings'),
('kurdish_sorani', 'blocked.unblock_title', 'بەکارهێنەر بلۆک لابەرەوە؟', 'settings'),
('kurdish_kurmanci', 'blocked.unblock_title', 'Bikarhêner blokê ji rakî?', 'settings'),
('german', 'blocked.unblock_title', 'Benutzer entsperren?', 'settings'),
('english', 'blocked.unblock_confirm', 'Are you sure you want to unblock {{name}}?', 'settings'),
('norwegian', 'blocked.unblock_confirm', 'Er du sikker på at du vil oppheve blokkeringen av {{name}}?', 'settings'),
('kurdish_sorani', 'blocked.unblock_confirm', 'دڵنیایت دەتەوێت بلۆکی {{name}} لاببەیت؟', 'settings'),
('kurdish_kurmanci', 'blocked.unblock_confirm', 'Tu bawer î ku dixwazî bloka {{name}} rakî?', 'settings'),
('german', 'blocked.unblock_confirm', 'Möchten Sie {{name}} wirklich entsperren?', 'settings'),
('english', 'blocked.cancel', 'Cancel', 'common'),
('norwegian', 'blocked.cancel', 'Avbryt', 'common'),
('kurdish_sorani', 'blocked.cancel', 'پاشگەزبوونەوە', 'common'),
('kurdish_kurmanci', 'blocked.cancel', 'Betal bike', 'common'),
('german', 'blocked.cancel', 'Abbrechen', 'common'),
('english', 'blocked.blocked_date', 'Blocked', 'settings'),
('norwegian', 'blocked.blocked_date', 'Blokkert', 'settings'),
('kurdish_sorani', 'blocked.blocked_date', 'بلۆککرا', 'settings'),
('kurdish_kurmanci', 'blocked.blocked_date', 'Hat blokekirin', 'settings'),
('german', 'blocked.blocked_date', 'Blockiert', 'settings'),
('english', 'blocked.users_blocked', '{{count}} user(s) blocked', 'settings'),
('norwegian', 'blocked.users_blocked', '{{count}} bruker(e) blokkert', 'settings'),
('kurdish_sorani', 'blocked.users_blocked', '{{count}} بەکارهێنەر بلۆککراوە', 'settings'),
('kurdish_kurmanci', 'blocked.users_blocked', '{{count}} bikarhêner hatine blokekirin', 'settings'),
('german', 'blocked.users_blocked', '{{count}} Benutzer blockiert', 'settings')
ON CONFLICT DO NOTHING;

-- ===== MATCHES (missing keys) =====
INSERT INTO app_translations (language_code, translation_key, translation_value, category) VALUES
('english', 'matches.new', 'New', 'discovery'),
('norwegian', 'matches.new', 'Ny', 'discovery'),
('kurdish_sorani', 'matches.new', 'نوێ', 'discovery'),
('kurdish_kurmanci', 'matches.new', 'Nû', 'discovery'),
('german', 'matches.new', 'Neu', 'discovery'),
('english', 'matches.just_now', 'Just now', 'discovery'),
('norwegian', 'matches.just_now', 'Akkurat nå', 'discovery'),
('kurdish_sorani', 'matches.just_now', 'ئێستا', 'discovery'),
('kurdish_kurmanci', 'matches.just_now', 'Niha', 'discovery'),
('german', 'matches.just_now', 'Gerade eben', 'discovery'),
('english', 'matches.hours_ago', '{{count}}h ago', 'discovery'),
('norwegian', 'matches.hours_ago', '{{count}}t siden', 'discovery'),
('kurdish_sorani', 'matches.hours_ago', '{{count}} کاتژمێر لەمەوپێش', 'discovery'),
('kurdish_kurmanci', 'matches.hours_ago', '{{count}} saet berê', 'discovery'),
('german', 'matches.hours_ago', 'vor {{count}} Std.', 'discovery'),
('english', 'matches.yesterday', 'Yesterday', 'discovery'),
('norwegian', 'matches.yesterday', 'I går', 'discovery'),
('kurdish_sorani', 'matches.yesterday', 'دوێنێ', 'discovery'),
('kurdish_kurmanci', 'matches.yesterday', 'Duh', 'discovery'),
('german', 'matches.yesterday', 'Gestern', 'discovery'),
('english', 'matches.days_ago', '{{count}}d ago', 'discovery'),
('norwegian', 'matches.days_ago', '{{count}}d siden', 'discovery'),
('kurdish_sorani', 'matches.days_ago', '{{count}} ڕۆژ لەمەوپێش', 'discovery'),
('kurdish_kurmanci', 'matches.days_ago', '{{count}} roj berê', 'discovery'),
('german', 'matches.days_ago', 'vor {{count}} Tagen', 'discovery'),
('english', 'matches.loading', 'Loading matches...', 'discovery'),
('norwegian', 'matches.loading', 'Laster matcher...', 'discovery'),
('kurdish_sorani', 'matches.loading', 'بارکردنی ماچەکان...', 'discovery'),
('kurdish_kurmanci', 'matches.loading', 'Bar kirin...', 'discovery'),
('german', 'matches.loading', 'Matches werden geladen...', 'discovery')
ON CONFLICT DO NOTHING;

-- ===== NOTIFICATIONS (missing keys) =====
INSERT INTO app_translations (language_code, translation_key, translation_value, category) VALUES
('english', 'notifications.new_like', 'New Like', 'notifications'),
('norwegian', 'notifications.new_like', 'Ny like', 'notifications'),
('kurdish_sorani', 'notifications.new_like', 'لایکی نوێ', 'notifications'),
('kurdish_kurmanci', 'notifications.new_like', 'Like nû', 'notifications'),
('german', 'notifications.new_like', 'Neues Like', 'notifications'),
('english', 'notifications.new_comment', 'New Comment', 'notifications'),
('norwegian', 'notifications.new_comment', 'Ny kommentar', 'notifications'),
('kurdish_sorani', 'notifications.new_comment', 'لێدوانی نوێ', 'notifications'),
('kurdish_kurmanci', 'notifications.new_comment', 'Şîrove nû', 'notifications'),
('german', 'notifications.new_comment', 'Neuer Kommentar', 'notifications'),
('english', 'notifications.profile_view', 'Profile View', 'notifications'),
('norwegian', 'notifications.profile_view', 'Profilvisning', 'notifications'),
('kurdish_sorani', 'notifications.profile_view', 'بینینی پرۆفایل', 'notifications'),
('kurdish_kurmanci', 'notifications.profile_view', 'Dîtina Profîlê', 'notifications'),
('german', 'notifications.profile_view', 'Profilansicht', 'notifications'),
('english', 'notifications.all_read', 'All notifications marked as read', 'notifications'),
('norwegian', 'notifications.all_read', 'Alle varsler merket som lest', 'notifications'),
('kurdish_sorani', 'notifications.all_read', 'هەموو ئاگادارییەکان وەک خوێندراوەتەوە نیشانکران', 'notifications'),
('kurdish_kurmanci', 'notifications.all_read', 'Hemû agahdarî wekî xwendî hatin nîşankirin', 'notifications'),
('german', 'notifications.all_read', 'Alle Benachrichtigungen als gelesen markiert', 'notifications'),
('english', 'notifications.removed', 'Notification removed', 'notifications'),
('norwegian', 'notifications.removed', 'Varsel fjernet', 'notifications'),
('kurdish_sorani', 'notifications.removed', 'ئاگاداری لابرا', 'notifications'),
('kurdish_kurmanci', 'notifications.removed', 'Agahdarî hat rakirin', 'notifications'),
('german', 'notifications.removed', 'Benachrichtigung entfernt', 'notifications')
ON CONFLICT DO NOTHING;

-- ===== ABOUT US =====
INSERT INTO app_translations (language_code, translation_key, translation_value, category) VALUES
('english', 'about.title', 'About KurdMatch', 'common'),
('norwegian', 'about.title', 'Om KurdMatch', 'common'),
('kurdish_sorani', 'about.title', 'دەربارەی KurdMatch', 'common'),
('kurdish_kurmanci', 'about.title', 'Der barê KurdMatch', 'common'),
('german', 'about.title', 'Über KurdMatch', 'common'),
('english', 'about.hero_title', 'Where Kurdish Hearts Meet', 'common'),
('norwegian', 'about.hero_title', 'Der kurdiske hjerter møtes', 'common'),
('kurdish_sorani', 'about.hero_title', 'شوێنی کۆبوونەوەی دڵەکانی کورد', 'common'),
('kurdish_kurmanci', 'about.hero_title', 'Cihê ku dilên Kurd hev dibînin', 'common'),
('german', 'about.hero_title', 'Wo kurdische Herzen sich treffen', 'common'),
('english', 'about.hero_desc', 'KurdMatch is the premier platform for Kurdish singles seeking meaningful, marriage-focused relationships. We honor tradition while empowering modern connection.', 'common'),
('norwegian', 'about.hero_desc', 'KurdMatch er den ledende plattformen for kurdiske single som søker meningsfulle, ekteskapsfokuserte forhold. Vi hedrer tradisjon mens vi styrker moderne forbindelser.', 'common'),
('kurdish_sorani', 'about.hero_desc', 'KurdMatch پلاتفۆرمی پێشەنگە بۆ سینگڵەکانی کورد کە لە دوای پەیوەندی مانادار و هاوسەرگیری دەگەڕێن.', 'common'),
('kurdish_kurmanci', 'about.hero_desc', 'KurdMatch platforma pêşeng e ji bo keçîk û xortên Kurd ên ku li têkiliyên watedar û zewacê digerin.', 'common'),
('german', 'about.hero_desc', 'KurdMatch ist die führende Plattform für kurdische Singles, die nach bedeutungsvollen, eheorientierten Beziehungen suchen.', 'common'),
('english', 'about.our_mission', 'Our Mission', 'common'),
('norwegian', 'about.our_mission', 'Vårt oppdrag', 'common'),
('kurdish_sorani', 'about.our_mission', 'ئەرکی ئێمە', 'common'),
('kurdish_kurmanci', 'about.our_mission', 'Mîsyona Me', 'common'),
('german', 'about.our_mission', 'Unsere Mission', 'common'),
('english', 'about.our_values', 'Our Values', 'common'),
('norwegian', 'about.our_values', 'Våre verdier', 'common'),
('kurdish_sorani', 'about.our_values', 'بەهاکانمان', 'common'),
('kurdish_kurmanci', 'about.our_values', 'Nirxên Me', 'common'),
('german', 'about.our_values', 'Unsere Werte', 'common'),
('english', 'about.what_different', 'What Makes Us Different', 'common'),
('norwegian', 'about.what_different', 'Hva gjør oss annerledes', 'common'),
('kurdish_sorani', 'about.what_different', 'چی ئێمە جیاواز دەکات', 'common'),
('kurdish_kurmanci', 'about.what_different', 'Çi me cuda dike', 'common'),
('german', 'about.what_different', 'Was uns unterscheidet', 'common'),
('english', 'about.ready_match', 'Ready to find your match?', 'common'),
('norwegian', 'about.ready_match', 'Klar for å finne din match?', 'common'),
('kurdish_sorani', 'about.ready_match', 'ئامادەیت ماچەکەت بدۆزیتەوە؟', 'common'),
('kurdish_kurmanci', 'about.ready_match', 'Tu amade yî ku maça xwe bibînî?', 'common'),
('german', 'about.ready_match', 'Bereit, Ihr Match zu finden?', 'common'),
('english', 'about.join_today', 'Join KurdMatch Today', 'common'),
('norwegian', 'about.join_today', 'Bli med i KurdMatch i dag', 'common'),
('kurdish_sorani', 'about.join_today', 'ئەمڕۆ بەشداری KurdMatch بکە', 'common'),
('kurdish_kurmanci', 'about.join_today', 'Îro beşdarî KurdMatch bibe', 'common'),
('german', 'about.join_today', 'Treten Sie KurdMatch noch heute bei', 'common'),
('english', 'about.active_members', 'Active Members', 'common'),
('norwegian', 'about.active_members', 'Aktive medlemmer', 'common'),
('kurdish_sorani', 'about.active_members', 'ئەندامە چالاکەکان', 'common'),
('kurdish_kurmanci', 'about.active_members', 'Endamên Çalak', 'common'),
('german', 'about.active_members', 'Aktive Mitglieder', 'common'),
('english', 'about.matches_made', 'Matches Made', 'common'),
('norwegian', 'about.matches_made', 'Matcher gjort', 'common'),
('kurdish_sorani', 'about.matches_made', 'ماچی کراو', 'common'),
('kurdish_kurmanci', 'about.matches_made', 'Maçên Çêkirî', 'common'),
('german', 'about.matches_made', 'Matches erstellt', 'common'),
('english', 'about.countries', 'Countries', 'common'),
('norwegian', 'about.countries', 'Land', 'common'),
('kurdish_sorani', 'about.countries', 'وڵات', 'common'),
('kurdish_kurmanci', 'about.countries', 'Welat', 'common'),
('german', 'about.countries', 'Länder', 'common'),
('english', 'about.app_rating', 'App Rating', 'common'),
('norwegian', 'about.app_rating', 'Appvurdering', 'common'),
('kurdish_sorani', 'about.app_rating', 'نمرەی ئاپ', 'common'),
('kurdish_kurmanci', 'about.app_rating', 'Pîvana Appê', 'common'),
('german', 'about.app_rating', 'App-Bewertung', 'common')
ON CONFLICT DO NOTHING;

-- ===== CONTACT US =====
INSERT INTO app_translations (language_code, translation_key, translation_value, category) VALUES
('english', 'contact.title', 'Contact Us', 'common'),
('norwegian', 'contact.title', 'Kontakt oss', 'common'),
('kurdish_sorani', 'contact.title', 'پەیوەندیمان پێوە بکە', 'common'),
('kurdish_kurmanci', 'contact.title', 'Bi me re têkilî daynin', 'common'),
('german', 'contact.title', 'Kontaktieren Sie uns', 'common'),
('english', 'contact.get_in_touch', 'Get In Touch', 'common'),
('norwegian', 'contact.get_in_touch', 'Ta kontakt', 'common'),
('kurdish_sorani', 'contact.get_in_touch', 'پەیوەندی بکە', 'common'),
('kurdish_kurmanci', 'contact.get_in_touch', 'Têkilî dayne', 'common'),
('german', 'contact.get_in_touch', 'Kontakt aufnehmen', 'common'),
('english', 'contact.subtitle', 'Have a question, feedback, or need help? We''d love to hear from you.', 'common'),
('norwegian', 'contact.subtitle', 'Har du et spørsmål, tilbakemelding eller trenger hjelp? Vi vil gjerne høre fra deg.', 'common'),
('kurdish_sorani', 'contact.subtitle', 'پرسیارت هەیە، فیدباک، یان پێویستت بە یارمەتی هەیە؟ حەزمان دەکات لێت بیستین.', 'common'),
('kurdish_kurmanci', 'contact.subtitle', 'Pirsek, bertek an hewcedariya alîkariyê hene? Em dixwazin ji te bibîstin.', 'common'),
('german', 'contact.subtitle', 'Haben Sie eine Frage, Feedback oder brauchen Sie Hilfe? Wir würden gerne von Ihnen hören.', 'common'),
('english', 'contact.full_name', 'Full Name', 'common'),
('norwegian', 'contact.full_name', 'Fullt navn', 'common'),
('kurdish_sorani', 'contact.full_name', 'ناوی تەواو', 'common'),
('kurdish_kurmanci', 'contact.full_name', 'Navê tevahî', 'common'),
('german', 'contact.full_name', 'Vollständiger Name', 'common'),
('english', 'contact.your_name', 'Your name', 'common'),
('norwegian', 'contact.your_name', 'Ditt navn', 'common'),
('kurdish_sorani', 'contact.your_name', 'ناوی تۆ', 'common'),
('kurdish_kurmanci', 'contact.your_name', 'Navê te', 'common'),
('german', 'contact.your_name', 'Ihr Name', 'common'),
('english', 'contact.email', 'Email', 'common'),
('norwegian', 'contact.email', 'E-post', 'common'),
('kurdish_sorani', 'contact.email', 'ئیمەیڵ', 'common'),
('kurdish_kurmanci', 'contact.email', 'E-peyam', 'common'),
('german', 'contact.email', 'E-Mail', 'common'),
('english', 'contact.subject', 'Subject', 'common'),
('norwegian', 'contact.subject', 'Emne', 'common'),
('kurdish_sorani', 'contact.subject', 'بابەت', 'common'),
('kurdish_kurmanci', 'contact.subject', 'Mijar', 'common'),
('german', 'contact.subject', 'Betreff', 'common'),
('english', 'contact.select_topic', 'Select a topic', 'common'),
('norwegian', 'contact.select_topic', 'Velg et emne', 'common'),
('kurdish_sorani', 'contact.select_topic', 'بابەتێک هەڵبژێرە', 'common'),
('kurdish_kurmanci', 'contact.select_topic', 'Mijarekê hilbijêre', 'common'),
('german', 'contact.select_topic', 'Wählen Sie ein Thema', 'common'),
('english', 'contact.general', 'General Inquiry', 'common'),
('norwegian', 'contact.general', 'Generell forespørsel', 'common'),
('kurdish_sorani', 'contact.general', 'داواکاری گشتی', 'common'),
('kurdish_kurmanci', 'contact.general', 'Daxwaza Giştî', 'common'),
('german', 'contact.general', 'Allgemeine Anfrage', 'common'),
('english', 'contact.account_issue', 'Account Issue', 'common'),
('norwegian', 'contact.account_issue', 'Kontoproblem', 'common'),
('kurdish_sorani', 'contact.account_issue', 'کێشەی هەژمار', 'common'),
('kurdish_kurmanci', 'contact.account_issue', 'Pirsgirêka Hesab', 'common'),
('german', 'contact.account_issue', 'Kontoproblem', 'common'),
('english', 'contact.billing', 'Billing & Subscription', 'common'),
('norwegian', 'contact.billing', 'Fakturering og abonnement', 'common'),
('kurdish_sorani', 'contact.billing', 'قەرز و ئابوونە', 'common'),
('kurdish_kurmanci', 'contact.billing', 'Fatûrekirin û Aboneyî', 'common'),
('german', 'contact.billing', 'Abrechnung & Abonnement', 'common'),
('english', 'contact.safety', 'Safety Concern', 'common'),
('norwegian', 'contact.safety', 'Sikkerhetsbekymring', 'common'),
('kurdish_sorani', 'contact.safety', 'نیگەرانی ئاسایش', 'common'),
('kurdish_kurmanci', 'contact.safety', 'Fikarên Ewlehiyê', 'common'),
('german', 'contact.safety', 'Sicherheitsbedenken', 'common'),
('english', 'contact.bug', 'Bug Report', 'common'),
('norwegian', 'contact.bug', 'Feilrapport', 'common'),
('kurdish_sorani', 'contact.bug', 'ڕاپۆرتی هەڵە', 'common'),
('kurdish_kurmanci', 'contact.bug', 'Rapora Xeletiyê', 'common'),
('german', 'contact.bug', 'Fehlerbericht', 'common'),
('english', 'contact.feature', 'Feature Request', 'common'),
('norwegian', 'contact.feature', 'Funksjonsforespørsel', 'common'),
('kurdish_sorani', 'contact.feature', 'داواکاری تایبەتمەندی', 'common'),
('kurdish_kurmanci', 'contact.feature', 'Daxwaza Taybetmendiyê', 'common'),
('german', 'contact.feature', 'Funktionsanfrage', 'common'),
('english', 'contact.partnership', 'Partnership', 'common'),
('norwegian', 'contact.partnership', 'Partnerskap', 'common'),
('kurdish_sorani', 'contact.partnership', 'هاوبەشی', 'common'),
('kurdish_kurmanci', 'contact.partnership', 'Hevkarî', 'common'),
('german', 'contact.partnership', 'Partnerschaft', 'common'),
('english', 'contact.message', 'Message', 'common'),
('norwegian', 'contact.message', 'Melding', 'common'),
('kurdish_sorani', 'contact.message', 'نامە', 'common'),
('kurdish_kurmanci', 'contact.message', 'Peyam', 'common'),
('german', 'contact.message', 'Nachricht', 'common'),
('english', 'contact.how_help', 'Tell us how we can help...', 'common'),
('norwegian', 'contact.how_help', 'Fortell oss hvordan vi kan hjelpe...', 'common'),
('kurdish_sorani', 'contact.how_help', 'پێمان بڵێ چۆن دەتوانین یارمەتیت بدەین...', 'common'),
('kurdish_kurmanci', 'contact.how_help', 'Ji me re bêje em çawa dikarin alîkariya te bikin...', 'common'),
('german', 'contact.how_help', 'Sagen Sie uns, wie wir Ihnen helfen können...', 'common'),
('english', 'contact.sending', 'Sending...', 'common'),
('norwegian', 'contact.sending', 'Sender...', 'common'),
('kurdish_sorani', 'contact.sending', 'ناردن...', 'common'),
('kurdish_kurmanci', 'contact.sending', 'Dişîne...', 'common'),
('german', 'contact.sending', 'Senden...', 'common'),
('english', 'contact.send_message', 'Send Message', 'common'),
('norwegian', 'contact.send_message', 'Send melding', 'common'),
('kurdish_sorani', 'contact.send_message', 'نامە بنێرە', 'common'),
('kurdish_kurmanci', 'contact.send_message', 'Peyam bişîne', 'common'),
('german', 'contact.send_message', 'Nachricht senden', 'common'),
('english', 'contact.fill_all', 'Please fill in all fields', 'common'),
('norwegian', 'contact.fill_all', 'Vennligst fyll ut alle felt', 'common'),
('kurdish_sorani', 'contact.fill_all', 'تکایە هەموو خانەکان پڕ بکەوە', 'common'),
('kurdish_kurmanci', 'contact.fill_all', 'Ji kerema xwe hemû zeviyan dagire', 'common'),
('german', 'contact.fill_all', 'Bitte füllen Sie alle Felder aus', 'common'),
('english', 'contact.success', 'Message sent successfully! We''ll get back to you within 24-48 hours.', 'common'),
('norwegian', 'contact.success', 'Meldingen ble sendt! Vi kommer tilbake til deg innen 24-48 timer.', 'common'),
('kurdish_sorani', 'contact.success', 'نامەکە بە سەرکەوتوویی نێردرا! لە ماوەی ٢٤-٤٨ کاتژمێردا پەیوەندیت پێوە دەکەین.', 'common'),
('kurdish_kurmanci', 'contact.success', 'Peyam bi serkeftî hat şandin! Di nav 24-48 demjimêran de em ê bi te re têkilî daynin.', 'common'),
('german', 'contact.success', 'Nachricht erfolgreich gesendet! Wir melden uns innerhalb von 24-48 Stunden bei Ihnen.', 'common'),
('english', 'contact.response_time', 'Average response time:', 'common'),
('norwegian', 'contact.response_time', 'Gjennomsnittlig svartid:', 'common'),
('kurdish_sorani', 'contact.response_time', 'کاتی وەڵامدانەوەی ناوەند:', 'common'),
('kurdish_kurmanci', 'contact.response_time', 'Dema bersivdanê ya navîn:', 'common'),
('german', 'contact.response_time', 'Durchschnittliche Antwortzeit:', 'common'),
('english', 'contact.hours', '24 hours', 'common'),
('norwegian', 'contact.hours', '24 timer', 'common'),
('kurdish_sorani', 'contact.hours', '٢٤ کاتژمێر', 'common'),
('kurdish_kurmanci', 'contact.hours', '24 demjimêr', 'common'),
('german', 'contact.hours', '24 Stunden', 'common'),
('english', 'contact.urgent', 'For urgent safety concerns, please use the in-app report feature.', 'common'),
('norwegian', 'contact.urgent', 'For presserende sikkerhetsbekymringer, bruk rapportfunksjonen i appen.', 'common'),
('kurdish_sorani', 'contact.urgent', 'بۆ نیگەرانییەکانی ئاسایشی نوقسانی، تکایە تایبەتمەندی ڕاپۆرتی ئاپەکە بەکاربهێنە.', 'common'),
('kurdish_kurmanci', 'contact.urgent', 'Ji bo fikarên ewlehiyê yên acîl, ji kerema xwe taybetmendiya raporê ya di sepanê de bi kar bînin.', 'common'),
('german', 'contact.urgent', 'Bei dringenden Sicherheitsbedenken nutzen Sie bitte die In-App-Meldefunktion.', 'common'),
('english', 'contact.live_chat', 'Live Chat', 'common'),
('norwegian', 'contact.live_chat', 'Live Chat', 'common'),
('kurdish_sorani', 'contact.live_chat', 'چاتی ڕاستەوخۆ', 'common'),
('kurdish_kurmanci', 'contact.live_chat', 'Sohbeta Zindî', 'common'),
('german', 'contact.live_chat', 'Live-Chat', 'common'),
('english', 'contact.available', 'Available 9am-9pm CET', 'common'),
('norwegian', 'contact.available', 'Tilgjengelig 09-21 CET', 'common'),
('kurdish_sorani', 'contact.available', 'بەردەستە ٩پ.ن-٩د.ن CET', 'common'),
('kurdish_kurmanci', 'contact.available', 'Li ber dest e 9ê sibehê - 9ê êvarê CET', 'common'),
('german', 'contact.available', 'Verfügbar 9-21 Uhr MEZ', 'common'),
('english', 'contact.location', 'Location', 'common'),
('norwegian', 'contact.location', 'Sted', 'common'),
('kurdish_sorani', 'contact.location', 'شوێن', 'common'),
('kurdish_kurmanci', 'contact.location', 'Cih', 'common'),
('german', 'contact.location', 'Standort', 'common')
ON CONFLICT DO NOTHING;

-- ===== COMMUNITY GUIDELINES =====
INSERT INTO app_translations (language_code, translation_key, translation_value, category) VALUES
('english', 'guidelines.title', 'Community Guidelines', 'common'),
('norwegian', 'guidelines.title', 'Retningslinjer for fellesskap', 'common'),
('kurdish_sorani', 'guidelines.title', 'ڕێنماییەکانی کۆمەڵگە', 'common'),
('kurdish_kurmanci', 'guidelines.title', 'Rêwerzên Civakê', 'common'),
('german', 'guidelines.title', 'Community-Richtlinien', 'common'),
('english', 'guidelines.subtitle', 'Rules for a safe community', 'common'),
('norwegian', 'guidelines.subtitle', 'Regler for et trygt fellesskap', 'common'),
('kurdish_sorani', 'guidelines.subtitle', 'یاساکان بۆ کۆمەڵگەیەکی سەلامەت', 'common'),
('kurdish_kurmanci', 'guidelines.subtitle', 'Qaîdeyên ji bo civakek ewle', 'common'),
('german', 'guidelines.subtitle', 'Regeln für eine sichere Community', 'common'),
('english', 'guidelines.welcome', 'Welcome to KurdMatch', 'common'),
('norwegian', 'guidelines.welcome', 'Velkommen til KurdMatch', 'common'),
('kurdish_sorani', 'guidelines.welcome', 'بەخێربێیت بۆ KurdMatch', 'common'),
('kurdish_kurmanci', 'guidelines.welcome', 'Bi xêr hatî KurdMatch', 'common'),
('german', 'guidelines.welcome', 'Willkommen bei KurdMatch', 'common'),
('english', 'guidelines.prohibited', 'Prohibited Behavior', 'common'),
('norwegian', 'guidelines.prohibited', 'Forbudt atferd', 'common'),
('kurdish_sorani', 'guidelines.prohibited', 'ڕەفتاری قەدەغەکراو', 'common'),
('kurdish_kurmanci', 'guidelines.prohibited', 'Tevgerên Qedexekirî', 'common'),
('german', 'guidelines.prohibited', 'Verbotenes Verhalten', 'common'),
('english', 'guidelines.how_report', 'How to Report', 'common'),
('norwegian', 'guidelines.how_report', 'Hvordan rapportere', 'common'),
('kurdish_sorani', 'guidelines.how_report', 'چۆن ڕاپۆرت بکەیت', 'common'),
('kurdish_kurmanci', 'guidelines.how_report', 'Çawa rapor bikî', 'common'),
('german', 'guidelines.how_report', 'Wie man meldet', 'common'),
('english', 'guidelines.questions', 'Questions about our guidelines?', 'common'),
('norwegian', 'guidelines.questions', 'Spørsmål om retningslinjene våre?', 'common'),
('kurdish_sorani', 'guidelines.questions', 'پرسیارت هەیە دەربارەی ڕێنماییەکانمان؟', 'common'),
('kurdish_kurmanci', 'guidelines.questions', 'Pirsên te yên der barê rêwerzên me hene?', 'common'),
('german', 'guidelines.questions', 'Fragen zu unseren Richtlinien?', 'common'),
('english', 'guidelines.contact_support', 'Contact Support', 'common'),
('norwegian', 'guidelines.contact_support', 'Kontakt støtte', 'common'),
('kurdish_sorani', 'guidelines.contact_support', 'پەیوەندی بە پشتیوانی بکە', 'common'),
('kurdish_kurmanci', 'guidelines.contact_support', 'Bi piştgiriyê re têkilî dayne', 'common'),
('german', 'guidelines.contact_support', 'Support kontaktieren', 'common')
ON CONFLICT DO NOTHING;

-- ===== HELP SUPPORT (UI labels only, not FAQ content) =====
INSERT INTO app_translations (language_code, translation_key, translation_value, category) VALUES
('english', 'help.search', 'Search for help...', 'common'),
('norwegian', 'help.search', 'Søk etter hjelp...', 'common'),
('kurdish_sorani', 'help.search', 'بگەڕێ بۆ یارمەتی...', 'common'),
('kurdish_kurmanci', 'help.search', 'Ji bo alîkariyê bigere...', 'common'),
('german', 'help.search', 'Hilfe suchen...', 'common'),
('english', 'help.contact_us', 'Contact Us', 'common'),
('norwegian', 'help.contact_us', 'Kontakt oss', 'common'),
('kurdish_sorani', 'help.contact_us', 'پەیوەندیمان پێوە بکە', 'common'),
('kurdish_kurmanci', 'help.contact_us', 'Bi me re têkilî daynin', 'common'),
('german', 'help.contact_us', 'Kontaktieren Sie uns', 'common'),
('english', 'help.send_message', 'Send a message', 'common'),
('norwegian', 'help.send_message', 'Send en melding', 'common'),
('kurdish_sorani', 'help.send_message', 'نامەیەک بنێرە', 'common'),
('kurdish_kurmanci', 'help.send_message', 'Peyamek bişîne', 'common'),
('german', 'help.send_message', 'Nachricht senden', 'common'),
('english', 'help.guidelines', 'Guidelines', 'common'),
('norwegian', 'help.guidelines', 'Retningslinjer', 'common'),
('kurdish_sorani', 'help.guidelines', 'ڕێنماییەکان', 'common'),
('kurdish_kurmanci', 'help.guidelines', 'Rêwerz', 'common'),
('german', 'help.guidelines', 'Richtlinien', 'common'),
('english', 'help.community_rules', 'Community rules', 'common'),
('norwegian', 'help.community_rules', 'Fellesskapsregler', 'common'),
('kurdish_sorani', 'help.community_rules', 'یاساکانی کۆمەڵگە', 'common'),
('kurdish_kurmanci', 'help.community_rules', 'Qaîdeyên civakê', 'common'),
('german', 'help.community_rules', 'Community-Regeln', 'common'),
('english', 'help.my_tickets', 'My Support Tickets', 'common'),
('norwegian', 'help.my_tickets', 'Mine støttebilletter', 'common'),
('kurdish_sorani', 'help.my_tickets', 'تیکێتەکانی پشتیوانیم', 'common'),
('kurdish_kurmanci', 'help.my_tickets', 'Bilêtên Piştgiriya Min', 'common'),
('german', 'help.my_tickets', 'Meine Support-Tickets', 'common'),
('english', 'help.search_results', 'Search Results', 'common'),
('norwegian', 'help.search_results', 'Søkeresultater', 'common'),
('kurdish_sorani', 'help.search_results', 'ئەنجامەکانی گەڕان', 'common'),
('kurdish_kurmanci', 'help.search_results', 'Encamên Lêgerînê', 'common'),
('german', 'help.search_results', 'Suchergebnisse', 'common'),
('english', 'help.clear', 'Clear', 'common'),
('norwegian', 'help.clear', 'Tøm', 'common'),
('kurdish_sorani', 'help.clear', 'پاککردنەوە', 'common'),
('kurdish_kurmanci', 'help.clear', 'Paqij bike', 'common'),
('german', 'help.clear', 'Löschen', 'common'),
('english', 'help.popular_questions', 'Popular Questions', 'common'),
('norwegian', 'help.popular_questions', 'Populære spørsmål', 'common'),
('kurdish_sorani', 'help.popular_questions', 'پرسیارە بەناوبانگەکان', 'common'),
('kurdish_kurmanci', 'help.popular_questions', 'Pirsên Populer', 'common'),
('german', 'help.popular_questions', 'Beliebte Fragen', 'common'),
('english', 'help.all_topics', 'All Topics', 'common'),
('norwegian', 'help.all_topics', 'Alle emner', 'common'),
('kurdish_sorani', 'help.all_topics', 'هەموو بابەتەکان', 'common'),
('kurdish_kurmanci', 'help.all_topics', 'Hemû Mijar', 'common'),
('german', 'help.all_topics', 'Alle Themen', 'common'),
('english', 'help.no_results', 'No results found for', 'common'),
('norwegian', 'help.no_results', 'Ingen resultater funnet for', 'common'),
('kurdish_sorani', 'help.no_results', 'هیچ ئەنجامێک نەدۆزرایەوە بۆ', 'common'),
('kurdish_kurmanci', 'help.no_results', 'Ji bo tu encam nehatin dîtin', 'common'),
('german', 'help.no_results', 'Keine Ergebnisse gefunden für', 'common'),
('english', 'help.contact_instead', 'Contact support instead', 'common'),
('norwegian', 'help.contact_instead', 'Kontakt støtte i stedet', 'common'),
('kurdish_sorani', 'help.contact_instead', 'لە جیاتی ئەوە پەیوەندی بە پشتیوانی بکە', 'common'),
('kurdish_kurmanci', 'help.contact_instead', 'Li şûna wê bi piştgiriyê re têkilî dayne', 'common'),
('german', 'help.contact_instead', 'Stattdessen Support kontaktieren', 'common'),
('english', 'help.still_need', 'Still need help?', 'common'),
('norwegian', 'help.still_need', 'Trenger du fortsatt hjelp?', 'common'),
('kurdish_sorani', 'help.still_need', 'هێشتا پێویستت بە یارمەتی هەیە؟', 'common'),
('kurdish_kurmanci', 'help.still_need', 'Hêj hewcedariya te bi alîkariyê heye?', 'common'),
('german', 'help.still_need', 'Brauchen Sie noch Hilfe?', 'common'),
('english', 'help.support_247', 'Our support team is available 24/7 to assist you', 'common'),
('norwegian', 'help.support_247', 'Vårt støtteteam er tilgjengelig 24/7 for å hjelpe deg', 'common'),
('kurdish_sorani', 'help.support_247', 'تیمی پشتیوانی ئێمە ٢٤/٧ بەردەستە بۆ یارمەتیدانت', 'common'),
('kurdish_kurmanci', 'help.support_247', 'Tîma piştgiriya me 24/7 amade ye ku alîkariya te bike', 'common'),
('german', 'help.support_247', 'Unser Support-Team ist rund um die Uhr für Sie da', 'common'),
('english', 'help.contact_support', 'Contact Support', 'common'),
('norwegian', 'help.contact_support', 'Kontakt støtte', 'common'),
('kurdish_sorani', 'help.contact_support', 'پەیوەندی بە پشتیوانی بکە', 'common'),
('kurdish_kurmanci', 'help.contact_support', 'Bi piştgiriyê re têkilî dayne', 'common'),
('german', 'help.contact_support', 'Support kontaktieren', 'common')
ON CONFLICT DO NOTHING;

-- ===== VERIFICATION FORM =====
INSERT INTO app_translations (language_code, translation_key, translation_value, category) VALUES
('english', 'verification.title', 'Verify Your Identity', 'auth'),
('norwegian', 'verification.title', 'Bekreft identiteten din', 'auth'),
('kurdish_sorani', 'verification.title', 'ناسنامەکەت پشتڕاست بکەرەوە', 'auth'),
('kurdish_kurmanci', 'verification.title', 'Nasnameya xwe piştrast bike', 'auth'),
('german', 'verification.title', 'Verifizieren Sie Ihre Identität', 'auth'),
('english', 'verification.desc', 'Get verified to increase trust and match quality. Choose one of the verification methods below.', 'auth'),
('norwegian', 'verification.desc', 'Bli verifisert for å øke tillit og matchkvalitet. Velg en av verifiseringsmetodene nedenfor.', 'auth'),
('kurdish_sorani', 'verification.desc', 'پشتڕاست بکرێ بۆ زیادکردنی متمانە و کوالیتی ماچ.', 'auth'),
('kurdish_kurmanci', 'verification.desc', 'Hatî piştrast kirin da ku pêbawerî û kalîteya maçê zêde bike.', 'auth'),
('german', 'verification.desc', 'Lassen Sie sich verifizieren, um Vertrauen und Match-Qualität zu erhöhen.', 'auth'),
('english', 'verification.selfie', 'Selfie Verification', 'auth'),
('norwegian', 'verification.selfie', 'Selfie-verifisering', 'auth'),
('kurdish_sorani', 'verification.selfie', 'پشتڕاستکردنەوەی سێلفی', 'auth'),
('kurdish_kurmanci', 'verification.selfie', 'Piştrastkirina Selfiyê', 'auth'),
('german', 'verification.selfie', 'Selfie-Verifizierung', 'auth'),
('english', 'verification.take_photo', 'Take a photo of yourself', 'auth'),
('norwegian', 'verification.take_photo', 'Ta et bilde av deg selv', 'auth'),
('kurdish_sorani', 'verification.take_photo', 'وێنەیەکی خۆت بگرە', 'auth'),
('kurdish_kurmanci', 'verification.take_photo', 'Wêneyek ji xwe bigire', 'auth'),
('german', 'verification.take_photo', 'Machen Sie ein Foto von sich', 'auth'),
('english', 'verification.id_document', 'ID Document', 'auth'),
('norwegian', 'verification.id_document', 'ID-dokument', 'auth'),
('kurdish_sorani', 'verification.id_document', 'بەڵگەی ناسنامە', 'auth'),
('kurdish_kurmanci', 'verification.id_document', 'Belgeya Nasnameyê', 'auth'),
('german', 'verification.id_document', 'Ausweisdokument', 'auth'),
('english', 'verification.upload_id', 'Upload government ID', 'auth'),
('norwegian', 'verification.upload_id', 'Last opp offentlig ID', 'auth'),
('kurdish_sorani', 'verification.upload_id', 'ناسنامەی حکومی بباره‌وه‌', 'auth'),
('kurdish_kurmanci', 'verification.upload_id', 'Nasnameya hikûmetê bar bike', 'auth'),
('german', 'verification.upload_id', 'Amtlichen Ausweis hochladen', 'auth'),
('english', 'verification.retake', 'Retake', 'auth'),
('norwegian', 'verification.retake', 'Ta på nytt', 'auth'),
('kurdish_sorani', 'verification.retake', 'دووبارە بیگرەوە', 'auth'),
('kurdish_kurmanci', 'verification.retake', 'Ji nû ve bigire', 'auth'),
('german', 'verification.retake', 'Erneut aufnehmen', 'auth'),
('english', 'verification.guidelines', 'Guidelines:', 'auth'),
('norwegian', 'verification.guidelines', 'Retningslinjer:', 'auth'),
('kurdish_sorani', 'verification.guidelines', 'ڕێنماییەکان:', 'auth'),
('kurdish_kurmanci', 'verification.guidelines', 'Rêwerz:', 'auth'),
('german', 'verification.guidelines', 'Richtlinien:', 'auth'),
('english', 'verification.submitting', 'Submitting...', 'auth'),
('norwegian', 'verification.submitting', 'Sender inn...', 'auth'),
('kurdish_sorani', 'verification.submitting', 'ناردن...', 'auth'),
('kurdish_kurmanci', 'verification.submitting', 'Dişîne...', 'auth'),
('german', 'verification.submitting', 'Wird eingereicht...', 'auth'),
('english', 'verification.submit', 'Submit Verification', 'auth'),
('norwegian', 'verification.submit', 'Send verifisering', 'auth'),
('kurdish_sorani', 'verification.submit', 'پشتڕاستکردنەوە بنێرە', 'auth'),
('kurdish_kurmanci', 'verification.submit', 'Piştrastkirinê bişîne', 'auth'),
('german', 'verification.submit', 'Verifizierung einreichen', 'auth'),
('english', 'verification.submitted_title', 'Verification Submitted', 'auth'),
('norwegian', 'verification.submitted_title', 'Verifisering sendt', 'auth'),
('kurdish_sorani', 'verification.submitted_title', 'پشتڕاستکردنەوە نێردرا', 'auth'),
('kurdish_kurmanci', 'verification.submitted_title', 'Piştrastkirin hat şandin', 'auth'),
('german', 'verification.submitted_title', 'Verifizierung eingereicht', 'auth'),
('english', 'verification.submitted_desc', 'Your verification request has been submitted. We''ll review it within 24-48 hours and notify you of the result.', 'auth'),
('norwegian', 'verification.submitted_desc', 'Verifiseringsforespørselen din er sendt. Vi vil gjennomgå den innen 24-48 timer og varsle deg om resultatet.', 'auth'),
('kurdish_sorani', 'verification.submitted_desc', 'داواکاری پشتڕاستکردنەوەکەت نێردرا. لە ماوەی ٢٤-٤٨ کاتژمێردا پێداچوونەوەی دەکەین.', 'auth'),
('kurdish_kurmanci', 'verification.submitted_desc', 'Daxwaza piştrastkirina te hat şandin. Di nav 24-48 demjimêran de em ê lê binêrin.', 'auth'),
('german', 'verification.submitted_desc', 'Ihre Verifizierungsanfrage wurde eingereicht. Wir werden sie innerhalb von 24-48 Stunden überprüfen.', 'auth'),
('english', 'verification.error_no_image', 'Please capture or upload an image first', 'auth'),
('norwegian', 'verification.error_no_image', 'Vennligst ta eller last opp et bilde først', 'auth'),
('kurdish_sorani', 'verification.error_no_image', 'تکایە سەرەتا وێنەیەک بگرە یان باربکە', 'auth'),
('kurdish_kurmanci', 'verification.error_no_image', 'Ji kerema xwe pêşî wêneyek bigire an bar bike', 'auth'),
('german', 'verification.error_no_image', 'Bitte nehmen Sie zuerst ein Bild auf oder laden Sie eines hoch', 'auth'),
('english', 'verification.success_msg', 'Verification request submitted successfully. We will review it shortly.', 'auth'),
('norwegian', 'verification.success_msg', 'Verifiseringsforespørsel sendt. Vi vil gjennomgå den snart.', 'auth'),
('kurdish_sorani', 'verification.success_msg', 'داواکاری پشتڕاستکردنەوە بە سەرکەوتوویی نێردرا.', 'auth'),
('kurdish_kurmanci', 'verification.success_msg', 'Daxwaza piştrastkirinê bi serkeftî hat şandin.', 'auth'),
('german', 'verification.success_msg', 'Verifizierungsanfrage erfolgreich eingereicht.', 'auth'),
('english', 'verification.error_submit', 'Failed to submit verification request', 'auth'),
('norwegian', 'verification.error_submit', 'Kunne ikke sende verifiseringsforespørsel', 'auth'),
('kurdish_sorani', 'verification.error_submit', 'ناردنی داواکاری پشتڕاستکردنەوە سەرکەوتوو نەبوو', 'auth'),
('kurdish_kurmanci', 'verification.error_submit', 'Şandina daxwaza piştrastkirinê bi ser neket', 'auth'),
('german', 'verification.error_submit', 'Verifizierungsanfrage konnte nicht eingereicht werden', 'auth'),
('english', 'verification.take_selfie', 'Take Selfie', 'auth'),
('norwegian', 'verification.take_selfie', 'Ta selfie', 'auth'),
('kurdish_sorani', 'verification.take_selfie', 'سێلفی بگرە', 'auth'),
('kurdish_kurmanci', 'verification.take_selfie', 'Selfî bigire', 'auth'),
('german', 'verification.take_selfie', 'Selfie aufnehmen', 'auth'),
('english', 'verification.upload_id_btn', 'Upload ID', 'auth'),
('norwegian', 'verification.upload_id_btn', 'Last opp ID', 'auth'),
('kurdish_sorani', 'verification.upload_id_btn', 'ناسنامە باربکە', 'auth'),
('kurdish_kurmanci', 'verification.upload_id_btn', 'Nasname bar bike', 'auth'),
('german', 'verification.upload_id_btn', 'Ausweis hochladen', 'auth'),
('english', 'verification.selfie_prompt', 'Take a clear selfie showing your face', 'auth'),
('norwegian', 'verification.selfie_prompt', 'Ta en tydelig selfie som viser ansiktet ditt', 'auth'),
('kurdish_sorani', 'verification.selfie_prompt', 'سێلفیێکی ڕوون بگرە کە ڕووخسارت پیشان بدات', 'auth'),
('kurdish_kurmanci', 'verification.selfie_prompt', 'Selfîyek zelal bigire ku rûyê te nîşan bide', 'auth'),
('german', 'verification.selfie_prompt', 'Nehmen Sie ein klares Selfie auf, das Ihr Gesicht zeigt', 'auth'),
('english', 'verification.id_prompt', 'Upload a photo of your government ID', 'auth'),
('norwegian', 'verification.id_prompt', 'Last opp et bilde av din offentlige ID', 'auth'),
('kurdish_sorani', 'verification.id_prompt', 'وێنەیەکی ناسنامەی حکومیت باربکە', 'auth'),
('kurdish_kurmanci', 'verification.id_prompt', 'Wêneyek ji nasnameya hikûmetê bar bike', 'auth'),
('german', 'verification.id_prompt', 'Laden Sie ein Foto Ihres Ausweises hoch', 'auth')
ON CONFLICT DO NOTHING;
