
INSERT INTO public.app_translations (language_code, translation_key, translation_value, category, context) VALUES
-- English
('english','reg.step_account','Account','auth','RegistrationForm step title'),
('english','reg.step_personal','Personal','auth','RegistrationForm step title'),
('english','reg.step_profile','Profile','auth','RegistrationForm step title'),
('english','reg.email','Email','auth','RegistrationForm label'),
('english','reg.password','Password','auth','RegistrationForm label'),
('english','reg.create_password','Create a strong password','auth','RegistrationForm placeholder'),
('english','reg.password_requirements','Password must be at least 8 characters with 1 uppercase, 1 lowercase, and 1 number','auth','RegistrationForm description'),
('english','reg.confirm_password','Confirm Password','auth','RegistrationForm label'),
('english','reg.confirm_password_placeholder','Confirm your password','auth','RegistrationForm placeholder'),
('english','reg.first_name','First Name','auth','RegistrationForm label'),
('english','reg.last_name','Last Name','auth','RegistrationForm label'),
('english','reg.date_of_birth','Date of Birth','auth','RegistrationForm label'),
('english','reg.age_requirement','You must be at least 18 years old to register','auth','RegistrationForm description'),
('english','reg.location','Location','auth','RegistrationForm label'),
('english','reg.location_placeholder','City, Country','auth','RegistrationForm placeholder'),
('english','reg.occupation','Occupation','auth','RegistrationForm label'),
('english','reg.occupation_placeholder','Software Engineer, Doctor, Artist, etc.','auth','RegistrationForm placeholder'),
('english','reg.about_me','About Me','auth','RegistrationForm label'),
('english','reg.about_me_placeholder','Tell us a bit about yourself...','auth','RegistrationForm placeholder'),
('english','reg.agree_terms','I agree to the Terms of Service and Privacy Policy','auth','RegistrationForm terms'),
('english','reg.creating_account','Creating Account...','auth','RegistrationForm button'),
('english','reg.create_account','Create Account','auth','RegistrationForm button'),
('english','reg.account_created','Your account has been created successfully.','auth','RegistrationForm toast'),
('english','reg.create_failed','Failed to create account. Please try again.','auth','RegistrationForm toast'),

-- Norwegian
('norwegian','reg.step_account','Konto','auth','RegistrationForm step title'),
('norwegian','reg.step_personal','Personlig','auth','RegistrationForm step title'),
('norwegian','reg.step_profile','Profil','auth','RegistrationForm step title'),
('norwegian','reg.email','E-post','auth','RegistrationForm label'),
('norwegian','reg.password','Passord','auth','RegistrationForm label'),
('norwegian','reg.create_password','Lag et sterkt passord','auth','RegistrationForm placeholder'),
('norwegian','reg.password_requirements','Passord må være minst 8 tegn med 1 stor bokstav, 1 liten bokstav og 1 tall','auth','RegistrationForm description'),
('norwegian','reg.confirm_password','Bekreft passord','auth','RegistrationForm label'),
('norwegian','reg.confirm_password_placeholder','Bekreft passordet ditt','auth','RegistrationForm placeholder'),
('norwegian','reg.first_name','Fornavn','auth','RegistrationForm label'),
('norwegian','reg.last_name','Etternavn','auth','RegistrationForm label'),
('norwegian','reg.date_of_birth','Fødselsdato','auth','RegistrationForm label'),
('norwegian','reg.age_requirement','Du må være minst 18 år gammel for å registrere deg','auth','RegistrationForm description'),
('norwegian','reg.location','Plassering','auth','RegistrationForm label'),
('norwegian','reg.location_placeholder','By, Land','auth','RegistrationForm placeholder'),
('norwegian','reg.occupation','Yrke','auth','RegistrationForm label'),
('norwegian','reg.occupation_placeholder','Programvareutvikler, Lege, Kunstner, osv.','auth','RegistrationForm placeholder'),
('norwegian','reg.about_me','Om meg','auth','RegistrationForm label'),
('norwegian','reg.about_me_placeholder','Fortell oss litt om deg selv...','auth','RegistrationForm placeholder'),
('norwegian','reg.agree_terms','Jeg godtar vilkårene og personvernerklæringen','auth','RegistrationForm terms'),
('norwegian','reg.creating_account','Oppretter konto...','auth','RegistrationForm button'),
('norwegian','reg.create_account','Opprett konto','auth','RegistrationForm button'),
('norwegian','reg.account_created','Kontoen din har blitt opprettet.','auth','RegistrationForm toast'),
('norwegian','reg.create_failed','Kunne ikke opprette konto. Prøv igjen.','auth','RegistrationForm toast'),

-- German
('german','reg.step_account','Konto','auth','RegistrationForm step title'),
('german','reg.step_personal','Persönlich','auth','RegistrationForm step title'),
('german','reg.step_profile','Profil','auth','RegistrationForm step title'),
('german','reg.email','E-Mail','auth','RegistrationForm label'),
('german','reg.password','Passwort','auth','RegistrationForm label'),
('german','reg.create_password','Erstellen Sie ein sicheres Passwort','auth','RegistrationForm placeholder'),
('german','reg.password_requirements','Das Passwort muss mindestens 8 Zeichen mit 1 Großbuchstaben, 1 Kleinbuchstaben und 1 Zahl enthalten','auth','RegistrationForm description'),
('german','reg.confirm_password','Passwort bestätigen','auth','RegistrationForm label'),
('german','reg.confirm_password_placeholder','Bestätigen Sie Ihr Passwort','auth','RegistrationForm placeholder'),
('german','reg.first_name','Vorname','auth','RegistrationForm label'),
('german','reg.last_name','Nachname','auth','RegistrationForm label'),
('german','reg.date_of_birth','Geburtsdatum','auth','RegistrationForm label'),
('german','reg.age_requirement','Sie müssen mindestens 18 Jahre alt sein, um sich zu registrieren','auth','RegistrationForm description'),
('german','reg.location','Standort','auth','RegistrationForm label'),
('german','reg.location_placeholder','Stadt, Land','auth','RegistrationForm placeholder'),
('german','reg.occupation','Beruf','auth','RegistrationForm label'),
('german','reg.occupation_placeholder','Softwareentwickler, Arzt, Künstler, usw.','auth','RegistrationForm placeholder'),
('german','reg.about_me','Über mich','auth','RegistrationForm label'),
('german','reg.about_me_placeholder','Erzählen Sie uns etwas über sich...','auth','RegistrationForm placeholder'),
('german','reg.agree_terms','Ich stimme den Nutzungsbedingungen und der Datenschutzerklärung zu','auth','RegistrationForm terms'),
('german','reg.creating_account','Konto wird erstellt...','auth','RegistrationForm button'),
('german','reg.create_account','Konto erstellen','auth','RegistrationForm button'),
('german','reg.account_created','Ihr Konto wurde erfolgreich erstellt.','auth','RegistrationForm toast'),
('german','reg.create_failed','Konto konnte nicht erstellt werden. Bitte versuchen Sie es erneut.','auth','RegistrationForm toast'),

-- Kurdish Sorani
('kurdish_sorani','reg.step_account','هەژمار','auth','RegistrationForm step title'),
('kurdish_sorani','reg.step_personal','کەسی','auth','RegistrationForm step title'),
('kurdish_sorani','reg.step_profile','پرۆفایل','auth','RegistrationForm step title'),
('kurdish_sorani','reg.email','ئیمەیل','auth','RegistrationForm label'),
('kurdish_sorani','reg.password','وشەی نهێنی','auth','RegistrationForm label'),
('kurdish_sorani','reg.create_password','وشەیەکی نهێنی بەهێز دروست بکە','auth','RegistrationForm placeholder'),
('kurdish_sorani','reg.password_requirements','وشەی نهێنی دەبێت لانیکەم ٨ پیت بێت لەگەڵ ١ پیتی گەورە، ١ پیتی بچووک و ١ ژمارە','auth','RegistrationForm description'),
('kurdish_sorani','reg.confirm_password','دووپاتکردنەوەی وشەی نهێنی','auth','RegistrationForm label'),
('kurdish_sorani','reg.confirm_password_placeholder','وشەی نهێنیەکەت دووپات بکەرەوە','auth','RegistrationForm placeholder'),
('kurdish_sorani','reg.first_name','ناوی یەکەم','auth','RegistrationForm label'),
('kurdish_sorani','reg.last_name','ناوی خێزانی','auth','RegistrationForm label'),
('kurdish_sorani','reg.date_of_birth','بەرواری لەدایکبوون','auth','RegistrationForm label'),
('kurdish_sorani','reg.age_requirement','دەبێت لانیکەم ١٨ ساڵ تەمەنت بێت بۆ تۆمارکردن','auth','RegistrationForm description'),
('kurdish_sorani','reg.location','شوێن','auth','RegistrationForm label'),
('kurdish_sorani','reg.location_placeholder','شار، وڵات','auth','RegistrationForm placeholder'),
('kurdish_sorani','reg.occupation','پیشە','auth','RegistrationForm label'),
('kurdish_sorani','reg.occupation_placeholder','ئەندازیاری نەرمەکاڵا، پزیشک، هونەرمەند، هتد.','auth','RegistrationForm placeholder'),
('kurdish_sorani','reg.about_me','دەربارەی من','auth','RegistrationForm label'),
('kurdish_sorani','reg.about_me_placeholder','کەمێک لەبارەی خۆت بڵێ...','auth','RegistrationForm placeholder'),
('kurdish_sorani','reg.agree_terms','من ڕازیم بە مەرجەکانی خزمەتگوزاری و سیاسەتی تایبەتمەندی','auth','RegistrationForm terms'),
('kurdish_sorani','reg.creating_account','هەژمار دروست دەکرێت...','auth','RegistrationForm button'),
('kurdish_sorani','reg.create_account','دروستکردنی هەژمار','auth','RegistrationForm button'),
('kurdish_sorani','reg.account_created','هەژمارەکەت بە سەرکەوتوویی دروست کرا.','auth','RegistrationForm toast'),
('kurdish_sorani','reg.create_failed','نەتوانرا هەژمار دروست بکرێت. تکایە دووبارە هەوڵ بدەرەوە.','auth','RegistrationForm toast'),

-- Kurdish Kurmanji
('kurdish_kurmanji','reg.step_account','Hesab','auth','RegistrationForm step title'),
('kurdish_kurmanji','reg.step_personal','Kesane','auth','RegistrationForm step title'),
('kurdish_kurmanji','reg.step_profile','Profîl','auth','RegistrationForm step title'),
('kurdish_kurmanji','reg.email','E-name','auth','RegistrationForm label'),
('kurdish_kurmanji','reg.password','Pêborîn','auth','RegistrationForm label'),
('kurdish_kurmanji','reg.create_password','Pêborînek bihêz çêke','auth','RegistrationForm placeholder'),
('kurdish_kurmanji','reg.password_requirements','Pêborîn divê herî kêm 8 tîp be digel 1 tîpê mezin, 1 tîpê biçûk û 1 hejmar','auth','RegistrationForm description'),
('kurdish_kurmanji','reg.confirm_password','Pêborînê piştrast bike','auth','RegistrationForm label'),
('kurdish_kurmanji','reg.confirm_password_placeholder','Pêborîna xwe piştrast bike','auth','RegistrationForm placeholder'),
('kurdish_kurmanji','reg.first_name','Navê pêşîn','auth','RegistrationForm label'),
('kurdish_kurmanji','reg.last_name','Paşnav','auth','RegistrationForm label'),
('kurdish_kurmanji','reg.date_of_birth','Dîroka jidayikbûnê','auth','RegistrationForm label'),
('kurdish_kurmanji','reg.age_requirement','Divê herî kêm 18 salî be ji bo qeydkirinê','auth','RegistrationForm description'),
('kurdish_kurmanji','reg.location','Cih','auth','RegistrationForm label'),
('kurdish_kurmanji','reg.location_placeholder','Bajar, Welat','auth','RegistrationForm placeholder'),
('kurdish_kurmanji','reg.occupation','Pîşe','auth','RegistrationForm label'),
('kurdish_kurmanji','reg.occupation_placeholder','Endezyarê nermalayê, Bijîşk, Hunermend, hwd.','auth','RegistrationForm placeholder'),
('kurdish_kurmanji','reg.about_me','Der barê min de','auth','RegistrationForm label'),
('kurdish_kurmanji','reg.about_me_placeholder','Hinekî li ser xwe ji me re bibêje...','auth','RegistrationForm placeholder'),
('kurdish_kurmanji','reg.agree_terms','Ez bi şert û mercên xizmetê û polîtîkaya nepenîtiyê razî me','auth','RegistrationForm terms'),
('kurdish_kurmanji','reg.creating_account','Hesab tê çêkirin...','auth','RegistrationForm button'),
('kurdish_kurmanji','reg.create_account','Hesab çêke','auth','RegistrationForm button'),
('kurdish_kurmanji','reg.account_created','Hesabê te bi serkeftî hat çêkirin.','auth','RegistrationForm toast'),
('kurdish_kurmanji','reg.create_failed','Nehat çêkirin hesab. Ji kerema xwe dîsa biceribîne.','auth','RegistrationForm toast')

ON CONFLICT DO NOTHING;
