
-- Batch 17: Remaining hardcoded strings across SuperAdmin
INSERT INTO public.app_translations (language_code, translation_key, translation_value, category) VALUES
-- StatsOverview (uses default stat names)
-- AnalyticsPage
('english', 'admin.detailed_growth_analysis', 'Detailed User Growth Analysis', 'admin'),
('english', 'admin.track_user_acquisition', 'Track user acquisition trends', 'admin'),
('english', 'admin.detailed_growth_placeholder', 'Detailed growth analytics will appear here.', 'admin'),
('english', 'admin.platform_activity_metrics', 'Platform Activity Metrics', 'admin'),
('english', 'admin.monitor_engagement', 'Monitor user engagement and activity', 'admin'),
('english', 'admin.activity_placeholder', 'Activity metrics will appear here.', 'admin'),
-- PhotosPage
('english', 'admin.photo_deleted_success', 'Photo deleted successfully', 'admin'),
('english', 'admin.photo_delete_failed', 'Failed to delete photo', 'admin'),
-- DashboardNew
('english', 'admin.revenue_label', 'Revenue', 'admin'),
-- LikesPage
('english', 'admin.failed_load_likes', 'Failed to load likes', 'admin'),
('english', 'admin.delete_like_confirm', 'Are you sure you want to delete this like?', 'admin'),
('english', 'admin.like_deleted', 'Like deleted successfully', 'admin'),
('english', 'admin.like_delete_failed', 'Failed to delete like', 'admin'),
-- MatchesPage
('english', 'admin.failed_load_matches', 'Failed to load matches', 'admin'),
('english', 'admin.delete_match_confirm', 'Are you sure you want to delete this match?', 'admin'),
('english', 'admin.match_deleted', 'Match deleted successfully', 'admin'),
('english', 'admin.match_delete_failed', 'Failed to delete match', 'admin'),
-- SupportTicketsPage
('english', 'admin.failed_fetch_tickets', 'Failed to fetch support tickets', 'admin'),
('english', 'admin.ticket_resolved_msg', 'Your support ticket has been resolved.', 'admin'),
('english', 'admin.ticket_closed_msg', 'Your support ticket has been closed.', 'admin'),
('english', 'admin.ticket_pending_msg', 'Your support ticket is being reviewed.', 'admin'),
('english', 'admin.ticket_status_title', 'Ticket {{status}}', 'admin'),
('english', 'admin.ticket_status_updated_msg', 'Your ticket status has been updated to {{status}}.', 'admin'),
('english', 'admin.ticket_status_updated', 'Ticket status updated to {{status}}', 'admin'),
('english', 'admin.failed_update_ticket', 'Failed to update ticket status', 'admin'),
('english', 'admin.support_team_responded', 'Support Team Responded', 'admin'),
('english', 'admin.ticket_response_msg', 'Your support ticket "{{subject}}" has received a response.', 'admin'),
('english', 'admin.response_sent', 'Response sent and user notified', 'admin'),
('english', 'admin.failed_send_response', 'Failed to send response', 'admin'),
-- SubscribersPage
('english', 'admin.basic', 'Basic', 'admin'),
('english', 'admin.premium', 'Premium', 'admin'),
('english', 'admin.ultimate', 'Ultimate', 'admin'),
-- GhostUsersPage
('english', 'admin.published_items', 'Published {{count}} scheduled items.', 'admin'),
('english', 'admin.scheduled_items', 'Scheduled {{count}} new content items.', 'admin'),

-- Norwegian
('norwegian', 'admin.detailed_growth_analysis', 'Detaljert brukervekstanalyse', 'admin'),
('norwegian', 'admin.track_user_acquisition', 'Spor trender for brukeranskaffelse', 'admin'),
('norwegian', 'admin.detailed_growth_placeholder', 'Detaljert vekstanalyse vil vises her.', 'admin'),
('norwegian', 'admin.platform_activity_metrics', 'Plattformaktivitetsmålinger', 'admin'),
('norwegian', 'admin.monitor_engagement', 'Overvåk brukerengasjement og aktivitet', 'admin'),
('norwegian', 'admin.activity_placeholder', 'Aktivitetsmålinger vil vises her.', 'admin'),
('norwegian', 'admin.photo_deleted_success', 'Bildet ble slettet', 'admin'),
('norwegian', 'admin.photo_delete_failed', 'Kunne ikke slette bildet', 'admin'),
('norwegian', 'admin.revenue_label', 'Inntekt', 'admin'),
('norwegian', 'admin.failed_load_likes', 'Kunne ikke laste likerklikk', 'admin'),
('norwegian', 'admin.delete_like_confirm', 'Er du sikker på at du vil slette dette likerklikket?', 'admin'),
('norwegian', 'admin.like_deleted', 'Likerklikk slettet', 'admin'),
('norwegian', 'admin.like_delete_failed', 'Kunne ikke slette likerklikk', 'admin'),
('norwegian', 'admin.failed_load_matches', 'Kunne ikke laste treff', 'admin'),
('norwegian', 'admin.delete_match_confirm', 'Er du sikker på at du vil slette dette treffet?', 'admin'),
('norwegian', 'admin.match_deleted', 'Treff slettet', 'admin'),
('norwegian', 'admin.match_delete_failed', 'Kunne ikke slette treff', 'admin'),
('norwegian', 'admin.failed_fetch_tickets', 'Kunne ikke hente støttesaker', 'admin'),
('norwegian', 'admin.ticket_resolved_msg', 'Støttesaken din er løst.', 'admin'),
('norwegian', 'admin.ticket_closed_msg', 'Støttesaken din er lukket.', 'admin'),
('norwegian', 'admin.ticket_pending_msg', 'Støttesaken din blir gjennomgått.', 'admin'),
('norwegian', 'admin.ticket_status_title', 'Sak {{status}}', 'admin'),
('norwegian', 'admin.ticket_status_updated_msg', 'Sakstatusen din er oppdatert til {{status}}.', 'admin'),
('norwegian', 'admin.ticket_status_updated', 'Sakstatus oppdatert til {{status}}', 'admin'),
('norwegian', 'admin.failed_update_ticket', 'Kunne ikke oppdatere sakstatus', 'admin'),
('norwegian', 'admin.support_team_responded', 'Støtteteamet har svart', 'admin'),
('norwegian', 'admin.ticket_response_msg', 'Støttesaken "{{subject}}" har fått et svar.', 'admin'),
('norwegian', 'admin.response_sent', 'Svar sendt og bruker varslet', 'admin'),
('norwegian', 'admin.failed_send_response', 'Kunne ikke sende svar', 'admin'),
('norwegian', 'admin.basic', 'Basis', 'admin'),
('norwegian', 'admin.premium', 'Premium', 'admin'),
('norwegian', 'admin.ultimate', 'Ultimate', 'admin'),
('norwegian', 'admin.published_items', 'Publiserte {{count}} planlagte elementer.', 'admin'),
('norwegian', 'admin.scheduled_items', 'Planla {{count}} nye innholdselementer.', 'admin'),

-- German
('german', 'admin.detailed_growth_analysis', 'Detaillierte Benutzerwachstumsanalyse', 'admin'),
('german', 'admin.track_user_acquisition', 'Benutzerakquisitionstrends verfolgen', 'admin'),
('german', 'admin.detailed_growth_placeholder', 'Detaillierte Wachstumsanalysen werden hier angezeigt.', 'admin'),
('german', 'admin.platform_activity_metrics', 'Plattform-Aktivitätsmetriken', 'admin'),
('german', 'admin.monitor_engagement', 'Benutzerengagement und Aktivität überwachen', 'admin'),
('german', 'admin.activity_placeholder', 'Aktivitätsmetriken werden hier angezeigt.', 'admin'),
('german', 'admin.photo_deleted_success', 'Foto erfolgreich gelöscht', 'admin'),
('german', 'admin.photo_delete_failed', 'Foto konnte nicht gelöscht werden', 'admin'),
('german', 'admin.revenue_label', 'Umsatz', 'admin'),
('german', 'admin.failed_load_likes', 'Likes konnten nicht geladen werden', 'admin'),
('german', 'admin.delete_like_confirm', 'Sind Sie sicher, dass Sie dieses Like löschen möchten?', 'admin'),
('german', 'admin.like_deleted', 'Like erfolgreich gelöscht', 'admin'),
('german', 'admin.like_delete_failed', 'Like konnte nicht gelöscht werden', 'admin'),
('german', 'admin.failed_load_matches', 'Matches konnten nicht geladen werden', 'admin'),
('german', 'admin.delete_match_confirm', 'Sind Sie sicher, dass Sie dieses Match löschen möchten?', 'admin'),
('german', 'admin.match_deleted', 'Match erfolgreich gelöscht', 'admin'),
('german', 'admin.match_delete_failed', 'Match konnte nicht gelöscht werden', 'admin'),
('german', 'admin.failed_fetch_tickets', 'Support-Tickets konnten nicht abgerufen werden', 'admin'),
('german', 'admin.ticket_resolved_msg', 'Ihr Support-Ticket wurde gelöst.', 'admin'),
('german', 'admin.ticket_closed_msg', 'Ihr Support-Ticket wurde geschlossen.', 'admin'),
('german', 'admin.ticket_pending_msg', 'Ihr Support-Ticket wird überprüft.', 'admin'),
('german', 'admin.ticket_status_title', 'Ticket {{status}}', 'admin'),
('german', 'admin.ticket_status_updated_msg', 'Ihr Ticketstatus wurde auf {{status}} aktualisiert.', 'admin'),
('german', 'admin.ticket_status_updated', 'Ticketstatus auf {{status}} aktualisiert', 'admin'),
('german', 'admin.failed_update_ticket', 'Ticketstatus konnte nicht aktualisiert werden', 'admin'),
('german', 'admin.support_team_responded', 'Support-Team hat geantwortet', 'admin'),
('german', 'admin.ticket_response_msg', 'Ihr Support-Ticket "{{subject}}" hat eine Antwort erhalten.', 'admin'),
('german', 'admin.response_sent', 'Antwort gesendet und Benutzer benachrichtigt', 'admin'),
('german', 'admin.failed_send_response', 'Antwort konnte nicht gesendet werden', 'admin'),
('german', 'admin.basic', 'Basis', 'admin'),
('german', 'admin.premium', 'Premium', 'admin'),
('german', 'admin.ultimate', 'Ultimate', 'admin'),
('german', 'admin.published_items', '{{count}} geplante Elemente veröffentlicht.', 'admin'),
('german', 'admin.scheduled_items', '{{count}} neue Inhaltselemente geplant.', 'admin'),

-- Kurdish Sorani
('kurdish_sorani', 'admin.detailed_growth_analysis', 'شیکردنەوەی وردی گەشەی بەکارهێنەر', 'admin'),
('kurdish_sorani', 'admin.track_user_acquisition', 'شوێنکەوتنی ڕووەوەکانی بەدەستهێنانی بەکارهێنەر', 'admin'),
('kurdish_sorani', 'admin.detailed_growth_placeholder', 'شیکردنەوەی وردی گەشە لێرە نیشان دەدرێت.', 'admin'),
('kurdish_sorani', 'admin.platform_activity_metrics', 'پێوانەکانی چالاکیی پلاتفۆرم', 'admin'),
('kurdish_sorani', 'admin.monitor_engagement', 'چاودێری بەشداریی بەکارهێنەر و چالاکی', 'admin'),
('kurdish_sorani', 'admin.activity_placeholder', 'پێوانەکانی چالاکی لێرە نیشان دەدرێن.', 'admin'),
('kurdish_sorani', 'admin.photo_deleted_success', 'وێنەکە بە سەرکەوتوویی سڕایەوە', 'admin'),
('kurdish_sorani', 'admin.photo_delete_failed', 'سڕینەوەی وێنەکە سەرنەکەوت', 'admin'),
('kurdish_sorani', 'admin.revenue_label', 'داهات', 'admin'),
('kurdish_sorani', 'admin.failed_load_likes', 'بارکردنی لایکەکان سەرنەکەوت', 'admin'),
('kurdish_sorani', 'admin.delete_like_confirm', 'دڵنیایت لە سڕینەوەی ئەم لایکە؟', 'admin'),
('kurdish_sorani', 'admin.like_deleted', 'لایکەکە سڕایەوە', 'admin'),
('kurdish_sorani', 'admin.like_delete_failed', 'سڕینەوەی لایکەکە سەرنەکەوت', 'admin'),
('kurdish_sorani', 'admin.failed_load_matches', 'بارکردنی لەیەکگونجانەکان سەرنەکەوت', 'admin'),
('kurdish_sorani', 'admin.delete_match_confirm', 'دڵنیایت لە سڕینەوەی ئەم لەیەکگونجانە؟', 'admin'),
('kurdish_sorani', 'admin.match_deleted', 'لەیەکگونجانەکە سڕایەوە', 'admin'),
('kurdish_sorani', 'admin.match_delete_failed', 'سڕینەوەی لەیەکگونجانەکە سەرنەکەوت', 'admin'),
('kurdish_sorani', 'admin.failed_fetch_tickets', 'هێنانی تیکەتەکانی پشتیوانی سەرنەکەوت', 'admin'),
('kurdish_sorani', 'admin.ticket_resolved_msg', 'تیکەتی پشتیوانیت چارەسەر کرا.', 'admin'),
('kurdish_sorani', 'admin.ticket_closed_msg', 'تیکەتی پشتیوانیت داخرا.', 'admin'),
('kurdish_sorani', 'admin.ticket_pending_msg', 'تیکەتی پشتیوانیت لەژێر پێداچوونەوەدایە.', 'admin'),
('kurdish_sorani', 'admin.ticket_status_title', 'تیکەت {{status}}', 'admin'),
('kurdish_sorani', 'admin.ticket_status_updated_msg', 'بارودۆخی تیکەتەکەت نوێ کرایەوە بۆ {{status}}.', 'admin'),
('kurdish_sorani', 'admin.ticket_status_updated', 'بارودۆخی تیکەت نوێ کرایەوە بۆ {{status}}', 'admin'),
('kurdish_sorani', 'admin.failed_update_ticket', 'نوێکردنەوەی بارودۆخی تیکەت سەرنەکەوت', 'admin'),
('kurdish_sorani', 'admin.support_team_responded', 'تیمی پشتیوانی وەڵامی دایەوە', 'admin'),
('kurdish_sorani', 'admin.ticket_response_msg', 'تیکەتی پشتیوانیت "{{subject}}" وەڵامی وەرگرت.', 'admin'),
('kurdish_sorani', 'admin.response_sent', 'وەڵام نێردرا و بەکارهێنەر ئاگادار کرایەوە', 'admin'),
('kurdish_sorani', 'admin.failed_send_response', 'ناردنی وەڵام سەرنەکەوت', 'admin'),
('kurdish_sorani', 'admin.basic', 'بنەڕەتی', 'admin'),
('kurdish_sorani', 'admin.premium', 'پریمیۆم', 'admin'),
('kurdish_sorani', 'admin.ultimate', 'ئەلتیمەیت', 'admin'),
('kurdish_sorani', 'admin.published_items', '{{count}} بابەتی پلانکراو بڵاوکرایەوە.', 'admin'),
('kurdish_sorani', 'admin.scheduled_items', '{{count}} بابەتی ناوەرۆکی نوێ پلانکرا.', 'admin'),

-- Kurdish Kurmanji
('kurdish_kurmanji', 'admin.detailed_growth_analysis', 'Analîza hûrgulî ya mezinbûna bikarhêner', 'admin'),
('kurdish_kurmanji', 'admin.track_user_acquisition', 'Şopandina meylên bidestxistina bikarhêner', 'admin'),
('kurdish_kurmanji', 'admin.detailed_growth_placeholder', 'Analîzên mezinbûnê yên hûrgulî dê li vir bên nîşandan.', 'admin'),
('kurdish_kurmanji', 'admin.platform_activity_metrics', 'Pîvanên çalakiya platformê', 'admin'),
('kurdish_kurmanji', 'admin.monitor_engagement', 'Çavdêriya tevlêbûn û çalakiya bikarhêner', 'admin'),
('kurdish_kurmanji', 'admin.activity_placeholder', 'Pîvanên çalakiyê dê li vir bên nîşandan.', 'admin'),
('kurdish_kurmanji', 'admin.photo_deleted_success', 'Wêne bi serkeftî hat jêbirin', 'admin'),
('kurdish_kurmanji', 'admin.photo_delete_failed', 'Jêbirina wêneyê bi ser neket', 'admin'),
('kurdish_kurmanji', 'admin.revenue_label', 'Dahat', 'admin'),
('kurdish_kurmanji', 'admin.failed_load_likes', 'Barkirin lîkeyan bi ser neket', 'admin'),
('kurdish_kurmanji', 'admin.delete_like_confirm', 'Ma hûn ji jêbirina vê lîkeyê piştrast in?', 'admin'),
('kurdish_kurmanji', 'admin.like_deleted', 'Lîke bi serkeftî hat jêbirin', 'admin'),
('kurdish_kurmanji', 'admin.like_delete_failed', 'Jêbirina lîkeyê bi ser neket', 'admin'),
('kurdish_kurmanji', 'admin.failed_load_matches', 'Barkirin lihevhatinan bi ser neket', 'admin'),
('kurdish_kurmanji', 'admin.delete_match_confirm', 'Ma hûn ji jêbirina vê lihevhatinê piştrast in?', 'admin'),
('kurdish_kurmanji', 'admin.match_deleted', 'Lihevhatin bi serkeftî hat jêbirin', 'admin'),
('kurdish_kurmanji', 'admin.match_delete_failed', 'Jêbirina lihevhatinê bi ser neket', 'admin'),
('kurdish_kurmanji', 'admin.failed_fetch_tickets', 'Anîna tîketên piştgiriyê bi ser neket', 'admin'),
('kurdish_kurmanji', 'admin.ticket_resolved_msg', 'Tîketa piştgiriya we hat çareserkirin.', 'admin'),
('kurdish_kurmanji', 'admin.ticket_closed_msg', 'Tîketa piştgiriya we hat girtin.', 'admin'),
('kurdish_kurmanji', 'admin.ticket_pending_msg', 'Tîketa piştgiriya we tê vekolîn.', 'admin'),
('kurdish_kurmanji', 'admin.ticket_status_title', 'Tîket {{status}}', 'admin'),
('kurdish_kurmanji', 'admin.ticket_status_updated_msg', 'Rewşa tîketa we hat nûkirin bo {{status}}.', 'admin'),
('kurdish_kurmanji', 'admin.ticket_status_updated', 'Rewşa tîketê hat nûkirin bo {{status}}', 'admin'),
('kurdish_kurmanji', 'admin.failed_update_ticket', 'Nûkirina rewşa tîketê bi ser neket', 'admin'),
('kurdish_kurmanji', 'admin.support_team_responded', 'Tîma piştgiriyê bersiv da', 'admin'),
('kurdish_kurmanji', 'admin.ticket_response_msg', 'Tîketa piştgiriya we "{{subject}}" bersivek wergirt.', 'admin'),
('kurdish_kurmanji', 'admin.response_sent', 'Bersiv hat şandin û bikarhêner hat agahdar kirin', 'admin'),
('kurdish_kurmanji', 'admin.failed_send_response', 'Şandina bersivê bi ser neket', 'admin'),
('kurdish_kurmanji', 'admin.basic', 'Bingehîn', 'admin'),
('kurdish_kurmanji', 'admin.premium', 'Premium', 'admin'),
('kurdish_kurmanji', 'admin.ultimate', 'Ultimate', 'admin'),
('kurdish_kurmanji', 'admin.published_items', '{{count}} babetên plankir hatin weşandin.', 'admin'),
('kurdish_kurmanji', 'admin.scheduled_items', '{{count}} babetên naverokê yên nû hatin plankirin.', 'admin')
ON CONFLICT DO NOTHING;
