
INSERT INTO public.app_translations (language_code, translation_key, translation_value, category, context)
VALUES
-- Location manager keys
('english','location.geolocation_not_supported','Geolocation not supported','location','toast'),
('english','location.browser_no_geolocation','Your browser doesn''t support geolocation services.','location','toast'),
('english','location.location_updated','Location updated','location','toast'),
('english','location.current_location_set','Your current location has been set.','location','toast'),
('english','location.location_error','Location error','location','toast'),
('english','location.could_not_determine','Could not determine your location. Please try again.','location','toast'),
('english','location.permission_denied','Location permission denied. Please enable location services in your browser settings.','location','toast'),
('english','location.position_unavailable','Location information is unavailable.','location','toast'),
('english','location.request_timeout','Location request timed out.','location','toast'),
('english','location.manually_set_to','Your location has been manually set to {{location}}','location','toast'),
('english','location.passport_location_set','Passport location set','location','toast'),
('english','location.passport_location_cleared','Passport location cleared','location','toast'),
('english','location.browsing_from','You''re now browsing from {{location}}','location','toast'),
('english','location.travel_mode_deactivated','Travel mode deactivated','location','toast'),
-- Registration step keys
('english','reg.step_email_password','Email & Password','registration','step title'),
('english','reg.step_email_desc','Create your secure account','registration','step desc'),
('english','reg.step_basic_info','Basic Info','registration','step title'),
('english','reg.step_basic_desc','Tell us about yourself','registration','step desc'),
('english','reg.step_location','Location & Travel','registration','step title'),
('english','reg.step_location_desc','Where are you from and where do you dream to go?','registration','step desc'),
('english','reg.step_photos','Photos','registration','step title'),
('english','reg.step_photos_desc','Add your best photos','registration','step desc'),

-- Norwegian
('norwegian','location.geolocation_not_supported','Geolokalisering støttes ikke','location','toast'),
('norwegian','location.browser_no_geolocation','Nettleseren din støtter ikke geolokaliseringstjenester.','location','toast'),
('norwegian','location.location_updated','Posisjon oppdatert','location','toast'),
('norwegian','location.current_location_set','Din nåværende posisjon er satt.','location','toast'),
('norwegian','location.location_error','Posisjonsfeil','location','toast'),
('norwegian','location.could_not_determine','Kunne ikke bestemme posisjonen din. Vennligst prøv igjen.','location','toast'),
('norwegian','location.permission_denied','Posisjonstillatelse avslått. Aktiver posisjonstjenester i nettleserinnstillingene.','location','toast'),
('norwegian','location.position_unavailable','Posisjonsinformasjon er utilgjengelig.','location','toast'),
('norwegian','location.request_timeout','Posisjonsforespørselen gikk ut på tid.','location','toast'),
('norwegian','location.manually_set_to','Posisjonen din er manuelt satt til {{location}}','location','toast'),
('norwegian','location.passport_location_set','Passposisjon satt','location','toast'),
('norwegian','location.passport_location_cleared','Passposisjon fjernet','location','toast'),
('norwegian','location.browsing_from','Du blar nå fra {{location}}','location','toast'),
('norwegian','location.travel_mode_deactivated','Reisemodus deaktivert','location','toast'),
('norwegian','reg.step_email_password','E-post og passord','registration','step title'),
('norwegian','reg.step_email_desc','Opprett din sikre konto','registration','step desc'),
('norwegian','reg.step_basic_info','Grunnleggende info','registration','step title'),
('norwegian','reg.step_basic_desc','Fortell oss om deg selv','registration','step desc'),
('norwegian','reg.step_location','Posisjon og reise','registration','step title'),
('norwegian','reg.step_location_desc','Hvor er du fra og hvor drømmer du om å reise?','registration','step desc'),
('norwegian','reg.step_photos','Bilder','registration','step title'),
('norwegian','reg.step_photos_desc','Legg til dine beste bilder','registration','step desc'),

-- Kurdish Sorani
('kurdish_sorani','location.geolocation_not_supported','شوێنی جوگرافی پشتگیری ناکرێت','location','toast'),
('kurdish_sorani','location.browser_no_geolocation','وێبگەڕەکەت خزمەتگوزاریی شوێنی جوگرافی پشتگیری ناکات.','location','toast'),
('kurdish_sorani','location.location_updated','شوێن نوێکرایەوە','location','toast'),
('kurdish_sorani','location.current_location_set','شوێنی ئێستات دانراوە.','location','toast'),
('kurdish_sorani','location.location_error','هەڵەی شوێن','location','toast'),
('kurdish_sorani','location.could_not_determine','نەتوانرا شوێنت دیاری بکرێت. تکایە دووبارە هەوڵ بدەوە.','location','toast'),
('kurdish_sorani','location.permission_denied','ڕێگەپێدانی شوێن ڕەتکرایەوە. تکایە خزمەتگوزاریی شوێن لە ڕێکخستنەکانی وێبگەڕ چالاک بکە.','location','toast'),
('kurdish_sorani','location.position_unavailable','زانیاری شوێن بەردەست نییە.','location','toast'),
('kurdish_sorani','location.request_timeout','داواکاری شوێن کاتی تێپەڕی.','location','toast'),
('kurdish_sorani','location.manually_set_to','شوێنەکەت بە دەستی دانراوە بۆ {{location}}','location','toast'),
('kurdish_sorani','location.passport_location_set','شوێنی پاسپۆرت دانرا','location','toast'),
('kurdish_sorani','location.passport_location_cleared','شوێنی پاسپۆرت پاککرایەوە','location','toast'),
('kurdish_sorani','location.browsing_from','ئێستا لە {{location}} بگەڕێ','location','toast'),
('kurdish_sorani','location.travel_mode_deactivated','دۆخی گەشتوگوزار ناچالاککرا','location','toast'),
('kurdish_sorani','reg.step_email_password','ئیمەیل و وشەی نهێنی','registration','step title'),
('kurdish_sorani','reg.step_email_desc','هەژمارە پارێزراوەکەت دروست بکە','registration','step desc'),
('kurdish_sorani','reg.step_basic_info','زانیاری سەرەتایی','registration','step title'),
('kurdish_sorani','reg.step_basic_desc','باسی خۆت بکە','registration','step desc'),
('kurdish_sorani','reg.step_location','شوێن و گەشت','registration','step title'),
('kurdish_sorani','reg.step_location_desc','لەکوێیت و خەونی گەشت بۆ کوێ دەبینیت؟','registration','step desc'),
('kurdish_sorani','reg.step_photos','وێنەکان','registration','step title'),
('kurdish_sorani','reg.step_photos_desc','باشترین وێنەکانت زیاد بکە','registration','step desc'),

-- Kurdish Kurmanci
('kurdish_kurmanci','location.geolocation_not_supported','Geolokasyon nayê piştgirîkirin','location','toast'),
('kurdish_kurmanci','location.browser_no_geolocation','Geroka te xizmetên geolokasyonê piştgirî nake.','location','toast'),
('kurdish_kurmanci','location.location_updated','Cîh hate nûvekirin','location','toast'),
('kurdish_kurmanci','location.current_location_set','Cîhê te yê niha hate danîn.','location','toast'),
('kurdish_kurmanci','location.location_error','Çewtiya cîhê','location','toast'),
('kurdish_kurmanci','location.could_not_determine','Cîhê te nehat diyarkirin. Ji kerema xwe dîsa biceribîne.','location','toast'),
('kurdish_kurmanci','location.permission_denied','Destûra cîhê hat redkirin. Ji kerema xwe xizmetên cîhê di mîhengên gerokê de çalak bike.','location','toast'),
('kurdish_kurmanci','location.position_unavailable','Agahiya cîhê peyda nabe.','location','toast'),
('kurdish_kurmanci','location.request_timeout','Daxwaza cîhê dem derbas bû.','location','toast'),
('kurdish_kurmanci','location.manually_set_to','Cîhê te bi destan hate danîn li {{location}}','location','toast'),
('kurdish_kurmanci','location.passport_location_set','Cîhê pasaportê hate danîn','location','toast'),
('kurdish_kurmanci','location.passport_location_cleared','Cîhê pasaportê hate pakkirin','location','toast'),
('kurdish_kurmanci','location.browsing_from','Tu niha ji {{location}} digerî','location','toast'),
('kurdish_kurmanci','location.travel_mode_deactivated','Moda rêwîtiyê hate neçalakkirin','location','toast'),
('kurdish_kurmanci','reg.step_email_password','E-name û şîfre','registration','step title'),
('kurdish_kurmanci','reg.step_email_desc','Hesabê xwe yê ewle biafirîne','registration','step desc'),
('kurdish_kurmanci','reg.step_basic_info','Agahiyên bingehîn','registration','step title'),
('kurdish_kurmanci','reg.step_basic_desc','Ji me re li ser xwe agahdar bike','registration','step desc'),
('kurdish_kurmanci','reg.step_location','Cîh û Rêwîtî','registration','step title'),
('kurdish_kurmanci','reg.step_location_desc','Tu ji ku yî û xewna te rêwîtî bo ku ye?','registration','step desc'),
('kurdish_kurmanci','reg.step_photos','Wêne','registration','step title'),
('kurdish_kurmanci','reg.step_photos_desc','Wêneyên xwe yên herî baş zêde bike','registration','step desc'),

-- German
('german','location.geolocation_not_supported','Geolokalisierung nicht unterstützt','location','toast'),
('german','location.browser_no_geolocation','Dein Browser unterstützt keine Geolokalisierungsdienste.','location','toast'),
('german','location.location_updated','Standort aktualisiert','location','toast'),
('german','location.current_location_set','Dein aktueller Standort wurde festgelegt.','location','toast'),
('german','location.location_error','Standortfehler','location','toast'),
('german','location.could_not_determine','Standort konnte nicht ermittelt werden. Bitte versuche es erneut.','location','toast'),
('german','location.permission_denied','Standortberechtigung verweigert. Bitte aktiviere Standortdienste in deinen Browsereinstellungen.','location','toast'),
('german','location.position_unavailable','Standortinformationen sind nicht verfügbar.','location','toast'),
('german','location.request_timeout','Standortanfrage hat das Zeitlimit überschritten.','location','toast'),
('german','location.manually_set_to','Dein Standort wurde manuell auf {{location}} gesetzt','location','toast'),
('german','location.passport_location_set','Reisepass-Standort festgelegt','location','toast'),
('german','location.passport_location_cleared','Reisepass-Standort gelöscht','location','toast'),
('german','location.browsing_from','Du surfst jetzt von {{location}}','location','toast'),
('german','location.travel_mode_deactivated','Reisemodus deaktiviert','location','toast'),
('german','reg.step_email_password','E-Mail & Passwort','registration','step title'),
('german','reg.step_email_desc','Erstelle dein sicheres Konto','registration','step desc'),
('german','reg.step_basic_info','Grundlegende Infos','registration','step title'),
('german','reg.step_basic_desc','Erzähl uns von dir','registration','step desc'),
('german','reg.step_location','Standort & Reisen','registration','step title'),
('german','reg.step_location_desc','Woher kommst du und wohin träumst du zu reisen?','registration','step desc'),
('german','reg.step_photos','Fotos','registration','step title'),
('german','reg.step_photos_desc','Füge deine besten Fotos hinzu','registration','step desc')

ON CONFLICT (language_code, translation_key) DO UPDATE SET translation_value = EXCLUDED.translation_value;
