
-- Batch 3: Toast messages, dialog strings, hooks feedback
-- Excluding common.cancel and common.download which already exist

INSERT INTO public.app_translations (language_code, translation_key, translation_value, category, auto_translated, needs_review) VALUES

-- ===== PROFILE EDITOR TOASTS =====
('english', 'toast.profile.basic_updated', 'Basic info updated successfully!', 'profile', false, false),
('norwegian', 'toast.profile.basic_updated', 'Grunnleggende info oppdatert!', 'profile', true, true),
('kurdish_sorani', 'toast.profile.basic_updated', 'زانیاری سەرەکی بە سەرکەوتوویی نوێ کرایەوە!', 'profile', true, true),
('kurdish_kurmanci', 'toast.profile.basic_updated', 'Agahiyên bingehîn bi serkeftî hatin nûkirin!', 'profile', true, true),
('german', 'toast.profile.basic_updated', 'Grundinformationen erfolgreich aktualisiert!', 'profile', true, true),

('english', 'toast.profile.career_updated', 'Education & career updated!', 'profile', false, false),
('norwegian', 'toast.profile.career_updated', 'Utdanning og karriere oppdatert!', 'profile', true, true),
('kurdish_sorani', 'toast.profile.career_updated', 'خوێندن و کار نوێ کرایەوە!', 'profile', true, true),
('kurdish_kurmanci', 'toast.profile.career_updated', 'Perwerde û karîyer hatin nûkirin!', 'profile', true, true),
('german', 'toast.profile.career_updated', 'Bildung & Karriere aktualisiert!', 'profile', true, true),

('english', 'toast.profile.values_updated', 'Values & personality updated!', 'profile', false, false),
('norwegian', 'toast.profile.values_updated', 'Verdier og personlighet oppdatert!', 'profile', true, true),
('kurdish_sorani', 'toast.profile.values_updated', 'بەها و کەسایەتی نوێ کرایەوە!', 'profile', true, true),
('kurdish_kurmanci', 'toast.profile.values_updated', 'Nirx û kesayetî hatin nûkirin!', 'profile', true, true),
('german', 'toast.profile.values_updated', 'Werte & Persönlichkeit aktualisiert!', 'profile', true, true),

('english', 'toast.profile.interests_updated', 'Interests & hobbies updated!', 'profile', false, false),
('norwegian', 'toast.profile.interests_updated', 'Interesser og hobbyer oppdatert!', 'profile', true, true),
('kurdish_sorani', 'toast.profile.interests_updated', 'ئارەزوو و ئاسایشەکان نوێ کرایەوە!', 'profile', true, true),
('kurdish_kurmanci', 'toast.profile.interests_updated', 'Eleqe û hobî hatin nûkirin!', 'profile', true, true),
('german', 'toast.profile.interests_updated', 'Interessen & Hobbys aktualisiert!', 'profile', true, true),

('english', 'toast.profile.favorites_updated', 'Favorites updated successfully!', 'profile', false, false),
('norwegian', 'toast.profile.favorites_updated', 'Favoritter oppdatert!', 'profile', true, true),
('kurdish_sorani', 'toast.profile.favorites_updated', 'دڵخوازەکان بە سەرکەوتوویی نوێ کرایەوە!', 'profile', true, true),
('kurdish_kurmanci', 'toast.profile.favorites_updated', 'Bijarte bi serkeftî hatin nûkirin!', 'profile', true, true),
('german', 'toast.profile.favorites_updated', 'Favoriten erfolgreich aktualisiert!', 'profile', true, true),

('english', 'toast.profile.relationship_updated', 'Relationship preferences updated!', 'profile', false, false),
('norwegian', 'toast.profile.relationship_updated', 'Forholdspreferanser oppdatert!', 'profile', true, true),
('kurdish_sorani', 'toast.profile.relationship_updated', 'ئارەزووی پەیوەندی نوێ کرایەوە!', 'profile', true, true),
('kurdish_kurmanci', 'toast.profile.relationship_updated', 'Vebijarkên têkiliyê hatin nûkirin!', 'profile', true, true),
('german', 'toast.profile.relationship_updated', 'Beziehungspräferenzen aktualisiert!', 'profile', true, true),

('english', 'toast.profile.bio_updated', 'Bio updated successfully!', 'profile', false, false),
('norwegian', 'toast.profile.bio_updated', 'Bio oppdatert!', 'profile', true, true),
('kurdish_sorani', 'toast.profile.bio_updated', 'بایۆ بە سەرکەوتوویی نوێ کرایەوە!', 'profile', true, true),
('kurdish_kurmanci', 'toast.profile.bio_updated', 'Biyografî bi serkeftî hat nûkirin!', 'profile', true, true),
('german', 'toast.profile.bio_updated', 'Bio erfolgreich aktualisiert!', 'profile', true, true),

('english', 'toast.profile.photo_removed', 'Photo removed successfully', 'profile', false, false),
('norwegian', 'toast.profile.photo_removed', 'Bilde fjernet', 'profile', true, true),
('kurdish_sorani', 'toast.profile.photo_removed', 'وێنە لابرا', 'profile', true, true),
('kurdish_kurmanci', 'toast.profile.photo_removed', 'Wêne hat rakirin', 'profile', true, true),
('german', 'toast.profile.photo_removed', 'Foto erfolgreich entfernt', 'profile', true, true),

('english', 'toast.profile.photo_updated', 'Profile photo updated', 'profile', false, false),
('norwegian', 'toast.profile.photo_updated', 'Profilbilde oppdatert', 'profile', true, true),
('kurdish_sorani', 'toast.profile.photo_updated', 'وێنەی پرۆفایل نوێ کرایەوە', 'profile', true, true),
('kurdish_kurmanci', 'toast.profile.photo_updated', 'Wêneyê profîlê hat nûkirin', 'profile', true, true),
('german', 'toast.profile.photo_updated', 'Profilfoto aktualisiert', 'profile', true, true),

('english', 'toast.privacy.sharing_removed', 'Sharing removed', 'settings', false, false),
('norwegian', 'toast.privacy.sharing_removed', 'Deling fjernet', 'settings', true, true),
('kurdish_sorani', 'toast.privacy.sharing_removed', 'هاوبەشکردن لابرا', 'settings', true, true),
('kurdish_kurmanci', 'toast.privacy.sharing_removed', 'Parvekirinê hat rakirin', 'settings', true, true),
('german', 'toast.privacy.sharing_removed', 'Freigabe entfernt', 'settings', true, true),

('english', 'toast.privacy.profile_shared', 'Profile shared', 'settings', false, false),
('norwegian', 'toast.privacy.profile_shared', 'Profil delt', 'settings', true, true),
('kurdish_sorani', 'toast.privacy.profile_shared', 'پرۆفایل هاوبەش کرا', 'settings', true, true),
('kurdish_kurmanci', 'toast.privacy.profile_shared', 'Profîl hat parve kirin', 'settings', true, true),
('german', 'toast.privacy.profile_shared', 'Profil geteilt', 'settings', true, true),

('english', 'toast.privacy.update_failed', 'Failed to update sharing', 'settings', false, false),
('norwegian', 'toast.privacy.update_failed', 'Kunne ikke oppdatere deling', 'settings', true, true),
('kurdish_sorani', 'toast.privacy.update_failed', 'نەتوانرا هاوبەشکردن نوێ بکرێتەوە', 'settings', true, true),
('kurdish_kurmanci', 'toast.privacy.update_failed', 'Parvekirinê nûkirin bi ser neket', 'settings', true, true),
('german', 'toast.privacy.update_failed', 'Freigabe konnte nicht aktualisiert werden', 'settings', true, true),

('english', 'toast.privacy.premium_feature', 'Field visibility is a Premium feature', 'settings', false, false),
('norwegian', 'toast.privacy.premium_feature', 'Feltsynlighet er en Premium-funksjon', 'settings', true, true),
('kurdish_sorani', 'toast.privacy.premium_feature', 'بینینی بواری تایبەتمەندی پریمیۆمە', 'settings', true, true),
('kurdish_kurmanci', 'toast.privacy.premium_feature', 'Dîtina qadê taybetmendiya Premium e', 'settings', true, true),
('german', 'toast.privacy.premium_feature', 'Feldsichtbarkeit ist eine Premium-Funktion', 'settings', true, true),

('english', 'toast.ai_bio.generating', 'AI is crafting 5 personalized bios...', 'profile', false, false),
('norwegian', 'toast.ai_bio.generating', 'AI lager 5 personlige bioer...', 'profile', true, true),
('kurdish_sorani', 'toast.ai_bio.generating', 'AI ٥ بایۆی تایبەت بۆت دروست دەکات...', 'profile', true, true),
('kurdish_kurmanci', 'toast.ai_bio.generating', 'AI 5 biyografiyên kesane çêdike...', 'profile', true, true),
('german', 'toast.ai_bio.generating', 'KI erstellt 5 personalisierte Bios...', 'profile', true, true),

('english', 'toast.ai_bio.generated', '5 personalized bios generated!', 'profile', false, false),
('norwegian', 'toast.ai_bio.generated', '5 personlige bioer generert!', 'profile', true, true),
('kurdish_sorani', 'toast.ai_bio.generated', '٥ بایۆی تایبەت دروست کران!', 'profile', true, true),
('kurdish_kurmanci', 'toast.ai_bio.generated', '5 biyografiyên kesane hatin çêkirin!', 'profile', true, true),
('german', 'toast.ai_bio.generated', '5 personalisierte Bios erstellt!', 'profile', true, true),

('english', 'toast.ai_bio.failed', 'Failed to generate bios', 'profile', false, false),
('norwegian', 'toast.ai_bio.failed', 'Kunne ikke generere bioer', 'profile', true, true),
('kurdish_sorani', 'toast.ai_bio.failed', 'نەتوانرا بایۆ دروست بکرێت', 'profile', true, true),
('kurdish_kurmanci', 'toast.ai_bio.failed', 'Çêkirina biyografiyan bi ser neket', 'profile', true, true),
('german', 'toast.ai_bio.failed', 'Bios konnten nicht erstellt werden', 'profile', true, true),

('english', 'download_data.title', 'Download My Data', 'profile', false, false),
('norwegian', 'download_data.title', 'Last ned mine data', 'profile', true, true),
('kurdish_sorani', 'download_data.title', 'داگرتنی داتاکانم', 'profile', true, true),
('kurdish_kurmanci', 'download_data.title', 'Daxistina daneyên min', 'profile', true, true),
('german', 'download_data.title', 'Meine Daten herunterladen', 'profile', true, true),

('english', 'download_data.whats_included', 'What''s Included', 'profile', false, false),
('norwegian', 'download_data.whats_included', 'Hva som er inkludert', 'profile', true, true),
('kurdish_sorani', 'download_data.whats_included', 'چی لەخۆ دەگرێت', 'profile', true, true),
('kurdish_kurmanci', 'download_data.whats_included', 'Çi tê de ye', 'profile', true, true),
('german', 'download_data.whats_included', 'Was enthalten ist', 'profile', true, true),

('english', 'download_data.profile_info', 'Profile information and photos', 'profile', false, false),
('norwegian', 'download_data.profile_info', 'Profilinformasjon og bilder', 'profile', true, true),
('kurdish_sorani', 'download_data.profile_info', 'زانیاری پرۆفایل و وێنەکان', 'profile', true, true),
('kurdish_kurmanci', 'download_data.profile_info', 'Agahiyên profîlê û wêne', 'profile', true, true),
('german', 'download_data.profile_info', 'Profilinformationen und Fotos', 'profile', true, true),

('english', 'download_data.match_history', 'Match history and conversations', 'profile', false, false),
('norwegian', 'download_data.match_history', 'Matchhistorikk og samtaler', 'profile', true, true),
('kurdish_sorani', 'download_data.match_history', 'مێژووی هاوتا و گفتوگۆکان', 'profile', true, true),
('kurdish_kurmanci', 'download_data.match_history', 'Dîroka lihevhatinan û axaftinan', 'profile', true, true),
('german', 'download_data.match_history', 'Match-Verlauf und Gespräche', 'profile', true, true),

('english', 'download_data.likes', 'Likes given and received', 'profile', false, false),
('norwegian', 'download_data.likes', 'Likes gitt og mottatt', 'profile', true, true),
('kurdish_sorani', 'download_data.likes', 'لایکی نێردراو و وەرگیراو', 'profile', true, true),
('kurdish_kurmanci', 'download_data.likes', 'Lîkên hatine dayîn û wergirtin', 'profile', true, true),
('german', 'download_data.likes', 'Gegebene und erhaltene Likes', 'profile', true, true),

('english', 'download_data.social_accounts', 'Connected social accounts', 'profile', false, false),
('norwegian', 'download_data.social_accounts', 'Tilkoblede sosiale kontoer', 'profile', true, true),
('kurdish_sorani', 'download_data.social_accounts', 'هەژمارە کۆمەڵایەتییە پەیوەندیدارەکان', 'profile', true, true),
('kurdish_kurmanci', 'download_data.social_accounts', 'Hesabên civakî yên girêdayî', 'profile', true, true),
('german', 'download_data.social_accounts', 'Verbundene soziale Konten', 'profile', true, true),

('english', 'download_data.activity', 'Account activity data', 'profile', false, false),
('norwegian', 'download_data.activity', 'Kontoaktivitetsdata', 'profile', true, true),
('kurdish_sorani', 'download_data.activity', 'داتای چالاکی هەژمار', 'profile', true, true),
('kurdish_kurmanci', 'download_data.activity', 'Daneyên çalakiya hesab', 'profile', true, true),
('german', 'download_data.activity', 'Kontoaktivitätsdaten', 'profile', true, true),

('english', 'download_data.privacy_title', 'Privacy & Security', 'profile', false, false),
('norwegian', 'download_data.privacy_title', 'Personvern og sikkerhet', 'profile', true, true),
('kurdish_sorani', 'download_data.privacy_title', 'تایبەتمەندی و ئاسایش', 'profile', true, true),
('kurdish_kurmanci', 'download_data.privacy_title', 'Nepenî û Ewlehî', 'profile', true, true),
('german', 'download_data.privacy_title', 'Datenschutz & Sicherheit', 'profile', true, true),

('english', 'download_data.privacy_desc', 'Your data is exported securely and includes only information associated with your account.', 'profile', false, false),
('norwegian', 'download_data.privacy_desc', 'Dine data eksporteres sikkert og inkluderer kun informasjon knyttet til din konto.', 'profile', true, true),
('kurdish_sorani', 'download_data.privacy_desc', 'داتاکانت بە شێوەیەکی پارێزراو هەناردە دەکرێت و تەنها زانیاری پەیوەندیدار بە هەژمارەکەت لەخۆ دەگرێت.', 'profile', true, true),
('kurdish_kurmanci', 'download_data.privacy_desc', 'Daneyên te bi ewlehî têne derxistin û tenê agahiyên bi hesabê te ve girêdayî hene.', 'profile', true, true),
('german', 'download_data.privacy_desc', 'Ihre Daten werden sicher exportiert und enthalten nur Informationen, die mit Ihrem Konto verknüpft sind.', 'profile', true, true),

('english', 'download_data.preparing', 'Preparing your data...', 'profile', false, false),
('norwegian', 'download_data.preparing', 'Forbereder dataene dine...', 'profile', true, true),
('kurdish_sorani', 'download_data.preparing', 'داتاکانت ئامادە دەکرێت...', 'profile', true, true),
('kurdish_kurmanci', 'download_data.preparing', 'Daneyên te têne amadekirin...', 'profile', true, true),
('german', 'download_data.preparing', 'Ihre Daten werden vorbereitet...', 'profile', true, true),

('english', 'download_data.success', 'Your data has been downloaded successfully!', 'profile', false, false),
('norwegian', 'download_data.success', 'Dataene dine er lastet ned!', 'profile', true, true),
('kurdish_sorani', 'download_data.success', 'داتاکانت بە سەرکەوتوویی داگیرا!', 'profile', true, true),
('kurdish_kurmanci', 'download_data.success', 'Daneyên te bi serkeftî hatin daxistin!', 'profile', true, true),
('german', 'download_data.success', 'Ihre Daten wurden erfolgreich heruntergeladen!', 'profile', true, true),

('english', 'download_data.error', 'Failed to download your data. Please try again.', 'profile', false, false),
('norwegian', 'download_data.error', 'Kunne ikke laste ned dataene dine. Prøv igjen.', 'profile', true, true),
('kurdish_sorani', 'download_data.error', 'نەتوانرا داتاکانت داگیرێت. تکایە دووبارە هەوڵبدە.', 'profile', true, true),
('kurdish_kurmanci', 'download_data.error', 'Daxistina daneyan bi ser neket. Ji kerema xwe dîsa biceribîne.', 'profile', true, true),
('german', 'download_data.error', 'Daten konnten nicht heruntergeladen werden. Bitte versuchen Sie es erneut.', 'profile', true, true),

('english', 'toast.password.changed', 'Password changed successfully!', 'auth', false, false),
('norwegian', 'toast.password.changed', 'Passord endret!', 'auth', true, true),
('kurdish_sorani', 'toast.password.changed', 'وشەی نهێنی بە سەرکەوتوویی گۆڕدرا!', 'auth', true, true),
('kurdish_kurmanci', 'toast.password.changed', 'Şîfre bi serkeftî hat guhertin!', 'auth', true, true),
('german', 'toast.password.changed', 'Passwort erfolgreich geändert!', 'auth', true, true),

('english', 'toast.accounts.load_failed', 'Failed to load connected accounts', 'profile', false, false),
('norwegian', 'toast.accounts.load_failed', 'Kunne ikke laste tilkoblede kontoer', 'profile', true, true),
('kurdish_sorani', 'toast.accounts.load_failed', 'نەتوانرا هەژمارە پەیوەندیدارەکان بار بکرێن', 'profile', true, true),
('kurdish_kurmanci', 'toast.accounts.load_failed', 'Hesabên girêdayî nehatin barkirin', 'profile', true, true),
('german', 'toast.accounts.load_failed', 'Verbundene Konten konnten nicht geladen werden', 'profile', true, true),

('english', 'toast.accounts.enter_username', 'Please enter a username', 'profile', false, false),
('norwegian', 'toast.accounts.enter_username', 'Vennligst skriv inn et brukernavn', 'profile', true, true),
('kurdish_sorani', 'toast.accounts.enter_username', 'تکایە ناوی بەکارهێنەر بنووسە', 'profile', true, true),
('kurdish_kurmanci', 'toast.accounts.enter_username', 'Ji kerema xwe navê bikarhêner binivîse', 'profile', true, true),
('german', 'toast.accounts.enter_username', 'Bitte geben Sie einen Benutzernamen ein', 'profile', true, true),

('english', 'toast.accounts.link_copied', 'Shareable link copied!', 'profile', false, false),
('norwegian', 'toast.accounts.link_copied', 'Delbar lenke kopiert!', 'profile', true, true),
('kurdish_sorani', 'toast.accounts.link_copied', 'لینکی هاوبەشکردن کۆپی کرا!', 'profile', true, true),
('kurdish_kurmanci', 'toast.accounts.link_copied', 'Lînka parvekirinê hat kopîkirin!', 'profile', true, true),
('german', 'toast.accounts.link_copied', 'Teilbarer Link kopiert!', 'profile', true, true),

('english', 'toast.languages.updated', 'Languages updated successfully!', 'profile', false, false),
('norwegian', 'toast.languages.updated', 'Språk oppdatert!', 'profile', true, true),
('kurdish_sorani', 'toast.languages.updated', 'زمانەکان بە سەرکەوتوویی نوێ کرایەوە!', 'profile', true, true),
('kurdish_kurmanci', 'toast.languages.updated', 'Ziman bi serkeftî hatin nûkirin!', 'profile', true, true),
('german', 'toast.languages.updated', 'Sprachen erfolgreich aktualisiert!', 'profile', true, true),

-- HOOKS
('english', 'toast.settings.load_failed', 'Failed to load settings', 'settings', false, false),
('norwegian', 'toast.settings.load_failed', 'Kunne ikke laste innstillinger', 'settings', true, true),
('kurdish_sorani', 'toast.settings.load_failed', 'نەتوانرا ڕێکخستنەکان بار بکرێن', 'settings', true, true),
('kurdish_kurmanci', 'toast.settings.load_failed', 'Mîheng nehatin barkirin', 'settings', true, true),
('german', 'toast.settings.load_failed', 'Einstellungen konnten nicht geladen werden', 'settings', true, true),

('english', 'toast.settings.updated', 'Settings updated successfully', 'settings', false, false),
('norwegian', 'toast.settings.updated', 'Innstillinger oppdatert', 'settings', true, true),
('kurdish_sorani', 'toast.settings.updated', 'ڕێکخستنەکان بە سەرکەوتوویی نوێ کرایەوە', 'settings', true, true),
('kurdish_kurmanci', 'toast.settings.updated', 'Mîheng bi serkeftî hatin nûkirin', 'settings', true, true),
('german', 'toast.settings.updated', 'Einstellungen erfolgreich aktualisiert', 'settings', true, true),

('english', 'toast.settings.update_failed', 'Failed to update settings', 'settings', false, false),
('norwegian', 'toast.settings.update_failed', 'Kunne ikke oppdatere innstillinger', 'settings', true, true),
('kurdish_sorani', 'toast.settings.update_failed', 'نەتوانرا ڕێکخستنەکان نوێ بکرێنەوە', 'settings', true, true),
('kurdish_kurmanci', 'toast.settings.update_failed', 'Nûkirina mîhengan bi ser neket', 'settings', true, true),
('german', 'toast.settings.update_failed', 'Einstellungen konnten nicht aktualisiert werden', 'settings', true, true),

('english', 'toast.video.must_login', 'You must be logged in', 'auth', false, false),
('norwegian', 'toast.video.must_login', 'Du må være innlogget', 'auth', true, true),
('kurdish_sorani', 'toast.video.must_login', 'دەبێت چوونەژوورەوە بکەیت', 'auth', true, true),
('kurdish_kurmanci', 'toast.video.must_login', 'Divê tu têkevî', 'auth', true, true),
('german', 'toast.video.must_login', 'Sie müssen angemeldet sein', 'auth', true, true),

('english', 'toast.video.storage_not_configured', 'Video storage not configured', 'settings', false, false),
('norwegian', 'toast.video.storage_not_configured', 'Videolagring er ikke konfigurert', 'settings', true, true),
('kurdish_sorani', 'toast.video.storage_not_configured', 'کۆگای ڤیدیۆ ڕێکنەخراوە', 'settings', true, true),
('kurdish_kurmanci', 'toast.video.storage_not_configured', 'Depoya vîdyoyê nehatiye mîhenkirin', 'settings', true, true),
('german', 'toast.video.storage_not_configured', 'Videospeicher nicht konfiguriert', 'settings', true, true),

('english', 'toast.video.submitted', 'Verification submitted!', 'profile', false, false),
('norwegian', 'toast.video.submitted', 'Verifisering sendt!', 'profile', true, true),
('kurdish_sorani', 'toast.video.submitted', 'پشتڕاستکردنەوە نێردرا!', 'profile', true, true),
('kurdish_kurmanci', 'toast.video.submitted', 'Verastkirinê hat şandin!', 'profile', true, true),
('german', 'toast.video.submitted', 'Verifizierung eingereicht!', 'profile', true, true),

('english', 'toast.ai.too_many_requests', 'Too many requests', 'common', false, false),
('norwegian', 'toast.ai.too_many_requests', 'For mange forespørsler', 'common', true, true),
('kurdish_sorani', 'toast.ai.too_many_requests', 'داواکاری زۆر', 'common', true, true),
('kurdish_kurmanci', 'toast.ai.too_many_requests', 'Pir zêde daxwaz', 'common', true, true),
('german', 'toast.ai.too_many_requests', 'Zu viele Anfragen', 'common', true, true),

('english', 'toast.ai.credits_exhausted', 'AI credits exhausted', 'common', false, false),
('norwegian', 'toast.ai.credits_exhausted', 'AI-kreditter brukt opp', 'common', true, true),
('kurdish_sorani', 'toast.ai.credits_exhausted', 'کرێدیتی AI تەواو بوو', 'common', true, true),
('kurdish_kurmanci', 'toast.ai.credits_exhausted', 'Krediyên AI qediya', 'common', true, true),
('german', 'toast.ai.credits_exhausted', 'KI-Guthaben aufgebraucht', 'common', true, true),

('english', 'toast.ai.suggestion_failed', 'Could not generate suggestions', 'common', false, false),
('norwegian', 'toast.ai.suggestion_failed', 'Kunne ikke generere forslag', 'common', true, true),
('kurdish_sorani', 'toast.ai.suggestion_failed', 'نەتوانرا پێشنیار دروست بکرێت', 'common', true, true),
('kurdish_kurmanci', 'toast.ai.suggestion_failed', 'Nehat pêşniyar çêkirin', 'common', true, true),
('german', 'toast.ai.suggestion_failed', 'Vorschläge konnten nicht erstellt werden', 'common', true, true),

('english', 'toast.ai.something_wrong', 'Something went wrong', 'common', false, false),
('norwegian', 'toast.ai.something_wrong', 'Noe gikk galt', 'common', true, true),
('kurdish_sorani', 'toast.ai.something_wrong', 'هەڵەیەک ڕوویدا', 'common', true, true),
('kurdish_kurmanci', 'toast.ai.something_wrong', 'Tiştek xelet çêbû', 'common', true, true),
('german', 'toast.ai.something_wrong', 'Etwas ist schiefgelaufen', 'common', true, true),

('english', 'toast.swipe.premium_feature', 'Rewind is a premium feature', 'common', false, false),
('norwegian', 'toast.swipe.premium_feature', 'Spol tilbake er en Premium-funksjon', 'common', true, true),
('kurdish_sorani', 'toast.swipe.premium_feature', 'گەڕانەوە تایبەتمەندی پریمیۆمە', 'common', true, true),
('kurdish_kurmanci', 'toast.swipe.premium_feature', 'Paşvegerin taybetmendiya Premium e', 'common', true, true),
('german', 'toast.swipe.premium_feature', 'Zurückspulen ist eine Premium-Funktion', 'common', true, true),

('english', 'toast.swipe.no_swipe', 'No swipe to undo', 'common', false, false),
('norwegian', 'toast.swipe.no_swipe', 'Ingen sveip å angre', 'common', true, true),
('kurdish_sorani', 'toast.swipe.no_swipe', 'هیچ سوایپێک نییە بۆ پاشگەزبوونەوە', 'common', true, true),
('kurdish_kurmanci', 'toast.swipe.no_swipe', 'Tu swipe tune ku paşve were girtin', 'common', true, true),
('german', 'toast.swipe.no_swipe', 'Kein Swipe zum Rückgängigmachen', 'common', true, true),

('english', 'toast.swipe.undone', 'Swipe undone!', 'common', false, false),
('norwegian', 'toast.swipe.undone', 'Sveip angret!', 'common', true, true),
('kurdish_sorani', 'toast.swipe.undone', 'سوایپ پاشگەزکرایەوە!', 'common', true, true),
('kurdish_kurmanci', 'toast.swipe.undone', 'Swipe hat paşve girtin!', 'common', true, true),
('german', 'toast.swipe.undone', 'Swipe rückgängig gemacht!', 'common', true, true),

('english', 'toast.swipe.undo_failed', 'Failed to undo swipe', 'common', false, false),
('norwegian', 'toast.swipe.undo_failed', 'Kunne ikke angre sveip', 'common', true, true),
('kurdish_sorani', 'toast.swipe.undo_failed', 'نەتوانرا سوایپ پاشگەز بکرێتەوە', 'common', true, true),
('kurdish_kurmanci', 'toast.swipe.undo_failed', 'Paşvegirtina swipe bi ser neket', 'common', true, true),
('german', 'toast.swipe.undo_failed', 'Swipe konnte nicht rückgängig gemacht werden', 'common', true, true),

('english', 'toast.profile.load_failed', 'Failed to load profile data', 'profile', false, false),
('norwegian', 'toast.profile.load_failed', 'Kunne ikke laste profildata', 'profile', true, true),
('kurdish_sorani', 'toast.profile.load_failed', 'نەتوانرا داتای پرۆفایل بار بکرێت', 'profile', true, true),
('kurdish_kurmanci', 'toast.profile.load_failed', 'Daneyên profîlê nehatin barkirin', 'profile', true, true),
('german', 'toast.profile.load_failed', 'Profildaten konnten nicht geladen werden', 'profile', true, true),

('english', 'toast.profile.update_failed', 'Failed to update profile', 'profile', false, false),
('norwegian', 'toast.profile.update_failed', 'Kunne ikke oppdatere profil', 'profile', true, true),
('kurdish_sorani', 'toast.profile.update_failed', 'نەتوانرا پرۆفایل نوێ بکرێتەوە', 'profile', true, true),
('kurdish_kurmanci', 'toast.profile.update_failed', 'Nûkirina profîlê bi ser neket', 'profile', true, true),
('german', 'toast.profile.update_failed', 'Profil konnte nicht aktualisiert werden', 'profile', true, true),

('english', 'toast.admin.setting_updated', 'Setting updated', 'settings', false, false),
('norwegian', 'toast.admin.setting_updated', 'Innstilling oppdatert', 'settings', true, true),
('kurdish_sorani', 'toast.admin.setting_updated', 'ڕێکخستن نوێ کرایەوە', 'settings', true, true),
('kurdish_kurmanci', 'toast.admin.setting_updated', 'Mîheng hat nûkirin', 'settings', true, true),
('german', 'toast.admin.setting_updated', 'Einstellung aktualisiert', 'settings', true, true),

('english', 'toast.admin.settings_saved', 'Settings saved', 'settings', false, false),
('norwegian', 'toast.admin.settings_saved', 'Innstillinger lagret', 'settings', true, true),
('kurdish_sorani', 'toast.admin.settings_saved', 'ڕێکخستنەکان پاشەکەوت کران', 'settings', true, true),
('kurdish_kurmanci', 'toast.admin.settings_saved', 'Mîheng hatin tomarkirin', 'settings', true, true),
('german', 'toast.admin.settings_saved', 'Einstellungen gespeichert', 'settings', true, true),

('english', 'toast.admin.settings_reset', 'Settings reset to defaults', 'settings', false, false),
('norwegian', 'toast.admin.settings_reset', 'Innstillinger tilbakestilt til standard', 'settings', true, true),
('kurdish_sorani', 'toast.admin.settings_reset', 'ڕێکخستنەکان گەڕایەوە بۆ بنەڕەت', 'settings', true, true),
('kurdish_kurmanci', 'toast.admin.settings_reset', 'Mîheng vegeriyan ser standard', 'settings', true, true),
('german', 'toast.admin.settings_reset', 'Einstellungen auf Standard zurückgesetzt', 'settings', true, true),

('english', 'toast.post.empty', 'Post content cannot be empty', 'discovery', false, false),
('norwegian', 'toast.post.empty', 'Innleggsinnhold kan ikke være tomt', 'discovery', true, true),
('kurdish_sorani', 'toast.post.empty', 'ناوەڕۆکی پۆست نابێت بەتاڵ بێت', 'discovery', true, true),
('kurdish_kurmanci', 'toast.post.empty', 'Naveroka postê nikare vala be', 'discovery', true, true),
('german', 'toast.post.empty', 'Beitragsinhalt darf nicht leer sein', 'discovery', true, true),

('english', 'toast.post.too_long', 'Post is too long (max 5000 characters)', 'discovery', false, false),
('norwegian', 'toast.post.too_long', 'Innlegget er for langt (maks 5000 tegn)', 'discovery', true, true),
('kurdish_sorani', 'toast.post.too_long', 'پۆستەکە زۆر درێژە (زۆرینە ٥٠٠٠ پیت)', 'discovery', true, true),
('kurdish_kurmanci', 'toast.post.too_long', 'Post pir dirêj e (herî zêde 5000 tîp)', 'discovery', true, true),
('german', 'toast.post.too_long', 'Beitrag ist zu lang (max. 5000 Zeichen)', 'discovery', true, true),

('english', 'toast.post.updated', 'Post updated successfully', 'discovery', false, false),
('norwegian', 'toast.post.updated', 'Innlegg oppdatert', 'discovery', true, true),
('kurdish_sorani', 'toast.post.updated', 'پۆست بە سەرکەوتوویی نوێ کرایەوە', 'discovery', true, true),
('kurdish_kurmanci', 'toast.post.updated', 'Post bi serkeftî hat nûkirin', 'discovery', true, true),
('german', 'toast.post.updated', 'Beitrag erfolgreich aktualisiert', 'discovery', true, true),

('english', 'toast.post.update_failed', 'Failed to update post', 'discovery', false, false),
('norwegian', 'toast.post.update_failed', 'Kunne ikke oppdatere innlegg', 'discovery', true, true),
('kurdish_sorani', 'toast.post.update_failed', 'نەتوانرا پۆست نوێ بکرێتەوە', 'discovery', true, true),
('kurdish_kurmanci', 'toast.post.update_failed', 'Nûkirina postê bi ser neket', 'discovery', true, true),
('german', 'toast.post.update_failed', 'Beitrag konnte nicht aktualisiert werden', 'discovery', true, true),

('english', 'edit_post.title', 'Edit Post', 'discovery', false, false),
('norwegian', 'edit_post.title', 'Rediger innlegg', 'discovery', true, true),
('kurdish_sorani', 'edit_post.title', 'دەستکاری پۆست', 'discovery', true, true),
('kurdish_kurmanci', 'edit_post.title', 'Postê biguherîne', 'discovery', true, true),
('german', 'edit_post.title', 'Beitrag bearbeiten', 'discovery', true, true),

('english', 'edit_post.description', 'Make changes to your post content', 'discovery', false, false),
('norwegian', 'edit_post.description', 'Gjør endringer i innleggsinnholdet ditt', 'discovery', true, true),
('kurdish_sorani', 'edit_post.description', 'گۆڕانکاری لە ناوەڕۆکی پۆستەکەت بکە', 'discovery', true, true),
('kurdish_kurmanci', 'edit_post.description', 'Di naveroka postê xwe de guherînan bike', 'discovery', true, true),
('german', 'edit_post.description', 'Ändern Sie den Inhalt Ihres Beitrags', 'discovery', true, true),

('english', 'edit_post.placeholder', 'What''s on your mind?', 'discovery', false, false),
('norwegian', 'edit_post.placeholder', 'Hva tenker du på?', 'discovery', true, true),
('kurdish_sorani', 'edit_post.placeholder', 'چی لە مێشکتدایە؟', 'discovery', true, true),
('kurdish_kurmanci', 'edit_post.placeholder', 'Li ser çi difikire?', 'discovery', true, true),
('german', 'edit_post.placeholder', 'Was denkst du?', 'discovery', true, true),

('english', 'edit_post.save', 'Save Changes', 'discovery', false, false),
('norwegian', 'edit_post.save', 'Lagre endringer', 'discovery', true, true),
('kurdish_sorani', 'edit_post.save', 'پاشەکەوتکردنی گۆڕانکارییەکان', 'discovery', true, true),
('kurdish_kurmanci', 'edit_post.save', 'Guherînan tomar bike', 'discovery', true, true),
('german', 'edit_post.save', 'Änderungen speichern', 'discovery', true, true),

('english', 'toast.language.already_selected', 'This language is already selected', 'profile', false, false),
('norwegian', 'toast.language.already_selected', 'Dette språket er allerede valgt', 'profile', true, true),
('kurdish_sorani', 'toast.language.already_selected', 'ئەم زمانە پێشتر هەڵبژێردراوە', 'profile', true, true),
('kurdish_kurmanci', 'toast.language.already_selected', 'Ev ziman jixwe hatiye hilbijartin', 'profile', true, true),
('german', 'toast.language.already_selected', 'Diese Sprache ist bereits ausgewählt', 'profile', true, true);
