
INSERT INTO public.app_translations (language_code, translation_key, translation_value, category, context)
VALUES
-- DynamicRegistrationStepRenderer keys
('english','reg.setup_credentials','Set up your secure login credentials','auth','DynamicRegistrationStepRenderer subtitle'),
('english','reg.tell_us_about_yourself','Tell us about yourself','auth','DynamicRegistrationStepRenderer step 2 title'),
('english','reg.basic_info','Basic information to create your profile','auth','DynamicRegistrationStepRenderer step 2 subtitle'),
('english','reg.where_are_you_from','Where are you from?','auth','DynamicRegistrationStepRenderer step 3 subtitle'),
('english','reg.current_location','Current Location','auth','DynamicRegistrationStepRenderer label'),
('english','reg.detecting_location','Detecting location...','auth','DynamicRegistrationStepRenderer placeholder'),
('english','reg.enter_your_city','Enter your city','auth','DynamicRegistrationStepRenderer placeholder'),
('english','reg.add_photos','Add Photos','auth','DynamicRegistrationStepRenderer step 4 title'),
('english','reg.show_your_best_self','Show your best self','auth','DynamicRegistrationStepRenderer step 4 subtitle'),
-- ChangePasswordDialog password requirements
('english','settings.pwd_req_min_chars','At least 8 characters','settings','ChangePasswordDialog requirement'),
('english','settings.pwd_req_uppercase','Contains uppercase letter','settings','ChangePasswordDialog requirement'),
('english','settings.pwd_req_lowercase','Contains lowercase letter','settings','ChangePasswordDialog requirement'),
('english','settings.pwd_req_number','Contains number','settings','ChangePasswordDialog requirement'),
('english','settings.pwd_req_match','Passwords match','settings','ChangePasswordDialog requirement'),

-- Norwegian
('norwegian','reg.setup_credentials','Sett opp dine sikre innloggingsopplysninger','auth','DynamicRegistrationStepRenderer subtitle'),
('norwegian','reg.tell_us_about_yourself','Fortell oss om deg selv','auth','DynamicRegistrationStepRenderer step 2 title'),
('norwegian','reg.basic_info','Grunnleggende informasjon for å opprette profilen din','auth','DynamicRegistrationStepRenderer step 2 subtitle'),
('norwegian','reg.where_are_you_from','Hvor er du fra?','auth','DynamicRegistrationStepRenderer step 3 subtitle'),
('norwegian','reg.current_location','Nåværende plassering','auth','DynamicRegistrationStepRenderer label'),
('norwegian','reg.detecting_location','Oppdager plassering...','auth','DynamicRegistrationStepRenderer placeholder'),
('norwegian','reg.enter_your_city','Skriv inn byen din','auth','DynamicRegistrationStepRenderer placeholder'),
('norwegian','reg.add_photos','Legg til bilder','auth','DynamicRegistrationStepRenderer step 4 title'),
('norwegian','reg.show_your_best_self','Vis deg fra din beste side','auth','DynamicRegistrationStepRenderer step 4 subtitle'),
('norwegian','settings.pwd_req_min_chars','Minst 8 tegn','settings','ChangePasswordDialog requirement'),
('norwegian','settings.pwd_req_uppercase','Inneholder stor bokstav','settings','ChangePasswordDialog requirement'),
('norwegian','settings.pwd_req_lowercase','Inneholder liten bokstav','settings','ChangePasswordDialog requirement'),
('norwegian','settings.pwd_req_number','Inneholder tall','settings','ChangePasswordDialog requirement'),
('norwegian','settings.pwd_req_match','Passordene samsvarer','settings','ChangePasswordDialog requirement'),

-- German
('german','reg.setup_credentials','Richten Sie Ihre sicheren Anmeldedaten ein','auth','DynamicRegistrationStepRenderer subtitle'),
('german','reg.tell_us_about_yourself','Erzählen Sie uns von sich','auth','DynamicRegistrationStepRenderer step 2 title'),
('german','reg.basic_info','Grundlegende Informationen zur Erstellung Ihres Profils','auth','DynamicRegistrationStepRenderer step 2 subtitle'),
('german','reg.where_are_you_from','Woher kommen Sie?','auth','DynamicRegistrationStepRenderer step 3 subtitle'),
('german','reg.current_location','Aktueller Standort','auth','DynamicRegistrationStepRenderer label'),
('german','reg.detecting_location','Standort wird erkannt...','auth','DynamicRegistrationStepRenderer placeholder'),
('german','reg.enter_your_city','Geben Sie Ihre Stadt ein','auth','DynamicRegistrationStepRenderer placeholder'),
('german','reg.add_photos','Fotos hinzufügen','auth','DynamicRegistrationStepRenderer step 4 title'),
('german','reg.show_your_best_self','Zeigen Sie sich von Ihrer besten Seite','auth','DynamicRegistrationStepRenderer step 4 subtitle'),
('german','settings.pwd_req_min_chars','Mindestens 8 Zeichen','settings','ChangePasswordDialog requirement'),
('german','settings.pwd_req_uppercase','Enthält Großbuchstaben','settings','ChangePasswordDialog requirement'),
('german','settings.pwd_req_lowercase','Enthält Kleinbuchstaben','settings','ChangePasswordDialog requirement'),
('german','settings.pwd_req_number','Enthält Zahl','settings','ChangePasswordDialog requirement'),
('german','settings.pwd_req_match','Passwörter stimmen überein','settings','ChangePasswordDialog requirement'),

-- Kurdish Sorani
('kurdish_sorani','reg.setup_credentials','زانیاری چوونەژوورەوەی پارێزراوت دابنێ','auth','DynamicRegistrationStepRenderer subtitle'),
('kurdish_sorani','reg.tell_us_about_yourself','دەربارەی خۆت پێمان بڵێ','auth','DynamicRegistrationStepRenderer step 2 title'),
('kurdish_sorani','reg.basic_info','زانیاری بنەڕەتی بۆ دروستکردنی پرۆفایلت','auth','DynamicRegistrationStepRenderer step 2 subtitle'),
('kurdish_sorani','reg.where_are_you_from','لەکوێیت؟','auth','DynamicRegistrationStepRenderer step 3 subtitle'),
('kurdish_sorani','reg.current_location','شوێنی ئێستا','auth','DynamicRegistrationStepRenderer label'),
('kurdish_sorani','reg.detecting_location','دۆزینەوەی شوێن...','auth','DynamicRegistrationStepRenderer placeholder'),
('kurdish_sorani','reg.enter_your_city','شارەکەت بنووسە','auth','DynamicRegistrationStepRenderer placeholder'),
('kurdish_sorani','reg.add_photos','وێنە زیاد بکە','auth','DynamicRegistrationStepRenderer step 4 title'),
('kurdish_sorani','reg.show_your_best_self','باشترین لای خۆت پیشان بدە','auth','DynamicRegistrationStepRenderer step 4 subtitle'),
('kurdish_sorani','settings.pwd_req_min_chars','لانیکەم ٨ پیت','settings','ChangePasswordDialog requirement'),
('kurdish_sorani','settings.pwd_req_uppercase','پیتی گەورە لەخۆ دەگرێت','settings','ChangePasswordDialog requirement'),
('kurdish_sorani','settings.pwd_req_lowercase','پیتی بچووک لەخۆ دەگرێت','settings','ChangePasswordDialog requirement'),
('kurdish_sorani','settings.pwd_req_number','ژمارە لەخۆ دەگرێت','settings','ChangePasswordDialog requirement'),
('kurdish_sorani','settings.pwd_req_match','وشەی نهێنییەکان یەکدەگرن','settings','ChangePasswordDialog requirement'),

-- Kurdish Kurmanji
('kurdish_kurmanji','reg.setup_credentials','Agahiyên xwe yên têketinê yên ewle saz bikin','auth','DynamicRegistrationStepRenderer subtitle'),
('kurdish_kurmanji','reg.tell_us_about_yourself','Der barê xwe de ji me re bêje','auth','DynamicRegistrationStepRenderer step 2 title'),
('kurdish_kurmanji','reg.basic_info','Agahiyên bingehîn ji bo afirandina profîla te','auth','DynamicRegistrationStepRenderer step 2 subtitle'),
('kurdish_kurmanji','reg.where_are_you_from','Tu ji ku derê yî?','auth','DynamicRegistrationStepRenderer step 3 subtitle'),
('kurdish_kurmanji','reg.current_location','Cihê niha','auth','DynamicRegistrationStepRenderer label'),
('kurdish_kurmanji','reg.detecting_location','Cih tê dîtin...','auth','DynamicRegistrationStepRenderer placeholder'),
('kurdish_kurmanji','reg.enter_your_city','Bajarê xwe binivîse','auth','DynamicRegistrationStepRenderer placeholder'),
('kurdish_kurmanji','reg.add_photos','Wêneyan zêde bike','auth','DynamicRegistrationStepRenderer step 4 title'),
('kurdish_kurmanji','reg.show_your_best_self','Aliyê xwe yê çêtirîn nîşan bide','auth','DynamicRegistrationStepRenderer step 4 subtitle'),
('kurdish_kurmanji','settings.pwd_req_min_chars','Herî kêm 8 tîp','settings','ChangePasswordDialog requirement'),
('kurdish_kurmanji','settings.pwd_req_uppercase','Tîpên mezin dihewîne','settings','ChangePasswordDialog requirement'),
('kurdish_kurmanji','settings.pwd_req_lowercase','Tîpên biçûk dihewîne','settings','ChangePasswordDialog requirement'),
('kurdish_kurmanji','settings.pwd_req_number','Hejmaran dihewîne','settings','ChangePasswordDialog requirement'),
('kurdish_kurmanji','settings.pwd_req_match','Şîfre hev digirin','settings','ChangePasswordDialog requirement')
ON CONFLICT (language_code, translation_key) DO UPDATE SET translation_value = EXCLUDED.translation_value;
