
INSERT INTO public.app_translations (language_code, translation_key, translation_value, category, context) VALUES
('english','admin.feature_disabled','Feature Disabled','admin','GenerateProfilesForm toast'),
('english','admin.profile_gen_disabled','Profile generation has been disabled. This system now only works with real users who register through the app.','admin','GenerateProfilesForm toast'),
('english','admin.information','Information','admin','GenerateProfilesForm toast'),
('english','admin.profile_gen_unavailable','Profile generation is no longer available in real data mode.','admin','GenerateProfilesForm toast'),
('english','admin.real_users_only_title','Real Users Only','admin','GenerateProfilesForm alert'),
('english','admin.real_users_only_desc','This application now only supports real users who register through the normal registration process. Profile generation features have been disabled to ensure data authenticity.','admin','GenerateProfilesForm alert'),
('english','admin.how_to_add_users_title','How to Add Users','admin','GenerateProfilesForm alert'),
('english','admin.how_to_add_users_desc','To see users in this admin panel, they need to register through your app''s registration flow at /register.','admin','GenerateProfilesForm alert'),
('english','admin.processing','Processing...','admin','GenerateProfilesForm button'),
('english','admin.close','Close','admin','GenerateProfilesForm button'),
('english','admin.real_data_mode','Real Data Mode','admin','UpdateProfilesForm alert'),
('english','admin.real_data_mode_desc','This application now operates in real data mode. Only actual user profiles from real registrations are shown.','admin','UpdateProfilesForm alert'),
('english','admin.user_profile_mgmt','User Profile Management','admin','UpdateProfilesForm alert'),
('english','admin.user_profile_mgmt_desc','To manage user profiles, users must update their own profiles through the regular app interface.','admin','UpdateProfilesForm alert'),
('english','admin.profile_updating_disabled','Profile updating has been disabled. This system now only works with real user data.','admin','UpdateProfilesForm toast'),
('english','admin.profile_updating_unavailable','Profile updating is no longer available in real data mode.','admin','UpdateProfilesForm toast'),
('english','admin.placeholder_role_name','e.g., Content Manager','admin','NewRoleDialog placeholder'),
('english','admin.placeholder_role_desc','Describe the purpose of this role','admin','NewRoleDialog placeholder'),
('english','admin.support_agent','Support Agent','admin','NewRoleDialog option'),
('english','admin.marketing','Marketing','admin','NewRoleDialog option'),
('english','admin.test_data_removed','All test data has been removed. Only real users will be shown.','admin','AddUserDialog toast'),
('english','admin.cleanup_error','An error occurred during cleanup','admin','AddUserDialog toast'),
('english','admin.provider_updated','{{provider}} provider updated','admin','SocialLoginPage toast'),
('english','admin.provider_update_failed','Failed to update provider: {{error}}','admin','SocialLoginPage toast'),
('english','toast.profile_passed','Profile passed','discovery','LikedMe'),
('english','support.validation_error','Validation Error','support','ContactSupportDialog toast'),
('english','support.fix_form_errors','Please fix the errors in the form','support','ContactSupportDialog toast'),
('english','support.message_sent','Message Sent','support','ContactSupportDialog toast'),
('english','support.reply_within_24h','We''ll get back to you within 24 hours','support','ContactSupportDialog toast'),
('english','support.send_failed','Failed to send message. Please try again.','support','ContactSupportDialog toast'),
('english','support.contact_support','Contact Support','support','ContactSupportDialog title'),
('english','support.send_us_message','Send us a message and we''ll respond within 24 hours','support','ContactSupportDialog desc'),
('english','support.cancel','Cancel','support','ContactSupportDialog button'),
('english','support.send_message','Send Message','support','ContactSupportDialog button'),
('english','support.thank_you','Thank you!','support','MyTickets toast'),
('english','support.feedback_helps','Your feedback helps us improve our support.','support','MyTickets toast'),
('english','support.feedback_failed','Failed to submit feedback. Please try again.','support','MyTickets toast'),
('english','support.my_tickets','My Support Tickets','support','MyTickets title'),
('english','support.track_requests','Track your support requests','support','MyTickets desc'),
('english','support.no_tickets','No support tickets yet','support','MyTickets empty'),
('english','support.contact_if_help','Contact support if you need help','support','MyTickets empty'),
('english','support.login_to_view','Please log in to view your support tickets','support','MyTickets auth'),
('english','profile.unfollowed','Unfollowed','profile','ProfileActionButtons'),
('english','profile.following','Following','profile','ProfileActionButtons'),
('english','profile.you_unfollowed','You unfollowed {{name}}','profile','ProfileActionButtons'),
('english','profile.now_following','You are now following {{name}}','profile','ProfileActionButtons'),
('english','profile.checkout_failed','Failed to start checkout','profile','ProfileActionButtons'),
('english','chat.rate_limit','Rate limit reached','chat','MessageTranslation'),
('english','chat.rate_limit_desc','Please wait a moment before translating again.','chat','MessageTranslation'),
('english','chat.service_unavailable','Service unavailable','chat','MessageTranslation'),
('english','chat.service_unavailable_desc','Translation credits need to be added.','chat','MessageTranslation'),
('english','chat.translation_complete','Translation complete','chat','MessageTranslation'),
('english','chat.translated_to','Translated to {{language}}','chat','MessageTranslation'),
('english','chat.translation_failed','Translation failed','chat','MessageTranslation'),
('english','chat.translation_failed_desc','Unable to translate message. Please try again.','chat','MessageTranslation'),
('english','photo.feature_migration','Feature Migration in Progress','shared','AIPhotoStudioDialog'),
('english','photo.bg_removal_migration','Background removal is being migrated to our new AI infrastructure. Check back soon!','shared','AIPhotoStudioDialog'),
('english','photo.premium_feature','{{tool}} is a premium feature','shared','AIPhotoStudioDialog'),
('english','photo.coming_soon','This functionality is coming soon!','shared','AIPhotoStudioDialog'),
('english','photo.ai_enhancement','AI Photo Enhancement','shared','AIPhotoStudioDialog'),
('english','photo.enhancing','Enhancing your photo with AI to get more matches...','shared','AIPhotoStudioDialog'),
('english','photo.enhanced','Photo Enhanced!','shared','AIPhotoStudioDialog'),
('english','photo.enhanced_desc','Your photo has been enhanced with AI for better match potential.','shared','AIPhotoStudioDialog'),
('english','photo.enhancement_failed','Enhancement Failed','shared','AIPhotoStudioDialog'),
('english','photo.enhancement_failed_desc','AI photo enhancement is a premium feature. Upgrade to access!','shared','AIPhotoStudioDialog'),
('english','photo.ai_studio','AI Photo Studio','shared','AIPhotoStudioDialog'),
('english','photo.ai_tools','AI Editing Tools','shared','AIPhotoStudioDialog'),
('english','photo.save','Save Photo','shared','AIPhotoStudioDialog'),
('english','photo.ai_working','AI is working its magic...','shared','AIPhotoStudioDialog'),
('english','verification.error_title','Error','verification','VerificationForm'),
('english','verification.success_title','Success','verification','VerificationForm'),
('english','phone.code_sent','Code Sent','phone','usePhoneVerification'),
('english','phone.code_sent_desc','Verification code has been sent to your phone','phone','usePhoneVerification'),
('english','phone.send_failed','Failed to send verification code','phone','usePhoneVerification'),
('english','phone.verified','Verified!','phone','usePhoneVerification'),
('english','phone.verified_desc','Your phone number has been verified successfully','phone','usePhoneVerification'),
('english','phone.invalid_code','Invalid verification code','phone','usePhoneVerification'),
('english','subscription.check_failed','Failed to check subscription status','subscription','useSubscription'),
('english','subscription.checkout_failed','Failed to start checkout process','subscription','useSubscription'),
('english','subscription.portal_failed','Failed to open subscription management','subscription','useSubscription'),
('english','form.too_many_attempts','Too Many Attempts','form','useSecureForm'),
('english','form.wait_before_retry','Please wait before trying again.','form','useSecureForm'),
('english','form.success','Success','form','useSecureForm'),
('english','form.submitted','Form submitted successfully','form','useSecureForm'),
('english','form.validation_error','Validation Error','form','useSecureForm'),
('english','form.check_errors','Please check the form for errors','form','useSecureForm'),
('english','form.submission_error','Submission Error','form','useSecureForm'),
('english','push.not_supported','Not Supported','push','usePushNotifications'),
('english','push.not_supported_desc','Push notifications are not supported in your browser','push','usePushNotifications'),
('english','push.permission_denied','Permission Denied','push','usePushNotifications'),
('english','push.permission_denied_desc','Please enable notifications in your browser settings','push','usePushNotifications'),
('english','push.enabled','Push notifications enabled successfully','push','usePushNotifications'),
('english','push.enable_failed','Failed to enable push notifications','push','usePushNotifications'),
('english','push.disabled','Push notifications disabled','push','usePushNotifications'),
('english','push.disable_failed','Failed to disable push notifications','push','usePushNotifications'),
('english','location.not_supported','Geolocation not supported','location','useLocationManager'),
('english','location.not_supported_desc','Your browser does not support geolocation services.','location','useLocationManager'),
('english','location.updated','Location updated','location','useLocationManager'),
('english','location.current_set','Your current location has been set.','location','useLocationManager'),
('english','location.error','Location error','location','useLocationManager'),
('english','location.error_desc','Could not determine your location. Please try again.','location','useLocationManager'),
('english','location.manual_set','Your location has been manually set to {{location}}','location','useLocationManager'),
('english','location.passport_set','Passport location set','location','useLocationManager'),
('english','location.passport_cleared','Passport location cleared','location','useLocationManager'),
('english','location.browsing_from','You are now browsing from {{location}}','location','useLocationManager'),
('english','location.travel_deactivated','Travel mode deactivated','location','useLocationManager'),
('english','location.passport_removed','Passport location removed','location','PassportLocationDisplay'),
('english','location.passport_reset','Your passport location has been reset.','location','PassportLocationDisplay'),
('english','location.no_passport','No passport location set','location','PassportLocationDisplay'),
('english','location.virtual_desc','Virtual location for exploring matches in other cities worldwide.','location','PassportLocationDisplay'),
('english','location.search_error','Search error','location','LocationSearch'),
('english','location.search_error_desc','Could not search for locations. Please try again.','location','LocationSearch'),
('english','location.searching','Searching locations...','location','LocationSearch'),
('english','insights.generated','Insights generated','chat','useConversationInsights'),
('english','insights.generated_desc','AI has analyzed your conversation patterns','chat','useConversationInsights'),
('english','insights.failed','Failed to generate insights','chat','useConversationInsights'),
('english','insights.failed_desc','Unable to analyze conversation at this time','chat','useConversationInsights'),
('english','verification.load_failed','Failed to load verification requests','verification','useVerificationData'),
('english','verification.action_success','User {{action}} successfully','verification','useVerificationData'),
('english','verification.action_failed','Failed to {{action}} user','verification','useVerificationData'),
('english','nearby.load_failed','Failed to load nearby users','nearby','useNearbyUsers'),
('english','nearby.try_later','Please try again later','nearby','useNearbyUsers'),
('english','auth.welcome_back','Welcome back!','auth','useOAuthCallback'),
('english','auth.redirect_admin','Redirecting to super admin dashboard...','auth','useOAuthCallback'),
('english','auth.redirect_discovery','Redirecting to discovery...','auth','useOAuthCallback'),
('english','auth.welcome','Welcome!','auth','useOAuthCallback'),
('english','auth.complete_profile','Let''s complete your profile to get started...','auth','useOAuthCallback'),
('english','auth.auth_failed','Authentication failed','auth','useOAuthCallback'),
('english','auth.try_login_again','Please try logging in again.','auth','useOAuthCallback'),
('english','auth.admin_ready','Admin Account Ready','auth','useSetupManager'),
('english','auth.admin_verified','Super admin account has been verified successfully.','auth','useSetupManager'),
('english','auth.setup_delayed','Setup Delayed','auth','useSetupManager'),
('english','auth.setup_issue','Setup Issue','auth','useSetupManager'),
('english','auth.setup_error','Setup Error','auth','useSetupManager'),
('english','auth.retry_failed','Retry Failed','auth','useSetupManager'),
('english','auth.cache_cleared','Cache Cleared','auth','useSetupManager'),
('english','auth.cache_cleared_desc','Setup cache has been cleared. You can now retry the setup.','auth','useSetupManager'),
('english','auth.resuming_registration','Resuming your registration from {{time}} minute(s) ago.','auth','useRegistrationFormLogic'),
('english','auth.unable_verify_email','Unable to verify email','auth','useRegistrationFormLogic'),
('english','auth.check_connection','Please check your connection and try again.','auth','useRegistrationFormLogic'),
('english','auth.email_registered','Email Already Registered','auth','useRegistrationFormLogic'),
('english','auth.use_different_email','Please use a different email or sign in to your existing account.','auth','useRegistrationFormLogic'),
('english','auth.photo_warning','Photo Upload Warning','auth','useRegistrationFormLogic'),
('english','auth.photos_failed','{{count}} photo(s) failed to upload. Your profile was still created successfully.','auth','useRegistrationFormLogic'),
('english','auth.photo_storage_error','Photo Storage Error','auth','useRegistrationFormLogic'),
('english','auth.photos_save_failed','Photos uploaded but failed to save to database','auth','useRegistrationFormLogic'),
('english','auth.account_created','Your account has been created. Please check your email to verify your account.','auth','useRegistrationFormLogic'),
('english','auth.create_failed','Failed to create account. Please try again.','auth','useRegistrationFormLogic'),
('english','auth.profile_complete','Profile Complete!','auth','useRegistrationForm'),
('english','auth.profile_completed_desc','Your profile has been completed successfully.','auth','useRegistrationForm'),
('english','auth.verify_email','Your account has been created. Please check your email to verify your account before logging in.','auth','useRegistrationForm'),
('english','auth.incomplete_reg','Incomplete Registration','auth','EnhancedDynamicRegistrationForm'),
('english','auth.complete_step','Please complete "{{step}}" step before submitting.','auth','EnhancedDynamicRegistrationForm'),
('english','auth.fix_errors','Please fix errors in: {{fields}}','auth','EnhancedDynamicRegistrationForm'),
('english','auth.reg_form_error','Failed to load registration form. Please refresh the page.','auth','useDynamicRegistrationForm'),
('english','auth.incomplete_fields','Incomplete Fields','auth','useDynamicRegistrationForm'),
('english','auth.complete_required','Please complete all required fields: {{fields}}','auth','useDynamicRegistrationForm'),
('english','auth.reg_failed','Registration Failed','auth','useDynamicRegistrationForm'),
('english','auth.profile_creation_failed','Profile Creation Failed','auth','useDynamicRegistrationForm'),
('english','auth.profile_setup_failed','Your account was created but profile setup failed. Please complete your profile.','auth','useDynamicRegistrationForm'),
('english','auth.reg_successful','Registration Successful!','auth','useDynamicRegistrationForm'),
('english','auth.welcome_kurdmatch','Welcome to KurdMatch! Your profile has been created.','auth','useDynamicRegistrationForm'),
('english','auth.photo_upload_warning','Some photos could not be uploaded. You can add them later.','auth','useDynamicRegistrationForm'),
('english','auth.strong_password','Strong password generated','auth','SuperAdminSetupForm'),
('english','auth.save_password','Make sure to copy and save this password securely.','auth','SuperAdminSetupForm'),
('english','auth.copied','Copied to clipboard','auth','SuperAdminSetupForm'),
('english','auth.copied_desc','{{type}} copied successfully.','auth','SuperAdminSetupForm'),
('english','auth.copy_failed','Copy failed','auth','SuperAdminSetupForm'),
('english','auth.copy_manual','Please copy the text manually.','auth','SuperAdminSetupForm'),
('english','wizard.about_you','About You','wizard','ProfileCompletionWizard'),
('english','wizard.your_lifestyle','Your Lifestyle','wizard','ProfileCompletionWizard'),
('english','wizard.values_beliefs','Values & Beliefs','wizard','ProfileCompletionWizard'),
('english','wizard.relationships_family','Relationships & Family','wizard','ProfileCompletionWizard'),
('english','wizard.career_education','Career & Education','wizard','ProfileCompletionWizard'),
('english','wizard.interests_hobbies','Interests & Hobbies','wizard','ProfileCompletionWizard'),
('english','wizard.your_favorites','Your Favorites','wizard','ProfileCompletionWizard'),
('english','wizard.final_touches','Final Touches','wizard','ProfileCompletionWizard'),
('english','wizard.profile_completed','Profile completed!','wizard','ProfileCompletionWizard'),
('english','wizard.all_set','You are all set to start discovering amazing people!','wizard','ProfileCompletionWizard'),
('english','wizard.save_failed','Failed to save your profile. Please try again.','wizard','ProfileCompletionWizard')
ON CONFLICT (language_code, translation_key) DO NOTHING;

INSERT INTO public.app_translations (language_code, translation_key, translation_value, category) VALUES
('norwegian','admin.feature_disabled','Funksjon deaktivert','admin'),
('norwegian','admin.close','Lukk','admin'),
('norwegian','admin.processing','Behandler...','admin'),
('norwegian','admin.test_data_removed','Alle testdata er fjernet.','admin'),
('norwegian','admin.cleanup_error','En feil oppstod under opprydding','admin'),
('norwegian','admin.provider_updated','{{provider}}-leverandor oppdatert','admin'),
('norwegian','toast.profile_passed','Profil passert','discovery'),
('norwegian','support.validation_error','Valideringsfeil','support'),
('norwegian','support.message_sent','Melding sendt','support'),
('norwegian','support.send_failed','Kunne ikke sende melding.','support'),
('norwegian','support.contact_support','Kontakt support','support'),
('norwegian','support.cancel','Avbryt','support'),
('norwegian','support.send_message','Send melding','support'),
('norwegian','support.thank_you','Takk!','support'),
('norwegian','support.feedback_failed','Kunne ikke sende tilbakemelding.','support'),
('norwegian','support.my_tickets','Mine supportsaker','support'),
('norwegian','support.no_tickets','Ingen supportsaker enda','support'),
('norwegian','support.login_to_view','Logg inn for a se supportsaker','support'),
('norwegian','profile.unfollowed','Sluttet a folge','profile'),
('norwegian','profile.following','Folger','profile'),
('norwegian','profile.checkout_failed','Kunne ikke starte betaling','profile'),
('norwegian','chat.rate_limit','Hastighetsbegrensning nadd','chat'),
('norwegian','chat.translation_complete','Oversettelse fullfort','chat'),
('norwegian','chat.translation_failed','Oversettelse mislyktes','chat'),
('norwegian','photo.ai_studio','AI Fotostudio','shared'),
('norwegian','photo.save','Lagre bilde','shared'),
('norwegian','verification.error_title','Feil','verification'),
('norwegian','verification.success_title','Suksess','verification'),
('norwegian','phone.code_sent','Kode sendt','phone'),
('norwegian','phone.verified','Verifisert!','phone'),
('norwegian','form.success','Suksess','form'),
('norwegian','form.validation_error','Valideringsfeil','form'),
('norwegian','push.not_supported','Ikke stottet','push'),
('norwegian','push.permission_denied','Tillatelse nektet','push'),
('norwegian','location.updated','Plassering oppdatert','location'),
('norwegian','location.error','Plasseringsfeil','location'),
('norwegian','location.passport_removed','Passplassering fjernet','location'),
('norwegian','location.search_error','Sokefeil','location'),
('norwegian','insights.generated','Innsikt generert','chat'),
('norwegian','insights.failed','Kunne ikke generere innsikt','chat'),
('norwegian','nearby.load_failed','Kunne ikke laste brukere i nerheten','nearby'),
('norwegian','auth.welcome_back','Velkommen tilbake!','auth'),
('norwegian','auth.welcome','Velkommen!','auth'),
('norwegian','auth.auth_failed','Autentisering mislyktes','auth'),
('norwegian','auth.admin_ready','Adminkonto klar','auth'),
('norwegian','auth.reg_failed','Registrering mislyktes','auth'),
('norwegian','auth.reg_successful','Registrering vellykket!','auth'),
('norwegian','auth.copied','Kopiert til utklippstavle','auth'),
('norwegian','auth.copy_failed','Kopiering mislyktes','auth'),
('norwegian','wizard.about_you','Om deg','wizard'),
('norwegian','wizard.your_lifestyle','Din livsstil','wizard'),
('norwegian','wizard.values_beliefs','Verdier og tro','wizard'),
('norwegian','wizard.profile_completed','Profil fullfort!','wizard'),
('norwegian','wizard.save_failed','Kunne ikke lagre profilen din.','wizard'),
('german','admin.feature_disabled','Funktion deaktiviert','admin'),
('german','admin.close','Schliessen','admin'),
('german','admin.processing','Verarbeitung...','admin'),
('german','admin.test_data_removed','Alle Testdaten wurden entfernt.','admin'),
('german','admin.cleanup_error','Fehler bei der Bereinigung','admin'),
('german','german.provider_updated','{{provider}}-Anbieter aktualisiert','admin'),
('german','toast.profile_passed','Profil uebergangen','discovery'),
('german','support.validation_error','Validierungsfehler','support'),
('german','support.message_sent','Nachricht gesendet','support'),
('german','support.contact_support','Support kontaktieren','support'),
('german','support.cancel','Abbrechen','support'),
('german','support.send_message','Nachricht senden','support'),
('german','support.thank_you','Danke!','support'),
('german','support.my_tickets','Meine Support-Tickets','support'),
('german','profile.unfollowed','Entfolgt','profile'),
('german','profile.following','Folge ich','profile'),
('german','chat.translation_complete','Uebersetzung abgeschlossen','chat'),
('german','chat.translation_failed','Uebersetzung fehlgeschlagen','chat'),
('german','photo.ai_studio','AI Fotostudio','shared'),
('german','photo.save','Foto speichern','shared'),
('german','verification.error_title','Fehler','verification'),
('german','verification.success_title','Erfolg','verification'),
('german','phone.code_sent','Code gesendet','phone'),
('german','phone.verified','Verifiziert!','phone'),
('german','form.success','Erfolg','form'),
('german','form.validation_error','Validierungsfehler','form'),
('german','location.updated','Standort aktualisiert','location'),
('german','location.error','Standortfehler','location'),
('german','auth.welcome_back','Willkommen zurueck!','auth'),
('german','auth.welcome','Willkommen!','auth'),
('german','auth.auth_failed','Authentifizierung fehlgeschlagen','auth'),
('german','auth.reg_successful','Registrierung erfolgreich!','auth'),
('german','wizard.about_you','Ueber dich','wizard'),
('german','wizard.profile_completed','Profil vervollstaendigt!','wizard'),
('german','wizard.save_failed','Profil konnte nicht gespeichert werden.','wizard'),
('kurdish_sorani','admin.feature_disabled','تایبەتمەندی ناچالاک کرا','admin'),
('kurdish_sorani','admin.close','داخستن','admin'),
('kurdish_sorani','admin.test_data_removed','هەموو داتای تاقیکاری لابرا.','admin'),
('kurdish_sorani','toast.profile_passed','پرۆفایل تێپەڕێندرا','discovery'),
('kurdish_sorani','support.message_sent','نامە نێردرا','support'),
('kurdish_sorani','support.contact_support','پەیوەندی بە پشتگیری','support'),
('kurdish_sorani','support.thank_you','سوپاس!','support'),
('kurdish_sorani','support.my_tickets','تیکەتەکانم','support'),
('kurdish_sorani','chat.translation_complete','وەرگێڕان تەواو بوو','chat'),
('kurdish_sorani','phone.code_sent','کۆد نێردرا','phone'),
('kurdish_sorani','phone.verified','پشتڕاستکراوەتەوە!','phone'),
('kurdish_sorani','form.success','سەرکەوتوو','form'),
('kurdish_sorani','location.updated','شوێن نوێکرایەوە','location'),
('kurdish_sorani','auth.welcome_back','بەخێربێیتەوە!','auth'),
('kurdish_sorani','auth.reg_successful','تۆمارکردن سەرکەوتوو بوو!','auth'),
('kurdish_sorani','wizard.about_you','دەربارەی تۆ','wizard'),
('kurdish_sorani','wizard.profile_completed','پرۆفایل تەواو بوو!','wizard'),
('kurdish_sorani','verification.error_title','هەڵە','verification'),
('kurdish_sorani','verification.success_title','سەرکەوتوو','verification'),
('kurdish_kurmanji','admin.feature_disabled','Taybetmendi necalak kirin','admin'),
('kurdish_kurmanji','admin.close','Bigire','admin'),
('kurdish_kurmanji','admin.test_data_removed','Hemu daneyen teste hatin rakirin.','admin'),
('kurdish_kurmanji','toast.profile_passed','Profil derbas bu','discovery'),
('kurdish_kurmanji','support.message_sent','Peyam hat shandin','support'),
('kurdish_kurmanji','support.contact_support','Bi pishtgiriye re tekili','support'),
('kurdish_kurmanji','support.thank_you','Spas!','support'),
('kurdish_kurmanji','support.my_tickets','Tiketen min','support'),
('kurdish_kurmanji','chat.translation_complete','Werger qediya','chat'),
('kurdish_kurmanji','phone.code_sent','Kod hat shandin','phone'),
('kurdish_kurmanji','phone.verified','Hat pishtrastkirin!','phone'),
('kurdish_kurmanji','form.success','Serketi','form'),
('kurdish_kurmanji','location.updated','Cih hat nukirin','location'),
('kurdish_kurmanji','auth.welcome_back','Bi xer hati!','auth'),
('kurdish_kurmanji','auth.reg_successful','Tomarkirin bi ser ket!','auth'),
('kurdish_kurmanji','wizard.about_you','Derbare te','wizard'),
('kurdish_kurmanji','wizard.profile_completed','Profil qediya!','wizard'),
('kurdish_kurmanji','verification.error_title','Xeleti','verification'),
('kurdish_kurmanji','verification.success_title','Serketi','verification')
ON CONFLICT (language_code, translation_key) DO NOTHING;
