
-- Batch 8: Translations for SystemHealth, Categories, Exports, ABTesting, AIInsights, Analytics, EmailCampaigns, AuditLogs, BulkActions, ApiKeys pages
INSERT INTO public.app_translations (language_code, translation_key, translation_value, category) VALUES
-- SystemHealth
('english', 'admin.system_health', 'System Health', 'admin'),
('english', 'admin.select_time_range', 'Select time range', 'admin'),
('english', 'admin.last_hour', 'Last hour', 'admin'),
('english', 'admin.last_24_hours', 'Last 24 hours', 'admin'),
('english', 'admin.last_7_days', 'Last 7 days', 'admin'),
('english', 'admin.last_30_days', 'Last 30 days', 'admin'),
('english', 'admin.alerts', 'Alerts', 'admin'),
('english', 'admin.overall_system', 'Overall System', 'admin'),
('english', 'admin.active_users', 'Active Users', 'admin'),
('english', 'admin.database_records', 'Database Records', 'admin'),
('english', 'admin.ai_system_monitoring', 'AI-Powered System Monitoring', 'admin'),
('english', 'admin.ai_system_monitoring_desc', 'Real-time metrics collection via edge functions every 5 minutes', 'admin'),
('english', 'admin.overview', 'Overview', 'admin'),
('english', 'admin.api_performance', 'API Performance', 'admin'),
('english', 'admin.system_resources', 'System Resources', 'admin'),
('english', 'admin.incidents', 'Incidents', 'admin'),
('english', 'admin.response_time_error_rate', 'Response time and error rate over time', 'admin'),
('english', 'admin.current_resource_usage', 'Current resource usage across systems', 'admin'),
('english', 'admin.system', 'System', 'admin'),
('english', 'admin.status', 'Status', 'admin'),
('english', 'admin.cpu', 'CPU', 'admin'),
('english', 'admin.memory', 'Memory', 'admin'),
('english', 'admin.disk', 'Disk', 'admin'),
('english', 'admin.recent_incidents', 'Recent Incidents', 'admin'),
('english', 'admin.incidents_status', 'System incidents and their status', 'admin'),
('english', 'admin.view_details', 'View Details', 'admin'),
('english', 'admin.no_metrics', 'No Metrics Available', 'admin'),
('english', 'admin.metrics_collected_auto', 'System metrics are collected automatically every 5 minutes via the edge function.', 'admin'),
('english', 'admin.waiting_first_metric', 'Waiting for first metric collection...', 'admin'),
('english', 'admin.api_performance_details', 'API Performance Details', 'admin'),
('english', 'admin.detailed_api_metrics', 'Detailed API performance metrics and logs', 'admin'),
('english', 'admin.system_resources_details', 'System Resources Details', 'admin'),
('english', 'admin.detailed_resource_metrics', 'Detailed system resource metrics', 'admin'),
('english', 'admin.incident_history', 'Incident History', 'admin'),
('english', 'admin.complete_incident_history', 'Complete incident history and resolutions', 'admin'),
('english', 'admin.healthy', 'Healthy', 'admin'),
('english', 'admin.warning', 'Warning', 'admin'),
('english', 'admin.critical', 'Critical', 'admin'),
('english', 'admin.investigating', 'Investigating', 'admin'),
('english', 'admin.resolved', 'Resolved', 'admin'),

-- Exports
('english', 'admin.data_exports', 'Data Exports', 'admin'),
('english', 'admin.refresh', 'Refresh', 'admin'),
('english', 'admin.refreshing', 'Refreshing...', 'admin'),
('english', 'admin.new_export', 'New Export', 'admin'),
('english', 'admin.ai_enhanced_exports', 'AI-Enhanced Data Exports', 'admin'),
('english', 'admin.ai_enhanced_exports_desc', 'Our AI system can automatically schedule reports, detect patterns, and format data for optimal analysis', 'admin'),
('english', 'admin.recent_exports', 'Recent Exports', 'admin'),
('english', 'admin.scheduled', 'Scheduled', 'admin'),
('english', 'admin.export_templates', 'Export Templates', 'admin'),
('english', 'admin.search_exports', 'Search exports...', 'admin'),
('english', 'admin.filter_by_type', 'Filter by type', 'admin'),
('english', 'admin.all_types', 'All Types', 'admin'),
('english', 'admin.export_name', 'Export Name', 'admin'),
('english', 'admin.format', 'Format', 'admin'),
('english', 'admin.date_requested', 'Date Requested', 'admin'),
('english', 'admin.records', 'Records', 'admin'),
('english', 'admin.size', 'Size', 'admin'),
('english', 'admin.actions', 'Actions', 'admin'),
('english', 'admin.download', 'Download', 'admin'),
('english', 'admin.retry', 'Retry', 'admin'),
('english', 'admin.processing', 'Processing...', 'admin'),
('english', 'admin.completed', 'Completed', 'admin'),
('english', 'admin.no_exports_found', 'No exports found', 'admin'),
('english', 'admin.new_data_export', 'New Data Export', 'admin'),
('english', 'admin.configure_export', 'Configure and create a new data export job.', 'admin'),
('english', 'admin.data_type', 'Data Type', 'admin'),
('english', 'admin.date_range', 'Date Range', 'admin'),
('english', 'admin.from', 'From', 'admin'),
('english', 'admin.to', 'To', 'admin'),
('english', 'admin.file_format', 'File Format', 'admin'),
('english', 'admin.export_options', 'Export Options', 'admin'),
('english', 'admin.include_headers', 'Include column headers', 'admin'),
('english', 'admin.anonymize_data', 'Anonymize sensitive data', 'admin'),
('english', 'admin.include_metadata', 'Include metadata', 'admin'),
('english', 'admin.scheduling', 'Scheduling', 'admin'),
('english', 'admin.export_now', 'Export Now', 'admin'),
('english', 'admin.schedule_later', 'Schedule for Later', 'admin'),
('english', 'admin.set_recurring', 'Set as Recurring', 'admin'),
('english', 'admin.cancel', 'Cancel', 'admin'),
('english', 'admin.create_export', 'Create Export', 'admin'),
('english', 'admin.scheduled_exports', 'Scheduled Exports', 'admin'),
('english', 'admin.scheduled_exports_desc', 'Exports scheduled for future execution', 'admin'),
('english', 'admin.reusable_configs', 'Reusable export configurations', 'admin'),

-- ABTesting
('english', 'admin.ab_testing', 'A/B Testing', 'admin'),
('english', 'admin.new_test', 'New Test', 'admin'),
('english', 'admin.ai_test_analysis', 'AI-Powered Test Analysis', 'admin'),
('english', 'admin.ai_test_analysis_desc', 'Our AI continuously analyzes test results and provides insights to help optimize your decisions', 'admin'),
('english', 'admin.all_tests', 'All Tests', 'admin'),
('english', 'admin.active', 'Active', 'admin'),
('english', 'admin.draft', 'Draft', 'admin'),
('english', 'admin.test_name', 'Test Name', 'admin'),
('english', 'admin.target', 'Target', 'admin'),
('english', 'admin.improvement', 'Improvement', 'admin'),
('english', 'admin.duration', 'Duration', 'admin'),
('english', 'admin.stop', 'Stop', 'admin'),
('english', 'admin.start', 'Start', 'admin'),
('english', 'admin.not_started', 'Not started', 'admin'),
('english', 'admin.duplicate', 'Duplicate', 'admin'),
('english', 'admin.edit', 'Edit', 'admin'),
('english', 'admin.target_audience', 'Target Audience', 'admin'),
('english', 'admin.performance_metrics', 'Performance Metrics', 'admin'),
('english', 'admin.ai_analysis', 'AI Analysis', 'admin'),
('english', 'admin.stop_test', 'Stop Test', 'admin'),
('english', 'admin.active_tests', 'Active Tests', 'admin'),
('english', 'admin.currently_running', 'Currently running tests', 'admin'),
('english', 'admin.completed_tests', 'Completed Tests', 'admin'),
('english', 'admin.finished_with_results', 'Finished tests with results', 'admin'),
('english', 'admin.draft_tests', 'Draft Tests', 'admin'),
('english', 'admin.tests_preparation', 'Tests in preparation', 'admin'),
('english', 'admin.create_ab_test', 'Create New A/B Test', 'admin'),
('english', 'admin.setup_test_desc', 'Set up a new test to compare variations and measure their performance.', 'admin'),

-- AIInsights
('english', 'admin.ai_insights', 'AI Conversation Insights', 'admin'),
('english', 'admin.ai_insights_desc', 'View AI-generated conversation analysis', 'admin'),
('english', 'admin.all_ai_insights', 'All AI Insights', 'admin'),
('english', 'admin.search_insights', 'Search insights...', 'admin'),
('english', 'admin.loading_insights', 'Loading AI insights...', 'admin'),
('english', 'admin.no_insights_found', 'No AI insights found', 'admin'),
('english', 'admin.communication_style', 'Communication Style', 'admin'),
('english', 'admin.shared_interests', 'Shared Interests', 'admin'),
('english', 'admin.suggested_topics', 'Suggested Topics', 'admin'),

-- Analytics
('english', 'admin.advanced_analytics', 'Advanced Analytics', 'admin'),
('english', 'admin.realtime_insights', 'Real-time insights from your platform', 'admin'),
('english', 'admin.export', 'Export', 'admin'),
('english', 'admin.ai_analytics', 'AI-Powered Analytics', 'admin'),
('english', 'admin.ai_analytics_desc', 'Our AI system identifies trends and provides insights to optimize user engagement', 'admin'),
('english', 'admin.total_users', 'Total Users', 'admin'),
('english', 'admin.new_this_month', '{{count}} new this month', 'admin'),
('english', 'admin.total_messages', 'Total Messages', 'admin'),
('english', 'admin.matches_made', '{{count}} matches made', 'admin'),
('english', 'admin.premium_users', 'Premium Users', 'admin'),
('english', 'admin.revenue', '{{amount}} revenue', 'admin'),
('english', 'admin.user_growth', 'User Growth', 'admin'),
('english', 'admin.activity', 'Activity', 'admin'),
('english', 'admin.user_growth_30d', 'User Growth (Last 30 Days)', 'admin'),
('english', 'admin.new_registrations', 'New user registrations over time', 'admin'),
('english', 'admin.message_activity_30d', 'Message Activity (Last 30 Days)', 'admin'),
('english', 'admin.messages_over_time', 'Messages sent over time', 'admin'),
('english', 'admin.platform_summary', 'Platform Summary', 'admin'),
('english', 'admin.key_metrics', 'Key metrics at a glance', 'admin'),
('english', 'admin.total_photos', 'Total Photos', 'admin'),
('english', 'admin.verified_users', 'Verified Users', 'admin'),
('english', 'admin.total_matches', 'Total Matches', 'admin'),
('english', 'admin.conversion_rate', 'Conversion Rate', 'admin'),
('english', 'admin.no_data_available', 'No data available', 'admin'),

-- EmailCampaigns
('english', 'admin.email_campaigns', 'Email Campaigns', 'admin'),
('english', 'admin.new_campaign', 'New Campaign', 'admin'),
('english', 'admin.ai_email_optimization', 'AI-Powered Email Optimization', 'admin'),
('english', 'admin.ai_email_desc', 'Our AI system analyzes campaign performance and suggests optimizations for subject lines, content, and send times', 'admin'),
('english', 'admin.all_campaigns', 'All Campaigns', 'admin'),
('english', 'admin.paused', 'Paused', 'admin'),
('english', 'admin.search_campaigns', 'Search campaigns...', 'admin'),
('english', 'admin.filter_by_status', 'Filter by status', 'admin'),
('english', 'admin.all_statuses', 'All Statuses', 'admin'),
('english', 'admin.campaign_name', 'Campaign Name', 'admin'),
('english', 'admin.audience', 'Audience', 'admin'),
('english', 'admin.last_sent', 'Last Sent', 'admin'),
('english', 'admin.next_send', 'Next Send', 'admin'),
('english', 'admin.opens', 'Opens', 'admin'),
('english', 'admin.clicks', 'Clicks', 'admin'),
('english', 'admin.no_campaigns_found', 'No campaigns found', 'admin'),
('english', 'admin.campaign_performance', 'Campaign Performance', 'admin'),
('english', 'admin.daily_engagement', 'Daily Engagement', 'admin'),
('english', 'admin.ai_recommendations', 'AI Recommendations', 'admin'),
('english', 'admin.draft_campaign', 'Draft Campaign', 'admin'),
('english', 'admin.not_sent_yet', 'This campaign hasn''t been sent yet. No performance metrics available.', 'admin'),
('english', 'admin.edit_campaign', 'Edit Campaign', 'admin'),
('english', 'admin.schedule_campaign', 'Schedule Campaign', 'admin'),

-- AuditLogs
('english', 'admin.audit_logs', 'Audit Logs', 'admin'),
('english', 'admin.track_admin_actions', 'Track all administrative actions', 'admin'),
('english', 'admin.total_activities', 'Total Activities', 'admin'),
('english', 'admin.todays_activities', 'Today''s Activities', 'admin'),
('english', 'admin.active_admins', 'Active Admins', 'admin'),
('english', 'admin.activity_log', 'Activity Log', 'admin'),
('english', 'admin.complete_history', 'Complete history of administrative actions', 'admin'),
('english', 'admin.search_activities', 'Search activities...', 'admin'),
('english', 'admin.loading_audit_logs', 'Loading audit logs...', 'admin'),
('english', 'admin.no_audit_logs', 'No audit logs found', 'admin'),
('english', 'admin.user', 'User', 'admin'),
('english', 'admin.description', 'Description', 'admin'),
('english', 'admin.timestamp', 'Timestamp', 'admin'),
('english', 'admin.previous', 'Previous', 'admin'),
('english', 'admin.next', 'Next', 'admin'),
('english', 'admin.activity_details', 'Activity Details', 'admin'),
('english', 'admin.activity_type', 'Activity Type', 'admin'),
('english', 'admin.performed_by', 'Performed By', 'admin'),
('english', 'admin.close', 'Close', 'admin'),
('english', 'admin.no_description', 'No description', 'admin'),

-- BulkActions
('english', 'admin.bulk_actions', 'Bulk User Actions', 'admin'),
('english', 'admin.import_users', 'Import Users', 'admin'),
('english', 'admin.ai_segmentation', 'AI-Powered User Segmentation', 'admin'),
('english', 'admin.ai_segmentation_desc', 'Our AI system analyzes user behavior patterns to suggest optimal user segments for targeted actions', 'admin'),
('english', 'admin.action_history', 'Action History', 'admin'),
('english', 'admin.new_bulk_action', 'New Bulk Action', 'admin'),
('english', 'admin.scheduled_actions', 'Scheduled Actions', 'admin'),
('english', 'admin.search_bulk_actions', 'Search bulk actions...', 'admin'),
('english', 'admin.job_name', 'Job Name', 'admin'),
('english', 'admin.type', 'Type', 'admin'),
('english', 'admin.affected_users', 'Affected Users', 'admin'),
('english', 'admin.created_by', 'Created By', 'admin'),
('english', 'admin.no_bulk_actions', 'No bulk action jobs found', 'admin'),
('english', 'admin.select_action_type', 'Select Bulk Action Type', 'admin'),
('english', 'admin.choose_action_desc', 'Choose the type of bulk action you want to perform', 'admin'),
('english', 'admin.status_update', 'Status Update', 'admin'),
('english', 'admin.status_update_desc', 'Update the status of multiple user accounts', 'admin'),
('english', 'admin.email_notification', 'Email Notification', 'admin'),
('english', 'admin.email_notification_desc', 'Send an email to multiple users', 'admin'),
('english', 'admin.account_suspension', 'Account Suspension', 'admin'),
('english', 'admin.account_suspension_desc', 'Suspend multiple user accounts', 'admin'),
('english', 'admin.role_update', 'Role Update', 'admin'),
('english', 'admin.role_update_desc', 'Change the role of multiple users', 'admin'),
('english', 'admin.data_update', 'Data Update', 'admin'),
('english', 'admin.data_update_desc', 'Update specific data fields for multiple users', 'admin'),
('english', 'admin.custom_action', 'Custom Action', 'admin'),
('english', 'admin.custom_action_desc', 'Define a custom action for multiple users', 'admin'),

-- ApiKeys
('english', 'admin.api_keys', 'API Keys & Integrations', 'admin'),
('english', 'admin.api_keys_desc', 'Manage external API keys for all app integrations. Keys are stored securely in the database.', 'admin'),
('english', 'admin.configured', 'configured', 'admin'),
('english', 'admin.get_api_key', 'Get API key', 'admin'),
('english', 'admin.not_set', 'Not set', 'admin'),
('english', 'admin.save', 'Save', 'admin'),
('english', 'admin.update', 'Update', 'admin'),
('english', 'admin.saving', 'Saving...', 'admin'),

-- Norwegian translations
('norwegian', 'admin.system_health', 'Systemhelse', 'admin'),
('norwegian', 'admin.select_time_range', 'Velg tidsperiode', 'admin'),
('norwegian', 'admin.last_hour', 'Siste time', 'admin'),
('norwegian', 'admin.last_24_hours', 'Siste 24 timer', 'admin'),
('norwegian', 'admin.last_7_days', 'Siste 7 dager', 'admin'),
('norwegian', 'admin.last_30_days', 'Siste 30 dager', 'admin'),
('norwegian', 'admin.alerts', 'Varsler', 'admin'),
('norwegian', 'admin.overall_system', 'Overordnet system', 'admin'),
('norwegian', 'admin.active_users', 'Aktive brukere', 'admin'),
('norwegian', 'admin.database_records', 'Databaseposter', 'admin'),
('norwegian', 'admin.ai_system_monitoring', 'AI-drevet systemovervåking', 'admin'),
('norwegian', 'admin.ai_system_monitoring_desc', 'Sanntids metrikker via edge-funksjoner hvert 5. minutt', 'admin'),
('norwegian', 'admin.overview', 'Oversikt', 'admin'),
('norwegian', 'admin.api_performance', 'API-ytelse', 'admin'),
('norwegian', 'admin.system_resources', 'Systemressurser', 'admin'),
('norwegian', 'admin.incidents', 'Hendelser', 'admin'),
('norwegian', 'admin.healthy', 'Frisk', 'admin'),
('norwegian', 'admin.warning', 'Advarsel', 'admin'),
('norwegian', 'admin.critical', 'Kritisk', 'admin'),
('norwegian', 'admin.investigating', 'Under etterforskning', 'admin'),
('norwegian', 'admin.resolved', 'Løst', 'admin'),
('norwegian', 'admin.view_details', 'Se detaljer', 'admin'),
('norwegian', 'admin.no_metrics', 'Ingen metrikker tilgjengelig', 'admin'),
('norwegian', 'admin.data_exports', 'Dataeksporter', 'admin'),
('norwegian', 'admin.refresh', 'Oppdater', 'admin'),
('norwegian', 'admin.refreshing', 'Oppdaterer...', 'admin'),
('norwegian', 'admin.new_export', 'Ny eksport', 'admin'),
('norwegian', 'admin.download', 'Last ned', 'admin'),
('norwegian', 'admin.retry', 'Prøv igjen', 'admin'),
('norwegian', 'admin.cancel', 'Avbryt', 'admin'),
('norwegian', 'admin.ab_testing', 'A/B-testing', 'admin'),
('norwegian', 'admin.new_test', 'Ny test', 'admin'),
('norwegian', 'admin.stop', 'Stopp', 'admin'),
('norwegian', 'admin.start', 'Start', 'admin'),
('norwegian', 'admin.duplicate', 'Dupliser', 'admin'),
('norwegian', 'admin.edit', 'Rediger', 'admin'),
('norwegian', 'admin.ai_insights', 'AI-samtaleinnnsikter', 'admin'),
('norwegian', 'admin.advanced_analytics', 'Avansert analyse', 'admin'),
('norwegian', 'admin.export', 'Eksporter', 'admin'),
('norwegian', 'admin.total_users', 'Totale brukere', 'admin'),
('norwegian', 'admin.total_messages', 'Totale meldinger', 'admin'),
('norwegian', 'admin.premium_users', 'Premiumbrukere', 'admin'),
('norwegian', 'admin.email_campaigns', 'E-postkampanjer', 'admin'),
('norwegian', 'admin.new_campaign', 'Ny kampanje', 'admin'),
('norwegian', 'admin.audit_logs', 'Revisjonslogger', 'admin'),
('norwegian', 'admin.bulk_actions', 'Massehandlinger', 'admin'),
('norwegian', 'admin.import_users', 'Importer brukere', 'admin'),
('norwegian', 'admin.api_keys', 'API-nøkler og integrasjoner', 'admin'),
('norwegian', 'admin.save', 'Lagre', 'admin'),
('norwegian', 'admin.update', 'Oppdater', 'admin'),
('norwegian', 'admin.saving', 'Lagrer...', 'admin'),
('norwegian', 'admin.close', 'Lukk', 'admin'),
('norwegian', 'admin.previous', 'Forrige', 'admin'),
('norwegian', 'admin.next', 'Neste', 'admin'),
('norwegian', 'admin.active', 'Aktiv', 'admin'),
('norwegian', 'admin.draft', 'Utkast', 'admin'),
('norwegian', 'admin.completed', 'Fullført', 'admin'),
('norwegian', 'admin.scheduled', 'Planlagt', 'admin'),
('norwegian', 'admin.paused', 'Pauset', 'admin'),
('norwegian', 'admin.status', 'Status', 'admin'),
('norwegian', 'admin.actions', 'Handlinger', 'admin'),
('norwegian', 'admin.description', 'Beskrivelse', 'admin'),
('norwegian', 'admin.type', 'Type', 'admin'),

-- German translations
('german', 'admin.system_health', 'Systemzustand', 'admin'),
('german', 'admin.select_time_range', 'Zeitraum wählen', 'admin'),
('german', 'admin.last_hour', 'Letzte Stunde', 'admin'),
('german', 'admin.last_24_hours', 'Letzte 24 Stunden', 'admin'),
('german', 'admin.last_7_days', 'Letzte 7 Tage', 'admin'),
('german', 'admin.last_30_days', 'Letzte 30 Tage', 'admin'),
('german', 'admin.alerts', 'Warnungen', 'admin'),
('german', 'admin.overall_system', 'Gesamtsystem', 'admin'),
('german', 'admin.active_users', 'Aktive Benutzer', 'admin'),
('german', 'admin.database_records', 'Datenbankeinträge', 'admin'),
('german', 'admin.healthy', 'Gesund', 'admin'),
('german', 'admin.warning', 'Warnung', 'admin'),
('german', 'admin.critical', 'Kritisch', 'admin'),
('german', 'admin.investigating', 'Wird untersucht', 'admin'),
('german', 'admin.resolved', 'Gelöst', 'admin'),
('german', 'admin.view_details', 'Details anzeigen', 'admin'),
('german', 'admin.no_metrics', 'Keine Metriken verfügbar', 'admin'),
('german', 'admin.data_exports', 'Datenexporte', 'admin'),
('german', 'admin.refresh', 'Aktualisieren', 'admin'),
('german', 'admin.refreshing', 'Wird aktualisiert...', 'admin'),
('german', 'admin.new_export', 'Neuer Export', 'admin'),
('german', 'admin.download', 'Herunterladen', 'admin'),
('german', 'admin.retry', 'Wiederholen', 'admin'),
('german', 'admin.cancel', 'Abbrechen', 'admin'),
('german', 'admin.ab_testing', 'A/B-Tests', 'admin'),
('german', 'admin.new_test', 'Neuer Test', 'admin'),
('german', 'admin.stop', 'Stopp', 'admin'),
('german', 'admin.start', 'Start', 'admin'),
('german', 'admin.duplicate', 'Duplizieren', 'admin'),
('german', 'admin.edit', 'Bearbeiten', 'admin'),
('german', 'admin.ai_insights', 'KI-Gesprächseinblicke', 'admin'),
('german', 'admin.advanced_analytics', 'Erweiterte Analysen', 'admin'),
('german', 'admin.export', 'Exportieren', 'admin'),
('german', 'admin.total_users', 'Gesamtbenutzer', 'admin'),
('german', 'admin.total_messages', 'Gesamte Nachrichten', 'admin'),
('german', 'admin.premium_users', 'Premium-Benutzer', 'admin'),
('german', 'admin.email_campaigns', 'E-Mail-Kampagnen', 'admin'),
('german', 'admin.new_campaign', 'Neue Kampagne', 'admin'),
('german', 'admin.audit_logs', 'Auditprotokolle', 'admin'),
('german', 'admin.bulk_actions', 'Massenaktionen', 'admin'),
('german', 'admin.import_users', 'Benutzer importieren', 'admin'),
('german', 'admin.api_keys', 'API-Schlüssel & Integrationen', 'admin'),
('german', 'admin.save', 'Speichern', 'admin'),
('german', 'admin.update', 'Aktualisieren', 'admin'),
('german', 'admin.saving', 'Speichern...', 'admin'),
('german', 'admin.close', 'Schließen', 'admin'),
('german', 'admin.previous', 'Zurück', 'admin'),
('german', 'admin.next', 'Weiter', 'admin'),
('german', 'admin.active', 'Aktiv', 'admin'),
('german', 'admin.draft', 'Entwurf', 'admin'),
('german', 'admin.completed', 'Abgeschlossen', 'admin'),
('german', 'admin.scheduled', 'Geplant', 'admin'),
('german', 'admin.paused', 'Pausiert', 'admin'),
('german', 'admin.status', 'Status', 'admin'),
('german', 'admin.actions', 'Aktionen', 'admin'),
('german', 'admin.description', 'Beschreibung', 'admin'),
('german', 'admin.type', 'Typ', 'admin'),

-- Kurdish Sorani translations
('kurdish_sorani', 'admin.system_health', 'تەندروستیی سیستەم', 'admin'),
('kurdish_sorani', 'admin.alerts', 'ئاگاداریەکان', 'admin'),
('kurdish_sorani', 'admin.active_users', 'بەکارهێنەری چالاک', 'admin'),
('kurdish_sorani', 'admin.healthy', 'تەندروست', 'admin'),
('kurdish_sorani', 'admin.warning', 'ئاگاداری', 'admin'),
('kurdish_sorani', 'admin.critical', 'کریتیکاڵ', 'admin'),
('kurdish_sorani', 'admin.resolved', 'چارەسەرکرا', 'admin'),
('kurdish_sorani', 'admin.data_exports', 'هەناردەی داتا', 'admin'),
('kurdish_sorani', 'admin.refresh', 'نوێکردنەوە', 'admin'),
('kurdish_sorani', 'admin.download', 'داگرتن', 'admin'),
('kurdish_sorani', 'admin.cancel', 'پاشگەزبوونەوە', 'admin'),
('kurdish_sorani', 'admin.ab_testing', 'تاقیکردنەوەی A/B', 'admin'),
('kurdish_sorani', 'admin.stop', 'وەستان', 'admin'),
('kurdish_sorani', 'admin.start', 'دەستپێکردن', 'admin'),
('kurdish_sorani', 'admin.edit', 'دەستکاری', 'admin'),
('kurdish_sorani', 'admin.email_campaigns', 'کەمپینەکانی ئیمەیڵ', 'admin'),
('kurdish_sorani', 'admin.audit_logs', 'تۆمارەکانی چاودێری', 'admin'),
('kurdish_sorani', 'admin.bulk_actions', 'کردارەکانی کۆمەڵ', 'admin'),
('kurdish_sorani', 'admin.api_keys', 'کلیلەکانی API', 'admin'),
('kurdish_sorani', 'admin.save', 'پاشەکەوتکردن', 'admin'),
('kurdish_sorani', 'admin.close', 'داخستن', 'admin'),
('kurdish_sorani', 'admin.previous', 'پێشوو', 'admin'),
('kurdish_sorani', 'admin.next', 'دواتر', 'admin'),
('kurdish_sorani', 'admin.active', 'چالاک', 'admin'),
('kurdish_sorani', 'admin.completed', 'تەواوبوو', 'admin'),
('kurdish_sorani', 'admin.status', 'دۆخ', 'admin'),
('kurdish_sorani', 'admin.actions', 'کردارەکان', 'admin'),

-- Kurdish Kurmanci translations
('kurdish_kurmanci', 'admin.system_health', 'Tenduristiya Sîstemê', 'admin'),
('kurdish_kurmanci', 'admin.alerts', 'Hişyarî', 'admin'),
('kurdish_kurmanci', 'admin.active_users', 'Bikarhênerên çalak', 'admin'),
('kurdish_kurmanci', 'admin.healthy', 'Saxlem', 'admin'),
('kurdish_kurmanci', 'admin.warning', 'Hişyarî', 'admin'),
('kurdish_kurmanci', 'admin.critical', 'Krîtîk', 'admin'),
('kurdish_kurmanci', 'admin.resolved', 'Çareserkirî', 'admin'),
('kurdish_kurmanci', 'admin.data_exports', 'Derxistina daneyan', 'admin'),
('kurdish_kurmanci', 'admin.refresh', 'Nûkirin', 'admin'),
('kurdish_kurmanci', 'admin.download', 'Daxistin', 'admin'),
('kurdish_kurmanci', 'admin.cancel', 'Betal kirin', 'admin'),
('kurdish_kurmanci', 'admin.ab_testing', 'Testa A/B', 'admin'),
('kurdish_kurmanci', 'admin.stop', 'Rawestin', 'admin'),
('kurdish_kurmanci', 'admin.start', 'Destpêkirin', 'admin'),
('kurdish_kurmanci', 'admin.edit', 'Guhertin', 'admin'),
('kurdish_kurmanci', 'admin.email_campaigns', 'Kampanyayên e-nameyê', 'admin'),
('kurdish_kurmanci', 'admin.audit_logs', 'Tomarên kontrolê', 'admin'),
('kurdish_kurmanci', 'admin.bulk_actions', 'Kiryarên girseyî', 'admin'),
('kurdish_kurmanci', 'admin.api_keys', 'Kilîtên API', 'admin'),
('kurdish_kurmanci', 'admin.save', 'Tomar kirin', 'admin'),
('kurdish_kurmanci', 'admin.close', 'Girtin', 'admin'),
('kurdish_kurmanci', 'admin.previous', 'Berê', 'admin'),
('kurdish_kurmanci', 'admin.next', 'Pêş', 'admin'),
('kurdish_kurmanci', 'admin.active', 'Çalak', 'admin'),
('kurdish_kurmanci', 'admin.completed', 'Qediya', 'admin'),
('kurdish_kurmanci', 'admin.status', 'Rewş', 'admin'),
('kurdish_kurmanci', 'admin.actions', 'Kiryar', 'admin')

ON CONFLICT DO NOTHING;
