
INSERT INTO public.app_translations (language_code, translation_key, translation_value, category) VALUES
-- ActivityTabs
('english', 'admin.user_activity', 'User Activity', 'admin'),
('english', 'admin.engagement', 'Engagement', 'admin'),
('english', 'admin.distribution', 'Distribution', 'admin'),
('english', 'admin.no_engagement_data', 'No user engagement data available', 'admin'),
('norwegian', 'admin.user_activity', 'Brukeraktivitet', 'admin'),
('norwegian', 'admin.engagement', 'Engasjement', 'admin'),
('norwegian', 'admin.distribution', 'Distribusjon', 'admin'),
('norwegian', 'admin.no_engagement_data', 'Ingen brukerengasjementsdata tilgjengelig', 'admin'),
('kurdish_sorani', 'admin.user_activity', 'چالاکی بەکارهێنەر', 'admin'),
('kurdish_sorani', 'admin.engagement', 'بەشداربوون', 'admin'),
('kurdish_sorani', 'admin.distribution', 'دابەشکردن', 'admin'),
('kurdish_sorani', 'admin.no_engagement_data', 'هیچ داتای بەشداربوونی بەکارهێنەر بەردەست نییە', 'admin'),
('kurdish_kurmanci', 'admin.user_activity', 'Çalakiya bikarhêner', 'admin'),
('kurdish_kurmanci', 'admin.engagement', 'Tevlêbûn', 'admin'),
('kurdish_kurmanci', 'admin.distribution', 'Belavkirin', 'admin'),
('kurdish_kurmanci', 'admin.no_engagement_data', 'Daneyên tevlêbûna bikarhêneran tune ne', 'admin'),
('german', 'admin.user_activity', 'Benutzeraktivität', 'admin'),
('german', 'admin.engagement', 'Engagement', 'admin'),
('german', 'admin.distribution', 'Verteilung', 'admin'),
('german', 'admin.no_engagement_data', 'Keine Benutzer-Engagement-Daten verfügbar', 'admin'),

-- QuickActions
('english', 'admin.quick_actions', 'Quick Actions', 'admin'),
('english', 'admin.common_admin_tasks', 'Common administrative tasks', 'admin'),
('english', 'admin.add_new_user', 'Add New User', 'admin'),
('english', 'admin.send_notification', 'Send Notification', 'admin'),
('english', 'admin.manage_categories', 'Manage Categories', 'admin'),
('english', 'admin.system_settings', 'System Settings', 'admin'),
('english', 'admin.manage_likes', 'Manage Likes', 'admin'),
('english', 'admin.view_analytics', 'View Analytics', 'admin'),
('norwegian', 'admin.quick_actions', 'Hurtighandlinger', 'admin'),
('norwegian', 'admin.common_admin_tasks', 'Vanlige administrative oppgaver', 'admin'),
('norwegian', 'admin.add_new_user', 'Legg til ny bruker', 'admin'),
('norwegian', 'admin.send_notification', 'Send varsling', 'admin'),
('norwegian', 'admin.manage_categories', 'Administrer kategorier', 'admin'),
('norwegian', 'admin.system_settings', 'Systeminnstillinger', 'admin'),
('norwegian', 'admin.manage_likes', 'Administrer likerklikk', 'admin'),
('norwegian', 'admin.view_analytics', 'Vis analyse', 'admin'),
('kurdish_sorani', 'admin.quick_actions', 'کردارە خێراکان', 'admin'),
('kurdish_sorani', 'admin.common_admin_tasks', 'ئەرکە باوەکانی بەڕێوەبردن', 'admin'),
('kurdish_sorani', 'admin.add_new_user', 'زیادکردنی بەکارهێنەری نوێ', 'admin'),
('kurdish_sorani', 'admin.send_notification', 'ناردنی ئاگادارکردنەوە', 'admin'),
('kurdish_sorani', 'admin.manage_categories', 'بەڕێوەبردنی پۆلەکان', 'admin'),
('kurdish_sorani', 'admin.system_settings', 'ڕێکخستنەکانی سیستەم', 'admin'),
('kurdish_sorani', 'admin.manage_likes', 'بەڕێوەبردنی پەسەندکردنەکان', 'admin'),
('kurdish_sorani', 'admin.view_analytics', 'بینینی شیکاری', 'admin'),
('kurdish_kurmanci', 'admin.quick_actions', 'Kiryarên bilez', 'admin'),
('kurdish_kurmanci', 'admin.common_admin_tasks', 'Karên rêvebiriyê yên hevpar', 'admin'),
('kurdish_kurmanci', 'admin.add_new_user', 'Bikarhênerek nû zêde bike', 'admin'),
('kurdish_kurmanci', 'admin.send_notification', 'Agahdariyê bişîne', 'admin'),
('kurdish_kurmanci', 'admin.manage_categories', 'Kategorîyan birêve bibe', 'admin'),
('kurdish_kurmanci', 'admin.system_settings', 'Mîhengên pergalê', 'admin'),
('kurdish_kurmanci', 'admin.manage_likes', 'Hesandinan birêve bibe', 'admin'),
('kurdish_kurmanci', 'admin.view_analytics', 'Analîzan bibîne', 'admin'),
('german', 'admin.quick_actions', 'Schnellaktionen', 'admin'),
('german', 'admin.common_admin_tasks', 'Häufige Verwaltungsaufgaben', 'admin'),
('german', 'admin.add_new_user', 'Neuen Benutzer hinzufügen', 'admin'),
('german', 'admin.send_notification', 'Benachrichtigung senden', 'admin'),
('german', 'admin.manage_categories', 'Kategorien verwalten', 'admin'),
('german', 'admin.system_settings', 'Systemeinstellungen', 'admin'),
('german', 'admin.manage_likes', 'Likes verwalten', 'admin'),
('german', 'admin.view_analytics', 'Analysen anzeigen', 'admin'),

-- RecentActivity
('english', 'admin.recent_activity', 'Recent Activity', 'admin'),
('english', 'admin.latest_actions', 'Latest actions across the platform', 'admin'),
('english', 'admin.no_recent_activities', 'No recent activities found.', 'admin'),
('english', 'admin.view_all_activity', 'View All Activity', 'admin'),
('english', 'admin.new_user_registration', 'New user registration', 'admin'),
('english', 'admin.user_upgraded_premium', 'User upgraded to premium', 'admin'),
('english', 'admin.new_photos_uploaded', 'New photos uploaded', 'admin'),
('english', 'admin.new_message_sent', 'New message sent', 'admin'),
('english', 'admin.profile_updated', 'Profile updated', 'admin'),
('english', 'admin.user_moderation_activity', 'User moderation', 'admin'),
('english', 'admin.system_update_activity', 'System update', 'admin'),
('english', 'admin.content_moderation_activity', 'Content moderation', 'admin'),
('english', 'admin.user_support_activity', 'User support', 'admin'),
('english', 'admin.system_maintenance_activity', 'System maintenance', 'admin'),
('norwegian', 'admin.recent_activity', 'Nylig aktivitet', 'admin'),
('norwegian', 'admin.latest_actions', 'Siste handlinger på plattformen', 'admin'),
('norwegian', 'admin.no_recent_activities', 'Ingen nylige aktiviteter funnet.', 'admin'),
('norwegian', 'admin.view_all_activity', 'Vis all aktivitet', 'admin'),
('norwegian', 'admin.new_user_registration', 'Ny brukerregistrering', 'admin'),
('norwegian', 'admin.user_upgraded_premium', 'Bruker oppgradert til premium', 'admin'),
('norwegian', 'admin.new_photos_uploaded', 'Nye bilder lastet opp', 'admin'),
('norwegian', 'admin.new_message_sent', 'Ny melding sendt', 'admin'),
('norwegian', 'admin.profile_updated', 'Profil oppdatert', 'admin'),
('norwegian', 'admin.user_moderation_activity', 'Brukermoderasjon', 'admin'),
('norwegian', 'admin.system_update_activity', 'Systemoppdatering', 'admin'),
('norwegian', 'admin.content_moderation_activity', 'Innholdsmoderasjon', 'admin'),
('norwegian', 'admin.user_support_activity', 'Brukerstøtte', 'admin'),
('norwegian', 'admin.system_maintenance_activity', 'Systemvedlikehold', 'admin'),
('kurdish_sorani', 'admin.recent_activity', 'چالاکیی نوێ', 'admin'),
('kurdish_sorani', 'admin.latest_actions', 'دوایین کردارەکان لە پلاتفۆرمەکەدا', 'admin'),
('kurdish_sorani', 'admin.no_recent_activities', 'هیچ چالاکیی نوێ نەدۆزرایەوە.', 'admin'),
('kurdish_sorani', 'admin.view_all_activity', 'بینینی هەموو چالاکییەکان', 'admin'),
('kurdish_sorani', 'admin.new_user_registration', 'تۆمارکردنی بەکارهێنەری نوێ', 'admin'),
('kurdish_sorani', 'admin.user_upgraded_premium', 'بەکارهێنەر نوێکرایەوە بۆ پریمیەم', 'admin'),
('kurdish_sorani', 'admin.new_photos_uploaded', 'وێنەی نوێ بارکرا', 'admin'),
('kurdish_sorani', 'admin.new_message_sent', 'نامەی نوێ نێردرا', 'admin'),
('kurdish_sorani', 'admin.profile_updated', 'پرۆفایل نوێکرایەوە', 'admin'),
('kurdish_sorani', 'admin.user_moderation_activity', 'مۆدێرەیشنی بەکارهێنەر', 'admin'),
('kurdish_sorani', 'admin.system_update_activity', 'نوێکردنەوەی سیستەم', 'admin'),
('kurdish_sorani', 'admin.content_moderation_activity', 'مۆدێرەیشنی ناوەڕۆک', 'admin'),
('kurdish_sorani', 'admin.user_support_activity', 'پشتگیری بەکارهێنەر', 'admin'),
('kurdish_sorani', 'admin.system_maintenance_activity', 'چاککردنی سیستەم', 'admin'),
('kurdish_kurmanci', 'admin.recent_activity', 'Çalakiya dawî', 'admin'),
('kurdish_kurmanci', 'admin.latest_actions', 'Kiryarên herî dawî li ser platformê', 'admin'),
('kurdish_kurmanci', 'admin.no_recent_activities', 'Çalakiya dawî nehat dîtin.', 'admin'),
('kurdish_kurmanci', 'admin.view_all_activity', 'Hemû çalakiyan bibîne', 'admin'),
('kurdish_kurmanci', 'admin.new_user_registration', 'Qeydkirina bikarhênerek nû', 'admin'),
('kurdish_kurmanci', 'admin.user_upgraded_premium', 'Bikarhêner bi premium hat bilindkirin', 'admin'),
('kurdish_kurmanci', 'admin.new_photos_uploaded', 'Wêneyên nû hatin barkirin', 'admin'),
('kurdish_kurmanci', 'admin.new_message_sent', 'Peyamek nû hat şandin', 'admin'),
('kurdish_kurmanci', 'admin.profile_updated', 'Profîl hat nûkirin', 'admin'),
('kurdish_kurmanci', 'admin.user_moderation_activity', 'Moderasyona bikarhêner', 'admin'),
('kurdish_kurmanci', 'admin.system_update_activity', 'Nûkirina pergalê', 'admin'),
('kurdish_kurmanci', 'admin.content_moderation_activity', 'Moderasyona naverokê', 'admin'),
('kurdish_kurmanci', 'admin.user_support_activity', 'Piştgiriya bikarhêner', 'admin'),
('kurdish_kurmanci', 'admin.system_maintenance_activity', 'Lênihêrîna pergalê', 'admin'),
('german', 'admin.recent_activity', 'Letzte Aktivität', 'admin'),
('german', 'admin.latest_actions', 'Neueste Aktionen auf der Plattform', 'admin'),
('german', 'admin.no_recent_activities', 'Keine aktuellen Aktivitäten gefunden.', 'admin'),
('german', 'admin.view_all_activity', 'Alle Aktivitäten anzeigen', 'admin'),
('german', 'admin.new_user_registration', 'Neue Benutzerregistrierung', 'admin'),
('german', 'admin.user_upgraded_premium', 'Benutzer auf Premium aktualisiert', 'admin'),
('german', 'admin.new_photos_uploaded', 'Neue Fotos hochgeladen', 'admin'),
('german', 'admin.new_message_sent', 'Neue Nachricht gesendet', 'admin'),
('german', 'admin.profile_updated', 'Profil aktualisiert', 'admin'),
('german', 'admin.user_moderation_activity', 'Benutzermoderation', 'admin'),
('german', 'admin.system_update_activity', 'Systemaktualisierung', 'admin'),
('german', 'admin.content_moderation_activity', 'Inhaltsmoderation', 'admin'),
('german', 'admin.user_support_activity', 'Benutzersupport', 'admin'),
('german', 'admin.system_maintenance_activity', 'Systemwartung', 'admin'),

-- EngagementChart
('english', 'admin.engagement_metrics', 'User Engagement Metrics', 'admin'),
('english', 'admin.engagement_description', 'Likes, views, and matches over time', 'admin'),
('norwegian', 'admin.engagement_metrics', 'Brukerengasjement-metrikker', 'admin'),
('norwegian', 'admin.engagement_description', 'Likerklikk, visninger og treff over tid', 'admin'),
('kurdish_sorani', 'admin.engagement_metrics', 'پێوەرەکانی بەشداربوونی بەکارهێنەر', 'admin'),
('kurdish_sorani', 'admin.engagement_description', 'پەسەندکردن، بینین و هاوتاکردن بە درێژایی کات', 'admin'),
('kurdish_kurmanci', 'admin.engagement_metrics', 'Pîvanên tevlêbûna bikarhêneran', 'admin'),
('kurdish_kurmanci', 'admin.engagement_description', 'Hesandin, dîtin û hevberdanan bi demê re', 'admin'),
('german', 'admin.engagement_metrics', 'Benutzer-Engagement-Metriken', 'admin'),
('german', 'admin.engagement_description', 'Likes, Aufrufe und Übereinstimmungen im Zeitverlauf', 'admin'),

-- UserActivityChart
('english', 'admin.activity_trends', 'User Activity Trends', 'admin'),
('english', 'admin.activity_trends_description', 'Daily active users and conversations', 'admin'),
('norwegian', 'admin.activity_trends', 'Brukeraktivitetstrender', 'admin'),
('norwegian', 'admin.activity_trends_description', 'Daglige aktive brukere og samtaler', 'admin'),
('kurdish_sorani', 'admin.activity_trends', 'ڕەوتەکانی چالاکی بەکارهێنەر', 'admin'),
('kurdish_sorani', 'admin.activity_trends_description', 'بەکارهێنەرە چالاکەکانی ڕۆژانە و گفتوگۆکان', 'admin'),
('kurdish_kurmanci', 'admin.activity_trends', 'Trendên çalakiya bikarhêneran', 'admin'),
('kurdish_kurmanci', 'admin.activity_trends_description', 'Bikarhênerên çalak ên rojane û danûstandin', 'admin'),
('german', 'admin.activity_trends', 'Benutzeraktivitätstrends', 'admin'),
('german', 'admin.activity_trends_description', 'Täglich aktive Benutzer und Konversationen', 'admin'),

-- UserDistributionChart
('english', 'admin.user_distribution', 'User Distribution', 'admin'),
('english', 'admin.breakdown_user_types', 'Breakdown of user types', 'admin'),
('english', 'admin.no_user_data', 'No user data available', 'admin'),
('english', 'admin.error_loading_data', 'Error loading data', 'admin'),
('english', 'admin.could_not_load_distribution', 'Could not load user distribution data', 'admin'),
('norwegian', 'admin.user_distribution', 'Brukerfordeling', 'admin'),
('norwegian', 'admin.breakdown_user_types', 'Fordeling av brukertyper', 'admin'),
('norwegian', 'admin.no_user_data', 'Ingen brukerdata tilgjengelig', 'admin'),
('norwegian', 'admin.error_loading_data', 'Feil ved lasting av data', 'admin'),
('norwegian', 'admin.could_not_load_distribution', 'Kunne ikke laste brukerfordelingsdata', 'admin'),
('kurdish_sorani', 'admin.user_distribution', 'دابەشبوونی بەکارهێنەر', 'admin'),
('kurdish_sorani', 'admin.breakdown_user_types', 'وردەکاری جۆرەکانی بەکارهێنەر', 'admin'),
('kurdish_sorani', 'admin.no_user_data', 'هیچ داتای بەکارهێنەر بەردەست نییە', 'admin'),
('kurdish_sorani', 'admin.error_loading_data', 'هەڵە لە بارکردنی داتا', 'admin'),
('kurdish_sorani', 'admin.could_not_load_distribution', 'نەتوانرا داتای دابەشبوونی بەکارهێنەر بارکرێت', 'admin'),
('kurdish_kurmanci', 'admin.user_distribution', 'Belavkirina bikarhêneran', 'admin'),
('kurdish_kurmanci', 'admin.breakdown_user_types', 'Dabeşkirina cureyên bikarhêneran', 'admin'),
('kurdish_kurmanci', 'admin.no_user_data', 'Daneyên bikarhêneran tune ne', 'admin'),
('kurdish_kurmanci', 'admin.error_loading_data', 'Xeletî di barkirina daneyan de', 'admin'),
('kurdish_kurmanci', 'admin.could_not_load_distribution', 'Daneyên belavkirina bikarhêneran nehatin barkirin', 'admin'),
('german', 'admin.user_distribution', 'Benutzerverteilung', 'admin'),
('german', 'admin.breakdown_user_types', 'Aufschlüsselung der Benutzertypen', 'admin'),
('german', 'admin.no_user_data', 'Keine Benutzerdaten verfügbar', 'admin'),
('german', 'admin.error_loading_data', 'Fehler beim Laden der Daten', 'admin'),
('german', 'admin.could_not_load_distribution', 'Benutzerverteilungsdaten konnten nicht geladen werden', 'admin'),

-- StatsOverview defaults
('english', 'admin.total_users_stat', 'Total Users', 'admin'),
('english', 'admin.active_conversations_stat', 'Active Conversations', 'admin'),
('english', 'admin.photos_uploaded_stat', 'Photos Uploaded', 'admin'),
('english', 'admin.daily_active_users_stat', 'Daily Active Users', 'admin'),
('norwegian', 'admin.total_users_stat', 'Totalt antall brukere', 'admin'),
('norwegian', 'admin.active_conversations_stat', 'Aktive samtaler', 'admin'),
('norwegian', 'admin.photos_uploaded_stat', 'Bilder lastet opp', 'admin'),
('norwegian', 'admin.daily_active_users_stat', 'Daglige aktive brukere', 'admin'),
('kurdish_sorani', 'admin.total_users_stat', 'کۆی بەکارهێنەران', 'admin'),
('kurdish_sorani', 'admin.active_conversations_stat', 'گفتوگۆە چالاکەکان', 'admin'),
('kurdish_sorani', 'admin.photos_uploaded_stat', 'وێنەی بارکراو', 'admin'),
('kurdish_sorani', 'admin.daily_active_users_stat', 'بەکارهێنەرە چالاکەکانی ڕۆژانە', 'admin'),
('kurdish_kurmanci', 'admin.total_users_stat', 'Tevahiya bikarhêneran', 'admin'),
('kurdish_kurmanci', 'admin.active_conversations_stat', 'Danûstandinên çalak', 'admin'),
('kurdish_kurmanci', 'admin.photos_uploaded_stat', 'Wêneyên barkirî', 'admin'),
('kurdish_kurmanci', 'admin.daily_active_users_stat', 'Bikarhênerên çalak ên rojane', 'admin'),
('german', 'admin.total_users_stat', 'Gesamtbenutzer', 'admin'),
('german', 'admin.active_conversations_stat', 'Aktive Unterhaltungen', 'admin'),
('german', 'admin.photos_uploaded_stat', 'Hochgeladene Fotos', 'admin'),
('german', 'admin.daily_active_users_stat', 'Täglich aktive Benutzer', 'admin')
ON CONFLICT (language_code, translation_key) DO NOTHING;
