
INSERT INTO public.app_translations (language_code, translation_key, translation_value, category, context) VALUES
-- CreateEventModal
('english','toast.event.create_failed','Failed to create event','toast','CreateEventModal'),
('english','events.create_event','Create Event','events','CreateEventModal'),
('english','events.event_title','Event Title','events','CreateEventModal'),
('english','events.title_placeholder','e.g., Kurdish Cultural Night','events','CreateEventModal'),
('english','events.describe_placeholder','Describe your event...','events','CreateEventModal'),
('english','events.date_time','Date & Time','events','CreateEventModal'),
('english','events.location_placeholder','Event location','events','CreateEventModal'),
('english','events.category_placeholder','e.g., Cultural, Sports, Music','events','CreateEventModal'),
('english','events.max_attendees','Max Attendees','events','CreateEventModal'),
('english','events.image_url','Event Image URL','events','CreateEventModal'),
('english','common.creating','Creating...','common','CreateEventModal'),
-- TravelModeSettings
('english','toast.travel.activated','Travel Mode activated!','toast','TravelModeSettings'),
('english','toast.travel.deactivated','Travel Mode deactivated','toast','TravelModeSettings'),
('english','settings.travel_mode','Travel Mode','settings','TravelModeSettings'),
('english','settings.gold_feature','Gold Feature','settings','TravelModeSettings'),
('english','settings.travel_upgrade','Upgrade to Gold to appear in other cities while traveling','settings','TravelModeSettings'),
('english','settings.enable_travel','Enable Travel Mode','settings','TravelModeSettings'),
('english','settings.select_city','Select City','settings','TravelModeSettings'),
('english','settings.choose_city','Choose a city...','settings','TravelModeSettings'),
('english','settings.custom_location','Or enter a custom location','settings','TravelModeSettings'),
('english','settings.enter_city','Enter city name...','settings','TravelModeSettings'),
('english','settings.travel_description','Your profile will appear to users in this location instead of your home city. Your real location stays private.','settings','TravelModeSettings'),
('english','settings.save_travel','Save Travel Mode','settings','TravelModeSettings'),
-- ChangePasswordDialog
('english','toast.password.change_failed','Failed to change password. Please try again.','toast','ChangePasswordDialog'),
('english','settings.change_password','Change Password','settings','ChangePasswordDialog'),
('english','settings.current_password','Current Password','settings','ChangePasswordDialog'),
('english','settings.enter_current_password','Enter current password','settings','ChangePasswordDialog'),
('english','settings.new_password','New Password','settings','ChangePasswordDialog'),
('english','settings.enter_new_password','Enter new password','settings','ChangePasswordDialog'),
('english','settings.confirm_new_password','Confirm New Password','settings','ChangePasswordDialog'),
('english','settings.confirm_new_password_placeholder','Confirm new password','settings','ChangePasswordDialog'),
('english','settings.password_requirements','Password Requirements','settings','ChangePasswordDialog'),
('english','settings.changing_password','Changing...','settings','ChangePasswordDialog'),
-- ProfileSwipeActions
('english','toast.swipe.like_profile_failed','Failed to like profile','toast','ProfileSwipeActions'),
-- EventCard
('english','events.full','Full','events','EventCard'),
('english','events.attending','attending','events','EventCard'),
('english','events.max','max','events','EventCard'),
('english','events.organized_by','Organized by','events','EventCard'),
('english','events.leave_event','Leave Event','events','EventCard'),
('english','events.event_full','Event Full','events','EventCard'),
('english','events.join_event','Join Event','events','EventCard'),
-- useQuestions
('english','admin.add_question_failed','Failed to add question','admin','useQuestions'),
-- GiftsAndDates
('english','toast.date.response_failed','Failed to respond','toast','GiftsAndDates'),
('english','toast.date.cancel_failed','Failed to cancel','toast','GiftsAndDates'),
('english','gifts.title','Gifts & Dates','gifts','GiftsAndDates'),
('english','gifts.received','Received','gifts','GiftsAndDates'),
('english','gifts.sent','Sent','gifts','GiftsAndDates'),
('english','gifts.dates','Dates','gifts','GiftsAndDates'),
('english','gifts.no_received','No gifts received yet','gifts','GiftsAndDates'),
('english','gifts.from','From','gifts','GiftsAndDates'),
('english','gifts.someone','Someone','gifts','GiftsAndDates'),
('english','common.new','New','common','GiftsAndDates'),
('english','gifts.no_sent','No gifts sent yet','gifts','GiftsAndDates'),
('english','gifts.no_dates','No date proposals yet','gifts','GiftsAndDates'),
('english','gifts.to','To','gifts','GiftsAndDates'),
('english','common.accept','Accept','common','GiftsAndDates'),
('english','common.decline','Decline','common','GiftsAndDates'),
('english','gifts.cancel_invitation','Cancel invitation','gifts','GiftsAndDates'),
-- Norwegian
('norwegian','toast.event.create_failed','Kunne ikke opprette arrangement','toast','CreateEventModal'),
('norwegian','events.create_event','Opprett arrangement','events','CreateEventModal'),
('norwegian','events.event_title','Arrangementtittel','events','CreateEventModal'),
('norwegian','events.title_placeholder','f.eks. Kurdisk kulturkveld','events','CreateEventModal'),
('norwegian','events.describe_placeholder','Beskriv arrangementet ditt...','events','CreateEventModal'),
('norwegian','events.date_time','Dato og tid','events','CreateEventModal'),
('norwegian','events.location_placeholder','Arrangementssted','events','CreateEventModal'),
('norwegian','events.category_placeholder','f.eks. Kultur, Sport, Musikk','events','CreateEventModal'),
('norwegian','events.max_attendees','Maks deltakere','events','CreateEventModal'),
('norwegian','events.image_url','Arrangementbilde-URL','events','CreateEventModal'),
('norwegian','common.creating','Oppretter...','common','CreateEventModal'),
('norwegian','toast.travel.activated','Reisemodus aktivert!','toast','TravelModeSettings'),
('norwegian','toast.travel.deactivated','Reisemodus deaktivert','toast','TravelModeSettings'),
('norwegian','settings.travel_mode','Reisemodus','settings','TravelModeSettings'),
('norwegian','settings.gold_feature','Gold-funksjon','settings','TravelModeSettings'),
('norwegian','settings.travel_upgrade','Oppgrader til Gold for å vises i andre byer mens du reiser','settings','TravelModeSettings'),
('norwegian','settings.enable_travel','Aktiver reisemodus','settings','TravelModeSettings'),
('norwegian','settings.select_city','Velg by','settings','TravelModeSettings'),
('norwegian','settings.choose_city','Velg en by...','settings','TravelModeSettings'),
('norwegian','settings.custom_location','Eller skriv inn en egendefinert plassering','settings','TravelModeSettings'),
('norwegian','settings.enter_city','Skriv inn bynavn...','settings','TravelModeSettings'),
('norwegian','settings.travel_description','Profilen din vil vises for brukere på denne plasseringen i stedet for hjembyen din. Din virkelige plassering forblir privat.','settings','TravelModeSettings'),
('norwegian','settings.save_travel','Lagre reisemodus','settings','TravelModeSettings'),
('norwegian','toast.password.change_failed','Kunne ikke endre passord. Prøv igjen.','toast','ChangePasswordDialog'),
('norwegian','settings.change_password','Endre passord','settings','ChangePasswordDialog'),
('norwegian','settings.current_password','Nåværende passord','settings','ChangePasswordDialog'),
('norwegian','settings.enter_current_password','Skriv inn nåværende passord','settings','ChangePasswordDialog'),
('norwegian','settings.new_password','Nytt passord','settings','ChangePasswordDialog'),
('norwegian','settings.enter_new_password','Skriv inn nytt passord','settings','ChangePasswordDialog'),
('norwegian','settings.confirm_new_password','Bekreft nytt passord','settings','ChangePasswordDialog'),
('norwegian','settings.confirm_new_password_placeholder','Bekreft nytt passord','settings','ChangePasswordDialog'),
('norwegian','settings.password_requirements','Passordkrav','settings','ChangePasswordDialog'),
('norwegian','settings.changing_password','Endrer...','settings','ChangePasswordDialog'),
('norwegian','toast.swipe.like_profile_failed','Kunne ikke like profil','toast','ProfileSwipeActions'),
('norwegian','events.full','Fullt','events','EventCard'),
('norwegian','events.attending','deltar','events','EventCard'),
('norwegian','events.max','maks','events','EventCard'),
('norwegian','events.organized_by','Organisert av','events','EventCard'),
('norwegian','events.leave_event','Forlat arrangement','events','EventCard'),
('norwegian','events.event_full','Fullt arrangement','events','EventCard'),
('norwegian','events.join_event','Bli med på arrangement','events','EventCard'),
('norwegian','admin.add_question_failed','Kunne ikke legge til spørsmål','admin','useQuestions'),
('norwegian','toast.date.response_failed','Kunne ikke svare','toast','GiftsAndDates'),
('norwegian','toast.date.cancel_failed','Kunne ikke avlyse','toast','GiftsAndDates'),
('norwegian','gifts.title','Gaver og dater','gifts','GiftsAndDates'),
('norwegian','gifts.received','Mottatt','gifts','GiftsAndDates'),
('norwegian','gifts.sent','Sendt','gifts','GiftsAndDates'),
('norwegian','gifts.dates','Dater','gifts','GiftsAndDates'),
('norwegian','gifts.no_received','Ingen gaver mottatt ennå','gifts','GiftsAndDates'),
('norwegian','gifts.from','Fra','gifts','GiftsAndDates'),
('norwegian','gifts.someone','Noen','gifts','GiftsAndDates'),
('norwegian','common.new','Ny','common','GiftsAndDates'),
('norwegian','gifts.no_sent','Ingen gaver sendt ennå','gifts','GiftsAndDates'),
('norwegian','gifts.no_dates','Ingen dateforslag ennå','gifts','GiftsAndDates'),
('norwegian','gifts.to','Til','gifts','GiftsAndDates'),
('norwegian','common.accept','Godta','common','GiftsAndDates'),
('norwegian','common.decline','Avslå','common','GiftsAndDates'),
('norwegian','gifts.cancel_invitation','Avlys invitasjon','gifts','GiftsAndDates'),
-- German
('german','toast.event.create_failed','Veranstaltung konnte nicht erstellt werden','toast','CreateEventModal'),
('german','events.create_event','Veranstaltung erstellen','events','CreateEventModal'),
('german','events.event_title','Veranstaltungstitel','events','CreateEventModal'),
('german','events.title_placeholder','z.B. Kurdischer Kulturabend','events','CreateEventModal'),
('german','events.describe_placeholder','Beschreibe deine Veranstaltung...','events','CreateEventModal'),
('german','events.date_time','Datum & Uhrzeit','events','CreateEventModal'),
('german','events.location_placeholder','Veranstaltungsort','events','CreateEventModal'),
('german','events.category_placeholder','z.B. Kultur, Sport, Musik','events','CreateEventModal'),
('german','events.max_attendees','Max. Teilnehmer','events','CreateEventModal'),
('german','events.image_url','Veranstaltungsbild-URL','events','CreateEventModal'),
('german','common.creating','Erstelle...','common','CreateEventModal'),
('german','toast.travel.activated','Reisemodus aktiviert!','toast','TravelModeSettings'),
('german','toast.travel.deactivated','Reisemodus deaktiviert','toast','TravelModeSettings'),
('german','settings.travel_mode','Reisemodus','settings','TravelModeSettings'),
('german','settings.gold_feature','Gold-Funktion','settings','TravelModeSettings'),
('german','settings.travel_upgrade','Upgrade auf Gold, um in anderen Städten zu erscheinen','settings','TravelModeSettings'),
('german','settings.enable_travel','Reisemodus aktivieren','settings','TravelModeSettings'),
('german','settings.select_city','Stadt auswählen','settings','TravelModeSettings'),
('german','settings.choose_city','Wähle eine Stadt...','settings','TravelModeSettings'),
('german','settings.custom_location','Oder eigenen Ort eingeben','settings','TravelModeSettings'),
('german','settings.enter_city','Stadtname eingeben...','settings','TravelModeSettings'),
('german','settings.travel_description','Dein Profil wird Nutzern an diesem Ort angezeigt statt in deiner Heimatstadt. Dein echter Standort bleibt privat.','settings','TravelModeSettings'),
('german','settings.save_travel','Reisemodus speichern','settings','TravelModeSettings'),
('german','toast.password.change_failed','Passwort konnte nicht geändert werden. Bitte versuche es erneut.','toast','ChangePasswordDialog'),
('german','settings.change_password','Passwort ändern','settings','ChangePasswordDialog'),
('german','settings.current_password','Aktuelles Passwort','settings','ChangePasswordDialog'),
('german','settings.enter_current_password','Aktuelles Passwort eingeben','settings','ChangePasswordDialog'),
('german','settings.new_password','Neues Passwort','settings','ChangePasswordDialog'),
('german','settings.enter_new_password','Neues Passwort eingeben','settings','ChangePasswordDialog'),
('german','settings.confirm_new_password','Neues Passwort bestätigen','settings','ChangePasswordDialog'),
('german','settings.confirm_new_password_placeholder','Neues Passwort bestätigen','settings','ChangePasswordDialog'),
('german','settings.password_requirements','Passwortanforderungen','settings','ChangePasswordDialog'),
('german','settings.changing_password','Ändere...','settings','ChangePasswordDialog'),
('german','toast.swipe.like_profile_failed','Profil konnte nicht geliked werden','toast','ProfileSwipeActions'),
('german','events.full','Voll','events','EventCard'),
('german','events.attending','teilnehmend','events','EventCard'),
('german','events.max','max','events','EventCard'),
('german','events.organized_by','Organisiert von','events','EventCard'),
('german','events.leave_event','Veranstaltung verlassen','events','EventCard'),
('german','events.event_full','Veranstaltung voll','events','EventCard'),
('german','events.join_event','Veranstaltung beitreten','events','EventCard'),
('german','admin.add_question_failed','Frage konnte nicht hinzugefügt werden','admin','useQuestions'),
('german','toast.date.response_failed','Antwort fehlgeschlagen','toast','GiftsAndDates'),
('german','toast.date.cancel_failed','Absage fehlgeschlagen','toast','GiftsAndDates'),
('german','gifts.title','Geschenke & Dates','gifts','GiftsAndDates'),
('german','gifts.received','Erhalten','gifts','GiftsAndDates'),
('german','gifts.sent','Gesendet','gifts','GiftsAndDates'),
('german','gifts.dates','Dates','gifts','GiftsAndDates'),
('german','gifts.no_received','Noch keine Geschenke erhalten','gifts','GiftsAndDates'),
('german','gifts.from','Von','gifts','GiftsAndDates'),
('german','gifts.someone','Jemand','gifts','GiftsAndDates'),
('german','common.new','Neu','common','GiftsAndDates'),
('german','gifts.no_sent','Noch keine Geschenke gesendet','gifts','GiftsAndDates'),
('german','gifts.no_dates','Noch keine Date-Vorschläge','gifts','GiftsAndDates'),
('german','gifts.to','An','gifts','GiftsAndDates'),
('german','common.accept','Akzeptieren','common','GiftsAndDates'),
('german','common.decline','Ablehnen','common','GiftsAndDates'),
('german','gifts.cancel_invitation','Einladung absagen','gifts','GiftsAndDates'),
-- Kurdish Sorani
('kurdish_sorani','toast.event.create_failed','نەتوانرا بۆنە دروست بکرێت','toast','CreateEventModal'),
('kurdish_sorani','events.create_event','دروستکردنی بۆنە','events','CreateEventModal'),
('kurdish_sorani','events.event_title','ناونیشانی بۆنە','events','CreateEventModal'),
('kurdish_sorani','events.title_placeholder','بۆ نموونە، شەوی کولتووری کوردی','events','CreateEventModal'),
('kurdish_sorani','events.describe_placeholder','بۆنەکەت وەسف بکە...','events','CreateEventModal'),
('kurdish_sorani','events.date_time','بەروار و کات','events','CreateEventModal'),
('kurdish_sorani','events.location_placeholder','شوێنی بۆنە','events','CreateEventModal'),
('kurdish_sorani','events.category_placeholder','بۆ نموونە، کولتووری، وەرزشی، مۆسیقا','events','CreateEventModal'),
('kurdish_sorani','events.max_attendees','زۆرترین بەشداربوو','events','CreateEventModal'),
('kurdish_sorani','events.image_url','لینکی وێنەی بۆنە','events','CreateEventModal'),
('kurdish_sorani','common.creating','دروستدەکرێت...','common','CreateEventModal'),
('kurdish_sorani','toast.travel.activated','دۆخی گەشت چالاک کرا!','toast','TravelModeSettings'),
('kurdish_sorani','toast.travel.deactivated','دۆخی گەشت ناچالاک کرا','toast','TravelModeSettings'),
('kurdish_sorani','settings.travel_mode','دۆخی گەشت','settings','TravelModeSettings'),
('kurdish_sorani','settings.gold_feature','تایبەتمەندی گۆڵد','settings','TravelModeSettings'),
('kurdish_sorani','settings.travel_upgrade','بەرزکردنەوە بۆ گۆڵد بۆ دەرکەوتن لە شارەکانی تر','settings','TravelModeSettings'),
('kurdish_sorani','settings.enable_travel','چالاککردنی دۆخی گەشت','settings','TravelModeSettings'),
('kurdish_sorani','settings.select_city','شار هەڵبژێرە','settings','TravelModeSettings'),
('kurdish_sorani','settings.choose_city','شارێک هەڵبژێرە...','settings','TravelModeSettings'),
('kurdish_sorani','settings.custom_location','یان شوێنێکی تایبەت بنووسە','settings','TravelModeSettings'),
('kurdish_sorani','settings.enter_city','ناوی شار بنووسە...','settings','TravelModeSettings'),
('kurdish_sorani','settings.travel_description','پرۆفایلەکەت لە شوێنی گەشتکردنت دەردەکەوێت نەک لە شارەکەت. شوێنی ڕاستەقینەت تایبەت دەمێنێتەوە.','settings','TravelModeSettings'),
('kurdish_sorani','settings.save_travel','پاشەکەوتکردنی دۆخی گەشت','settings','TravelModeSettings'),
('kurdish_sorani','toast.password.change_failed','نەتوانرا وشەی نهێنی بگۆڕدرێت. تکایە دووبارە هەوڵ بدەوە.','toast','ChangePasswordDialog'),
('kurdish_sorani','settings.change_password','گۆڕینی وشەی نهێنی','settings','ChangePasswordDialog'),
('kurdish_sorani','settings.current_password','وشەی نهێنی ئێستا','settings','ChangePasswordDialog'),
('kurdish_sorani','settings.enter_current_password','وشەی نهێنی ئێستا بنووسە','settings','ChangePasswordDialog'),
('kurdish_sorani','settings.new_password','وشەی نهێنی نوێ','settings','ChangePasswordDialog'),
('kurdish_sorani','settings.enter_new_password','وشەی نهێنی نوێ بنووسە','settings','ChangePasswordDialog'),
('kurdish_sorani','settings.confirm_new_password','دووپاتکردنەوەی وشەی نهێنی نوێ','settings','ChangePasswordDialog'),
('kurdish_sorani','settings.confirm_new_password_placeholder','وشەی نهێنی نوێ دووبارە بنووسە','settings','ChangePasswordDialog'),
('kurdish_sorani','settings.password_requirements','مەرجەکانی وشەی نهێنی','settings','ChangePasswordDialog'),
('kurdish_sorani','settings.changing_password','دەگۆڕدرێت...','settings','ChangePasswordDialog'),
('kurdish_sorani','toast.swipe.like_profile_failed','نەتوانرا پرۆفایل لایک بکرێت','toast','ProfileSwipeActions'),
('kurdish_sorani','events.full','پڕ','events','EventCard'),
('kurdish_sorani','events.attending','بەشداربوو','events','EventCard'),
('kurdish_sorani','events.max','زۆرترین','events','EventCard'),
('kurdish_sorani','events.organized_by','ڕێکخراوە لەلایەن','events','EventCard'),
('kurdish_sorani','events.leave_event','جێهێشتنی بۆنە','events','EventCard'),
('kurdish_sorani','events.event_full','بۆنە پڕە','events','EventCard'),
('kurdish_sorani','events.join_event','بەشداری بۆنە','events','EventCard'),
('kurdish_sorani','admin.add_question_failed','نەتوانرا پرسیار زیاد بکرێت','admin','useQuestions'),
('kurdish_sorani','toast.date.response_failed','نەتوانرا وەڵام بدرێتەوە','toast','GiftsAndDates'),
('kurdish_sorani','toast.date.cancel_failed','نەتوانرا هەڵوەشێنرێتەوە','toast','GiftsAndDates'),
('kurdish_sorani','gifts.title','دیاری و میعاد','gifts','GiftsAndDates'),
('kurdish_sorani','gifts.received','وەرگیراو','gifts','GiftsAndDates'),
('kurdish_sorani','gifts.sent','نێردراو','gifts','GiftsAndDates'),
('kurdish_sorani','gifts.dates','میعادەکان','gifts','GiftsAndDates'),
('kurdish_sorani','gifts.no_received','هێشتا هیچ دیارییەک وەرنەگیراوە','gifts','GiftsAndDates'),
('kurdish_sorani','gifts.from','لە','gifts','GiftsAndDates'),
('kurdish_sorani','gifts.someone','کەسێک','gifts','GiftsAndDates'),
('kurdish_sorani','common.new','نوێ','common','GiftsAndDates'),
('kurdish_sorani','gifts.no_sent','هێشتا هیچ دیارییەک نەنێردراوە','gifts','GiftsAndDates'),
('kurdish_sorani','gifts.no_dates','هێشتا هیچ پێشنیاری میعادێک نییە','gifts','GiftsAndDates'),
('kurdish_sorani','gifts.to','بۆ','gifts','GiftsAndDates'),
('kurdish_sorani','common.accept','پەسەندکردن','common','GiftsAndDates'),
('kurdish_sorani','common.decline','ڕەتکردنەوە','common','GiftsAndDates'),
('kurdish_sorani','gifts.cancel_invitation','هەڵوەشاندنەوەی بانگهێشت','gifts','GiftsAndDates'),
-- Kurdish Kurmanji
('kurdish_kurmanji','toast.event.create_failed','Çêkirina bûyerê bi ser neket','toast','CreateEventModal'),
('kurdish_kurmanji','events.create_event','Bûyerê çêke','events','CreateEventModal'),
('kurdish_kurmanji','events.event_title','Navê bûyerê','events','CreateEventModal'),
('kurdish_kurmanji','events.title_placeholder','mînak, Şeva Çanda Kurdî','events','CreateEventModal'),
('kurdish_kurmanji','events.describe_placeholder','Bûyera xwe binivîse...','events','CreateEventModal'),
('kurdish_kurmanji','events.date_time','Dîrok û Dem','events','CreateEventModal'),
('kurdish_kurmanji','events.location_placeholder','Cihê bûyerê','events','CreateEventModal'),
('kurdish_kurmanji','events.category_placeholder','mînak, Çand, Werzîş, Muzîk','events','CreateEventModal'),
('kurdish_kurmanji','events.max_attendees','Hejmara herî zêde','events','CreateEventModal'),
('kurdish_kurmanji','events.image_url','Lînka wêneyê bûyerê','events','CreateEventModal'),
('kurdish_kurmanji','common.creating','Tê çêkirin...','common','CreateEventModal'),
('kurdish_kurmanji','toast.travel.activated','Moda rêwîtiyê çalak bû!','toast','TravelModeSettings'),
('kurdish_kurmanji','toast.travel.deactivated','Moda rêwîtiyê neçalak bû','toast','TravelModeSettings'),
('kurdish_kurmanji','settings.travel_mode','Moda Rêwîtiyê','settings','TravelModeSettings'),
('kurdish_kurmanji','settings.gold_feature','Taybetmendiya Gold','settings','TravelModeSettings'),
('kurdish_kurmanji','settings.travel_upgrade','Ji bo ku di bajarên din de xuya bibî bilind bike bo Gold','settings','TravelModeSettings'),
('kurdish_kurmanji','settings.enable_travel','Moda rêwîtiyê çalak bike','settings','TravelModeSettings'),
('kurdish_kurmanji','settings.select_city','Bajar hilbijêre','settings','TravelModeSettings'),
('kurdish_kurmanji','settings.choose_city','Bajarekî hilbijêre...','settings','TravelModeSettings'),
('kurdish_kurmanji','settings.custom_location','An jî cihekî taybet binivîse','settings','TravelModeSettings'),
('kurdish_kurmanji','settings.enter_city','Navê bajar binivîse...','settings','TravelModeSettings'),
('kurdish_kurmanji','settings.travel_description','Profîla te li vê cihê xuya dibe li şûna bajarê te. Cihê te yê rastîn veşartî dimîne.','settings','TravelModeSettings'),
('kurdish_kurmanji','settings.save_travel','Moda rêwîtiyê tomar bike','settings','TravelModeSettings'),
('kurdish_kurmanji','toast.password.change_failed','Şîfre nehat guhertin. Ji kerema xwe dîsa biceribîne.','toast','ChangePasswordDialog'),
('kurdish_kurmanji','settings.change_password','Şîfreyê biguherîne','settings','ChangePasswordDialog'),
('kurdish_kurmanji','settings.current_password','Şîfreya niha','settings','ChangePasswordDialog'),
('kurdish_kurmanji','settings.enter_current_password','Şîfreya niha binivîse','settings','ChangePasswordDialog'),
('kurdish_kurmanji','settings.new_password','Şîfreya nû','settings','ChangePasswordDialog'),
('kurdish_kurmanji','settings.enter_new_password','Şîfreya nû binivîse','settings','ChangePasswordDialog'),
('kurdish_kurmanji','settings.confirm_new_password','Şîfreya nû piştrast bike','settings','ChangePasswordDialog'),
('kurdish_kurmanji','settings.confirm_new_password_placeholder','Şîfreya nû piştrast bike','settings','ChangePasswordDialog'),
('kurdish_kurmanji','settings.password_requirements','Pêdiviyên şîfreyê','settings','ChangePasswordDialog'),
('kurdish_kurmanji','settings.changing_password','Tê guhertin...','settings','ChangePasswordDialog'),
('kurdish_kurmanji','toast.swipe.like_profile_failed','Profîl nehat like kirin','toast','ProfileSwipeActions'),
('kurdish_kurmanji','events.full','Tije','events','EventCard'),
('kurdish_kurmanji','events.attending','beşdar','events','EventCard'),
('kurdish_kurmanji','events.max','herî zêde','events','EventCard'),
('kurdish_kurmanji','events.organized_by','Ji aliyê ve','events','EventCard'),
('kurdish_kurmanji','events.leave_event','Bûyerê bihêle','events','EventCard'),
('kurdish_kurmanji','events.event_full','Bûyer tije ye','events','EventCard'),
('kurdish_kurmanji','events.join_event','Beşdarî bûyerê bibe','events','EventCard'),
('kurdish_kurmanji','admin.add_question_failed','Pirsiyar nehat zêdekirin','admin','useQuestions'),
('kurdish_kurmanji','toast.date.response_failed','Bersiv nehat dayîn','toast','GiftsAndDates'),
('kurdish_kurmanji','toast.date.cancel_failed','Betalkirin bi ser neket','toast','GiftsAndDates'),
('kurdish_kurmanji','gifts.title','Diyarî û Mîtîng','gifts','GiftsAndDates'),
('kurdish_kurmanji','gifts.received','Wergirtî','gifts','GiftsAndDates'),
('kurdish_kurmanji','gifts.sent','Şandî','gifts','GiftsAndDates'),
('kurdish_kurmanji','gifts.dates','Mîtîng','gifts','GiftsAndDates'),
('kurdish_kurmanji','gifts.no_received','Hêj diyarî nehatiye wergirtin','gifts','GiftsAndDates'),
('kurdish_kurmanji','gifts.from','Ji','gifts','GiftsAndDates'),
('kurdish_kurmanji','gifts.someone','Kesek','gifts','GiftsAndDates'),
('kurdish_kurmanji','common.new','Nû','common','GiftsAndDates'),
('kurdish_kurmanji','gifts.no_sent','Hêj diyarî nehatiye şandin','gifts','GiftsAndDates'),
('kurdish_kurmanji','gifts.no_dates','Hêj pêşniyara mîtîngê tune','gifts','GiftsAndDates'),
('kurdish_kurmanji','gifts.to','Bo','gifts','GiftsAndDates'),
('kurdish_kurmanji','common.accept','Qebûl bike','common','GiftsAndDates'),
('kurdish_kurmanji','common.decline','Red bike','common','GiftsAndDates'),
('kurdish_kurmanji','gifts.cancel_invitation','Vexwendinê betal bike','gifts','GiftsAndDates')
ON CONFLICT (language_code, translation_key) DO NOTHING;
