
-- Batch 11: Remaining admin components translations
INSERT INTO public.app_translations (language_code, translation_key, translation_value, category) VALUES
-- Roles components
('english', 'admin.create_new_role', 'Create New Role', 'admin'),
('english', 'admin.define_new_role', 'Define a new role with custom permissions.', 'admin'),
('english', 'admin.role_name', 'Role Name', 'admin'),
('english', 'admin.description', 'Description', 'admin'),
('english', 'admin.base_permissions_on', 'Base Permissions On', 'admin'),
('english', 'admin.start_from_scratch', 'Start from scratch', 'admin'),
('english', 'admin.clone_existing_role', 'Clone existing role', 'admin'),
('english', 'admin.select_role_to_clone', 'Select Role to Clone', 'admin'),
('english', 'admin.permission_sets', 'Permission Sets', 'admin'),
('english', 'admin.user_management', 'User Management', 'admin'),
('english', 'admin.content_management', 'Content Management', 'admin'),
('english', 'admin.configure_detailed_permissions', 'Configure Detailed Permissions', 'admin'),
('english', 'admin.create_role', 'Create Role', 'admin'),
('english', 'admin.role_name_header', 'Role Name', 'admin'),
('english', 'admin.users', 'Users', 'admin'),
('english', 'admin.type', 'Type', 'admin'),
('english', 'admin.system', 'System', 'admin'),
('english', 'admin.custom', 'Custom', 'admin'),
('english', 'admin.view', 'View', 'admin'),
('english', 'admin.delete', 'Delete', 'admin'),
('english', 'admin.no_roles_found', 'No roles found', 'admin'),
('english', 'admin.search_roles', 'Search roles...', 'admin'),
('english', 'admin.ai_role_recommendations', 'AI Role Recommendations', 'admin'),
('english', 'admin.ai_role_suggestions_desc', 'Suggested role configurations based on usage patterns', 'admin'),
('english', 'admin.moderator_role_optimization', 'Moderator Role Optimization', 'admin'),
('english', 'admin.moderator_optimization_desc', 'Moderators are rarely using the report creation functionality but frequently need to export content for review. Consider adjusting permissions to remove report creation and add export capabilities.', 'admin'),
('english', 'admin.apply_recommendation', 'Apply Recommendation', 'admin'),
('english', 'admin.new_role_suggestion', 'New Role Suggestion: Content Creator', 'admin'),
('english', 'admin.content_creator_desc', 'We''ve noticed a pattern where Marketing users need more granular content management permissions without user management access. A new "Content Creator" role could improve workflow efficiency.', 'admin'),
('english', 'admin.create_suggested_role', 'Create Suggested Role', 'admin'),
('english', 'admin.permission_settings', 'Permission Settings', 'admin'),
('english', 'admin.module', 'Module', 'admin'),
('english', 'admin.create', 'Create', 'admin'),
('english', 'admin.edit', 'Edit', 'admin'),
('english', 'admin.special', 'Special', 'admin'),
('english', 'admin.content', 'Content', 'admin'),
('english', 'admin.settings', 'Settings', 'admin'),
('english', 'admin.roles', 'Roles', 'admin'),
('english', 'admin.reports', 'Reports', 'admin'),
('english', 'admin.billing', 'Billing', 'admin'),
('english', 'admin.system_role', 'System Role', 'admin'),
('english', 'admin.custom_role', 'Custom Role', 'admin'),
('english', 'admin.users_assigned', 'users assigned', 'admin'),
('english', 'admin.edit_permissions', 'Edit Permissions', 'admin'),
('english', 'admin.save_changes', 'Save Changes', 'admin'),
('english', 'common.cancel', 'Cancel', 'common'),
('english', 'common.close', 'Close', 'common'),
-- Photos page
('english', 'admin.photo_management', 'Photo Management', 'admin'),
('english', 'admin.manage_moderate_photos', 'Manage and moderate user photos', 'admin'),
('english', 'common.refresh', 'Refresh', 'admin'),
('english', 'admin.search_by_user', 'Search by user name...', 'admin'),
('english', 'common.search', 'Search', 'common'),
('english', 'admin.loading_photos', 'Loading photos...', 'admin'),
('english', 'admin.no_photos_found', 'No photos found', 'admin'),
('english', 'admin.adjust_search', 'Try adjusting your search query', 'admin'),
('english', 'admin.primary', 'Primary', 'admin'),
('english', 'admin.unknown_user', 'Unknown User', 'admin'),
('english', 'admin.photo_details', 'Photo Details', 'admin'),
('english', 'admin.photo_information', 'Photo Information', 'admin'),
('english', 'admin.user_label', 'User:', 'admin'),
('english', 'admin.upload_date', 'Upload Date:', 'admin'),
('english', 'common.status', 'Status:', 'admin'),
('english', 'admin.primary_photo', 'Primary Photo', 'admin'),
('english', 'admin.additional_photo', 'Additional Photo', 'admin'),
('english', 'admin.delete_photo', 'Delete Photo', 'admin'),
('english', 'common.previous', 'Previous', 'common'),
('english', 'common.next', 'Next', 'common'),
-- Users components
('english', 'admin.total_users', 'Total Users', 'admin'),
('english', 'admin.active_users', 'Active Users', 'admin'),
('english', 'admin.pending', 'Pending', 'admin'),
('english', 'admin.inactive', 'Inactive', 'admin'),
('english', 'admin.loading_user_stats', 'Loading user statistics...', 'admin'),
('english', 'admin.no_real_users', 'No real users yet', 'admin'),
('english', 'admin.db_user_verification', 'Database User Verification', 'admin'),
('english', 'admin.verified_users_count', 'Verified {{count}} total registered users in database', 'admin'),
('english', 'admin.verifying_users', 'Verifying users in database...', 'admin'),
('english', 'admin.search_users_placeholder', 'Search by name, email, or location...', 'admin'),
('english', 'admin.all_status', 'All Status', 'admin'),
('english', 'admin.active', 'Active', 'admin'),
('english', 'admin.suspended', 'Suspended', 'admin'),
('english', 'admin.all_roles', 'All Roles', 'admin'),
('english', 'admin.user', 'User', 'admin'),
('english', 'admin.premium', 'Premium', 'admin'),
('english', 'admin.moderator', 'Moderator', 'admin'),
('english', 'admin.admin', 'Admin', 'admin'),
('english', 'admin.per_page', '{{count}} per page', 'admin'),
('english', 'admin.users_per_page', 'Users per page', 'admin'),
('english', 'common.actions', 'Actions', 'common'),
('english', 'admin.view_details', 'View Details', 'admin'),
('english', 'admin.edit_user', 'Edit User', 'admin'),
('english', 'admin.delete_user', 'Delete User', 'admin'),
('english', 'admin.user_details', 'User Details', 'admin'),
('english', 'admin.view_user_info', 'View complete information about this user.', 'admin'),
('english', 'admin.edit_user_profile', 'Make changes to the user profile.', 'admin'),
('english', 'admin.basic_information', 'Basic Information', 'admin'),
('english', 'admin.name', 'Name', 'admin'),
('english', 'admin.email', 'Email', 'admin'),
('english', 'admin.role', 'Role', 'admin'),
('english', 'admin.location_information', 'Location Information', 'admin'),
('english', 'admin.location', 'Location', 'admin'),
('english', 'admin.account_information', 'Account Information', 'admin'),
('english', 'admin.join_date', 'Join Date', 'admin'),
('english', 'admin.last_active', 'Last Active', 'admin'),
('english', 'admin.activity_statistics', 'Activity Statistics', 'admin'),
('english', 'admin.photos', 'Photos', 'admin'),
('english', 'admin.messages', 'Messages', 'admin'),
('english', 'admin.select_role', 'Select role', 'admin'),
('english', 'admin.select_status', 'Select status', 'admin'),
-- User dialogs
('english', 'admin.user_action', 'User Action', 'admin'),
('english', 'admin.permanently_delete_user', 'Permanently Delete User', 'admin'),
('english', 'admin.permanent_delete_warning', 'This will permanently delete {{name}} and ALL their data. This action cannot be undone.', 'admin'),
('english', 'admin.choose_action', 'Choose an action for', 'admin'),
('english', 'admin.deactivate', 'Deactivate', 'admin'),
('english', 'admin.permanent_delete', 'Permanent Delete', 'admin'),
('english', 'admin.go_back', 'Go Back', 'admin'),
('english', 'admin.yes_permanently_delete', 'Yes, Permanently Delete', 'admin'),
('english', 'admin.processing', 'Processing...', 'admin'),
('english', 'admin.deleting', 'Deleting...', 'admin'),
('english', 'admin.deactivate_users_by_role', 'Deactivate Users by Role', 'admin'),
('english', 'admin.deactivate_users_desc', 'Choose which users to deactivate based on their role. Their profiles will be hidden but their data will be preserved.', 'admin'),
('english', 'admin.deactivate_warning', 'This will deactivate ALL users with the selected role, not just the current page.', 'admin'),
('english', 'admin.regular_users', 'Regular Users', 'admin'),
('english', 'admin.moderators', 'Moderators', 'admin'),
('english', 'admin.admins', 'Admins', 'admin'),
('english', 'admin.deactivating', 'Deactivating...', 'admin'),
('english', 'admin.deactivate_users', 'Deactivate {{role}} Users', 'admin'),
('english', 'admin.clean_up_test_data', 'Clean Up Test Data', 'admin'),
('english', 'admin.clean_up_desc', 'Remove all automatically generated profiles, mock engagement data, and test content from the database. This will only keep real users who registered through your app.', 'admin'),
('english', 'admin.cleaning_up', 'Cleaning Up Test Data...', 'admin'),
('english', 'admin.clean_up_all', 'Clean Up All Test Data', 'admin'),
('english', 'admin.real_users_only', 'Real Users Only', 'admin'),
('english', 'admin.real_users_dialog_desc', 'This system now only shows real users who registered through the normal app registration process. All profile generation features have been disabled to ensure data authenticity.', 'admin'),
('english', 'admin.how_to_add_real_users', 'How to Add Real Users', 'admin'),
('english', 'admin.how_to_add_desc', 'To see users in this admin panel, they need to register through your app''s normal registration flow at /register. Test this by creating accounts through the regular user registration process.', 'admin'),
-- Question categories
('english', 'admin.question_categories', 'Question Categories', 'admin'),
('english', 'admin.all_questions', 'All Questions', 'admin'),

-- Norwegian translations
('norwegian', 'admin.create_new_role', 'Opprett ny rolle', 'admin'),
('norwegian', 'admin.define_new_role', 'Definer en ny rolle med egendefinerte tillatelser.', 'admin'),
('norwegian', 'admin.role_name', 'Rollenavn', 'admin'),
('norwegian', 'admin.description', 'Beskrivelse', 'admin'),
('norwegian', 'admin.base_permissions_on', 'Basistillatelser på', 'admin'),
('norwegian', 'admin.start_from_scratch', 'Start fra bunnen', 'admin'),
('norwegian', 'admin.clone_existing_role', 'Klon eksisterende rolle', 'admin'),
('norwegian', 'admin.select_role_to_clone', 'Velg rolle å klone', 'admin'),
('norwegian', 'admin.permission_sets', 'Tillatelsessett', 'admin'),
('norwegian', 'admin.content_management', 'Innholdsadministrasjon', 'admin'),
('norwegian', 'admin.configure_detailed_permissions', 'Konfigurer detaljerte tillatelser', 'admin'),
('norwegian', 'admin.create_role', 'Opprett rolle', 'admin'),
('norwegian', 'admin.role_name_header', 'Rollenavn', 'admin'),
('norwegian', 'admin.users', 'Brukere', 'admin'),
('norwegian', 'admin.type', 'Type', 'admin'),
('norwegian', 'admin.system', 'System', 'admin'),
('norwegian', 'admin.custom', 'Egendefinert', 'admin'),
('norwegian', 'admin.view', 'Vis', 'admin'),
('norwegian', 'admin.delete', 'Slett', 'admin'),
('norwegian', 'admin.no_roles_found', 'Ingen roller funnet', 'admin'),
('norwegian', 'admin.search_roles', 'Søk roller...', 'admin'),
('norwegian', 'admin.ai_role_recommendations', 'AI-rolleanbefalinger', 'admin'),
('norwegian', 'admin.ai_role_suggestions_desc', 'Foreslåtte rollekonfigurasjoner basert på bruksmønstre', 'admin'),
('norwegian', 'admin.moderator_role_optimization', 'Moderatorrolleoptimalisering', 'admin'),
('norwegian', 'admin.moderator_optimization_desc', 'Moderatorer bruker sjelden rapportopprettingsfunksjonaliteten, men trenger ofte å eksportere innhold for gjennomgang. Vurder å justere tillatelser.', 'admin'),
('norwegian', 'admin.apply_recommendation', 'Bruk anbefaling', 'admin'),
('norwegian', 'admin.new_role_suggestion', 'Nytt rolleforslag: Innholdsskaper', 'admin'),
('norwegian', 'admin.content_creator_desc', 'Vi har lagt merke til at markedsføringsbrukere trenger mer detaljerte innholdsadministrasjonstillatelser uten brukertilgang.', 'admin'),
('norwegian', 'admin.create_suggested_role', 'Opprett foreslått rolle', 'admin'),
('norwegian', 'admin.permission_settings', 'Tillatelsesinnstillinger', 'admin'),
('norwegian', 'admin.module', 'Modul', 'admin'),
('norwegian', 'admin.create', 'Opprett', 'admin'),
('norwegian', 'admin.edit', 'Rediger', 'admin'),
('norwegian', 'admin.special', 'Spesiell', 'admin'),
('norwegian', 'admin.content', 'Innhold', 'admin'),
('norwegian', 'admin.settings', 'Innstillinger', 'admin'),
('norwegian', 'admin.roles', 'Roller', 'admin'),
('norwegian', 'admin.reports', 'Rapporter', 'admin'),
('norwegian', 'admin.billing', 'Fakturering', 'admin'),
('norwegian', 'admin.system_role', 'Systemrolle', 'admin'),
('norwegian', 'admin.custom_role', 'Egendefinert rolle', 'admin'),
('norwegian', 'admin.users_assigned', 'brukere tildelt', 'admin'),
('norwegian', 'admin.edit_permissions', 'Rediger tillatelser', 'admin'),
('norwegian', 'admin.save_changes', 'Lagre endringer', 'admin'),
('norwegian', 'common.cancel', 'Avbryt', 'common'),
('norwegian', 'common.close', 'Lukk', 'common'),
('norwegian', 'admin.photo_management', 'Fotoadministrasjon', 'admin'),
('norwegian', 'admin.manage_moderate_photos', 'Administrer og moderer brukerbilder', 'admin'),
('norwegian', 'common.refresh', 'Oppdater', 'admin'),
('norwegian', 'admin.search_by_user', 'Søk etter brukernavn...', 'admin'),
('norwegian', 'common.search', 'Søk', 'common'),
('norwegian', 'admin.loading_photos', 'Laster bilder...', 'admin'),
('norwegian', 'admin.no_photos_found', 'Ingen bilder funnet', 'admin'),
('norwegian', 'admin.adjust_search', 'Prøv å justere søket ditt', 'admin'),
('norwegian', 'admin.primary', 'Primær', 'admin'),
('norwegian', 'admin.unknown_user', 'Ukjent bruker', 'admin'),
('norwegian', 'admin.photo_details', 'Bildedetaljer', 'admin'),
('norwegian', 'admin.photo_information', 'Bildeinformasjon', 'admin'),
('norwegian', 'admin.user_label', 'Bruker:', 'admin'),
('norwegian', 'admin.upload_date', 'Opplastingsdato:', 'admin'),
('norwegian', 'common.status', 'Status:', 'admin'),
('norwegian', 'admin.primary_photo', 'Primærbilde', 'admin'),
('norwegian', 'admin.additional_photo', 'Tilleggsbilde', 'admin'),
('norwegian', 'admin.delete_photo', 'Slett bilde', 'admin'),
('norwegian', 'common.previous', 'Forrige', 'common'),
('norwegian', 'common.next', 'Neste', 'common'),
('norwegian', 'admin.total_users', 'Totalt brukere', 'admin'),
('norwegian', 'admin.active_users', 'Aktive brukere', 'admin'),
('norwegian', 'admin.pending', 'Ventende', 'admin'),
('norwegian', 'admin.inactive', 'Inaktiv', 'admin'),
('norwegian', 'admin.loading_user_stats', 'Laster brukerstatistikk...', 'admin'),
('norwegian', 'admin.no_real_users', 'Ingen ekte brukere ennå', 'admin'),
('norwegian', 'admin.db_user_verification', 'Databasebrukerverifisering', 'admin'),
('norwegian', 'admin.verified_users_count', 'Verifisert {{count}} totalt registrerte brukere i databasen', 'admin'),
('norwegian', 'admin.verifying_users', 'Verifiserer brukere i databasen...', 'admin'),
('norwegian', 'admin.search_users_placeholder', 'Søk etter navn, e-post eller sted...', 'admin'),
('norwegian', 'admin.all_status', 'Alle statuser', 'admin'),
('norwegian', 'admin.active', 'Aktiv', 'admin'),
('norwegian', 'admin.suspended', 'Suspendert', 'admin'),
('norwegian', 'admin.all_roles', 'Alle roller', 'admin'),
('norwegian', 'admin.user', 'Bruker', 'admin'),
('norwegian', 'admin.premium', 'Premium', 'admin'),
('norwegian', 'admin.moderator', 'Moderator', 'admin'),
('norwegian', 'admin.admin', 'Administrator', 'admin'),
('norwegian', 'admin.per_page', '{{count}} per side', 'admin'),
('norwegian', 'admin.users_per_page', 'Brukere per side', 'admin'),
('norwegian', 'common.actions', 'Handlinger', 'common'),
('norwegian', 'admin.view_details', 'Vis detaljer', 'admin'),
('norwegian', 'admin.edit_user', 'Rediger bruker', 'admin'),
('norwegian', 'admin.delete_user', 'Slett bruker', 'admin'),
('norwegian', 'admin.user_details', 'Brukerdetaljer', 'admin'),
('norwegian', 'admin.view_user_info', 'Se fullstendig informasjon om denne brukeren.', 'admin'),
('norwegian', 'admin.edit_user_profile', 'Gjør endringer i brukerprofilen.', 'admin'),
('norwegian', 'admin.basic_information', 'Grunnleggende informasjon', 'admin'),
('norwegian', 'admin.name', 'Navn', 'admin'),
('norwegian', 'admin.email', 'E-post', 'admin'),
('norwegian', 'admin.role', 'Rolle', 'admin'),
('norwegian', 'admin.location_information', 'Stedsinformasjon', 'admin'),
('norwegian', 'admin.location', 'Sted', 'admin'),
('norwegian', 'admin.account_information', 'Kontoinformasjon', 'admin'),
('norwegian', 'admin.join_date', 'Ble med dato', 'admin'),
('norwegian', 'admin.last_active', 'Sist aktiv', 'admin'),
('norwegian', 'admin.activity_statistics', 'Aktivitetsstatistikk', 'admin'),
('norwegian', 'admin.photos', 'Bilder', 'admin'),
('norwegian', 'admin.messages', 'Meldinger', 'admin'),
('norwegian', 'admin.select_role', 'Velg rolle', 'admin'),
('norwegian', 'admin.select_status', 'Velg status', 'admin'),
('norwegian', 'admin.user_action', 'Brukerhandling', 'admin'),
('norwegian', 'admin.permanently_delete_user', 'Slett bruker permanent', 'admin'),
('norwegian', 'admin.permanent_delete_warning', 'Dette vil permanent slette {{name}} og ALLE dataene deres. Denne handlingen kan ikke angres.', 'admin'),
('norwegian', 'admin.choose_action', 'Velg en handling for', 'admin'),
('norwegian', 'admin.deactivate', 'Deaktiver', 'admin'),
('norwegian', 'admin.permanent_delete', 'Permanent sletting', 'admin'),
('norwegian', 'admin.go_back', 'Gå tilbake', 'admin'),
('norwegian', 'admin.yes_permanently_delete', 'Ja, slett permanent', 'admin'),
('norwegian', 'admin.processing', 'Behandler...', 'admin'),
('norwegian', 'admin.deleting', 'Sletter...', 'admin'),
('norwegian', 'admin.deactivate_users_by_role', 'Deaktiver brukere etter rolle', 'admin'),
('norwegian', 'admin.deactivate_users_desc', 'Velg hvilke brukere som skal deaktiveres basert på rollen deres. Profilene deres vil bli skjult, men dataene bevart.', 'admin'),
('norwegian', 'admin.deactivate_warning', 'Dette vil deaktivere ALLE brukere med den valgte rollen, ikke bare den nåværende siden.', 'admin'),
('norwegian', 'admin.regular_users', 'Vanlige brukere', 'admin'),
('norwegian', 'admin.moderators', 'Moderatorer', 'admin'),
('norwegian', 'admin.admins', 'Administratorer', 'admin'),
('norwegian', 'admin.deactivating', 'Deaktiverer...', 'admin'),
('norwegian', 'admin.deactivate_users', 'Deaktiver {{role}} brukere', 'admin'),
('norwegian', 'admin.clean_up_test_data', 'Rydd opp testdata', 'admin'),
('norwegian', 'admin.clean_up_desc', 'Fjern alle automatisk genererte profiler, mock-data og testinnhold fra databasen.', 'admin'),
('norwegian', 'admin.cleaning_up', 'Rydder opp testdata...', 'admin'),
('norwegian', 'admin.clean_up_all', 'Rydd opp all testdata', 'admin'),
('norwegian', 'admin.real_users_dialog_desc', 'Dette systemet viser nå kun ekte brukere som registrerte seg gjennom den normale registreringsprosessen.', 'admin'),
('norwegian', 'admin.how_to_add_real_users', 'Hvordan legge til ekte brukere', 'admin'),
('norwegian', 'admin.how_to_add_desc', 'For å se brukere i dette adminpanelet, må de registrere seg gjennom appens normale registreringsflyt på /register.', 'admin'),
('norwegian', 'admin.question_categories', 'Spørsmålskategorier', 'admin'),
('norwegian', 'admin.all_questions', 'Alle spørsmål', 'admin'),

-- Kurdish Sorani
('kurdish_sorani', 'admin.create_new_role', 'دروستکردنی ڕۆڵی نوێ', 'admin'),
('kurdish_sorani', 'admin.role_name', 'ناوی ڕۆڵ', 'admin'),
('kurdish_sorani', 'admin.description', 'وەسف', 'admin'),
('kurdish_sorani', 'admin.view', 'بینین', 'admin'),
('kurdish_sorani', 'admin.delete', 'سڕینەوە', 'admin'),
('kurdish_sorani', 'admin.create', 'دروستکردن', 'admin'),
('kurdish_sorani', 'admin.edit', 'دەستکاری', 'admin'),
('kurdish_sorani', 'common.cancel', 'پاشگەزبوونەوە', 'common'),
('kurdish_sorani', 'common.close', 'داخستن', 'common'),
('kurdish_sorani', 'common.search', 'گەڕان', 'common'),
('kurdish_sorani', 'common.refresh', 'نوێکردنەوە', 'admin'),
('kurdish_sorani', 'common.previous', 'پێشوو', 'common'),
('kurdish_sorani', 'common.next', 'دواتر', 'common'),
('kurdish_sorani', 'admin.photo_management', 'بەڕێوەبردنی وێنە', 'admin'),
('kurdish_sorani', 'admin.total_users', 'کۆی بەکارهێنەران', 'admin'),
('kurdish_sorani', 'admin.active_users', 'بەکارهێنەرانی چالاک', 'admin'),
('kurdish_sorani', 'admin.pending', 'چاوەڕوان', 'admin'),
('kurdish_sorani', 'admin.inactive', 'ناچالاک', 'admin'),
('kurdish_sorani', 'admin.question_categories', 'پۆلەکانی پرسیار', 'admin'),
('kurdish_sorani', 'admin.all_questions', 'هەموو پرسیارەکان', 'admin'),
('kurdish_sorani', 'common.actions', 'کردارەکان', 'common'),
('kurdish_sorani', 'admin.save_changes', 'پاشەکەوتکردنی گۆڕانکارییەکان', 'admin'),

-- Kurdish Kurmanci
('kurdish_kurmanci', 'admin.create_new_role', 'Rola nû biafirîne', 'admin'),
('kurdish_kurmanci', 'admin.role_name', 'Navê rolê', 'admin'),
('kurdish_kurmanci', 'admin.description', 'Danasîn', 'admin'),
('kurdish_kurmanci', 'admin.view', 'Dîtin', 'admin'),
('kurdish_kurmanci', 'admin.delete', 'Jêbirin', 'admin'),
('kurdish_kurmanci', 'admin.create', 'Afirandin', 'admin'),
('kurdish_kurmanci', 'admin.edit', 'Guhertin', 'admin'),
('kurdish_kurmanci', 'common.cancel', 'Betal bike', 'common'),
('kurdish_kurmanci', 'common.close', 'Bigire', 'common'),
('kurdish_kurmanci', 'common.search', 'Lêgerîn', 'common'),
('kurdish_kurmanci', 'common.refresh', 'Nûkirin', 'admin'),
('kurdish_kurmanci', 'common.previous', 'Berê', 'common'),
('kurdish_kurmanci', 'common.next', 'Pêş', 'common'),
('kurdish_kurmanci', 'admin.photo_management', 'Rêveberiya wêneyan', 'admin'),
('kurdish_kurmanci', 'admin.total_users', 'Tevahiya bikarhêneran', 'admin'),
('kurdish_kurmanci', 'admin.active_users', 'Bikarhênerên çalak', 'admin'),
('kurdish_kurmanci', 'admin.pending', 'Li benda', 'admin'),
('kurdish_kurmanci', 'admin.inactive', 'Neçalak', 'admin'),
('kurdish_kurmanci', 'admin.question_categories', 'Kategoriyên pirsan', 'admin'),
('kurdish_kurmanci', 'admin.all_questions', 'Hemû pirs', 'admin'),
('kurdish_kurmanci', 'common.actions', 'Kiryar', 'common'),
('kurdish_kurmanci', 'admin.save_changes', 'Guhertinan tomar bike', 'admin'),

-- German
('german', 'admin.create_new_role', 'Neue Rolle erstellen', 'admin'),
('german', 'admin.define_new_role', 'Definieren Sie eine neue Rolle mit benutzerdefinierten Berechtigungen.', 'admin'),
('german', 'admin.role_name', 'Rollenname', 'admin'),
('german', 'admin.description', 'Beschreibung', 'admin'),
('german', 'admin.base_permissions_on', 'Berechtigungen basieren auf', 'admin'),
('german', 'admin.start_from_scratch', 'Von Grund auf beginnen', 'admin'),
('german', 'admin.clone_existing_role', 'Bestehende Rolle klonen', 'admin'),
('german', 'admin.select_role_to_clone', 'Rolle zum Klonen auswählen', 'admin'),
('german', 'admin.permission_sets', 'Berechtigungssätze', 'admin'),
('german', 'admin.content_management', 'Inhaltsverwaltung', 'admin'),
('german', 'admin.configure_detailed_permissions', 'Detaillierte Berechtigungen konfigurieren', 'admin'),
('german', 'admin.create_role', 'Rolle erstellen', 'admin'),
('german', 'admin.role_name_header', 'Rollenname', 'admin'),
('german', 'admin.users', 'Benutzer', 'admin'),
('german', 'admin.type', 'Typ', 'admin'),
('german', 'admin.system', 'System', 'admin'),
('german', 'admin.custom', 'Benutzerdefiniert', 'admin'),
('german', 'admin.view', 'Ansehen', 'admin'),
('german', 'admin.delete', 'Löschen', 'admin'),
('german', 'admin.no_roles_found', 'Keine Rollen gefunden', 'admin'),
('german', 'admin.search_roles', 'Rollen suchen...', 'admin'),
('german', 'admin.ai_role_recommendations', 'KI-Rollenempfehlungen', 'admin'),
('german', 'admin.ai_role_suggestions_desc', 'Vorgeschlagene Rollenkonfigurationen basierend auf Nutzungsmustern', 'admin'),
('german', 'admin.apply_recommendation', 'Empfehlung anwenden', 'admin'),
('german', 'admin.create_suggested_role', 'Vorgeschlagene Rolle erstellen', 'admin'),
('german', 'admin.permission_settings', 'Berechtigungseinstellungen', 'admin'),
('german', 'admin.module', 'Modul', 'admin'),
('german', 'admin.create', 'Erstellen', 'admin'),
('german', 'admin.edit', 'Bearbeiten', 'admin'),
('german', 'admin.special', 'Spezial', 'admin'),
('german', 'admin.content', 'Inhalt', 'admin'),
('german', 'admin.settings', 'Einstellungen', 'admin'),
('german', 'admin.roles', 'Rollen', 'admin'),
('german', 'admin.reports', 'Berichte', 'admin'),
('german', 'admin.billing', 'Abrechnung', 'admin'),
('german', 'admin.system_role', 'Systemrolle', 'admin'),
('german', 'admin.custom_role', 'Benutzerdefinierte Rolle', 'admin'),
('german', 'admin.users_assigned', 'Benutzer zugewiesen', 'admin'),
('german', 'admin.edit_permissions', 'Berechtigungen bearbeiten', 'admin'),
('german', 'admin.save_changes', 'Änderungen speichern', 'admin'),
('german', 'common.cancel', 'Abbrechen', 'common'),
('german', 'common.close', 'Schließen', 'common'),
('german', 'admin.photo_management', 'Fotoverwaltung', 'admin'),
('german', 'admin.manage_moderate_photos', 'Benutzerfotos verwalten und moderieren', 'admin'),
('german', 'common.refresh', 'Aktualisieren', 'admin'),
('german', 'admin.search_by_user', 'Nach Benutzername suchen...', 'admin'),
('german', 'common.search', 'Suchen', 'common'),
('german', 'admin.loading_photos', 'Fotos werden geladen...', 'admin'),
('german', 'admin.no_photos_found', 'Keine Fotos gefunden', 'admin'),
('german', 'admin.adjust_search', 'Versuchen Sie, Ihre Suche anzupassen', 'admin'),
('german', 'admin.primary', 'Primär', 'admin'),
('german', 'admin.unknown_user', 'Unbekannter Benutzer', 'admin'),
('german', 'admin.photo_details', 'Fotodetails', 'admin'),
('german', 'admin.photo_information', 'Fotoinformationen', 'admin'),
('german', 'admin.primary_photo', 'Primärfoto', 'admin'),
('german', 'admin.additional_photo', 'Zusätzliches Foto', 'admin'),
('german', 'admin.delete_photo', 'Foto löschen', 'admin'),
('german', 'common.previous', 'Zurück', 'common'),
('german', 'common.next', 'Weiter', 'common'),
('german', 'admin.total_users', 'Gesamtbenutzer', 'admin'),
('german', 'admin.active_users', 'Aktive Benutzer', 'admin'),
('german', 'admin.pending', 'Ausstehend', 'admin'),
('german', 'admin.inactive', 'Inaktiv', 'admin'),
('german', 'admin.loading_user_stats', 'Benutzerstatistiken werden geladen...', 'admin'),
('german', 'admin.no_real_users', 'Noch keine echten Benutzer', 'admin'),
('german', 'admin.search_users_placeholder', 'Nach Name, E-Mail oder Ort suchen...', 'admin'),
('german', 'admin.all_status', 'Alle Status', 'admin'),
('german', 'admin.active', 'Aktiv', 'admin'),
('german', 'admin.suspended', 'Gesperrt', 'admin'),
('german', 'admin.all_roles', 'Alle Rollen', 'admin'),
('german', 'admin.user', 'Benutzer', 'admin'),
('german', 'admin.premium', 'Premium', 'admin'),
('german', 'admin.moderator', 'Moderator', 'admin'),
('german', 'admin.admin', 'Administrator', 'admin'),
('german', 'common.actions', 'Aktionen', 'common'),
('german', 'admin.view_details', 'Details ansehen', 'admin'),
('german', 'admin.edit_user', 'Benutzer bearbeiten', 'admin'),
('german', 'admin.delete_user', 'Benutzer löschen', 'admin'),
('german', 'admin.user_details', 'Benutzerdetails', 'admin'),
('german', 'admin.basic_information', 'Grundinformationen', 'admin'),
('german', 'admin.name', 'Name', 'admin'),
('german', 'admin.email', 'E-Mail', 'admin'),
('german', 'admin.role', 'Rolle', 'admin'),
('german', 'admin.location', 'Standort', 'admin'),
('german', 'admin.join_date', 'Beitrittsdatum', 'admin'),
('german', 'admin.last_active', 'Zuletzt aktiv', 'admin'),
('german', 'admin.photos', 'Fotos', 'admin'),
('german', 'admin.messages', 'Nachrichten', 'admin'),
('german', 'admin.deactivate', 'Deaktivieren', 'admin'),
('german', 'admin.permanent_delete', 'Endgültig löschen', 'admin'),
('german', 'admin.go_back', 'Zurück', 'admin'),
('german', 'admin.processing', 'Verarbeitung...', 'admin'),
('german', 'admin.deleting', 'Löschung...', 'admin'),
('german', 'admin.question_categories', 'Fragenkategorien', 'admin'),
('german', 'admin.all_questions', 'Alle Fragen', 'admin')
ON CONFLICT (language_code, translation_key) DO UPDATE SET translation_value = EXCLUDED.translation_value;
