
INSERT INTO public.app_translations (language_code, translation_key, translation_value, category, context) VALUES
-- Common buttons
('english','common.cancel','Cancel','common','Editor buttons'),
('english','common.save','Save','common','Editor buttons'),
('english','common.save_changes','Save Changes','common','Editor buttons'),
('english','common.see_less','See less','common','BasicInfoEditor'),
('english','common.see_more_languages','See more languages (+{{count}})','common','BasicInfoEditor'),
('norwegian','common.cancel','Avbryt','common','Editor buttons'),
('norwegian','common.save','Lagre','common','Editor buttons'),
('norwegian','common.save_changes','Lagre endringer','common','Editor buttons'),
('norwegian','common.see_less','Se mindre','common','BasicInfoEditor'),
('norwegian','common.see_more_languages','Se flere språk (+{{count}})','common','BasicInfoEditor'),
('german','common.cancel','Abbrechen','common','Editor buttons'),
('german','common.save','Speichern','common','Editor buttons'),
('german','common.save_changes','Änderungen speichern','common','Editor buttons'),
('german','common.see_less','Weniger anzeigen','common','BasicInfoEditor'),
('german','common.see_more_languages','Mehr Sprachen (+{{count}})','common','BasicInfoEditor'),
('kurdish_sorani','common.cancel','پاشگەزبوونەوە','common','Editor buttons'),
('kurdish_sorani','common.save','پاشەکەوتکردن','common','Editor buttons'),
('kurdish_sorani','common.save_changes','گۆڕانکارییەکان پاشەکەوت بکە','common','Editor buttons'),
('kurdish_sorani','common.see_less','کەمتر ببینە','common','BasicInfoEditor'),
('kurdish_sorani','common.see_more_languages','زمانی زیاتر (+{{count}})','common','BasicInfoEditor'),
('kurdish_kurmanji','common.cancel','Betal bike','common','Editor buttons'),
('kurdish_kurmanji','common.save','Tomar bike','common','Editor buttons'),
('kurdish_kurmanji','common.save_changes','Guhertinan tomar bike','common','Editor buttons'),
('kurdish_kurmanji','common.see_less','Kêmtir bibîne','common','BasicInfoEditor'),
('kurdish_kurmanji','common.see_more_languages','Bêtir ziman (+{{count}})','common','BasicInfoEditor'),

-- BasicInfoEditor labels
('english','profile.full_name','Full Name','profile','BasicInfoEditor'),
('english','profile.age','Age','profile','BasicInfoEditor'),
('english','profile.height','Height','profile','BasicInfoEditor'),
('english','profile.ethnicity','Ethnicity','profile','BasicInfoEditor'),
('english','profile.location','Location','profile','BasicInfoEditor'),
('english','profile.kurdistan_region','Kurdistan Region','profile','BasicInfoEditor'),
('english','profile.kurdish_dialects','Kurdish Dialects','profile','BasicInfoEditor'),
('english','profile.languages','Languages','profile','BasicInfoEditor'),
('norwegian','profile.full_name','Fullt navn','profile','BasicInfoEditor'),
('norwegian','profile.age','Alder','profile','BasicInfoEditor'),
('norwegian','profile.height','Høyde','profile','BasicInfoEditor'),
('norwegian','profile.ethnicity','Etnisitet','profile','BasicInfoEditor'),
('norwegian','profile.location','Sted','profile','BasicInfoEditor'),
('norwegian','profile.kurdistan_region','Kurdistan-region','profile','BasicInfoEditor'),
('norwegian','profile.kurdish_dialects','Kurdiske dialekter','profile','BasicInfoEditor'),
('norwegian','profile.languages','Språk','profile','BasicInfoEditor'),
('german','profile.full_name','Vollständiger Name','profile','BasicInfoEditor'),
('german','profile.age','Alter','profile','BasicInfoEditor'),
('german','profile.height','Größe','profile','BasicInfoEditor'),
('german','profile.ethnicity','Ethnizität','profile','BasicInfoEditor'),
('german','profile.location','Standort','profile','BasicInfoEditor'),
('german','profile.kurdistan_region','Kurdistan-Region','profile','BasicInfoEditor'),
('german','profile.kurdish_dialects','Kurdische Dialekte','profile','BasicInfoEditor'),
('german','profile.languages','Sprachen','profile','BasicInfoEditor'),
('kurdish_sorani','profile.full_name','ناوی تەواو','profile','BasicInfoEditor'),
('kurdish_sorani','profile.age','تەمەن','profile','BasicInfoEditor'),
('kurdish_sorani','profile.height','باڵا','profile','BasicInfoEditor'),
('kurdish_sorani','profile.ethnicity','ڕەگەز','profile','BasicInfoEditor'),
('kurdish_sorani','profile.location','شوێن','profile','BasicInfoEditor'),
('kurdish_sorani','profile.kurdistan_region','هەرێمی کوردستان','profile','BasicInfoEditor'),
('kurdish_sorani','profile.kurdish_dialects','زاراوەکانی کوردی','profile','BasicInfoEditor'),
('kurdish_sorani','profile.languages','زمانەکان','profile','BasicInfoEditor'),
('kurdish_kurmanji','profile.full_name','Navê tevahî','profile','BasicInfoEditor'),
('kurdish_kurmanji','profile.age','Temen','profile','BasicInfoEditor'),
('kurdish_kurmanji','profile.height','Bilindahî','profile','BasicInfoEditor'),
('kurdish_kurmanji','profile.ethnicity','Etnîsîte','profile','BasicInfoEditor'),
('kurdish_kurmanji','profile.location','Cih','profile','BasicInfoEditor'),
('kurdish_kurmanji','profile.kurdistan_region','Herêma Kurdistanê','profile','BasicInfoEditor'),
('kurdish_kurmanji','profile.kurdish_dialects','Zaravayên Kurdî','profile','BasicInfoEditor'),
('kurdish_kurmanji','profile.languages','Ziman','profile','BasicInfoEditor'),

-- EducationCareerEditor labels
('english','profile.education_level','Education Level','profile','EducationCareerEditor'),
('english','profile.work_life_balance','Work-Life Balance','profile','EducationCareerEditor'),
('english','profile.occupation','Occupation','profile','EducationCareerEditor'),
('english','profile.company','Company','profile','EducationCareerEditor'),
('english','profile.career_ambitions','Career Ambitions','profile','EducationCareerEditor'),
('english','profile.career_education','Career & Education','profile','CareerEducationEditor'),
('norwegian','profile.education_level','Utdanningsnivå','profile','EducationCareerEditor'),
('norwegian','profile.work_life_balance','Balanse mellom jobb og fritid','profile','EducationCareerEditor'),
('norwegian','profile.occupation','Yrke','profile','EducationCareerEditor'),
('norwegian','profile.company','Selskap','profile','EducationCareerEditor'),
('norwegian','profile.career_ambitions','Karriereambisjoner','profile','EducationCareerEditor'),
('norwegian','profile.career_education','Karriere og utdanning','profile','CareerEducationEditor'),
('german','profile.education_level','Bildungsniveau','profile','EducationCareerEditor'),
('german','profile.work_life_balance','Work-Life-Balance','profile','EducationCareerEditor'),
('german','profile.occupation','Beruf','profile','EducationCareerEditor'),
('german','profile.company','Unternehmen','profile','EducationCareerEditor'),
('german','profile.career_ambitions','Karriereziele','profile','EducationCareerEditor'),
('german','profile.career_education','Karriere & Bildung','profile','CareerEducationEditor'),
('kurdish_sorani','profile.education_level','ئاستی خوێندن','profile','EducationCareerEditor'),
('kurdish_sorani','profile.work_life_balance','هاوسەنگی کار و ژیان','profile','EducationCareerEditor'),
('kurdish_sorani','profile.occupation','پیشە','profile','EducationCareerEditor'),
('kurdish_sorani','profile.company','کۆمپانیا','profile','EducationCareerEditor'),
('kurdish_sorani','profile.career_ambitions','ئامانجەکانی پیشە','profile','EducationCareerEditor'),
('kurdish_sorani','profile.career_education','پیشە و خوێندن','profile','CareerEducationEditor'),
('kurdish_kurmanji','profile.education_level','Asta perwerdehiyê','profile','EducationCareerEditor'),
('kurdish_kurmanji','profile.work_life_balance','Hevsengiya kar û jiyanê','profile','EducationCareerEditor'),
('kurdish_kurmanji','profile.occupation','Pîşe','profile','EducationCareerEditor'),
('kurdish_kurmanji','profile.company','Şirket','profile','EducationCareerEditor'),
('kurdish_kurmanji','profile.career_ambitions','Armancên pîşeyî','profile','EducationCareerEditor'),
('kurdish_kurmanji','profile.career_education','Pîşe û Perwerdehî','profile','CareerEducationEditor'),

-- InterestsHobbiesEditor labels
('english','profile.interests','Interests','profile','InterestsHobbiesEditor'),
('english','profile.hobbies','Hobbies','profile','InterestsHobbiesEditor'),
('english','profile.creative_pursuits','Creative Pursuits','profile','InterestsHobbiesEditor'),
('english','profile.weekend_activities','Weekend Activities','profile','InterestsHobbiesEditor'),
('norwegian','profile.interests','Interesser','profile','InterestsHobbiesEditor'),
('norwegian','profile.hobbies','Hobbyer','profile','InterestsHobbiesEditor'),
('norwegian','profile.creative_pursuits','Kreative sysler','profile','InterestsHobbiesEditor'),
('norwegian','profile.weekend_activities','Helgeaktiviteter','profile','InterestsHobbiesEditor'),
('german','profile.interests','Interessen','profile','InterestsHobbiesEditor'),
('german','profile.hobbies','Hobbys','profile','InterestsHobbiesEditor'),
('german','profile.creative_pursuits','Kreative Beschäftigungen','profile','InterestsHobbiesEditor'),
('german','profile.weekend_activities','Wochenendaktivitäten','profile','InterestsHobbiesEditor'),
('kurdish_sorani','profile.interests','ئارەزووەکان','profile','InterestsHobbiesEditor'),
('kurdish_sorani','profile.hobbies','ئاسایشەکان','profile','InterestsHobbiesEditor'),
('kurdish_sorani','profile.creative_pursuits','چالاکییە داهێنانەکان','profile','InterestsHobbiesEditor'),
('kurdish_sorani','profile.weekend_activities','چالاکییەکانی کۆتایی هەفتە','profile','InterestsHobbiesEditor'),
('kurdish_kurmanji','profile.interests','Eleqe','profile','InterestsHobbiesEditor'),
('kurdish_kurmanji','profile.hobbies','Hobî','profile','InterestsHobbiesEditor'),
('kurdish_kurmanji','profile.creative_pursuits','Çalakiyên afirîner','profile','InterestsHobbiesEditor'),
('kurdish_kurmanji','profile.weekend_activities','Çalakiyên dawiya hefteyê','profile','InterestsHobbiesEditor'),

-- ValuesPersonalityEditor labels
('english','profile.religion','Religion','profile','ValuesPersonalityEditor'),
('english','profile.political_views','Political Views','profile','ValuesPersonalityEditor'),
('english','profile.zodiac_sign','Zodiac Sign','profile','ValuesPersonalityEditor'),
('english','profile.personality_type','Personality Type (MBTI)','profile','ValuesPersonalityEditor'),
('english','profile.core_values','Core Values','profile','ValuesPersonalityEditor'),
('norwegian','profile.religion','Religion','profile','ValuesPersonalityEditor'),
('norwegian','profile.political_views','Politiske synspunkter','profile','ValuesPersonalityEditor'),
('norwegian','profile.zodiac_sign','Stjernetegn','profile','ValuesPersonalityEditor'),
('norwegian','profile.personality_type','Personlighetstype (MBTI)','profile','ValuesPersonalityEditor'),
('norwegian','profile.core_values','Kjerneverdier','profile','ValuesPersonalityEditor'),
('german','profile.religion','Religion','profile','ValuesPersonalityEditor'),
('german','profile.political_views','Politische Ansichten','profile','ValuesPersonalityEditor'),
('german','profile.zodiac_sign','Sternzeichen','profile','ValuesPersonalityEditor'),
('german','profile.personality_type','Persönlichkeitstyp (MBTI)','profile','ValuesPersonalityEditor'),
('german','profile.core_values','Grundwerte','profile','ValuesPersonalityEditor'),
('kurdish_sorani','profile.religion','ئایین','profile','ValuesPersonalityEditor'),
('kurdish_sorani','profile.political_views','بۆچوونە سیاسییەکان','profile','ValuesPersonalityEditor'),
('kurdish_sorani','profile.zodiac_sign','بورجی ئەستێرەناسی','profile','ValuesPersonalityEditor'),
('kurdish_sorani','profile.personality_type','جۆری کەسایەتی (MBTI)','profile','ValuesPersonalityEditor'),
('kurdish_sorani','profile.core_values','بەهاکانی سەرەکی','profile','ValuesPersonalityEditor'),
('kurdish_kurmanji','profile.religion','Ol','profile','ValuesPersonalityEditor'),
('kurdish_kurmanji','profile.political_views','Nêrînên siyasî','profile','ValuesPersonalityEditor'),
('kurdish_kurmanji','profile.zodiac_sign','Burca stêrnasiyê','profile','ValuesPersonalityEditor'),
('kurdish_kurmanji','profile.personality_type','Tîpa kesayetiyê (MBTI)','profile','ValuesPersonalityEditor'),
('kurdish_kurmanji','profile.core_values','Nirxên bingehîn','profile','ValuesPersonalityEditor'),

-- RelationshipPreferencesEditor labels
('english','profile.relationship_goals','Relationship Goals','profile','RelationshipPreferencesEditor'),
('english','profile.children','Children','profile','RelationshipPreferencesEditor'),
('english','profile.family_closeness','Family Closeness','profile','RelationshipPreferencesEditor'),
('english','profile.love_language','Love Language','profile','RelationshipPreferencesEditor'),
('english','profile.communication_style','Communication Style','profile','RelationshipPreferencesEditor'),
('english','profile.ideal_date','Ideal Date','profile','RelationshipPreferencesEditor'),
('norwegian','profile.relationship_goals','Forholdsmål','profile','RelationshipPreferencesEditor'),
('norwegian','profile.children','Barn','profile','RelationshipPreferencesEditor'),
('norwegian','profile.family_closeness','Familienærhet','profile','RelationshipPreferencesEditor'),
('norwegian','profile.love_language','Kjærlighetsspråk','profile','RelationshipPreferencesEditor'),
('norwegian','profile.communication_style','Kommunikasjonsstil','profile','RelationshipPreferencesEditor'),
('norwegian','profile.ideal_date','Ideell date','profile','RelationshipPreferencesEditor'),
('german','profile.relationship_goals','Beziehungsziele','profile','RelationshipPreferencesEditor'),
('german','profile.children','Kinder','profile','RelationshipPreferencesEditor'),
('german','profile.family_closeness','Familiennähe','profile','RelationshipPreferencesEditor'),
('german','profile.love_language','Liebessprache','profile','RelationshipPreferencesEditor'),
('german','profile.communication_style','Kommunikationsstil','profile','RelationshipPreferencesEditor'),
('german','profile.ideal_date','Ideales Date','profile','RelationshipPreferencesEditor'),
('kurdish_sorani','profile.relationship_goals','ئامانجەکانی پەیوەندی','profile','RelationshipPreferencesEditor'),
('kurdish_sorani','profile.children','منداڵەکان','profile','RelationshipPreferencesEditor'),
('kurdish_sorani','profile.family_closeness','نزیکایەتی خێزان','profile','RelationshipPreferencesEditor'),
('kurdish_sorani','profile.love_language','زمانی خۆشەویستی','profile','RelationshipPreferencesEditor'),
('kurdish_sorani','profile.communication_style','شێوازی پەیوەندی','profile','RelationshipPreferencesEditor'),
('kurdish_sorani','profile.ideal_date','چاوپێکەوتنی ئیدیال','profile','RelationshipPreferencesEditor'),
('kurdish_kurmanji','profile.relationship_goals','Armancên têkiliyê','profile','RelationshipPreferencesEditor'),
('kurdish_kurmanji','profile.children','Zarok','profile','RelationshipPreferencesEditor'),
('kurdish_kurmanji','profile.family_closeness','Nêzîkahiya malbatê','profile','RelationshipPreferencesEditor'),
('kurdish_kurmanji','profile.love_language','Zimanê evînê','profile','RelationshipPreferencesEditor'),
('kurdish_kurmanji','profile.communication_style','Şêwaza ragihandinê','profile','RelationshipPreferencesEditor'),
('kurdish_kurmanji','profile.ideal_date','Hevdîtina îdeal','profile','RelationshipPreferencesEditor'),

-- LifestyleEditor labels
('english','profile.exercise_habits','Exercise Habits','profile','LifestyleEditor'),
('english','profile.dietary_preferences','Dietary Preferences','profile','LifestyleEditor'),
('english','profile.smoking','Smoking','profile','LifestyleEditor'),
('english','profile.drinking','Drinking','profile','LifestyleEditor'),
('english','profile.sleep_schedule','Sleep Schedule','profile','LifestyleEditor'),
('english','profile.pets','Pets','profile','LifestyleEditor'),
('norwegian','profile.exercise_habits','Treningsvaner','profile','LifestyleEditor'),
('norwegian','profile.dietary_preferences','Kostholdsvalg','profile','LifestyleEditor'),
('norwegian','profile.smoking','Røyking','profile','LifestyleEditor'),
('norwegian','profile.drinking','Alkohol','profile','LifestyleEditor'),
('norwegian','profile.sleep_schedule','Søvnplan','profile','LifestyleEditor'),
('norwegian','profile.pets','Kjæledyr','profile','LifestyleEditor'),
('german','profile.exercise_habits','Sportgewohnheiten','profile','LifestyleEditor'),
('german','profile.dietary_preferences','Ernährungsvorlieben','profile','LifestyleEditor'),
('german','profile.smoking','Rauchen','profile','LifestyleEditor'),
('german','profile.drinking','Alkohol','profile','LifestyleEditor'),
('german','profile.sleep_schedule','Schlafrhythmus','profile','LifestyleEditor'),
('german','profile.pets','Haustiere','profile','LifestyleEditor'),
('kurdish_sorani','profile.exercise_habits','خوی وەرزشی','profile','LifestyleEditor'),
('kurdish_sorani','profile.dietary_preferences','هەڵبژاردنی خواردن','profile','LifestyleEditor'),
('kurdish_sorani','profile.smoking','جگەرەکێشان','profile','LifestyleEditor'),
('kurdish_sorani','profile.drinking','خواردنەوە','profile','LifestyleEditor'),
('kurdish_sorani','profile.sleep_schedule','بەرنامەی خەوتن','profile','LifestyleEditor'),
('kurdish_sorani','profile.pets','ئاژەڵی ماڵی','profile','LifestyleEditor'),
('kurdish_kurmanji','profile.exercise_habits','Adetên werzîşê','profile','LifestyleEditor'),
('kurdish_kurmanji','profile.dietary_preferences','Bijartinên xwarinê','profile','LifestyleEditor'),
('kurdish_kurmanji','profile.smoking','Cixarekêşan','profile','LifestyleEditor'),
('kurdish_kurmanji','profile.drinking','Vexwarin','profile','LifestyleEditor'),
('kurdish_kurmanji','profile.sleep_schedule','Bernameya xewê','profile','LifestyleEditor'),
('kurdish_kurmanji','profile.pets','Heywanên malê','profile','LifestyleEditor'),

-- FavoritesEditor labels
('english','profile.favorites_inspirations','Favorites & Inspirations','profile','FavoritesEditor'),
('english','profile.favorite_books','Favorite Books','profile','FavoritesEditor'),
('english','profile.favorite_movies','Favorite Movies','profile','FavoritesEditor'),
('english','profile.favorite_music','Favorite Music','profile','FavoritesEditor'),
('english','profile.favorite_foods','Favorite Foods','profile','FavoritesEditor'),
('english','profile.favorite_quote','Favorite Quote','profile','FavoritesEditor'),
('english','profile.dream_vacation','Dream Vacation','profile','FavoritesEditor'),
('norwegian','profile.favorites_inspirations','Favoritter og inspirasjoner','profile','FavoritesEditor'),
('norwegian','profile.favorite_books','Favorittbøker','profile','FavoritesEditor'),
('norwegian','profile.favorite_movies','Favorittfilmer','profile','FavoritesEditor'),
('norwegian','profile.favorite_music','Favorittmusikk','profile','FavoritesEditor'),
('norwegian','profile.favorite_foods','Favorittmat','profile','FavoritesEditor'),
('norwegian','profile.favorite_quote','Favorittsitat','profile','FavoritesEditor'),
('norwegian','profile.dream_vacation','Drømmeferie','profile','FavoritesEditor'),
('german','profile.favorites_inspirations','Favoriten & Inspirationen','profile','FavoritesEditor'),
('german','profile.favorite_books','Lieblingsbücher','profile','FavoritesEditor'),
('german','profile.favorite_movies','Lieblingsfilme','profile','FavoritesEditor'),
('german','profile.favorite_music','Lieblingsmusik','profile','FavoritesEditor'),
('german','profile.favorite_foods','Lieblingsessen','profile','FavoritesEditor'),
('german','profile.favorite_quote','Lieblingszitat','profile','FavoritesEditor'),
('german','profile.dream_vacation','Traumurlaub','profile','FavoritesEditor'),
('kurdish_sorani','profile.favorites_inspirations','دڵخوازەکان و ئیلهامەکان','profile','FavoritesEditor'),
('kurdish_sorani','profile.favorite_books','کتێبە دڵخوازەکان','profile','FavoritesEditor'),
('kurdish_sorani','profile.favorite_movies','فیلمە دڵخوازەکان','profile','FavoritesEditor'),
('kurdish_sorani','profile.favorite_music','مۆسیقای دڵخواز','profile','FavoritesEditor'),
('kurdish_sorani','profile.favorite_foods','خواردنە دڵخوازەکان','profile','FavoritesEditor'),
('kurdish_sorani','profile.favorite_quote','وتەی دڵخواز','profile','FavoritesEditor'),
('kurdish_sorani','profile.dream_vacation','پشووی خەیاڵی','profile','FavoritesEditor'),
('kurdish_kurmanji','profile.favorites_inspirations','Bijarte û Îlham','profile','FavoritesEditor'),
('kurdish_kurmanji','profile.favorite_books','Pirtûkên bijarte','profile','FavoritesEditor'),
('kurdish_kurmanji','profile.favorite_movies','Fîlmên bijarte','profile','FavoritesEditor'),
('kurdish_kurmanji','profile.favorite_music','Muzîka bijarte','profile','FavoritesEditor'),
('kurdish_kurmanji','profile.favorite_foods','Xwarinên bijarte','profile','FavoritesEditor'),
('kurdish_kurmanji','profile.favorite_quote','Gotina bijarte','profile','FavoritesEditor'),
('kurdish_kurmanji','profile.dream_vacation','Betlaneya xewnan','profile','FavoritesEditor')

ON CONFLICT (language_code, translation_key) DO NOTHING;
