
-- Batch 14: TranslationsPage, SupportTicketsPage remaining, SuperAdminLayout sidebar labels, dashboard components
INSERT INTO public.app_translations (language_code, translation_key, translation_value, category) VALUES
-- TranslationsPage
('english', 'admin.translation_management', 'Translation Management', 'admin'),
('english', 'admin.manage_translations_desc', 'Manage app translations across all languages', 'admin'),
('english', 'admin.need_review', 'Need Review', 'admin'),
('english', 'admin.extracting', 'Extracting...', 'admin'),
('english', 'admin.extract_all_texts', 'Extract All Texts', 'admin'),
('english', 'admin.export_csv', 'Export CSV', 'admin'),
('english', 'admin.import_csv', 'Import CSV', 'admin'),
('english', 'admin.add_translation', 'Add Translation', 'admin'),
('english', 'admin.search_translations', 'Search translations...', 'admin'),
('english', 'admin.select_language', 'Select language', 'admin'),
('english', 'admin.all_languages', 'All Languages', 'admin'),
('english', 'admin.select_category', 'Select category', 'admin'),
('english', 'admin.needs_review_only', 'Needs Review Only', 'admin'),
('english', 'admin.translations_count', 'Translations', 'admin'),
('english', 'admin.no_translations_found', 'No translations found', 'admin'),
('english', 'admin.needs_review', 'Needs Review', 'admin'),
('english', 'admin.context_label', 'Context', 'admin'),
('english', 'admin.translation_updated', 'Translation updated successfully', 'admin'),
('english', 'admin.failed_update_translation', 'Failed to update translation', 'admin'),
('english', 'admin.marked_reviewed', 'Marked as reviewed', 'admin'),
('english', 'admin.failed_mark_reviewed', 'Failed to mark as reviewed', 'admin'),
('english', 'admin.failed_load_translations', 'Failed to load translations', 'admin'),
('english', 'admin.failed_extract_texts', 'Failed to extract texts from system', 'admin'),

-- SupportTicketsPage remaining hardcoded strings
('english', 'admin.subject', 'Subject', 'admin'),
('english', 'admin.email_label', 'Email', 'admin'),
('english', 'admin.category', 'Category', 'admin'),
('english', 'admin.created', 'Created', 'admin'),
('english', 'admin.actions', 'Actions', 'admin'),
('english', 'admin.all_status', 'All Status', 'admin'),
('english', 'admin.all_categories', 'All Categories', 'admin'),
('english', 'admin.technical', 'Technical', 'admin'),
('english', 'admin.billing', 'Billing', 'admin'),
('english', 'admin.account', 'Account', 'admin'),
('english', 'admin.safety', 'Safety', 'admin'),
('english', 'admin.feedback', 'Feedback', 'admin'),
('english', 'admin.search_placeholder_tickets', 'Search by subject, email, or message...', 'admin'),
('english', 'admin.message_label', 'Message', 'admin'),
('english', 'admin.admin_notes', 'Admin Notes / Responses', 'admin'),
('english', 'admin.add_response', 'Add Response', 'admin'),
('english', 'admin.write_response', 'Write your response to the user...', 'admin'),
('english', 'admin.change_status', 'Change Status', 'admin'),
('english', 'admin.close', 'Close', 'admin'),
('english', 'admin.verifying_access', 'Verifying admin access...', 'admin'),
('english', 'admin.sign_out', 'Sign Out', 'admin'),

-- SuperAdminLayout sidebar labels
('english', 'admin.nav_dashboard', 'Dashboard', 'admin'),
('english', 'admin.nav_users_management', 'Users Management', 'admin'),
('english', 'admin.nav_ghost_users', 'Ghost Users', 'admin'),
('english', 'admin.nav_subscribers', 'Subscribers', 'admin'),
('english', 'admin.nav_payments', 'Payments', 'admin'),
('english', 'admin.nav_likes', 'Likes', 'admin'),
('english', 'admin.nav_matches', 'Matches', 'admin'),
('english', 'admin.nav_comments', 'Comments', 'admin'),
('english', 'admin.nav_groups', 'Groups', 'admin'),
('english', 'admin.nav_events', 'Events', 'admin'),
('english', 'admin.nav_followers', 'Followers', 'admin'),
('english', 'admin.nav_notifications', 'Notifications', 'admin'),
('english', 'admin.nav_hashtags', 'Hashtags', 'admin'),
('english', 'admin.nav_blocked_users', 'Blocked Users', 'admin'),
('english', 'admin.nav_conversations', 'Conversations', 'admin'),
('english', 'admin.nav_rate_limits', 'Rate Limits', 'admin'),
('english', 'admin.nav_daily_usage', 'Daily Usage', 'admin'),
('english', 'admin.nav_ai_insights', 'AI Insights', 'admin'),
('english', 'admin.nav_interests', 'Interests', 'admin'),
('english', 'admin.nav_support_tickets', 'Support Tickets', 'admin'),
('english', 'admin.nav_verification', 'User Verification', 'admin'),
('english', 'admin.nav_moderation', 'Content Moderation', 'admin'),
('english', 'admin.nav_landing_page', 'Landing Page Editor', 'admin'),
('english', 'admin.nav_translations', 'Translations', 'admin'),
('english', 'admin.nav_analytics', 'Advanced Analytics', 'admin'),
('english', 'admin.nav_ab_testing', 'A/B Testing', 'admin'),
('english', 'admin.nav_system_health', 'System Health', 'admin'),
('english', 'admin.nav_email_campaigns', 'Email Campaigns', 'admin'),
('english', 'admin.nav_exports', 'Data Exports', 'admin'),
('english', 'admin.nav_audit_logs', 'Audit Logs', 'admin'),
('english', 'admin.nav_roles', 'Role Management', 'admin'),
('english', 'admin.nav_bulk_actions', 'Bulk User Actions', 'admin'),
('english', 'admin.nav_social_login', 'Social Login', 'admin'),
('english', 'admin.nav_categories', 'Categories', 'admin'),
('english', 'admin.nav_reg_questions', 'Registration Questions', 'admin'),
('english', 'admin.nav_messages', 'Messages', 'admin'),
('english', 'admin.nav_photos', 'Photos', 'admin'),
('english', 'admin.nav_virtual_gifts', 'Virtual Gifts', 'admin'),
('english', 'admin.nav_api_keys', 'API Keys', 'admin'),
('english', 'admin.nav_settings', 'Settings', 'admin'),

-- Norwegian
('norwegian', 'admin.translation_management', 'Oversettelseshåndtering', 'admin'),
('norwegian', 'admin.manage_translations_desc', 'Administrer app-oversettelser på alle språk', 'admin'),
('norwegian', 'admin.need_review', 'Trenger gjennomgang', 'admin'),
('norwegian', 'admin.extracting', 'Henter ut...', 'admin'),
('norwegian', 'admin.extract_all_texts', 'Hent ut alle tekster', 'admin'),
('norwegian', 'admin.export_csv', 'Eksporter CSV', 'admin'),
('norwegian', 'admin.import_csv', 'Importer CSV', 'admin'),
('norwegian', 'admin.add_translation', 'Legg til oversettelse', 'admin'),
('norwegian', 'admin.search_translations', 'Søk i oversettelser...', 'admin'),
('norwegian', 'admin.select_language', 'Velg språk', 'admin'),
('norwegian', 'admin.all_languages', 'Alle språk', 'admin'),
('norwegian', 'admin.select_category', 'Velg kategori', 'admin'),
('norwegian', 'admin.needs_review_only', 'Kun trenger gjennomgang', 'admin'),
('norwegian', 'admin.translations_count', 'Oversettelser', 'admin'),
('norwegian', 'admin.no_translations_found', 'Ingen oversettelser funnet', 'admin'),
('norwegian', 'admin.needs_review', 'Trenger gjennomgang', 'admin'),
('norwegian', 'admin.context_label', 'Kontekst', 'admin'),
('norwegian', 'admin.translation_updated', 'Oversettelse oppdatert', 'admin'),
('norwegian', 'admin.failed_update_translation', 'Kunne ikke oppdatere oversettelse', 'admin'),
('norwegian', 'admin.marked_reviewed', 'Merket som gjennomgått', 'admin'),
('norwegian', 'admin.failed_mark_reviewed', 'Kunne ikke merke som gjennomgått', 'admin'),
('norwegian', 'admin.failed_load_translations', 'Kunne ikke laste oversettelser', 'admin'),
('norwegian', 'admin.failed_extract_texts', 'Kunne ikke hente ut tekster fra systemet', 'admin'),
('norwegian', 'admin.subject', 'Emne', 'admin'),
('norwegian', 'admin.email_label', 'E-post', 'admin'),
('norwegian', 'admin.category', 'Kategori', 'admin'),
('norwegian', 'admin.created', 'Opprettet', 'admin'),
('norwegian', 'admin.actions', 'Handlinger', 'admin'),
('norwegian', 'admin.all_status', 'Alle statuser', 'admin'),
('norwegian', 'admin.all_categories', 'Alle kategorier', 'admin'),
('norwegian', 'admin.technical', 'Teknisk', 'admin'),
('norwegian', 'admin.billing', 'Fakturering', 'admin'),
('norwegian', 'admin.account', 'Konto', 'admin'),
('norwegian', 'admin.safety', 'Sikkerhet', 'admin'),
('norwegian', 'admin.feedback', 'Tilbakemelding', 'admin'),
('norwegian', 'admin.search_placeholder_tickets', 'Søk etter emne, e-post eller melding...', 'admin'),
('norwegian', 'admin.message_label', 'Melding', 'admin'),
('norwegian', 'admin.admin_notes', 'Adminnotater / Svar', 'admin'),
('norwegian', 'admin.add_response', 'Legg til svar', 'admin'),
('norwegian', 'admin.write_response', 'Skriv ditt svar til brukeren...', 'admin'),
('norwegian', 'admin.change_status', 'Endre status', 'admin'),
('norwegian', 'admin.close', 'Lukk', 'admin'),
('norwegian', 'admin.verifying_access', 'Verifiserer admintilgang...', 'admin'),
('norwegian', 'admin.sign_out', 'Logg ut', 'admin'),
('norwegian', 'admin.nav_dashboard', 'Dashbord', 'admin'),
('norwegian', 'admin.nav_users_management', 'Brukeradministrasjon', 'admin'),
('norwegian', 'admin.nav_ghost_users', 'Spøkelsesbrukere', 'admin'),
('norwegian', 'admin.nav_subscribers', 'Abonnenter', 'admin'),
('norwegian', 'admin.nav_payments', 'Betalinger', 'admin'),
('norwegian', 'admin.nav_likes', 'Likerklikk', 'admin'),
('norwegian', 'admin.nav_matches', 'Matcher', 'admin'),
('norwegian', 'admin.nav_comments', 'Kommentarer', 'admin'),
('norwegian', 'admin.nav_groups', 'Grupper', 'admin'),
('norwegian', 'admin.nav_events', 'Arrangementer', 'admin'),
('norwegian', 'admin.nav_followers', 'Følgere', 'admin'),
('norwegian', 'admin.nav_notifications', 'Varsler', 'admin'),
('norwegian', 'admin.nav_hashtags', 'Hashtags', 'admin'),
('norwegian', 'admin.nav_blocked_users', 'Blokkerte brukere', 'admin'),
('norwegian', 'admin.nav_conversations', 'Samtaler', 'admin'),
('norwegian', 'admin.nav_rate_limits', 'Hastighetsgrenser', 'admin'),
('norwegian', 'admin.nav_daily_usage', 'Daglig bruk', 'admin'),
('norwegian', 'admin.nav_ai_insights', 'AI-innsikt', 'admin'),
('norwegian', 'admin.nav_interests', 'Interesser', 'admin'),
('norwegian', 'admin.nav_support_tickets', 'Støttesaker', 'admin'),
('norwegian', 'admin.nav_verification', 'Brukerverifisering', 'admin'),
('norwegian', 'admin.nav_moderation', 'Innholdsmoderering', 'admin'),
('norwegian', 'admin.nav_landing_page', 'Landingssideredigerer', 'admin'),
('norwegian', 'admin.nav_translations', 'Oversettelser', 'admin'),
('norwegian', 'admin.nav_analytics', 'Avansert analyse', 'admin'),
('norwegian', 'admin.nav_ab_testing', 'A/B-testing', 'admin'),
('norwegian', 'admin.nav_system_health', 'Systemhelse', 'admin'),
('norwegian', 'admin.nav_email_campaigns', 'E-postkampanjer', 'admin'),
('norwegian', 'admin.nav_exports', 'Dataeksport', 'admin'),
('norwegian', 'admin.nav_audit_logs', 'Revisjonslogger', 'admin'),
('norwegian', 'admin.nav_roles', 'Rolleadministrasjon', 'admin'),
('norwegian', 'admin.nav_bulk_actions', 'Massehandlinger', 'admin'),
('norwegian', 'admin.nav_social_login', 'Sosial innlogging', 'admin'),
('norwegian', 'admin.nav_categories', 'Kategorier', 'admin'),
('norwegian', 'admin.nav_reg_questions', 'Registreringsspørsmål', 'admin'),
('norwegian', 'admin.nav_messages', 'Meldinger', 'admin'),
('norwegian', 'admin.nav_photos', 'Bilder', 'admin'),
('norwegian', 'admin.nav_virtual_gifts', 'Virtuelle gaver', 'admin'),
('norwegian', 'admin.nav_api_keys', 'API-nøkler', 'admin'),
('norwegian', 'admin.nav_settings', 'Innstillinger', 'admin'),

-- Kurdish Sorani
('kurdish_sorani', 'admin.translation_management', 'بەڕێوەبردنی وەرگێڕان', 'admin'),
('kurdish_sorani', 'admin.manage_translations_desc', 'بەڕێوەبردنی وەرگێڕانی ئەپ لە هەموو زمانەکان', 'admin'),
('kurdish_sorani', 'admin.need_review', 'پێویستی بە پێداچوونەوە', 'admin'),
('kurdish_sorani', 'admin.extracting', 'دەرهێنان...', 'admin'),
('kurdish_sorani', 'admin.extract_all_texts', 'هەموو دەقەکان دەربهێنە', 'admin'),
('kurdish_sorani', 'admin.export_csv', 'هاوردەی CSV', 'admin'),
('kurdish_sorani', 'admin.import_csv', 'هێنانەژوورەوەی CSV', 'admin'),
('kurdish_sorani', 'admin.add_translation', 'زیادکردنی وەرگێڕان', 'admin'),
('kurdish_sorani', 'admin.search_translations', 'گەڕان لە وەرگێڕانەکان...', 'admin'),
('kurdish_sorani', 'admin.select_language', 'زمان هەڵبژێرە', 'admin'),
('kurdish_sorani', 'admin.all_languages', 'هەموو زمانەکان', 'admin'),
('kurdish_sorani', 'admin.select_category', 'پۆل هەڵبژێرە', 'admin'),
('kurdish_sorani', 'admin.needs_review_only', 'تەنها پێویستی بە پێداچوونەوە', 'admin'),
('kurdish_sorani', 'admin.translations_count', 'وەرگێڕانەکان', 'admin'),
('kurdish_sorani', 'admin.no_translations_found', 'هیچ وەرگێڕانێک نەدۆزرایەوە', 'admin'),
('kurdish_sorani', 'admin.needs_review', 'پێویستی بە پێداچوونەوە', 'admin'),
('kurdish_sorani', 'admin.context_label', 'چوارچێوە', 'admin'),
('kurdish_sorani', 'admin.subject', 'بابەت', 'admin'),
('kurdish_sorani', 'admin.email_label', 'ئیمەیل', 'admin'),
('kurdish_sorani', 'admin.category', 'پۆل', 'admin'),
('kurdish_sorani', 'admin.created', 'دروستکراوە', 'admin'),
('kurdish_sorani', 'admin.actions', 'کردارەکان', 'admin'),
('kurdish_sorani', 'admin.all_status', 'هەموو بارەکان', 'admin'),
('kurdish_sorani', 'admin.all_categories', 'هەموو پۆلەکان', 'admin'),
('kurdish_sorani', 'admin.close', 'داخستن', 'admin'),
('kurdish_sorani', 'admin.verifying_access', 'پشتڕاستکردنەوەی دەستگەیشتنی ئەدمین...', 'admin'),
('kurdish_sorani', 'admin.sign_out', 'چوونەدەرەوە', 'admin'),
('kurdish_sorani', 'admin.nav_dashboard', 'داشبۆرد', 'admin'),
('kurdish_sorani', 'admin.nav_users_management', 'بەڕێوەبردنی بەکارهێنەران', 'admin'),
('kurdish_sorani', 'admin.nav_ghost_users', 'بەکارهێنەرانی خەیاڵی', 'admin'),
('kurdish_sorani', 'admin.nav_subscribers', 'بەشداربووان', 'admin'),
('kurdish_sorani', 'admin.nav_payments', 'پارەدانەکان', 'admin'),
('kurdish_sorani', 'admin.nav_likes', 'پەسەندەکان', 'admin'),
('kurdish_sorani', 'admin.nav_matches', 'هاوتاکان', 'admin'),
('kurdish_sorani', 'admin.nav_settings', 'ڕێکخستنەکان', 'admin'),

-- Kurdish Kurmanci
('kurdish_kurmanci', 'admin.translation_management', 'Rêvebiriya Wergeran', 'admin'),
('kurdish_kurmanci', 'admin.manage_translations_desc', 'Rêvebiriya wergerên appê li hemû zimanan', 'admin'),
('kurdish_kurmanci', 'admin.need_review', 'Pêdivî bi vekolînê', 'admin'),
('kurdish_kurmanci', 'admin.extract_all_texts', 'Hemû nivîsan derxîne', 'admin'),
('kurdish_kurmanci', 'admin.export_csv', 'Eksporta CSV', 'admin'),
('kurdish_kurmanci', 'admin.import_csv', 'Importa CSV', 'admin'),
('kurdish_kurmanci', 'admin.add_translation', 'Wergerekê zêde bike', 'admin'),
('kurdish_kurmanci', 'admin.search_translations', 'Li wergeran bigere...', 'admin'),
('kurdish_kurmanci', 'admin.all_languages', 'Hemû ziman', 'admin'),
('kurdish_kurmanci', 'admin.needs_review_only', 'Tenê pêdivî bi vekolînê', 'admin'),
('kurdish_kurmanci', 'admin.no_translations_found', 'Tu werger nehat dîtin', 'admin'),
('kurdish_kurmanci', 'admin.subject', 'Mijar', 'admin'),
('kurdish_kurmanci', 'admin.email_label', 'Email', 'admin'),
('kurdish_kurmanci', 'admin.category', 'Beş', 'admin'),
('kurdish_kurmanci', 'admin.created', 'Hatiye afirandin', 'admin'),
('kurdish_kurmanci', 'admin.actions', 'Kiryar', 'admin'),
('kurdish_kurmanci', 'admin.close', 'Bigire', 'admin'),
('kurdish_kurmanci', 'admin.sign_out', 'Derkeve', 'admin'),
('kurdish_kurmanci', 'admin.nav_dashboard', 'Dashboard', 'admin'),
('kurdish_kurmanci', 'admin.nav_users_management', 'Rêvebiriya Bikarhêneran', 'admin'),
('kurdish_kurmanci', 'admin.nav_settings', 'Mîheng', 'admin'),

-- German
('german', 'admin.translation_management', 'Übersetzungsverwaltung', 'admin'),
('german', 'admin.manage_translations_desc', 'App-Übersetzungen für alle Sprachen verwalten', 'admin'),
('german', 'admin.need_review', 'Überprüfung erforderlich', 'admin'),
('german', 'admin.extracting', 'Wird extrahiert...', 'admin'),
('german', 'admin.extract_all_texts', 'Alle Texte extrahieren', 'admin'),
('german', 'admin.export_csv', 'CSV exportieren', 'admin'),
('german', 'admin.import_csv', 'CSV importieren', 'admin'),
('german', 'admin.add_translation', 'Übersetzung hinzufügen', 'admin'),
('german', 'admin.search_translations', 'Übersetzungen durchsuchen...', 'admin'),
('german', 'admin.select_language', 'Sprache auswählen', 'admin'),
('german', 'admin.all_languages', 'Alle Sprachen', 'admin'),
('german', 'admin.select_category', 'Kategorie auswählen', 'admin'),
('german', 'admin.needs_review_only', 'Nur zu überprüfende', 'admin'),
('german', 'admin.translations_count', 'Übersetzungen', 'admin'),
('german', 'admin.no_translations_found', 'Keine Übersetzungen gefunden', 'admin'),
('german', 'admin.needs_review', 'Überprüfung erforderlich', 'admin'),
('german', 'admin.context_label', 'Kontext', 'admin'),
('german', 'admin.translation_updated', 'Übersetzung aktualisiert', 'admin'),
('german', 'admin.failed_update_translation', 'Übersetzung konnte nicht aktualisiert werden', 'admin'),
('german', 'admin.marked_reviewed', 'Als überprüft markiert', 'admin'),
('german', 'admin.failed_mark_reviewed', 'Konnte nicht als überprüft markiert werden', 'admin'),
('german', 'admin.failed_load_translations', 'Übersetzungen konnten nicht geladen werden', 'admin'),
('german', 'admin.failed_extract_texts', 'Texte konnten nicht aus dem System extrahiert werden', 'admin'),
('german', 'admin.subject', 'Betreff', 'admin'),
('german', 'admin.email_label', 'E-Mail', 'admin'),
('german', 'admin.category', 'Kategorie', 'admin'),
('german', 'admin.created', 'Erstellt', 'admin'),
('german', 'admin.actions', 'Aktionen', 'admin'),
('german', 'admin.all_status', 'Alle Status', 'admin'),
('german', 'admin.all_categories', 'Alle Kategorien', 'admin'),
('german', 'admin.technical', 'Technisch', 'admin'),
('german', 'admin.billing', 'Abrechnung', 'admin'),
('german', 'admin.account', 'Konto', 'admin'),
('german', 'admin.safety', 'Sicherheit', 'admin'),
('german', 'admin.feedback', 'Feedback', 'admin'),
('german', 'admin.search_placeholder_tickets', 'Nach Betreff, E-Mail oder Nachricht suchen...', 'admin'),
('german', 'admin.message_label', 'Nachricht', 'admin'),
('german', 'admin.admin_notes', 'Admin-Notizen / Antworten', 'admin'),
('german', 'admin.add_response', 'Antwort hinzufügen', 'admin'),
('german', 'admin.write_response', 'Schreiben Sie Ihre Antwort an den Benutzer...', 'admin'),
('german', 'admin.change_status', 'Status ändern', 'admin'),
('german', 'admin.close', 'Schließen', 'admin'),
('german', 'admin.verifying_access', 'Admin-Zugang wird überprüft...', 'admin'),
('german', 'admin.sign_out', 'Abmelden', 'admin'),
('german', 'admin.nav_dashboard', 'Dashboard', 'admin'),
('german', 'admin.nav_users_management', 'Benutzerverwaltung', 'admin'),
('german', 'admin.nav_ghost_users', 'Geisterbenutzer', 'admin'),
('german', 'admin.nav_subscribers', 'Abonnenten', 'admin'),
('german', 'admin.nav_payments', 'Zahlungen', 'admin'),
('german', 'admin.nav_likes', 'Likes', 'admin'),
('german', 'admin.nav_matches', 'Matches', 'admin'),
('german', 'admin.nav_comments', 'Kommentare', 'admin'),
('german', 'admin.nav_groups', 'Gruppen', 'admin'),
('german', 'admin.nav_events', 'Veranstaltungen', 'admin'),
('german', 'admin.nav_followers', 'Follower', 'admin'),
('german', 'admin.nav_notifications', 'Benachrichtigungen', 'admin'),
('german', 'admin.nav_hashtags', 'Hashtags', 'admin'),
('german', 'admin.nav_blocked_users', 'Blockierte Benutzer', 'admin'),
('german', 'admin.nav_conversations', 'Unterhaltungen', 'admin'),
('german', 'admin.nav_rate_limits', 'Ratenlimits', 'admin'),
('german', 'admin.nav_daily_usage', 'Tägliche Nutzung', 'admin'),
('german', 'admin.nav_ai_insights', 'KI-Einblicke', 'admin'),
('german', 'admin.nav_interests', 'Interessen', 'admin'),
('german', 'admin.nav_support_tickets', 'Support-Tickets', 'admin'),
('german', 'admin.nav_verification', 'Benutzerverifizierung', 'admin'),
('german', 'admin.nav_moderation', 'Inhaltsmoderation', 'admin'),
('german', 'admin.nav_landing_page', 'Landingpage-Editor', 'admin'),
('german', 'admin.nav_translations', 'Übersetzungen', 'admin'),
('german', 'admin.nav_analytics', 'Erweiterte Analytik', 'admin'),
('german', 'admin.nav_ab_testing', 'A/B-Tests', 'admin'),
('german', 'admin.nav_system_health', 'Systemstatus', 'admin'),
('german', 'admin.nav_email_campaigns', 'E-Mail-Kampagnen', 'admin'),
('german', 'admin.nav_exports', 'Datenexport', 'admin'),
('german', 'admin.nav_audit_logs', 'Audit-Logs', 'admin'),
('german', 'admin.nav_roles', 'Rollenverwaltung', 'admin'),
('german', 'admin.nav_bulk_actions', 'Massenaktionen', 'admin'),
('german', 'admin.nav_social_login', 'Social Login', 'admin'),
('german', 'admin.nav_categories', 'Kategorien', 'admin'),
('german', 'admin.nav_reg_questions', 'Registrierungsfragen', 'admin'),
('german', 'admin.nav_messages', 'Nachrichten', 'admin'),
('german', 'admin.nav_photos', 'Fotos', 'admin'),
('german', 'admin.nav_virtual_gifts', 'Virtuelle Geschenke', 'admin'),
('german', 'admin.nav_api_keys', 'API-Schlüssel', 'admin'),
('german', 'admin.nav_settings', 'Einstellungen', 'admin')
ON CONFLICT (language_code, translation_key) DO UPDATE SET translation_value = EXCLUDED.translation_value;
