
-- Batch 18: i18n (without duplicates)
INSERT INTO public.app_translations (language_code, translation_key, translation_value, category, auto_translated, needs_review) VALUES
-- Registration Questions - QuestionsToolbar
('english','admin.configure_questions','Configure questions users will answer during registration','admin',false,false),
('norwegian','admin.configure_questions','Konfigurer spørsmål brukerne vil svare på under registrering','admin',true,true),
('german','admin.configure_questions','Konfigurieren Sie Fragen, die Benutzer bei der Registrierung beantworten','admin',true,true),
('kurdish_sorani','admin.configure_questions','پرسیارەکان ڕێکبخە کە بەکارهێنەران لە کاتی تۆمارکردندا وەڵامیان دەدەنەوە','admin',true,true),
('kurdish_kurmanji','admin.configure_questions','Pirsên ku bikarhêner dê di dema qeydkirinê de bersiv bidin mîheng bikin','admin',true,true),
('english','admin.search_questions','Search questions...','admin',false,false),
('norwegian','admin.search_questions','Søk spørsmål...','admin',true,true),
('german','admin.search_questions','Fragen suchen...','admin',true,true),
('kurdish_sorani','admin.search_questions','گەڕان بۆ پرسیارەکان...','admin',true,true),
('kurdish_kurmanji','admin.search_questions','Li pirsan bigerin...','admin',true,true),
('english','admin.filter_questions','Filter Questions','admin',false,false),
('norwegian','admin.filter_questions','Filtrer spørsmål','admin',true,true),
('german','admin.filter_questions','Fragen filtern','admin',true,true),
('kurdish_sorani','admin.filter_questions','فلتەری پرسیارەکان','admin',true,true),
('kurdish_kurmanji','admin.filter_questions','Pirsan fîltre bikin','admin',true,true),
('english','admin.required_questions','Required Questions','admin',false,false),
('norwegian','admin.required_questions','Påkrevde spørsmål','admin',true,true),
('german','admin.required_questions','Erforderliche Fragen','admin',true,true),
('kurdish_sorani','admin.required_questions','پرسیارە پێویستەکان','admin',true,true),
('kurdish_kurmanji','admin.required_questions','Pirsên pêwîst','admin',true,true),
('english','admin.optional_questions','Optional Questions','admin',false,false),
('norwegian','admin.optional_questions','Valgfrie spørsmål','admin',true,true),
('german','admin.optional_questions','Optionale Fragen','admin',true,true),
('kurdish_sorani','admin.optional_questions','پرسیارە ئیختیارییەکان','admin',true,true),
('kurdish_kurmanji','admin.optional_questions','Pirsên bijartî','admin',true,true),
('english','admin.enabled_questions','Enabled Questions','admin',false,false),
('norwegian','admin.enabled_questions','Aktiverte spørsmål','admin',true,true),
('german','admin.enabled_questions','Aktivierte Fragen','admin',true,true),
('kurdish_sorani','admin.enabled_questions','پرسیارە چالاکەکان','admin',true,true),
('kurdish_kurmanji','admin.enabled_questions','Pirsên çalak','admin',true,true),
('english','admin.disabled_questions','Disabled Questions','admin',false,false),
('norwegian','admin.disabled_questions','Deaktiverte spørsmål','admin',true,true),
('german','admin.disabled_questions','Deaktivierte Fragen','admin',true,true),
('kurdish_sorani','admin.disabled_questions','پرسیارە ناچالاکەکان','admin',true,true),
('kurdish_kurmanji','admin.disabled_questions','Pirsên neçalak','admin',true,true),
('english','admin.question','Question','admin',false,false),
('norwegian','admin.question','Spørsmål','admin',true,true),
('german','admin.question','Frage','admin',true,true),
('kurdish_sorani','admin.question','پرسیار','admin',true,true),
('kurdish_kurmanji','admin.question','Pirs','admin',true,true),
('english','admin.field_type','Field Type','admin',false,false),
('norwegian','admin.field_type','Felttype','admin',true,true),
('german','admin.field_type','Feldtyp','admin',true,true),
('kurdish_sorani','admin.field_type','جۆری خانە','admin',true,true),
('kurdish_kurmanji','admin.field_type','Tîpa qadê','admin',true,true),
('english','admin.required','Required','admin',false,false),
('norwegian','admin.required','Påkrevd','admin',true,true),
('german','admin.required','Erforderlich','admin',true,true),
('kurdish_sorani','admin.required','پێویستە','admin',true,true),
('kurdish_kurmanji','admin.required','Pêwîst','admin',true,true),
('english','admin.optional','Optional','admin',false,false),
('norwegian','admin.optional','Valgfri','admin',true,true),
('german','admin.optional','Optional','admin',true,true),
('kurdish_sorani','admin.optional','ئیختیاری','admin',true,true),
('kurdish_kurmanji','admin.optional','Bijartî','admin',true,true),
('english','admin.registration_step','Registration Step','admin',false,false),
('norwegian','admin.registration_step','Registreringstrinn','admin',true,true),
('german','admin.registration_step','Registrierungsschritt','admin',true,true),
('kurdish_sorani','admin.registration_step','هەنگاوی تۆمارکردن','admin',true,true),
('kurdish_kurmanji','admin.registration_step','Gava qeydkirinê','admin',true,true),
('english','admin.no_questions_found','No questions found','admin',false,false),
('norwegian','admin.no_questions_found','Ingen spørsmål funnet','admin',true,true),
('german','admin.no_questions_found','Keine Fragen gefunden','admin',true,true),
('kurdish_sorani','admin.no_questions_found','هیچ پرسیارێک نەدۆزرایەوە','admin',true,true),
('kurdish_kurmanji','admin.no_questions_found','Tu pirs nehatin dîtin','admin',true,true),
('english','admin.system_field_restricted','System field - some operations are restricted','admin',false,false),
('norwegian','admin.system_field_restricted','Systemfelt - noen operasjoner er begrenset','admin',true,true),
('german','admin.system_field_restricted','Systemfeld - einige Operationen sind eingeschränkt','admin',true,true),
('kurdish_sorani','admin.system_field_restricted','خانەی سیستەم - هەندێک کردار سنووردارن','admin',true,true),
('kurdish_kurmanji','admin.system_field_restricted','Qada sîstemê - hin karker sînordar in','admin',true,true),
('english','admin.maps_to','Maps to:','admin',false,false),
('norwegian','admin.maps_to','Tilordnes til:','admin',true,true),
('german','admin.maps_to','Zugeordnet zu:','admin',true,true),
('kurdish_sorani','admin.maps_to','دەگوازرێتەوە بۆ:','admin',true,true),
('kurdish_kurmanji','admin.maps_to','Tê nexşekirin bo:','admin',true,true),
('english','admin.add_new_registration_question','Add New Registration Question','admin',false,false),
('norwegian','admin.add_new_registration_question','Legg til nytt registreringsspørsmål','admin',true,true),
('german','admin.add_new_registration_question','Neue Registrierungsfrage hinzufügen','admin',true,true),
('kurdish_sorani','admin.add_new_registration_question','پرسیاری تۆمارکردنی نوێ زیاد بکە','admin',true,true),
('kurdish_kurmanji','admin.add_new_registration_question','Pirsa qeydkirinê ya nû lê zêde bike','admin',true,true),
('english','admin.create_question_desc','Create a new question for the registration process','admin',false,false),
('norwegian','admin.create_question_desc','Opprett et nytt spørsmål for registreringsprosessen','admin',true,true),
('german','admin.create_question_desc','Erstellen Sie eine neue Frage für den Registrierungsprozess','admin',true,true),
('kurdish_sorani','admin.create_question_desc','پرسیارێکی نوێ بۆ پرۆسەی تۆمارکردن دروست بکە','admin',true,true),
('kurdish_kurmanji','admin.create_question_desc','Ji bo pêvajoya qeydkirinê pirsek nû çêbikin','admin',true,true),
('english','admin.question_text','Question Text','admin',false,false),
('norwegian','admin.question_text','Spørsmålstekst','admin',true,true),
('german','admin.question_text','Fragentext','admin',true,true),
('kurdish_sorani','admin.question_text','دەقی پرسیار','admin',true,true),
('kurdish_kurmanji','admin.question_text','Nivîsa pirsê','admin',true,true),
('english','admin.placeholder_text','Placeholder Text','admin',false,false),
('norwegian','admin.placeholder_text','Plassholdertekst','admin',true,true),
('german','admin.placeholder_text','Platzhaltertext','admin',true,true),
('kurdish_sorani','admin.placeholder_text','دەقی شوێنگر','admin',true,true),
('kurdish_kurmanji','admin.placeholder_text','Nivîsa cîhgir','admin',true,true),
('english','admin.profile_field_mapping','Profile Field Mapping','admin',false,false),
('norwegian','admin.profile_field_mapping','Profilfelt-tilordning','admin',true,true),
('german','admin.profile_field_mapping','Profilfeldzuordnung','admin',true,true),
('kurdish_sorani','admin.profile_field_mapping','نەخشەکردنی خانەی پرۆفایل','admin',true,true),
('kurdish_kurmanji','admin.profile_field_mapping','Nexşekirina qada profîlê','admin',true,true),
('english','admin.field_options','Field Options','admin',false,false),
('norwegian','admin.field_options','Feltalternativer','admin',true,true),
('german','admin.field_options','Feldoptionen','admin',true,true),
('kurdish_sorani','admin.field_options','هەڵبژاردنەکانی خانە','admin',true,true),
('kurdish_kurmanji','admin.field_options','Vebijarkên qadê','admin',true,true),
('english','admin.add_new_option','Add a new option','admin',false,false),
('norwegian','admin.add_new_option','Legg til et nytt alternativ','admin',true,true),
('german','admin.add_new_option','Neue Option hinzufügen','admin',true,true),
('kurdish_sorani','admin.add_new_option','هەڵبژاردنێکی نوێ زیاد بکە','admin',true,true),
('kurdish_kurmanji','admin.add_new_option','Vebijarkek nû lê zêde bike','admin',true,true),
('english','admin.edit_registration_question','Edit Registration Question','admin',false,false),
('norwegian','admin.edit_registration_question','Rediger registreringsspørsmål','admin',true,true),
('german','admin.edit_registration_question','Registrierungsfrage bearbeiten','admin',true,true),
('kurdish_sorani','admin.edit_registration_question','پرسیاری تۆمارکردن دەستکاری بکە','admin',true,true),
('kurdish_kurmanji','admin.edit_registration_question','Pirsa qeydkirinê biguherîne','admin',true,true),
('english','admin.edit_question_desc','Make changes to the registration question below','admin',false,false),
('norwegian','admin.edit_question_desc','Gjør endringer i registreringsspørsmålet nedenfor','admin',true,true),
('german','admin.edit_question_desc','Nehmen Sie Änderungen an der Registrierungsfrage vor','admin',true,true),
('kurdish_sorani','admin.edit_question_desc','گۆڕانکاری لە پرسیاری تۆمارکردنی خوارەوە بکە','admin',true,true),
('kurdish_kurmanji','admin.edit_question_desc','Di pirsa qeydkirinê ya jêr de guhertinan bikin','admin',true,true),
('english','admin.question_text_required','Question text is required','admin',false,false),
('norwegian','admin.question_text_required','Spørsmålstekst er påkrevd','admin',true,true),
('german','admin.question_text_required','Fragentext ist erforderlich','admin',true,true),
('kurdish_sorani','admin.question_text_required','دەقی پرسیار پێویستە','admin',true,true),
('kurdish_kurmanji','admin.question_text_required','Nivîsa pirsê pêwîst e','admin',true,true),
('english','admin.preview','Preview','admin',false,false),
('norwegian','admin.preview','Forhåndsvisning','admin',true,true),
('german','admin.preview','Vorschau','admin',true,true),
('kurdish_sorani','admin.preview','پێشبینین','admin',true,true),
('kurdish_kurmanji','admin.preview','Pêşdîtin','admin',true,true),
('english','admin.mobile','Mobile','admin',false,false),
('norwegian','admin.mobile','Mobil','admin',true,true),
('german','admin.mobile','Mobil','admin',true,true),
('kurdish_sorani','admin.mobile','مۆبایل','admin',true,true),
('kurdish_kurmanji','admin.mobile','Mobîl','admin',true,true),
('english','admin.desktop','Desktop','admin',false,false),
('norwegian','admin.desktop','Skrivebord','admin',true,true),
('german','admin.desktop','Desktop','admin',true,true),
('kurdish_sorani','admin.desktop','دێسکتۆپ','admin',true,true),
('kurdish_kurmanji','admin.desktop','Desktop','admin',true,true),
('english','admin.registration_preview','Registration Preview','admin',false,false),
('norwegian','admin.registration_preview','Forhåndsvisning av registrering','admin',true,true),
('german','admin.registration_preview','Registrierungsvorschau','admin',true,true),
('kurdish_sorani','admin.registration_preview','پێشبینینی تۆمارکردن','admin',true,true),
('kurdish_kurmanji','admin.registration_preview','Pêşdîtina qeydkirinê','admin',true,true),
('english','admin.select_question_preview','Select a question to preview','admin',false,false),
('norwegian','admin.select_question_preview','Velg et spørsmål å forhåndsvise','admin',true,true),
('german','admin.select_question_preview','Wählen Sie eine Frage zur Vorschau','admin',true,true),
('kurdish_sorani','admin.select_question_preview','پرسیارێک هەڵبژێرە بۆ پێشبینین','admin',true,true),
('kurdish_kurmanji','admin.select_question_preview','Ji bo pêşdîtinê pirsek hilbijêrin','admin',true,true),
('english','admin.select_question_preview_desc','Select a question to preview how it will appear to users','admin',false,false),
('norwegian','admin.select_question_preview_desc','Velg et spørsmål for å forhåndsvise hvordan det vil se ut for brukere','admin',true,true),
('german','admin.select_question_preview_desc','Wählen Sie eine Frage, um die Vorschau für Benutzer anzuzeigen','admin',true,true),
('kurdish_sorani','admin.select_question_preview_desc','پرسیارێک هەڵبژێرە بۆ بینینی ئەوەی چۆن بۆ بەکارهێنەران دەردەکەوێت','admin',true,true),
('kurdish_kurmanji','admin.select_question_preview_desc','Ji bo pêşdîtina ku ew ê çawa ji bikarhêneran re xuya bibe pirsek hilbijêrin','admin',true,true),
('english','admin.continue','Continue','admin',false,false),
('norwegian','admin.continue','Fortsett','admin',true,true),
('german','admin.continue','Weiter','admin',true,true),
('kurdish_sorani','admin.continue','بەردەوام بە','admin',true,true),
('kurdish_kurmanji','admin.continue','Berdewam bike','admin',true,true),
('english','admin.unsupported_field_type','Unsupported field type','admin',false,false),
('norwegian','admin.unsupported_field_type','Felttype støttes ikke','admin',true,true),
('german','admin.unsupported_field_type','Nicht unterstützter Feldtyp','admin',true,true),
('kurdish_sorani','admin.unsupported_field_type','جۆری خانە پشتگیری ناکرێت','admin',true,true),
('kurdish_kurmanji','admin.unsupported_field_type','Tîpa qadê nayê piştgirîkirin','admin',true,true),
('english','admin.yes','Yes','admin',false,false),
('norwegian','admin.yes','Ja','admin',true,true),
('german','admin.yes','Ja','admin',true,true),
('kurdish_sorani','admin.yes','بەڵێ','admin',true,true),
('kurdish_kurmanji','admin.yes','Erê','admin',true,true),
('english','admin.questions_selected','questions selected','admin',false,false),
('norwegian','admin.questions_selected','spørsmål valgt','admin',true,true),
('german','admin.questions_selected','Fragen ausgewählt','admin',true,true),
('kurdish_sorani','admin.questions_selected','پرسیار هەڵبژێردراون','admin',true,true),
('kurdish_kurmanji','admin.questions_selected','pirs hatin hilbijartin','admin',true,true),
('english','admin.enable','Enable','admin',false,false),
('norwegian','admin.enable','Aktiver','admin',true,true),
('german','admin.enable','Aktivieren','admin',true,true),
('kurdish_sorani','admin.enable','چالاککردن','admin',true,true),
('kurdish_kurmanji','admin.enable','Çalak bike','admin',true,true),
('english','admin.disable','Disable','admin',false,false),
('norwegian','admin.disable','Deaktiver','admin',true,true),
('german','admin.disable','Deaktivieren','admin',true,true),
('kurdish_sorani','admin.disable','ناچالاککردن','admin',true,true),
('kurdish_kurmanji','admin.disable','Neçalak bike','admin',true,true),
('english','admin.system_fields_no_bulk','System fields cannot be modified in bulk operations','admin',false,false),
('norwegian','admin.system_fields_no_bulk','Systemfelt kan ikke endres i masseoperasjoner','admin',true,true),
('german','admin.system_fields_no_bulk','Systemfelder können nicht in Massenoperationen geändert werden','admin',true,true),
('kurdish_sorani','admin.system_fields_no_bulk','خانەکانی سیستەم ناتوانرێت لە کردارە کۆمەڵەکاندا بگۆڕدرێن','admin',true,true),
('kurdish_kurmanji','admin.system_fields_no_bulk','Qadên sîstemê nikarin di karên girseyî de werin guhertin','admin',true,true),
('english','admin.questions_deleted_success','{{count}} questions deleted successfully','admin',false,false),
('norwegian','admin.questions_deleted_success','{{count}} spørsmål slettet','admin',true,true),
('german','admin.questions_deleted_success','{{count}} Fragen erfolgreich gelöscht','admin',true,true),
('kurdish_sorani','admin.questions_deleted_success','{{count}} پرسیار بە سەرکەوتوویی سڕایەوە','admin',true,true),
('kurdish_kurmanji','admin.questions_deleted_success','{{count}} pirs bi serkeftî hatin jêbirin','admin',true,true),
('english','admin.questions_toggled_success','{{count}} questions {{action}} successfully','admin',false,false),
('norwegian','admin.questions_toggled_success','{{count}} spørsmål {{action}}','admin',true,true),
('german','admin.questions_toggled_success','{{count}} Fragen erfolgreich {{action}}','admin',true,true),
('kurdish_sorani','admin.questions_toggled_success','{{count}} پرسیار بە سەرکەوتوویی {{action}}','admin',true,true),
('kurdish_kurmanji','admin.questions_toggled_success','{{count}} pirs bi serkeftî {{action}}','admin',true,true),
('english','admin.system_fields_required','System fields are required for user registration','admin',false,false),
('norwegian','admin.system_fields_required','Systemfelt er påkrevd for brukerregistrering','admin',true,true),
('german','admin.system_fields_required','Systemfelder sind für die Benutzerregistrierung erforderlich','admin',true,true),
('kurdish_sorani','admin.system_fields_required','خانەکانی سیستەم پێویستن بۆ تۆمارکردنی بەکارهێنەر','admin',true,true),
('kurdish_kurmanji','admin.system_fields_required','Qadên sîstemê ji bo qeydkirina bikarhêneran pêwîst in','admin',true,true),
('english','admin.question_deleted_success','Question deleted successfully','admin',false,false),
('norwegian','admin.question_deleted_success','Spørsmål slettet','admin',true,true),
('german','admin.question_deleted_success','Frage erfolgreich gelöscht','admin',true,true),
('kurdish_sorani','admin.question_deleted_success','پرسیار بە سەرکەوتوویی سڕایەوە','admin',true,true),
('kurdish_kurmanji','admin.question_deleted_success','Pirs bi serkeftî hat jêbirin','admin',true,true),
('english','admin.question_updated_success','Question updated successfully','admin',false,false),
('norwegian','admin.question_updated_success','Spørsmål oppdatert','admin',true,true),
('german','admin.question_updated_success','Frage erfolgreich aktualisiert','admin',true,true),
('kurdish_sorani','admin.question_updated_success','پرسیار بە سەرکەوتوویی نوێکرایەوە','admin',true,true),
('kurdish_kurmanji','admin.question_updated_success','Pirs bi serkeftî hat nûkirin','admin',true,true),
('english','admin.question_added_success','New question added successfully','admin',false,false),
('norwegian','admin.question_added_success','Nytt spørsmål lagt til','admin',true,true),
('german','admin.question_added_success','Neue Frage erfolgreich hinzugefügt','admin',true,true),
('kurdish_sorani','admin.question_added_success','پرسیاری نوێ بە سەرکەوتوویی زیادکرا','admin',true,true),
('kurdish_kurmanji','admin.question_added_success','Pirsa nû bi serkeftî hat zêdekirin','admin',true,true),
('english','admin.profile_categories','Profile Categories','admin',false,false),
('norwegian','admin.profile_categories','Profilkategorier','admin',true,true),
('german','admin.profile_categories','Profilkategorien','admin',true,true),
('kurdish_sorani','admin.profile_categories','پۆلەکانی پرۆفایل','admin',true,true),
('kurdish_kurmanji','admin.profile_categories','Kategoriyên profîlê','admin',true,true),
('english','admin.manage_organize_categories','Manage and organize profile categories','admin',false,false),
('norwegian','admin.manage_organize_categories','Administrer og organiser profilkategorier','admin',true,true),
('german','admin.manage_organize_categories','Profilkategorien verwalten und organisieren','admin',true,true),
('kurdish_sorani','admin.manage_organize_categories','بەڕێوەبردن و ڕێکخستنی پۆلەکانی پرۆفایل','admin',true,true),
('kurdish_kurmanji','admin.manage_organize_categories','Kategoriyên profîlê birêvebirin û organîze bikin','admin',true,true),
('english','admin.search_categories','Search categories...','admin',false,false),
('norwegian','admin.search_categories','Søk kategorier...','admin',true,true),
('german','admin.search_categories','Kategorien suchen...','admin',true,true),
('kurdish_sorani','admin.search_categories','گەڕان بۆ پۆلەکان...','admin',true,true),
('kurdish_kurmanji','admin.search_categories','Li kategoriyan bigerin...','admin',true,true),
('english','admin.all','All','admin',false,false),
('norwegian','admin.all','Alle','admin',true,true),
('german','admin.all','Alle','admin',true,true),
('kurdish_sorani','admin.all','هەموو','admin',true,true),
('kurdish_kurmanji','admin.all','Hemû','admin',true,true),
('english','admin.active_status','Active','admin',false,false),
('norwegian','admin.active_status','Aktiv','admin',true,true),
('german','admin.active_status','Aktiv','admin',true,true),
('kurdish_sorani','admin.active_status','چالاک','admin',true,true),
('kurdish_kurmanji','admin.active_status','Çalak','admin',true,true),
('english','admin.inactive_status','Inactive','admin',false,false),
('norwegian','admin.inactive_status','Inaktiv','admin',true,true),
('german','admin.inactive_status','Inaktiv','admin',true,true),
('kurdish_sorani','admin.inactive_status','ناچالاک','admin',true,true),
('kurdish_kurmanji','admin.inactive_status','Neçalak','admin',true,true),
('english','admin.name','Name','admin',false,false),
('norwegian','admin.name','Navn','admin',true,true),
('german','admin.name','Name','admin',true,true),
('kurdish_sorani','admin.name','ناو','admin',true,true),
('kurdish_kurmanji','admin.name','Nav','admin',true,true),
('english','admin.description','Description','admin',false,false),
('norwegian','admin.description','Beskrivelse','admin',true,true),
('german','admin.description','Beschreibung','admin',true,true),
('kurdish_sorani','admin.description','وەسف','admin',true,true),
('kurdish_kurmanji','admin.description','Danasîn','admin',true,true),
('english','admin.order','Order','admin',false,false),
('norwegian','admin.order','Rekkefølge','admin',true,true),
('german','admin.order','Reihenfolge','admin',true,true),
('kurdish_sorani','admin.order','ڕیزبەندی','admin',true,true),
('kurdish_kurmanji','admin.order','Rêz','admin',true,true),
('english','admin.updated','Updated','admin',false,false),
('norwegian','admin.updated','Oppdatert','admin',true,true),
('german','admin.updated','Aktualisiert','admin',true,true),
('kurdish_sorani','admin.updated','نوێکرایەوە','admin',true,true),
('kurdish_kurmanji','admin.updated','Nûkirin','admin',true,true),
('english','admin.view_items','View Items','admin',false,false),
('norwegian','admin.view_items','Vis elementer','admin',true,true),
('german','admin.view_items','Elemente anzeigen','admin',true,true),
('kurdish_sorani','admin.view_items','بینینی بڕگەکان','admin',true,true),
('kurdish_kurmanji','admin.view_items','Hêmanan bibînin','admin',true,true),
('english','admin.no_categories_found','No categories found','admin',false,false),
('norwegian','admin.no_categories_found','Ingen kategorier funnet','admin',true,true),
('german','admin.no_categories_found','Keine Kategorien gefunden','admin',true,true),
('kurdish_sorani','admin.no_categories_found','هیچ پۆلێک نەدۆزرایەوە','admin',true,true),
('kurdish_kurmanji','admin.no_categories_found','Tu kategorî nehatin dîtin','admin',true,true),
('english','admin.categories_reordered','Categories reordered successfully','admin',false,false),
('norwegian','admin.categories_reordered','Kategorier omorganisert','admin',true,true),
('german','admin.categories_reordered','Kategorien erfolgreich neu geordnet','admin',true,true),
('kurdish_sorani','admin.categories_reordered','پۆلەکان بە سەرکەوتوویی ڕیزبەندکرانەوە','admin',true,true),
('kurdish_kurmanji','admin.categories_reordered','Kategorî bi serkeftî hatin rêzkirin','admin',true,true),
('english','admin.items_reordered','Items reordered successfully','admin',false,false),
('norwegian','admin.items_reordered','Elementer omorganisert','admin',true,true),
('german','admin.items_reordered','Elemente erfolgreich neu geordnet','admin',true,true),
('kurdish_sorani','admin.items_reordered','بڕگەکان بە سەرکەوتوویی ڕیزبەندکرانەوە','admin',true,true),
('kurdish_kurmanji','admin.items_reordered','Hêman bi serkeftî hatin rêzkirin','admin',true,true),
('english','admin.category_added','Category added successfully','admin',false,false),
('norwegian','admin.category_added','Kategori lagt til','admin',true,true),
('german','admin.category_added','Kategorie erfolgreich hinzugefügt','admin',true,true),
('kurdish_sorani','admin.category_added','پۆل بە سەرکەوتوویی زیادکرا','admin',true,true),
('kurdish_kurmanji','admin.category_added','Kategorî bi serkeftî hat zêdekirin','admin',true,true),
('english','admin.category_updated','Category updated successfully','admin',false,false),
('norwegian','admin.category_updated','Kategori oppdatert','admin',true,true),
('german','admin.category_updated','Kategorie erfolgreich aktualisiert','admin',true,true),
('kurdish_sorani','admin.category_updated','پۆل بە سەرکەوتوویی نوێکرایەوە','admin',true,true),
('kurdish_kurmanji','admin.category_updated','Kategorî bi serkeftî hat nûkirin','admin',true,true),
('english','admin.category_deleted','Category deleted successfully','admin',false,false),
('norwegian','admin.category_deleted','Kategori slettet','admin',true,true),
('german','admin.category_deleted','Kategorie erfolgreich gelöscht','admin',true,true),
('kurdish_sorani','admin.category_deleted','پۆل بە سەرکەوتوویی سڕایەوە','admin',true,true),
('kurdish_kurmanji','admin.category_deleted','Kategorî bi serkeftî hat jêbirin','admin',true,true),
('english','admin.item_added','Item added successfully','admin',false,false),
('norwegian','admin.item_added','Element lagt til','admin',true,true),
('german','admin.item_added','Element erfolgreich hinzugefügt','admin',true,true),
('kurdish_sorani','admin.item_added','بڕگە بە سەرکەوتوویی زیادکرا','admin',true,true),
('kurdish_kurmanji','admin.item_added','Hêman bi serkeftî hat zêdekirin','admin',true,true),
('english','admin.item_updated','Item updated successfully','admin',false,false),
('norwegian','admin.item_updated','Element oppdatert','admin',true,true),
('german','admin.item_updated','Element erfolgreich aktualisiert','admin',true,true),
('kurdish_sorani','admin.item_updated','بڕگە بە سەرکەوتوویی نوێکرایەوە','admin',true,true),
('kurdish_kurmanji','admin.item_updated','Hêman bi serkeftî hat nûkirin','admin',true,true),
('english','admin.item_deleted','Item deleted successfully','admin',false,false),
('norwegian','admin.item_deleted','Element slettet','admin',true,true),
('german','admin.item_deleted','Element erfolgreich gelöscht','admin',true,true),
('kurdish_sorani','admin.item_deleted','بڕگە بە سەرکەوتوویی سڕایەوە','admin',true,true),
('kurdish_kurmanji','admin.item_deleted','Hêman bi serkeftî hat jêbirin','admin',true,true),
('english','admin.search_items','Search items...','admin',false,false),
('norwegian','admin.search_items','Søk elementer...','admin',true,true),
('german','admin.search_items','Elemente suchen...','admin',true,true),
('kurdish_sorani','admin.search_items','گەڕان بۆ بڕگەکان...','admin',true,true),
('kurdish_kurmanji','admin.search_items','Li hêmanan bigerin...','admin',true,true),
('english','admin.type','Type','admin',false,false),
('norwegian','admin.type','Type','admin',true,true),
('german','admin.type','Typ','admin',true,true),
('kurdish_sorani','admin.type','جۆر','admin',true,true),
('kurdish_kurmanji','admin.type','Tîp','admin',true,true),
('english','admin.last_updated','Last Updated','admin',false,false),
('norwegian','admin.last_updated','Sist oppdatert','admin',true,true),
('german','admin.last_updated','Zuletzt aktualisiert','admin',true,true),
('kurdish_sorani','admin.last_updated','دوایین نوێکردنەوە','admin',true,true),
('kurdish_kurmanji','admin.last_updated','Nûkirina dawî','admin',true,true),
('english','admin.view_all_categories','View All Categories','admin',false,false),
('norwegian','admin.view_all_categories','Vis alle kategorier','admin',true,true),
('german','admin.view_all_categories','Alle Kategorien anzeigen','admin',true,true),
('kurdish_sorani','admin.view_all_categories','بینینی هەموو پۆلەکان','admin',true,true),
('kurdish_kurmanji','admin.view_all_categories','Hemû kategoriyan bibînin','admin',true,true),
('english','admin.failed_load_roles','Failed to load roles','admin',false,false),
('norwegian','admin.failed_load_roles','Kunne ikke laste roller','admin',true,true),
('german','admin.failed_load_roles','Rollen konnten nicht geladen werden','admin',true,true),
('kurdish_sorani','admin.failed_load_roles','ڕۆڵەکان بارنەبوون','admin',true,true),
('kurdish_kurmanji','admin.failed_load_roles','Rol nehatin barkirin','admin',true,true),
('english','admin.role_deletion_not_implemented','Role deletion not yet implemented','admin',false,false),
('norwegian','admin.role_deletion_not_implemented','Sletting av roller er ikke implementert ennå','admin',true,true),
('german','admin.role_deletion_not_implemented','Rollenlöschung noch nicht implementiert','admin',true,true),
('kurdish_sorani','admin.role_deletion_not_implemented','سڕینەوەی ڕۆڵ هێشتا جێبەجێنەکراوە','admin',true,true),
('kurdish_kurmanji','admin.role_deletion_not_implemented','Jêbirina rolan hê nehatiye pêkanîn','admin',true,true),
('english','admin.campaign_started','Campaign started','admin',false,false),
('norwegian','admin.campaign_started','Kampanje startet','admin',true,true),
('german','admin.campaign_started','Kampagne gestartet','admin',true,true),
('kurdish_sorani','admin.campaign_started','کەمپەین دەستیپێکرد','admin',true,true),
('kurdish_kurmanji','admin.campaign_started','Kampanya dest pê kir','admin',true,true),
('english','admin.campaign_paused','Campaign paused','admin',false,false),
('norwegian','admin.campaign_paused','Kampanje satt på pause','admin',true,true),
('german','admin.campaign_paused','Kampagne pausiert','admin',true,true),
('kurdish_sorani','admin.campaign_paused','کەمپەین وەستێنرا','admin',true,true),
('kurdish_kurmanji','admin.campaign_paused','Kampanya hat sekinandin','admin',true,true),
('english','admin.campaign_deleted','Campaign deleted','admin',false,false),
('norwegian','admin.campaign_deleted','Kampanje slettet','admin',true,true),
('german','admin.campaign_deleted','Kampagne gelöscht','admin',true,true),
('kurdish_sorani','admin.campaign_deleted','کەمپەین سڕایەوە','admin',true,true),
('kurdish_kurmanji','admin.campaign_deleted','Kampanya hat jêbirin','admin',true,true),
('english','admin.remove_api_key_confirm','Remove {{label}}? This will disable features that depend on it.','admin',false,false),
('norwegian','admin.remove_api_key_confirm','Fjerne {{label}}? Dette vil deaktivere funksjoner som avhenger av den.','admin',true,true),
('german','admin.remove_api_key_confirm','{{label}} entfernen? Dies deaktiviert abhängige Funktionen.','admin',true,true),
('kurdish_sorani','admin.remove_api_key_confirm','{{label}} بسڕیتەوە؟ ئەمە تایبەتمەندییەکان ناچالاک دەکات.','admin',true,true),
('kurdish_kurmanji','admin.remove_api_key_confirm','{{label}} jê bibe? Ev ê taybetmendiyên girêdayî neçalak bike.','admin',true,true),
('english','admin.key_saved_success','{{label}} saved successfully','admin',false,false),
('norwegian','admin.key_saved_success','{{label}} lagret','admin',true,true),
('german','admin.key_saved_success','{{label}} erfolgreich gespeichert','admin',true,true),
('kurdish_sorani','admin.key_saved_success','{{label}} بە سەرکەوتوویی پاشەکەوتکرا','admin',true,true),
('kurdish_kurmanji','admin.key_saved_success','{{label}} bi serkeftî hat tomarkirin','admin',true,true),
('english','admin.key_removed','{{label}} removed','admin',false,false),
('norwegian','admin.key_removed','{{label}} fjernet','admin',true,true),
('german','admin.key_removed','{{label}} entfernt','admin',true,true),
('kurdish_sorani','admin.key_removed','{{label}} لابرا','admin',true,true),
('kurdish_kurmanji','admin.key_removed','{{label}} hat rakirin','admin',true,true),
('english','admin.please_enter_value','Please enter a value','admin',false,false),
('norwegian','admin.please_enter_value','Vennligst skriv inn en verdi','admin',true,true),
('german','admin.please_enter_value','Bitte geben Sie einen Wert ein','admin',true,true),
('kurdish_sorani','admin.please_enter_value','تکایە بەهایەک بنووسە','admin',true,true),
('kurdish_kurmanji','admin.please_enter_value','Ji kerema xwe nirxek binivîsin','admin',true,true),
('english','admin.all_users_deactivated','All users have been deactivated','admin',false,false),
('norwegian','admin.all_users_deactivated','Alle brukere er deaktivert','admin',true,true),
('german','admin.all_users_deactivated','Alle Benutzer wurden deaktiviert','admin',true,true),
('kurdish_sorani','admin.all_users_deactivated','هەموو بەکارهێنەران ناچالاککران','admin',true,true),
('kurdish_kurmanji','admin.all_users_deactivated','Hemû bikarhêner hatin neçalakkirin','admin',true,true),
('english','admin.no_other_users_role','No other users with the role "{{role}}" were found','admin',false,false),
('norwegian','admin.no_other_users_role','Ingen andre brukere med rollen "{{role}}" ble funnet','admin',true,true),
('german','admin.no_other_users_role','Keine anderen Benutzer mit der Rolle "{{role}}" gefunden','admin',true,true),
('kurdish_sorani','admin.no_other_users_role','هیچ بەکارهێنەرێکی تر بە ڕۆڵی "{{role}}" نەدۆزرایەوە','admin',true,true),
('kurdish_kurmanji','admin.no_other_users_role','Tu bikarhênerên din bi rola "{{role}}" nehatin dîtin','admin',true,true),
('english','admin.role_users_deactivated','All users with role "{{role}}" have been deactivated','admin',false,false),
('norwegian','admin.role_users_deactivated','Alle brukere med rollen "{{role}}" er deaktivert','admin',true,true),
('german','admin.role_users_deactivated','Alle Benutzer mit der Rolle "{{role}}" wurden deaktiviert','admin',true,true),
('kurdish_sorani','admin.role_users_deactivated','هەموو بەکارهێنەرانی ڕۆڵی "{{role}}" ناچالاککران','admin',true,true),
('kurdish_kurmanji','admin.role_users_deactivated','Hemû bikarhênerên bi rola "{{role}}" hatin neçalakkirin','admin',true,true),
('english','admin.no_users_role','No users with the role "{{role}}" were found','admin',false,false),
('norwegian','admin.no_users_role','Ingen brukere med rollen "{{role}}" ble funnet','admin',true,true),
('german','admin.no_users_role','Keine Benutzer mit der Rolle "{{role}}" gefunden','admin',true,true),
('kurdish_sorani','admin.no_users_role','هیچ بەکارهێنەرێک بە ڕۆڵی "{{role}}" نەدۆزرایەوە','admin',true,true),
('kurdish_kurmanji','admin.no_users_role','Tu bikarhêner bi rola "{{role}}" nehatin dîtin','admin',true,true),
('english','admin.error_deactivating_users','There was an error deactivating users','admin',false,false),
('norwegian','admin.error_deactivating_users','Det oppstod en feil ved deaktivering av brukere','admin',true,true),
('german','admin.error_deactivating_users','Beim Deaktivieren der Benutzer ist ein Fehler aufgetreten','admin',true,true),
('kurdish_sorani','admin.error_deactivating_users','هەڵەیەک ڕوویدا لە ناچالاککردنی بەکارهێنەران','admin',true,true),
('kurdish_kurmanji','admin.error_deactivating_users','Di neçalakkirina bikarhêneran de çewtî çêbû','admin',true,true),
('english','admin.could_not_load_users','Could not load user data. Please try again.','admin',false,false),
('norwegian','admin.could_not_load_users','Kunne ikke laste brukerdata. Prøv igjen.','admin',true,true),
('german','admin.could_not_load_users','Benutzerdaten konnten nicht geladen werden. Bitte versuchen Sie es erneut.','admin',true,true),
('kurdish_sorani','admin.could_not_load_users','داتای بەکارهێنەران بارنەبوو. تکایە دووبارە هەوڵبدەرەوە.','admin',true,true),
('kurdish_kurmanji','admin.could_not_load_users','Daneyên bikarhêneran nehatin barkirin. Ji kerema xwe dîsa biceribînin.','admin',true,true)
ON CONFLICT (language_code, translation_key) DO NOTHING;
