
INSERT INTO public.app_translations (language_code, translation_key, translation_value, category, context) VALUES
-- Support categories (shared between ContactSupportDialog and MyTickets)
('english','support.cat_account','Account Issues','support','category label'),
('english','support.cat_billing','Billing & Payments','support','category label'),
('english','support.cat_technical','Technical Problems','support','category label'),
('english','support.cat_safety','Safety Concerns','support','category label'),
('english','support.cat_feedback','Feedback & Suggestions','support','category label'),
('english','support.cat_other','Other','support','category label'),
('norwegian','support.cat_account','Kontoproblemer','support','category label'),
('norwegian','support.cat_billing','Fakturering og betalinger','support','category label'),
('norwegian','support.cat_technical','Tekniske problemer','support','category label'),
('norwegian','support.cat_safety','Sikkerhetsbekymringer','support','category label'),
('norwegian','support.cat_feedback','Tilbakemeldinger og forslag','support','category label'),
('norwegian','support.cat_other','Annet','support','category label'),
('german','support.cat_account','Kontoprobleme','support','category label'),
('german','support.cat_billing','Abrechnung & Zahlungen','support','category label'),
('german','support.cat_technical','Technische Probleme','support','category label'),
('german','support.cat_safety','Sicherheitsbedenken','support','category label'),
('german','support.cat_feedback','Feedback & Vorschläge','support','category label'),
('german','support.cat_other','Sonstiges','support','category label'),
('kurdish_sorani','support.cat_account','کێشەی هەژمار','support','category label'),
('kurdish_sorani','support.cat_billing','پارەدان و فاتوورە','support','category label'),
('kurdish_sorani','support.cat_technical','کێشەی تەکنیکی','support','category label'),
('kurdish_sorani','support.cat_safety','نیگەرانی ئاسایش','support','category label'),
('kurdish_sorani','support.cat_feedback','ڕاوبۆچوون و پێشنیار','support','category label'),
('kurdish_sorani','support.cat_other','هی تر','support','category label'),
('kurdish_kurmanci','support.cat_account','Pirsgirêkên hesabê','support','category label'),
('kurdish_kurmanci','support.cat_billing','Fature û peredan','support','category label'),
('kurdish_kurmanci','support.cat_technical','Pirsgirêkên teknîkî','support','category label'),
('kurdish_kurmanci','support.cat_safety','Fikarên ewlehiyê','support','category label'),
('kurdish_kurmanci','support.cat_feedback','Bertek û pêşniyar','support','category label'),
('kurdish_kurmanci','support.cat_other','Yên din','support','category label'),

-- MyTickets status labels
('english','support.status_open','Open','support','ticket status'),
('english','support.status_pending','In Progress','support','ticket status'),
('english','support.status_resolved','Resolved','support','ticket status'),
('english','support.status_closed','Closed','support','ticket status'),
('norwegian','support.status_open','Åpen','support','ticket status'),
('norwegian','support.status_pending','Under behandling','support','ticket status'),
('norwegian','support.status_resolved','Løst','support','ticket status'),
('norwegian','support.status_closed','Lukket','support','ticket status'),
('german','support.status_open','Offen','support','ticket status'),
('german','support.status_pending','In Bearbeitung','support','ticket status'),
('german','support.status_resolved','Gelöst','support','ticket status'),
('german','support.status_closed','Geschlossen','support','ticket status'),
('kurdish_sorani','support.status_open','کراوە','support','ticket status'),
('kurdish_sorani','support.status_pending','لە بەردەستدایە','support','ticket status'),
('kurdish_sorani','support.status_resolved','چارەسەرکرا','support','ticket status'),
('kurdish_sorani','support.status_closed','داخرا','support','ticket status'),
('kurdish_kurmanci','support.status_open','Vekirî','support','ticket status'),
('kurdish_kurmanci','support.status_pending','Di pêvajoyê de','support','ticket status'),
('kurdish_kurmanci','support.status_resolved','Çareser kirin','support','ticket status'),
('kurdish_kurmanci','support.status_closed','Girtî','support','ticket status'),

-- MyTickets UI strings
('english','support.login_required','Please log in to view your support tickets','support','MyTickets'),
('english','support.my_tickets','My Support Tickets','support','MyTickets'),
('english','support.track_requests','Track your support requests','support','MyTickets'),
('english','support.no_tickets','No support tickets yet','support','MyTickets'),
('english','support.contact_if_help','Contact support if you need help','support','MyTickets'),
('english','support.active','Active','support','MyTickets tab'),
('english','support.resolved','Resolved','support','MyTickets tab'),
('english','support.has_response','Has response','support','MyTickets'),
('english','support.your_message','Your Message:','support','MyTickets'),
('english','support.support_response','Support Response:','support','MyTickets'),
('english','support.rate_experience','How was your support experience?','support','MyTickets'),
('english','support.feedback_placeholder','Share additional feedback (optional)','support','MyTickets'),
('english','support.submit_feedback','Submit Feedback','support','MyTickets'),
('english','support.was_helpful','Was this helpful?','support','MyTickets'),
('english','support.rate_support','Rate Support','support','MyTickets'),
('english','support.your_rating','Your Rating:','support','MyTickets'),
('english','support.ticket_id','Ticket ID','support','MyTickets'),
('english','support.resolved_date','Resolved','support','MyTickets'),
('norwegian','support.login_required','Logg inn for å se støttebillettene dine','support','MyTickets'),
('norwegian','support.my_tickets','Mine støttebilletter','support','MyTickets'),
('norwegian','support.track_requests','Spor støtteforespørslene dine','support','MyTickets'),
('norwegian','support.no_tickets','Ingen støttebilletter ennå','support','MyTickets'),
('norwegian','support.contact_if_help','Kontakt støtte hvis du trenger hjelp','support','MyTickets'),
('norwegian','support.active','Aktive','support','MyTickets tab'),
('norwegian','support.resolved','Løst','support','MyTickets tab'),
('norwegian','support.has_response','Har svar','support','MyTickets'),
('norwegian','support.your_message','Din melding:','support','MyTickets'),
('norwegian','support.support_response','Støttesvar:','support','MyTickets'),
('norwegian','support.rate_experience','Hvordan var støtteopplevelsen din?','support','MyTickets'),
('norwegian','support.feedback_placeholder','Del tilleggstilbakemelding (valgfritt)','support','MyTickets'),
('norwegian','support.submit_feedback','Send tilbakemelding','support','MyTickets'),
('norwegian','support.was_helpful','Var dette nyttig?','support','MyTickets'),
('norwegian','support.rate_support','Vurder støtte','support','MyTickets'),
('norwegian','support.your_rating','Din vurdering:','support','MyTickets'),
('norwegian','support.ticket_id','Billett-ID','support','MyTickets'),
('norwegian','support.resolved_date','Løst','support','MyTickets'),
('german','support.login_required','Bitte melden Sie sich an, um Ihre Support-Tickets zu sehen','support','MyTickets'),
('german','support.my_tickets','Meine Support-Tickets','support','MyTickets'),
('german','support.track_requests','Verfolgen Sie Ihre Support-Anfragen','support','MyTickets'),
('german','support.no_tickets','Noch keine Support-Tickets','support','MyTickets'),
('german','support.contact_if_help','Kontaktieren Sie den Support, wenn Sie Hilfe benötigen','support','MyTickets'),
('german','support.active','Aktiv','support','MyTickets tab'),
('german','support.resolved','Gelöst','support','MyTickets tab'),
('german','support.has_response','Hat Antwort','support','MyTickets'),
('german','support.your_message','Ihre Nachricht:','support','MyTickets'),
('german','support.support_response','Support-Antwort:','support','MyTickets'),
('german','support.rate_experience','Wie war Ihre Support-Erfahrung?','support','MyTickets'),
('german','support.feedback_placeholder','Zusätzliches Feedback teilen (optional)','support','MyTickets'),
('german','support.submit_feedback','Feedback absenden','support','MyTickets'),
('german','support.was_helpful','War das hilfreich?','support','MyTickets'),
('german','support.rate_support','Support bewerten','support','MyTickets'),
('german','support.your_rating','Ihre Bewertung:','support','MyTickets'),
('german','support.ticket_id','Ticket-ID','support','MyTickets'),
('german','support.resolved_date','Gelöst','support','MyTickets'),
('kurdish_sorani','support.login_required','تکایە بچۆرە ژوورەوە بۆ بینینی تیکەتەکانت','support','MyTickets'),
('kurdish_sorani','support.my_tickets','تیکەتەکانی پشتگیری من','support','MyTickets'),
('kurdish_sorani','support.track_requests','شوێنکەوتنی داواکاریەکانی پشتگیری','support','MyTickets'),
('kurdish_sorani','support.no_tickets','هیچ تیکەتێکی پشتگیری نییە','support','MyTickets'),
('kurdish_sorani','support.contact_if_help','پەیوەندی بکە بە پشتگیری ئەگەر پێویستت بە یارمەتی هەیە','support','MyTickets'),
('kurdish_sorani','support.active','چالاک','support','MyTickets tab'),
('kurdish_sorani','support.resolved','چارەسەرکرا','support','MyTickets tab'),
('kurdish_sorani','support.has_response','وەڵامی هەیە','support','MyTickets'),
('kurdish_sorani','support.your_message','نامەکەت:','support','MyTickets'),
('kurdish_sorani','support.support_response','وەڵامی پشتگیری:','support','MyTickets'),
('kurdish_sorani','support.rate_experience','ئەزموونی پشتگیریت چۆن بوو؟','support','MyTickets'),
('kurdish_sorani','support.feedback_placeholder','ڕاوبۆچوونی زیاتر بنووسە (ئارەزوومەندانە)','support','MyTickets'),
('kurdish_sorani','support.submit_feedback','ناردنی ڕاوبۆچوون','support','MyTickets'),
('kurdish_sorani','support.was_helpful','ئایا ئەمە بەسوود بوو؟','support','MyTickets'),
('kurdish_sorani','support.rate_support','هەڵسەنگاندنی پشتگیری','support','MyTickets'),
('kurdish_sorani','support.your_rating','هەڵسەنگاندنەکەت:','support','MyTickets'),
('kurdish_sorani','support.ticket_id','ناسنامەی تیکەت','support','MyTickets'),
('kurdish_sorani','support.resolved_date','چارەسەرکرا','support','MyTickets'),
('kurdish_kurmanci','support.login_required','Ji kerema xwe têkevin bo dîtina bilêtên piştgiriyê','support','MyTickets'),
('kurdish_kurmanci','support.my_tickets','Bilêtên piştgiriyê yên min','support','MyTickets'),
('kurdish_kurmanci','support.track_requests','Daxwazên piştgiriyê bişopînin','support','MyTickets'),
('kurdish_kurmanci','support.no_tickets','Hîn bilêtek piştgiriyê tune','support','MyTickets'),
('kurdish_kurmanci','support.contact_if_help','Heke hewcedariya we bi alîkariyê heye bi piştgiriyê re têkilî daynin','support','MyTickets'),
('kurdish_kurmanci','support.active','Çalak','support','MyTickets tab'),
('kurdish_kurmanci','support.resolved','Çareser kirin','support','MyTickets tab'),
('kurdish_kurmanci','support.has_response','Bersiv heye','support','MyTickets'),
('kurdish_kurmanci','support.your_message','Peyama te:','support','MyTickets'),
('kurdish_kurmanci','support.support_response','Bersiva piştgiriyê:','support','MyTickets'),
('kurdish_kurmanci','support.rate_experience','Ezmûna piştgiriyê çawa bû?','support','MyTickets'),
('kurdish_kurmanci','support.feedback_placeholder','Bertek û şîroveya zêde parve bikin (bijartî)','support','MyTickets'),
('kurdish_kurmanci','support.submit_feedback','Bertekê bişînin','support','MyTickets'),
('kurdish_kurmanci','support.was_helpful','Ev arîkar bû?','support','MyTickets'),
('kurdish_kurmanci','support.rate_support','Piştgiriyê binirxînin','support','MyTickets'),
('kurdish_kurmanci','support.your_rating','Nirxandina te:','support','MyTickets'),
('kurdish_kurmanci','support.ticket_id','ID-ya bilêtê','support','MyTickets'),
('kurdish_kurmanci','support.resolved_date','Çareser kirin','support','MyTickets'),

-- ProfileActionButtons
('english','profile.following','Following','profile','ProfileActionButtons'),
('english','profile.follow','Follow','profile','ProfileActionButtons'),
('english','profile.message','Message','profile','ProfileActionButtons'),
('english','profile.pm_premium','PM - Premium Feature','profile','ProfileActionButtons'),
('english','profile.send_unlimited','Send unlimited messages to Premium and Gold members!','profile','ProfileActionButtons'),
('english','profile.premium_benefits','Premium Benefits:','profile','ProfileActionButtons'),
('english','profile.benefit_messages','Send messages to anyone','profile','ProfileActionButtons'),
('english','profile.benefit_super_likes','10 Super Likes per day','profile','ProfileActionButtons'),
('english','profile.benefit_unlimited_likes','Unlimited regular likes','profile','ProfileActionButtons'),
('english','profile.benefit_see_likes','See who liked you','profile','ProfileActionButtons'),
('english','profile.benefit_rewinds','5 Rewinds per day','profile','ProfileActionButtons'),
('english','profile.upgrade_premium','Upgrade to Premium','profile','ProfileActionButtons'),
('norwegian','profile.following','Følger','profile','ProfileActionButtons'),
('norwegian','profile.follow','Følg','profile','ProfileActionButtons'),
('norwegian','profile.message','Melding','profile','ProfileActionButtons'),
('norwegian','profile.pm_premium','PM - Premiumfunksjon','profile','ProfileActionButtons'),
('norwegian','profile.send_unlimited','Send ubegrenset med meldinger til Premium- og Gold-medlemmer!','profile','ProfileActionButtons'),
('norwegian','profile.premium_benefits','Premiumfordeler:','profile','ProfileActionButtons'),
('norwegian','profile.benefit_messages','Send meldinger til hvem som helst','profile','ProfileActionButtons'),
('norwegian','profile.benefit_super_likes','10 Super Likes per dag','profile','ProfileActionButtons'),
('norwegian','profile.benefit_unlimited_likes','Ubegrenset vanlige likes','profile','ProfileActionButtons'),
('norwegian','profile.benefit_see_likes','Se hvem som likte deg','profile','ProfileActionButtons'),
('norwegian','profile.benefit_rewinds','5 Angrer per dag','profile','ProfileActionButtons'),
('norwegian','profile.upgrade_premium','Oppgrader til Premium','profile','ProfileActionButtons'),
('german','profile.following','Folge ich','profile','ProfileActionButtons'),
('german','profile.follow','Folgen','profile','ProfileActionButtons'),
('german','profile.message','Nachricht','profile','ProfileActionButtons'),
('german','profile.pm_premium','PM - Premium-Funktion','profile','ProfileActionButtons'),
('german','profile.send_unlimited','Sende unbegrenzt Nachrichten an Premium- und Gold-Mitglieder!','profile','ProfileActionButtons'),
('german','profile.premium_benefits','Premium-Vorteile:','profile','ProfileActionButtons'),
('german','profile.benefit_messages','Nachrichten an jeden senden','profile','ProfileActionButtons'),
('german','profile.benefit_super_likes','10 Super Likes pro Tag','profile','ProfileActionButtons'),
('german','profile.benefit_unlimited_likes','Unbegrenzte reguläre Likes','profile','ProfileActionButtons'),
('german','profile.benefit_see_likes','Sehen, wer dich geliked hat','profile','ProfileActionButtons'),
('german','profile.benefit_rewinds','5 Zurückspulen pro Tag','profile','ProfileActionButtons'),
('german','profile.upgrade_premium','Auf Premium upgraden','profile','ProfileActionButtons'),
('kurdish_sorani','profile.following','شوێنکەوتن','profile','ProfileActionButtons'),
('kurdish_sorani','profile.follow','شوێنکەوتن','profile','ProfileActionButtons'),
('kurdish_sorani','profile.message','نامە','profile','ProfileActionButtons'),
('kurdish_sorani','profile.pm_premium','نامە - تایبەتمەندی پریمیۆم','profile','ProfileActionButtons'),
('kurdish_sorani','profile.send_unlimited','نامەی بێسنوور بنێرە بۆ ئەندامانی پریمیۆم و گۆڵد!','profile','ProfileActionButtons'),
('kurdish_sorani','profile.premium_benefits','سوودەکانی پریمیۆم:','profile','ProfileActionButtons'),
('kurdish_sorani','profile.benefit_messages','نامە بنێرە بۆ هەر کەسێک','profile','ProfileActionButtons'),
('kurdish_sorani','profile.benefit_super_likes','١٠ سوپەر لایک لە ڕۆژێکدا','profile','ProfileActionButtons'),
('kurdish_sorani','profile.benefit_unlimited_likes','لایکی ئاسایی بێسنوور','profile','ProfileActionButtons'),
('kurdish_sorani','profile.benefit_see_likes','ببینە کێ لایکی کردیت','profile','ProfileActionButtons'),
('kurdish_sorani','profile.benefit_rewinds','٥ گەڕانەوە لە ڕۆژێکدا','profile','ProfileActionButtons'),
('kurdish_sorani','profile.upgrade_premium','نوێکردنەوە بۆ پریمیۆم','profile','ProfileActionButtons'),
('kurdish_kurmanci','profile.following','Dişopînim','profile','ProfileActionButtons'),
('kurdish_kurmanci','profile.follow','Bişopîne','profile','ProfileActionButtons'),
('kurdish_kurmanci','profile.message','Peyam','profile','ProfileActionButtons'),
('kurdish_kurmanci','profile.pm_premium','PM - Taybetmendiya Premium','profile','ProfileActionButtons'),
('kurdish_kurmanci','profile.send_unlimited','Peyamên bêsînor ji endamên Premium û Gold re bişîne!','profile','ProfileActionButtons'),
('kurdish_kurmanci','profile.premium_benefits','Feydeyên Premium:','profile','ProfileActionButtons'),
('kurdish_kurmanci','profile.benefit_messages','Ji her kesî re peyam bişîne','profile','ProfileActionButtons'),
('kurdish_kurmanci','profile.benefit_super_likes','10 Super Like di rojê de','profile','ProfileActionButtons'),
('kurdish_kurmanci','profile.benefit_unlimited_likes','Like yên asayî yên bêsînor','profile','ProfileActionButtons'),
('kurdish_kurmanci','profile.benefit_see_likes','Bibîne kê te like kiriye','profile','ProfileActionButtons'),
('kurdish_kurmanci','profile.benefit_rewinds','5 Vegerin di rojê de','profile','ProfileActionButtons'),
('kurdish_kurmanci','profile.upgrade_premium','Bilez bo Premium','profile','ProfileActionButtons'),

-- Common keys
('english','common.submitting','Submitting...','common','general'),
('norwegian','common.submitting','Sender...','common','general'),
('german','common.submitting','Wird gesendet...','common','general'),
('kurdish_sorani','common.submitting','دەنێردرێت...','common','general'),
('kurdish_kurmanci','common.submitting','Tê şandin...','common','general')

ON CONFLICT (language_code, translation_key) DO NOTHING;
