
INSERT INTO public.app_translations (language_code, translation_key, translation_value, category, context) VALUES
-- Registration form keys (useDynamicRegistrationForm)
('english','reg.failed_load_form','Failed to load registration form. Please refresh the page.','auth','useDynamicRegistrationForm'),
('english','reg.incomplete_fields','Incomplete Fields','auth','useDynamicRegistrationForm'),
('english','reg.complete_required_fields','Please complete all required fields','auth','useDynamicRegistrationForm'),
('english','reg.validation_error','Validation Error','auth','registration'),
('english','reg.validation_error_desc','There was an error validating the form. Please try again.','auth','useDynamicRegistrationForm'),
('english','reg.registration_failed','Registration Failed','auth','registration'),
('english','reg.user_creation_failed','User creation failed. Please try again.','auth','registration'),
('english','reg.profile_creation_failed','Profile Creation Failed','auth','registration'),
('english','reg.profile_setup_failed','Your account was created but profile setup failed. Please complete your profile.','auth','registration'),
('english','reg.registration_successful','Registration Successful!','auth','registration'),
('english','reg.welcome_profile_created','Welcome to KurdMatch! Your profile has been created.','auth','registration'),
('english','reg.unexpected_error','An unexpected error occurred. Please try again.','auth','registration'),
('english','reg.photo_upload_warning','Photo Upload Warning','auth','registration'),
('english','reg.photos_upload_later','Some photos couldn''t be uploaded. You can add them later.','auth','registration'),
-- useRegistrationForm
('english','reg.photos_failed_profile_created','Some photos failed to upload. Your profile was still created successfully.','auth','useRegistrationForm'),
('english','reg.profile_complete','Profile Complete!','auth','useRegistrationForm'),
('english','reg.profile_completed_successfully','Your profile has been completed successfully.','auth','useRegistrationForm'),
('english','reg.check_email_verify','Your account has been created. Please check your email to verify your account before logging in.','auth','useRegistrationForm'),
('english','reg.failed_create_account','Failed to create account. Please try again.','auth','useRegistrationForm'),
-- ProfileCompletionWizard
('english','wizard.about_you','About You','auth','ProfileCompletionWizard'),
('english','wizard.save_failed','Failed to save your profile. Please try again.','auth','ProfileCompletionWizard'),
-- EnhancedDynamicRegistrationForm (already has some, add missing)
('english','reg.incomplete_registration','Incomplete Registration','auth','EnhancedDynamicRegistrationForm'),
('english','reg.complete_step_before_submit','Please complete all steps before submitting.','auth','EnhancedDynamicRegistrationForm'),
('english','reg.fix_errors_in','Please fix the errors in the form.','auth','EnhancedDynamicRegistrationForm'),
-- SuperAdminSetupForm
('english','admin.password_generated','Strong password generated','admin','SuperAdminSetupForm'),
('english','admin.save_password','Make sure to copy and save this password securely.','admin','SuperAdminSetupForm'),
('english','admin.copied_to_clipboard','Copied to clipboard','admin','SuperAdminSetupForm'),
('english','admin.copied_successfully','Copied successfully.','admin','SuperAdminSetupForm'),
('english','admin.copy_failed','Copy failed','admin','SuperAdminSetupForm'),
('english','admin.copy_manually','Please copy the text manually.','admin','SuperAdminSetupForm'),
('english','admin.super_admin_setup','Super Admin Setup Configuration','admin','SuperAdminSetupForm'),
('english','admin.super_admin_setup_desc','Configure your Supabase project to enable super admin functionality. Follow these steps in order.','admin','SuperAdminSetupForm'),
('english','admin.step1_credentials','Step 1: Configure Admin Credentials','admin','SuperAdminSetupForm'),
('english','admin.admin_email','Admin Email','admin','SuperAdminSetupForm'),
('english','admin.admin_password','Admin Password','admin','SuperAdminSetupForm'),
('english','common.generate','Generate','common','SuperAdminSetupForm'),
('english','admin.step2_secrets','Step 2: Add Secrets to Supabase Dashboard','admin','SuperAdminSetupForm'),
('english','admin.go_to_dashboard','Go to your Supabase Dashboard → Project Settings → Edge Functions → Secrets and add these two secrets:','admin','SuperAdminSetupForm'),
('english','admin.secret_name','Secret Name:','admin','SuperAdminSetupForm'),
('english','admin.secret_value','Secret Value:','admin','SuperAdminSetupForm'),
('english','admin.open_supabase_settings','Open Supabase Edge Functions Settings','admin','SuperAdminSetupForm'),
('english','admin.step3_deploy','Step 3: Deploy Edge Function','admin','SuperAdminSetupForm'),
('english','admin.deploy_edge_function_desc','The setup-admin Edge Function is already configured in your project. If you have the Supabase CLI installed, you can deploy it by running this command in your project directory:','admin','SuperAdminSetupForm'),
('english','admin.cli_command','CLI Command:','admin','SuperAdminSetupForm'),
('english','admin.alternative_deploy','Alternatively, you can deploy the function through the Supabase Dashboard in the Edge Functions section.','admin','SuperAdminSetupForm'),
('english','admin.step4_verify','Step 4: Verify Setup','admin','SuperAdminSetupForm'),
('english','admin.verify_setup_desc','After completing steps 1-3, refresh the admin login page. The setup should run automatically and create your admin user. You can then log in using the credentials you configured.','admin','SuperAdminSetupForm'),
('english','admin.database_requirements','Database Requirements','admin','SuperAdminSetupForm'),
('english','admin.database_requirements_desc','Ensure your database has a user_roles table with the following structure: user_id (UUID), role (TEXT), created_at (TIMESTAMP). And proper Row Level Security policies are enabled.','admin','SuperAdminSetupForm'),
-- HeroEditor
('english','admin.hero_section_content','Hero Section Content','admin','HeroEditor'),
('english','admin.hero_section_desc','Edit the main content displayed in the hero section at the top of the landing page','admin','HeroEditor'),
('english','admin.tagline','Tagline','admin','HeroEditor'),
('english','admin.tagline_desc','Short tagline displayed above the main title','admin','HeroEditor'),
('english','admin.main_title','Main Title','admin','HeroEditor'),
('english','admin.subtitle','Subtitle','admin','HeroEditor'),
('english','admin.user_count','User Count','admin','HeroEditor'),
('english','admin.user_count_desc','Number of users shown on the counter (e.g., "10,000+")','admin','HeroEditor'),

-- Norwegian translations
('norwegian','reg.failed_load_form','Kunne ikke laste registreringsskjema. Vennligst oppdater siden.','auth','useDynamicRegistrationForm'),
('norwegian','reg.incomplete_fields','Ufullstendige felt','auth','useDynamicRegistrationForm'),
('norwegian','reg.complete_required_fields','Vennligst fyll ut alle obligatoriske felt','auth','useDynamicRegistrationForm'),
('norwegian','reg.validation_error','Valideringsfeil','auth','registration'),
('norwegian','reg.validation_error_desc','Det oppstod en feil ved validering av skjemaet. Prøv igjen.','auth','useDynamicRegistrationForm'),
('norwegian','reg.registration_failed','Registrering mislyktes','auth','registration'),
('norwegian','reg.user_creation_failed','Brukeropprettelse mislyktes. Prøv igjen.','auth','registration'),
('norwegian','reg.profile_creation_failed','Profilopprettelse mislyktes','auth','registration'),
('norwegian','reg.profile_setup_failed','Kontoen din ble opprettet, men profiloppsettet mislyktes. Fullfør profilen din.','auth','registration'),
('norwegian','reg.registration_successful','Registrering vellykket!','auth','registration'),
('norwegian','reg.welcome_profile_created','Velkommen til KurdMatch! Profilen din er opprettet.','auth','registration'),
('norwegian','reg.unexpected_error','En uventet feil oppstod. Prøv igjen.','auth','registration'),
('norwegian','reg.photo_upload_warning','Fotoadvarsel','auth','registration'),
('norwegian','reg.photos_upload_later','Noen bilder kunne ikke lastes opp. Du kan legge dem til senere.','auth','registration'),
('norwegian','reg.photos_failed_profile_created','Noen bilder mislyktes. Profilen din ble likevel opprettet.','auth','useRegistrationForm'),
('norwegian','reg.profile_complete','Profil fullført!','auth','useRegistrationForm'),
('norwegian','reg.profile_completed_successfully','Profilen din er fullført.','auth','useRegistrationForm'),
('norwegian','reg.check_email_verify','Kontoen din er opprettet. Sjekk e-posten din for å bekrefte kontoen.','auth','useRegistrationForm'),
('norwegian','reg.failed_create_account','Kunne ikke opprette konto. Prøv igjen.','auth','useRegistrationForm'),
('norwegian','wizard.about_you','Om deg','auth','ProfileCompletionWizard'),
('norwegian','wizard.save_failed','Kunne ikke lagre profilen din. Prøv igjen.','auth','ProfileCompletionWizard'),
('norwegian','reg.incomplete_registration','Ufullstendig registrering','auth','EnhancedDynamicRegistrationForm'),
('norwegian','reg.complete_step_before_submit','Fullfør alle trinn før du sender inn.','auth','EnhancedDynamicRegistrationForm'),
('norwegian','reg.fix_errors_in','Vennligst rett feilene i skjemaet.','auth','EnhancedDynamicRegistrationForm'),
('norwegian','admin.password_generated','Sterkt passord generert','admin','SuperAdminSetupForm'),
('norwegian','admin.save_password','Sørg for å kopiere og lagre dette passordet sikkert.','admin','SuperAdminSetupForm'),
('norwegian','admin.copied_to_clipboard','Kopiert til utklippstavlen','admin','SuperAdminSetupForm'),
('norwegian','admin.copied_successfully','Kopiert.','admin','SuperAdminSetupForm'),
('norwegian','admin.copy_failed','Kopiering mislyktes','admin','SuperAdminSetupForm'),
('norwegian','admin.copy_manually','Vennligst kopier teksten manuelt.','admin','SuperAdminSetupForm'),
('norwegian','admin.super_admin_setup','Superadmin-oppsett','admin','SuperAdminSetupForm'),
('norwegian','admin.super_admin_setup_desc','Konfigurer Supabase-prosjektet ditt for å aktivere superadmin-funksjonalitet.','admin','SuperAdminSetupForm'),
('norwegian','admin.hero_section_content','Hero-seksjon innhold','admin','HeroEditor'),
('norwegian','admin.hero_section_desc','Rediger hovedinnholdet som vises i hero-seksjonen øverst på landingssiden','admin','HeroEditor'),
('norwegian','admin.tagline','Slagord','admin','HeroEditor'),
('norwegian','admin.tagline_desc','Kort slagord vist over hovedtittelen','admin','HeroEditor'),
('norwegian','admin.main_title','Hovedtittel','admin','HeroEditor'),
('norwegian','admin.subtitle','Undertittel','admin','HeroEditor'),
('norwegian','admin.user_count','Antall brukere','admin','HeroEditor'),
('norwegian','admin.user_count_desc','Antall brukere vist på telleren (f.eks. "10 000+")','admin','HeroEditor'),
('norwegian','common.generate','Generer','common','SuperAdminSetupForm'),

-- German translations
('german','reg.failed_load_form','Registrierungsformular konnte nicht geladen werden. Bitte aktualisieren Sie die Seite.','auth','useDynamicRegistrationForm'),
('german','reg.incomplete_fields','Unvollständige Felder','auth','useDynamicRegistrationForm'),
('german','reg.complete_required_fields','Bitte füllen Sie alle Pflichtfelder aus','auth','useDynamicRegistrationForm'),
('german','reg.validation_error','Validierungsfehler','auth','registration'),
('german','reg.validation_error_desc','Beim Validieren des Formulars ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut.','auth','useDynamicRegistrationForm'),
('german','reg.registration_failed','Registrierung fehlgeschlagen','auth','registration'),
('german','reg.user_creation_failed','Benutzererstellung fehlgeschlagen. Bitte versuchen Sie es erneut.','auth','registration'),
('german','reg.profile_creation_failed','Profilerstellung fehlgeschlagen','auth','registration'),
('german','reg.profile_setup_failed','Ihr Konto wurde erstellt, aber die Profileinrichtung ist fehlgeschlagen.','auth','registration'),
('german','reg.registration_successful','Registrierung erfolgreich!','auth','registration'),
('german','reg.welcome_profile_created','Willkommen bei KurdMatch! Ihr Profil wurde erstellt.','auth','registration'),
('german','reg.unexpected_error','Ein unerwarteter Fehler ist aufgetreten. Bitte versuchen Sie es erneut.','auth','registration'),
('german','reg.photo_upload_warning','Foto-Upload-Warnung','auth','registration'),
('german','reg.photos_upload_later','Einige Fotos konnten nicht hochgeladen werden. Sie können sie später hinzufügen.','auth','registration'),
('german','reg.photos_failed_profile_created','Einige Fotos konnten nicht hochgeladen werden. Ihr Profil wurde dennoch erstellt.','auth','useRegistrationForm'),
('german','reg.profile_complete','Profil abgeschlossen!','auth','useRegistrationForm'),
('german','reg.profile_completed_successfully','Ihr Profil wurde erfolgreich abgeschlossen.','auth','useRegistrationForm'),
('german','reg.check_email_verify','Ihr Konto wurde erstellt. Bitte überprüfen Sie Ihre E-Mail zur Bestätigung.','auth','useRegistrationForm'),
('german','reg.failed_create_account','Konto konnte nicht erstellt werden. Bitte versuchen Sie es erneut.','auth','useRegistrationForm'),
('german','wizard.about_you','Über dich','auth','ProfileCompletionWizard'),
('german','wizard.save_failed','Profil konnte nicht gespeichert werden. Bitte versuchen Sie es erneut.','auth','ProfileCompletionWizard'),
('german','reg.incomplete_registration','Unvollständige Registrierung','auth','EnhancedDynamicRegistrationForm'),
('german','reg.complete_step_before_submit','Bitte vervollständigen Sie alle Schritte vor dem Absenden.','auth','EnhancedDynamicRegistrationForm'),
('german','reg.fix_errors_in','Bitte beheben Sie die Fehler im Formular.','auth','EnhancedDynamicRegistrationForm'),
('german','admin.password_generated','Starkes Passwort generiert','admin','SuperAdminSetupForm'),
('german','admin.save_password','Stellen Sie sicher, dass Sie dieses Passwort sicher kopieren und speichern.','admin','SuperAdminSetupForm'),
('german','admin.copied_to_clipboard','In Zwischenablage kopiert','admin','SuperAdminSetupForm'),
('german','admin.copied_successfully','Erfolgreich kopiert.','admin','SuperAdminSetupForm'),
('german','admin.copy_failed','Kopieren fehlgeschlagen','admin','SuperAdminSetupForm'),
('german','admin.copy_manually','Bitte kopieren Sie den Text manuell.','admin','SuperAdminSetupForm'),
('german','admin.super_admin_setup','Super-Admin-Einrichtung','admin','SuperAdminSetupForm'),
('german','admin.super_admin_setup_desc','Konfigurieren Sie Ihr Supabase-Projekt für Super-Admin-Funktionalität.','admin','SuperAdminSetupForm'),
('german','admin.hero_section_content','Hero-Bereich Inhalt','admin','HeroEditor'),
('german','admin.hero_section_desc','Bearbeiten Sie den Hauptinhalt im Hero-Bereich oben auf der Landingpage','admin','HeroEditor'),
('german','admin.tagline','Slogan','admin','HeroEditor'),
('german','admin.tagline_desc','Kurzer Slogan über dem Haupttitel','admin','HeroEditor'),
('german','admin.main_title','Haupttitel','admin','HeroEditor'),
('german','admin.subtitle','Untertitel','admin','HeroEditor'),
('german','admin.user_count','Benutzeranzahl','admin','HeroEditor'),
('german','admin.user_count_desc','Anzahl der Benutzer auf dem Zähler (z.B. "10.000+")','admin','HeroEditor'),
('german','common.generate','Generieren','common','SuperAdminSetupForm'),

-- Kurdish Sorani
('kurdish_sorani','reg.failed_load_form','فۆرمی تۆمارکردن بارنەبوو. تکایە پەڕەکە نوێ بکەوە.','auth','useDynamicRegistrationForm'),
('kurdish_sorani','reg.incomplete_fields','خانەکان تەواو نین','auth','useDynamicRegistrationForm'),
('kurdish_sorani','reg.complete_required_fields','تکایە هەموو خانە پێویستەکان پڕ بکەوە','auth','useDynamicRegistrationForm'),
('kurdish_sorani','reg.validation_error','هەڵەی پشتڕاستکردنەوە','auth','registration'),
('kurdish_sorani','reg.registration_failed','تۆمارکردن سەرکەوتوو نەبوو','auth','registration'),
('kurdish_sorani','reg.registration_successful','تۆمارکردن سەرکەوتوو بوو!','auth','registration'),
('kurdish_sorani','reg.welcome_profile_created','بەخێربێیت بۆ کوردمەتچ! پڕۆفایلەکەت دروست کرا.','auth','registration'),
('kurdish_sorani','reg.photo_upload_warning','ئاگاداری بارکردنی وێنە','auth','registration'),
('kurdish_sorani','wizard.about_you','دەربارەی تۆ','auth','ProfileCompletionWizard'),
('kurdish_sorani','wizard.save_failed','پڕۆفایلەکەت پاشەکەوت نەکرا. تکایە دووبارە هەوڵ بدەوە.','auth','ProfileCompletionWizard'),
('kurdish_sorani','admin.password_generated','وشەی نهێنی بەهێز دروست کرا','admin','SuperAdminSetupForm'),
('kurdish_sorani','admin.copied_to_clipboard','لەبەرگرتەوە کۆپی کرا','admin','SuperAdminSetupForm'),
('kurdish_sorani','admin.copy_failed','کۆپی کردن سەرکەوتوو نەبوو','admin','SuperAdminSetupForm'),
('kurdish_sorani','admin.hero_section_content','ناوەڕۆکی بەشی سەرەکی','admin','HeroEditor'),
('kurdish_sorani','admin.tagline','دەقی کورت','admin','HeroEditor'),
('kurdish_sorani','admin.main_title','ناونیشانی سەرەکی','admin','HeroEditor'),
('kurdish_sorani','admin.subtitle','ژێرناونیشان','admin','HeroEditor'),
('kurdish_sorani','admin.user_count','ژمارەی بەکارهێنەران','admin','HeroEditor'),
('kurdish_sorani','common.generate','دروستکردن','common','SuperAdminSetupForm'),

-- Kurdish Kurmanji
('kurdish_kurmanji','reg.failed_load_form','Forma tomarkirinê bar nebû. Ji kerema xwe rûpelê nû bike.','auth','useDynamicRegistrationForm'),
('kurdish_kurmanji','reg.incomplete_fields','Qadên netemam','auth','useDynamicRegistrationForm'),
('kurdish_kurmanji','reg.complete_required_fields','Ji kerema xwe hemû qadên pêwîst dagirin','auth','useDynamicRegistrationForm'),
('kurdish_kurmanji','reg.validation_error','Çewtiya pejirandinê','auth','registration'),
('kurdish_kurmanji','reg.registration_failed','Tomarkirin bi ser neket','auth','registration'),
('kurdish_kurmanji','reg.registration_successful','Tomarkirin bi ser ket!','auth','registration'),
('kurdish_kurmanji','reg.welcome_profile_created','Bi xêr hatî KurdMatch! Profîla te hate afirandin.','auth','registration'),
('kurdish_kurmanji','reg.photo_upload_warning','Hişyariya barkirina wêneyan','auth','registration'),
('kurdish_kurmanji','wizard.about_you','Der barê te de','auth','ProfileCompletionWizard'),
('kurdish_kurmanji','wizard.save_failed','Profîla te nehat tomarkirin. Ji kerema xwe dîsa biceribîne.','auth','ProfileCompletionWizard'),
('kurdish_kurmanji','admin.password_generated','Şîfreya bihêz hate çêkirin','admin','SuperAdminSetupForm'),
('kurdish_kurmanji','admin.copied_to_clipboard','Li clipboardê hat kopîkirin','admin','SuperAdminSetupForm'),
('kurdish_kurmanji','admin.copy_failed','Kopîkirin bi ser neket','admin','SuperAdminSetupForm'),
('kurdish_kurmanji','admin.hero_section_content','Naveroka beşa sereke','admin','HeroEditor'),
('kurdish_kurmanji','admin.tagline','Gotina kurt','admin','HeroEditor'),
('kurdish_kurmanji','admin.main_title','Sernavê sereke','admin','HeroEditor'),
('kurdish_kurmanji','admin.subtitle','Binsernavê','admin','HeroEditor'),
('kurdish_kurmanji','admin.user_count','Hejmara bikarhêneran','admin','HeroEditor'),
('kurdish_kurmanji','common.generate','Çêkirin','common','SuperAdminSetupForm')
ON CONFLICT (language_code, translation_key) DO NOTHING;
