// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqgjfxilcpqosmccextj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxZ2pmeGlsY3Bxb3NtY2NleHRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2ODI4ODAsImV4cCI6MjA1ODI1ODg4MH0.tBXkDKyVcGfQyHXeiGsv5gtHNSCGATMw_0-axVP7hwM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});